bin/jest.js
This is an updated PR using the most recent jest bin from master (from #111), and proposed solution to #110. I do not have the foggiest notion on how to write a test for this, and couldn't find any bin tests anyway...
I have manually checked on Windows 8.1, using the [getting started](https://facebook.github.io/jest/docs/getting-started.html#content) code as the test code and running:
- the tests with the globally installed jest-cli (`0.2.1`)
- then `npm link` this branch and run the tests again.
The problem is present in the most recent version of jest in my example test, and this change resolves it. The added `return`s prevent further code execution quite nicely it seems. In all most attempts to check it (`--help` and missing local install), nothing past the return ran (I would hope …
=> use process exit listener instead of process.exit()

src/JSDomEnvironment.js, src/lib/FakeTimers.js, src/lib/__tests__/FakeTimers-test.js
Fix for #213, adds ```setImmediate``` to the set of mocked timer function in FakeTimers.
=> #213 Added SetImmediate mock to FakeTimers.

package.json
Please bump harmonize to support running in node v0.12 and iojs. This request obviously does not attempt to address all issues to fully support node v0.12 or iojs, but does allow users to install and run jest-cli in those environments. Tested in node v0.10.36, node v0.12.0, and iojs v1.2.0.
Fixes facebook/jest/issues/235. 
Part of the work required for facebook/jest/issues/243. 
See dcodeIO/node-harmonize/issues/1.
=> Bump harmonize to 1.4.0

bin/jest.js, src/HasteModuleLoader/HasteModuleLoader.js, src/HasteModuleLoader/__tests__/HasteModuleLoader-NODE_PATH-test.js, src/HasteModuleLoader/__tests__/HasteModuleLoader-getTestEnvData-test.js, src/jest.js, src/lib/utils.js
config.testEnvData makes it possible to specify data that should be made available to the test environment via jest.getTestEnvData().
(cc @zpao )
=> Add config.testEnvData (and --testEnvData=<<json string>>)

docs/TutorialjQuery.md
"innter" -> "inner"
"we'd it expect" -> "we'd expect"
@zpoa so sorry to have put this in the wrong place. this makes much more sense. thanks for the correction :)
originally #284
=> docs: fix typo

docs/TutorialCoffeeScript.md
Fix type: "builtin" -> "built-in"
originally: #285
=> docs: fix typo "builtin" -> "built-in"

website/package.json
I followed the instructions in website/README.md:
- Clone jest repo
- `cd website`
- `npm install`
- `npm start`
- Go to http://localhost:8080/jest/index.html
```
Error: Error: ERROR RENDERING PAGE ON SERVER:
<mapped error>
TypeError: Cannot read property '__reactAutoBindMap' of undefined
Please report this to https://github.com/chjj/marked.
at Constructor (evalmachine.null:null:15)
at Parser.tok (evalmachine.null:null:14)
at Parser.parse (evalmachine.null:null:19)
at Function.Parser.parse (evalmachine.null:null:17)
at marked (evalmachine.null:null:19)
at React.createClass.render (evalmachine.null:null:32)
at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (evalmachine.null:null:34)
at ReactCompositeComponentMixin._renderValidatedComponent …
```
=> Website build is broken

src/jasmineTestRunner/JasmineReporter.js, src/jasmineTestRunner/__tests__/JasmineReporter-test.js
Summary:
Jest may appear to hang (for dozens of seconds, up to minutes) when
printing failed test results.
An example of the kind of failure output that can trigger this condition
is a dump of a very large JS object and a short string. All of the time
is spent in the diffing algorithm that we use to color-highlight the
differences between the expected and actual value. This scenario is one
of the worst cases for the underlying Myers LCS diff algorithm, which
runs in O(n+d^2) time (where "d" is the length of the edit script
between the two strings).
This commit ameliorates the worst case scenario by switching to a
line-level diff whenever newlines are present in either string. There
will still be pathological cases that can be very slow (really huge
multi-line diffs, or very long …
=> Speed up output for failing tests

src/lib/__tests__/moduleMocker-test.js, src/lib/moduleMocker.js
Forwarding a function's `name` property to the mocked function.
=> Forwarding a function's `name` property to the mocked function.

examples/react/CheckboxWithLabel.js, examples/react/__tests__/CheckboxWithLabel-test.js
Removing this since React >= 0.12.0 does not require it.
=> Remove JSX pragma from React example

docs/TutorialCoffeeScript.md
Jest didn't work for my coffeescript project as written. Through some debugging I found `"moduleFileExtensions"`, which fixed my problem and allowed my coffee files to be tested.
I have submitted a CLA.
=> include `"moduleFileExtensions"` in CoffeeScript Tutorial

bin/jest.js, src/DefaultTestReporter.js, src/jasmineTestRunner/JasmineReporter.js, src/jasmineTestRunner/jasmineTestRunner.js, src/jest.js, src/lib/utils.js
Ability to get plain output for better debug logs (that avoids having in logs things like "[0m[1m" from the highlighter).
=> Add --noHighlight option

package.json, src/CoverageCollector.js
I noticed jest is only using `template` and using a really old version so replaced it with just the template dep.
=> Use `lodash.template`.

src/lib/jsdom-compat.js
When updating JSdom to the newer version that is compatible with node, 3.1.2, `npm test` will throw some errors.
```
FAIL  HasteModuleLoader/__tests__/HasteModuleLoader-genMockFromModule-test.js
TypeError: Cannot call method 'appendHtmlToDocument' of undefined
at setInnerHTML (/Users/fabs/Dev/fb/jest/node_modules/jsdom/lib/jsdom/level1/core.js:48:22)
at HTMLDocument.inheritFrom.write (/Users/fabs/Dev/fb/jest/node_modules/jsdom/lib/jsdom/level1/core.js:1706:7)
at Object.exports.jsdom (/Users/fabs/Dev/fb/jest/node_modules/jsdom/lib/jsdom.js:59:7)
at new JSDomEnvironment (/Users/fabs/Dev/fb/jest/src/JSDomEnvironment.js:32:47)
at TestRunner.runTest (/Users/fabs/Dev/fb/jest/src/TestRunner.js:322:13)
at onMessage (/Users/fabs/Dev/fb/jest/src/TestWorker.js:50:25)
at Socket.<anonymous> …
```
=> Fixes Jest tests when using it with newer versions of jsdom.

src/__tests__/TestRunner-fs-test.js
Fix to 4 jest unit tests at `TestRunner-fs-test.js` that failed on Windows. e.g.:
- Expected: {
| 0: '__testtests__\test.js'
} toEqual: {
| 0: '__testtests__/test.js'
}
But `HasteModuleLoader-requireMock-test.js` still has a failing test, but it's not related to paths, and I couldn't fix it:
HasteModuleLoader › requireMock › it just falls back when loading a native module
- Expected '%1 is not a valid Win32 application.
c:\Prog\Others\jest\protron\src\HasteModuleLoader\__tests__\test_root\NativeModule.node' to contain 'NativeModule.node: file too short'.
=> Windows fix: path.normalize for TestRunner-fs-test.js

src/HasteModuleLoader/HasteModuleLoader.js, src/HasteModuleLoader/__tests__/HasteModuleLoader-requireModule-test.js
Fixes #228.
Advice for how to unit test this welcome. I added `JSON` to the environment mock to make sure existing tests pass, but couldn't figure out how to create a new mocked environment that will let me assert that the issue described in #228 is fixed.
=> Require JSON files from same environment as modules

vendor/jasmine/jasmine-1.3.0.js
This was fixed in Jasmine 2.x, but it seems we cannot easily upgrade Jasmine?
This just pulls in https://github.com/jasmine/jasmine/blob/master/src/core/PrettyPrinter.js#L53 to make the pretty printer work for objects created with `Object.create(null)`.
Without that change, Jasmine throws the error
```
- TypeError: Object object has no method 'hasOwnProperty'
at jasmine.PrettyPrinter.iterateObject (...)
...
```
when trying to pretty print such objects.
=> Make pretty printer work for objects without prototype

src/lib/utils.js
Update #99, if we still want it.
cc @jeffmo
=> Benjamn preprocessor ignore patterns

src/lib/utils.js
Resets _contentCache in readAndPreprocessFileContent, if file mtime was changed
Needed for gulp watch. Bug described in issue:  #222
=> Module load caching file mtime check

src/TestRunner.js
On a dual core machine, we had a Jest build with 33 files that took 138 seconds to run. After playing with `maxWorkers`:
maxWorkers | time to run 
----------------- | -----------
1 | 138 
2 | 99 
3 | 100 
4 | 102 
I think it's safe to assume that most of the configurations will benefit of running the tests more parallelised.
=> Update default maxWorkers to be number of CPUs

src/HasteModuleLoader/HasteModuleLoader.js, src/TestRunner.js, src/jasmineTestRunner/jasmineTestRunner.js
This gives the two setup scripts `setupTestFrameworkScriptFile` and `setupEnvScriptFile` access to the jest runtime of the test.
=> Pass jest runtime to test setup scripts (closes #108)

src/lib/FakeTimers.js
Closes issue #356.
The `this._cancelledImmediates` should be updated from the `runAllImmediates` prior calling the callback, since the callback may throw, and the map won't be updated (which will cause throwing from this callback when it will be ran from the main scheduled `setImmediate`).
=> Fix setImmediate and nextTick handling

docs/API.md, src/HasteModuleLoader/HasteModuleLoader.js
This will make it easier to use arrow functions when writing unit tests that have custom matchers:
```js
beforeEach(() => {
jest.addMatchers({
toBeOne() {
return this.actual === 1;
}
});
});
```
=> Implement `addMatchers` shortcut on `jest`

package.json, src/jest.js
For a non-TTY session do `--noHighlight` mode by default.
=> noHighlight option default to not TTY process

src/lib/utils.js
The use-case here is that if we want to do caching inside of the
preprocess script, then we want to include the jest configuration to
create a cache-key.
=> Pass down jest config to preprocess script

src/lib/__tests__/moduleMocker-test.js, src/lib/moduleMocker.js
Fixes https://github.com/facebook/jest/issues/332
It's not clear to me if/how I could add a test for this. It depends on attempting to mock a module that exports an ES6 class or instance. If it needs a test to be merged and you can provide some guidance I'll add it.
> There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.
I'm not sure `scan` is an ideal name, but I don't have anything better at the moment.
=> Scan for ES6 methods in moduleMocker.js

src/lib/utils.js
Cache never worked because of this.
=> Check actual mtime equality by calling 'mtime'

bin/jest.js, src/DefaultTestReporter.js, src/TestRunner.js, src/jasmineTestRunner/JasmineReporter.js, src/jest.js, src/lib/testLogger.js, src/lib/utils.js
Add a `--verbose` config flag to pretty print the test suite individually
Relates to issue #4 and takes into account some of the suggestions from pull #92 
contributors include myself @PhilVargas and @arcin
called using `jest --verbose`
example of when the test suite passes:
example of when the test suite fails:
=> Verbose test results

docs/API.md, src/HasteModuleLoader/HasteModuleLoader.js, src/HasteModuleLoader/__tests__/HasteModuleLoader-currentTestPath-test.js, src/TestRunner.js
It is useful to have the current test filename available in the test reporter environment. For instance, we use the JUnitReporter with our CI server, and because each test file is run in its own process, this enables us to output a results file named for each test:
```javascript
// This script enables JUnit XML output by the test runner to be parsed and reported by Bamboo
jasmine.VERBOSE = true;
require('jasmine-reporters');
// massage the test file path into an output filename
var relativeTestPath = 'test' + _jestTestFilePath
.replace(process.cwd(), '')
.replace(/\//g, '.')
.replace('__tests__.', '')
.replace(/\.jsx?$/, '');
var reporter = new jasmine.JUnitXmlReporter('test_results', true, true, relativeTestPath, true);
jasmine.getEnv().addReporter(reporter);
```
I looked a bit into how …
=> Make currently-executing test's file path available as jest.currentTestPath()

examples/react-es6/__tests__/CheckboxWithLabel-test.js
The test of the ES6 example is broken due to jest automocking.
ES5 `require` corresponding to ES6 `import` are hoisted during the compilation. So the `CheckboxWithLabel` module is mocked because the require is placed before `jest.dontMock`.
See [babel-jest#16](https://github.com/babel/babel-jest/issues/16)
=> Prevent module to be hoisted before jest.dontMock in ES6 example

bin/jest.js, src/DefaultTestReporter.js, src/TestRunner.js, src/jest.js
Addresses issue #127 to add a flag to abort the test suite after the first failing test file occurs.
- invoke the fail-fast flag by calling jest with the `--bail` options or `-b` alias. 
- if the flag is present and a test fails, exit the worker process from the `DefaultTestReporter`
after calling the cleanup method `onRunComplete` in order to print the test results before abort
- calculate the overall runTime by saving the startTime (instead of final runTime) in `aggregatedResults`. this allows us to calculate the runTime anywhere `aggregatedResults` is available. I.e. to print the overall run time during any individual test, instead of after all the tests have run.
I'm currently having an issue on jest 0.4.5 (from facebook/jest/master) that is forcing noHighlight to always be called. I …
=> Add failFast flag to abort test suite after first failure

src/lib/__tests__/moduleMocker-test.js, src/lib/moduleMocker.js
Don't mock non-enumerable accessors yet: they may throw, and fail in the mocker, when the mocker tries to get the value by the slot. Fixes #389, #380.
=> Don't mock non-enum accessors

package.json, src/jasmineTestRunner/jasmineTestRunner.js
We shouldn't be iterating over arrays with for..in. This cleans it up
and ensures that we're treating arrays like arrays. It has the side
effect, for Facebook, of allowing us to use our own Arrray.prototype.es6
polyfill without warnings.
=> jasmineTestRunner: eliminate the use of for..in on arrays

src/lib/FakeTimers.js, src/lib/__tests__/FakeTimers-test.js
Fixes #391.
We should run immediate calls in `runOnlyPendingTimers`.
=> Run immediate calls in runOnlyPendingTimers

src/lib/FakeTimers.js
Immediate calls can be enqueued during handling of timers, we should run these dynamically added immediates as well.
=> Run dynamic immediates during runAllTimers

src/DefaultTestReporter.js, src/lib/testLogger.js
This one prints test path and time to be consistent in the header output in the short mode.
=> Print test path and time in verbose mode

src/DefaultTestReporter.js, src/lib/testLogger.js
touch up some of the changes per comments of #397 
- change reporter logic to always print the results header -> if verbose print suite map as well. changed from if verbose -> print header + suite map else print header
- added a check to see if there were any postSuiteHeaders prior to logging it to avoided printed an extra newline character at the end of the verbose run and prior to the `x tests passed` line
=> Verbose logger touchup

src/HasteModuleLoader/HasteModuleLoader.js
If `main` isn't in package.json then `path.join` will throw when it gets `undefined`. We should fall through in that case to the next step which tries to read `index.js`
=> Check that main exists in a package.json before using it.

src/TestRunner.js
This is an update to the TestRunners gather files to include in coverage process. In testing we have found that node_modules were being included in the generated coverage report, which was throwing off our coverage numbers. Our setup is as follows;
app/
package.json
node_modules/
configs.js
app.js
specific-application-directory/
=> Fix to correctly filter out node_modules from coverage report

.jshintrc, package.json, src/HasteModuleLoader/HasteModuleLoader.js, src/HasteModuleLoader/__tests__/HasteModuleLoader-NODE_PATH-test.js, src/HasteModuleLoader/__tests__/HasteModuleLoader-genMockFromModule-test.js, src/HasteModuleLoader/__tests__/HasteModuleLoader-getTestEnvData-test.js, src/HasteModuleLoader/__tests__/HasteModuleLoader-requireMock-test.js, src/HasteModuleLoader/__tests__/HasteModuleLoader-requireModule-test.js, src/HasteModuleLoader/__tests__/HasteModuleLoader-requireModuleOrMock-test.js, src/TestRunner.js, src/TestWorker.js, src/__tests__/TestRunner-test.js, src/jasmineTestRunner/JasmineReporter.js, src/jest.js, src/lib/utils.js
The [bluebird](https://github.com/petkaantonov/bluebird) seems to have better performance than [Q](https://github.com/kriskowal/q).
An [issue](https://github.com/petkaantonov/bluebird/issues/661) was noticed after the switch, which is solved locally, but probably Bluebird will fix it at library level.
=> Replace Q with Bluebird

docs/ManualMocks.md
Added examples of where to put the __mocks__ directory so mocked objects get auto-loaded.
=> Update ManualMocks.md to clarify how __mocks__ directories work.

src/jasmineTestRunner/JasmineReporter.js, src/jasmineTestRunner/__tests__/JasmineReporter-test.js
Previously, exceptions with newlines in messages didn't get highlighted properly. Only the last line of the message would be highlighted. This fixes that and adds a unit test.
In addition to running the test, I played around with the functionality by messing with things in the examples folder.
cc @DmitrySoshnikov
=> Fix jest highlighting on multiple lines

src/lib/utils.js
Disk caching layer is added. Caching is done by default, unless explicitly disabled via the `preprocessCachingDisabled` config option. Preprocessor script may also export `getCacheKey` method,  in case of custom hashing or invalidating logic for a cache key.
=> Preprocessor disk cache

src/lib/utils.js
Fix error with not registering `preprocessCachingDisabled` as a config key
=> Fix error with not registering preprocessCachingDisabled as a config key

bin/jest.js
We're going to merge `0.5.x` to master, and make the legacy `0.4.x` if people still want to run Jest on Node `0.10.x`. This adds a deprecation message to the CLI.
=> Add legacy Node deprecation message

src/lib/FakeTimers.js, src/lib/__tests__/FakeTimers-test.js
Fix clearing a timer from within another timer resulting in `TypeError: Cannot read property 'type' of undefined`.
=> No longer try to run cleared timers in `runOnlyPendingTimers`

bin/jest.js
ref #425  The notice message isn't as clear to people unaware of io.js and node merger.
=> Clarify new io.js compatibility message

README.md, docs/API.md, src/lib/utils.js
It is already being checked for throughout the `DefaultTestReporter.js` file. Here are the uses:
[Line 32](https://github.com/facebook/jest/blob/master/src/DefaultTestReporter.js#L32)
[Line 76](https://github.com/facebook/jest/blob/master/src/DefaultTestReporter.js#L76)
[Line 84](https://github.com/facebook/jest/blob/master/src/DefaultTestReporter.js#L84)
[Line 113](https://github.com/facebook/jest/blob/master/src/DefaultTestReporter.js#L113)
Utils.js did not report is a supported option so I enabled it.
=> Adding Verbose as a supported config option

src/lib/utils.js
Currently, specifying a non-empty `preprocessorIgnorePatterns` configuration will fatal because `String.prototype.test` is not a valid function.
=> Fix fatal when using `preprocessorIgnorePatterns`

package.json, src/TestRunner.js
The `cacheKey` introduced in https://github.com/facebook/jest/pull/419, in the default case, relies on the stringified value of `config`. Since most (if not all) of the config values are up the prototype (so not own properties of config), they don't get serialized by `JSON.stringify`, which kinda negates the purpose of using the config in the cache key.
I considered changing the hashing instead to use `JSON.stringify(config.__proto__)` or a do a stringify up each level of the prototype chain – but this seemed like the most straight forward solution.
The `readAndPreprocessFileContent` function should probably pass `scriptPreprocessor` and `getCacheKey` a copy of the config too, to prevent accidental mutation. I can submit another PR for that.
=> Clone config instead of subclassing it

src/lib/moduleMocker.js
=> Add a check for `hasOwnProperty()`

docs/TutorialReact.md
Given that react-tools is deprecated, and react is using babel. I've updated the docs to show how to use babel. This is essentially a copy of [babel-jest's implementation](https://github.com/babel/babel-jest/blob/master/index.js)
=> Update TutorialReact.md to use babel instead of react-tools

README.md, docs/API.md
Clarify the documentation by indicating that `expect` is a globally injected function. This will help newcomers to understand how it works, and projects like [globals](/sindresorhus/globals) to list globally defined variables (see sindresorhus/globals#46).
=> Add `expect` to the list of globally injected variables

src/lib/utils.js
This fixes internal issues at FB that writes to a shared tmp file.
I also changed the name of the generated file – this should make debugging for jest developers easier and has no user impact:
`fileName_<hash>.js` instead of `<hash>_fileName.js`
=> Move preprocess cache into the `cacheDir` provided by the config.

src/lib/moduleMocker.js
Bound functions now are named "bound ${name}", which is not a valid function identifier. To replicate this name in the module mocker, we can strip off "bound " and call `bind()` on the generated function instead.
Fix #488
=> [Node 4] Handle bound functions

src/lib/utils.js
If `/tmp/jest_preprocess_cache` already exists by different owner then preprocess-cache raises `chmodSync` permission error.
e.g. When many users run Jest on a shared-server, raise following error:
```
Error: /<snip>/node_modules/babel-jest: EPERM, operation not permitted '/tmp/jest_preprocess_cache'
at Object.fs.chmodSync (fs.js:833:18)
at Object.readAndPreprocessFileContent (/<snip>/node_modules/jest-cli/src/lib/utils.js:392:12)
at Loader._execModule (/<snip>/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:209:11)
at Loader.requireModule (/<snip>/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:914:12)
at jasmineTestRunner (/<snip>/node_modules/jest-cli/src/jasmineTestRunner/jasmineTestRunner.js:292:16)
at …
```
=> Fix chmod error when different owner's dir exists in preprocess-cache

package.json
The patch for jest has been published as 1.10.0 so we don't need to download coffee-script from GitHub each time anymore.
=> [CoffeeScript] Update coffee-script to ^1.10.0

README.md, docs/API.md
Add missing preprocessCachingDisabled option to docs
=> doc(config): add preprocessCachingDisabled option

src/lib/utils.js
This PR reverts https://github.com/facebook/jest/pull/491. The change introduced in that PR introduced a race condition into the creation of the preprocess cache directory, which can result in an unhandled `EEXIST` error. As far as I can see, the change made in that PR isn't required if the user is managing their own cache directory (which is easier to do now following https://github.com/facebook/jest/pull/470).
=> Fix preprocess cache directory creation race condition

src/lib/utils.js
Adds the `testPathPattern` key to the whitelisted keys in `utils.normalizeConfig()`
Read #501 for explanation of the issue
`$ npm test` should pass
=> Added testPathPattern to whitelisted normalizeConfig keys

src/DefaultTestReporter.js, src/lib/utils.js
Improves Jest's failure stack traces in the following ways:
- Fix noise filtering (which excludes Jasmine and Jest libraries).
- Use relative paths (same logic used for test paths).
- Support filtering "eval" stack traces.
=> Improve Failure Stack Traces

src/HasteModuleLoader/HasteModuleLoader.js
If a project that you're trying to run Jest on is a symlink, all modules will be relative to the symlink. However, the configuration paths (e.g. `<rootDir>/...`) are real paths. This can cause, for example, modules that are configured to be unmocked (via `unmockedModulePathPatterns`) to be mocked.
This fixes the problem by ensuring that we resolve the module path used to resolve all modules.
=> Fix module paths for project symlinks

src/HasteModuleLoader/HasteModuleLoader.js
I have no idea what's going on, but the Jest symlink situation needs serious reworking. Internally at Facebook, ecf8ad709fbce8acb0e54ee5f8a17ea52e9e1bd4 is causing problems.
I'm reverting the previous fix and simply making Jest unmock a module path if either its real path or symlink path matches a path in the unmock list.
=> Improve Symlink Fix

src/TestRunner.js
On verbose mode log error shows "Cannot read property 'length' of undefined"
=> Issue #517 Bug on log error when verbose=true

src/lib/moduleMocker.js
I mistakenly said that we couldn't use strict mode on this module.
Adding 'use strict' to it and removing the comment that explained why it wasn't used.
=> Apply strict mode on moduleMocker.js

package.json, src/HasteModuleLoader/HasteModuleLoader.js
If you have a scoped package, its name in package.json looks like `@scope/pkg` which messes up the mkdir call since it doesn't expect there to be an extra directory for the Haste cache.
Fixes https://github.com/facebook/jest/issues/446
Test Plan: Use jest in a project that has a scoped name.
=> [npm] Add support for npm scoped packages

package.json, src/Console.js, src/DefaultTestReporter.js, src/TestRunner.js, src/TestWorker.js, src/jasmineTestRunner/JasmineReporter.js, src/lib/__tests__/promisify-test.js, src/lib/promisify.js
* More reliable (uses IPC instead of stdin/out)
* No more weird messaging issues (unable to parse, message order, etc)
* Allows (currently, up to 2) initialization errors per worker
* Console logs can appear as they are executed (not buffered)
* Also means that they console logs appear even when there is initialization errors
* Simplifies console and logger implementation
* Easier for debugging (even if the program crashes you can still see your logs)
* Opens up opportunities for future more involved inter-worker communication (say sharing mocking work)
cc @cpojer @DmitrySoshnikov
=> Replace node-worker-pool with node-worker-farm

bin/jest.js, src/IstanbulTestReporter.js, src/TestRunner.js, src/jest.js, src/lib/utils.js
I've used `config.useStderr` internally to divert stdout to stderr
so we can talk to the caller via json. Instead of having a one-off
config option, I'm making this an actual option with a consistent
behaviour.
Had to convert the `InstanbulTestReporter` into a proper class
so it can do proper inheritence.
cc @cpojer @DmitrySoshnikov
=> Make useStderr a proper config value

src/jasmineTestRunner/JasmineReporter.js
I *think* I understand what's going on and did this right but maybe not…
While v8 currently supports `Promise.defer`, it won't always.
=> Promise.defer shouldn't exist, don't use it

docs/TutorialReact.md, examples/react/__tests__/CheckboxWithLabel-test.js, examples/react/package.json
React/addons is deprecated as is usage of findDOMNode from react. ReactDOM is now used.
=> Updated testing docs

examples/react/package.json
Updated the npm dependencies in examples/react. Previously didn't include jest-cli. Also updated documentation for the React Tutorial page to update these changes. Example previously would not work because it omitted "<rootDir>/node_modules/fbjs" from the unmockedModulePathPatterns section.
=> Updating React documentation and npm dependencies

examples/manual_mocks/__tests__/FileSummarizer-test.js
Fix the failing manual_mocks example by explicitly mocking the `fs`-module.
Fixes #541. Fixes #375.
=> Fix manual mocks example

website/server/server.js
Looks like the only change to pick up from Relay here was the looser check for argv. It seems to contain the full path to the node executable now, not just node.
=> Fix website site script so it runs in node 4

examples/react/.babelrc, examples/react/CheckboxWithLabel.js
- in order to use 'babel-plugins-*' to parse the syntax, we can use
'babel-preset-*' packages that we have already installed.
for using 'babel-preset-*' packages you need to specify it in the
.babelrc file as "presets".
(Look here: https://babeljs.io/docs/plugins/#presets)
otherwise if you want to use 'plugins' and parse the syntax;
you have to install 'babel-plugin-*' packages.
(Look here: https://babeljs.io/docs/plugins/)
- 'export default *' changed to 'module.exports = *' due to
syntax error.
=> fix(react example): correct .babelrc and example

package.json
Adds missing dev dependencies `graceful-fs` & `mkdirp` which are used in `./build/test.js` but are not in `package.json`
=> fix: add missing dev dependencies graceful-fs & mkdirp

packages/jest-cli/src/lib/formatTestResults.js, types/TestResult.js
Flowify formatTestResults. 
I couldn't figure out what CodeCoverageResult, CodeCoverageReporter, and CodeCoverageFormatter should be. So I purposely left them inprecise.
=> Flowify formatTestResults

packages/jest-snapshot/package.json, packages/jest-snapshot/src/SnapshotFile.js
Enabling the jsx-like extension for ReactTestComponent to pretty-format
=> pretty format ReactTestComponents as jsx-like by default

README.md, docs/GettingStarted.md
I just wanted to fix the broken link and additional changes to the README appear when I run `npm start` in the website directory. I guess it is part of the documentation generation process.
=> Fix broken link to React tests and re-generate documentation.

packages/jest-config/src/normalize.js, packages/jest-util/src/index.js
This is super ugly, but it's Good Enough™ for now.
The main issue is that `replacePathSepForRegex` doesn't understand if a `\` is actually part of a file path (eg. `C:\src\jest\`), or if it's escaping a regex character (eg. `\.` to match a dot). This means that it incorrectly escapes all `\` characters on Windows, meaning a regex containing `\.js` to match *.js files will never match anything as it'll look for a literal "\.js" in the path.
The 'nicest' hack I could think of was to only escape `\` if it's not followed by `.`. By far the most common escape I've seen is `\.` to match a dot (ie. `\.js` to match .js files) so this is just an escape hatch to allow `\.` (instead of escaping it like `\\.`), while continuing to escape `c:\foo` as expected.
Things will actually work totally fine if …
=> Fix escaping of "\." on Windows

flowlibs/console.js, package.json, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/jest.js, packages/jest-config/src/reporters/VerboseLogger.js, packages/jest-environment-jsdom/package.json, packages/jest-runtime/src/__tests__/Runtime-cli-test.js, packages/jest-runtime/src/cli/index.js, packages/jest-util/package.json, packages/jest-util/src/Console.js, scripts/watch.js
* Add more npm scripts
* update npm dependencies
* watch now builds all and recovers from errors
* code style cleanup
* return proper promise from src/jest.js
=> Smaller cleanups:

packages/jest-snapshot/src/SnapshotFile.js, packages/jest-snapshot/src/__tests__/SnapshotFile-test.js
Before
exports[`foo`] = `<Foo
bar="baz"
/>`;
After
exports[`foo`] = `
<Foo
bar="baz"
/>
`;
I expect this to be much easier to read and see in the diff view.
=> Pretty print React components on new line

docs/API.md, packages/jest-config/src/__tests__/normalize-test.js, packages/jest-config/src/defaults.js, packages/jest-config/src/normalize.js, packages/jest-resolve/package.json, packages/jest-resolve/src/index.js, packages/jest-runtime/src/__tests__/jest-resolve-test.js, packages/jest-runtime/src/__tests__/test_root/node_modules/jest-resolve-test/browser.js, packages/jest-runtime/src/__tests__/test_root/node_modules/jest-resolve-test/node.js, packages/jest-runtime/src/__tests__/test_root/node_modules/jest-resolve-test/package.json, types/Config.js
Fixes #61 
This change makes Jest respect the `"browser"` field when resolving packages using [browser-resolve](https://www.npmjs.com/package/browser-resolve).
A consideration to make when evaluating this PR is what to do for server side tests as the wrong module will be resolved in this case. I think the best option would be adding a `browser: <bool>` field to Jest configs? Thoughts?
=> Respect package.json 'browser' field when resolving dependencies

packages/jest-config/src/normalize.js, packages/jest-config/src/reporters/VerboseLogger.js, packages/jest-jasmine2/package.json, packages/jest-jasmine2/src/reporter.js, types/TestResult.js
Records the time taken by each spec in a test suite, and prints them when in verbose mode. This is helpful in figuring out why your tests are slow.
Microsecond timing is used so that times will be rounded to nearest rather than truncated.
=> Report run times of individual specs in verbose mode.

examples/jquery/__tests__/displayUser-test.js
Minor spelling errors
inner instead of 'inter'
we'd expect it to instead of we'd it expect
=> spelling errors

integration_tests/__tests__/verbose-test.js, integration_tests/verbose_logger/__tests__/verbose-test.js, integration_tests/verbose_logger/package.json, packages/jest-config/src/reporters/VerboseLogger.js, packages/jest-config/src/reporters/__tests__/VerboseLogger-test.js, packages/jest-jasmine2/vendor/jasmine-2.4.1.js, packages/jest-util/src/formatFailureMessage.js
Fixes #1121.
cc @dmitriiabramov I think we should redo how we print failure messages. Errors should be printed in-line with the verbose messages instead of printing all the tests and then printing all the failures. Should be a relatively simple change in DefaultTestReporter.
=> Print top level `it` or `test` calls in Jest.

scripts/test.js
we already have them in `integration_tests`
=> remove `json` and `verbose` tests from `scripts/test.js`

package.json, packages/jest-cli/src/SearchSource.js, packages/jest-mock/src/index.js, packages/jest-snapshot/src/SnapshotFile.js
not sure what exactly is going on there, i'm pretty sure travis should've automatically installed `0.28.0`, but it wasn't passing on my laptop
=> flow-bin@0.28.0

packages/jest-cli/src/cli/getJest.js
Fixes #1293 
Running `jest` from a a location other than `<package>/node_modules` will no longer exit with a non-zero exit code, but it will highlight the warning message when the tests complete.
=> non-local jest-cli run will not fail, but will show big red warning

packages/jest-cli/src/TestWorker.js, packages/jest-cli/src/__tests__/SearchSource-test.js, packages/jest-cli/src/jest.js, packages/jest-haste-map/src/index.js, packages/jest-resolve/src/index.js, packages/jest-runtime/src/__mocks__/createRuntime.js, packages/jest-runtime/src/cli/index.js, packages/jest-runtime/src/index.js
to `Runtime.create(Resolver|HasteMap)`.
This way `jest-haste-map` and `jest-resolve` don’t require knowledge of Jest’s configs and can be used more clearly outside of Jest.
=> Move `Resolver.create` and `HasteMap.create`

packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/lib/formatTestResults.js, packages/jest-cli/src/reporters/NotifyReporter.js, packages/jest-cli/src/reporters/SummaryReporter.js, packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/reporter.js, types/TestResult.js
moving snapshot logic from reporters to the core of jest.
Decision of whether the test run is successful or not is based on three factors
1. Are there any test failures?
2. Were any snapshots updated/removed/unused?
3. Did any of the reporters throw? (the only case right now is coverage threshold)
**1** and **2** have to be captured in jest itself and not anywhere else, because it's the core functionality of jest. Because we had **2** spread across multiple files, things kept breaking and it especially hard to integrate it with the internal runner.
after this change:
1. Test results are generated **only** in test runner (initially in jasmine though)
2. Reporters only consume results and don't modify anything (there is still one exception in the old code, but i'll fix it)
=> Snapshot failures

packages/jest-jasmine2/src/extendJasmineExpect.js, packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/jasmine-check.js, packages/jest-runtime/src/__tests__/Runtime-internalModule-test.js, packages/jest-runtime/src/__tests__/test_root/internal-module.js, packages/jest-runtime/src/__tests__/test_root/internal-root.js, packages/jest-runtime/src/__tests__/test_root/test-preprocessor.js, packages/jest-runtime/src/index.js, packages/jest-runtime/src/transform.js
This is necessary to run jest code in a context that is isolated from configuration like preprocessors.
Open questions: should these be cached indefinitely and not be able to be wiped away through `jest.resetModuleRegistry()`?
=> Add concept of internal modules to jest-runtime.

blog/2016-07-27-jest-14.md
The test was "Link renders correctly" but the snapshot example was "Link changes the class when hovered", which was a bit confusing.
=> Update snapshot example to correspond with test name

packages/jest-cli/src/reporters/SummaryReporter.js
Prints:
* "re-run with `-u`" when invoked with Jest.
* "run with `npm <event> -- -u`" when invoked through npm.
cc @gaearon
=> Print proper snapshot update command.

packages/jest-cli/src/cli/index.js, packages/jest-cli/src/jest.js, packages/jest-config/src/normalize.js
These are a bunch of extensions to make Jest more viable to scripting.
* `runCLI` sucks and is exported for our internal runner. Some people depend on it, so we cannot really change it. I chose to export `run` instead, so now there are two options; one that works with a custom `argv` event that applies Jest and one that doesn't. `run` should be used by everyone.
* `config` was previously allowed to be an object but for some reason we lost this ability through passing JSON in argv.
* Allow presets to be any `.json` file.
=> Allow to specify custom argv and root for jest-cli.

CHANGELOG.md, packages/jest-cli/src/SearchSource.js, packages/jest-config/src/defaults.js, packages/jest-haste-map/src/crawlers/node.js, packages/jest-runtime/src/transform.js
If Jest is run within the OS's cache directory it won't be able to find anything because the cache directory itself is ignored by Jest. This change makes it so that Jest stores everything inside of `tmpdir + '/jest'`. I also updated the error messages and made it so that Jest doesn't appear to be crashing when it cannot find any files at all.
This was discovered by working on https://github.com/facebookincubator/create-react-app/pull/250
cc @gaearon
=> Updates for cache directories.

packages/jest-react-native/src/index.js
This enables the easy mocking of fetch()
=> #1350: Add Request, Response and Header classes to global scope in jest-react-native

integration_tests/__tests__/coverage_report-test.js, integration_tests/__tests__/empty_suite_error-test.js, integration_tests/runJest.js, package.json, packages/babel-plugin-jest-hoist/package.json, packages/jest-changed-files/package.json, packages/jest-cli/package.json, packages/jest-config/package.json, packages/jest-diff/package.json, packages/jest-environment-node/package.json, packages/jest-file-exists/package.json, packages/jest-haste-map/package.json, packages/jest-haste-map/src/__tests__/index-test.js, packages/jest-jasmine2/package.json, packages/jest-matcher-utils/package.json, packages/jest-matchers/package.json, packages/jest-mock/package.json, packages/jest-react-native/package.json, packages/jest-repl/package.json, packages/jest-resolve-dependencies/package.json, packages/jest-resolve/package.json, packages/jest-runtime/package.json, packages/jest-runtime/src/__tests__/Runtime-requireModuleOrMock-test.js, packages/jest-runtime/src/__tests__/Runtime-requireModuleOrMock-transitive-deps-test.js, packages/jest-snapshot/package.json, packages/jest-util/package.json, packages/jest-util/src/__tests__/JasmineFormatter-test.js, scripts/build.js, scripts/test.js, testSetupFile.js
```
488 tests passed (488 total in 62 test suites, 9 snapshots, run time 30.878s)
```
=> single jest run for all packages

packages/jest-react-native/package.json
Just updated my project to RN 0.31. 
because `jest-react-native` includes a hard dependency to RN 0.30, the packager is not running anymore and neither is `jest` 
this error is thrown:
> Using Jest CLI v14.1.0, jasmine2, babel-jest, jest-react-native preset
>
> jest-haste-map: @providesModule naming collision:
>   Duplicate module name: react-native
>   Paths: /<MY_PROJECT>/node_modules/jest-react-native/node_modules/react-native/package.json collides with /<MY_PROJECT>/node_modules/react-native/package.json
=> fix hard dependency to react-native

packages/jest-environment-node/src/__tests__/NodeEnvironment-test.js, packages/jest-environment-node/src/index.js
This fixes code that tests `global.global === global` to check if it is running in Node, [as RxJS 5 does] (https://github.com/ReactiveX/rxjs/blob/3793e4768dd2655300b67a82be9b30c4c065bac1/src/util/root.ts#L28).
=> Add global.global to "node" environment

packages/jest/src/jest.js
Remove the `#!/usr/bin/env node` hashbang from the entry point module of the `jest` package (`src/jest.js`, which is built to `build/jest.js`).
`build/jest.js` is the entry point that is imported when you do `require('jest')`, and it doesn't execute anything when run as an executable, so it doesn't make sense to have the hashbang there.
I ran into some issues trying to bundle this file with webpack (yes, I'm trying to do some weird stuff), it choked on the hashbang when trying to parse the module.
=> Remove the hashbang from the entry point module

docs/API.md
The current link is correct in Markdown but for some reason it doesn’t lead to the right place (the last `>` gets lost).
=> Fix Jasmine doc link

packages/jest-cli/src/jest.js
I'm getting a test failure on my local machine:
```
FAIL  __tests__/Intro-test.js
Test suite failed to run:
/Users/forbeslindesay/Documents/GitHub/jest/examples/react-native/node_modules/jest-react-native/node_modules/react-native/Libraries/Fetch/fetch.js:15
import 'whatwg-fetch';
^^^^^^
SyntaxError: Unexpected token import
at transformAndBuildScript (../../packages/jest-runtime/build/transform.js:328:10)
```
The changes I've made shouldn't make any difference to behaviour but simplifies things slightly.  It should also be marginally more performant because it skips creating a couple of completely un-used promises.
=> Simplify promise chain in jest-cli

README.md, docs/API.md
I reordered in terms of importance - "expect" first, "mock functions" next, "configuration" last - and added some documentation for everything on "expect". That I know about at least. Here's a screen shot of the new API doc page:
There is still more docs stuff to do, like I'd like to make sure everything in "globals" had some documentation. But for this PR I would mostly like to make sure that all the new info is correct, and not make it too much bigger. So let me know if things are erroneous.
=> Improving API documentation

integration_tests/__tests__/coverage_report-test.js, integration_tests/__tests__/debug-test.js, integration_tests/__tests__/transform-test.js, integration_tests/utils.js
Since we no longer output the version by default, our snapshots work
without needing to strip out the jest version.
=> Remove stripJestVersion

packages/jest-cli/src/__tests__/__snapshots__/generateEmptyCoverage-test.js.snap
the object structure changed due to the release of new versions (see https://github.com/istanbuljs/istanbul-lib-coverage/commit/6c9c65ed81ce7c0e8b4efa8a4f5d96f02349c5ea and https://github.com/istanbuljs/istanbul-lib-instrument/commit/add579687c2f617d346a3a7618601ba6d73c83df)
this shouldn't affect the resulting coverage report
=> update coverage .snap

docs/Troubleshooting.md
When using manual mocks for node modules, they will not be properly
mocked if `testPathDirs` has been set and doesn't include the root level
'__mocks__` directory.
I can imagine this is a common source of confusion, and there doesn't seem to be too many easily searchable answers online.
=> Add troubleshooting gotcha for npm module mocks

packages/jest-cli/package.json, packages/jest-cli/src/SearchSource.js, packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/TestWorker.js, packages/jest-cli/src/reporters/CoverageReporter.js, packages/jest-file-exists/src/__tests__/index-test.js, packages/jest-file-exists/src/index.js, packages/jest-haste-map/package.json, packages/jest-haste-map/src/HasteFS.js, packages/jest-haste-map/src/ModuleMap.js, packages/jest-haste-map/src/__tests__/index-test.js, packages/jest-haste-map/src/constants.js, packages/jest-haste-map/src/crawlers/node.js, packages/jest-haste-map/src/crawlers/watchman.js, packages/jest-haste-map/src/index.js, packages/jest-resolve-dependencies/src/index.js, packages/jest-resolve/src/index.js, packages/jest-runtime/src/__mocks__/createRuntime.js, packages/jest-runtime/src/index.js, packages/jest-snapshot/src/index.js, packages/jest-util/src/formatFailureMessage.js, types/HasteMap.js, types/Reporters.js
This is the first diff in a series to make `jest-haste-map` more performant. This diff doesn't impact performance but rather improves APIs so I can do further work:
* Instead of a POJO, a `HasteMap` object now consists of `HasteFS` and `ModuleMap` instances. These classes are intended to be immutable (for now) and have accessors for all data that you might want to read from it. In a follow-up, this will enable us to split up the data for both into separate cache files. Jest workers only need the module map and most of the time only either the file or the module maps are written. By splitting them in half and only writing or reading one, we can cut write time by 50 % and then read time in the worker by another 50 %. On www that's about 300-500ms per invocation of Jest (yes, really!)
* …
=> Refactor jest-haste-map (1/n)

integration_tests/__tests__/__snapshots__/console-test.js.snap, integration_tests/__tests__/console-test.js, integration_tests/__tests__/verbose-test.js, integration_tests/console/__tests__/console-test.js, integration_tests/console/__tests__/console2-test.js, integration_tests/console/package.json, packages/jest-cli/package.json, packages/jest-cli/src/Test.js, packages/jest-cli/src/lib/BufferedConsole.js, packages/jest-cli/src/reporters/BaseReporter.js, packages/jest-cli/src/reporters/DefaultReporter.js, packages/jest-cli/src/reporters/SummaryReporter.js, packages/jest-cli/src/reporters/VerboseReporter.js, packages/jest-cli/src/reporters/getConsoleOutput.js, packages/jest-util/package.json, packages/jest-util/src/Console.js, types/Console.js, types/TestResult.js
This is the first iteration of buffering and pretty-printing console messages. There are three possible behaviors:
* `--silent` does not print console messages.
* `--verbose` prints console messages as soon as they happen.
* *new default*: print console messages after a test completes.
We'll be changing the default to verbose mode if only a single test is run in #1418 and I think it is important to log asap in case people are debugging and trying to figure out infinite loops. In a follow-up diff I'll explore a timer in `BufferedConsole` that will attempt to flush console messages if a test is still running after 10 seconds. This applies to a lot of tests at FB but I think it is fine to do this and will work well in open source.
* `jest haste-map --verbose`
* `jest haste-map`
cc @gaearon …
=> Buffer console messages.

packages/jest-haste-map/src/__tests__/index-test.js, packages/jest-haste-map/src/index.js
This is necessary for adoption in react-native packager.
In Jest we can omit most node modules because we use the `resolve` module which (unfortunately) does real fs access. react-native packager doesn't want this (and we don't either, but it is convenient) so we are adding an option to retain all files in the haste map so packager can use it to optimize its resolution algorithm. Long term I expect this option to be on in Jest as well.
cc @davidaurelio
=> Add an option to retain all files in jest-haste-map.

integration_tests/__tests__/typescript-coverage-test.js, packages/jest-cli/src/TestRunner.js, packages/jest-runtime/src/index.js
there's probably a eslint update. those were passing locally just fine
=> fix dangling comma lint errors

packages/jest-config/src/__tests__/normalize-test.js, packages/jest-config/src/normalize.js, packages/jest-runtime/src/transform.js
When someone sets this to `jsdom`, we require jsdom instead of `jest-environment-jsdom` so it will break. Reordering will work.
Also added a config option to the transform cache key.
=> Resolve `jest-environment-<name>` before trying `<name>`.

packages/jest-jasmine2/src/index.js, packages/jest-matchers/src/matchers.js, packages/jest-snapshot/src/matcher.js
This just forwards to Jasmine's equality checker. This means we are in control of the printing but we rely on Jasmine to not change the behavior of our toEqual matcher.
Follow-up diff will explore improved messages and colors.
=> toEqual Jest matcher.

integration_tests/__tests__/verbose-test.js, packages/jest-cli/src/jest.js
I'm not sure if this is necessarily the best way to make the change.
1. Config seems to be immutable so I had to clone it in order to update the `verbose` setting.
2. Do we want to enable verbose by default when you just type `jest` if there is only one file, or should we restrict it to when you've typed `jest paty/to/a/file.js`?
3. Should we add a separate integration test for manually passing `--verbose` when there are multiple files.
=> Default to verbose mode for single files

integration_tests/__tests__/__snapshots__/console-test.js.snap, integration_tests/__tests__/__snapshots__/failures-test.js.snap, integration_tests/__tests__/failures-test.js, integration_tests/__tests__/stack_trace-test.js, integration_tests/__tests__/testcheck-test.js, integration_tests/failures/__tests__/__snapshots__/test-error-test.js.snap, integration_tests/failures/__tests__/test-error-test.js, integration_tests/failures/package.json, packages/jest-cli/src/reporters/DefaultReporter.js, packages/jest-cli/src/reporters/getConsoleOutput.js, packages/jest-diff/src/__tests__/diff-test.js, packages/jest-diff/src/diffStrings.js, packages/jest-diff/src/index.js, packages/jest-jasmine2/src/__tests__/matchers-test.js, packages/jest-matcher-utils/src/index.js, packages/jest-matchers/src/__tests__/__snapshots__/toThrowMatchers-test.js.snap, packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-matchers/src/__tests__/spyMatchers-test.js, packages/jest-matchers/src/matchers.js, packages/jest-matchers/src/spyMatchers.js, packages/jest-matchers/src/toThrowMatchers.js, packages/jest-snapshot/src/matcher.js, packages/jest-util/src/__tests__/__snapshots__/formatFailureMessage-test.js.snap, packages/jest-util/src/formatFailureMessage.js, packages/jest-util/src/separateMessageFromStack.js
=> Polish failure reporting in Jest.

docs/TutorialReact.md
This would confuse the reader as both code blocks show same file name.
As the test file calls the correct file name but the name is wrong in react component file name, it results in confusion.
=> File name in comment chnaged

packages/babel-jest/README.md
Seems like you should basically always be installing babel-jest with --save-dev rather than --save IIUC.
=> Teeny docs tweak

website/core/Site.js
Previously we were using the same analytics account as a couple other sites which made the data not useful. This switches it to a new account that is Jest-only.
=> switch google analytics account

lerna.json, package.json, packages/jest-cli/src/SearchSource.js, packages/jest-util/src/index.js
- Upgrade Lerna. Lerna 2.0 beta 24 has known issues in Windows: It appears to run successfully but actually doesn't do anything (https://github.com/lerna/lerna/issues/226#issuecomment-233049613). Need to upgrade to beta 26 to get an actual working version.
- The regex in `package.json` wasn't working correctly for some reason. Moving the `\` to the right spot (before the `.`) fixed it. (6c7620237ba9fa3a441bb7f26aabc59e9df85467)
- `SearchSource`  was incorrectly escaping `\` characters in the file path. To avoid this, we convert the `\` to `/` before running `escapeStrForRegex`. `replacePathSepForRegex` (which is what `pathToRegex` calls) converts it back to the correct separator anyways.
Fixes #1462
=> Fixes for Jest on Windows

packages/jest-matcher-utils/src/index.js, packages/jest-matchers/src/__tests__/__snapshots__/spyMatchers-test.js.snap, packages/jest-matchers/src/__tests__/spyMatchers-test.js, packages/jest-matchers/src/spyMatchers.js
`t 12627110`
seems like it has also been done already. I just changed the tests to use snapshots instead of regexps to capture the whole message and not just the piece.
=> SpyMatchers snapshot tests

packages/jest-util/src/__tests__/__snapshots__/formatFailureMessage-test.js.snap, packages/jest-util/src/formatFailureMessage.js
This makes the line with the error red and bold. The new printing style is less intrusive so it is easy to miss errors. This should make it clear *which* test is failing.
=> Make failures more obvious with the new printing.

packages/jest-cli/src/jest.js
Run the passed in test pattern when using `jest pattern --watch`. Don't re-run Jest when the coverage info is written.
=> Fixes for jest --watch

docs/TutorialReactNative.md, examples/react-native/__tests__/Intro-test.js, examples/react-native/__tests__/__snapshots__/Intro-test.js.snap, examples/react-native/package.json, integration_tests/package.json, packages/jest-react-native/jest-preset.json, packages/jest-react-native/src/index.js, packages/jest-react-native/src/setup.js
Also added aa mockComponent convenience function.
This adds new and improved default mocks for:
* View
* Image
* ListView
* ScrollView
* TextInput
* ActivityIndicator
=> More react-native default mocks

integration_tests/__tests__/__snapshots__/coverage_report-test.js.snap, integration_tests/__tests__/coverage_report-test.js, integration_tests/console/__tests__/console2-test.js, integration_tests/json_reporter/__tests__/sum-test.js, integration_tests/json_reporter/package.json, packages/jest-cli/src/reporters/CoverageReporter.js
=> Add short coverage summary.

packages/jest-cli/src/SearchSource.js
Before:
After:
I’m not sure the message about dynamic `require`s is very valuable here. We could leave it in `-o` documentation.
=> Simplify watcher message

packages/jest-cli/src/TestRunner.js
I upgraded our suite of tests at Pinterest to use jest-cli@14.1.0 and the --bail config option made Jenkins sad. It appears that when the TestRunner was refactored the bail option no longer looked at the numFailedTests. This fixed our issues locally.
=> Fix --bail config option bug

packages/jest-haste-map/package.json, packages/jest-matcher-utils/src/index.js, packages/jest-matchers/src/__tests__/__snapshots__/toThrowMatchers-test.js.snap, packages/jest-matchers/src/__tests__/toThrowMatchers-test.js, packages/jest-matchers/src/matchers.js, packages/jest-matchers/src/toThrowMatchers.js, packages/jest-util/src/__tests__/__snapshots__/FakeTimers-test.js.snap, packages/jest-util/src/__tests__/__snapshots__/messages-test.js.snap, packages/jest-util/src/messages.js
It really doesn't make sense that toThrow and toThrowError are doing something different. This now merges both of them into the same matcher: one that does *everything*. I believe this is the best user experience.
cc @gaearon @dmitriiabramov 
Fixes #1544
=> Expand toThrowError, alias toThrow to toThrowError.

jest, packages/jest-matchers/src/__tests__/__snapshots__/toThrowMatchers-test.js.snap, packages/jest-matchers/src/__tests__/toThrowMatchers-test.js, packages/jest-util/src/messages.js
Fixes the failing snapshot test on node 4. Through the snapshot test I learned that stack traces on node 4 and node 6 can be different; the node 6 ones have more information.
This made me realize the node 4 stack trace matching was actually broken and that the two regexes we had could easily be rolled into a single one. Finally, to make the test pass, I created a custom Error class to make sure that the stack trace is definitely the same on all node versions.
=> Fix stack trace printing in node 4.

packages/jest-cli/src/jest.js, packages/jest-cli/src/reporters/VerboseReporter.js, packages/jest-util/src/clearLine.js
Unlike the one used today, it clears the whole console on Windows (as opposed to a part of the screen). We have been using the same sequence as I propose here for a month in Create React App, and it works well on all platforms.
The only downside is that it erases the scroll history on Windows. IMO it’s a tolerable downside and less annoying than misaligned output interleaved with older commands.
Inspired by https://github.com/mochajs/mocha/pull/641.
The pending circle didn’t need updating, it worked fine on Windows.
This prevents run-on “Determining tests to run“ and “Running N tests...” on Windows.
All changes tested on OS X too.
Fixes #1555.
=> Windows CLI improvements

integration_tests/__tests__/config-test.js, packages/jest-cli/src/__tests__/SearchSource-test.js, packages/jest-cli/src/cli/index.js, packages/jest-config/src/index.js, packages/jest-runtime/src/__tests__/Runtime-cli-test.js, packages/jest-runtime/src/__tests__/test_root/logging.js, packages/jest-runtime/src/cli/index.js, types/Config.js
This seems like a reasonable default. Also made it so runtime can accept a JSON config.
cc @kyldvs
=> jest-runtime always disables automocking by default.

packages/jest-diff/package.json, packages/jest-diff/src/__tests__/diff-test.js, packages/jest-diff/src/index.js, packages/jest-snapshot/package.json, packages/jest-snapshot/src/SnapshotFile.js
Fixes #1429.
Fixes #1509.
Adds pretty-printing of elements both to regular tests (yay shallow rendering diffs!) and to snapshot tests (which had pretty-printing for instances but not for elements).
=> Pretty-print React elements

packages/jest-config/src/normalize.js
Fixes https://github.com/facebookincubator/create-react-app/issues/546
=> Fix test environment resolution.

packages/jest-util/src/index.js
This fixes facebookincubator/create-react-app#542 for me locally
=> Don't escape hyphens for Regex

README.md, docs/API.md
Refs https://github.com/facebook/jest/issues/1582. Adds section on `mockImplementationOnce` to the API Reference documentation (and to the README) - previously it was only documented on the "Mock Functions" documentation page (in `docs/MockFunctions.md`, where the code examples used here are borrowed from).
=> Update API docs with section on mockImplementationOnce

integration_tests/__tests__/runtime-internal-module-registry-test.js, integration_tests/runtime-internal-module-registry/__mocks__/fs.js, integration_tests/runtime-internal-module-registry/__tests__/runtime-internal-module-registry-test.js, integration_tests/runtime-internal-module-registry/package.json, packages/jest-runtime/src/index.js
Here's a possible fix for #1571.
When the `mkdirp` module is first required, it's required from `jest-utils`, which is required from [jasmine-check.js](https://github.com/facebook/jest/blob/0504590c40a7621fc68468c6aec0d6eed9c08edb/packages/jest-jasmine2/src/jasmine-check.js), which is required using `requireInternalModule` from [jest-jasmine2/index.js](https://github.com/facebook/jest/blob/0504590c40a7621fc68468c6aec0d6eed9c08edb/packages/jest-jasmine2/src/index.js). Because requiring internal modules and requiring "normal" modules (e.g. in a test or within your own code) use the same module registry, when `mkdirp` is required by the app code, Jest already has required it (as an internal module), and thus it doesn't try to require it again and just returns it from the module registry, …
=> Split internal module registry from main module registry

integration_tests/__tests__/globals-test.js, packages/jest-util/src/__tests__/globals-test.js, packages/jest-util/src/installCommonGlobals.js
This improves compat with some libraries like bluebird.
They seem to check for the toString result of process.
=> change toString of process copy

integration_tests/__tests__/runtime-internal-module-registry-test.js
It seems like most (if not all) of the integration tests fail on Windows. I'll have to investigate and determine why. In the meantime, disable this test on Windows.
Also, testing that AppVeyor works on pull requests 😛
=> Temporarily skip runtime-internal-module-registry-test on Windows.

package.json, testSetupFile.js
Uses the AppVeyor Jasmine reporter from the `jasmine-reporters` project to report test details to AppVeyor.
Example: https://ci.appveyor.com/project/Daniel15/jest-71o27/build/3/tests (this is building my fork of Jest)
Before: "Tests" tab is empty
After: "Tests" tab is populated
Failing tests show the output when clicked:
=> Add AppVeyor Jasmine reporter

packages/jest-cli/src/jest.js
I made this change in #1556 to make console clear work better on Windows. However I now discovered this has a significant downside on OS X: now if you first have a bunch of errors, scroll down, and then a successful run, scrolling up brings a confusing mixed view:
This change just reverts my tweak and makes it the way it has been before, with clear boundaries between the test runs in the scroll history:
=> Clear console like we did before

packages/jest-mock/src/__tests__/jest-mock-test.js, packages/jest-mock/src/index.js
The logic in `getSlots()` in `jest-mock` currently doesn't correctly handle the code generated by babel for `export { ... } from '...'` statements.
This code:
`export { Thing } from "./module-c";`
Generates:
```
"use strict";
Object.defineProperty(exports, "__esModule", {
value: true
});
var _moduleC = require("./module-c");
Object.defineProperty(exports, "Thing", {
enumerable: true,
get: function get() {
return _moduleC.Thing;
}
});
```
But `getSlots()` ignores the `Thing` field because it ignores getters. This means that when generating an automatic mock for this module, trying to `import { Thing } from "module-that-uses-export-from"` will result in `Thing` being undefined. A reproduction of the issue is here: https://github.com/benweissmann/jest-issue-repro
This PR detects the …
=> jest-mock: Correctly handle `export ... from ...` in babel-style ES2015 modules

examples/react/package.json
I came across this warning running the `jest` command in the terminal inside the examples/react dir with npm 3.10.6.
```
├── UNMET PEER DEPENDENCY react@15.2.1
└── react-addons-test-utils@0.14.8 
npm WARN react-addons-test-utils@0.14.8 requires a peer of react@^0.14.8 but none was installed.
```
npm 2.14.7 (less of a concern) throws npm ERR!:
```
npm ERR! peerinvalid The package react@15.2.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@15.2.1 wants react@^15.2.1
npm ERR! peerinvalid Peer react-addons-test-utils@0.14.8 wants react@^0.14.8
npm3:
```
Looks like these are all strict peer dependencies. I considered just bumping react-addons-test-utils to 15.2.1, but seen as bumping all three to the latest still ran the tests in both npm2 and …
=> Fix peerinvalid npm error in react example

README.md
Github seems to prepend the repository url when the link doesn't have a URL scheme.
=> Fix link to Plotly Academy Guide

packages/jest-cli/src/cli/args.js
Noticed a typo when I was trying to figure out how to grab my env variables for jest testing, went ahead and fixed it. CLA signed
=> Env Spacing Fix

docs/API.md
[this blog post](https://facebook.github.io/jest/blog/2016/09/01/jest-15.html) mentions the new configuration value `timers`, but it's missing from the API documentation.
=> update documentation to mention timers API configuration option

blog/2016-06-22-jest-13.md
Getting started section Remote debugging with Web Inspector
was removed due outdated information in this commit
https://github.com/facebook/jest/commit/46868fcf1d6c5371ea093984c3896dbf391c034a
=> Remove broken `debugging Jest tests` link from blog

packages/jest-cli/src/cli/args.js
This fixes this eslint error:
```
[...]/jest/packages/jest-cli/src/cli/args.js
157:1  error  Line 157 exceeds the maximum line length of 80  max-len
✖ 1 problem (1 error, 0 warnings)
```
=> Fix eslint error

docs/Troubleshooting.md
This adds information in the troubleshooting section about how to use the Chrome inspector in Node versions greater than or equal to 6.3 to debug Jest tests.
Relevant to this tweet: https://twitter.com/cpojer/status/774440000553226240
=> Add information about how to use Node debugger

docs/API.md
I didn’t know that Jest had support for `afterAll` and `beforeAll` until after opening a couple of issues and looking at the Jest source code. It could be really helpful to newcomers in the future to know these hooks exist 😊
=> Add `afterAll` and `beforeAll` to docs

docs/TutorialWebpack.md
As stated in the `Note:`, the Webpack config option is called `modulesDirectories`, whereas the Jest config option is called `moduleDirectories`.
https://webpack.github.io/docs/configuration.html#resolve-modulesdirectories
=> Correctly use modulesDirectories in docs

integration_tests/__tests__/jasmine_async-test.js, integration_tests/jasmine_async/__tests__/promise_beforeAll-test.js, integration_tests/jasmine_async/__tests__/promise_it-test.js, packages/jest-jasmine2/src/jasmine-async.js
This exposes per-hook timeout settings using the same API used by jasmine natively. This change should be compatible with existing tests unless they were relying on the 2nd parameter being ignored.
Since I was already at it, I also added a test for the `it` timeout for consistency.
=> Forward timeout argument for lifecycle hooks

docs/API.md
`coverageReporters` option was missing from the API documentation #1677
=> Add coverageReporters to the API docs (#1677)

packages/jest-util/src/index.js
Whitespace, comma and hash/pound aren't special either
This should fix #1621
=> Remove other non-special characters from escapeStrForRegex

packages/jest-mock/src/__tests__/jest-mock-test.js, packages/jest-mock/src/index.js
Fix to work around this issue:
https://github.com/joeapearson/jest-jsonschema
Problem seems to be that `jsonschema` module creates member functions with `-` in them (e.g. `utc-millisec`), presumably to mirror the json schema [spec](https://tools.ietf.org/html/draft-zyp-json-schema-03)
=> address jsonschema mock edge case

packages/jest-mock/src/__tests__/jest-mock-test.js
node 4 doesn't take function names from the object key name.
=> Fix mock-test on node 4.

integration_tests/__tests__/toMatchSnapshot-test.js, integration_tests/toMatchSnapshot/package.json
before i go into working on snapshot testing, i want to make sure we have a very good test suite.
this is a more declarative way of testing snapshot without introducing much file system state (existing test fail once in a while if you interrupt `jest` before it finishes)
all test files and their content are defined in the test file and written to the fs every test, so no need to switch between directories/files every time
=> toMatchSnapshot integration tests

packages/jest-matchers/src/index.js, packages/jest-matchers/src/types.js
MatcherContext is going to be `this` inside matcher functions.
why:
1. Right now it has only one value `isNot`, that tells you whether matcher was called with `.not` or not. Snapshot matcher will need this value in order to disable all `.not` invokations.
2. Later we'll be able to pass other context values that snapshots need (current file, suite, test names)
=> MatcherContext

docs/API.md
**Summary**
It seems that the `testURL` configuration setting was not documented. This PR adds a section for it.
**Test plan**
There are no code changes, but the config setting referred to can be found [here](https://github.com/facebook/jest/blob/83c254177f6ee58a9669c56e359d22ade0b21977/packages/jest-environment-jsdom/src/index.js#L27).
The default value for testURL is set [here](https://github.com/facebook/jest/blob/2699ed50ae4f849dfc384d3a4f4c4687b9fb24b0/packages/jest-config/src/defaults.js#L54)
=> Add section in documentation for testURL

packages/jest-resolve/src/index.js, packages/jest-runtime/src/__tests__/Runtime-requireModuleOrMock-test.js
**Summary**
The config option `moduleNameMapper` currently requires a full path match. This is because it is doing a regex replace on the original module name. This diff changes that so that instead we are using the mapped name directly. This makes it much easier to match any file of a specific type: like `'\\.css'`. There will be a small backwards compatability possibility for matches that depended on the previously incorrect behavior. (I found one such case in the Pinterest codebase that was resolved by using requireActual instead, which was more correct anyway). 
The previous functionality is:
**Before**
| moduleName             | regex     |   mappedName             | Resolution |
| --------------------- | ------- | ----------------------- | ------ |
| module/name/test   | …
=> Update regex replace to not require full path matching

packages/jest-config/src/__tests__/normalize-test.js, packages/jest-config/src/defaults.js, packages/jest-config/src/normalize.js
**Summary**
I added this ugly special case a while back when we didn't have great react-native support. Now we don't actually need this any more as I expect the community to fully switch over to the preset.
Fixes #1655
**Test plan**
the react-native example still passes.
=> Remove react-native special case.

packages/jest-jasmine2/src/index.js
**Summary**
This fixes #1730. Having setupTestFrameworkScriptFile run after extendJasmineExpect makes sure that it is possible to override global.expect to use another expectation library like chai.
**Test plan**
A demo of jest working with chai is here: https://github.com/0xR/snapshot-experiments/pull/1.
You can run `npm test` which will run the tests which have chai assertions. The integrate-chai fork of jest-jasmine2 is installed to demo that the codes solves the issue.
**Future work**
Document how to use jest with chai.
=> Run setupTestFrameworkScriptFile after extendJasmineExpect

docs/TutorialReactNative.md
**Summary**
It fixes a tiny typo in Jest documentation.
**Test plan**
Simple look at the PR diff should suffice. It's a single letter. :)
=> Fixed typo in TutorialReactNative.md

integration_tests/__tests__/testNamePattern-test.js, integration_tests/testNamePattern/__tests__/testNamePattern-test.js, integration_tests/testNamePattern/package.json, packages/jest-cli/src/cli/args.js, packages/jest-config/src/setFromArgv.js, packages/jest-jasmine2/src/index.js, types/Config.js
**Summary**
The `--testNamePattern <regex>` argument (alias `-t <regex>`) allows running only tests with a name that matches a given regex pattern. Fixes #1662.
**Test plan**
Added an integration test in `integration_tests/__tests__/testNamePattern-test.js`.
=> Add testNamePattern CLI argument

packages/jest-snapshot/package.json, packages/jest-snapshot/src/SnapshotFile.js, packages/jest-snapshot/src/__tests__/SnapshotFile-test.js
**Summary**
For easier reviewing, "test 2" should go before "test 10" in the snapshot file. Fixes #1612.
**Test plan**
Unit test added.
=> Sort snapshots by natural sort order

docs/API.md, packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-matchers/src/matchers.js
This matcher uses the same approach as toContain, except it uses deep-equality checking instead of object equality.
Closes #1369.
**Summary**
As discussed in #1369, a matcher is wanted that checks whether an _equal_ value is present in a collection. The existing `toContain` matcher uses ===, a strict equality check. This new matcher uses the same equality check as `toEqual` does - hence the name.
**Test plan**
Run unit tests.
=> Add deep-equality matcher for checking collection contents.

packages/jest-cli/src/reporters/getResultHeader.js
**Summary**
See #1593. This should work better on a bigger variety of terminal color schemes.
**Test plan**
Try Jest with different terminal schemes.
=> Tweak PASS/FAIL color. Fixes #1593

.flowconfig, integration_tests/__tests__/toMatchSnapshot-test.js, packages/jest-cli/src/SearchSource.js, packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/runTest.js, packages/jest-environment-jsdom/src/index.js, packages/jest-haste-map/src/index.js, packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/reporter.js, packages/jest-matchers/src/__tests__/__snapshots__/toThrowMatchers-test.js.snap, packages/jest-matchers/src/matchers.js, packages/jest-matchers/src/spyMatchers.js, packages/jest-matchers/src/toThrowMatchers.js, packages/jest-mock/src/index.js, packages/jest-resolve-dependencies/src/index.js, packages/jest-resolve/src/index.js, packages/jest-runtime/src/index.js, packages/jest-snapshot/package.json, packages/jest-snapshot/src/matcher.js, packages/jest-util/src/FakeTimers.js, packages/jest-util/src/__tests__/FakeTimers-test.js, packages/jest-util/src/__tests__/__snapshots__/FakeTimers-test.js.snap, packages/jest-util/src/__tests__/messages-test.js, packages/jest-util/src/clearLine.js, packages/jest-util/src/messages.js, types/TestResult.js
**Summary**
Because of how lerna hooks up node modules (previously with one index file and now with a symlink), Flow was unable to follow the modules properly. This diff adds a module mapper in the flowconfig and fixes up all the invalid Flow annotations that we accumulated over time.
**Test plan**
flow + jest
cc @hzoo this might be interesting to you.
=> Better flow annotations.

packages/jest-haste-map/src/__tests__/__snapshots__/index-test.js.snap, packages/jest-haste-map/src/__tests__/index-test.js, packages/jest-haste-map/src/index.js
Add `throwOnModuleCollision` option to `jest-haste-map`. Setting this to `true` will cause it to throw an error (rather than output a warning to console) when a module name collision is detected. This is useful for scenarios where determinism is critical.
`npm test`
=> Throw on module collision

docs/API.md
**Summary**
Adds some APIs I noticed were missing from documentation. Noted which methods on the `jest` global are chainable.
**Test plan**
N/A? :)
=> Doc tweaks

examples/enzyme/.babelrc, examples/enzyme/CheckboxWithLabel.js, examples/enzyme/__tests__/CheckboxWithLabel-test.js, examples/enzyme/package.json
**Summary**
Jest's [DOM testing guide](http://facebook.github.io/jest/docs/tutorial-react.html#dom-testing) uses react-test-utils, an example with Enzyme may be nicer and demonstrate how frictionless using 3rd party libraries alongside Jest can be.
I haven't updated the documentation text (yet) because explaining Enzyme's renderer doesn't mock the DOM seems like a distracting nuance but I can't figure out what to write instead. It occurred to me that to many developers an easier title might be "Normal testing" but that's silly.
**Test plan**
```sh
cd examples/enzyme
npm install
npm test
```
=> Add enzyme example

examples/react-native/__tests__/__snapshots__/Intro-test.js.snap, examples/snapshot/__tests__/__snapshots__/Link.react-test.js.snap, packages/jest-diff/package.json, packages/jest-diff/src/__tests__/__snapshots__/diff-test.js.snap, packages/jest-diff/src/__tests__/diff-test.js, packages/jest-diff/src/constants.js, packages/jest-diff/src/diffStrings.js, packages/jest-diff/src/index.js, packages/jest-matcher-utils/package.json, packages/jest-matcher-utils/src/__tests__/__snapshots__/index-test.js.snap, packages/jest-matcher-utils/src/__tests__/index-test.js, packages/jest-matcher-utils/src/index.js, packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/__snapshots__/spyMatchers-test.js.snap, packages/jest-matchers/src/__tests__/__snapshots__/toThrowMatchers-test.js.snap, packages/jest-matchers/src/__tests__/spyMatchers-test.js, packages/jest-snapshot/package.json, packages/jest-snapshot/src/SnapshotFile.js, packages/jest-snapshot/src/State.js, packages/jest-snapshot/src/__tests__/utils-test.js, packages/jest-snapshot/src/utils.js
**Summary**
This diff:
* Updates pretty-format to 4.2.x.
* Removes function names from snapshots. This has been a frequent source of issues, most recently with a Node.js update and istanbul's coverage plugin. Generally I believe that it is some signal to keep the function names in the snapshot but at the same time it isn't something visible in the UI so we shouldn't include them. Fixes #1740.
* Changes jest-diff to use `pretty-format` instead of our own `JSON.stringify` serialization. Fixes #1640 and #1727.
* If two objects are compared (toEqual) and serialize to the same value because of calls to `toJSON`, we now try to create a second diff that doesn't call `toJSON`. The worst case here is that we'll do twice as much work trying to come up with a diff for the user but it seems like an …
=> Printing and Snapshot Fixes

package.json
**Summary**
When trying to install jest, npm will give following warning:
```
$ npm install jest
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```
I've upgrade istanbul-api to latest release, minimatch have been upgrade to 3.0.2 and the problem is fixed.
**Test plan**
`npm install` don't give the warning now.
=> upgrade dependencies to fix npm package deprecate warning

docs/TutorialReact.md
**Summary**
Reasoning is outlined in #1761 (PR that adds Enzyme example). Rather than add an additional example to the docs I replaced the existing DOM testing section to avoid redundancy. I also added some guidance on setting up jsdom.
This is a documentation change only.
=> Use enzyme inside react tutorial's DOM testing section (instead of React's testutils)

README.md
Fix the typo error in readme.md file. Removed the duplicate link of the same video.
=> typo-fix readme

packages/jest-react-native/src/index.js
Now it's able to mock `arrow-style` components aka `stateless components` aka `lambdas`
=> Use name prop as component name for stateless components

packages/jest-matchers/src/__tests__/__snapshots__/spyMatchers-test.js.snap, packages/jest-matchers/src/spyMatchers.js
**Summary**
For a detailed summary, see #1786. TL;DR: when a mock/spy is unexpectedly invoked during a test, output the arguments used in the invocation to ease troubleshooting.
**Test plan**
`npm test` should be enough.
=> Give more feedback when a mock/spy is unexpectedly invoked

docs/TutorialWebpack.md
I saw an opportunity to simplify the example identity-obj-proxy configuration. This doesn't require the `styleMock.js` and `fileMock.js` files.
=> Simplify example identity-obj-proxy configuration

docs/API.md, examples/timer/__tests__/timerGame-test.js, packages/jest-runtime/src/index.js, types/Environment.js
**Summary**
Jest doesn't currently expose `runTimersToTime` during test runs, even though it supports it internally.
**Test plan**
I've added a test to examples/timers that uses this newly exposed functionality.
=> expose runTimersToTime; add to docs; add example

packages/jest-haste-map/src/crawlers/watchman.js
**Summary**
This addresses the watchman issue shown here:
This happens when dirExpr isn't a valid query and it causes watchman to crash
**Test plan**
npm run build && npm run test
=> Fixes bug in watchman.js that constructs invalid queries

packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/jest.js, packages/jest-cli/src/reporters/BaseReporter.js, packages/jest-cli/src/reporters/CoverageReporter.js, packages/jest-cli/src/reporters/DefaultReporter.js, packages/jest-cli/src/reporters/Status.js, packages/jest-cli/src/reporters/SummaryReporter.js, types/Reporters.js
**Summary**
* Fixes #1782 by immediately printing "RUNS" in the single process mode between tests and hiding the summary.
* Hides the cursor and removes a trailing newline.
**Test plan**
`jest cli -i`, `jest haste-map`, `jest` and watch the output.
=> Polish concurrent runner output.

packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/TestWatcher.js, packages/jest-cli/src/jest.js
Properly fixes https://github.com/facebook/jest/issues/1769. Supersedes: https://github.com/facebook/jest/pull/1771
This is now pretty awesome with the watcher interruption we have :) cc @thymikee
=> Make --bail work with watch mode.

packages/jest-jasmine2/src/__tests__/matchers-test.js, packages/jest-matcher-utils/src/__tests__/index-test.js, packages/jest-matchers/src/__tests__/__snapshots__/addMatchers-test.js.snap, packages/jest-matchers/src/__tests__/addMatchers-test.js
**Summary**
Convert rest of tests that's follow `toThowErrorMatchingSnapshot` matcher pattern to use matcher instead
**Test plan**
jest
=> Convert rest of tests to use toThowErrorMatchingSnapshot matcher

packages/jest-haste-map/src/__tests__/index-test.js, packages/jest-haste-map/src/crawlers/__tests__/node-test.js, packages/jest-haste-map/src/crawlers/__tests__/watchman-test.js, packages/jest-haste-map/src/crawlers/node.js, packages/jest-haste-map/src/crawlers/watchman.js, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/types.js
**Summary**
Add `forceNodeFilesystemAPI` option that forces the node crawler to use the Node file system API regardless of platform.
**Test plan**
unit test
=> Add `forceNodeFilesystemAPI` option to `jest-haste-map`

packages/jest-cli/src/reporters/SummaryReporter.js, packages/jest-matchers/src/matchers.js, packages/jest-matchers/src/spyMatchers.js, packages/jest-snapshot/src/index.js
**Summary**
Seems like calling prettyFormat on every spy matcher causes a memory leak. This stops the bleeding but should certainly be fixed so that we don't leak when pretty-printing, obviously. At least I have a repro now :)
**Test plan**
jest at FB
Fixes #1834
=> All matcher messages must be lazy; SummaryReporter prints per character.

docs/API.md
**Summary**
* Add docs about aliases `toHaveBeenCalled`, `toHaveBeenCalledWith` and `toHaveBeenLastCalledWith` matchers
* Add docs about new `toHaveBeenCalledTimes` matcher
* Add docs about `toThrowErrorMatchingSnapshot` matcher
**Test plan**
No
=> Update API docs for SpyMatchers and toThrowErrorMatchingSnapshot [ci skip]

docs/TutorialReactNative.md
**Summary**
Add testing series links [1](https://blog.callstack.io/unit-testing-react-native-with-the-new-jest-i-snapshots-come-into-play-68ba19b1b9fe#.yyst6qpc5) and [2](https://blog.callstack.io/unit-testing-react-native-with-the-new-jest-ii-redux-snapshots-for-your-actions-and-reducers-8559f6f8050b) to RN docs so users can read more about this topic.
**Test plan**
N/A.
---
@cpojer I got the titles from your community update :). Let me know if the PR is fine, I was not sure where to place it. Maybe is preferable a section at the top/end for external links.
=> Update React Native docs with links to a testing series example

docs/ManualMocks.md
**Summary**
It is currently confusing on where to place mocks for node/npm modules and locally created modules. This PR expands the example directory tree to give a better visual on where to place your modules.
=> expand example for mocks directory structure

docs/API.md, website/core/Header.js
**Summary**
Anchors generation on Github and Website was working differently,
what caused broken anchors in one the of sources
This PR:
* Making anchors generation consistent
* Fixes broken for website `toHaveBeenCalled` anchor
* Resolves #1851
**Test plan**
Jest website / Github page with API docs
=> Fix anchors of website [ci skip]

packages/jest-cli/src/reporters/__tests__/__snapshots__/utils-test.js.snap, packages/jest-cli/src/reporters/__tests__/utils-test.js, packages/jest-cli/src/reporters/utils.js
**Summary**
If a terminal's width is reported by node as `0`, this would get caught in an infinite loop, and crash v8 trying to allocate an ever-expanding array.
This works around this by immediately returning the supplied string if the width supplied is `0`, and adds a test for such a case.
**Test plan**
```javascript
require('jest/node_modules/jest-cli/build/reporters/utils').wrapAnsiString('so long, v8', 0)
```
will now return `'so long, v8'`, rather than crash the v8 runtime
fixes #1863
=> Avoid an infinite loop in `wrapAnsiString`

docs/TutorialWebpack.md
#1803 somehow oversimplified the `moduleNameMapper` config.
=> updated webpack tutorial

docs/TutorialWebpack.md
**Summary**
The current CSS Modules mock is returning `undefined` for every class. This makes impossible to test if a component has a class defined. Using this implementation we can have a value for each class.
```js
// Before
import styles from './Style.css'
styles.classA // undefined
styles.classB // undefined
// After
import styles from './Style.css'
style.classA // 'classA'
style.classB // 'classB'
```
I'm aware this solution is not 100% compatible with CSS Modules, i.e. if I import two different modules with the same class name I end up with the same value:
```js
import stylesA from './StylesA.css'
import stylesB from './StylesB.css'
stylesA.label === stylesB.label // true, in CSS Modules it would be false
```
That said this implementation covers 90% of the testing needs for CSS …
=> Update CSS Modules mock

docs/TutorialWebpack.md
Reverts facebook/jest#1882
I just noticed that the documentation already contains a similar solution for CSS modules, so this change is not necessary.
Sorry about that
=> Revert "Update CSS Modules mock"

packages/jest-snapshot/src/__tests__/utils-test.js, packages/jest-snapshot/src/utils.js
**Summary**
Windows uses `\r\n` for newlines. This PR normalizes this when saving snapshots to `\n`.
Fixes #1878
**Test plan**
A simple test case is included in the PR.
=> Normalize newlines across different OS.

docs/API.md
**Summary**
In the example for `toBeLessThan(number)` the text says 20 ounces but the code says 10 ounces.
**Test plan**
No test plan because this is a documentation change.
=> Fix typo in toBeLessThan example

packages/jest-haste-map/src/index.js
**Summary**
This change ensures that if throwOnModuleCollision is set to true, and a module collision occurs that any workers are cleaned up. Previously, this was not the case which resulted in any calling process appearing to hang after it should have completed.
**Test plan**
Create two files with the same @providesModule name. Then create a test script similar to the following
```javascript
const map = new HasteMap({
throwOnModuleCollision: true,
...
});
map.build().then(() => {
console.log('done');
}).catch((err) => {
console.log(err);
});
```
Without this patch the test script will output the error and hang. With the patch applied the test script will output the error and exit normally.
=> Haste-map now cleans up workers if throwOnModuleCollision is set to true

packages/jest-haste-map/src/__tests__/__snapshots__/index-test.js.snap, packages/jest-haste-map/src/index.js
**Summary**
The motivation behind this change is that hastemap was blaming me for `Dupicate` Mocks.
It should blame me about `Duplicate` Mocks.
=> Fixes a typo

docs/Configuration.md
**Summary**
This clears up the Browserify/`browser` notes in the configuration docs by correcting a typo and adding detail to link text.
**Test plan**
N/A. This is a documentation edit.
=> Remove typo in Configuration.md

packages/jest-cli/src/reporters/utils.js
**Summary**
Addresses #1928. The test time was being printed in red, which is potentially confusing because it could be seen as an error or a problem.
**Test plan**
Ran `npm run build && npm run test-examples`. Output:
=> Use yellow instead of red for time reporting. Fixes #1928

packages/jest-cli/src/cli/args.js, packages/jest-cli/src/cli/index.js, types/Config.js
Solve issue #1456
Duplicated of PR #1847 but passing tests.
=> RDY: feat(jest-cli): add forceExitAfterTestRun avg (Duplicated of PR #1847)

.gitignore, .travis.yml, appveyor.yml, package.json
The first run will be normal speed (~7.7s on my mac), but subsequent runs were just over a second.
=> Speed up eslint via built-in caching

package.json, packages/jest-environment-jsdom/package.json
**Summary**
The [releases](https://github.com/tmpvar/jsdom/blob/master/Changelog.md#980) since jsdom v9.5.0 include a fix for:
> a performance regression introduced in 9.5.0 for modifying the DOM. It was particularly noticable during initial parsing of a document with many elements; for example, one test showed parsing ten thousand elements taking 36.4 seconds, whereas after this fix it is back to a more reasonable 0.4 seconds.
It also includes implementations for the `document.hasFocus()` API, proper `activeElement` focus behavior for iframes, some `file` interface fixes, plus a few other odds and ends. The iframe focus behavior fixes would avoid hacks in tests like [these ones](https://github.com/facebook/react/pull/7936#pullrequestreview-4373554), while the utility of the performance …
=> Update jsdom dependency

docs/API.md
**Summary**
The documentation for `.toBeInstanceOf` in the API.md file was inconsistent.
**Test plan**
No code was changed; markdown review should be sufficient for testing purposes.
=> Docs: Fix toBeInstanceOf capitalization in API.md

packages/jest-cli/src/TestRunner.js
First of all thanks for this tool!
I'm very new to Jest so please forgive any stupid error or incorrect assumption.
I'm very open to adapt this to the project / community needs, in fact I am trying to understand how to add an integration test for this, any suggestion is more than welcome.
**Summary**
Whenever the `--coverage` flag is passed, jest exits with `0` even if the threshold requirements are not met.
Seems like the solution is to determine if a run is successful after `onRunComplete` is called, because in that function `aggregatedResults` is populated with the required values.
**Test plan**
I've written a small POC which has a 100% coverage requirement which is not met.
With the change after you run `npm test` in this POC you will get `1` as a result from `echo $?`.
```JS
// …
```
=> Return exit code 1 if coverage threshold requirements are not met

docs/API.md
Follows up on https://github.com/facebook/jest/issues/1970
Document the CLI options that allow to select tests to be run / snapshots to be re-recorded. 
When working on a test, it’s much easier to work with particular test / file. 
I’ve built the website locally and the markdown seems to be all fine. Please review copy, will be glad to improve it. 
Also if documenting only these options doesn’t grant a new top level header, maybe let me know what other options are best to add docs for and I’ll try my best.
=> Add CLI options documentation

packages/jest-cli/src/cli/args.js
Somewhat helps with facebook#1970
--updateSnapshot accepts <suiteName> to select which snapshots to update
--updateSnapshot can be combined with --testNamePattern to re-record
snapshot for particular test in as suite
=> Document updateSnapshot with testNamePattern

packages/jest-runtime/src/index.js
**Summary**
Encountered the following error message while trying to run React tests on Windows:
```
FAIL  src\renderers\shared\stack\reconciler\__tests__\ReactStateSetters-test.js
SyntaxError: Invalid regular expression: /\__tests__\/: \ at end of pattern
at new RegExp (native)
at new Runtime (node_modules\jest-runtime\build\index.js:111:23)
at handle (node_modules\worker-farm\lib\child\index.js:41:8)
at process.<anonymous> (node_modules\worker-farm\lib\child\index.js:47:3)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
at internal\child_process.js:696:12
at nextTickCallbackWith0Args (node.js:420:9)
```
Node.js version is 4.6.1.
**Test plan**
React tests run properly after the fix.
=> Fix path separator replacement bug in Windows

examples/typescript/preprocessor.js, examples/typescript/tsconfig.json
**Summary**
When using typescript in a real project, it is idiomatic to provide the typescript compiler options by means of the `tsconfig.json` file. This makes sure the typescript compiler, webpack loaders, IDE's, test runners like jest, all use the same compiler flags (for example `"jsx": "react"`). 
In the current `preprocessor.js` example the configuration was in line. People using typescript with jest will usually change this to load `tsconfig.json` instead. The confusing thing is that the transpiler doesn't want all the options, but just the `compilerOptions` section from the config file. I made that more clear with-this new setup. I've seen two different cases in the last week where people run into this. (Example: https://github.com/mobxjs/mobx/issues/405#issuecomment-255342371). …
=> Use typescript compiler more idiomatically

integration_tests/__tests__/resolve-test.js, integration_tests/resolve/__tests__/resolve-test.js, integration_tests/resolve/package.json, integration_tests/resolve/test1.android.js, integration_tests/resolve/test1.js, integration_tests/resolve/test1.json, integration_tests/resolve/test1.native.js, integration_tests/resolve/test2.js, integration_tests/resolve/test2.json, integration_tests/resolve/test2.native.js, integration_tests/resolve/test3.js, integration_tests/resolve/test3.json, integration_tests/resolve/test4.json, packages/jest-resolve/src/index.js
**Summary**
Jest currently is not able to resolve internal modules with a platform extension such as .android.js / .ios.js.
This solves this issue by allowing the Resolver from jest-resolve to find a module also by using the defaultPlatform option.
This also allows to test android and ios platforms by defining the defaultPlatform accordingly
**Test plan**
ls -l ./src:
> -rw-r--r-- 1 user user 1K Oct 18 12:59 App.android.js
> -rw-r--r-- 1 user user 1K Oct 18 12:59 App.ios.js
in \_\_tests\_\_/App-test.js:
```javascript
import 'react-native'
import React from 'react'
import App from '../src/App'
import renderer from 'react-test-renderer'
it('renders correctly', () => {
const tree = renderer.create(
<App/>
).toJSON();
expect(tree).toMatchSnapshot();
})
```
```
jest --no-cache
```
=> Add defaultPlatform extensions to resolveModule extensions

docs/API.md
This fixes a broken anchor to CLI options on the API docs.
s/jestclioptions/jest-cli-options
=> Fixes typo in link to CLI options

CONTRIBUTING.md
**Summary**
Adds instructions for getting started to the CONTRIBUTING docs. I couldn't find any docs ([like this](https://github.com/danger/danger#im-here-to-help-out)) showing me how to grab the code, and run the tests to verify everything is fine. 
So I added it to the contributing docs 👍
=> Add getting set up instructions to the contributing doc

website/src/jest/index.js
Fixes grammatical error on the website's index page that may lead people to think that "Jest Work" is a separate package needed to run Jest with compile-to-JS languages.
CURRENT: "**Jest Work** with any compile ..."
CHANGE: "**Jest works** with any compile..."
=> Fix grammatical error in whyJest[9].content

docs/Troubleshooting.md
**Summary**
Stop using Node `--inspect` option in the docs on debugging
The technique described in the instructions does not pick up
breakpoints set with `debugger` statements. This issue is being
tracked by https://github.com/facebook/jest/issues/1652, but
it's unclear how long it will take to resolve as it's actually
a Node issue.
As a work-around, have updated docs to describe connecting an
external debugger to the Node process.
**Test plan**
I have locally generated and previewed the updated documentation using the `npm start` command in the `website` directory.
=> Stop using Node `--inspect` option in the docs on debugging

packages/jest-cli/src/reporters/CoverageReporter.js
=> Remove custom coverage printing.

packages/jest-react-native/src/bridge-mock.js
**Summary**
In RN 0.36 there has been a lot of refactoring. One of the changes is that the `NativeModules.js` now expects the modules to not have `RCT` or `PK` prefixes anymore. Which causes the mock to be invalid. This simply changes the mock to be updated to the shape `NativeModules.js` expects.
Now, tests are still broken in 0.36 due to https://github.com/facebook/react-native/blob/292cc82d0ebc437a6f1cdd2e972b3917b7ee05a4/Libraries/Core/InitializeCore.js#L186-L196 which tries to start a websocket in test mode. I am not sure how to go about that. PR react-native to change it or mock it somehow in Jest?
Fixes #1912
=> remove RCT prefix for native modules

packages/jest-react-native/package.json, packages/jest-react-native/src/bridge-mock.js, packages/jest-react-native/src/setup.js
I seem to have missed things in my previous PRs. this _should_ work now I guess we'll find out when certain components / apis are used if something is missing. I updated the bridge mock to follow the new structure (I missed the changed data structure in my previous PR). With the updated mock it seems there is no need to mock setupDevtools either.
Is it possible to generate a new mock for the bridge? That will probably be the best idea.
=> Update bridge mock again

packages/jest-haste-map/src/lib/__tests__/docblock-test.js, packages/jest-haste-map/src/lib/docblock.js
**Summary**
Allows to parse directives from multiline comments and strips line comments from docblocks / multiline comments.
Fixes #2004
Fixes #2005
=> haste-map Allow directives in non docblock comments

integration_tests/__tests__/__snapshots__/snapshot-serializers-test.js.snap, integration_tests/__tests__/snapshot-serializers-test.js, integration_tests/snapshot-serializers/__tests__/snapshot-test.js, packages/jest-snapshot/src/__tests__/plugins-test.js, packages/jest-snapshot/src/plugins.js
**Summary**
This PR applies a small change on #1842, prepending instead of appending custom serializers to the default ones provided by Jest. This allows those serializers to work not only on *parts* of the snapshot, but also on the snapshot *as a whole*, since they are given precedence with respect to the default ones.  This, in turn, allows React components to be rendered not only with the default `ReactTestComponent` plugin, but also with a custom HTML previewer (an idea introduced in #1862).
**Test plan**
Unit test and integration tests are included. Integration tests show that default and custom serializers work, both independently and in tandem.
=> Prepend custom snapshot serializers (instead of appending them)

packages/jest-haste-map/src/index.js
**Summary**
During debugging some FS problem on my machine I found that one of the files created looked a bit ugly with no sensible name. After some more debugging I found out that this was the haste-map generated by jest.
**Test plan**
Run jest and check if the generated file in the cache has been changed to a filename with `haste-map` prepended.
=> Prepend configuration name with `haste-map`

integration_tests/__tests__/global-test.js, integration_tests/auto-clear-mocks/package.json, packages/jest-environment-node/src/index.js, packages/jest-runtime/src/transform.js
**Summary**
There appears to be no other way to pull out built-ins from a vm context than actually evaluating them inside of the vm. This takes a bit of code from jsdom and adapts them to set the appropriate globals on the `global` object. This makes it so that `Object` equals `global.Object` inside of a vm context, with the right globals (not the ones from Jest's own context).
Fixes #1597
cc @domenic in case he knows whether there is another way.
**Test plan**
jest (+ will add an integration test)
=> Properly set globals from within the vm context.

packages/babel-jest/src/index.js, packages/jest-file-exists/src/index.js, packages/jest-runtime/src/transform.js, types/Transform.js
**Summary**
Long standing "bug" in Jest that was confusing to people and required them to run with `--no-cache` once.
**Test plan**
* Run jest
* Change `.babelrc` to remove all the transforms
* Run jest again; it should now throw whereas previously it would still pass because it used the cache files.
cc @taion @kentcdodds
=> .babelrc is now part of the cache key.

docs/TutorialReact.md
**Summary**
I've updated a link for the `create-react-apps` docs which was outdated :smile: 
**Test plan**
1. Open the new link
2. Observe
=> docs: fix incorrect link

appveyor.yml
We can delete the `choco install yarn` from `appveyor.yml` now, since Yarn is now preinstalled on AppVeyor :)
=> Yarn is now preinstalled on AppVeyor

packages/jest-matchers/src/__tests__/__snapshots__/extend-test.js.snap, packages/jest-matchers/src/__tests__/extend-test.js, packages/jest-matchers/src/index.js
this is not ideal, i would want 'message' to be required but that's blocking the sync with www
=> make 'message' optional when adding matchers

docs/Configuration.md
`modulePaths` takes an array of absolute paths. In a json config, I cannot construct the absolute path to my local modules programmatically.
Fortunately, `modulePaths` supports `<rootPath>` but it wasn't documented.
=> Add note about `<rootDir>` in modulePaths documentation

integration_tests/resolve/package.json, packages/jest-resolve/src/index.js
**Summary**
See #2065. We should only resolve native modules if the "native" platform extension is provided.
**Test plan**
* `yarn add react-relay react react-dom`
* `require('react-relay')` in a test file
* `jest` does not throw
=> Fix native platform resolution.

integration_tests/__tests__/compare-dom-nodes-test.js, integration_tests/compare-dom-nodes/__tests__/failed-assertion.js, integration_tests/compare-dom-nodes/package.json, packages/jest-matcher-utils/src/index.js
This change is based on the feedback from @cpojer in https://github.com/thejameskyle/pretty-format/pull/47.
Closes #1772
=> Set maxDepth to truncate extraordinarily deep object printing

packages/jest-resolve/src/index.js
**Summary**
fixes extensions array growing with every module being resolved, this was introduced in 17.0.1 when concat was changed to unshift
**Test plan**
this is quite a simple regression fix, tested it on a project of mine and it fixes the regression causing the test to run extremely slowly due to the array becoming thousands in length
unfortunately I haven't found any tests that would cover the module resolution specifically, should a new test be created for this change?
=> [bug] fix regression from jest 17.0.1 mutating options.extensions

packages/jest-haste-map/src/index.js
No point in doing all the work twice if the same is passed around.
=> De-duplicate roots in jest-haste-map.

packages/jest-haste-map/src/__tests__/index-test.js, packages/jest-haste-map/src/index.js
**Summary**
It's possible we receive multiple events if one folder is watched twice for some reason.
Example:
* Roots are `<rootDir>` and `<rootDir>/packages`
* `touch packages/a.js`
* Two events are emitted to the `onChange` handler.
This diff also changes the onChange handler into a queue based system, just to make sure this is all done in sequence.
**Test plan**
jest + manual verification.
cc @matryoshcow @davidaurelio
=> jest-haste-map: prevent duplicate fs change events from being emitted.

integration_tests/testNamePattern/__tests__/testNamePattern-test.js, packages/jest-jasmine2/src/jasmine-async.js
**Summary**
`test.concurrent` doesn't respect `testNamePattern`. CLI reports that test is skipped, but actually it is executed.
**Test plan**
Run modified `testNamePattern-test.js` without applying suggested fix to see.
Or see screenshot (sample user test):
=> test.concurrent must support testNamePattern

packages/jest-jasmine2/src/jasmine-async.js
I see `(node:5197) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Jest: concurrent tests must return a Promise.` in a CI server log and have no idea what test causes it.
`specName` should be in the error message.
**Test plan**
No test. Just cosmetics.
=> include specName into the concurrent test assertion message

packages/jest-cli/src/jest.js
Working on some changes to update facebook/react to use Jest 17 and since it uses .runTests(), it needs access to TestWatcher so the concurrent reporter works.
=> Expose TestWatcher

packages/jest-cli/src/TestRunner.js
https://github.com/facebook/jest/issues/1903#issuecomment-261583088
Condition `timings.every(timing => timing < SLOW_TEST_TIME)` returns `true` if no timings. And if no timings — tests will be executed serially.
**Test plan**
Well, my tests executed not in 20 minutes, but in 3 minutes :)
=> do not run in band first time (no timings)

docs/TutorialReact.md
=> typo in require('babel-jest')

packages/jest-cli/src/reporters/NotifyReporter.js
**Summary**
This PR solves this incorrect or bad formatted notification when using `--notify`:
Code example:
```js
describe('Test suite', () => {
// describe('Boolean test', () => {
// 
//   it('Expect true', () => {
//     expect(true).toBeTruthy();
//   });
//   
//   it('Expect false', () => {
//     expect(false).toBeFalsy();
//   })
// 
// });
});
```
After this change, the notification is:
**Test plan**
Tests ran green locally
=> Fix "NaN% Failed" notification

packages/jest-matcher-utils/src/__tests__/__snapshots__/index-test.js.snap, packages/jest-matcher-utils/src/__tests__/index-test.js, packages/jest-matcher-utils/src/index.js
reduce `maxDepth` when pretty formatting the object if the resulting string is too long.
It will reduce depth by 1 every time until it either fits the `MAX_LENGTH` or becomes 1 (just printing the top level keys). This should happen only on failures, so the performance hit from running `format` multiple times should not be that bad.
cc @gaearon
=> reduce maxDepth for very large objects

docs/MigrationGuide.md
**Summary**
Unnecessary word ('get') in document.
=> Fix typo in MigrationGuide.md

packages/jest-react-native/jest-preset.json
**Summary**
When using jest with React Native and Relay and recommended default settings, jest throws :
```
Cannot find module 'react-dom' from 'relayUnstableBatchedUpdates.js'
at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
at Object.<anonymous> (node_modules/react-relay/lib/relayUnstableBatchedUpdates.js:15:18)
at new RelayEnvironment (node_modules/react-relay/lib/RelayEnvironment.js:39:63)
```
Investigating this, I found out that https://github.com/facebook/jest/blob/master/packages/jest-react-native/jest-preset.json didn't have "native" in the list of platforms, hence jest can't pick up `relayUnstableBatchedUpdates.native.js` in react-relay. 
**Test plan**
I copied and paste the content of https://github.com/facebook/jest/blob/master/packages/jest-react-nati …
=> Adds native to the list of jest-react-native platforms to fix testing with react-relay.

packages/babel-jest/README.md
**Summary**
`config.transform` link in `babel-jest` README doesn't link to the correct URL.
**Test plan**
Click the link.
=> Fix config.transform link in babel-jest README

docs/Troubleshooting.md
Hey guys, me and a bunch of others users have found that Jest may be slow on CI servers and/or Docker machines. This is probably related to limited IOPS or CPU power. Until there's a solution I recommend documenting it in the troubleshooting guide. Suggestions for improvement are welcome.
=> Document slow tests on certain CI servers and/or Docker machines.

packages/jest-snapshot/src/index.js
**Summary**
I am currently working on implementation of jest snapshots into Ava (https://github.com/avajs/ava/pull/1113) and wanted to smooth a few rough edges when implementing with another runner.
In particular:
- jest-snapshots relies on a context that has `dontThrow` function - that however depends too much on the implementation
- message on failure contains information about where the failure occurred; that way, the first line of the message says `expect(value).toMatchSnapshot()` - which again displays an implementation detail that isn't necessary
I'm happy to change the solution but it would be great to address these issues.
**Test plan**
When integrated with Ava, we get this kind of output:
(Amazingly, when combined with `nyc` for test coverage, it works seamlessly without any …
=> Amend jest snapshots to tie in nicely with Ava

docs/Configuration.md, packages/babel-jest/README.md
**Summary**
Clarify that when "transform" is overwritten, the babel-jest is not loaded automatically anymore and should be explicitly defined in the config.
Related to: #2096
=> Update transform and babel-jest docs

docs/API.md, integration_tests/__tests__/toMatchSnapshot-test.js, packages/jest-snapshot/src/index.js
**Summary**
In reference to #1392, changes `.toMatchSnapshot()` to `.toMatchSnapshot(?string)`.
This is primarily so that dynamic tests can have more meaningful snapshot names, compared to having the same name with a different numeric suffix.
See: c46d1b7.
**Test plan**
1. `npm run watch`
2. `npm run jest ./integration_tests/__tests__/toMatchSnapshot-test.js`
See: 8d05bec.
=> .toMatchSnapshot(?string)

packages/babel-jest/src/index.js
**Summary**
The babel-jest package can sometimes be used to transpile and instrument
at the same time. Only jest-runtime was passing CWD properly to
istanbul. This pull mirrors this behavior in babel-jest as well now.
**Test plan**
After this change, any usage of istanbul that I can see is properly passed a 'cwd' variable equal to the config.rootDir option. No tests or APIs should be impacted by this.
=> Pass CWD when instrumented through babel-jest

packages/jest-cli/src/jest.js
**Summary**
This PR introduces two new ideas for the jest-cli after discussion on #2049 .
1) Allow hiding of usage in watch mode by setting the env `JEST_HIDE_USAGE`
2) Displaying the usage by hitting `?`
**Test plan**
```
$ export JEST_HIDE_USAGE= && node ./packages/jest-cli/bin/jest.js --watch
$ export JEST_HIDE_USAGE=1 && node ./packages/jest-cli/bin/jest.js --watch
```
First run should show usage, second should not. Hit `?` while in watch mode.
=> Allow hiding of usage #2049

integration_tests/__tests__/timer_after_resetAllMocks-test.js, integration_tests/timer_after_resetAllMocks/index.js, integration_tests/timer_after_resetAllMocks/package.json, integration_tests/timer_after_resetAllMocks/timer_and_mock.test.js, packages/jest-util/src/FakeTimers.js, packages/jest-util/src/__tests__/FakeTimers-test.js
**Summary**
If the flag `resetMocks` or `jest.resetAllMocks` is used in the test, all the timer-related tests following that will fail with no way of recovering.
**Cause**
`jest.resetAllMocks` resets everything, including mocks created by fakeTimers. There are also no public methods that we can use to re-instantiate a new FakeTimer object to mitigate the problem.
**Solution**
Given that both mock and fake timers are part of the jest, they should be working together out-of-the box without extra code gluing them together. We change the `useFakeTimers` method to always create new mocks so the mocks will not be reverted by `resetAllMocks`. If there is a better way to manage the lifecycle of those mocks, please let me know. I will be happy to make changes.
**Test plan**
I have provided a new …
=> Always recreate mocks in FakeTimers.useFakeTimers()

packages/jest-cli/src/jest.js
`Array.prototype.includes` is not supported in Node v4.
Fixes #2178
=> Replace Array.includes with Array.indexOf for node v4 support

integration_tests/__tests__/__snapshots__/failures-test.js.snap, packages/jest-runtime/src/index.js, packages/jest-runtime/src/transform.js, packages/jest-util/src/messages.js
**Summary**
Trying to make @gaearon happy. Fixes #1929
**Test plan**
Add a syntax error, run jest and don't see a stack trace.
=> Don’t print stack traces from babel.

docs/API.md
**Summary**
Add documentation to `docs/API.md` for the new `expect.extend` API. #1977
=> Add documentation for expect.extend API

docs/Configuration.md
**Summary**
The sorting of a few configuration options in the header of "_Configuration.md_" did not match the sorting of their detailed descriptions. That was corrected.
=> Update configuration options order in docs

.babelrc, integration_tests/__tests__/json-test.js, package.json, yarn.lock
**Summary**
Allows using `async` functions inside the jest codebases.
**Test plan**
I'd like to hope that the babel team have all the tests for this 👍 - assuming all is 📗 on tests then I think the transpiling is good
=> Adds support for using `async` inside the babel runtime

integration_tests/babel-plugin-jest-hoist/__tests__/integration-test.js, packages/babel-plugin-jest-hoist/src/index.js, packages/jest-haste-map/src/__tests__/index-test.js
**Summary**
* Virtual mocks weren't hoisted.
* Fix insane clowniness in static analysis.
**Test plan**
jest
=> Fixes for babel-plugin-jest-hoist.

docs/MigrationGuide.md
**Summary**
https://github.com/skovhus/jest-codemods now support Mocha and chai asserts (see https://github.com/skovhus/jest-codemods/issues/16). 
This updates the Migration Guide documentation.
=> Update documentation with jest-codemods new Mocha and chai support

website/publish-gh-pages.js
Do a regular `git push` to origin. `gh-pages` is a protected branch in `facebook/jest`.
** Test plan **
Not tested. See https://circleci.com/gh/facebook/jest/3 where the current script failed on `facebook/jest` due to the use of `-f`. This script was based on [React Native's](https://github.com/facebook/react-native/blob/master/website/publish-gh-pages.js#L132) which also does not use `-f`. git pushing to `origin` should effectively push to "jest-bot@github.com/facebook/jest.git" as this is the repo that was checked out earlier in the script.
=> Do not force push to gh-pages, a protected branch

packages/jest-jasmine2/src/jasmine-async.js
**Summary**
Fixes #1868 
`it.concurrent` fails to report handled error due to mismatched arguments being passed to `originalFn` in `makeConcurrent()` which ends up throwing UnhandledPromiseRejectionWarning.
**Test plan**
Pass correct arguments to function.
**Before**
**After**
=> Pass correct args to makeConcurrent's originalFn while catching error

docs/TutorialWebpack.md
1. Uses `JSON.stringify()` so that quotes in the filename don't kill it.
2. Removes `getCacheKey()` because this example is broken in my testing with it if it just returns `filename`. Perhaps we need to hash the result of this call? I have a reeaaaaly long path of the temp folder as a result, and Jest errors failing to create a cache at that location.
=> Fix file transformer example

packages/jest-cli/src/jest.js
**Summary**
First run should show usage, second should not. Hit ? while in watch mode.
@cpojer asked me to address this from a [previous pull request](https://github.com/facebook/jest/pull/2125#issuecomment-263659285)
**Test plan**
`$ export JEST_HIDE_USAGE=1 && node ./packages/jest-cli/bin/jest.js --watch`
1st run displays usage. With the watcher still runnning, make a minor change to a file, the watcher should rerun tests and not display the usage.
=> When using the hide jest usage env, show usage first run only

packages/jest-react-native/jest-preset.json
**Summary**
This is attempt to fix segmentation fault on Node 4. Since "Segmentation fault" means that we tried to access memory that we do not have access to, it could happen that we tried to reach not-existing directory.
**Test plan**
Travis
=> Fix moduleNameMapper in jest-react-native

docs/Configuration.md
**Summary**
It looks like `json` was a typo for `jest` because:
* `snapshotSerializers` is at the same level of hierarchy as the other keys in `jest-cli/src/normalize.js` and the only reference to `json` in that file is about coverage reporters
* Jest documentation differs from `enzyme-to-json` and `jest-serializer-enzyme`
Because this is the only json code fence in Configuration, I changed it to follow the example of js code fences under `coverageThreshold` and `globals`
**Test plan**
Review by someone who knows for sure, please.
=> Docs: replace json with jest under snapshotSerializers in Configuration

integration_tests/__tests__/json_reporter-test.js, packages/jest-cli/src/cli/args.js, packages/jest-cli/src/jest.js
**Summary**
Renamed `jsonOutputFile` to `outputFile`
`jsonOutputFile` is only used with the `json` parameter, besides it would be better to make it more generic if we plan to support different formats
**Test plan**
```
yarn cache clean
yarn install
yarn test
```
=> rename jsonOutputFile to outputFile

integration_tests/__tests__/json-test.js, packages/jest-jasmine2/vendor/jasmine-2.5.2.js, packages/jest-matchers/src/index.js, packages/jest-matchers/src/matchers.js
**Summary**
`Jasmine`'s built-in [matchers are providing](https://github.com/facebook/jest/blob/master/packages/jest-jasmine2/vendor/jasmine-2.5.2.js#L1568) `matcherName`, plus `expected` and `actual` values, allowing external reporters and integrations to provide any custom diff views, such as
or
Also, most of existing standalone assertion libraries, [such as `chai`](https://github.com/chaijs/chai/blob/master/lib/chai/assertion.js#L111), also pass the values in their error object, however [`jasmine` doesn't pass the error object](https://github.com/facebook/jest/blob/master/packages/jest-jasmine2/vendor/jasmine-2.5.2.js#L1611) through.
`Jest` is providing the built-in diff (which looks great in terminal), however, `Jest`'s matchers are not passing through the matcher results (including …
=> Pass `expected` and `actual` objects from matchers and custom errors from jasmine

integration_tests/__tests__/testResultsProcessor-test.js, integration_tests/testResultsProcessor/__tests__/processor-test.js, integration_tests/testResultsProcessor/package.json, integration_tests/testResultsProcessor/processor.js, packages/jest-cli/src/cli/args.js, packages/jest-cli/src/lib/formatTestResults.js, packages/jest-config/src/setFromArgv.js
Expose the `testResultsProcessor` option on the cli
The option was already available through configuration, 
I've exposed it and add an integration test for testing it.
**Test plan**
yarn test
=> expose --testResultsProcessor

packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-matchers/src/matchers.js
Fixes issue #2212.
Added tests to check that the matcher maintains array-ordering.
=> Fixed bug in array order toMatchObject

docs/Configuration.md, integration_tests/snapshot-serializers/package.json, integration_tests/snapshot-serializers/plugins/foo/index.js, packages/jest-config/src/__tests__/__snapshots__/normalize-test.js.snap, packages/jest-config/src/__tests__/normalize-test.js, packages/jest-config/src/normalize.js, types/Config.js
**Summary**
This allows to hook in extensions in node_modules as "foo" instead of "<rootDir>/node_modules/foo/index.js"
**Test plan**
jest
=> Properly resolve config options.

docs/API.md, packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-matchers/src/index.js
**Summary**
Jasmine has [some special values with asymmetric equality](https://jasmine.github.io/edge/introduction#section-Matching_Anything_with_<code>jasmine.any</code>). Currently, everything works fine with Jest as well, but it is not documented and causes troubles like this: https://github.com/facebookincubator/create-react-app/pull/1127
Adding this as a part of Jest public API will encourage people to use this feature in cases like [that](https://github.com/facebook/jest/issues/2202) and also will open this for future improvements in developer experience with equality check of big objects.
=> Expose jasmine asymmetric matches as part of Jest public API

packages/jest-matchers/src/index.js, packages/jest-matchers/src/matchers.js
Adds code comments to explain the reason for changes in https://github.com/facebook/jest/pull/2198 and outline potential use cases for custom integration.
=> Add code comments documenting passing matcher results

packages/jest-cli/src/jest.js
simply tweak clear codes and check 'em in different envs
main purpose was to clear scrollback buffer, instead of just clearing screen
**Summary**
clear scroll back on watch mode. helps a lot if you have output which you want to scroll up
**Test plan**
tested with this diff just to show that I have patched version of jest running:
```diff
diff --git a/packages/jest-cli/src/jest.js b/packages/jest-cli/src/jest.js
index f499dd3..77ff3e1 100644
--- a/packages/jest-cli/src/jest.js
+++ b/packages/jest-cli/src/jest.js
@@ -285,6 +285,7 @@ const runCLI = (
argv = argv || {};
if (argv.version) {
pipe.write(`v${VERSION}\n`);
+    pipe.write(`PATCHED VERSION FROM 1861-clr-scroll-on-watch\n`);
onComplete && onComplete();
return;
}
```
on each test, I have to add `jest/packages` to `NODE_PATH` and do …
=> Clear scrollback on terminal clear in watch mode

website/server/convert.js
**Summary**
Addresses an issue introduced in #2025 where the [API Reference doc fails to be generated](https://jest-bot.github.io/jest/docs/api.html#content) when the website is built.
As part of the website generation script, the markdown source files are converted into React components, and the markdown content is HTML-fied and injected into the component. Prior to this fix, any place holders in the original markdown document will persist in the React component. This results in a script error as the variable used in the example is, as expected, not defined in this context:
```
Error: ReferenceError: received is not defined
at /Users/hramos/git/react/jest/website/node_modules/react-page-middleware/src/guard.js:27:12
at onOutputGenerated …
```
=> [Website] Allow place holders to be used in code examples

examples/async/package.json
**Summary**
This PR fixes an issue in the async example, discussed here: https://github.com/facebook/jest/issues/1939#issuecomment-266013090
The package.json fixes the babel-jest version to ^9.0.0 while for jest-cli the latest ("*") is downloaded. When downloading the packages, a version mismatch can occur which causes Jest mocks not to work.
**Test plan**
Fixing the versions of babel-jest and jest-cli to the same major version (^17.0.0), solves the version mismatching issue.
-Download packages:
yarn
-Run test example:
npm test
=> Fixed version issues with examples/async

packages/jest-editor-support/src/__tests__/TypeScriptParser-test.js, packages/jest-editor-support/src/__tests__/fixtures/global_its.example, packages/jest-editor-support/src/__tests__/fixtures/nested_its.example
**Summary**
Added tests to verify that describe.only/test/test.only work with the jest-editor-support
**Test plan**
This is the test plan
=> added tests for describe.only/test/test.only

packages/jest-matchers/src/__tests__/matchers-test.js
We have a failure on node 4 and I'm unsure why.
=> Fix matcher-test snapshot on node 4.

docs/Configuration.md, integration_tests/__tests__/test-in-root-test.js, integration_tests/test-in-root/foo.js, integration_tests/test-in-root/footest.js, integration_tests/test-in-root/package.json, integration_tests/test-in-root/spec.js, integration_tests/test-in-root/test.js, packages/jest-config/src/defaults.js
**Summary**
I have a file called `test.js` in the root of my project, and I think jests should automatically pick it up without me providing custom `testRegex`.
**Test plan**
```sh-session
$ node_modules/.bin/jest
PASS  ./test.js
✓ assets should always be an array (2ms)
✓ assets should should be reversed (1ms)
✓ should invoke callback on success (7ms)
✓ should invoke callback on error (1ms)
✓ should add file using compilation's publicPath (3ms)
✓ should used passed in publicPath
○ should handle missing `publicPath`
✓ should add file missing "/" to public path
✓ should add sourcemap to compilation
✓ should skip adding sourcemap to compilation if set to false
✓ should include hash of file content if option is set
✓ should add to css if `typeOfAsset` is css
✓ should replace compilation …
```
=> Allow files called just test.jsx? or spec.jsx? in root

CHANGELOG.md, packages/jest-cli/src/jest.js
**Summary**
See #2294 
**Test plan**
* Have a single test failure, run with `jest --watchAll --bail`.
* When changing the file, the tests should re-run.
=> Reset the “TestWatcher” state. Fixes #2294

docs/Configuration.md
**Summary**
The configuration page of the docs is amazing, but I think there are some minor inconsistencies with how code is styled...
**Code blocks**
For the default values some of them are using rendering the value as code and some as plain text
_Example of current state:_
**Double quotes**
Most of the examples for config are using single quotes, but I guess that it is more common to have the Jest config in the `package.json` than in a separate `js` config file, right (I might be wrong)? Using double quotes makes it easier to just paste into a the `package.json`
_Example of current state:_
**Test plan**
The Markdown seems to render correctly, but I was not able to figure out how to build the docs and website to fully test it.
=> Use double quotes for json in config docs

packages/jest-cli/src/reporters/CoverageReporter.js, types/TestResult.js
That should make `coverage` object garbage collectable and free up some memory.
I made it a string in case someone tries to access coverage in the future.
=> Remove coverage data after it's been merged

packages/pretty-format/src/index.js
i don't know much about it, but without this argument formatting (7 or 8 tests in www) breaks on this line https://github.com/facebook/jest/blob/master/packages/pretty-format/src/plugins/ReactElement.js#L57
cc @thejameskyle
=> add `colors` arg to complex values calls

integration_tests/testResultsProcessor/processor.js, packages/jest-cli/src/jest.js
**Summary**
The test results processor should return the newly created object, otherwise we are just inspiring mutative APIs and it kinda sucks like this. This is a breaking change for Jest 18.
**Test plan**
jest
=> Change testResultsProcessor API

packages/jest-jasmine2/src/setup-jest-globals.js, packages/jest-snapshot/src/index.js
The change is similar to the https://github.com/facebook/jest/pull/2198 and allows custom reporters to access `expected` and `actual` of the `toMatchSnapshot` matcher to provide custom diff views for `jest` snapshots.
=> Pass `toMatchSnapshot` `expected` and `actual` for custom reporters

packages/jest-cli/src/cli/index.js, packages/jest-util/src/index.js
**Summary**
I've ran `jest -h` quite a few times expecting it to behave like `jest --help` (but instead it kicks off my test suite).  This is a fairly small change that aliases `-h` to `--help` so all 3 of these commands work the same:
- `jest -h`
- `jest --help`
- `jest help`
**Test plan**
1. Cloned repo and made code changes
2. Ran `yarn build`
3. Tested a few commands by running things like
- `node ./packages/jest-cli/bin/jest.js -h`
- `node ./packages/jest-cli/bin/jest.js --help`
- `node ./packages/jest-cli/bin/jest.js help`
- `yarn jest -- -h`
- `yarn jest -- --help`
- `yarn jest -- help`
and confirming they work
4. Ran the entire test suite via `yarn test` and `yarn jest-coverage`
**Demo**
=> Add -h alias for --help

packages/jest-diff/src/diffStrings.js
**Summary**
Introduce highlighting of trailing whitespace. Kinda fixes #2287 I guess.
**Test plan**
jest
=> Highlight trailing whitespace inside snapshots

docs/API.md
**Summary**
Fix the typo and add a return value to example custom `toBe` implementation.
=> Fix expect.extend example in docs

packages/jest-editor-support/src/Process.js, packages/jest-editor-support/src/ProjectWorkspace.js, packages/jest-editor-support/src/Runner.js, packages/jest-editor-support/src/ScriptParser.js, packages/jest-editor-support/src/Settings.js, packages/jest-editor-support/src/TestReconciler.js, packages/jest-editor-support/src/__tests__/Runner-test.js, packages/jest-editor-support/src/index.js, packages/jest-editor-support/src/parsers/BabylonParser.js, packages/jest-editor-support/src/parsers/ParserNodes.js, packages/jest-editor-support/src/parsers/TypeScriptParser.js, packages/jest-editor-support/src/types.js
**Summary**
Pre v18 builds of Jest used `jsonOutputFile` but new versions use `outputFile` - unlike the rest of the project, there is no guarantee that you are running the same version of the runner as the source code. 
This lets the extension tell the process what version of Jest is in the current workspace. 
**Test plan**
Passes locally
=> Add support for running older processes of Jest

docs/API.md, docs/CLI.md, docs/Configuration.md, docs/GettingStarted.md, docs/ManualMocks.md, docs/MigrationGuide.md, docs/MockFunctions.md, docs/TimerMocks.md, docs/Troubleshooting.md, docs/TutorialAsync.md, docs/TutorialReact.md, docs/TutorialReactNative.md, docs/TutorialWebpack.md, docs/TutorialjQuery.md
As described in https://github.com/facebook/jest/issues/2366 the previous organization of the docs was inconsistent.
What we have now:
Introduction = stuff noobs all need to know about Jest
Guides = how to do thing X, where X is anything. Kind of a grab bag
Reference = the type of thing that has 50 boring aspects, we describe each one
I split CLI stuff out into its own reference doc but in general there's more to do there.
=> Reorganize the side-nav-bar

packages/jest-matchers/src/matchers.js
Apparently it's already injected from somewhere else (@cpojer told me!) and this passes all the tests so that sounds good.
=> Remove jest-snapshot dependency from jest-matchers

packages/jest-matcher-utils/src/equals.js, packages/jest-matcher-utils/src/index.js, packages/jest-matchers/src/matchers.js, packages/jest-matchers/src/spyMatchers.js, packages/jest-matchers/src/toThrowMatchers.js
I brought equals from the checked in version of jasmine ( https://github.com/facebook/jest/blob/db0f3b4902ddb360020be8f737db1fae7a8508c4/packages/jest-jasmine2/vendor/jasmine-2.5.2.js#L2787-L3048 )
I did a few tweaks:
- Imported isUndefined, isA and isDomNode
- Moved all the functions that were defined inside of functions to the global "namespace"
- Disabled lint and flow
=> Remove jasmine dependency from jest-matchers

packages/jest-jasmine2/src/jest-expect.js, packages/jest-matchers/src/__tests__/assertion-counts-test.js, packages/jest-matchers/src/__tests__/extend-test.js, packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-matchers/src/__tests__/spyMatchers-test.js, packages/jest-matchers/src/__tests__/toThrowMatchers-test.js, packages/jest-matchers/src/index.js
This way we can have the same top level api as expect npm module:
```js
const expect = require('jest-matchers');
```
=> Change the exports of jest-matcher to be just expect

docs/ExpectAPI.md, docs/JestObjectAPI.md, docs/ManualMocks.md, docs/TimerMocks.md, docs/TutorialReact.md, docs/TutorialReactNative.md, docs/TutorialjQuery.md
This replaces "it" with "test" in a lot of places. It also improves the documentation around expect.extend, which I found difficult to follow while replacing it->test in it.
=> Misc fixes

docs/ExpectAPI.md
**Summary**
Fix them braces in `toBeDivisibleBy` example
=> Fix toBeDivisibleBy braces

website/src/jest/css/jest.css
The sidebar is now in a fixed position in the docs. Tested in Chrome and Firefox. Firefox slightly obscures the footer when the viewport is not tall enough, but it does not seem like a big deal.
See screencast of this sidebar in action on Chrome: https://cl.ly/iWbs
See screencast of this sidebar in action on Firefox: https://cl.ly/iWJJ
=> Fixed position sidebar

README.md, docs/ExpectAPI.md
Two sorts of problems this fixes. One is that toThrowError and toThrow are now aliases. The other is that previously in a lot of places I stuck a "describe" block when it wasn't necessary, because I thought we were encouraging that. Nowadays it seems clear we are *not* encouraging describe blocks if they are not necessary. So I just removed single-test describe blocks from our code samples in the "expect" reference doc, it should make things a bit cleaner while not really removing useful content.
=> Throwing & Describing

packages/jest-jasmine2/src/jest-expect.js, packages/jest-matcher-utils/src/index.js, packages/jest-matchers/package.json, packages/jest-matchers/src/index.js, packages/jest-matchers/src/jasmine-utils.js, packages/jest-matchers/src/matchers.js, packages/jest-matchers/src/spyMatchers.js, packages/jest-matchers/src/toThrowMatchers.js
In #2389 I moved equals but it turns out there are more!
I renamed the file `expect.js` to `jasmine-utils` and moved it to `jest-matchers` instead of `jest-matcher-utils`.
This is the big thing, otherwise it's been pretty much copy and pasted from jasmine.
=> Move asymetric matchers from jasmine to jest

docs/CLI.md
I based this on what you get if you type `jest --help`. It seems useful to have this doc since we do refer to the CLI a number of times. Included some instructions for the `npm test -- -jest-flags-go-here` thing too.
=> better CLI doc

CONTRIBUTING.md, docs/Babel.md, docs/MoreResources.md, docs/TimerMocks.md, docs/Troubleshooting.md, docs/TutorialAsync.md, docs/Webpack.md, website/siteConfig.js, website/src/jest/index.js
Expand the More Resources section.
Reduce number of CTAs on the home page.
Do not use single-character aliases in examples.
Fixes #2383
=> Update Homepage and More Resources

website/core/nav/HeaderNav.js
=> Add API Reference to Navigation Header

packages/jest-cli/src/jest.js
#2427 for more info
This PR treats arrows as no-op to prevent Jest patterns to break in watch mode, but I think in the future we could do some cool stuff like:
* left/right arrows will actually move the cursor and allow you to add/remove text where the cursor is.
* up/down arrows could show some typeahead history, for example. If my last 3 patterns where `react.*dom`, `react` and `component` then using the up arrow while in "pattern mode" will set the current pattern to `component`, using it again will set it to `react`, etc.
**Before**
**After**
=> Treat arrows as no-op while entering a pattern FIX #2427

packages/jest-editor-support/index.d.ts, packages/jest-editor-support/package.json
**Summary**
Provides typings for people using this module in TypeScript code. (like vscode-jest)
=> add typings file for jest-editor-support package

package.json
see discussion in: https://github.com/facebook/jest/issues/2356
this update should remove the warning:
`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
=> chore: update to newer version of istanbul-api, removing deprecation warning

packages/jest-cli/src/runTest.js, packages/jest-runtime/src/cli/index.js, packages/jest-util/src/FakeTimers.js, packages/jest-util/src/index.js, packages/jest-util/src/setGlobal.js, yarn.lock
**Summary**
Alternative fix for #2457.
**Test plan**
jest passes on node 7.3 again.
=> Add a non-strict module to set fields on the global object for node 7.3.

integration_tests/__tests__/__snapshots__/coverage_report-test.js.snap, integration_tests/__tests__/coverage_report-test.js, packages/jest-cli/src/cli/args.js, packages/jest-config/src/normalize.js
Expose the `collectCoverageOnlyFrom` option on the cli
==
The option was already available through configuration,
I've exposed it and add an integration test for testing it.
The option accept an array, so it can be called in multiple ways:
`jest <...> --coverage --collectCoverageOnlyFrom fileA.js fileB.js -- <testPattern>`
if we don't like using the `--` delimeter it's possible to use the coverage flag _after_ collectCoverageOnlyFrom:
`jest <...> --collectCoverageOnlyFrom fileA.js fileB.js --coverage <testPattern>`
**Test plan**
I've add an integration test.
`yarn test`
=> expose --collectCoverageOnlyFrom

packages/jest-runtime/src/__tests__/Runtime-mock-test.js
**Summary**
I was looking into the Jest Runtime folder and I found out that two tests were duplicated.
Both are running expectations on "RegularModule" while the second one should check "ManuallyMocked".
**Test plan**
I made the change, ran `npm test` and tests are still green.
=> Fix Jest Runtime mock test

packages/jest-config/src/index.js, packages/jest-config/src/loadFromFile.js, packages/jest-config/src/loadFromPackage.js
Pass CLI arguments when loading config from file.
Fixes #2472. 
Expected env should be `node`:
```
jest --config path-to-config --env node
```
=> Pass CLI args when loading config from file

packages/jest-config/src/__tests__/__snapshots__/normalize-test.js.snap, packages/jest-config/src/__tests__/normalize-test.js, packages/jest-config/src/normalize.js
**Summary**
Provides a better error for invalid `transform` config option. Fixes https://github.com/facebook/jest/issues/2228
**Test plan**
jest
=> Better error for invalid transform config

packages/babel-jest/package.json
Normally semver takes care of this but I'd like to ensure that existing Create React App users will get this bugfix update next time they update CRA (and thus Jest). It fixes `displayName` inference for functional components when coverage is enabled: https://github.com/facebookincubator/create-react-app/issues/1010#issuecomment-270907699.
=> Bump minimal version of babel-plugin-istanbul

docs/ManualMocks.md, docs/MigrationGuide.md, docs/MockFunctions.md, docs/SetupAndTeardown.md, docs/TimerMocks.md, docs/TutorialAsync.md
After some thought, this guide serves as a good intro to mocking. I've moved it to Introduction, and moved things around in Guides to fix the sequence of links.
=> Move Mock Functions to Introduction

package.json
**Summary**
As discussed with @cpojer, we should to track coverage for all packages we expose.
This dramatically lowers coverage, which imply we need to write more tests.
=> Collect coverate from all packages

.travis.yml, package.json
**Summary**
I messed around with the setup a lot and had trouble with yarn install so I moved travis to use yarn link. I had a cached version of node_modules locally and didn't realize the new code doesn't set up eslint properly for local development. This fixes it for both travis and local development.
**Test plan**
yarn lint works locally
=> Fix local eslint setup.

packages/eslint-plugin-jest/README.md, packages/eslint-plugin-jest/docs/rules/no-skipped-tests.md, packages/eslint-plugin-jest/src/index.js, packages/eslint-plugin-jest/src/rules/__tests__/no-skipped-tests-test.js, packages/eslint-plugin-jest/src/rules/no-skipped-tests.js
**Summary**
Adding a `no-skipped-tests` rule to `eslint-plugin-jest`. Also took the opportunity to add a recommended rule configuration.
**Test plan**
For `no-skipped-tests` rule, running the unit test suite should be sufficient. To check the recommend configuration create a test project with an `.eslintrc`:
```js
{
"plugins": [
"jest"
],
"extends": ["plugin:jest/recommended"],
"parser": "babel-eslint"
}
```
and eslint should error on:
```js
it.only('foo', () => {});
```
=> Eslint no skipped tests

packages/jest-editor-support/src/Runner.js, packages/jest-editor-support/src/__tests__/Runner-test.js
**Summary**
Node process wasn't exiting on editor termination.  Therefore even after closing the editor the process kept running on windows.
**Test plan**
Verified that the process was no longer running after closing the editor and calling `closeProcess`
=> windows doesn't exit node processes when it's supposed to

packages/jest-runtime/src/__tests__/Runtime-requireModuleOrMock-transitive-deps-test.js, packages/jest-runtime/src/__tests__/test_root/depOnMappedModule.js, packages/jest-runtime/src/__tests__/test_root/mapped_dir/moduleInMapped.js, packages/jest-runtime/src/index.js
**Summary**
fixes #2463 
adds support for testing jspm/system-js based apps that often use aliases for modules or for module paths.
**Test plan**
Added test to: packages/jest-runtime/src/__tests__/Runtime-requireModuleOrMock-transitive-deps-test.js 
test requires a module that in turn requires a mapped module (aliased) using moduleNameMapper configuration. 
Before the fix, trying to mock the aliased module would silently fail
=> #2463 - fix for jest-runtime _normalizeID doesnt provide determinstic results for all mocks

packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/TestWorker.js, packages/jest-cli/src/__tests__/TestRunner-test.js, packages/jest-cli/src/__tests__/watch-test.js, packages/jest-cli/src/constants.js, packages/jest-cli/src/jest.js, packages/jest-cli/src/lib/__tests__/getMaxWorkers-test.js, packages/jest-cli/src/lib/__tests__/logDebugMessages-test.js, packages/jest-cli/src/lib/__tests__/setWatchMode-test.js, packages/jest-cli/src/lib/buildTestPathPatternInfo.js, packages/jest-cli/src/lib/createHasteContext.js, packages/jest-cli/src/lib/getMaxWorkers.js, packages/jest-cli/src/lib/logDebugMessages.js, packages/jest-cli/src/lib/setWatchMode.js, packages/jest-cli/src/runJest.js, packages/jest-cli/src/watch.js, packages/jest-haste-map/src/ModuleMap.js, packages/jest-haste-map/src/index.js, packages/jest-runtime/src/index.js, types/HasteMap.js
**Summary**
This extracts the watch mode to its own module, which was suggested by @cpojer as a prerequisite for #2324.
This should make watch mode faster and removes some duplicated code from `jest.js`.
Now we only need to reconcile with the file system only when a file is added/removed, but not otherwise
More info https://github.com/facebook/jest/pull/2324#issuecomment-267149669 I hope that this will also allow us to add more tests in the future.
**Known issues:**
~Test interruption is not working and I'm not sure why. It seems that I'm setting the correct state in the `TestWatcher` :(~ UPDATE: I first thought that the issue was introduced in this PR, but it seems that it is also happening in master. Based on my understanding it was introduced in #2312
=> Extract watch mode

packages/jest-environment-jsdom/src/index.js, packages/jest-environment-node/src/index.js, packages/jest-mock/src/__tests__/jest-mock-test.js, packages/jest-mock/src/index.js, packages/jest-runtime/src/index.js, packages/jest-util/src/FakeTimers.js, packages/jest-util/src/__tests__/FakeTimers-test.js, types/Environment.js
Right now it returns a class that you've got to instantiate which is not the API we want. This PR makes it return an instance and adds the ModuleMocker class as an attribute.
Test Plan:
Make sure tests are passing
Also make sure that we can write this :)
```js
var mock = require('jest-mock');
const fn = mock.getMockFn();
```
=> Make jest-mock return an object

packages/jest-mock/README.md, packages/jest-mock/src/__tests__/jest-mock-test.js, packages/jest-mock/src/index.js, packages/jest-runtime/src/index.js, packages/jest-util/src/FakeTimers.js
**Summary**
jest-mock now has the same `fn` API as the `jest` object. cc @vjeux please merge :)
**Test plan**
yarn test
=> Rename `getMockFn` to `fn` in `jest-mock`.

packages/jest-runtime/src/__mocks__/createRuntime.js, packages/jest-runtime/src/__tests__/Runtime-mock-test.js, packages/jest-runtime/src/index.js
**Summary**
I'm working on a CLI package that takes in the path of a config file as an argument (e.g. `--config foo.config.js`). I then resolve the config file path to an absolute path (e.g. `/absolute/path/to/foo.config.js`) and dynamically `require` it.
When writing tests with Jest, I found that even after registering a virtual `jest.mock` for the absolute path of a config file, Jest was throwing `Cannot find module '/absolute/path/to/foo.config.js' from 'loadConfig.js'`
**`src/loadConfig.js`**
```js
import * as path from 'path';
export default function loadConfig(configPath) {
return require(path.resolve(configPath));
}
```
**`src/__tests__/loadConfig-test.js`**
```js
import * as path from 'path';
import loadConfig from '../loadConfig';
const configPath = 'foo.config.js';
const …
```
=> Mock Virtual Modules via Absolute Path

packages/jest-cli/src/TestRunner.js
This change ends the worker farm when tests get interrupted...
**Before**
**After**
Test plan: I didn't add a test for this since it required a lot of extra mocks, let me know if I should add it 😄
=> End worker farm when tests get interrupted

packages/jest-cli/src/__tests__/__snapshots__/watch-test.js.snap, packages/jest-cli/src/__tests__/watch-test.js, packages/jest-cli/src/watch.js
**Summary**
In the extract watch mode PR I changed some `console.log` to `pipe.write` https://github.com/facebook/jest/pull/2362#discussion_r95072873 which causes a small regression in watch mode when entering and leaving 'pattern' mode...
**Before**
**After**
**Test plan**
I added a test to cover this case and moved some of the implementation of the test to use snapshots
=> Fix pipe.write regression introduced after #2362

danger/package.json, dangerfile.js
**Summary**
Danger was breaking on the node4 CI runs - https://travis-ci.org/facebook/jest/jobs/190225150
This replaces the array includes with a lodash one, which comes from Danger's dependencies.
**Test plan**
If this greens, then we're 👍
=> [Danger] Ensure node 4 builds fine on travis

dangerfile.js
**Summary**
Danger was checking for files without copyright, but when creating the regular expression from a string the initial escape for `(` and `)` was already evaluated, so it wouldn't match.
Also the flow+strict check was filling an array with filter, but that array contains correct files instead of wrong files.
**Test plan**
I ran the code manually to check the result of the regex before and after, 
also looked at the code filtering.
=> Fixes dangerfile

packages/jest-cli/src/__tests__/watch-test.js
**Summary**
Node 4 doesn't support `...`. cc @rogeliog 
**Test plan**
`jest watch` on node 4.
=> Fix test on node 4.

docs/TutorialReact.md
The regexp used in `"transform"` (`"^.+\\.js"`) in the example was different than one used in [Webpack tutorial](https://github.com/facebook/jest/blob/new-docs/docs/Webpack.md) (`"\\.js"`) but matched the same file (everything ending with string `.js`). 
This one introduces less space for error. Or is there an edge case it doesn't cover?
**Explain the motivation for making this change. What existing problem does the pull request solve?**
1. Keep regexp with same effect consistent across examples
2. Reduce chance of error being introduced
=> Standarize file matching regexp

packages/jest-cli/src/cli/args.js, packages/jest-config/src/normalize.js
**Summary**
Fixes #2501. I've also removed `colors` from `normalize.js`, because it's not a valid config option and added a note about switching colors off. This may need linguistic adjustments though.
**Test plan**
works on my machine
=> Add 'color' as valid cli option, remove from config

packages/jest-resolve/src/index.js, packages/jest-runtime/src/index.js
**Summary**
I am trying to fix a bug
**Test plan**
I have the following configuration
```json
{
"moduleNameMapper": {
"\\.css$": "identity-obj-proxy",
"\\.sass$": "identity-obj-proxy"
}
}
```
When I run tests, only latest pattern will be applied, the first `\\.css$` regexp is totally ignored because current implementation uses mapper path as a unique key, which is not always correct.
=> Do not overwrite existing module mocks

packages/eslint-config-fb-strict/index.js
**Summary**
```
it('is really long', () => {}) // was always allowed
test('a really long string', () => {}) // is now allowed
```
**Test plan**
write a long line with `test` and eslint won't yell at you.
=> `test` is now ignored in long lines.

packages/jest-cli/package.json, packages/jest-cli/src/__tests__/__snapshots__/watch-pattern-mode-test.js.snap, packages/jest-cli/src/__tests__/watch-pattern-mode-test.js, packages/jest-cli/src/patternMode.js, packages/jest-cli/src/watch.js
There are a some issues when using typeahead in different terminals mainly (xterm vs screen)
See https://github.com/sindresorhus/ansi-escapes/issues/1 for more info about why this happens
To fix this instead of clearing the whole screen every time we are only clearing it then the user goes into pattern mode.
* For terminals that do not support `ansiEscapes.cursorRestorePosition` we use `ansiEscapes.cursorTo` as a fallback
* For terminals that do support `ansiEscapes.cursorRestorePosition` we use that.
**Before**
**After**
I've been testing typeahead mode in the following environments and it seems fine.
- iTerm2
- with zsh
- with bash
- Hyper
- Terminal.app
- with tmux
- with a Docker container
- with sh
- with bash
- with zsh
Here is a mega gif how it works in each and every env
NOTE: I …
=> Make typeahead play better with different terminals

packages/jest-config/src/__tests__/normalize-test.js, packages/jest-config/src/normalize.js
Summary
In certain edge cases a javascript file might be deeply nested in a verbose folder structure
(I am looking at you, Java) and therefore cause jests haste-map can cause an ENAMETOOLONG error.
By hashing the name we limit its max size to a length of 32 + additional parts for the cost of making
the cache actually readable.
fixes #2538
Again it might be wise to check for the actual length the normalizer would produce and then only fallback to hashing when the produces name looks too verbose. Therefore keeping the ability to have a human readable hash. (then again not sure if that is needed?)
=> Hash directory used as name to prevent enametoolong

packages/jest-runtime/src/__tests__/Runtime-jest-spyOn-test.js, packages/jest-runtime/src/index.js
**Summary**
Fixes #2534
**Test plan**
Added tests for this
=> Add spyOn to jest-runtime

packages/jest-cli/src/TestWorker.js
Killing the main process while the tests are still running causes this error in the workers
```
(node:56445) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: channel closed
```
**Before**
**After**
* @cpojer Does this look like enough to fix #2385?
* Is there a more appropriate way of fixing this?
**Test plan**
I'm not sure what is the best way to add tests to this type of issues.
=> Fix unhandled promise rejection in worker when parent has exited

packages/jest-runtime/src/__tests__/Runtime-jest-spyOn-test.js
cc @rogeliog @vjeux 
Merged the behavior change from @vjeux and also @rogeliog's API addition which were conflicting. We are now calling the original function when using spyOn.
=> Fix test because of behavior change.

packages/jest-runtime/package.json, packages/jest-runtime/src/__tests__/Runtime-requireModule-test.js, packages/jest-runtime/src/__tests__/test_root/UTF8WithBOM.js, packages/jest-runtime/src/__tests__/test_root/UTF8WithBOM.json, packages/jest-runtime/src/index.js
**Summary**
Currently `require`ing JSON encoded in utf-8 w/ BOM will error because the BOM isn't stripped before being passed to `JSON.parse`.
It looks although [Node core strips the BOM before parsing JSON](https://github.com/nodejs/node/blob/master/lib/module.js#L585) so I've done the same here.
**Test plan**
Includes unit tests to test json and js modules encoded in utf-8 w/ BOM.
**NOTES**
- If [`strip-bom`](https://www.npmjs.com/package/strip-bom) is a bit too `left-pad`y I could just copy it from Node -- https://github.com/nodejs/node/blob/master/lib/internal/module.js#L47
=> Handle JSON modules encoded with a BOM

packages/jest-haste-map/src/__tests__/__snapshots__/index-test.js.snap, packages/jest-haste-map/src/__tests__/getMockName-test.js, packages/jest-haste-map/src/__tests__/index-test.js, packages/jest-haste-map/src/getMockName.js, packages/jest-haste-map/src/index.js, packages/jest-runtime/src/__tests__/Runtime-mock-test.js, packages/jest-runtime/src/__tests__/test_root/__mocks__/nested1/nested2/nested3.js, packages/jest-runtime/src/__tests__/test_root/nested1/nested2/nested3.js
**Summary**
Following #2475 this PR enables manual mocks with nested folders.
You can now mock dependencies with nested folders like:
`jest.mock('react-styleguidist/src/rsg-components/Playground/PlaygroundRenderer')`
Where the manual mock directory structure is the following:
This PR exists mostly to get an early feedback from the team and it could be improved.
For example, I attached the `getMockName` function to the `HasteMap` class to make testing easier but we can find a better solution (transforming it to an instance method?).
**Test plan**
I tried it on a [project](https://github.com/MicheleBertoli/snapguidist) where I actually need it, and it worked.
Before (Jest loads the actual package):
After (It works):
=> Enable manual mocks with nested folders

package.json, packages/babel-plugin-jest-hoist/package.json, packages/jest-changed-files/package.json, packages/jest-cli/package.json, packages/jest-config/package.json, packages/jest-diff/package.json, packages/jest-editor-support/package.json, packages/jest-environment-node/package.json, packages/jest-file-exists/package.json, packages/jest-haste-map/package.json, packages/jest-jasmine2/package.json, packages/jest-matcher-utils/package.json, packages/jest-matchers/package.json, packages/jest-mock/package.json, packages/jest-repl/package.json, packages/jest-resolve-dependencies/package.json, packages/jest-resolve/package.json, packages/jest-runtime/package.json, packages/jest-snapshot/package.json, packages/jest-util/package.json, packages/pretty-format/package.json, packages/pretty-format/perf/test.js
We only support testing on the top level of the repo.
=> Remove unnecessary test commands from packages. They don’t work anymore.

docs/Configuration.md
**Summary**
There was a typo in `snapshotSerializers` docs.
=> Fix typo in snapshotSerializers docs

packages/jest-diff/src/index.js, packages/jest-matcher-utils/src/__tests__/__snapshots__/index-test.js.snap, packages/jest-matcher-utils/src/index.js, packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/asymmetric-matchers-test.js, packages/jest-matchers/src/asymmetric-matchers.js, packages/jest-matchers/src/index.js, packages/jest-matchers/src/jasmine-utils.js, packages/jest-matchers/src/matchers.js, packages/pretty-format/src/__tests__/AsymmetricMatcher-test.js, packages/pretty-format/src/plugins/AsymmetricMatcher.js
**Summary**
Fixes https://github.com/facebook/jest/issues/2397
=> Pretty-print asymmetric matchers

packages/jest-snapshot/src/index.js
**Summary**
Removing `snapshotState` and `getSnapshotState` as they don't seem to do _anything_. The former is always `undefined`, and neither are ever used in the code base. Also, this removes the "shadowing" with the other `snapshotState` within `toMatchSnapshot`.
**Test plan**
Ran the tests, scanned through the code base. Couldn't find any use of these. The setup in `setup-jest-globals.js` relies on `initializeSnapshotState` which returns the initialized snapshot state but doesn't write to the `snapshotState` variable.
=> Remove always undefined snapshotState

packages/jest-config/src/__tests__/__snapshots__/normalize-test.js.snap, packages/jest-config/src/deprecated.js, packages/jest-validate/README.md, packages/jest-validate/package.json, packages/jest-validate/src/__tests__/__snapshots__/validate-test.js.snap, packages/jest-validate/src/__tests__/validate-test.js, packages/jest-validate/src/errors.js, packages/jest-validate/src/index.js, packages/jest-validate/src/types.js, packages/jest-validate/src/utils.js, packages/jest-validate/src/validate.js, packages/jest-validate/src/warnings.js
**Summary**
Add "did you mean" to warnings with the help of Levenshtein. I'm also exporting a helper function to create that message, so it can be used in other warnings and errors (like CLI ones)
This PR also adds quotation marks around config keys, as I thought this is useful for terminals without bolding enabled:
**Test plan**
jest
=> Add "did you mean" to jest-validate

packages/jest-validate/src/__tests__/__snapshots__/validate-test.js.snap, packages/jest-validate/src/warnings.js
I think "typing mistake" is better use of language for a tool like Jest (or jest-validate). @thymikee it's your decision: approve or request changes on this. After that, we can tag jest-validate 18.2.
=> “typo” -> “typing mistake”

packages/jest-config/src/index.js, packages/jest-validate/package.json, packages/jest-validate/src/__tests__/fixtures/jestConfig.js, packages/jest-validate/src/__tests__/validate-test.js
**Summary**
`jest-validate` had a circular dev dependency of `jest-config` for testing purposes. Removed this in favour of fixtures.
**Test plan**
jest
=> Remove circular dependency from jest-validate

docs/Webpack.md
make clear that the transform setting overwrite the default `babel-jest` transformation
**Summary**
**Test plan**
=> add note for babel-jest user on transform feature

packages/jest-cli/src/__tests__/__snapshots__/watch-pattern-mode-test.js.snap, packages/jest-cli/src/__tests__/watch-pattern-mode-test.js, packages/jest-cli/src/lib/__tests__/__snapshots__/highlight-test.js.snap, packages/jest-cli/src/lib/__tests__/highlight-test.js, packages/jest-cli/src/lib/highlight.js, packages/jest-cli/src/lib/terminalUtils.js, packages/jest-cli/src/patternMode.js
**Summary**
Fixes: #2597 
This truncates the results when there is not enough space and adds highlighting for several non trivial cases. I needed to do some extra parsing because the string that is used for filtering all the files and the one that we output is not the same_(full path vs formatted relative path)_
1. Highlight only the `...` when the pattern only matches something in the `rootDir`
1. Highlight the `...` and the beginning of the file path when the pattern matches something in the `rootDir` + something else. For example this regex `/Users/myuser/.*packages`
**Test plan**
* I'm still curious how all of this works in Windows 
* There is still one case that I know of that doesn't get highlighted. This is when the pattern matches only something in the `rootDir` and the result is …
=> Truncate results in typeahead

packages/jest-cli/src/__tests__/watch-pattern-mode-test.js
This was happening because we are mocking ansi-escapes.... Another possible solution is to also mock `cursorDown()`
=> Mock process.on in test to prevent CI failure

docs/ManualMocks.md
**Summary**
Add documentation regarding the behavior of manual mocks when used with node modules - the mocks are given precedence even when `jest.mock('moduleName')` is not explicitly called.
This behavior is contrary to how manual mocks work with application modules. It appears to be a bug when it is actually an implementation detail. There are a few issues already reporting this behavior: #2355, #2354, #1927 
Hopefully the language I've used here is clear enough but I'm happy to revise if it's still confusing.
**Test plan**
n/a - documentation only
=> add detail regarding manual mocks and node modules

packages/babel-jest/README.md
**Summary**
The path for the transform did not work.
`<rootDir>/node_modules/babel-jest` did result in `TypeError: Object.values is not a function`.
After digging in `jest-config` I found the transform provided by default is:
```
"transform": {
"^.+\\.jsx?$": "babel-jest"
}
```
I wanted to save other developers time when setting up custom `transform`s and want to continue using `babel-jest`.
=> Update default transform for babel-jest

packages/jest-matcher-utils/src/index.js, packages/jest-matchers/src/toThrowMatchers.js
**Summary**
Fixes #2673
**Test plan**
I may want to add a test for this
=> Highlight whitespace in expected/received

packages/jest-runtime/src/index.js
**Summary**
`getMockModule` is called even when it is not used. After this patch `yarn test` is running ~2 seconds faster in my computer. I am not familiar with the code to estimate the impact, but it worth to be fixed anyway.
**Test plan**
`yarn test`
Before:
After:
=> Avoid unnecessary call to getMockModule

packages/jest-cli/src/SearchSource.js
Jest was not matching any tests when the pattern was a directory
=> Fix findMatchingTests for directories

package.json, packages/jest-haste-map/src/__tests__/index-test.js, packages/jest-haste-map/src/index.js
**Summary**
Fixes #2592 and will fix https://github.com/facebook/react-native/issues/11301 once Jest 19 is out.
Explanation: since we don't store the haste map in watch mode, it is ok to "retain all files". This will issue change events when files in node_modules have changed, which will make the watch mode in Jest 19 behave more like Jest 18 (where changes to node_modules would re-run Jest), as well as fix something in react-native-packager.
Related, I kinda feel like retainAllFiles has to go. It makes things faster on our giant codebase but gives a bunch of trouble.
**Test plan**
* Manual testing
* Added a test
=> jest-haste-map: Emit change events if a file in node_modules has changed

docs/Configuration.md
```
[...] using `'<rootDir>'` as a string token in any other path-based config settings to refer back to this value.
```
Changed to:
```
[...] using `'<rootDir>'` as a string token in any other path-based config settings will refer back to this value.
```
**Summary**
**Test plan**
=> Fix typo in rootDir section of Configuration Page

dangerfile.js
ES modules are strict mode by default, so the check should look for use of "import"/"export" to determine if flagging is required.
Closes #2708
=> Patch dangerfile to only do "use strict" checks on non-es modules

danger/README.md, danger/package.json, danger/yarn.lock, dangerfile.js
**Summary**
The latest Danger release adds `danger pr` which makes it trivial to test a PR against Danger. 
This PR adds docs to the danger folder, and a call to action to read it showing you how to make changes and verify that what you want to change has changed correctly.
**Test plan**
=> Updates Danger, and adds docs on how to change the Dangerfile

packages/jest-resolve/src/index.js, packages/jest-runtime/src/index.js, packages/jest-util/src/index.js
**Summary**
Almost all methods and functions used by `_normalizeID` are from `resolver`. Because of that, it makes much more sense to move it to `resolver` and pass `virtualMocks` from `runtime` since it is the only `runtime`'s data required. Besides that, this patch includes a refactor of use of `this._getVirtualMockPath` to `getModulePath`.
I want to contribute with the project but I am not familiar with the code. I will read it and refactor everything that would help to understand the code. Right now, my focus is in `jest-runtime` package and I intend to move to other packages as well.
If you guys don't want to receive patches where the purpose is only refactor the code to improve design and readability, you can let me know and I won't bother you guys anymore.
**Test plan**
I am not …
=> Move jest-runtime/_normalizeID to jest-resolve/getModuleID

integration_tests/__tests__/__snapshots__/failures-test.js.snap, integration_tests/__tests__/__snapshots__/snapshot-serializers-test.js.snap, integration_tests/__tests__/__snapshots__/snapshot-test.js.snap, integration_tests/__tests__/__snapshots__/stack_trace-test.js.snap, integration_tests/__tests__/__snapshots__/testNamePattern-test.js.snap, packages/jest-config/src/__tests__/__snapshots__/normalize-test.js.snap, packages/jest-diff/src/__tests__/__snapshots__/diff-test.js.snap, packages/jest-matcher-utils/src/__tests__/__snapshots__/index-test.js.snap, packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/__snapshots__/spyMatchers-test.js.snap, packages/jest-matchers/src/__tests__/__snapshots__/toThrowMatchers-test.js.snap, packages/jest-runtime/src/__tests__/__snapshots__/transform-test.js.snap, packages/jest-snapshot/src/State.js, packages/jest-snapshot/src/__tests__/utils-test.js, packages/jest-snapshot/src/utils.js, packages/jest-util/src/__tests__/__snapshots__/FakeTimers-test.js.snap, packages/jest-util/src/__tests__/__snapshots__/messages-test.js.snap, packages/pretty-format/src/__tests__/pretty-format-test.js, packages/pretty-format/src/index.js, packages/pretty-format/src/plugins/ReactElement.js, packages/pretty-format/src/plugins/ReactTestComponent.js, packages/pretty-format/src/plugins/escapeHTML.js
There were many issues with snapshot test escaping:
- When escaping backtick, it didn't escape backslash
- Double quote escaping was overzealous and also escaped single quotes
- JSX text didn't use HTML escaping
- Regex escaping didn't escape all the control characters that should be
Because of the first one, you couldn't do eval(snapshot) and get the correct value, in order to make it kind of work, an unescape function was created that did ... something. Now that escaping is done properly we don't need it anymore.
This is a breaking change as all the double quotes now need to be escaped which triggers a ton of failures.
Fixes #1789
=> [Breaking change] Properly escape snapshots

packages/jest-cli/package.json
Updates the dependency of `node-notifier` to the latest [newly released `v5.0.1`](https://github.com/mikaelbr/node-notifier/blob/master/CHANGELOG.md#v500).
With this change there are a lot fewer dependencies as the built in CLI is removed, and other dependencies are trimmed. 
No change in the way it's used in `jest-cli`. Tested on macOS and Windows where it works as expected.
---
As an aside:
With the new `node-notifier` input on macOS is possible. Could be possible to add buttons to rerun the tests. Don't know if this is interesting, but something to think about.
=> Updates node-notifier dep of jest-cli to v5

packages/jest-util/src/__tests__/__snapshots__/validateCLIOptions-test.js.snap, packages/jest-validate/src/__tests__/__snapshots__/validate-test.js.snap
**Summary**
Fixes Travis.
Btw, this looks a bit weird with "unescaped" backslash now, when comparing old/new snapshot
=> Update snapshots to new format

packages/jest-cli/package.json, packages/jest-config/package.json
**Summary**
Drops `jest-mock` from `jest-cli` and `jest-config`.
Incidentally, `jest-mock` is also required by `jest-runtime`, but it is [only used for the type import](https://github.com/facebook/jest/blob/054f9c35a7733e785b2b615f3ccd62f32d8cbc1e/packages/jest-runtime/src/index.js#L18).  Would that mean that it could/should be a devDependency?
**Test plan**
=> Remove `jest-mock` from `jest-cli` and `jest-config`.

packages/jest-runtime/package.json, packages/jest-runtime/src/index.js, types/Mock.js
**Summary**
Hoists `MockFunctionMetadata` and `ModuleMocker` from `jest-mock` to `types/Mock`.  This allows `jest-runtime` to reference `types/Mock` for those types instead of requiring a runtime dependency of `jest-mock`.
**Test plan**
=> Hoist `jest-mock` types to `types/Mock`.

dangerfile.js
It should now properly ignore flowtype-related import/export statements, as they aren't actually related to ES modules at all and will not trigger auto strict-mode.
@thymikee & @cpojer I added a commented link to a test suite of sorts. Should be good to go.
=> Revised dangerfile ES module detection regex

.github/ISSUE_TEMPLATE.md
**Summary**
There's a growing number of "help me" issues. Maybe we should stress a bit more that Jest issue tracker is not a help forum and point users to Support page, which includes links to SO and Discord?
=> Update ISSUE_TEMPLATE.md to include Support page

docs/SnapshotTesting.md
**Summary**
The link points to README.md that says this repository was moved into Jest.
P.S. Found unexpectedly while studying the well-organized new docs! Nice theme color too.
**Test plan**
Please verify that I copied the link correctly :)
=> Docs: change pretty-format link from thejameskyle to jest packages

examples/snapshot/__tests__/__snapshots__/Link.react-test.js.snap, packages/pretty-format/src/__tests__/pretty-format-test.js, packages/pretty-format/src/plugins/escapeHTML.js
**Summary**
Snapshots with React are used in different contexts, not just on the web. We don't need to replace all html entities. It does make sense however for < and > because otherwise it would break the pretty-printed JSX.
cc @vjeux
**Test plan**
jest
=> Don’t escape html entities except for < and >.

packages/jest-config/src/__tests__/normalize-test.js, packages/jest-config/src/normalize.js
**Summary**
When you have preset file without `setupFiles` property and you try to extend it with config that has `setupFiles` property, `jest` throws an exception;
**Test plan**
1. Create preset file without `setupFiles`
2. Create config with `setupFiles`
3. Run `jest`
=> Preset without setupFiles fix

docs/JestObjectAPI.md
**Summary**
There were 2 links in `JestObjectAPI.md` that pointed to the wrong place (I assume left unchecked from the redesign).
I've changed these to where I believe they are supposed to go.
**Test plan**
Since these are only docs changes, the only things I thought to were check the docs locally with the server running from `npm start` and running `npm test`. Everything rendered properly in the browser test, and no tests failed.
=> Fixed links in JestObjectAPI docs

packages/jest-jasmine2/src/jest-expect.js, packages/jest-matchers/src/index.js
**Summary**
Does first bullet point in https://github.com/facebook/jest/pull/2746#issuecomment-276344253
Move `expect.addSnapshotSerializer = addSerializer;`
* from `packages/jest-matchers/src/index.js`
* to `packages/jest-jasmine2/src/jest-expect.js`
Thank you for your patience. Not sure why test seemed to fail when I tried to do it in #2746
**Test plan**
`integration_tests/snapshot-serializers/__tests__/snapshot-test.js` now [still] passes
=> Move expect.addSnapshotSerializer to jest-jasmine2

docs/Configuration.md, docs/ExpectAPI.md
**Summary**
Configuration.md
* capitalization: noticed these are the only all-lowercase occurrences of JavaScript and React in prose content of docs.
* cross-reference: readers need the other direction with brief contrasting explanation
ExpectAPI.md
* removed an extra empty line from when I moved the code example
**Test plan**
Review by a second pair of eyes, thank you :)
P.S. Do we have a doc convention to tell people which version of Jest, as discussed in http://facebook.github.io/jest/docs/expect.html#expectaddsnapshotserializerserializer
=> Docs: capitalization and cross-reference in Configuration.md

docs/Webpack.md
**Summary**
I went the long way around to find this... Having it easily available in the docs would be nice.
Ref #2442
**Test plan**
N/A
=> Add note to Webpack docs about how to handle dynamic imports

packages/jest-cli/package.json, packages/jest-cli/src/SearchSource.js, packages/jest-cli/src/runTest.js, packages/jest-resolve-dependencies/package.json, packages/jest-resolve-dependencies/src/index.js, types/Resolve.js
**Summary**
Hoists `Resolver` and `ResolveModuleConfig` from `jest-resolve` to `types/Resolve`.  This allows `jest-cli` and `jest-resolve-dependencies` to refer to `types/Resolve` for those types instead of requiring a runtime dependency of `jest-resolve`.
**Test plan**
=> Hoist `jest-resolve` types to `types/Resolve`.

integration_tests/babel-plugin-jest-hoist/.babelrc, integration_tests/babel-plugin-jest-hoist/__tests__/integration-test.js, integration_tests/babel-plugin-jest-hoist/package.json, packages/babel-plugin-jest-hoist/src/index.js
=> Prevent jest-hoist from erroring on identifiers in type annotations

docs/ExpectAPI.md, website/src/jest/css/jest.css
**Summary**
Currently only for `expect.stringContaining`.
=> Add 'available since' to docs

docs/ExpectAPI.md
see #2813 
```
I think it's a bug in a code example in the documentation
https://facebook.github.io/jest/docs/expect.html#expectstringmatchingregexp
```
=> fixed bug in example code expect.stringMatching

packages/jest-editor-support/src/parsers/BabylonParser.js
Fixing the "babylonParser" expects that "plugins" is set in error #2819
=> Create new array if parsed babel file does not have the plugin section.

packages/jest-cli/src/lib/__tests__/__snapshots__/highlight-test.js.snap, packages/jest-cli/src/lib/__tests__/highlight-test.js, packages/jest-cli/src/lib/highlight.js
**Summary**
Now, highlight in pattern mode working wrong on relative paths starts with `./`:
**Test plan**
After fix, it is look like this:
=> Fix wrong highlighting for the matches in pattern mode

packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/__tests__/watch-test.js, packages/jest-cli/src/jest.js, packages/jest-cli/src/reporters/NotifyReporter.js, packages/jest-cli/src/runJest.js, packages/jest-cli/src/watch.js
This PR opens the discussion around input buttons for notify reporter in jest-cli. As far as I could see, there were no way to restart running from reporters. This PR passes `startJest` to the NotifyReporter for it to use on user interaction. I don't know if this is the best way to do it, but I thought it's better to open a PR to start the discussion and get some feedback.
With this change, you get possibility to re-run tests (in current mode for watching) from macOS notifications. See video: https://youtu.be/YvmdM4id7zU
=> Adds possibility to rerun tasks from NotifyReporter

examples/react-native/__tests__/__snapshots__/Intro-test.js.snap, examples/snapshot/__tests__/__snapshots__/Link.react-test.js.snap, integration_tests/__tests__/__snapshots__/snapshot-serializers-test.js.snap, integration_tests/transform/multiple-transformers/__tests__/__snapshots__/multiple-transformers-test.js.snap, packages/jest-diff/src/__tests__/diff-test.js, packages/pretty-format/src/__tests__/__snapshots__/pretty-format-test.js.snap, packages/pretty-format/src/__tests__/pretty-format-test.js, packages/pretty-format/src/index.js, packages/pretty-format/src/plugins/ReactElement.js, packages/pretty-format/src/plugins/ReactTestComponent.js
Improves clarity of snapshot diffs by placing closing brackets below the last prop in element.
**Note**: In case of element without props, closing bracket remains in the same line as opening tag - the same way as default `tag-aligned` location in ESLint ([react/jsx-closing-bracket-location](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md#location)) - recommended in [Airbnb React/JSX Style guide](https://github.com/airbnb/javascript/blob/master/react/README.md#alignment), so it will print:
```jsx
<Foo />
```
instead of:
```jsx
<Foo
/>
```
I have no strong opinion whether it should remain in the same line or go to next line in the same way as with multiline elements, so please let me know if I should change that.
Fixes #2830.
=> Put JSX closing brackets in new line in snapshots

packages/jest-cli/src/watch.js
Fixes #2760
It does not rerun the tests when the the 'change' event was caused only by `.snap` files
I still want to verify some things tomorrow before moving forward with this 😄
=> Filter snap file changes in watch mode

package.json, yarn.lock
**Summary**
Drops `eslint-plugin-flow-vars`.  It doesn't seem to be used, or be a peerDependency.  Also, installing it gives the following warning.
```
warning eslint-plugin-flow-vars@0.5.0: eslint-plugin-flow-vars has been deprecated in favor of eslint-plugin-flowtype@2.4.0 or higher
```
**Test plan**
=> Remove `eslint-plugin-flow-vars`.

docs/TimerMocks.md
- Add Information about `jest.runTimersToTime(msToRun)` in Timers Mock Documentation.
- Fixed #2840
=> Updating the TimerMocks Documentation

packages/jest-snapshot/src/State.js, packages/jest-snapshot/src/__tests__/utils-test.js, packages/jest-snapshot/src/utils.js
**Summary**
This is a followup of https://github.com/facebook/jest/pull/2731.
I didn't want to alter serialisation improvements which @vjeux introduced, so I thought it would be safer to bring back an `unescape` in a little different form and use it only to generate un-escaped output to diff tool. Thanks to this we avoid having extra backslashes in console output.
Given test:
```js
test('snap', () => {
expect('coca cola "yoko \\son (*)\d o".').toMatchSnapshot();
expect(/some-regex('\"\))\\.x/).toMatchSnapshot();
});
```
Before:
After: 
**Test plan**
jest
cc: @cpojer @vjeux
=> Unescape serialized snapshots for diffing

docs/CLI.md
**Summary**
The document at http://facebook.github.io/jest/docs/cli.html#jsonoutputfile-filename is wrong. According to jest --help, the correct option name is outputFile instead of jsonOutputFile
**Test plan**
Document change doesn't have a way to test it. Sorry about that..
BTW, this option name consumes me a hour to find correct name....:'(
=> replace jsonOutputFile with outputFile

packages/jest-cli/src/cli/args.js, packages/jest-config/src/setFromArgv.js
Fixes #2860.
**Summary**
I want to configure the coverage directory per-invocation, not just per-project.
**Test plan**
There seem to be no CLI tests, and per #2864, tests fail on master already, so I'm not sure how to test this. If there are CLI tests and someone could point me to them, that'd be great.
=> [New] add `coverageDirectory` config to CLI options.

docs/ExpectAPI.md
**Summary**
Fixes #2823 /cc @devboell @thymikee
In explanations: added "received" and replaced "provided" with "expected"
* `arrayContaining` rewrote explanation and replaced example
* `objectContaining` improved explanation and moved into alphabetical order
* `stringContaining` removed extra empty line
* `stringMatching` rewrote explanation and replaced example
**Test plan**
Please review as correct, clear, and complete for the primary audience.
=> Docs: replace examples of arrayContaining in ExpectAPI.md

CONTRIBUTING.md
**Summary**
I updated the contributing docs to use `yarn` instead of `npm`.
**Motivation**
I was just going through the contributing doc when working on #2489. I didn't have `yarn` installed globally, and `npm install` failed...I noticed that many of the scripts use `yarn`...so I figured I'd update the doc to reflect that.
**Test Plan**
No tests required, it's just a change to the docs.
=> Update contributing docs to use yarn

website/core/home/GridBlock.js, website/core/home/HomeSplash.js, website/core/nav/SideNav.js, website/layout/BlogPageLayout.js, website/src/jest/index.js, website/src/jest/users.js
The following warning is shown for several components when the website is built:
> Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Marked. See https://fb.me/react-warning-keys for more information.
I've addressed the cause of this warning for several components:
- `GridBlock`
- `HomeSplash`
- `SideNav`
- `BlogPageLayout`
- `index.js`
- `users.js`
Ran `node server/generate.js` and `npm start` to verify the warnings go away, as well as to make sure the website is rendered properly.
There is one remaining component that causes this warning to show up, `Marked`. Addressing this would require updating the markdown parser to automatically insert keys props when needed.
=> [Website] Remove several react-warning-keys warnings.

packages/jest-editor-support/src/TestReconciler.js
**Summary**
In case of dynamically requiring describes the line of code doesn't exists as the filename will not be present on the stacktrace.
Test: change parserTests.js to fail, look at the `executableJSON` and see that both the `BabylonParser` and the `TypeScriptParser` test are failing but they are not in the message:
``` 
expect(received).toBe(expected)
Expected value to be (using ===):
true
Received:
false
at Object.<anonymous>.test (packages/jest-editor-support/src/__tests__/parsers/parserTests.js:178:30)
```
**Test plan**
doesn't throw anymore.
=> Editor support testReconciler: don't throw if missing line number.

packages/jest-matchers/src/__tests__/matchers-test.js
**Summary**
This unbreaks node 4 on travis which doesn't have function name inference and therefore had outdated snapshots.
cc @bestander 
**Test plan**
yarn test on node 4.
=> Make matchers snapshot test consistent across node versions.

packages/jest-snapshot/src/__tests__/utils-test.js, packages/jest-snapshot/src/utils.js
**Summary**
Re: comments in https://github.com/facebook/jest/pull/2921
**Test plan**
Should green in CI
=> Re-word 'users of' to 'developers on' in snapshot migration copy

docs/SnapshotTesting.md
**Summary**
The example code in *SnapshotTesting* doesn't match the screenshot and it may cause confusion:
```html
<Link page="https://facebook.github.io/jest/">Jest</Link>
```
should be
```html
<Link page="http://www.instagram.com">Instagram</Link>
```
**Test plan**
N/A
=> Documentation: Update code to match the screenshot

packages/jest-runtime/package.json
**Summary**
It was removed from `jest-runtime`, but it's actually used there: https://github.com/facebook/jest/blob/master/packages/jest-runtime/src/transform.js#L22
Fixes https://github.com/facebook/jest/issues/2935
**Test plan**
clean install
=> Bring json-stable-stringify back to jest-runtime

docs/MockFunctions.md
I have always struggled getting mocks to work properly and this possible typo has always contributed to the problem. I say "possible" because I still am not super comfortable with what `jest.mock` actually does.
**Summary**
**Test plan**
=> Documentation: Fix possibly confusing typo

packages/jest-snapshot/src/utils.js
**Summary**
I had to think hard to understand **what** I need to do and **when** and **why**.
* Move **when** to the front: Before you upgrade snapshots [instead of while upgrading]
* Change **what** from passive to active: We recommend that you [instead of it is advised to]
* Change **why** from passive to active: you do not store [instead of no…is stored]
This applies guidelines from Microsoft Manual of Style:
* active “We recommend…” instead of passive wording as a rare exception to the guideline to avoid the first person
* active “you” instead of third person wording for actions
**Test plan**
Second opinion about whether revised wording helps someone who didn’t expect this and doesn’t read English as first language.
I’m not sure the last words “invalid state” is clear enough, but …
=> Revise the snapshot version warning

packages/jest-haste-map/src/index.js
**Summary**
If watchman was installed globally, jest couldn't run at all.
=> Fix canUseWatchman freeze @ jest-haste-map 

packages/pretty-format/src/plugins/ReactTestComponent.js
**Summary**
The excellent improvement in snapshot format causes a **regression** because `Object.keys(instance.props)` is outside `if (instance.props) { … }`
As part of work-in-progress on subset matching to ignore irrelevant details, a helper function transforms test-rendered elements by omitting empty props objects to improve the error diff message for `toMatchObject` assertion. Recently I used it for a `toMatchSnapshot` assertion.
Here is a minimal example to illustrate what is happening:
```js
test('omitted irrelevant props for toMatchObject', () => {
expect({
$$typeof: Symbol.for('react.test.json'),
type: 'span',
children: ['and used it for toMatchSnapshot'],
}).toMatchSnapshot();
});
```
Jest 18.0.1 stores a snapshot:
```
exports[`omitted irrelevant props for toMatchObject 1`] = ` …
```
=> Keep supporting undefined props in ReactTestComponent plugin

packages/jest-cli/src/__tests__/SearchSource-test.js, packages/jest-cli/src/__tests__/watch-filename-pattern-mode-test.js, packages/jest-cli/src/__tests__/watch-test-name-pattern-mode-test.js, packages/jest-cli/src/__tests__/watch-test.js, packages/jest-cli/src/jest.js, packages/jest-cli/src/watch.js, packages/jest-config/src/__tests__/normalize-test.js, packages/jest-config/src/index.js, packages/jest-config/src/normalize.js, packages/jest-runtime/src/__mocks__/createRuntime.js, packages/jest-runtime/src/cli/index.js, packages/jest-validate/README.md, packages/jest-validate/src/__tests__/validate-test.js, packages/jest-validate/src/deprecated.js, packages/jest-validate/src/exampleConfig.js, packages/jest-validate/src/types.js, packages/jest-validate/src/validate.js
**Summary**
Resolve #2916. Using hack with global variable, but for get better solution we need rewrite jest-validate for get deprecation warnings in jest-cli. I'm really may try to do it after release, but now its best solution.
**Test plan**
=> Handle deprecation warnings in watch mode

packages/pretty-format/src/plugins/ReactTestComponent.js
**Summary**
Given the problem solved in #2943 these Flow type annotations find the following error:
element of Object.keys. Expected object instead of possibly undefined value
As a Flow newbie, I am especially glad for your guidance whether this is enough, or to add more.
**Test plan**
The new type checks pass. But not without a fight: if you enjoy irony, see comment in code :)
=> Add Flow type annotations to ReactTestComponent plugin

packages/jest-editor-support/src/__tests__/fixtures/declarationWithoutAssignment.example, packages/jest-editor-support/src/__tests__/parsers/parserTests.js, packages/jest-editor-support/src/parsers/BabylonParser.js
**Summary**
Fixes a bug preventing the babylon parser to correctly parse files with uninitialized variables:
**Test plan**
Add a test to reproduce the bug:
After the fix the test passes.
=> Fixes bug in the parser throwing when finding an uninitialized variable

packages/jest-util/src/validateCLIOptions.js
Just noticed a missing space.
This should fix it.
Another occurrence of the message in `warnings.js` is not affected because it already has the space.
=> Add missing space before "Did you mean"

integration_tests/__tests__/config-test.js, packages/jest-config/src/setFromArgv.js
**Summary**
This PR aims to solve #2847. The default CLI setting for `watchman` is `true` so the existing check would always set it to true and would never take into account the config setting. I modified the check to only look at the `argv` setting if the config option wasn't set.
**Test plan**
All tests should pass and you can now set `watchman: false` in config and see it is disabled with `--debug` output.
**Note**
I thought about unit testing this under `jest-config` package, but felt that adding to the integration test was more robust to see it grab the value from config instead of `argv`. If you think I should add a unit test for `setFromArgv` function, I am more than willing to do that as well.
=> Respect `watchman` config setting

docs/TutorialReactNative.md
**Summary**
It looks like the default function exported from 'jest-react-native' is the `mockComponent` function. When I was running `jestReactNative.mockComponent`, I would get `TypeError: jestReactNative.mockComponent is not a function`. 
**Test plan**
In my code, removing that and just running `jestReactNative('TouchableHighlight')` worked so I just removed it from the documentation to reflect that.
Side Note: I'm running `jest@18.0.0`.
=> Removed `.mockComponent`

packages/jest-cli/src/lib/__tests__/isValidPath-test.js, packages/jest-cli/src/lib/isValidPath.js, packages/jest-cli/src/watch.js
This fixes #2960 
The bug was introduced while rewriting watch mode... In the previous version it was filtering out `coverage` files and files not in `config.roots`
This PR adds back this logic: https://github.com/facebook/jest/blob/v18.1.0/packages/jest-cli/src/jest.js#L428
Test plan:
Running `--watch --coverage`, also added unit tests
=> Fix infinite loop issue when running watch with --coverage

packages/jest-cli/package.json, packages/jest-cli/src/reporters/utils.js
**Summary**
`node` manages paths differently in Windows in that it uses `\\` instead of `/`; this causes some snapshot tests to fail with something like
```
-  › path/to/file1-test.js
+  › path\\to\\file1-test.js
```
To get around that, `jest` has AppVeyor [overwrite snapshots that do not pass](https://github.com/facebook/jest/blob/master/appveyor.yml#L18-L22); consequently, all snapshot tests pass on AppVeyor unconditionally.
This PR uses the `slash` package (already in the dependency tree [via `babel-core`](https://github.com/babel/babel/blob/master/packages/babel-core/package.json#L46)) to normalize the output of `trimAndFormatPath`, replacing `\\` with `/`.  This makes 14 out of the 16 failing snapshot tests pass.
**Test plan**
Look at [the AppVeyor output of …
=> Use `slash` to normalize paths in Windows.

packages/jest-cli/src/reporters/NotifyReporter.js
**Summary**
Notify reporter crashes on Linux. `metadata` argument is only defined on macOS. The bug has been introduced with adding possibility to rerun tasks #2727.
https://github.com/facebook/jest/commit/07a6cfeafb1a89396d2434035bc7d67a677edc81#diff-f58da94b31399922b8177b3871db25e3R69
```
.../node_modules/jest-cli/build/reporters/NotifyReporter.js:69
if (metadata.activationValue === quitAnswer) {
^
TypeError: Cannot read property 'activationValue' of undefined
```
=> Fix notify reporter on Linux

packages/jest-resolve/src/index.js
**Summary**
@voideanvalue and I talked about this about six months ago but I never got to it. Basically we have a lot of "missing" modules because of our PHP JS modules at FB and every resolution of "MyModule" is really slow (there are thousands). However, we can still resolve relative requires quickly. This change skips likely node modules but keeps resolving relative requires without a noticeable performance hit.
**Test plan**
At FB, this now takes 5 seconds instead of 70.
=> Skip node resolution only for non-relative requires.

packages/jest-changed-files/src/__tests__/git-test.js, packages/jest-changed-files/src/__tests__/hg-test.js
**Summary**
Replaces the usage of `childProcess.spawnSync('mkdir', ['-p])` with `mkdirp.sync` in the `jest-changed-files` tests for `git` and `hg`.  This allows them to run on systems where `mkdir -p` is not recognized (i.e. Windows).
**Test plan**
=> Use `mkdirp.sync` instead of `childProcess.spawnSync('mkdir', ['-p'])`.

packages/jest-resolve/package.json, packages/jest-resolve/src/__test__/resolve-test.js, packages/jest-resolve/src/index.js
**Summary**
Uses `is-builtin-module` to determine if a module is a core module instead of `resolve.isCore`.  `resolve` is going away with #2925 and `is-builtin-module` is already in the dependency tree (not specifically of `jest-resolve`).
**Test plan**
Write tests for `Resolver.isCore`.
=> [jest-resolve] Use `is-builtin-module` instead of `resolve.isCore`.

dangerfile.js
I tested the regex thoroughly, so I think it's just a matter of usage. Regex.test() has some weird semantics if its run over the same string twice... so switched to match() instead.
This is an extracted commit from https://github.com/facebook/jest/pull/2704
=> Slight dangerfile tweak

docs/CLI.md
**Summary**
The documentation incorrectly stated that the `--findRelatedTests` cli option expected an `=` before the list of files.  It does not, and this corrects that documentation
**Test plan**
No testing necessary, documentation only.  However, it would likely be good to provide a usage example for this somewhere in the docs.  It took me a while to figure out what the usage was between the following:
```
jest --findRelatedTests='foo.bar, foo.baz'
jest --findRelatedTests='foo.bar foo.baz'
jest --findRelatedTests 'foo.bar, foo.baz'
jest --findRelatedTests 'foo.bar foo.baz'
jest --findRelatedTests foo.bar foo.baz
```
Admittedly, that was mostly due to the misleading doc.
=> findRelatedTests option doesn't use a `=`

packages/jest-cli/src/SearchSource.js, packages/jest-cli/src/__tests__/SearchSource-test.js, packages/jest-cli/src/__tests__/test_root/.hiddenFolder/not-really-a-test.txt
**Summary**
When a test is inside a folder that's name starts with `.`, they are ignored by `testMatch` but are correctly found by `testRegex`. It's even more obscure if the entire project is checked out below a dot-folder, in which case *all* tests are ignored by `testMatch` which is now the default way of finding tests.
**Test plan**
`yarn test`
=> testMatch should find tests in .folders

integration_tests/__tests__/__snapshots__/console-test.js.snap, integration_tests/__tests__/console-test.js, packages/jest-cli/src/runJest.js
**Summary**
This fixes #2987. The issue was if `verbose` option wasn't specifically set to `false`, then it would be set to `true`, so when jest was determining which `Console` class to use, it would always go into the truth part of the first ternary.
```js
const TestConsole =
config.verbose
? Console
: (config.silent
? NullConsole
: BufferedConsole
);
```
This fix makes sure we didn't explicitly set `silent: true` before changing the value of `verbose`.
**Test plan**
All tests pass and `verbose` is no longer set to `true` when `silent` is passed.
=> Fix behavior of `--silent` flag

integration_tests/__tests__/__snapshots__/snapshot-test.js.snap, integration_tests/__tests__/snapshot-test.js, integration_tests/snapshot/__tests__/snapshot-test.js, packages/jest-snapshot/src/__tests__/utils-test.js, packages/jest-snapshot/src/utils.js
**Summary**
This fixes #2969. When snapshot data is saved, it normalizes `\r\n` to `\n`, but on next runs when it receives the new snapshot data and serializes it, this normalization doesn't happen, so tests would fail without any changes to the data being snapshot tested.
**Test plan**
All tests pass and subsequent runs of snapshot tests containing `\r\n` will not fail without changes.
=> [jest-snapshot] Normalize line endings in `serialize` function

packages/jest-config/package.json, packages/jest-config/src/__mocks__/read-pkg.js, packages/jest-config/src/__tests__/loadFromPackage-test.js, packages/jest-config/src/index.js, packages/jest-config/src/loadFromPackage.js
**Summary**
Uses `read-pkg` to read `package.json` instead of `require`'ing `package.json` directly.  `read-pkg` is already in the dependency tree, (not specifically in `jest-config`'s, but the only packages that require `jest-config` are `jest-runtime`, `jest-cli`, and `ts-jest`, which also has `read-pkg` in its dependency tree) so it reduces code duplication.
**Test plan**
Writing tests for `loadFromPackage`
=> [jest-config] Use `read-pkg` to read `package.json`.

README.md, docs/GettingStarted.md, examples/async/package.json, examples/enzyme/package.json, examples/react/package.json, examples/snapshot/package.json, packages/jest-config/src/__tests__/normalize-test.js, packages/jest-config/src/normalize.js
**Summary**
Drop auto-including of `babel-polyfill` if available. Fixes #2693
**Test plan**
jest
=> Remove auto-inclusion of babel-polyfill

packages/pretty-format/src/__tests__/pretty-format-test.js, packages/pretty-format/src/index.js
=> pretty-format should run plugins before serializing nested basic values

packages/jest-matcher-utils/src/index.js
**Summary**
Fixes #3020 
**Test plan**
Given
```javascript
it('test .toBeGreaterThan message', () => {
expect("222").toBeGreaterThan(344444)
})
```
It prints
=> change error message to ensureActualIsNumber

packages/jest-matchers/src/__tests__/__snapshots__/toThrowMatchers-test.js.snap, packages/jest-matchers/src/__tests__/toThrowMatchers-test.js, packages/jest-matchers/src/toThrowMatchers.js
**Summary**
Fixes #2946.
We should warn if an `actual` value of any of `toThrowMatchers` is not a function, as `toThrow()` matcher can pass a supposed-to-be-failing test because of Jest's internal error (in the issue attached it's a TypeError when trying to call `actual()` on a string).
Here's a screenshot of what it looks like:
**Test plan**
jest
=> Throw if actual value of toThrowMatchers is not a function

packages/jest-cli/src/lib/highlight.js
**Summary**
Makes `relativePathHead` always be `./` instead of `.\\` on Windows.  Since `filePath` [is already normalized](https://github.com/facebook/jest/blob/master/packages/jest-cli/src/reporters/utils.js), it will never be `.\\`.  This was what was causing snapshot tests to fail on Windows.
**Test plan**
Look at [the AppVeyor output of another PR](https://ci.appveyor.com/project/Daniel15/jest/build/2305#L435) and see that 2 snapshots are being updated.  The AppVeyor output for this PR should have 0.
=> Fix snapshot tests on Windows.

packages/jest-resolve-dependencies/src/index.js
**Summary**
Fixes #2843.
Feel free to close it, if we don't want such behaviour, but I think it's nice.
**Test plan**
`jest-resolve-dependencies` has no tests :(. If we eventually want to merge it, I'll add some.
=> [WIP] Treat snapshots as related to test files

packages/eslint-plugin-jest/README.md
**Summary**
This Pull Request is intended to resolve the broken links to the eslint-plugin-jest rule definitions on the NPM documentation page, whilst also still working through GitHub. Resolves #3036.
**Test plan**
This PR is a little difficult to test, as I don't have access to the NPM page. I've tested that the new links work in GitHub, but some help on testing them on NPM would be great.
=> Add relative paths to eslint-plugin-jest docs

package.json, packages/jest-runtime/src/__tests__/Runtime-cli-test.js, packages/jest-runtime/src/__tests__/transform-test.js, packages/jest-runtime/src/transform.js, yarn.lock
**Summary**
Removes `skipOnWindows` calls for `jest-runtime` tests and resolves the underlying issues.
- `require('child_process').spawnSync` has been replaced with `require('cross-spawn').sync`.
- `cachePath` is now normalized through `slash`.
**Test plan**
Everything that passed Travis and AppVeyor before should pass now.
=> Enable all `jest-runtime` tests on Windows.

integration_tests/__tests__/__snapshots__/failures-test.js.snap, integration_tests/failures/__tests__/assertion-count-test.js, packages/jest-jasmine2/src/setup-jest-globals.js, packages/jest-matchers/src/index.js, types/Matchers.js
**Summary**
This was pretty bad before and didn't integrate properly with Jest.
Before:
After:
**Test plan**
jest
=> Improve printing of `expect.assertions` error.

packages/jest-resolve-dependencies/package.json, packages/jest-resolve-dependencies/src/__tests__/DependencyResolver-test.js, packages/jest-resolve-dependencies/src/__tests__/__fixtures__/__snapshots__/related-test.js.snap, packages/jest-resolve-dependencies/src/__tests__/__fixtures__/file-test.js, packages/jest-resolve-dependencies/src/__tests__/__fixtures__/file.js, packages/jest-resolve-dependencies/src/__tests__/__fixtures__/related-test.js, packages/jest-resolve-dependencies/src/index.js
**Summary**
Review highly appreciated. I use real files from `__fixtures__` instead of mocks, because it was easier for me this way (behaves more like integration test though). 
**Test plan**
jest
=> Add tests for jest-resolve-dependencies

packages/jest-resolve/package.json, packages/jest-resolve/src/index.js
**Summary**
Moves `jest-haste-map` from `dependencies` to `devDependencies` for `jest-resolve`.  It's only used in tests and as a type import.
**Test plan**
=> [jest-resolve] Move `jest-haste-map` to `devDependencies`.

packages/jest-haste-map/package.json, packages/jest-haste-map/src/crawlers/__tests__/node-test.js, packages/jest-haste-map/src/crawlers/node.js
**Summary**
Removes `skipOnWindows` calls for `nodeCrawl` in `jest-haste-map` and resolves the underlying issues.
- Path is normalized through `slash`.
**Test plan**
Everything that passed Travis and AppVeyor before should pass now.
=> [jest-haste-map] Enable `nodeCrawl` tests for Windows.

packages/jest-haste-map/package.json, packages/jest-haste-map/src/crawlers/__tests__/node-test.js, packages/jest-haste-map/src/crawlers/node.js
It breaks stuff in `SearchSource`.
=> Revert "[jest-haste-map] Enable `nodeCrawl` tests for Windows."

packages/jest-haste-map/package.json, packages/jest-haste-map/src/index.js, packages/jest-runtime/src/index.js
This fixes an issue on OS X when there are too many files/folders to watch that causes the test to crash with error 
`2016-09-22 10:49 node[79167] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)`
See Issue #1767
This solve the issue by updating [sane](https://github.com/amasad/sane) to 1.6.0 and passing a regular expression passed on the the `testPathIgnorePatterns` config option. This allows `sane` to never apply the watchers.
**_Currently there are no defaults. Maybe it should default to ignoring `.git|node_modules` if nothing is passed? Or else people may still encounter the error._**
The error is caused by some mixture node/OSX. (See joyent/node/issues/5463), where node/osx can't handle the amount of watchers.
On macOS Sierra, …
=> Fix bug with watchers on macOS causing test to crash

packages/jest-haste-map/src/index.js
@cpojer  
Following on from the jest-haste-map PR #2957 (exception with MacOS and watchers), @SimenB suggested an [alternative way to typecheck regex](https://github.com/facebook/jest/pull/2957/files#r104211008) that flow understands. Tested and passing flow.
=> jest-haste-map - updated typecheck for regex and remove FlowFixMe

docs/ExpectAPI.md, docs/SetupAndTeardown.md, packages/eslint-config-fb-strict/index.js, packages/eslint-plugin-jest/README.md, packages/eslint-plugin-jest/docs/rules/valid-expect.md, packages/eslint-plugin-jest/src/index.js, packages/eslint-plugin-jest/src/rules/__tests__/valid-expect-test.js, packages/eslint-plugin-jest/src/rules/types.js, packages/eslint-plugin-jest/src/rules/valid-expect.js, packages/pretty-format/src/__tests__/pretty-format-test.js
**Summary**
Adds a new eslint rule to pick up invalid usage of `expect`.
All credits goes to @tlvince and @alecxe, this code is 100% copy paste, including docs and tests (only change is how `context.report` is called, but it's called with the same args). Open question is how to credit them in the source code, and what should be done about the license header?
https://github.com/tlvince/eslint-plugin-jasmine/blob/master/lib/rules/valid-expect.js
Motivation: Especially when converting tests from other assertions libs, it's easy to miss something. Jest reports false positives for some misuse of the api.
**Test plan**
Run `yarn lint` on some code that uses `expect` in an invalid way. There actually was a test in the jest code base giving a false positive.
The diff from `pretty-format-test.js` …
=> Add eslint rule `valid-expect`

fixtures/global_its.example, fixtures/parserTests.js, packages/jest-editor-support/package.json, packages/jest-editor-support/src/parsers/BabylonParser.js
**Summary**
Solves #3070. Instead of including only the 'flow' babylon plugin, all available babylon plugins are included. As a result, parsing files containing JSX does not produce an error.
**Test plan**
Added a test case to `fixtures/global_its.example` and `fixtures/global_its.example`. The test checks whether parsing works with JSX:
```js
it('works with JSX', ()=> {
const foo = () => <div></div>;
})
```
This test wouldn't pass without the change. It does pass with the change.
=> Update babylon plugins in BabylonParser, solves #3070

packages/jest-cli/src/constants.js, packages/jest-cli/src/watch.js
**Summary**
This PR makes watch mode collapsed after first run, so it doesn't occupy so much of vertical space. It's possible to show the usage when pressing "w".
Here's a preview:
**Test plan**
Need to write a test for that
=> Collapse Watch Usage prompt after first run

.eslintignore, examples/react-native/Intro.js, examples/react-native/__tests__/Intro-test.js
**Summary**
Lint all the examples including `examples/react-native`. For some reason, `examples/react-native` was added in `.eslintignore` and wasn't being linted. I have removed it from `.eslintignore` and fixed all the lint errors thrown out by examples/react-native. Now all the examples are guaranteed linted, as there are no remaining example folder in `.eslintignore`. 
This emerged from the discuss here https://github.com/facebook/jest/pull/3047#issuecomment-284344520 with @cpojer
**Test plan**
`yarn run lint` works
=> lint all examples using eslint

packages/jest-cli/src/SearchSource.js
**Summary**
Lifts an `Object.keys` call in `jest-cli` out of a loop.  It should save a little over 500 calls when running `yarn run jest`; not really a noticeable difference.
**Test plan**
=> [jest-cli] Lift `Objecy.keys` call from loop.

packages/jest-resolve-dependencies/package.json, packages/jest-resolve-dependencies/src/__tests__/DependencyResolver-test.js, packages/jest-resolve-dependencies/src/__tests__/__fixtures__/file.js, packages/jest-resolve-dependencies/src/index.js
**Summary**
Drops `jest-file-exists` from `jest-resolve-dependencies` and removes it's usage.  ~~The check was redundant.~~
Strictly speaking, it wasn't redundant, just wasteful.  Expanded, it was
```
// `(AB+C)B` is the same as just `B` (since `A` is given to be true)
((hasteFS && hasteFS.exists(filePath)) || fs.existsSync(filePath)) && hasteFS.exists(filePath)
```
**Test plan**
=> [jest-resolve-dependencies] Remove `jest-file-exists`.

packages/jest-runtime/package.json, packages/jest-runtime/src/__tests__/transform-test.js, packages/jest-runtime/src/transform.js, packages/jest-snapshot/package.json, packages/jest-snapshot/src/State.js, packages/jest-snapshot/src/__tests__/utils-test.js, packages/jest-snapshot/src/index.js, packages/jest-snapshot/src/utils.js, packages/jest-util/package.json, packages/jest-util/src/index.js
**Summary**
Removes all usage of the `jest-file-exist` package.  With [one exception](https://github.com/facebook/jest/blob/master/packages/jest-snapshot/src/index.js#L34-L40), it was just a wrapper around `fs.existsSync`.
**Test plan**
=> Remove all usage of `jest-file-exists`.

packages/pretty-format/src/index.js, packages/pretty-format/src/plugins/AsymmetricMatcher.js, packages/pretty-format/src/plugins/ImmutableList.js, packages/pretty-format/src/plugins/ImmutableMap.js, packages/pretty-format/src/plugins/ImmutableOrderedMap.js, packages/pretty-format/src/plugins/ImmutableOrderedSet.js, packages/pretty-format/src/plugins/ImmutablePlugins.js, packages/pretty-format/src/plugins/ImmutableSet.js, packages/pretty-format/src/plugins/ImmutableStack.js, packages/pretty-format/src/plugins/ReactElement.js, packages/pretty-format/src/plugins/ReactTestComponent.js, packages/pretty-format/src/plugins/lib/printImmutable.js, packages/pretty-format/src/types.js
**Summary**
Unifying the use of `types` in all the pretty-format plugins.
Also, in `ImmutableMap` and `ImmutableSet` making sure they don't have the `@@__IMMUTABLE_ORDERED__@@` field. That way, the order in `ImmutablePlugins` won't matter
**Test plan**
yarn test
=> use Plugin type for pretty-format plugins

packages/jest-config/src/__tests__/loadFromFile-test.js, packages/jest-config/src/__tests__/loadFromPackage-test.js, packages/jest-config/src/index.js, packages/jest-config/src/loadFromFile.js, packages/jest-config/src/loadFromPackage.js
**Summary**
Hoists calls to `normalize` in `jest-config` from `readRawConfig`, `loadFromFile`, and `loadFromPackage` to `readConfig`. 
**Test plan**
Two tests were deleted as they are no longer accurate, but the behavior was strictly internal in the first place.
=> [jest-config] Hoist `normalize` call.

packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-matchers/src/index.js, types/Matchers.js
This PR addresses issue #1377 and adds promise support to **all the existing matchers** in jest. 
This allows us to run assertions on promises by adding the keywords `resolves` and `rejects` after the expect statement as follows:
```js
it('should reject', () => {
return expect(Promise.reject(4)).rejects.toBe(4);
});
it('should resolve', () => {
return expect(Promise.resolve(4)).resolves.toBe(4);
});
```
It can also easily be used in combination with `async/await`:
```js
it('should reject', async () => {
await expect(Promise.reject(4)).rejects.toBe(4);
await expect(Promise.reject(4)).rejects.not.toBe(5);
});
it('should resolve', async () => {
await expect(Promise.resolve(4)).resolves.toBe(4);
await expect(Promise.resolve(4)).resolves.not.toBe(5);
});
```
I would love to hear some feedback …
=> Add promise support to all the matchers

docs/TutorialReactNative.md
Without the slash at the end `react-native-button` is still being ignored for some reason.
=> Fix transformIgnorePatterns example

docs/ExpectAPI.md
**Summary**
Add dot for consistent naming
**Test plan**
—
=> Add missing dot in API docs

packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/index.js
**Summary**
Fixes the message when a promise was expected to be fulfilled but was rejected.
```js
await jestExpect(Promise.reject(4)).resolves.toBe(4);
```
```diff
- Expected received Promise to resolve, instead it rejected to value undefined
+ Expected received Promise to resolve, instead it rejected to value 4
```
This was overlooked in #3068.
**Test plan**
The snapshot covers this.
=> Show reject reason when expecting resolve

docs/Configuration.md, docs/Troubleshooting.md
I got a ~70% speed boost in test suite run times after adding a babel plugin that inlines require calls to an automocked codebase. This adds documentation so other users can discover this. Ref: #3084
=> add documentation around inline require transforms

packages/jest-matchers/src/asymmetric-matchers.js, packages/jest-matchers/src/jasmine-utils.js
**Summary**
Since `jasmine-utils` was mostly yanked from `underscore`, it had to deal with some specific cases (i.e. IE8 support).  This simplifies the implementation of `contains` and pulls it into `asymmetricMatch`, allowing the `Array.isArray` equivalent to be hoisted.
**Test plan**
=> [jest-matchers] Simplify `asymmetricMatch` of `ArrayContaining`.

packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/lib/getPlatformExtension.js, packages/jest-jasmine2/src/jasmine-light.js, packages/jest-matchers/src/asymmetric-matchers.js
**Summary**
The options object allows specification of custom platforms, but jest-haste-map doesn't use this when checking for duplicates, which leads to a lot of unnecessary warning messages on custom platforms.
**Test plan**
Ran these changes on a project with the following package.json configuration:
```
// ...
"jest": {
"haste": {
"platforms": ["vr"],
// ...
```
And two files: `MyModule.js` and `MyModule.vr.js`, both of which contain `@providesModule MyModule`
Without these changes, jest-haste-map produces a warning. With these changes, no warnings occur.
=> Support custom platforms on jest-haste-map

packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/TestSequencer.js, packages/jest-cli/src/__tests__/TestRunner-test.js, packages/jest-cli/src/__tests__/TestSequencer-test.js, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/cli/runCLI.js, packages/jest-cli/src/jest.js, packages/jest-cli/src/runJest.js, types/TestRunner.js
**Summary**
This is the preparatory work I did for the multi-config runner. It splits up the test performance cache into a TestSequencer class, uses async/await and moves a few things around. No behavior changes expected. Before merging, I will add a test for the TestSequencer.
See #3156
**Test plan**
jest
=> Refactor runner

packages/pretty-format/src/__tests__/ConvertAnsi-test.js, packages/pretty-format/src/__tests__/pretty-format-test.js
**Summary**
The motivation of this PR is to improve `pretty-format` package test coverage.
Old coverage:
New coverage:
**Test plan**
`yarn test-ci`
=> improve pretty-format coverage

packages/jest-cli/src/SearchSource.js, packages/jest-cli/src/TestPathPatternPrompt.js, packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/__tests__/SearchSource-test.js, packages/jest-cli/src/cli/runCLI.js, packages/jest-cli/src/lib/createContext.js, packages/jest-cli/src/runJest.js, packages/jest-cli/src/watch.js, packages/jest-resolve-dependencies/src/__tests__/DependencyResolver-test.js, packages/jest-runtime/src/cli/index.js, packages/jest-runtime/src/index.js, types/Context.js, types/HasteMap.js
**Summary**
Another piece from #3156 that can be shipped without any actual behavior changes.
**Test plan**
yarn test
=> Rename HasteContext to Context.

packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/matchers-test.js
**Summary**
The test file for the matchers has many test titles in different formats.  The purpose of this change is to unify the test titles into a consistent format.  @dmitriiabramov 
Test Titles Before:
Test Titles After:
**Test plan**
`jest ./packages/jest-matchers/src/__tests__/matchers-test.js`
`yarn test`
=> Test Title Unification for matchers-test.js in jest-matchers package

docs/ExpectAPI.md, docs/TestingAsyncCode.md, docs/TutorialAsync.md
Follow-up from PR #3068. This PR updates the docs to incorporate the new `.resolves` and `.rejects` keywords in the expect API.
=> Updated expect API docs with .resolves and .rejects

docs/SnapshotTesting.md
**Summary**
This paragraph alluded to the fact that snapshots should be reviewed (by mentioning pretty-format), but it should be explicitly mentioned.
**Test plan**
It's just a text modification
=> Explicitly mention that snapshots should be reviewed

packages/jest-editor-support/src/parsers/BabylonParser.js
**Summary**
Took a look at https://github.com/orta/vscode-jest/issues/85
The `getBabelRC` currently returns `""` as it was based on the original, but really, the results get thrown directly into `JSON.parse` in the `parse` function. Which raises. We don't want that.
**Test plan**
Kinda hoping everything greens, I couldn't get a working set up locally :D
=> Update the jest-editor babylon parser to return an empty JSON object + CRA changes

README.md, docs/MigrationGuide.md, docs/TestingFrameworks.md, docs/Troubleshooting.md
**Summary**
Fixes #2714. 
It's missing Ember, but it can be added later, if we find something suitable.
**Test plan**
=> Add Testing other frameworks guide

docs/TestingAsyncCode.md, docs/TutorialAsync.md
The [Testing Asynchronous Code](http://facebook.github.io/jest/docs/asynchronous.html) and [Async Example](http://facebook.github.io/jest/docs/tutorial-async.html) in the docs currently make no mention of the fact that `expect.resolves()` will not be available until v20.0+.
A [similar caveat was added](https://github.com/facebook/jest/pull/3172/commits/797af540890e6ea4f906beb3f1fb7f9169edb711) to the [Expect API ](http://facebook.github.io/jest/docs/expect.html) page.
=> Clarify docs: resolves is introduced in v20

packages/jest-jasmine2/src/__tests__/queueRunner-test.js, packages/jest-jasmine2/src/queueRunner.js, packages/jest-jasmine2/src/treeProcessor.js
**Summary**
Fixes `done.fail()` not passing arguments. Arrow functions don't bind `arguments`, so I used a regular function instead. 
Thanks @jwbay.
**Test plan**
Added a test for that.
=> Fix done.fail not passing arguments

packages/jest-matcher-utils/src/__tests__/index-test.js, packages/jest-message-util/src/__tests__/__snapshots__/messages-test.js.snap, packages/jest-message-util/src/__tests__/messages-test.js, packages/jest-mock/src/__tests__/jest-mock-test.js
**Summary**
improve some code coverage for the packages `jest-message-util`, `jest-mock` and `jest-matcher-utils`
**Test plan**
`yarn test`
=> improve code coverage

packages/jest-cli/src/__tests__/__snapshots__/watch-test.js.snap, packages/jest-cli/src/watch.js
**Summary**
This is a compromise we agreed on for #2978. Let's hide it from regular users until it's solid.
cc: @gaearon @zouxuoz @rogeliog
=> Temporarily remove filtering by a test name from Watch Usage

packages/jest-cli/src/reporters/SummaryReporter.js
**Summary**
Fixes https://github.com/facebook/jest/issues/3262
**Test plan**
```
$ npm test
Snapshot Summary
› 1 obsolete snapshot found, run with `npm test -- -u` to remove them.
```
```
$ yarn test
Snapshot Summary
› 1 obsolete snapshot found, run with `yarn test -- -u` to remove them.
```
=> Detect npm client in SummaryReporter

docs/SnapshotTesting.md
**Summary**
Ensures consistency of [snapshot example](https://github.com/facebook/jest/blob/master/examples/snapshot/__tests__/__snapshots__/Link.react-test.js.snap#L58-L67) in `docs/SnapshotTesting.md`.
**Test plan**
Modification of documentation.
=> Docs: Ensure consistency of example in SnapshotTesting.md

packages/babel-jest/src/index.js
**Summary**
Adds support for Babel 7:
- loading from `.babelrc.js` file
- babel deprecated and removed `babel.util` (no need for it, [apparently](https://github.com/babel/babel/pull/5487))
**Test plan**
I've tested this locally and it works well. The changes are pretty minimal.
The question I have is why was the `canCompile` call there in the first place? Here's the PR to Babel that removed the util: https://github.com/babel/babel/pull/5487. It recommends simply calling `.transform` instead (which is currently being done anyway.
=> Add support for Babel 7 in babel-jest

docs/Configuration.md
The @jest-environment docblock is a feature that's coming in Jest version 20.0.0.
This commit adds this information to the documentation.
=> Update configuration docs about @jest-environment

docs/GettingStarted.md
Fixes #3282 
As the default is `moduleFileExtensions: ['js', 'json', 'jsx', 'node'],` I think it makes sense to add the `".json"`. Should we add the `"node"` -  I've never seen the filetype before?
=> Add JSON to the list of recommended moduleFileExtensions for TS users

packages/jest-jasmine2/src/__tests__/integration/lifecycle-hooks-test.js, packages/jest-jasmine2/src/jasmine/Suite.js
**Summary**
It was discovered that afterAll hooks run in the same order that you add them,
while afterEach hooks were running in reverse order.  This commit makes their
order consistent, and adds regression tests.
Relevant issue - #3268
Note that even if this test were failing, it occurs in an afterAll hook which doesn't currently fail w/ errors.
**Test plan**
I added tests in the relevant package and tested with a combination of `yarn run build` and `yarn run jest ./packages/jest-jasmine2/src/__tests__/integration`.
The new tests were adapted from a similar set of tests in Jasmine.
=> [lifecycle hooks] Make afterAll hooks operate in the fashion as afterEach.

packages/jest-cli/src/TestNamePatternPrompt.js, packages/jest-cli/src/TestPathPatternPrompt.js, packages/jest-cli/src/watch.js
**Summary**
Part of https://github.com/facebook/jest/pull/3156, pulled out for easier review and more incremental shipping.
cc @thymikee @zouxuoz 
**Test plan**
jest
=> Refactor watch mode prompts.

packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/TestSequencer.js, packages/jest-cli/src/__tests__/TestRunner-test.js, packages/jest-cli/src/__tests__/TestSequencer-test.js, packages/jest-cli/src/reporters/BaseReporter.js, packages/jest-cli/src/reporters/CoverageReporter.js, packages/jest-cli/src/reporters/DefaultReporter.js, packages/jest-cli/src/reporters/VerboseReporter.js, packages/jest-cli/src/runJest.js, types/TestRunner.js
**Summary**
Pulling out commit #2 from https://github.com/facebook/jest/pull/3156 to make the other diff easier to review as I add more stuff on top of it. This is changing how reporters work a little bit but there may be some more changes later.
cc @abdulhannanali 
**Test plan**
jest
=> Pass “Test”s to reporters; update Test to contain contexts.

packages/jest-cli/src/watch.js
**Summary**
This change is to prevent the screen from clearing when building for Continuous Integration systems. While the `--watch` flag typically wouldn't be used on a CI system, this change gives us a hook into disabling the clear feature that can prevent other processes' output from being seen during a typical development workflow.
**Test plan**
I was able to verify this worked using the `CI=true jest --watchAll` npm-script in my project. Without the `CI` value set, the standard behavior of the screen clearing between watch runs, occurs.
Fixes #2959.
=> Clears screen during watch mode correctly.

packages/eslint-plugin-jest/src/rules/__tests__/valid-expect-test.js, packages/eslint-plugin-jest/src/rules/valid-expect.js
**Summary**
Part 1 of #3082 split up, see that for justification. I'll send a PR for locations soon™️ 
**Test plan**
See added tests which failed before this change
=> ESlint: Handle modifiers on `expect` in `valid-expect`

docs/CLI.md, integration_tests/__tests__/__snapshots__/showConfig-test.js.snap, integration_tests/__tests__/showConfig-test.js, packages/jest-cli/src/cli/args.js, packages/jest-cli/src/cli/runCLI.js, packages/jest-cli/src/lib/__tests__/logDebugMessages-test.js, packages/jest-cli/src/lib/logDebugMessages.js, packages/jest-editor-support/src/Settings.js, packages/jest-editor-support/src/__tests__/Settings-test.js
**Summary**
This solves #3288. It adds a JSON output of the config and then exits.
- Adds a `--showConfig` argument.
- Updates the `--debug` output to be JSON.
- Updates the `jest-editor-support` package to use `--showConfig`.
**Test plan**
- Integration tests pass.
- `jest --showConfig` outputs config and exits.
=> Add --showConfig argument

packages/jest-cli/src/__tests__/runJest-test.js, packages/jest-cli/src/runJest.js
**Summary**
Fixes #3297.
**Test plan**
Adds a very basic test for `runJest`. To be updated after #3156.
=> Make sure updateSnapshot propagates hasteContext.config

docs/TutorialReact.md
I’ve seen a few people installing Jest *on top of* Create React App. This intro paragraph is easy to miss, and since we link to this tutorial from the React website, people try following these steps. Adding explicit headers might help here.
=> Make it clear CRA users don't need to add dependencies

packages/jest-cli/src/SearchSource.js, packages/jest-cli/src/TestPathPatternPrompt.js, packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/TestSequencer.js, packages/jest-cli/src/__tests__/SearchSource-test.js, packages/jest-cli/src/__tests__/TestRunner-test.js, packages/jest-cli/src/__tests__/TestSequencer-test.js, packages/jest-cli/src/__tests__/runJest-test.js, packages/jest-cli/src/__tests__/watch-filename-pattern-mode-test.js, packages/jest-cli/src/__tests__/watch-test-name-pattern-mode-test.js, packages/jest-cli/src/__tests__/watch-test.js, packages/jest-cli/src/cli/args.js, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/cli/runCLI.js, packages/jest-cli/src/lib/getTestPathPattern.js, packages/jest-cli/src/lib/handleDeprecationWarnings.js, packages/jest-cli/src/lib/setState.js, packages/jest-cli/src/reporters/BaseReporter.js, packages/jest-cli/src/reporters/CoverageReporter.js, packages/jest-cli/src/reporters/DefaultReporter.js, packages/jest-cli/src/reporters/NotifyReporter.js, packages/jest-cli/src/reporters/SummaryReporter.js, packages/jest-cli/src/reporters/__tests__/CoverageReporter-test.js, packages/jest-cli/src/runJest.js, packages/jest-cli/src/watch.js, types/Reporters.js, types/TestRunner.js
**Summary**
Context: #2970 
This diff is the initial RFC for the multi-project runner. This is the proposal that merges all functionality into jest-cli which will make Facebook's internal multi-runner obsolete. The initial draft changes the Jest CLI to operate on a list of `TestContext`s, which is a new name for HasteContexts with the configuration object added to it. This is basically the entire extent of the added complexity to make this work, the rest is refactors that should be made regardless.
The refactoring of the TestSequencer, runCLI and usage of async/await alone make the codebase actually easier to understand and concerns are separated better with this diff applied. These changes were already landed as part of this PR.
**TODO**
* We need to make it so that there is an overall …
=> [RFC] Multi project runner

packages/jest-cli/src/TestNamePatternPrompt.js
Really small polish on the footer of the typeahed
**Before**
**After**
=> Fix spacing in test name pattern typeahead

docs/TutorialReact.md
Enzyme recently made a fix for console warning if we use React v15.5+ , See issue here: https://github.com/airbnb/enzyme/pull/876
To fix that, we have to install react-test-render instead of react-addons-test-utils
Warning:
``` 
console.error node_modules/fbjs/lib/warning.js:36
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
console.error node_modules/fbjs/lib/warning.js:36
Warning: Shallow renderer has been moved to react-test-renderer/shallow. Update references to remove this warning.
```
**Summary**
**Test plan**
=> install react-test-render to  fix Enzyme console warning

scripts/_runCommand.js, scripts/test_examples.js
**Summary**
Fixes [failing CircleCI](https://circleci.com/gh/facebook/jest/947?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) by linking to `.../node_modules/*` instead of `.../node_modules/`. This prevents permission issues while linking existing packages.
I've also adjusted the console output a little (display only example name and get rid of extra indentation for command after `cd`, it's just easier to read it this way):
**Test plan**
`yarn test-examples` pass on all CI servers
=> Fix symlinking babel-jest to examples

packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/reporters/BaseReporter.js, packages/jest-cli/src/reporters/CoverageReporter.js, packages/jest-cli/src/reporters/DefaultReporter.js, packages/jest-cli/src/reporters/NotifyReporter.js, packages/jest-cli/src/reporters/SummaryReporter.js, packages/jest-cli/src/reporters/getResultHeader.js, packages/jest-cli/src/reporters/utils.js, types/Config.js
**Summary**
This adds a "GlobalConfig" type as a first step to separate configs into a "GlobalConfig" and "ProjectConfig". GlobalConfig works better than SharedConfig because it isn't actually shared – I think the two configs will end up having almost no overlap, if any at all, so that makes more sense.
Right now it is not an exact type yet and it is still exactly the same value as before, this diff only changes typings but I'd like to ship this incrementally in smaller PRs :)
**Test plan**
yarn typecheck
=> Add “GlobalConfig” type.

packages/jest-editor-support/src/parsers/BabylonParser.js
**Summary**
`.babelrc` is the config file of `babel` and not `babylon`. Loading plugins from `.babelrc` and supplying them to babylon does nothing. `babylon` will not fail but silently ignore invalid plugins.
In future we want to have a way to use `.babelrc` (or similar) for babylon, but we are not there yet.
I noticed this while searching for why `vscode-jest` does not work with jsx syntax, but this is due to #3076 not being released yet.
//cc @orta
=> Remove handling of babelrc in jest-editor-support

packages/jest-util/src/Console.js
Summary: This is task 17383791. The goal was to modify a single file (Console.js) so that it passes the lint checks.
Test Plan: yarn eslint [path]/Console.js passes when we check for weak typing in .eslintrc file. yarn test passes when we disable check for weak typing.
Reviewers: adr
Subscribers: adr
=> Added flowtype typing to constructor arguments

packages/jest-mock/src/__tests__/jest-mock-test.js, packages/jest-mock/src/index.js
**Summary**
Fixes #3320
**Test plan**
`yarn jest`
=> Support setting returnvalue from mock to `undefined`

packages/jest-runtime/package.json, packages/jest-runtime/src/transform.js
**Summary**
We are encountering some errors on our CI machines, but the error message is not clear about the exact reason making it impossible to write the cache file. This changeset aims to expose the inner error message, that includes the errno code, that could be for example EACCESS or ENOENT.
**Test plan**
Automated testing.
=> jest-runtime: expose inner error when it fails to write cache

packages/jest-config/src/defaults.js
**Summary**
It appears in some contexts, `os.tmpdir()` doesn't make a difference between different users. As a result, you can run some script that runs `jest-runtime` once using `root`, then later using a non-privileged user; this crashes because that user is unable to write files owned by `root`. Separating by UID helps avoiding permission conflicts on files created by the cache logic.
**Test plan**
Automated testing. Would you suggest a particular test plan for this?
=> jest-config: use UID for default cache folder

circle.yml, crowdin.yaml
On last master build, crowdin-cli could not access the ENV variable CROWDIN_API_KEY. I was able to workaround this by replacing the two yarn commands ("yarn crowdin-upload" and "yarn crowdin-download") in circle.yml with their full commands.
=> Fixing a bug with crowdin-cli tool and yarn command not inheriting environment variables.

packages/jest-config/src/defaults.js
**Summary**
If `jest` runs first as `root`, then as non-`root`, then the top-level `/tmp/jest` folder will be owned by root and will not allow write permissions for the non-`root` instance. So we need to use completely different top-level folders for each user. We assume that we always have write permissions on the top-level `/tmp` or whichever `os.tmpdir()` returns.
**Test plan**
Automated testing.
=> jest-config: UID needs to be part of top-level folder

packages/jest-cli/src/TestNamePatternPrompt.js, packages/jest-cli/src/TestPathPatternPrompt.js, packages/jest-cli/src/__tests__/__snapshots__/watch-filename-pattern-mode-test.js.snap, packages/jest-cli/src/watch.js
This issue got introduced by #3327 
**Summary**
The position of the cursor is wrong in some terminals like Terminal.app, but not in other terminals that do support clearScreen
**Test plan**
Here is the before and after
=> Fix filter input when using Terminal.app

package.json
**Summary**
@jeanlauliac pointed out that it is confusing that yarn prints "Done in *time*" multiple times because all our scripts invoke Yarn. @bestander recommended adding `--silent`. It makes the `package.json` file bigger but the output more sane.
**Test plan**
* Run all the commands from scripts
* Wait for CI
=> Make yarn silent.

.flowconfig, package.json, yarn.lock
**Summary**
Bumps flow to the latest version.
They said something about perf wins in 0.43.1 and 0.44, but it actually takes 2s more for `flow check` now :(
**Test plan**
flow
=> Bump flow to 0.45

packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/reporters/CoverageReporter.js, packages/jest-cli/src/reporters/CoverageWorker.js, packages/jest-cli/src/reporters/__tests__/CoverageReporter-test.js, packages/jest-cli/src/reporters/__tests__/CoverageWorker-test.js
based on https://github.com/facebook/jest/pull/3309
i had to resolve some conflicts (multi runner/config splitting touched the same files)
=> Parallel coverage

packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-matchers/src/matchers.js, packages/jest-matchers/src/utils.js
**Summary**
Fixes #3409.
**Test plan**
Add new test for object without a prototype.
=> Fix toHaveProperty() to use hasOwnProperty from Object

docs/CLI.md, docs/JestObjectAPI.md
**Summary**
As discussed in #3364 
Update docs to include a warning about how importing modules in a setup file will circumvent the mocking system.
=> Add warning about setup file and mocking

packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/reporters/CoverageReporter.js, packages/jest-cli/src/reporters/CoverageWorker.js, packages/jest-cli/src/reporters/__tests__/CoverageReporter-test.js, packages/jest-cli/src/reporters/__tests__/CoverageWorker-test.js
**Summary**
This is a follow-up to @dmitriiabramov's PR from an open source contributor.
* `onRunComplete` has to be run sequentially, not concurrently so that we always print messages in the same order.
* Add ability to run untested coverage in-band when workers is <= 1.
* `--bail` also has to wait for the response from reporters before continuing with the test run, otherwise tests will run while it tries to clean up.
* Fixed up code style.
**Test plan**
jest
=> Fix coverage for untested files.

packages/pretty-format/src/__tests__/HTMLElementPlugin-test.js, packages/pretty-format/src/__tests__/expect-util.js, packages/pretty-format/src/index.js, packages/pretty-format/src/plugins/HTMLElement.js, types/PrettyFormat.js
**Summary**
(I've edited this since opening (and deleted my comments on the way), as I was able to fix it myself)
Support printing text and comment nodes with the HTML pretty printer.
**Test plan**
`yarn jest`
/cc @mute
=> Support text and comment nodes in html pretty printing

docs/ExpectAPI.md, integration_tests/__tests__/__snapshots__/failures-test.js.snap, integration_tests/__tests__/failures-test.js, integration_tests/failures/__tests__/assertion-count-test.js, packages/jest-jasmine2/src/jest-expect.js, packages/jest-jasmine2/src/setup-jest-globals.js, packages/jest-matchers/src/__tests__/assertion-counts-test.js, packages/jest-matchers/src/index.js, packages/pretty-format/src/plugins/AsymmetricMatcher.js, types/Matchers.js
Fixes #3371 
1. Updated docs for `.hasAssertions` API Change
2. Added test cases in `integration-tests`
3. Removed `yarn.lock` from pull request
**Summary**
**Test plan**
Unit test cases along with integration tests have been added.
=> Adding .hasAssertions to expect API

docs/GettingStarted.md
Updating documentation for jest-cli regarding `.babel` transformation without explicit installation of `babel-jest`.
Fixes #3405 
**Summary**
Updating documentation for files transformation by `babel` without `babel-jest`
**Test plan**
=> Updating documentation for jest-cli regarding `.babel` transformation

docs/SnapshotTesting.md
**Summary**
There are a few common misconceptions around snapshot testing that always come out when engineers are approaching this technique for the first time.
The new "frequently asked questions" section aims to answer the most common ones, giving clarity to the engineers.
These questions have been collected during conferences, meetups and within issues and PRs.
**Test plan**
- cd website
- yarn
- yarn start
- go to http://localhost:8080/jest/docs/snapshot-testing.html#frequently-asked-questions
=> Add snapshot testing FAQs

docs/ExpectAPI.md, docs/GlobalAPI.md, docs/TestingAsyncCode.md, docs/TutorialAsync.md, examples/async/__tests__/user-test.js
**Summary**
This pull request changes the documentation at several places regarding the recent async testing handling using `.resolves` and `.rejects`.
* Change wording of `.resolves` and `.rejects` API docs.
* Use ‘lemon’/‘octopus’ in Expect API docs.
* ~~Remove *old* (non-resolves) promise assertions everywhere in docs~~
* Add info about `.rejects` matcher in ‘Testing Asynchronous Code’.
* Update comments in Async tutorial and updated example files.
Related PR: #3172, #3068
**Test plan**
Changes in the docs.
=> Update promise docs

README.md, docs/en/GettingStarted.md
**Summary**
Suggest a small change to the match pattern for TS transformer.
The regex for TS transformer in the doc is too broad. For example, I set
the regex to `".(ts|tsx)"` as recommended in the docs and my test would
fail. The reason is that  one of my tested file imports the file `isArguments.js`
from `lodash-es` (ES 2015 build of lodash). Because `isArguments.js` matches the pattern
`.(ts|tsx)`, this file is not transpiled by babel (even after I've set
`transformIgnorePatterns` to `"<rootDir>/node_modules/(?!lodash-es)"`.
Changing the pattern to `"^.+\\.tsx?$"` fixes this problem. I think this will help others avoid the same problem.
**Test plan**
```js
// sample.ts
import sortBy from 'lodash-es/sortBy';
export function sample() {
// 
}
```
```js
// sample.test.js
import {
sample,
} …
```
=> Improve TS instructions

packages/jest-config/src/findConfig.js
**Summary**
This fixes `yarn test-examples` on master. Previously, it traversed up the tree until it found a jest config in package.json, now it stops when it finds a `package.json` as that can be considered the root of an app.
**Test plan**
`yarn test` works again.
=> Fix new jest.config.js behavior.

integration_tests/__tests__/__snapshots__/showConfig-test.js.snap, integration_tests/__tests__/__snapshots__/snapshot-test.js.snap, integration_tests/__tests__/showConfig-test.js, integration_tests/__tests__/snapshot-serializers-test.js, integration_tests/__tests__/snapshot-test.js, integration_tests/__tests__/toMatchSnapshot-test.js, integration_tests/__tests__/toThrowErrorMatchingSnapshot-test.js, packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/__tests__/watch-test.js, packages/jest-cli/src/cli/args.js, packages/jest-cli/src/watch.js, packages/jest-config/src/normalize.js, packages/jest-editor-support/src/__tests__/TestReconciler-test.js, packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/setup-jest-globals.js, packages/jest-snapshot/src/State.js, packages/jest-snapshot/src/__tests__/utils-test.js, packages/jest-snapshot/src/index.js, packages/jest-snapshot/src/utils.js, packages/pretty-format/src/__tests__/AsymmetricMatcher-test.js, types/Argv.js, types/Config.js, types/Matchers.js
**Summary**
When running on a CI environment or with `--ci`, Jest will now refuse to write new snapshots. This is so that on CI, uncommitted snapshots will fail rather than pass by writing new files every time.
I introduced a `--ci` field and changed the `updateSnapshot` field into one of three states: `none`, `all` or `new`. None won't write any snapshot files, `all` will write all and clean snapshots up and `new` will only create new snapshots.
**Test plan**
* `jest`
=> Do not write snapshots by default on CI

crowdin.yaml
**Summary**
A recent crowdin change removed folder hierarchy of files causing duplicate files to be uploaded. This setting enabled it so files are stored properly.
**Test plan**
Verified locally.
=> Preserve folder hierarchy when uploading documents to Crowd In

docs/en/ExpectAPI.md, packages/jest-matchers/src/__tests__/extend-test.js, packages/jest-matchers/src/index.js, types/Matchers.js
**Summary**
This was previously exposed through `jasmine.matcherUtils.equals`. It's now part of the custom matcher API so that it can be used in libraries like Relay.
**Test plan**
See added test.
=> Expose `this.equals` to custom matchers.

scripts/build.js
**Summary**
Related to #3360.
https://github.com/facebook/jest/pull/3421 introduced additional es5 builds of speciic Jest packages meant for use in browsers. But as `async/await` is used some places (and possibly other ES6 feature), the transpilation was missing `transform-runtime` in order to work for consumers.
Alternatives to this solution
- stop using `async/await` (and possibly other es6 features) in packages like `jest-matchers`
- make consumers provide the babel global runtime (but gives a pretty bad DX)
Should be noted that this proposed solution needs the consumer to install `babel-runtime`. This should be documented when browser support is made public.
**Test plan**
Do a beta build and test on https://github.com/ReactTraining/react-media/pull/61
=> Add babel-transform-runtime to browser builds

packages/jest-cli/src/TestSequencer.js, packages/jest-cli/src/__tests__/TestSequencer-test.js
**Summary**
When there was no cache, we failed to create a new cache object and instead created a new object for every call to `getCache` which means we'll never end up with a proper cache file. I didn't notice probably because when I built this, I had a valid cache file.
**Test plan**
* See newly added test
=> Fix TestSequencer to use proper cache object.

integration_tests/__tests__/__snapshots__/jest.config.js-test.js.snap, packages/jest-cli/src/runJest.js, packages/jest-config/src/findConfig.js
**Summary**
This fixes configs, again. This is a can of worms, I'm unhappy about the new feature as much as I am happy about it :(
This has one behavior change:
* For running Jest in subfolders, it correctly prints the relative path for each test again.
* For running Jest in parent folders by traversing up the tree to find a package.json, it now shows relative paths for tests rather than the path from the root directory. I could argue both are ok and I may reconsider changing this again. Right now, I don't have enough time to find the one that makes the most sense, tbh.
**Test plan**
* `cd ../; jest --projects jest` works again.
=> Fix findConfig for `cd ../; jest --projects jest`.

integration_tests/__tests__/__snapshots__/showConfig-test.js.snap
Woo, 20! Master is failing because of this snapshot.
Should remove or change the version field to avoid this in the future
=> Update config snapshot

packages/eslint-plugin-jest/README.md
Remove extra trailing at the last line of rules
**Summary**
Trailing comma or any other violations are causing .json files stop working
=> Fix trailling comma

packages/pretty-format/package.json, packages/pretty-format/yarn.lock
=> Add ansi-regex to pretty-format deps

website/server/convert.js, website/server/feed.js
**Summary**
This PR fixes a problem with the website's launching sequence on Windows when running `yarn start`. In some cases it seems to be necessary to replace the `\n` character with the OS' specific one through node's `os.EOL` constant because the `\r` character remains if just `\n` gets replaced on a Windows (10) machine.
The change in `feed.js` (`TypeError: Cannot read property '1' of null`) actually brings the site back up whereas the change in `convert.js` displays the blog post preview texts (not displayed without the change).
**Test plan**
N/A, only clicked it through on a Windows and Mac.
=> Fix website's yarn start on Windows

packages/jest-config/package.json
The `jest-config` package [depends](https://github.com/facebook/jest/blob/master/packages/jest-config/src/reporterValidationErrors.js#L18) on `jest-matcher-utils`, which isn't listed into its dependencies. It breaks the installation when running a package manager with no hoisting mechanism :)
=> Add missing dependency

packages/jest-config/src/__tests__/normalize-test.js, packages/jest-config/src/normalize.js
**Summary**
Fixes regressions described in #3535 and #3499
**Test plan**
Update `normalize-test.js` accordingly.
=> Replace <rootDir> in testMatch and moduleDirectories

README.md, docs/en/MoreResources.md, website/i18n/en.json, website/layout/ReferenceLayout.js
**Summary**
I have tried to edit an existing page in the documentation and landed on GitHub's 404 page because the edit link was missing the language code. This PR is adding those to problematic links.
_I have not touched any references in older blog posts or changelogs, but can also do this if you want._
As a side not it might be good to add canonical/hreflang tags to improve search engine indexing. At least a redirect from non-en to en might be helpful since these pages are now already indexed and users who come from there will still land on these pages _(the sidebar isn't fully rendered there for some reason)_.
**Test plan**
N/A
=> Fix broken docs/en links

packages/jest-jasmine2/src/jasmine-async.js
**Summary**
Currently the `this` context we're passing in `before/after` (although here `this` is undefined, and I didn't even try to investigate why) and `it/test` functions is preserved across consequent `test` runs, which makes it confusing to use (see #3505). 
As a workaround I propose passing empty object as a context for each function. This way we can still use `this` in `test` but it will be unique for each test function.
Fixes #3505.
**Test plan**
I'll add an integration test later, after we agree this is the right solution.
=> Reset context between test functions

integration_tests/__tests__/__snapshots__/stack_trace-test.js.snap, integration_tests/__tests__/stack_trace-test.js, integration_tests/stack_trace/__tests__/stack-trace-without-message-test.js, packages/jest-jasmine2/src/reporter.js
**Summary**
While working on Angular integration I bumped into this issue: https://github.com/thymikee/jest-preset-angular/issues/30.
For some weird reasons (probably Zone.js) `error.message` is not present in `error.stack` for _some_ errors like it is normally on Node.
Turns errors with _malformed_ stack trace from this:
into this:
**Test plan**
Integration test.
=> Support stack traces without proper message

docs/en/Webpack.md
**Summary**
A common issue for developers using Webpack 2 is Jest's caching of .babelrc. @cpojer mentioned it on Mar 5, 2016: https://github.com/facebook/jest/issues/770#issuecomment-192813963
This PR adds a short note explaining how to disable the cache.
**Test plan**
I copied the new markup into Dilinger's online markdown editor to ensure it is formatted correctly.
=> Mention that .babelrc might by cached

packages/jest-matchers/src/__tests__/assertion-counts-test.js, packages/jest-matchers/src/index.js
* `expect.hasAssertions()` should not allow useless parameters to limit confusion with `expect.assertions(<n>)`.
Fixes #3517
**Summary**
`expect.hasAssertions` now throws an exception when is passed parameters which clarifies its difference from the similar matcher, `expect.assertions(<n>)`.
**Test plan**
* `yarn test`
=> expect.hasAssertions should throw when passed arguments

integration_tests/__tests__/__snapshots__/showConfig-test.js.snap, integration_tests/__tests__/showConfig-test.js
**Summary**
When publishing Jest 20, this was quite the funny error on CI ;)
**Test plan**
jest + when a version is published, this test won't fail.
=> Fix showConfig test not to include the current Jest version

integration_tests/resolve/__tests__/resolve-test.js, integration_tests/resolve/package.json, packages/jest-resolve/src/index.js
**Summary**
This PR adds support for absolute resolution of files with custom extension in haste packages.
Jest support so-called "haste packages" which allow to place `package.json` with a `name` property providing a custom namespace for modules inside directory it resides. Since resolution for these haste packages use `require.resolve`, it doesn't support absolutely resolving custom extensions, like `.ios.js` or `.android.js`, it's just working with `.js` files. 
Such resolution mechanism works in React Native, I think it would be nice for Jest to support it.
Fixes #3342.
**Test plan**
Integration test.
=> Support absolute path to custom extension through haste package

packages/jest-cli/src/ReporterDispatcher.js
Fixes #3520
Fixed async calls to each reporter onRunComplete method
**Summary**
Whenever the `coverage` is enabled, jest exits with 0 even if the threshold requirements are not met.
The Coverage reporter will not return a resolved promise when `collectCoverageFrom` matches files and consequently the Dispatcher will resolve the `onRunComplete` promise before collecting the result from reporter.
=> Failure when coverage threshold not met

package.json, yarn.lock
**Summary**
Currently running `yarn` in the jest repo prints `warning "react-test-renderer@15.5.4" has incorrect peer dependency "react@^15.5.0".`.
**Test plan**
Running `yarn` in the jest repo should produce no peer dep warnings.
=> Normalise all version of react

integration_tests/__tests__/__snapshots__/custom-reporters-test.js.snap, integration_tests/__tests__/custom-reporters-test.js, packages/jest-cli/src/TestRunner.js
**Summary**
Fixes a "cannot find module" error when the reporters config includes the string "default" (the documented way to keep the default reporters enabled).
**Test plan**
Added new test.
=> Fix "reporters: ['default']" config

integration_tests/__tests__/__snapshots__/custom-reporters-test.js.snap, packages/jest-config/src/reporterValidationErrors.js, packages/jest-validate/src/utils.js
**Summary**
Fixes double error message like this [here](https://github.com/facebook/jest/pull/3567/files#diff-0454b3bf8e9e55c3655f3be2ff46cf28R14).
Also adjusted indentation in reporter errors messages
**Test plan**
Doesn't break anything, works with https://github.com/facebook/jest/pull/3567
=> Empty stack for ValidateError

docs/en/Configuration.md
**Summary**
As discussed in https://github.com/facebook/jest/issues/2972#issuecomment-301737420, this PR tries to clarify the behaviour of resetMocks vs clearMocks.
=> (docs): clarify clear vs reset mocks

packages/jest-validate/src/utils.js
**Summary**
Setting `this.stack = '';` breaks some tests Node 6. I still need to figure out what's the case with some errors having duplicated message [like this](https://github.com/facebook/jest/pull/3567/files#diff-0454b3bf8e9e55c3655f3be2ff46cf28R22)
=> Revert setting stack to empty string

packages/jest-editor-support/src/Settings.js, packages/jest-editor-support/src/__tests__/Settings-test.js
**Summary**
If there is no output from the process to check for settings, then this function never returns. In pre-Jest 20, it would close with errors so the callback never triggered. Now it will call it when the process is over instead.
**Test plan**
Has tests 👍
=> [Editor] Ensure that the check for settings always returns

docs/en/TutorialReactNative.md
The current example for using `transformIgnorePatterns` to test ReactNative apps doesn't matches anything because the `/` is at the end.
```
new RegExp("node_modules/(?!react-native|my-project|react-native-button)/").test('node_modules/')
false
new RegExp("node_modules/(?!react-native|my-project|react-native-button)/").test('node_modules/react-native/')
false
new RegExp("node_modules/(?!react-native|my-project|react-native-button)/").test('node_modules/my-project/')
false
new RegExp("node_modules/(?!react-native|my-project|react-native-button)/").test('node_modules/my-project-foo/')
false
```
When we put the slash inside the parens, it does what I believe we expect.
```
new RegExp("node_modules/(?!(react-native|my-project|react-native-button)/)").test('node_modules/')
true
new …
```
=> [docs] Fix regex for ReactNative transformIgnorePatterns

docs/en/CLI.md
**Summary**
Added the missing closing quote.
**Test plan**
Try executing the example command in your shell:
```
➜  my-project git:(master) jest "my.*(complex)?pattern
dquote>
```
Obviously, the shell expects the quote to be closed. That's what I did in this PR.
=> Fix typo in docs for CLI

packages/jest-cli/src/reporters/utils.js
**Summary**
On windows (cmd, powershell, and cmder/conemu) the progress bar was broken. The issue is windows doesnt fully support inverse, and so just renders blank spaces. Changing it to a block character (ascii 219) and removing the inverse fixes this, and should still look the same across other terminals that worked before this change.
**Test plan**
Not needed(?)
=> Fix progress bar in windows

packages/jest-runtime/src/__tests__/Runtime-requireModuleOrMock-test.js, packages/jest-runtime/src/index.js
**Summary**
This PR causes the jest-runtime to build out the unmocked module list even when automock is set to false. This makes it possible for jest tests to enableAutomock and still keep certain modules unmocked as expected.
**Test plan**
`yarn test` comes back clean.
Plus, I added a test to verify the module was built. Running the test before the change fails. Running after passes.
=> fixes bug with enableAutomock when automock is set to false

packages/jest-haste-map/src/__tests__/index-test.js, packages/jest-runtime/src/__tests__/Runtime-requireModuleOrMock-test.js, packages/jest-runtime/src/index.js
The way duplicate module IDs are handled is broken right now. `jest-haste-map` doesn't recover from duplicate module IDs, because it systematically loose track of one of the duplicates, unable to recover it ever after. This changeset adds the structure of the test to show that it's broken, and put comment where we'll want to change the lines once it's fixed.
**Test plan**
Unit test, no logic change.
=> jest-haste-map: add test to check duplicate modules are broken

packages/jest-editor-support/src/parsers/BabylonParser.js
Fixed spelling of multiple
**Summary**
multiple was spelled wrong
**Test plan**
now it's spelled right.
=> fix spelling

packages/jest-haste-map/src/__tests__/index-test.js, packages/jest-haste-map/src/index.js, types/HasteMap.js
This supersedes #3107. This changeset adds a new top-level structure to the "HasteMap" object kept internally. This structure keeps track of duplicated modules. We cannot keep track of these in the existing `map` field, that accepts only a single resolution per module name/ID. An alternative solution would have been to change the structure of `map`, for example to keep an array of file paths for each module name/ID. However, this would incur significant overhead persisting the whole "HasteMap". By adding a separate index structure, that only contains the strict necessary, we ensure minimum overhead is added for persistence.
**Test plan**
Unit tests. As you can see, I fixed the unit tests that were testing the broken behavior, that is now correct.
=> jest-haste-map: recover from duplicate IDs

docs/en/Webpack.md
**Summary**
These are written like string-based regex's for JSON, but are actually regex literals.
This image shows the error pretty clearly. These regex patterns are taken from a JSON config where they are strings, but, being literals, the slashes do not need to be escaped.
**Test plan**
N/A. It's documentation.
=> correct the example webpack regex's

integration_tests/__tests__/node_path-test.js, integration_tests/node_path/__tests__/node_path-test.js, integration_tests/node_path/package.json, integration_tests/node_path/src/path/file.js, integration_tests/runJest.js, packages/jest-resolve/src/__tests__/resolve-test.js, packages/jest-resolve/src/index.js
The downstream issue was reported in https://github.com/facebookincubator/create-react-app/issues/2230#issuecomment-302673174. The reproducing case is in https://github.com/ingro/cra-test-bug.
Babel Jest transform started climbing directories searching for `package.json`. People who run Jest with `NODE_PATH=src` and then import `App` expecting it to resolve to `src/App.js` started getting this error:
```
Cannot find module 'package.json'
at Function.Module._resolveFilename (module.js:470:15)
at Function.Module._load (module.js:418:25)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
```
This is because the `filename` argument to `getCacheKey` is a relative path in this case. However the function expects it to be absolute, and all other …
=> Fix NODE_PATH resolving for relative paths

docs/en/ExpectAPI.md
`toHaveProperty()` documentation incorrectly states value is be checked with strict equality (i.e. `===` like `toBe()`). It's actually checked with deep equality like `toEqual()`.
I've corrected the ExpectAPI documentation page to reflect this, and have made it absolutely clear which type of equality is used for this matcher.
Further suggestions: The page is quite inconsistent in how it talks about equality. It'd also be convenient to have an object property matcher that did use strict equality (e.g. `toHaveStrictProperty()` etc).
**Summary**
**Test plan**
=> Fix incorrect toHaveProperty() documentation

docs/en/TestingAsyncCode.md
**Summary**
Async is used is only used in one of two similar promise examples.  The inconsistency threw me off, particularly since async is not necessary in this context.
Motivation: clarity 
**Test plan**
This is only a documentation change.
=> Delete confusing async keyword

packages/jest-snapshot/src/__tests__/plugins-test.js, packages/pretty-format/src/__tests__/Immutable-test.js, packages/pretty-format/src/plugins/ImmutablePlugins.js, packages/pretty-format/src/plugins/ImmutableRecord.js, packages/pretty-format/src/plugins/lib/printImmutable.js
**Summary**
`Immutable.Record` are not handled by `pretty-print`, but other Immutable.js structures are. `Record` are often used in Redux states for example, and Redux reducers tested using snapshots. This will allow the snapshots to be more precise, referencing proper `Immutable.Record` and not plain JS objects.
**Test plan**
I added tests for the various usecases I had in mind. 
This fixes #3677
@thymikee can you review it? I tried to not add anything Record-specific in `lib/printImmutable.js` and rely on `val._keys` and `val._name`.
`val._name` is only used for `Record`, but `Immutable.Seq` (which is not supported by `pretty-print`) also has `._keys`. Maybe I should check if `val.forEach` is defined and fallback to `val._keys`? Or should I specificaly check if a record is passed?
=> Add support for Immutable.Record in pretty-format

docs/en/JestObjectAPI.md
I tweeted Christoph to clarify if `jest.mock` was per file or in the scope of the entire test suite, and thought that this might be a question others have so no harm in adding to the docs :)
=> (docs): Add sentence to clarify `jest.mock` is per file.

.flowconfig, packages/jest-config/package.json, packages/jest-config/src/reporterValidationErrors.js, packages/jest-diff/package.json, packages/jest-diff/src/index.js, packages/jest-get-type/.npmignore, packages/jest-get-type/package.json, packages/jest-get-type/src/__tests__/index-test.js, packages/jest-get-type/src/index.js, packages/jest-matcher-utils/package.json, packages/jest-matcher-utils/src/__tests__/index-test.js, packages/jest-matcher-utils/src/index.js, packages/jest-matchers/package.json, packages/jest-matchers/src/matchers.js, packages/jest-matchers/src/toThrowMatchers.js, packages/jest-validate/package.json, packages/jest-validate/src/errors.js
**Summary**
This resolves #3528. Move the `getType` utility function from `jest-matcher-utils` to standalone package. This way `jest-config` and other packages don't need to depend on `jest-matcher-utils` for just one function.
**Test plan**
All tests still pass.
---
~~_**Note:** When I ran `yarn test` locally, It failed to typecheck inside `node_modules/jest-validate` as it was looking for `getType` function that I just removed. This comes from `prettier` depending on `jest-validate`. I assumed it was safe to just ignore that typecheck since it is inside node_modules._~~
=> Move getType from jest-matcher-utils to separate package

integration_tests/__tests__/__snapshots__/failures-test.js.snap, integration_tests/__tests__/failures-test.js, integration_tests/utils.js
error stack traces are inconsistent between node versions.
This PR automatically unifies the stack traces between different node versions to make it possible to use snapshot tests
=> cleanup stack trace in tests

.flowconfig, examples/react-native/.flowconfig, flow-typed/resolve.js, integration_tests/utils.js, package.json, packages/jest-cli/src/reporters/CoverageReporter.js, packages/jest-cli/src/reporters/SummaryReporter.js, packages/jest-cli/src/runTest.js, packages/jest-haste-map/src/index.js, packages/jest-jasmine2/src/jasmine/SpyRegistry.js, packages/jest-jasmine2/src/jest-expect.js, packages/jest-jasmine2/src/queueRunner.js, packages/jest-jasmine2/src/treeProcessor.js, packages/jest-runtime/src/ScriptTransformer.js, packages/jest-snapshot/src/utils.js, packages/jest-util/src/Console.js, packages/pretty-format/src/plugins/HTMLElement.js, packages/pretty-format/src/plugins/ReactElement.js, packages/pretty-format/src/plugins/lib/printImmutable.js, types/Environment.js, yarn.lock
**Summary**
Bump flow to latest version. Also turned on `strict_call_arity` to ease migration to 0.47.0 in the future (it will be turned on by default there). More details: https://github.com/facebook/flow/releases/tag/v0.46.0
**Test plan**
CI passes.
=> Bump flow to 0.47.0

.travis.yml, appveyor.yml, circle.yml, integration_tests/__tests__/__snapshots__/failures-test.js.snap, integration_tests/__tests__/babel-plugin-jest-hoist-test.js, integration_tests/__tests__/failures-test.js
**Summary**
Switch from Node 7 to Node 8 on all of our CIs.
I took the opportunity to refactor our failure tests to only include failure messages (`assert.doesNotThrow` now throws extra message without additional dot, they probably fixed a typo).
**Test plan**
CI green
=> Use Node 8 on CI

packages/jest-snapshot/src/index.js
**Summary**
Jest colors (expected/stored in snapshot) in single line strings in snapshots were reversed:
Before | After
------- | -----
**Test plan**
There's a repro case in http://github.com/duailibe/jest-snapshot-colors
=> Fix colors for expected/stored snapshot message

website/languages.js, website/translators.txt
**Summary**
This PR will Enable Russian, Ukrainian and Chinese Simplified for the Jest website.
Our goal here is to inspire developers in these countries to contribute further and to reward our wonderful community for all their contributions.
=> Enable: Russian, Ukrainian, and Chinese Simplified

packages/jest-validate/README.md
Simple typo fix:
``` diff
-* `comment` – optional string to be rendered bellow error/warning message.
+* `comment` – optional string to be rendered below error/warning message.
```
There isn't one.
=> Fix minor typo

website/src/jest/css/jest.css
**Summary**
when using zh_Hans, and more than 1024px width, the nav item word broken and sank.
**Test plan**
before:
after:
=> [WebSite] Fix nav item word sank when using zh. (when more than 1024px width)

packages/pretty-format/src/plugins/HTMLElement.js, packages/pretty-format/src/plugins/ReactElement.js
**Summary**
The changes because of excellent Flow `strict_call_arity` in #3568 make it clear that `if else if else` statements can become `if else` in two plugins of `pretty-format` package.
**Test plan**
Jest
=> Delete redundant branch in ReactElement and HTMLElement plugins

packages/jest-matchers/src/__tests__/symbol-in-objects-test.js, packages/jest-matchers/src/jasmine-utils.js
**Summary**
Fixes #3347 
I'm using `Object.getOwnPropertySymbols` to get the `Symbol` keys
**Test plan**
`yarn test`
=> compare objects with Symbol keys

docs/en/CLI.md
**Summary**
With Jest 20 there was new CLI option introduced `--projects`. This PR proposes documentation changes to include this new flag. It probably needs some rewording, but I wanted to open this PR to keep track of it.
**Test plan**
No tests required. Documentation change only.
=> Add `--projects` option Jest CLI Options docs

packages/babel-jest/src/index.js
**Summary**
Relates to https://github.com/danger/danger-js/issues/261 .
This PR attempts to fix cases of reading babelrc via `package.json`. Using current code path, below case is possible:
```js
//directory is '.', relative current
const packageJsonFilePath = path.join(directory, PACKAGE_JSON); 
//now packageJsonFilePath === PACKAGE_JSON, plain filename only as 'package.json'
//fs can check file exists
if (fs.existsSync(packageJsonFilePath)) { 
//node module resolution failure cause it doesn't have paths, 
//node try to resolve it as node_modules -> exception thrown
const packageJsonFileContents = require(packageJsonFilePath);
...
```
I thought of using different mechanics to detect relative current (i.e `path.relative(directory, '.')`, `path.resolve(directory, __dirname)`..) but took …
=> Prevent babelrc package import failure on relative current path

docs/en/GlobalAPI.md
**Summary**
Adds documentation, including an example, of how to use `describe()` blocks in a nested fashion. I use them this way and it appears to be well-supported, but I didn't see documentation for it.
The example is a little longer than I'd like, but I think it illustrates a common use case of testing fast exits followed by green path testing.
**Test plan**
I regenerated the website locally and the document showed up fine. I also ran the test example locally in jest and confirmed that the code works. I omitted the definition of `CustomError` in the example to keep it from being too long.
=> Add docs showing nested describe() usage

packages/jest-snapshot/src/plugins.js, packages/pretty-format/src/plugins/ReactTestComponent.js
**Summary**
The most likely reason for the redundant branches deleted in #3731 was an unsuccessful attempt at a shortcut as in `ReactTestComponent` plugin to call itself directly for children, instead of calling the generic `print` serializer argument.
When the plugin was written a year ago, that optimization made sense, but now since #3017 `pretty-format` runs plugins before serializing nested **basic** values, it is more consistent:
* to handle child test objects like prop values and other non-string children (that is, numbers :)
* to maximize similarity of `printChildren` in `ReactTestComponent`, `ReactElement`, and `HTMLElement`
This pull request has a small optimization to make up some lost time. Reorder the plugins in `jest-snapshot` to what seems like decreasing frequency of …
=> Call print for non-string children in ReactTestComponent plugin

docs/en/Configuration.md
**Summary**
Closes #3730. Provides a visualization of the regex specified in `testRegex`.
CC @thymikee
=> Provide regex visualization for testRegex

integration_tests/__tests__/globals-test.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest-adapter-init.js
a few inconsistencies.
are we going to support `xit`, `fdescribe` globals in the future?
I aliased them in the legacy/adapter part of the framework, since i'm not sure if we want to bring them in natively
=> jasmine globals + skipped->pending

docs/en/JestObjectAPI.md, docs/en/Troubleshooting.md, integration_tests/__tests__/__snapshots__/timeouts-test.js.snap, integration_tests/__tests__/timeouts-test.js, packages/jest-circus/src/run.js, packages/jest-circus/src/state.js, packages/jest-circus/src/utils.js, packages/jest-cli/src/__tests__/SearchSource-test.js, packages/jest-runtime/src/index.js, testSetupFile.js
`jest.setTestTimeout` will actually set a timeout per async fn.
So if there's a timeout of `20ms` and there's a `beforeEach` hook defined, the total timeout for a test will be `40ms` (20ms for `beforeEach` and 20ms for the test itself).
i think this is reasonable, but maybe we'll need to rename `setTestTimeout` to `setTimeout` as @cpojer suggested earlier
=> jest-circus Timeouts

packages/jest-haste-map/src/crawlers/__tests__/node-test.js, packages/jest-haste-map/src/crawlers/node.js
**Summary**
This PR updates edge cases of `nodeCrawl` in case of empty roots are provided it never completes.
**Test plan**
Test coverage's added for specific cases.
- relates to https://github.com/danger/danger-js/issues/224
=> Completes nodeCrawl with empty roots

packages/jest-circus/src/utils.js
tho things:
1. Right now the whole circus thing is going on in the inner scope, meaning the globals like `setTimeout` are shared with the test and could be mocked (which will mess up circus internals). This is a quick fix to reference the real values before any test files are imported so nothing can mess with them. (i have a task to move circus to the outer scope, it'll take a while though, cause the code that does this right now is very complex)
2. Sometimes tests won't return (exit) until all timeouts are resolved. To avoid this i save the timeout ids and clear them after the test is finished
=> fix bug when setTimeout is mocked

integration_tests/__tests__/setup_test_framework_script_file_cli_config-test.js, integration_tests/setup_test_framework_script_file_cli_config/__tests__/runner_patch-test.js, integration_tests/setup_test_framework_script_file_cli_config/setup_hooks_into_runner.js
remove jasmine references and use `describe` since it's available in both `jasmine` and `circus`
=> fix setup-test-framework-test

packages/jest-haste-map/src/lib/extractRequires.js
This makes sure that a match for `require` is not preceded by a dot and whitespace, thus skipping over method calls to `.require(…)`.
=> Avoid parsing `.require(…)` method calls

integration_tests/__tests__/__snapshots__/failures-test.js.snap, integration_tests/__tests__/failures-test.js, integration_tests/utils.js, packages/jest-circus/package.json, packages/jest-circus/src/formatNodeAssertErrors.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest-adapter-init.js, packages/jest-circus/src/state.js, packages/jest-circus/src/utils.js, packages/jest-circus/types.js, packages/jest-matchers/src/extractExpectedAssertionsErrors.js, packages/jest-matchers/src/index.js, packages/jest-matchers/src/jest-matchers-object.js, types/Matchers.js
addresses all failing tests in `integration_tests/__tests__/failures-test.js`
- handles native node `assert` module failures
- `expect.assertions(555)`
- minor formatting tweaks to make errors to be formatted the same way we do it with jasmine
=> jest-circus test failures

packages/babel-jest/src/index.js, packages/babel-preset-jest/index.js, packages/eslint-config-fb-strict/index.js, packages/eslint-plugin-jest/src/index.js, packages/jest-changed-files/src/index.js, packages/jest-cli/src/TestNamePatternPrompt.js, packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/cli/getJest.js, packages/jest-cli/src/reporters/CoverageReporter.js, packages/jest-config/src/deprecated.js, packages/jest-environment-jsdom/src/index.js, packages/jest-resolve/src/index.js, packages/jest-runtime/src/ScriptTransformer.js, packages/jest-runtime/src/cli/index.js, packages/jest-runtime/src/index.js, packages/jest-validate/src/index.js, packages/jest-validate/src/utils.js, packages/jest/src/jest.js, packages/pretty-format/src/index.js, packages/pretty-format/src/plugins/ConvertAnsi.js, packages/pretty-format/src/plugins/ImmutablePlugins.js, packages/pretty-format/src/plugins/ImmutableRecord.js
**Summary**
Move a lot of the changes in #3493 to isolate the changes causing errors.
**Test plan**
Tests should pass
=> Lift requires

README.md
**Summary**
One of the reasons I love jest the most, is snapshot testing. I use it a lot for unit and acceptance testing, so I think UI testing is only a minimal fraction of what snapshots can do and are excellent at.
This is my personal take, feel free to disagree.
**Test plan**
This PR includes only doc changes
=> Simplify snapshots definition (docs)

docs/en/ExpectAPI.md
This is sufficiently non-obvious that [some](https://medium.com/@boriscoder/the-hidden-power-of-jest-matchers-f3d86d8101b0) recommend over-using the more cumbersome `.toEqual(expect.objectContaining({ ... }))`.
=> Point out you can use matchers in .toMatchObject

packages/jest-matchers/src/utils.js
**Summary**
Updated the object matcher utility to use hasOwnProperty independent of the object passed.
Before, `expect(Object.create(null)).toMatchObject(someObject)` would throw an error, as Object.create(null) lacks the object prototype.
It appears that you all had already noticed this as you had created a helper for it, but weren't actually using it.
**Test plan**
yarn run jest --silent && yarn run test-examples --silent
=> Fixed object matcher

packages/jest-mock/src/__tests__/jest-mock-test.js, packages/jest-mock/src/index.js
Binding and mocking methods in a specific order causes a `Maximum call stack size exceeded` error when the mocked method is called. 
**Summary**
`_createMockFunction` normally detects functions that have already been mocked by checking if they are named `"mockConstructor"`. However, calling `bind` on the mocked function changes the function name and causes the check to fail.
`_createMockFunction` already has code to strip out the `"bound "` prefix, but the check to look for `"mockConstructor"` was happening too early. This PR moves delays checking for `"mockConstructor"` until after `"bound "` has already been stripped out.
Repro steps:
1. Mock an anonymous function (fn is now named `"mockConstructor"`)
2. Bind the mocked function (fn is now named name `"bound mockConstructor"`)
3. Mock …
=> Fix issue mocking bound method

packages/jest-mock/src/__tests__/jest-mock-test.js, packages/jest-runtime/src/ScriptTransformer.js, packages/jest-runtime/src/__tests__/ScriptTransformer-test.js
**Summary**
Let use know when `transform` function doesn't return required type of content.
Resolves: https://github.com/facebook/jest/issues/3779
**Test plan**
Added necessary tests to the suite itself.
=> Provide better error checking for transformed content

packages/jest-jasmine2/src/jest-expect.js
**Summary**
`jasmine.matchersUtil` is not included on this fork of jasmine, so `undefined` is being passed to the custom matcher. We make sure we remove that dead reference and we add a comment on top, so if people looks why they are not getting the matching utilities passed, they get a hint on how to proceed and don't get confused.
=> Remove dead reference

packages/jest-haste-map/src/worker.js
**Summary**
Internally at Facebook, this created tons of issues with flaky caches.
**Test plan**
When passing a broken hasteImpl that throws, it will now crash the workers and refuse to do its work.
=> Hard-fail if hasteImpl is throwing an error during initialization.

packages/jest-cli/src/TestWorker.js, packages/jest-cli/src/reporters/CoverageWorker.js, packages/jest-haste-map/src/__tests__/index-test.js, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/worker.js, types/TestResult.js
It is not proper to put all the errors in the same basket, because some types of errors, such as `SyntaxError`, should definitely not be let ignored, and should instead crash the program right away.
What I propose is that we reduce the errors we handle here to a very specific and reduced set, and that we progressively add more codes or kind of errors if really necessary.
This follows up #3812.
**Test plan**
Automated tests.
=> jest-haste-map: only file IO errors should be silently ignored

packages/jest-runtime/src/cli/index.js
**Summary**
Without this change `console.error` will only log the `message` property and the stack will look like this:
```
Error: Cannot find module '../build/Release/pty.node' from 'pty.js'
```
Makes it pretty impossible to debug where the errors are coming from.
**Test plan**
Made the change locally and it worked fine.
=> Log stack when reporting errors in jest-runtime

website/i18n/en.json, website/src/jest/css/jest.css
This properly breaks lines so they render properly on the help.html page. CSS was also included to add horizontal space between these blocks when viewed from a browser on desktop.
Fixes https://github.com/facebook/jest/issues/3852
=> Fixes bad text block on /en/help.html

website/core/JestHelp.js
The theeColumn layout is not supported by Jest's current CSS. Switching to four column allows us to get the intended layout.
=> [Help Page] Change to four column layout

packages/jest-mock/src/__tests__/jest-mock-test.js, packages/jest-mock/src/index.js
**Summary**
Simplified the logic behind `mockReturnValueOnce` and `mockReturnValue` so that `isReturnValueLastSet` flag is only set by `mockReturnValue`.
Fixes https://github.com/facebook/jest/issues/3826
**Test plan**
Added test for that.
=> Fix regression in mockReturnValueOnce

integration_tests/__tests__/timer-useRealTimers-test.js, integration_tests/timer-useRealTimers/__tests__/use_real_timers.test.js, integration_tests/timer-useRealTimers/package.json, packages/jest-jasmine2/src/index.js
**Summary**
We unnecessarily call `useFakeTimers` on every `beforeEach`, even though it's only needed when combined with `resetMocks`.
Fixes https://github.com/facebook/jest/issues/3815
**Test plan**
Added an integration test.
=> Make useRealTimers play well with timers: fake

docs/en/ExpectAPI.md
**Summary**
Hey was just learning about jest (great btw, late to the part) but noticed these small things. I might be wrong but looks like small grammar or extra , :) Sorry If I miss understood 
**Test plan**
=> Small fixes to toHaveProperty docs

integration_tests/__tests__/iterator-to-null-test.js, packages/jest-jasmine2/package.json, packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/jasmine/Env.js, packages/jest-jasmine2/src/queueRunner.js
this PR fixes two problems:
1. Fixes the broken promise chain, that caused Jest process to stall with all errors swallowed (node <6)
2. Require Jasmine from the outer VM scope rather then inner, because modifying global object can break the runner (see https://github.com/facebook/jest/issues/3879) 
Taking jasmine out seems risky, but all tests seem to be passing
=> remove `p-map` and fix jasmine promise chain

integration_tests/__tests__/__snapshots__/console_log_output_when_run_in_band.test.js.snap, integration_tests/__tests__/console_log_output_when_run_in_band.test.js, packages/jest-cli/src/reporters/DefaultReporter.js
this is a split from https://github.com/facebook/jest/pull/3882
thanks @valerybugakov for finding this.
Console mesasges weren't being printed because we debounce the output for concurrent reporter, and some of the messages didn't have enough time to print before the process exits
=> fix missing console.log messages

website/core/Doc.js
**Summary**
Currently, we are reading `locale` information from `language` prop in Docs. When we don't pass the prop it treats as empty resulting in `404`. I defaulted language to `en` when prop is not passed. Addresses #3900 
**Test plan**
=> Adding default locale as `en`. Addresses #3900

website/core/JestHelp.js, website/src/jest/css/jest.css
At some point, the CSS file lost these threeColumn styles. This restores the threeColumn layout used by GridBlock, specifically in `core/JestHelp.js`'s use case.
=> [Website] Fix help layout grid

docs/en/Troubleshooting.md
- The troubleshooting documentation, specifically for when tests
are executing very slowly on Continuous Integration Servers, was
updated to reflect an alternative to runInBand which involves setting
the max worker pool to a value of 4.
- There is nothing magical around the value of 4 and it largely depends
on the number of tests running(A larger number of tests can have issues
with a larger worker pool).  The reason a value of 4 is used in the
example is to add color to what other developers can start with and
adjust accordingly to improve their CI feedback loop.
Related #3855
Motivation:  There are other developers that may come across this and it would be super helpful to see this in the troubleshooting documentation.
=> Update troubleshooting documentation

integration_tests/__tests__/__snapshots__/failures.test.js.snap, packages/jest-matchers/src/extract_expected_assertions_errors.js
**Summary**
Only removed the `only` word from `expected n assertions but only received m`. Indeed in case of more assertions than expected and since the only performed comparison is `assertionCalls !== expectedAssertionsNumber`, it doesn't seem to make any sense to let the word stand here. It might be sometimes a bit frustrating :)
=> Remove 'only' from '...to be called but only received...' messages

.vscode/settings.json, package.json, scripts/build.js, yarn.lock
**Summary**
It kind of always pissed me a bit that the build script outputs fixed width strings.
How about changing that?
| before | after |
|---|---|
| <img width="359" alt="screen shot 2017-06-23 at 22 48 58" src="https://user-images.githubusercontent.com/5106466/27500039-d9ba3c28-5866-11e7-80c7-e76332c49257.png"> | <img width="341" alt="screen shot 2017-06-23 at 22 47 43" src="https://user-images.githubusercontent.com/5106466/27500038-d9b85836-5866-11e7-8b42-af3901e68e2c.png"> |
**Test plan**
Tested on iTerm2 and Terminal (mac)
=> Make build script printing small-terminals-friendly

docs/en/SnapshotTesting.md
The links to the tests were written as something-test.js, but it need to be something.test.js
**Summary**
Well, obviously a documentation is not really helpful if the links it has inside are broken. I wanted the documentation to be fully working again.
**Test plan**
https://facebook.github.io/jest/docs/snapshot-testing.html
Just click the first link inside the document (where it says `example test`). 
It will lead to a GitHub 404 page.
=> docs: Update broken test links

docs/en/JestObjectAPI.md
**Summary**
Explicitly document `doMock` and `dontMock` methods. I also reordered `unmock` to be below `mock`.
**Test plan**
To provide a better understanding of hoisting with an example of when you might want to opt out. This should address #2649.
I moved `unmock` below `mock` because it makes sense that they are together. First I thought that the list was alphabetical, but it's not really.
---
This is a WIP because the example code I provided doesn't work. Sorry for submitting a WIP PR, I really want to clear this up for others, but first I need to understand it myself. Was I on the right track? Can `doMock` and `dontMock` be used for per-test mocking?
=> Document doMock and dontMock

packages/jest-haste-map/package.json, packages/jest-haste-map/src/index.js, packages/jest-haste-map/yarn.lock
This is to fix regressions with the NodeWatcher on macOS.
More info here: https://github.com/amasad/sane/pull/97
**Summary**
See #3902. Unsure why there are so many changes to the lockfile... EDIT: Seems like the dependency tree of fsevents is huge.
**Test plan**
See #3902
=> Upgrade sane and use FSEventsWatcher on Darwin

packages/jest-util/src/__tests__/fake_timers.test.js, packages/jest-util/src/fake_timers.js
**Summary**
Fixes https://github.com/facebook/jest/issues/3000
**Test plan**
Added a test from repro.
=> Make sure runAllTimers also clears all ticks

packages/jest-diff/src/index.js, packages/jest-matcher-utils/src/index.js
**Summary**
* Add `ReactTestComponent` to `jest-matcher-utils`
* Call the most frequently used plugins first.
Please confirm that `AsymmetricMatcher` is for `jest-diff` and `jest-matcher-utils` but not `jest-snapshot`
**Test plan**
Jest
=> Call consistent pretty-format plugins within Jest

packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js
When two platform variants of a single module ID change at the same time (ex. often happening after a far rebase), jest was loosing one of them, depending on the ordering of the change events. This is because it doesn't care about platform variants and deletes the whole module metadata every time. This is probably here for historical reasons, from before the introduction of platform extensions, and wasn't unit-tested.
This changeset adds a test and the corresponding fix for this behaviour. I wrote the test first and could see it failing if the correct fix is not added as well.
=> jest-haste-map: add test+fix for broken platform module support

packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js
**Summary**
Adjusted the order so that the options mappings are checked first and then the preset mappings are checked.
The preset mappings can be overridden by the options mappings.
Fixes #3565 
**Test plan**
Modified existing test and added a new test.
Tests passed after making the necessary code changes. TDD FTW ;) !
=> Fix options.moduleNameMapper override order with preset (#3565)

packages/jest-matchers/src/__tests__/__snapshots__/spy_matchers.test.js.snap, packages/jest-matchers/src/__tests__/spy_matchers.test.js, packages/jest-matchers/src/matchers.js, packages/jest-matchers/src/spy_matchers.js, packages/jest-matchers/src/utils.js
Fixes #3574 
FIxes #3619
**Summary**
While working on custom matchers to solve #3574, I found out that the cause for
not seeing this issue in `expect().toEqual()` comes from the fact that this
matcher passes the `iterableEquality` to the `equals()` function.
When I added this to the equal calls for our spy matchers as well, Immutable.js
types were properly suppored.
I'm considering this is a bug since the `toBeCalledWith()` matchers should
behave the same as the `equals()` matcher.
**Test plan**
I added a unit test that uses the already included `Immutable.js` library.
=> Use iterableEquality in spy matchers

packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js, packages/jest-haste-map/src/crawlers/watchman.js, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/lib/__tests__/normalize_path_sep.test.js, packages/jest-haste-map/src/lib/normalize_path_sep.js
See the inline comment. New versions of Watchman on Window are now returning paths using forward slashes, but consumers of `jest-haste-map` use to work and assume backslashes would be used (because they rely on `path.sep`, that is backslash on win32, along the other path functions).
This changeset make it so we `path.normalize` the paths we read from watchman. On POSIX systems this should not make any difference, but on Window this will have the effect of replacing forward slashes by the usual backslashes.
=> jest-haste-map: watchman crawler: normalize paths

docs/en/GettingStarted.md
**Summary**
The TypeScript example configuration will not find any tests with the .jsx extension.
**Test plan**
N/A. Documentation change only.
=> Add jsx as valid extension in TypeScript example

scripts/build.js
often when we work on a new package and switch between branches, git leaves a lot of empty directories in the directory tree.
Browser build will always crash on empty directories, this condition will make it ignore empty dirs and only build the ones that have `package.json`
=> don't build ghost packages

packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
fixes https://github.com/facebook/jest/issues/3928
=> mockImplemetation() resets the `returnValue` flag, but not the actual value

.eslintignore, .eslintrc.js
=> lint .eslintrc.js

yarn.lock
**Summary**
lru cache had some crazy perf improvements in the last release (isaacs/node-lru-cache#112).
On my (somewhat old) machine it cut down the testrun time quite a lot.
`Time:        171.296s, estimated 195s` (reproducible with `--no-cache` as well (3 runs, avg 180 on master, 172 on this branch))
**Test plan**
All tests should pass
=> Upgrade lru-cache

packages/jest-cli/src/reporters/__tests__/default_reporter.test.js, packages/jest-cli/src/reporters/default_reporter.js, packages/jest-resolve/yarn.lock, types/TestRunner.js
=> Avoid writing to stdout in default reporter if --json is enabled. Fixes #3941

packages/jest-cli/src/reporters/__tests__/default_reporter.test.js, packages/jest-cli/src/reporters/default_reporter.js, packages/jest-resolve/yarn.lock, types/TestRunner.js
This PR is related to another two changes deployed this morning: #3945 and #3946. These two had to be rolled back because they were causing issues in CI, however they were working locally.
The cause of the breakage in CI is due to the fact that the `is-ci` module was not being mocked. Since CI sessions are considered non-interactive, the reporter was not outputting anything and the test failed. After adding a mock to the module (`jest.mock('is-ci', () => false)`) tests are passing now.
Code for the reporter itself has not been changed when comparing it with the two earlier PRs, so the release done in-between (`jest@20.1-alpha.3`) is safe in that sense.
=> Check whether we should output to stdout or stderr

packages/pretty-format/src/__tests__/pretty_format.test.js, packages/pretty-format/src/index.js
**Summary**
Problem:
* `printPlugin` “hoists” the `boundPrint` and `boundIndent` declarations and therefore initializes the functions **whether or not** a plugin matches the value.
* `prettyFormat` calls `createIndent` if any plugins exist **instead of** if some plugin **matches** the value. Because plugins always exist in Jest, the conditional logic to avoid creating indentation for basic values doesn’t save any time.
Solution:
* Factor out a `findPlugin` function.
* Factor out `if` statement to call `printPlugin` only if a plugin matches the value.
* Call `createIndent` for arg in `printPlugin` and `printComplexValue` function calls.
Your review is especially wanted about the decision to throw an error if a plugin returns a non-string value. Am happy to revert that change if it’s a step …
=> Avoid unnecessary function declarations and call in pretty-format

integration_tests/__tests__/__snapshots__/show_config.test.js.snap, packages/jest-cli/src/lib/__tests__/is_valid_path.test.js, packages/jest-cli/src/lib/is_valid_path.js, packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js
**Summary**
Fixes #3955.
**Test plan**
Added a test, update existing one.
=> Set coverageDirectory during normalize phase

packages/jest-matchers/src/__tests__/extend.test.js, packages/jest-matchers/src/index.js, packages/jest-matchers/src/matchers.js, types/Matchers.js
**Summary**
https://github.com/facebook/jest/issues/3921
* Update `getMessage` function
* Found three cases in the code base where still a `string` was being returned, instead of a `function`
* Updated the type
Checked the documentation, which already says:
> provides a function with no arguments that returns an error message in case of failure.
**Test plan**
All tests pass.
Did not add any new test. Perhaps a test should be added for when we still pass a `string` ? Basically, it should throw an error: `VM189:1 Uncaught TypeError: message is not a function`
Additionally we could `try/catch` and default to `No message was specified for this matcher.` if a wrong type is supplied for `message`.
=> Force message in matchers to always be a function

packages/jest-haste-map/src/__tests__/__snapshots__/index.test.js.snap, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/module_map.js, types/HasteMap.js
**Summary**
Right now, if a module is duplicated, we remove it from the module map, so that when we try to resolve it later, it doesn't return one or the other randomly, that would be incorrect, but instead nothing.
I realised this approach is better then returning a random module, but is still incorrect, because the callsite (resolution algorithm) could then try to resolve the module name as a Node.js package, and find some other module. This is just as random, and incorrect.
I believe the correct approach in case of duplicate modules for a single name is to prevent any further resolution by throwing an exception with sufficient metadata for the callsite, or the user, to make a decision. This changeset implements this correct behavior.
**Test plan**
`yarn jest …
=> jest-haste-map: throw when trying to get a duplicated module

packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js
Updates the `_isNodeModules` function so that nested `node_modules` subdirectories of whitelisted npm packages are not whitelisted. This is causing problems because arbitrary npm packages that aren't explicitly whitelisted can cause Haste map collisions.
Test plan: Added unit tests that were failing before and ensure that they are passing now in addition to older unit tests.
=> Make providesModuleNodeModules ignore nested node_modules directories

packages/jest-changed-files/src/git.js, packages/jest-changed-files/src/hg.js, packages/jest-changed-files/src/index.js, packages/jest-cli/src/__tests__/watch.test.js, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/get_changed_files_promise.js, packages/jest-cli/src/lib/get_test_path_pattern.js, packages/jest-cli/src/run_jest.js, packages/jest-cli/src/search_source.js, packages/jest-cli/src/watch.js, types/ChangedFiles.js
should solve the performance regression in www.
I'm not a fan of passing this promise all the way down, but there isn't really a nice way of doing this yet
cc @rogeliog can you look at the watch stuff? i wanna make sure i didn't break anything accidentally
=> changed files eager loading

packages/jest-haste-map/src/index.js, packages/pretty-format/src/index.js
**Summary**
There are some inconsistencies in names of complex types for various options:
* specific case for empty list is `Arguments []` but general case with `min: true` is `[]`
* specific case for empty array is `Array []` and so on, but general case with `min: true` is `[]`
* when `hitMaxDepth` for typed array is `[Array]` instead of `[Uint32Array]` and so on
* when `hitMaxDepth` for constructed object is `[Object]` instead of `'[' + (val.constructor ? val.constructor.name : 'Object') + ']'` and I’m not sure tests cover this case
If y’all are willing to approve breaking changes to edge cases, I can submit an additional PR.
Whether or not, this PR applies advice from Kent Beck: move similar elements closer together.
* Move empty arguments and array from `printBasicValue` to …
=> Refactor names and delimiters of complex values in pretty-format

docs/en/ExpectAPI.md
**Summary**
Docs typo
**Test plan**
-
=> Docs: fix wrong object name

docs/en/ExpectAPI.md
**Summary**
Missing parentheses in docs, compared to other parts of the docs.
Added them for consistency.
**Test plan**
=> Docs: missing parentheses

docs/en/MockFunctionAPI.md
**Summary**
* Un-deprecates `mockReturnValue` (fixes #3961) and describes its usage in terms of changing the 
return value of an existing mock. This was marked as deprecated for Jest 0.9.0 over a year ago, but I wasn't able to find any other mention of it. If `mockReturnValue` and `mockReturnValueOnce` are actually deprecated, I can switch the documentation to point to `mockImplementation` and `mockImplementationOnce` as replacements since they're closer analogues.
* Document `mockReturnValueOnce` with usage example instead of implementation
**Test plan**
=> Update mockReturnValue documentation

docs/en/ExpectAPI.md
=> Add that toMatchObject can match arrays

packages/jest-haste-map/src/crawlers/watchman.js
Watchman returns `/` separated paths, but `jest-haste-map` uses `path.sep` which on windows equals `\`.
**Summary**
Addresses the issue finding tests on Windows with the latest watchman and Jest.
As a follow-up to https://github.com/facebook/jest/pull/3887
=> Fix Watchman on windows

karma.conf.js
All `karma-*` plugins are autoloaded (essentially same as webpack-contrib/karma-webpack#103)
**Summary**
Without this change, one can't do `yarn test-ci-es5-build-in-browser -- --browsers PhantomJS`
**Test plan**
Tests should still pass.
/cc @skovhus
=> Remove plugins entry from karma tests

integration_tests/__tests__/__snapshots__/multi_project_runner.test.js.snap, integration_tests/__tests__/multi_project_runner.test.js, packages/jest-cli/src/cli/index.js, packages/jest-config/src/index.js
right now there's a bug in multi runner.
it can run `jest --projects p1 p2`
but can't run `jest --config c.json` with `c.json` having `{projects: ['p1', 'p2']}`
I added a test for MPR and fixed the config bug
=> multi runner tests and bugfixes

.vscode/settings.json
**Summary**
Updates VSCode config to enable ESLint support. Makes working on different prettier configs easier (e.g. editing a file in `scripts` without the option enabled would result in adding a trailing comma to function params).
Fixes #4031.
**Test plan**
works for me
=> Enable prettier eslint integration for vscode

integration_tests/__tests__/stack_trace_no_captureStackTrace.test.js, integration_tests/stack_trace_no_captureStackTrace/__tests__/runtime_error.test.js, integration_tests/stack_trace_no_captureStackTrace/package.json, packages/jest-matchers/src/index.js
**Summary**
Ref #4027
This is a poor-man's version, but it works OK. Not sure we really need to fix it more?
Could put the logic to remove `JestAssertionError` along with the rest of the stack trace cleanup and avoid `Error.captureStackTrace` all together?
/cc @skovhus 
**Test plan**
Tests running in browsers should show assertion errors.
=> Wrap `Error.captureStackTrace` in a try

integration_tests/__tests__/only_changed.test.js, packages/jest-cli/src/cli/args.js, packages/jest-config/src/normalize.js, packages/jest-config/src/valid_config.js, types/Argv.js
depends on: https://github.com/facebook/jest/pull/4012
the code is in the last commit
=> jest --all

packages/jest-haste-map/src/__tests__/index.test.js
This adds a test to keep track of the broken behavior for when `ignorePattern` is changed. Normally, the new ignore pattern should be applied, that means new files may now have to be included, and that others may now have to be ignored. However this is not properly handled at the moment, the `ignorePattern` is ignored when there's already a cache.
By adding this test now, we can simply switch the "expect" line when this is fixed.
**Test plan**
yarn run jest packages/jest-haste-map/src/__tests__/index.test.js
=> jest-haste-map: add test case for broken handling of ignore pattern

packages/jest-haste-map/src/__tests__/index.test.js
For some reason, `graceful-fs` was mocked from within `beforeEach`. In this changeset I propose we move it to a usual `jest.mock`, that seems more the usual practice. That also ensures that no function can escape the mocking, ie. that no code starts calling `fs.stat` or other functions unexpectedly. In the original version, these functions do not seem mocked at all.
**Test plan**
I ran `yarn run jest packages/jest-haste-map/src/__tests__/index.test.js`, that passed.
=> jest-haste-map: mock 'fs' with more idiomatic jest.mock()

docs/en/JestObjectAPI.md, packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js, packages/jest-runtime/src/index.js
**Summary**
A new `.spyOn` method was added in Jest 19.0 to allow spying on methods without skipping their original behavior. However, Jest lacked a method to clean all the spies at once, as opposed as other existing APIs for cleaning or resetting mocks. Further discussion can be found on #3580.
Now, all spies can be cleaned at once by calling `jest.restoreAllMocks`, which naming is consistent with other group resets.
**Test plan**
New tests were added, so running the whole suit of tests should be enough. This would also include running `flow` to check typing errors. If you can think about something else, let me know :)
=> Add "restoreAllMocks" to the API. Closes #3580

packages/jest-cli/src/test_runner.js
Custom reporter experience is not great right now and it's pretty hard to customize.
Right now even if we pass this to config:
```js
{reporters: ['custom1.js', 'default', 'custom2.js']}
```
the order will be:
- default reporters
- custom reporters
- coverage/notify reporters
and that makes it hard to customize reporters that interact with coverage data. (coverage data is never available in custom reporters, because `CoverageReporter` is always last in the queue).
This requires a better fix (https://github.com/facebook/jest/issues/4052), but for now i want to move custom reporters to the very end, so they're run after all default reporters are done
=> Setup custom reporters after default reporters

integration_tests/__tests__/custom_reporters.test.js, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/reporter_dispatcher.js, packages/jest-cli/src/test_runner.js, types/TestRunner.js
there was a broken promise chain (again 😔) and all errors throw in custom reporter code would make `jest` hang forever.
Also the way we call reporter methods was inconsistent (`onRunComplete` was async, and all others were sync)
=> custom reporters error handling

packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js
I plan to revert `ignorePattern` to only being a strict `RegExp`, after removing the function use case from React Native and Metro bundler. The reason for getting rid of the function use case is that `ignorePattern` should be part of the cache key, and a function is not analysable at runtime. If it can only be a `RegExp`, then we can use `ignorePattern.toString()` as part of the cache key.
The reason it needs to be part of the cache key is because the cache needs to be discarded—or at least reevaluated—when the ignore pattern changes. Otherwise, we can be missing some new modules that should be included, or the reverse, we can be including modules that should now be ignored. I have observed considerable trouble caused by this issue. For example, in React Native, people would reload a …
=> jest-haste-map: deprecate functional ignorePattern and use it in cache key

integration_tests/__tests__/only_changed.test.js, packages/jest-config/src/normalize.js
it seems like right now when you run `jest -o my_test_file.test.js`, jest will ignore the test pattern and will still try to run tests related to changed files.
that was my bad, i think there was some nested condition in TestSelectionConfig that i killed
=> --onlyChanged + testPathPattern

integration_tests/__tests__/use_stderr.test.js, packages/jest-cli/src/cli/index.js
seems like this one was a noop for a long time (www used it, but it had a custom --printUserMessagesToStderr flag and internal runner didn't use any printing parts of OSS project, which is not passible today with MPR changes)
=> --useStderr

integration_tests/__tests__/version.test.js
seems like `jest --version` right now prints the version and proceeds to running tests (i possibly broke it with multi runner diffs this month 😔)
it's fixed in https://github.com/facebook/jest/pull/4067
=> `--version` integration test

integration_tests/__tests__/__snapshots__/show_config.test.js.snap, integration_tests/__tests__/only_changed.test.js, packages/jest-changed-files/src/git.js, packages/jest-changed-files/src/hg.js, packages/jest-cli/src/cli/args.js, packages/jest-cli/src/get_changed_files_promise.js, packages/jest-config/src/defaults.js, packages/jest-config/src/index.js, packages/jest-config/src/normalize.js, packages/jest-config/src/valid_config.js, types/Argv.js, types/Config.js
i don't know why we chose to do it this way in WWW, but since we're doing it, we might want to implement the same for `git`
=> --changedFilesWithAncestor

packages/pretty-format/src/index.js, types/PrettyFormat.js
**Summary**
Benefits of distinguishing config properties which **don’t change** (depend only on options and defaults) from arguments which **do change** during recursive descent through data structures:
* **concise clear** signature for core functions
* **correct complete consistent** API for plugins (but one step at a time :)
Converting from options to config in an even more functional lazy evaluation pattern solves a recent accidental performance regression (always iterating theme colors, even for top-level basic values).
Removed a readbump in `printList`, `printMap`, `printObject`, `printSet`: logic for final comma had been combined with edge spacing and indent instead of in parallel with logic for non-final comma.
Make yourself a cup of coffee or tea before you review this diff. …
=> Replace unchanging args with one config arg within pretty-format

packages/jest-haste-map/src/lib/__tests__/extract_requires.test.js, packages/jest-haste-map/src/lib/extract_requires.js
extract_requires shouldn't be looking at dependencies only used for flow types.
**Test plan**
Unit tests
=> Ignore import type for extract_requires

integration_tests/__tests__/__snapshots__/show_config.test.js.snap, integration_tests/__tests__/debug.test.js, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/lib/__tests__/__snapshots__/log_debug_messages.test.js.snap, packages/jest-cli/src/lib/__tests__/log_debug_messages.test.js, packages/jest-cli/src/lib/log_debug_messages.js
when running `jest --showConfig` with MPR we only show the first config.
this PR makes it log all project configs
=> --showConfig to show all project configs

packages/jest-cli/src/__tests__/watch_filename_pattern_mode.test.js, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/lib/update_global_config.js
We really need to have this: https://github.com/facebook/jest/issues/4022
right now watch mode is almost untested and we break it too often with the build being all green 😞
=> fix watch mode

packages/jest-matcher-utils/src/__tests__/index.test.js, packages/jest-matchers/src/__tests__/__snapshots__/matchers.test.js.snap, packages/jest-matchers/src/__tests__/__snapshots__/spy_matchers.test.js.snap, packages/pretty-format/src/__tests__/pretty_format.test.js, packages/pretty-format/src/index.js
**Summary**
Give the `return` statements in `printComplexValue` a parallel structure.
* For `min: true` option, the previous formatted value `Array []` instead of `[]` for empty array (or arguments) was inconsistent with `{}` for empty object. The change doesn’t affect snapshots directly, but it does affect format of Expected/Received values in Jest output when a test fails.
* When `hitMaxDepth` is true, the change to return name of typed array or constructed object instead of generic `[Array]` or `[Object]` doesn’t affect snapshots because default `maxDepth` is `Infinity` but does affect Jest output when a test fails, because `maxDepth = 10` is default.
**Test plan**
Updated tests for `min: true` option in `jest-matchers` and `jest-matcher-utils`
=> Fix inconsistent name of complex values in pretty-format

packages/pretty-format/src/__tests__/pretty_format.test.js
**Summary**
Here’s the residue that I doubt we’ll be able to cover:
* const getSymbols = Object.getOwnPropertySymbols || **(obj => [])**;
* `if (toStringed === '[object Function]' || toStringed === '[object GeneratorFunction]')` because preceded by `typeOf === 'function'`
* `if (toStringed === '[object Symbol]')` because preceded by `typeOf === 'symbol'`
* `if (val instanceof Error)` because preceded by `if (toStringed === '[object Error]')`
**Test plan**
Tests that increase coverage:
* anonymous callback function
* negative zero
Tests that increase peace of mind:
* named generator function (version 4 has basic functionality according to node.green)
* negative number
* zero
=> Add a few tests to increase coverage in pretty-format

packages/jest-haste-map/src/lib/__tests__/extract_requires.test.js, packages/jest-haste-map/src/lib/extract_requires.js
Additional tests for https://github.com/facebook/jest/pull/4079
=> Add tests for extract_requires on export types

integration_tests/browser-support/browser-test.js, packages/pretty-format/package.json, packages/pretty-format/src/__tests__/immutable.test.js, packages/pretty-format/src/plugins/asymmetric_matcher.js, packages/pretty-format/src/plugins/convert_ansi.js, packages/pretty-format/src/plugins/html_element.js, packages/pretty-format/src/plugins/immutable_list.js, packages/pretty-format/src/plugins/immutable_map.js, packages/pretty-format/src/plugins/immutable_ordered_map.js, packages/pretty-format/src/plugins/immutable_ordered_set.js, packages/pretty-format/src/plugins/immutable_plugins.js, packages/pretty-format/src/plugins/immutable_record.js, packages/pretty-format/src/plugins/immutable_set.js, packages/pretty-format/src/plugins/immutable_stack.js, packages/pretty-format/src/plugins/lib/escape_html.js, packages/pretty-format/src/plugins/lib/print_immutable.js, packages/pretty-format/src/plugins/react_element.js, packages/pretty-format/src/plugins/react_test_component.js
**Summary**
Fixes https://github.com/facebook/jest/issues/4002
**Test plan**
I've added a simple integration tests.
=> Add es5 build of pretty-format

packages/pretty-format/src/index.js
**Summary**
Rewrite some small bumps that have distracted me from understanding the big picture:
* Restructure the minority of exceptions to [no-else-return](http://eslint.org/docs/rules/no-else-return) rule (and `else if return` structure) to follow same pattern as the majority of conditional returns. Thinking forward to future code changes, the simple `if return` structure provides a **minimal diff** like trailing comma.
* Replace `key` with `name` in `printMap` to be parallel with `printObject`
* Replace `entries` with `values` iterator in `printSet`
* Replace `refs.indexOf(val) > -1` with `refs.indexOf(val) !== -1` in `printComplexValue`
* Move `refs.slice()` after `if return` in `printComplexValue`
To help future readers understand the recently refactored helper functions:
* Replace …
=> Rewrite some read bumps in pretty-format

.eslintrc.js
**Summary**
We have 63 warnings from `no-console` rule and since this is a command-line tool, we'll likely have more usage for `console.log`. Disabling the rule to cut the noise.
**Test plan**
Run `yarn lint` and make sure you see no errors nor warnings.
=> Update: disable `no-console` lint rule

integration_tests/__tests__/__snapshots__/console.test.js.snap, integration_tests/utils.js, packages/jest-cli/src/reporters/summary_reporter.js
this is probably not the best solution. Because of the way we run test with `arc` in www, summary reporter prints a very long message at the end
```
ran all tests matching <VERY_LONG_STRING_WITH_ALL_FILES_CHANGED_IN_THIS_DIFF>
```
=> Don't print test summary in --silent

packages/jest-runtime/package.json, packages/jest-runtime/src/__tests__/script_transformer.test.js, packages/jest-runtime/src/script_transformer.js
This change tries to address what may be a cause for #1874, where I posted some details on the approach. By doing atomic writes we ensure there's no cache file ending up being a mix of two transformed code files, and we limit the concurrency issues of having a file read and written at the same time. A prior PR #3561 tries to address the problem using a lock, but locks bring additional complexity that this change tries to avoid (ex. deadlocks).
This change also adds a checksum, because there can be other processes still writing non-atomically to cache files. Additional, not all filesystems may support atomic renames (what `atomic-write-file` relies on).
This change incurs a slight performance cost that is the additional I/O call to rename the files. However I believe it is less costly than …
=> jest-runtime: atomic cache write, and check validity of data

packages/pretty-format/src/__tests__/immutable.test.js, packages/pretty-format/src/plugins/lib/print_immutable.js
**Summary**
Explicitly specify expected result to prevent regression during work on `pretty-format` plugins :)
@cpenarrieta can you please confirm? Thank you!
```js
Immutable.OrderedSet [
]
// and so on for {min: false} option
```
**Test plan**
Added 8 tests
=> Test empty Immutable collections with {min: false} option

.eslintrc.js, packages/jest-diff/src/__tests__/diff.test.js, packages/jest-docblock/src/__tests__/index.test.js, packages/jest-editor-support/src/__tests__/parsers/babylon_parser.test.js, packages/jest-editor-support/src/__tests__/project_workspace.test.js, packages/jest-editor-support/src/__tests__/runner.test.js, packages/jest-editor-support/src/__tests__/settings.test.js, packages/jest-editor-support/src/__tests__/test_reconciler.test.js
=> flowtype packages tests #1

packages/jest-cli/src/__tests__/generate_empty_coverage.test.js, packages/jest-cli/src/__tests__/globals.test.js, packages/jest-cli/src/lib/__tests__/format_test_name_by_pattern.test.js, packages/jest-cli/src/lib/__tests__/highlight.test.js, packages/jest-cli/src/lib/__tests__/is_valid_path.test.js, test_utils.js, types/Config.js
a lot of times we test our modules using data structures incompatible with what the module is expecting.
for example we often pass `{rootDir: 'test'}` into a function that expects full `globalConfig` object with all it's values set.
most of the time it is ok, but
1. We can't flowtype those tests and with that we lose a lot of signal that can prevent bugs.
2. this is not a real world scenario, and potentially it can result in a green test that would never pass in the real world
this set of test utils provides two methods for generating a default project/global config with default values that can be overwritten
=> basic test utilities

package.json, yarn.lock
i want to try this before https://github.com/facebook/jest/pull/4145
it seems like master resolves to an older version of chalk, which did not have CI support
=> supprots-color@4.2.1

integration_tests/__tests__/supports_color_debug.test.js, integration_tests/supports_color.js
this is how i found the failure in Circle, but travis doesn't provide an ssh access.
I want to land it and see what exactly makes our tests disable colors
=> test to debug travis failure in master

packages/jest-diff/src/__tests__/__snapshots__/diff.test.js.snap, packages/jest-diff/src/__tests__/diff.test.js, packages/jest-diff/src/diff_strings.js
**Summary**
Fixes #4147. This will be useful for libraries like https://github.com/thymikee/snapshot-diff.
**Test plan**
Added several test cases (with snapshots) in `diff.test.js`.
=> Add `contextLines` option to jest-diff

.travis.yml
this is some CI madness this week.
looks like Travis changed the way we run builds today and now the default preinstalled version of yarn is `0.17`
=> install yarn on travis

docs/en/Webpack.md
The Webpack config example on the docs uses `resolve.modulesDirectories` and `resolve.root`, which were merged into `resolve.modules` in Webpack 2. I updated that snippet to avoid confusion.  
From the [Webpack docs](https://webpack.js.org/guides/migrating/#resolve-root-resolve-fallback-resolve-modulesdirectories) for migrating from v1 to v2:
> ### `resolve.root`, `resolve.fallback`, `resolve.modulesDirectories`
>
> These options were replaced by a single option `resolve.modules`.
=> Updated Webpack config example on docs

packages/pretty-format/src/__tests__/asymmetric_matcher.test.js, packages/pretty-format/src/__tests__/pretty_format.test.js, packages/pretty-format/src/plugins/asymmetric_matcher.js
**Summary**
Please pace yourself, my friendly reviewer :)
* **Breaking change** for edge case: `++depth > config.maxDepth` like ordinary Array or Object
* Replace `opts.spacing === SPACE` with `config.min`
**Test plan**
Added 2 fail-first tests for new result: **maxDepth** option
Additional tests explicitly specify existing correct results:
* stringMatching(regexp) {escapeRegex: **false**}
* stringMatching(regexp) {escapeRegex: **true**}
* **indent** option
=> Replace print with serialize in AsymmetricMatcher plugin

packages/pretty-format/src/__tests__/react.test.js, packages/pretty-format/src/plugins/lib/markup.js, packages/pretty-format/src/plugins/react_element.js, packages/pretty-format/src/plugins/react_test_component.js
**Summary**
Enforce consistency, reduce code. Like the TV advert: looks pretty, less filling :)
We will probably be able to factor out common code in HTMLElement too.
Analogy to react-redux as you review this diff:
* React plugins like **container** components?
* markup functions like **presentation** components?
**Test plan**
Added 2 tests to prevent regression related to test object for subset match, especially because of the incorrect Flow error.
=> Factor out common code for markup in React plugins

packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
**Summary**
As reported in https://github.com/facebook/jest/issues/3997, Jest mocks currently do not have the same arity as their underlying functions. This PR attempts to fix that.
**Test plan**
Run unit tests locally.
Test in a local project using tests provided in issue https://github.com/facebook/jest/issues/3997
Write unit test in jest-mock to ensure arity is set properly
=> Make sure function mocks match original arity

packages/pretty-format/src/__tests__/asymmetric_matcher.test.js, packages/pretty-format/src/collections.js, packages/pretty-format/src/index.js, packages/pretty-format/src/plugins/asymmetric_matcher.js, packages/pretty-format/src/plugins/lib/markup.js, packages/pretty-format/src/plugins/react_element.js, packages/pretty-format/src/plugins/react_test_component.js, types/PrettyFormat.js
**Summary**
From lemon to lemonade:
1. confused assumption:
* that `maxDepth` option didn’t work for asymmetric matchers
* didn’t read carefully to see that they delegate array or object to core which handles depth
2. embarrassing error in #4173:
* incorrectly edited new tests to fail when they should have passed
* added code to increment depth twice at a level to make the tests pass when it should fail
3. delayed discovery that in new tests, my careful comments contradicted the `maxDepth` option
4. course correction:
* instead of constructing new or `ArrayContaining` or `ObjectContaining` instances
* factor out 4 helper functions out so built-in plugins can call them (this PR calls 2 and the next PR for Immutable plugins will call the other 2)
* add `printer` callback function as …
=> Factor out common code for collections in pretty-format

packages/jest-runtime/src/__tests__/__snapshots__/script_transformer.test.js.snap, packages/jest-runtime/src/__tests__/script_transformer.test.js, packages/jest-runtime/src/script_transformer.js, types/Transform.js
**Summary**
The first time someone flips on mapCoverage, they'll have a bad time if their transformer implements a getCacheKey since the flag is not passed to it. There's a chance this PR would fix issues like #4163. I ran into something similar and nuking the cache manually fixed it.
**Test plan**
Test added
=> let transformers adjust cache key based on mapCoverage

packages/jest-changed-files/README.md
**Summary**
Updates the docs for jest-changed-files package to match what is the main export.
Issue referenced here https://github.com/facebook/jest/issues/4182
**Test plan**
No tests, just documentation updates.
=> Update docs for jest-changed-files

docs/en/Configuration.md
**Summary**
before:
through a jest.config.js file **or or** through the --config <path/to/js|json> option.
after:
through a jest.config.js file **or** through the --config <path/to/js|json> option.
=> Remove duplicate 'or' in docs.

packages/jest-phabricator/example/JestUnitTestEngine.php, packages/jest-phabricator/src/index.js, types/TestResult.js
Some changes were done to the `jest-phabricator` result processor; both for optimizing the size of the resulting JSON and for making the results shape more consistent. This is a summary on how the changes affect the current way of working of the plugin:
1. The additional level of indirection where all the results were copied inside `aggregatedResult` is gone. This way, the resulting data format is the same whether you use `jest-phabricator` or not.
2. Now we override `coverageMap` to place the coverage there. The standard coverage format is huge, and although the code said [we will not include it in the final result for performance reasons](https://github.com/facebook/jest/blob/dec54a3/packages/jest-phabricator/src/index.js#L56-L57), it was getting preserved inside …
=> Improve Jest phabricator plugin

packages/babel-jest/package.json, yarn.lock
**Summary**
This makes `babel-jest` compatible with whichever version of Babel is used in a given project, since `babel-core@6` is not necessarily compatible with plugins made for Babel 7.
**Note that this is a breaking change (albeit low impact).**
Fixes #4055 (`babel-jest` is incompatible with plugins made for Babel 7).
**Test plan**
In a project using `jest@20.0.4` and the following Babel packages:
```
"babel-cli": "^7.0.0-alpha.15",
"babel-core": "^7.0.0-alpha.15",
"babel-eslint": "^8.0.0-alpha.15",
"babel-loader": "^7.1.1",
"babel-plugin-dynamic-import-node": "^1.0.2",
"babel-plugin-syntax-dynamic-import": "^7.0.0-alpha.15",
"babel-plugin-transform-class-properties": "^7.0.0-alpha.15",
"babel-plugin-transform-object-rest-spread": "^7.0.0-alpha.15",
```
Install `babel-jest` using:
``` …
```
=> Change babel-core to peerDependency for compatibility with Babel 7

packages/pretty-format/src/__tests__/react.test.js, packages/pretty-format/src/plugins/lib/markup.js, packages/pretty-format/src/plugins/react_element.js, packages/pretty-format/src/plugins/react_test_component.js
**Summary**
For example, just as the minified Expected/Received summary in `jest-matcher-utils` limits depth of JavaScript arrays or objects, so also for React elements or test objects.
Y’all are welcome to suggest alternative to `<type … />` as the notation.
**Test plan**
Added 2 fail-first tests. Please forgive how verbose for my Pooh Bear brain to keep count.
=> Support maxDepth option in React plugins

packages/jest-diff/src/index.js, packages/jest-matcher-utils/src/index.js, packages/jest-snapshot/src/plugins.js, packages/pretty-format/src/__tests__/immutable.test.js
**Summary**
Follow up after #4189
**Test plan**
Separating from previous PR should avoid problem with links to dependencies
=> Replace concat(Immutable) with Immutable as item of plugins array

packages/pretty-format/src/__tests__/html_element.test.js, packages/pretty-format/src/plugins/html_element.js
**Summary**
Support `indentation` and `depth` arguments. Enforce consistent printing of attributes/props.
After reading about `Element.attributes` and `Node.childNodes` Web API docs on MDN, I removed some conditional expressions that seemed to protect against absence of the properties.
Future follow up: To understand how much of whitespace trimming affects significant text content (see comments in test file) I will study some realistic examples, especially HTML rendered by React.
**Test plan**
Added 3 new fail-first tests.
=> Replace print with serialize in HTMLElement plugin

packages/pretty-format/README.md
**Summary**
* Under **Usage** sort object keys and include trailing commas
* Under **API** replace list with table of options sorted by key
**Test plan**
Eagle eye of reviewer :)
=> Revise Usage and API in pretty-format/README.md

packages/jest-cli/src/__tests__/test_scheduler.test.js, packages/jest-cli/src/jest.js, packages/jest-cli/src/run_jest.js, packages/jest-cli/src/test_scheduler.js
**Summary**
I'm refactoring some bits and pieces in the TestRunner and it makes more sense going forward to rename it to TestScheduler. It doesn't actually run the tests, it just tells other parts of Jests which ones to run, in which order and how (in-band or parallel).
**Test plan**
jest
=> Rename TestRunner to TestScheduler

packages/pretty-format/README.md
**Summary**
Parallelized **Usage** headings and prioritized information to remove internal links.
* Move types to introduction
* Usage with options:
* Add example
* Align headings and reduce wrapping in table of options
* Usage with plugins: prioritize how to use above how to develop
**Test plan**
Critique by human
=> Repeat usage headings in pretty-format/README.md

packages/jest-cli/src/__tests__/test_runner.test.js, packages/jest-cli/src/__tests__/test_scheduler.test.js, packages/jest-cli/src/test_runner.js, packages/jest-cli/src/test_scheduler.js, types/TestRunner.js
**Summary**
Second step in making test runners pluggable. This simply splits up the big scheduler class into the TestScheduler that instruments everything and a concrete TestRunner that knows how to schedule JavaScript tests.
**Test plan**
jest
=> Split TestRunner off of TestScheduler

packages/jest-cli/src/cli/args.js, packages/jest-config/src/index.js
**Summary**
https://github.com/facebook/jest/issues/4194
Adds error handling for the `--config` argument.
- Handles error for invalid JSON object
- Handles error for invalid files that are not `.js` or `.json`
**Test plan**
Quick question: Is there a place that I can add some tests for this?
=> Better error handling for --config

packages/jest-matchers/src/__tests__/matchers.test.js, packages/jest-matchers/src/index.js
**Summary**
When using [unexpected](http://unexpected.js.org/) it's common to import it under the name `expect`. Consider this case:
```js
import expect from 'unexpected';
it('should be unexpected', () => {
expect(true, 'to be false');
});
``` 
If a user by accident forgets to import unexpected, they will not immediately notice, as the builtin expect in jest will ignore any further arguments passed to it. Which will result in a passing test instead of the failure you would expect.
This PR adds a check to the expect method, so that it will throw an error if it is called with more than one argument.
@Munter already discussed a solution to this with @cpojer. The solution I implemented here is a bit different. Instead of using a check on `arguments.length` I opted to use `...rest` and check …
=> Complain if expect is passed multiple arguments

packages/jest-haste-map/src/get_mock_name.js
**Summary**
Fixing #4014: mocks for packages with folders (like `lodash/fp/sum`) on Windows. 
**Questions** 
1) what is the better way to write tests for that? 
2) Is this change enough? Doesn't it break something else on windows? There are not a lot for tests
=> Fix mocking for modules with folders on windows

integration_tests/__tests__/__snapshots__/list_tests.test.js.snap, integration_tests/__tests__/list_tests.test.js, integration_tests/list_tests/__tests__/other.test.js, packages/jest-cli/src/run_jest.js
**Summary**
https://github.com/facebook/jest/issues/4214
This makes `--listTests` play better with tools like `grep`
**Test plan**
=> Make --listTests return a new line separated list when not using --json

packages/jest-config/src/valid_config.js
**Summary**
This was missing and giving me a few confusing validation messages.
**Test plan**
When runner is specified, no warning is printed.
=> Whitelist the `runner` option in valid_config.

integration_tests/__tests__/jest_require_actual.test.js, packages/jest-haste-map/src/lib/__tests__/extract_requires.test.js, packages/jest-haste-map/src/lib/extract_requires.js, packages/jest-runtime/src/index.js, types/Jest.js
fixes https://github.com/facebook/jest/issues/4137
=> implement `jest.requireActual`

docs/en/MoreResources.md
**Summary**
The link to Relay was previously broken by linking to a non-existent page.
**Test plan**
Clicking on the relay link, now takes you to:
=> Fixing broken link for relay tests

packages/jest-config/src/set_from_argv.js
**Summary**
Fixes #4251. To be honest i'm not sure if this is the right fix cc:@cpojer
**Test plan**
It would be great to add a test to prevent this regression
=> Fix --watchAll

packages/jest-util/src/__tests__/format_test_results_test.js, packages/jest-util/src/format_test_results.js, types/TestResult.js
**Summary**
Reinstate of https://github.com/facebook/jest/pull/3378 with added tests. 
> This PR adds an additional field fullName to FormattedAssertionResult.
>
> When we try to analyze the test result json, we find that two it test cases under different describe block in one test file are rendered the same in the json report. Including the full name help solving this issue.
**Test plan**
```
...
"testResults": [
{
"assertionResults": [
{
"failureMessages": [],
"fullName": "Header renders",
"status": "passed",
"title": "renders"
},
{
"failureMessages": [],
"fullName": "Header renders <Element /> with right props",
"status": "passed",
"title": "renders <Element /> with right props"
}
],
"endTime": 1493233733071,
"message": "",
"name": "/path/to/the/test/file.js",
"startTime": …
```
=> Include fullName in formattedAssertion

packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter.js
to run 
```
./jest --testRunner '<rootDir>/packages/jest-circus/build/legacy_code_todo_rewrite/jest_adapter.js' matchers.test
```
=> fix jest-circus

packages/jest-matcher-utils/src/index.js, packages/jest-matchers/src/__tests__/__snapshots__/matchers.test.js.snap, packages/jest-matchers/src/matchers.js
**Summary**
See https://github.com/facebook/jest/issues/4228
**Test plan**
=> [WIP] Make toBe matcher error message more helpful for objects and arrays
