docs/TutorialReact.md
=> Remove JSX pragma from TutorialReact.js

.travis.yml
This is apparently way faster and will be the default soon.
=> Use sudo: false for Travis

package.json
Fix for https://github.com/facebook/jest/issues/309
=> Move node-find-files to devDependencies and lock to 0.0.2

website/core/Site.js
I didn't want you to look silly =)
=> Update the copyright year in the footer

bin/jest.js
The missing documentation of this behavior caused major pain, the behavior it self is not very reasonable.
=> Update description for --config CLI option in bin/jest.js

README.md, bin/jest.js, docs/API.md, src/jest.js
Let me know if you need any changes or have any comments.
I did not think this deserved a specific test since I feel it is an edge case but let me know if you feel otherwise.
Thanks!
=> Issue #357 - CLI --testPathPattern option

src/lib/FakeTimers.js, src/lib/__tests__/FakeTimers-test.js
Check for new immediate after each timeout handler.
=> Fix dynamic immediates handling

src/jasmineTestRunner/jasmineTestRunner.js
cc @elgerlambert @coma 
https://github.com/facebook/jest/commit/39231b1abcc876e25b2784b638ef998e3d5bfaa8#diff-b5c8d6af17e002084e847c0cf102d283L58
=> restoring checks for WeakMap in jasmineTestRunner

README.md, docs/API.md, src/lib/utils.js
As requested by @PhilVargas in #424
=> adding bail to the config options

src/HasteModuleLoader/__tests__/test_root/RegularModule.js, src/lib/utils.js
`this === exports` in node modules.
Fixes #450
=> Correct node modules context

.travis.yml
Test Plan: The automated tests for this PR passed.
=> [io.js] Add io.js 3.x to the Travis CI test matrix

docs/GettingStarted.md
add document to showcase how to re-run tests automatically for #472
=> add document for re-run tests automatically

.travis.yml
Since we care about node v4, test it.
=> Add node v4 to Travis matrix

docs/API.md
Seems like it was forgotten in #303
=> Some info about config.preprocessorIgnorePatterns

bin/jest.js
=> feat: Add support for watching arbitrary file extensions

docs/API.md
Adding an example to show how to mock class constructors (see #124)
=> mockImplementation class constructor example

examples/react-es6/__tests__/CheckboxWithLabel-test.js, examples/react-es6/package.json
Updated example/react-es6 to use react 0.14.
This is same purpose as [https://github.com/facebook/jest/pull/550]
=> Upgrade to react 0.14

website/core/Site.js
(cherry picked from commit ca6cd96f2f7e502a3c8e3204af8c84354f1fcac8)
=> Update copyright year (website)

.flowconfig, packages/jest-util/src/JasmineFormatter.js, packages/jest-util/src/formatFailureMessage.js, packages/jest-util/src/installCommonGlobals.js, types/Config.js, types/Environment.js, types/Global.js, types/TestResult.js
=> Add type annotations to jest-util.

docs/TutorialWebpack.md
=> Improve webpack tutorial

packages/jest-environment-node/src/index.js, scripts/build.js
This adds flowtypes to the jest-environment-node package! 🎉
=> Flowify jest-environment-node

.flowconfig, package.json, packages/jest-environment-node/src/index.js, packages/jest-util/src/FakeTimers.js, scripts/build.js
Also add trailing comma transform.
=> Annotate FakeTimers.

package.json, scripts/build.js, scripts/watch.js
=> npm run watch

types/HasteMap.js
=> Add HasteMap type definition

packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/reporter.js, types/TestResult.js
Finish adding flow to the jasmine2 package
=> Flow-ify jasmine2/reporter

packages/jest-snapshot/src/SnapshotFile.js, packages/jest-snapshot/src/SnapshotState.js, packages/jest-snapshot/src/getMatchers.js, packages/jest-util/src/JasmineFormatter.js, types/Jasmine.js, types/TestResult.js
=> Snapshot flow 2

packages/jest-mock/src/index.js
This is a first pass - I know there are some types that could be more
detailed.
=> Add flow type annotations to `jest-mock`

packages/jest-resolve/src/index.js, types/HasteMap.js
=> Flowify jest-resolve

packages/jest-environment-jsdom/src/index.js
=> Add flow typing to environment-jsdom

packages/jest-cli/src/SearchSource.js, packages/jest-cli/src/lib/buildHasteMap.js, packages/jest-cli/src/types.js, packages/jest-resolve/src/index.js
=> Flowify searchsource

packages/jest-cli/src/SearchSource.js, packages/jest-cli/src/Test.js, packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/cli/args.js, packages/jest-cli/src/cli/getJest.js, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/constants.js, packages/jest-cli/src/jest.js, packages/jest-cli/src/lib/formatTestResults.js, packages/jest-haste-map/src/constants.js, packages/jest-haste-map/src/crawlers/node.js, packages/jest-haste-map/src/crawlers/watchman.js, packages/jest-haste-map/src/fastpath.js, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/lib/docblock.js, packages/jest-haste-map/src/lib/extractRequires.js, packages/jest-haste-map/src/lib/getPlatformExtension.js, packages/jest-haste-map/src/types.js, packages/jest-haste-map/src/worker.js, types/Config.js, types/TestResult.js
Now most of `jest-cli` should be "properly" typed. There is still a bunch of stuff I wanna clean up and some untyped areas, but overall this is pretty nice now :)
=> More Flow annotations.

packages/jest-config/src/normalize.js, packages/jest-config/src/setFromArgv.js, packages/jest-repl/.npmignore, packages/jest-repl/bin/jest-repl.js, packages/jest-repl/package.json, packages/jest-repl/src/cli/args.js, packages/jest-repl/src/cli/index.js, packages/jest-repl/src/cli/repl.js, packages/jest-repl/src/index.js, packages/jest-runtime/src/cli/index.js
=> Added jest-repl

packages/jest-repl/src/__tests__/jest-repl-test.js, packages/jest-repl/src/cli/repl.js, packages/jest-runtime/src/__tests__/Runtime-cli-test.js
- Fixed bug in jest-runtime test
- Fixed linter errors
=> Added jest-repl test

examples/snapshot/.babelrc, examples/snapshot/Link.react.js, examples/snapshot/__tests__/Link.react.js, examples/snapshot/__tests__/__snapshots__/Link.react.js.snap, examples/snapshot/package.json
Adds a little example for jest-snapshot
=> Adding example of snapshot

.eslintrc, integration_tests/testcheck/__tests__/testcheck-exceptions-test.js, integration_tests/testcheck/__tests__/testcheck-fit-test.js, integration_tests/testcheck/__tests__/testcheck-options-test.js, integration_tests/testcheck/__tests__/testcheck-test.js, packages/jest-environment-node/src/index.js, packages/jest-jasmine2/src/jasmine-check.js
I don't like adding new globals and think this is gonna make @dmitriiabramov happy.
=> Remove `gen` and `check` globals.

packages/jest-environment-node/src/index.js, scripts/watch.js
Why a git branch change causes a `rename` event to be fired I don't know.
The `rename` event is also not documented https://github.com/nodejs/node/issues/7504.
=> Watch script

examples/snapshot/package.json
moving the dependency of the snapshot example test from RC to Release version
=> Update to release version of react

examples/snapshot/__tests__/__snapshots__/Link.react.js.snap, packages/jest-snapshot/package.json, packages/jest-snapshot/src/SnapshotFile.js
* Properly compare escape characters.
* Sort the output of a snapshot file alphabetically.
=> Snapshot Fixes:

integration_tests/__tests__/__snapshots__/snapshot_regression-test.js.snap, integration_tests/__tests__/snapshot-test.js, integration_tests/package.json, integration_tests/snapshot-escape/__tests__/snapshot-test.js, integration_tests/snapshot-escape/package.json, packages/jest-config/src/reporters/DefaultTestReporter.js, packages/jest-snapshot/src/SnapshotFile.js
This fixes escaping of strings properly and I added a really nice integration test, @dmitriiabramov should be proud.
=> More snapshot fixes.

examples/snapshot/__tests__/Link.react-test.js, examples/snapshot/__tests__/__snapshots__/Link.react-test.js.snap, packages/jest-diff/package.json, packages/jest-snapshot/package.json, packages/jest-snapshot/src/SnapshotFile.js
This includes a test from #1260 and should fix all the remaining escaping issues.
(Just kidding, I'm sure there are more issues with this. Ughhhh).
=> Further snapshot escaping fixes.

docs/API.md
https://github.com/facebook/jest/issues/1290#issuecomment-232549875
=> Small documentation fix (moduleNameMapper section)

packages/jest-cli/src/TestRunner.js
our internal runner shamelessly accesses the private guts of TestRunner and different reporters.
exposing `addReporter` publicly would be the first step to defining a reporting interface
=> TestRunner#addReporter

packages/jest-runtime/src/__tests__/transform-test.js, packages/jest-runtime/src/transform.js
=> Make transform dependent on the `instrument` option.

integration_tests/__tests__/no-test-found-test.js, packages/jest-cli/src/reporters/SummaryReporter.js
cc @dmitriiabramov I think this is a regression.
=> Don’t print test summary if no tests were run.

blog/2016-07-27-jest-14.md
Updated the npm command to --save-dev instead of -save-dev
=> Updated typo in react native area of new blog post

blog/2016-07-27-jest-14.md
Official package implemented in https://github.com/facebook/react/pull/7362
=> Update blog post react-test-renderer import

docs/TutorialReact.md
=> docs: remove * from version in React Tutorial

packages/jest-snapshot/src/SnapshotFile.js, packages/jest-snapshot/src/index.js
=> Export SnapshotFile constructor from jest-snapshot

package.json, scripts/test_examples.js
=> npm run jest

README.md, docs/API.md
Currently testPathIgnorePattern is listed as the argument in the documentation but the implementation accepts testPathIgnorePatterns. Just wanted to update this for others who may be starting out and stumble on this.
=> Documentation for testPathIgnorePatterns

integration_tests/__tests__/empty_suite_error-test.js, integration_tests/__tests__/verbose-test.js, packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/TestWorker.js, packages/jest-cli/src/lib/formatTestResults.js, packages/jest-cli/src/reporters/DefaultReporter.js, packages/jest-cli/src/reporters/SummaryReporter.js, packages/jest-cli/src/reporters/VerboseReporter.js, packages/jest-cli/src/reporters/getResultHeader.js, packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/reporter.js, packages/jest-util/src/__tests__/__snapshots__/formatFailureMessage-test.js.snap, packages/jest-util/src/__tests__/formatFailureMessage-test.js, packages/jest-util/src/formatFailureMessage.js, packages/jest-util/src/index.js, packages/jest-util/src/separateMessageFromStack.js, types/TestResult.js
=> Error formatting

docs/Tutorial.md
=> Fix apostrophe typo

docs/TutorialWebpack.md
Ref https://github.com/facebook/jest/issues/1387
webpack apparently is always written "webpack".
=> Add webpack 2 Babel module docs

packages/jest-cli/src/TestRunner.js
=> Run fast test runs in band.

examples/react-native/package.json, packages/jest-react-native/jest-preset.json, packages/jest-react-native/package.json, packages/jest-react-native/src/index.js
=> Fix react-native preset.

packages/jest-resolve-dependencies/src/index.js, packages/jest-resolve/src/index.js, packages/jest-runtime/src/__tests__/Runtime-requireModuleOrMock-test.js, packages/jest-runtime/src/__tests__/test_root/TestModuleNameMapperResolution.jsx, packages/jest-runtime/src/index.js
=> Use resolution algorithm for moduleNameMapper.

packages/jest-cli/src/cli/args.js, packages/jest-cli/src/jest.js, packages/jest-cli/src/reporters/DefaultReporter.js, packages/jest-config/src/defaults.js, packages/jest-config/src/normalize.js, packages/jest-config/src/setFromArgv.js, packages/jest-util/src/Console.js, packages/jest-util/src/clearLine.js, packages/jest-util/src/index.js, types/Config.js
This will get rid of the ugly `Running 1 test suite… LOG FOOOOO`.
=> Add `clearLine` module and remove `config.noHighlight`.

packages/jest-cli/src/__tests__/customMatchers-test.js, packages/jest-jasmine2/src/index.js, packages/jest-matchers/src/__tests__/spyMatchers-test.js, packages/jest-matchers/src/spyMatchers.js
=> toHaveBeenCalled now works with Jest mocks

packages/jest-react-native/jest-preset.json, packages/jest-react-native/src/index.js
Mock Image component with `propTypes`, `resizeMode`, `prefetchImage` and `getSize` properties
=> Add propTypes and resizeMode to Image mock

package.json, packages/jest-changed-files/src/__tests__/git-test.js, packages/jest-changed-files/src/__tests__/hg-test.js, packages/jest-changed-files/src/git.js, packages/jest-changed-files/src/hg.js, packages/jest-cli/src/SearchSource.js, packages/jest-cli/src/cli/args.js, packages/jest-cli/src/jest.js
Added functionality to get list of changed files from last commit for both git and hg.
=> Fixed Issue https://github.com/facebook/jest/issues/1443

packages/jest-cli/package.json
Same as https://github.com/facebook/react-native/commit/1a375276069b5462b8fbb342c64736c0f729c833.
=> Update package dependency to `sane@~1.4.1`

packages/jest-cli/src/jest.js, packages/jest-cli/src/reporters/SummaryReporter.js, packages/jest-config/src/defaults.js, packages/jest-config/src/setFromArgv.js, packages/jest-snapshot/src/SnapshotFile.js, types/Config.js
=> Update snapshots from within watch mode

packages/jest-cli/src/reporters/BaseReporter.js, packages/jest-cli/src/reporters/CoverageReporter.js, packages/jest-cli/src/reporters/DefaultReporter.js, packages/jest-cli/src/reporters/VerboseReporter.js
=> Added message to coverage reporter.

integration_tests/coverage_report/package.json, packages/jest-cli/src/__tests__/generateEmptyCoverage-test.js, packages/jest-cli/src/generateEmptyCoverage.js, packages/jest-cli/src/reporters/CoverageReporter.js, packages/jest-runtime/src/index.js, packages/jest-runtime/src/shouldInstrument.js, packages/jest-runtime/src/transform.js
no more 
```
"!**/__tests__/**`,
"!**/__mocks__/**`,
```
in the config
=> exclude __tests__ and __mocks__ from coverage

package.json
let's start from something small and evolve incrementally :)
=> collect coverage only for specific packages

packages/jest-matcher-utils/src/index.js, packages/jest-matchers/src/__tests__/__snapshots__/toThrowMatchers-test.js.snap, packages/jest-matchers/src/__tests__/_matchErrorSnapshot.js, packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-matchers/src/__tests__/toThrowMatchers-test.js, packages/jest-matchers/src/toThrowMatchers.js
=> .toThrowError() messages

integration_tests/__tests__/__snapshots__/coverage_report-test.js.snap, packages/jest-cli/src/reporters/CoverageReporter.js
coverageReporter should be coverageReporters
=> Fixed coverageReporters prop name

integration_tests/__tests__/__snapshots__/console-test.js.snap, integration_tests/__tests__/__snapshots__/coverage_report-test.js.snap, integration_tests/__tests__/__snapshots__/failures-test.js.snap, integration_tests/__tests__/no-test-found-test.js, integration_tests/console/__tests__/console-test.js, packages/jest-cli/src/SearchSource.js, packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/__tests__/TestRunner-test.js, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/jest.js, packages/jest-cli/src/reporters/CoverageReporter.js, packages/jest-cli/src/reporters/DefaultReporter.js, packages/jest-cli/src/reporters/SummaryReporter.js, types/Reporters.js
See https://twitter.com/cpojer/status/770732614907027456
=> Enhanced watch mode and better summary printing.

packages/jest-matchers/src/__tests__/toThrowMatchers-test.js, packages/jest-matchers/src/toThrowMatchers.js
I did this as a mistake in https://github.com/facebook/jest/commit/83c254177f6ee58a9669c56e359d22ade0b21977 :(
=> Throw matcher

integration_tests/__tests__/symbol-test.js, packages/jest-matchers/src/matchers.js
=> Symbol fix

examples/snapshot/__tests__/Link.react-test.js, integration_tests/__tests__/jasmine_async-test.js, integration_tests/jasmine_async/__tests__/promise_afterAll-test.js, integration_tests/jasmine_async/__tests__/promise_beforeAll-test.js, packages/jest-jasmine2/src/jasmine-async.js
cc @ide who was too lazy to do this :P
=> Make afterAll and beforeAll work with promises and async/await.

packages/jest-cli/package.json, packages/jest-cli/src/jest.js
this is better! Looking forward to rewriting watch.
=> Use ansi-escapes to clear two lines.

blog/2016-09-01-jest-15.md, packages/jest-cli/src/jest.js
As requested on Twitter.
Also fixed an embarrassing typo.
=> New text for entering a test pattern.

packages/jest-diff/src/diffStrings.js
Test Plan: Patched Jest in local installation, looks good in light and dark schemes:
=> Use dim output for unchanged lines when showing a diff

website/src/jest/index.js
Mind adding my name as the author here? 😀
=> Shameless self-plug

docs/GettingStarted.md
cc @cpojer, added a link to the new testing guide I just released!
=> Add link to testing guide

README.md, packages/jest-cli/package.json, packages/jest/package.json, website/siteConfig.js
=> s/Painless Unit Testing/Painless Testing/

packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-matchers/src/matchers.js
=> expect(a).toBeInstanceOf(b)

docs/GettingStarted.md
=> Docs: add a note in Getting Started about babel-jest using NODE_ENV=test

README.md, docs/GettingStarted.md
Some of this looks repetitive which makes me think that maybe the README is generated. Let me know what changes I need to make :)
=> Add links to relevant egghead.io videos

integration_tests/__tests__/jasmine_async-test.js, integration_tests/jasmine_async/__tests__/concurrent-test.js, packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/jasmine-async.js
fixes https://github.com/facebook/jest/issues/1630
=> test.concurrent

integration_tests/__tests__/jasmine_async-test.js, integration_tests/jasmine_async/__tests__/generators-test.js, packages/jest-jasmine2/package.json, packages/jest-jasmine2/src/__tests__/generators-test.js, packages/jest-jasmine2/src/jasmine-async.js
add support for testing using generator functions per https://github.com/mxstbr/react-boilerplate/pull/980
cc @mxstbr
=> generator functions*

docs/API.md
=> Add async-to-gen as a possible script preprocessor

docs/MockFunctions.md
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. The two fields below are mandatory.
**Summary**
Fixing the typo
**Test plan**
NA
=> Fixed a typo in mock functions doc page

package.json
i have some flow errors that are only thrown using `flow-bin@0.32.0`. Updating it here so i can rebase later
=> flow-bin@0.32.0

.flowconfig, lerna.json, package.json, packages/jest-cli/src/__tests__/SearchSource-test.js
**Summary**
Updated lerna; made a test more consistent.
**Test plan**
jest
=> Update deps; make SearchSource-test consistent.

examples/typescript/__tests__/sub-test.ts
**Summary**
There is a typo in variable name and invalid test description in one of the TypeScript examples.
**Test plan**
N/A I guess, it is just a variable rename and string constant improvement in one isolated file.
=> Improve variable name and test description in TypeScript example

integration_tests/__tests__/toMatchSnapshot-test.js, integration_tests/utils.js
this thing was super easy to work with and i actually want to use it for some other tests too
=> move dynamic test creation to ./utils.js

packages/jest-jasmine2/src/index.js
i don't think we need it any more
=> remove jasmine hacks

packages/jest-react-native/src/setup.js
=> Add Modal mock

docs/Configuration.md
collectCoverageFrom should be an array of glob patterns.
=> [doc] fix collectCoverageFrom type

integration_tests/__tests__/toMatchSnapshot-test.js, integration_tests/__tests__/toThrowErrorMatchingSnapshot-test.js, integration_tests/snapshot/__tests__/snapshot-test.js, packages/jest-snapshot/src/index.js
Just a few small cleanups :)
cc @maximderbin
=> Polish toThrowErrorMatchingSnapshot.

integration_tests/__tests__/__snapshots__/console-test.js.snap, integration_tests/__tests__/__snapshots__/coverage_report-test.js.snap, integration_tests/__tests__/__snapshots__/failures-test.js.snap, integration_tests/__tests__/__snapshots__/globals-test.js.snap, integration_tests/__tests__/__snapshots__/snapshot-test.js.snap, integration_tests/__tests__/__snapshots__/stack_trace-test.js.snap, integration_tests/__tests__/__snapshots__/testNamePattern-test.js.snap, integration_tests/__tests__/console-test.js, integration_tests/__tests__/snapshot-test.js, integration_tests/__tests__/testNamePattern-test.js, integration_tests/__tests__/toMatchSnapshot-test.js, integration_tests/__tests__/toThrowErrorMatchingSnapshot-test.js, integration_tests/utils.js, packages/jest-cli/src/SearchSource.js, packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/jest.js, packages/jest-cli/src/reporters/DefaultReporter.js, packages/jest-cli/src/reporters/SummaryReporter.js, packages/jest-cli/src/reporters/VerboseReporter.js, packages/jest-cli/src/reporters/getResultHeader.js, packages/jest-cli/src/reporters/utils.js, packages/jest-cli/src/runTest.js, types/TestResult.js
=> Add back support for skipped tests in the CLI.

docs/MigrationGuide.md, docs/TutorialjQuery.md
https://github.com/facebook/jest/issues/1830
@cpojer please have a look :)
=> Documentation: migration guide

website/src/jest/index.js
**Summary**
Fixed a typo in the homepage.
**Test plan**
Not applicable.
=> Fixed typo in homepage

docs/TutorialWebpack.md
**Summary**
While trying to set up Webpack with Jest, I encountered a few issues with `webpack.config.js`.
- The config object should be exported.
- Missing comma for `modulesDirectories` line.
**Test plan**
Copy out the changed example code into a Webpack config file and test locally. (I did test it).
=> Fix Webpack config

docs/TutorialWebpack.md
**Summary**
http://theoatmeal.com/comics/apostrophe
**Test plan**
Visual inspection :)
=> Apostrophe fix

docs/Configuration.md
Fix https://github.com/facebook/jest/issues/1891
=> Fix order in configuration page

docs/Configuration.md
**Summary**
**Test plan**
It's difficult to debug, so add an additional notice.
=> [Docs] Add a note to moduleNameMapper

docs/ManualMocks.md
**Summary**
Fix internal documentation link
**Test plan**
=> fix link to genMockFromModule API documentation

docs/Configuration.md, integration_tests/__tests__/__snapshots__/snapshot-serializers-test.js.snap, integration_tests/__tests__/snapshot-serializers-test.js, integration_tests/snapshot-serializers/__tests__/snapshot-test.js, integration_tests/snapshot-serializers/package.json, integration_tests/snapshot-serializers/plugins/bar.js, integration_tests/snapshot-serializers/plugins/foo.js, integration_tests/snapshot-serializers/utils.js, packages/jest-config/src/__tests__/normalize-test.js, packages/jest-config/src/defaults.js, packages/jest-config/src/normalize.js, packages/jest-jasmine2/src/__mocks__/jest-snapshot.js, packages/jest-jasmine2/src/__tests__/setup-jest-globals-test.js, packages/jest-jasmine2/src/setup-jest-globals.js, packages/jest-snapshot/src/__tests__/plugins-test.js, packages/jest-snapshot/src/__tests__/plugins/bar.js, packages/jest-snapshot/src/__tests__/plugins/foo.js, packages/jest-snapshot/src/index.js, packages/jest-snapshot/src/plugins.js, packages/jest-snapshot/src/utils.js, types/Config.js
**Summary**
Add custom snapshot serializers as a configurable option, add it to "Configuration" docs.
=> Add custom snapshot serializers (#1741)

docs/TutorialWebpack.md
**Summary**
Fix regular expressions of `moduleNameMapper` config option in `TutorialWebpack.md` (for changes of a41450bdf01c52c542055425469eb8f12d85cd91).
=> Fix TutorialWebpack.md

website/src/jest/css/jest.css
**Summary**
Improve header tag anchor positioning so that jumping to a method shows the method name.
**Test plan**
```
cd website
npm install
npm start
```
Then go to something like http://localhost:8080/jest/docs/api.html, and click `expect(value)`. 
You should see the `expect(value)` header.
If you try the same at https://facebook.github.io/jest/docs/api.html, the header is hidden.
=> Docs: Improve header anchor positioning

examples/typescript/__tests__/sum-test.js
**Summary**
This is just a minor change to fix a typo in `examples/typescript`.
**Test plan**
No testing required.
=> Correct typo in TS example

docs/Configuration.md, docs/Troubleshooting.md, docs/TutorialReact.md, docs/TutorialReactNative.md, integration_tests/__tests__/__snapshots__/transform-test.js.snap, integration_tests/__tests__/transform-test.js, integration_tests/auto-reset-mocks/with-auto-reset/package.json, integration_tests/auto-reset-mocks/without-auto-reset/package.json, integration_tests/resolve/package.json, packages/babel-jest/src/index.js, packages/jest-cli/src/cli/args.js, packages/jest-config/src/__tests__/__snapshots__/normalize-test.js.snap, packages/jest-config/src/__tests__/normalize-test.js, packages/jest-config/src/constants.js, packages/jest-config/src/normalize.js, packages/jest-mock/src/__tests__/jest-mock-test.js, packages/jest-repl/src/cli/repl.js, packages/jest-runtime/src/__tests__/Runtime-requireModuleOrMock-test.js, packages/jest-runtime/src/__tests__/__snapshots__/Runtime-requireModuleOrMock-test.js.snap, packages/jest-runtime/src/index.js, packages/jest-runtime/src/transform.js, types/Transform.js
**Summary**
* More cleanups.
* Removed old deprecation warnings.
**Test plan**
jest
=> Transform/preprocessor cleanups; remove old deprecation warnings.

CHANGELOG.md, packages/jest-cli/src/lib/formatTestResults.js
**Summary**
Adds individual assertion results to the JSON output. See discussion in https://github.com/facebook/jest/issues/1900
The above issue predates me exploring how you can get the lines of an assertion in JS (In C-langs, it's easily available and cheap) but in JS it's neither https://github.com/winstonjs/winston/issues/200#issuecomment-173475163 - so I'm leaving it to the consumer of the JSON to make their own decisions about the asserting lines.
I also tried to keep all the terminology the same as the internal codebase.
You could derive it by splitting the failure messages by "\n" and pulling out the same one as the actual filename.
This file doesn't have tests, I can add one? ( Maybe the integration tests will get triggered, didn't try all of those yet - still doing all their …
=> Adds assertion information to the json output

packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/reporter.js, packages/jest-jasmine2/vendor/jasmine-2.5.2.js
**Summary**
Currently Jest uses a fork of Jasmine v2.4.1, which IMO causes a bug described here: #2050. It looks like upgrading to version 2.5.x fixes this particular issue. 
**Test plan**
Apply all custom changes made previously to Jasmine v2.4.1 by Jest team to the 2.5.2 version and make all tests pass. 
**Status**
Currently there's 1 test left to pass (@cpojer I'd be happy to use some of your help on this one):
=> Bump Jasmine to version 2.5.2

packages/jest-cli/src/cli/args.js, packages/jest-config/src/defaults.js, packages/jest-config/src/setFromArgv.js, packages/jest-diff/src/diffStrings.js, packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/jest-expect.js, packages/jest-jasmine2/src/setup-jest-globals.js, packages/jest-matcher-utils/src/__tests__/__snapshots__/index-test.js.snap, packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/matchers.js, packages/jest-snapshot/src/State.js, packages/jest-snapshot/src/index.js, types/Config.js
=> Collapse big diffs

packages/jest-react-native/src/setup.js
**Summary**
In order to test our various interactive components properly, we needed to mock all `<Touchable* />` components.
=> Mock all Touchable* components

docs/API.md, packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-matchers/src/matchers.js
=> .toHaveLength

examples/react-native/package.json, packages/jest-react-native/package.json
=> Update whatwg-fetch peer dependency.

packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/matchers-test.js
=> .toContain with iterable tests

packages/jest-matcher-utils/src/index.js, packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-matchers/src/__tests__/utils-test.js, packages/jest-matchers/src/matchers.js, packages/jest-matchers/src/utils.js
=> .toHaveProperty

integration_tests/__tests__/json-test.js, packages/jest-environment-node/src/index.js
**Summary**
See https://github.com/facebook/jest/issues/1822#issuecomment-263717270. For some reason this didn't work previously but now it does and it is great!
cc @kentcdodds who also had trouble with this.
**Test plan**
jest
=> Use JSON from the test context, not the parent context.

docs/API.md
**Summary**
Yesterday I got bit by outdated information in the documentation, I want to prevent that from happening to someone else. (See https://github.com/facebook/jest/issues/1535#issuecomment-264017479)
**Test plan**
No code change.
=> Updated and clarified the documentation on `.toMatch()`

docs/Configuration.md
**Summary**
- I was modifying my own `testRegex` and found that the docs differed from the source code slightly.
- I also added a mention to the `.spec` and `.test` suffixes.
**Test plan**
- N/A (documentation change)
=> Update testRegex documentation to match source code

docs/Configuration.md
This got me confused because I was sure I saw an example of a custom transformer somewhere but couldn't figure out where. Adding a link so I don't lose it again.
=> Link to webpack tutorial

packages/jest-config/package.json, yarn.lock
**Summary**
Remove the `istanbul` dependency from the `jest-config` package.
Please, correct me if I am wrong, but it did not seem to be used.
**Test plan**
Since the only change was to the `package.json` of `jest-config`, I did not write any tests
=> Drop `istanbul` from `jest-config`.

docs/Configuration.md
**Summary**
Mention about not automocking core modules. 
#2258
=> Note about core modules not being automocked

packages/jest-editor-support/src/__tests__/TypeScriptParser-test.js
=> Fix long line.

integration_tests/__tests__/require-v8-module-test.js, packages/jest-resolve/src/index.js
**Summary**
Fixes #2122
**Test plan**
jest
=> Make the v8 core module work in Jest.

packages/jest-config/src/normalize.js, packages/jest-runtime/src/transform.js, types/Config.js
i'm trying to understand what causes syntax errors on CI, i tried to reproduce all kinds of race conditions and it had no success. This info will help me understand whether it's really a race condition that is causing it or something else.
https://github.com/facebook/jest/issues/1874
=> Log additional info on Syntax Errors

integration_tests/__tests__/test-in-root-test.js, packages/jest-editor-support/src/Process.js, packages/jest-editor-support/src/ProjectWorkspace.js, packages/jest-editor-support/src/Runner.js, packages/jest-editor-support/src/Settings.js, packages/jest-editor-support/src/TestReconciler.js, packages/jest-editor-support/src/TypeScriptParser.js, packages/jest-editor-support/src/__tests__/JestRunner-test.js, packages/jest-editor-support/src/__tests__/ProjectWorkspace-test.js, packages/jest-editor-support/src/__tests__/TestReconciler-test.js, packages/jest-editor-support/src/__tests__/TypeScriptParser-test.js, packages/jest-editor-support/src/index.js, packages/jest-editor-support/src/types.js
**Summary**
A few renames and cleanups discussed in person last week with @orta.
**Test plan**
jest
=> Cleanups for jest-editor-support

CHANGELOG.md
=> Changelog for Jest 18.

packages/jest-editor-support/src/__tests__/Runner-test.js
**Summary**
`jsonFilePath` => `outputPath`
**Test plan**
jest
=> Fix jest-editor-support Runner test

packages/jest-editor-support/src/Settings.js, packages/jest-editor-support/src/index.js
**Summary**
Makes all of the object exports consistent inside this repo.
**Test plan**
For now it's mainly me getting piece set up to work on a new computer, will be fine to look at the babylon stuff tomorrow.
=> Jest-Editor - Makes the Settings object work with requires

packages/jest-cli/src/jest.js, packages/jest-util/src/formatTestResults.js, packages/jest-util/src/index.js
**Summary**
#2316 is having some Flow errors; doing the separation here so we can ship 18.
**Test plan**
jest
=> Move formatTestResults into jest-util.

blog/2016-12-15-2016-in-jest.md
**Summary**
Typo in a person's name.
=> Clemons => Clemmons

blog/2016-12-15-2016-in-jest.md
=> Fix my last name

packages/jest-cli/package.json
**Summary**
There was a typo (aplha), so newer versions weren't picked up.
Do you want `1.1.0-alpha.1`?
**Test plan**
Coverage still works in my project, unsure how else to test this?
=> Update version of istanbul-api

website/publish-gh-pages.js
**Summary**
pushing over http doesn't work. cc @hramos 
**Test plan**
publish the site locally using DEPLOY_USER=facebook CIRCLE_PROJECT_USERNAME=facebook CIRCLE_PROJECT_REPONAME=jest GIT_USER=cpojer node publish-gh-pages.js
=> Fix website deploy.

packages/jest-cli/package.json
**Summary**
From phone... https://github.com/istanbuljs/istanbul-api/releases
**Test plan**
This commit is made from a phone, so haven't been able to test it
=> Use 1.1.0 of istanbul api

.flowconfig, packages/jest-config/src/loadFromFile.js, packages/jest-config/src/vendor/jsonlint.js
**Summary**
When loading config from file like this issue mention #2229, there is no friendly error message to figure it out what was wrong.
**Test plan**
Add `jsonlint` to show what is wrong with the json config
=> Show better error when json config is invalid

docs/API.md, docs/TutorialReactNative.md
I went to fix the problems reported in the "update API reference" task and did some fixing which is included here. I alphabetized unalphabetized stuff, fixed some broken links, updating some weird sentences, added a bit of missing info. Really there are more problems with this page though - there are a lot more missing parts, and this one doc is becoming somewhat of a grab bag where people add more crap to it.
=> update API reference doc a bit

examples/async/package.json, examples/enzyme/package.json, examples/getting_started/package.json, examples/jquery/package.json, examples/manual_mocks/package.json, examples/react-native/package.json, examples/react/package.json, examples/snapshot/package.json, examples/timer/package.json, examples/typescript/package.json
**Summary**
Rename `jest-cli` to `jest` in example package.json files.
=> Rename jest-cli to jest in examples

website/src/jest/help.js
* Updated team name.
* Made the troubleshooting item shorter to fit on one line on a small screen, to align better with the other items in the same section.
=> Update help page.

website/core/Head.js, website/package.json, website/server/convert.js, website/server/feed.js, website/server/server.js
**Summary**
Fixes #2277
Generates both rss and atom in the step in the convert step
**Test plan**
running `yarn start`
=> Adds RSS/Atom blog Feed

package.json, packages/pretty-format/src/__tests__/pretty-format-test.js, yarn.lock
=> Fix pretty-format test.

README.md, docs/GettingStarted.md, docs/UsingMatchers.md, examples/getting_started/sum.js
This doc is just an intro to the most common matchers. It's designed to be an informative doc for a noob to read right after they get Jest set up. If all you know is setup + this doc, you should be able to use Jest in an ok-but-not-awesome fashion.
I also tweaked the getting started a small bit to use more normal-js type things instead of fancy one-liners.
=> Using Matchers

packages/jest-diff/src/__tests__/diff-test.js, packages/jest-diff/src/index.js, packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap, scripts/test_examples.js
@vjeux pointed out this looked odd before.
cc @dmitriiabramov
=> Update jest-diff message to fit better with jest-matchers.

.travis.yml, package.json, scripts/test_examples.js
=> Maybe fix CI.

docs/Mocking.md, docs/SetupAndTeardown.md, docs/TestingAsyncCode.md, docs/TimerMocks.md, docs/TutorialAsync.md, docs/UsingMatchers.md
Two docs for the introduction. Testing async code just explains the basics of callbacks / promises / async/await. Setup and teardown explains the after/before stuff.
=> "Testing Asynchronous Code" & "Setup and Teardown"

docs/ExpectAPI.md
**Summary**
Because it's a handy intro to people new to the concept.
Original PR: https://github.com/facebook/jest/pull/2440
**Test plan**
N/A
=> docs(api): add egghead link to snapshots

docs/ManualMocks.md
**Summary**
I thought this was really interesting and expect
others to find the information useful as well.
Original PR: https://github.com/facebook/jest/pull/2438
**Test plan**
N/A
=> docs(ManualMocks): add note about ES modules

.travis.yml
**Summary**
Feel free to close, if we're up to testing LTS only.
=> Enable Node 7 for Travis

.travis.yml, package.json, yarn.lock
**Summary**
@bestander told me this now works out of the box.
**Test plan**
travis passes
=> Don’t install Yarn on travis.

.flowconfig
**Summary**
Travis start complaining about a node_modules/npm/node_modules/config-chain/test/broken.json file when running `flow check`, this put that in the flow ignore list
**Test plan**
flow (and travis should be back to green)
=> ignore broken json in config-chain

packages/jest-diff/src/__tests__/__snapshots__/diff-test.js.snap, packages/jest-diff/src/__tests__/diff-test.js, packages/jest-diff/src/diffStrings.js, packages/jest-matcher-utils/src/__tests__/__snapshots__/index-test.js.snap, packages/jest-matchers/src/__tests__/__snapshots__/matchers-test.js.snap
**Summary**
Fixes #2412
**Test plan**
Snapshots
=> Show patch marks '@@ ... @@' only when necessary

packages/jest-mock/src/__tests__/jest-mock-test.js, packages/jest-mock/src/index.js
Heavily inspired by expect one: https://github.com/mjackson/expect/blob/master/modules/SpyUtils.js#L96-L112
=> Implement spyOn

examples/react-native/package.json
**Summary**
RN example was a bit outdated and misleading.
**Test plan**
jest
=> Update RN example

dangerfile.js
**Summary**
Uses relative import for lodash instead of global imports
**Test plan**
Works on my machine ;)
=> [Danger] node 4 lodash fix

packages/jest-cli/src/runTest.js
**Summary**
Resolve #2166.
**Test plan**
Tested on example from #2166 and it works as expected. If someone is knowing how to check it with unit tests - I can add tests.
=> Fix immediate execution for test result

dangerfile.js
**Summary**
Converts the flow check to only run on new js files that are not inside tests or mocks. Minor refactors too.
**Test plan**
This should green, did a quick local test too 👍 
Fixes #2563
=> [Dangerfile] Loosen the Flow check to just app files

package.json
**Summary**
Collect coverage only from `jest-*`, `eslint-*` and `pretty-format` packages, as the rest (`babel-*`, `jest`) is tested through integration tests hence not covered in the report
=> Collect coverage from jest-* eslint-* and pretty-format

packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-snapshot/src/__tests__/matcher-test.js
**Summary**
Tests for https://github.com/facebook/jest/pull/2198 and https://github.com/facebook/jest/pull/2342 as discussed at https://github.com/facebook/jest/pull/2342#issuecomment-267585515
=> Add matcher result tests

integration_tests/runJest.js
**Summary**
Fix spelling error in test file.
**Test plan**
No test necessary. Change is contained in a comment.
=> Fix spelling error

packages/jest-mock/src/__tests__/jest-mock-test.js, packages/jest-mock/src/index.js
As instructed on https://twitter.com/cpojer/status/818220253696106496
=> [spyOn] Call previous function as well

docs/MigrationGuide.md
just one more paren =P
**Summary**
Just one paren typo. Currently displaying "If you are using Mocha), AVA, chai or Tape, ..."
**Test plan**
=> Fix typo in MigrationGuide.md

CONTRIBUTING.md
**Summary**
> It is recommended to use npm3.
* This made me stop to think. The intended meaning is not to use **version 2**, but **version 4** is okay?
* Also replaced passive with **active voice**. The Microsoft Manual of Style recommends this as a rare situation to write in the first person (plural).
* Looks like (yet again) my editor config removed some **trailing spaces** when I saved the file. Glad to know your opinion whether I should turn off that option.
**Test plan**
Please someone who knows for sure to review.
=> Docs: recommend npm version 3 or later in CONTRIBUTING.md

packages/jest-validate/src/__tests__/__snapshots__/validate-test.js.snap, packages/jest-validate/src/__tests__/validate-test.js, packages/jest-validate/src/exampleConfig.js, packages/jest-validate/src/utils.js
**Summary**
Fixes #2610 
Before:
After:
**Test plan**
jest
=> Print jest-validate functions with .toString()

website/siteConfig.js
This is kind of critical for Jest's ongoing success.
=> Add the joker.

integration_tests/__tests__/__snapshots__/globals-test.js.snap, integration_tests/__tests__/globals-test.js, packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/constants.js, packages/jest-cli/src/reporters/VerboseReporter.js
**Summary**
Resolve #2169
**Test plan**
Works on local machine and added unit tests are passed.
**Preview**
=> Filter skipped tests for verbose reporter

dangerfile.js
**Summary**
Fixes danger not correctly skipping __tests__.
**Test plan**
Works on my machine.
=> exclude __tests__ and __mocks__ from flow

packages/jest-cli/src/patternMode.js, packages/jest-matchers/src/__tests__/asymmetric-matchers-test.js
**Summary**
Fixes lint errors and warnings
**Test plan**
`jest patternmode` `jest asymmetric-matchers-test.js`  and `yarn lint`
=> Fixes eslint errors and warnings

website/core/nav/HeaderNav.js, website/src/jest/css/jest.css
**Summary**
Partially fixes #2656 (nav only)
=> New mobile nav

packages/jest-changed-files/src/git.js
=> "options" argument to findChangedFiles made optional

packages/jest-cli/src/cli/index.js, packages/jest-config/src/validConfig.js, packages/jest-repl/src/cli/index.js, packages/jest-runtime/src/cli/index.js, packages/jest-util/package.json, packages/jest-util/src/__tests__/__snapshots__/validateCLIOptions-test.js.snap, packages/jest-util/src/__tests__/validateCLIOptions-test.js, packages/jest-util/src/index.js, packages/jest-util/src/validateCLIOptions.js, packages/jest-validate/src/index.js
**Summary**
Fixes #2599 
Preview:
**Test plan**
Needs tests.
=> Throw error for invalid CLI config

docs/TutorialWebpack.md, website/layout/RedirectLayout.js, website/src/jest/support.js
Fixes #2276
- Added redirect, support.html to help.html
=> Implement RedirectLayout

docs/Configuration.md
**Summary**
Fix [configuration](https://facebook.github.io/jest/docs/configuration.html#transform-object-string-string) pages missing link.
**Test plan**
No because documentation fix only.
=> Fix documation example/typescript links

packages/jest-util/package.json
**Summary**
Drops the `diff` dependency from `jest-util`.  It doesn't seem to be used there, nor does it seem to be a peerDependency of anything there.
**Test plan**
=> Remove `diff` from `jest-util`.

examples/snapshot/__tests__/__snapshots__/Link.react-test.js.snap
**Summary**
Missed that. This time whole `yarn test` passes.
**Test plan**
=> Fix snapshot example

packages/jest-cli/package.json, packages/jest-config/package.json, packages/jest-runtime/package.json, yarn.lock
**Summary**
Drops `json-stable-stringify` from `jest-cli`, `jest-config`, and `jest-runtime`.  They don't seem to be used, or be peerDependencies.
**Test plan**
=> Drop `json-stable-stringify`.

packages/jest-cli/package.json
**Summary**
Drops `sane` from `jest-cli`.  It doesn't seem to be used there, or be a peerDependency.
**Test plan**
=> Remove `sane` from `jest-cli`.

website/core/home/HomeSplash.js
**Summary**
Removes the `mostRecent` and `mostRecentContent` declarations from `HomeSplash`.  They weren't used.
**Test plan**
=> Remove `mostRecentContent` from `HomeSplash`.

packages/jest-cli/package.json, packages/jest-resolve/package.json
**Summary**
Drops `jest-file-exists` from `jest-cli` and `jest-resolve`.  It doesn't seem to be used by either.
**Test plan**
=> Remove `jest-file-exists` from `jest-cli` and `jest-resolve`.

circle.yml
Deploy website from master using CircleCI. Do not merge until we're ready to release the new website refresh.
=> [Do Not Merge] Restore CircleCI builds from master.

packages/jest-runtime/package.json
**Summary**
Remove `jest-config` from the `devDependencies` of `jest-runtime`.  It's already in `dependencies`.
**Test plan**
=> Remove devDependency `jest-config` from `jest-runtime`.

packages/jest-cli/package.json
**Summary**
Drops `strip-ansi` from `jest-cli`.  It's only used in a test.
**Test plan**
=> Drop `strip-ansi` from `jest-cli`.

packages/jest-matchers/package.json
**Summary**
Drops `pretty-format` from `jest-matchers`.  It doesn't seem to be used there, or be a peerDepndency.
**Test plan**
=> Remove `pretty-format` from `jest-matchers`.

docs/Configuration.md
=> Fixed "See also testMatch" link

docs/TutorialAsync.md
**Summary**
Current example checks only the error message, the test will pass if there was no error thrown. 
**Test plan**
The pattern is checked on personal projects.
=> check that promise actually throws in TutorialAsync.md examples

packages/jest-runtime/package.json
**Summary**
Drops `jest-snapshot` from `jest-runtime`.  It doesn't seem to be used thre, or be a peerDependency.
**Test plan**
=> Remove `jest-snapshot` from `jest-runtime`.

docs/SnapshotTesting.md
**Summary**
http://facebook.github.io/jest/blog/2016/10/03/jest-16.html
> We removed function names from snapshots.
**Test plan**
Your clear mind and sharp eyes, friendly reviewer :)
=> Docs: omit function name in SnapshotTesting.md

examples/async/__tests__/user-test.js
**Summary**
Apply changes from #2782 to example files. 
**Test plan**
Manually tested
=> Enhance async examples

docs/Configuration.md, docs/ExpectAPI.md
**Summary**
Also change wording
=> Add availability note on testMatch

packages/eslint-config-fb-strict/package.json
**Summary**
Removes `eslint` from the `dependencies` of `eslint-config-fb-strict` and adds it as a peerDependency.  I believe this is breaking.
**Test plan**
Outside of breaking if `eslint` is not in the dependency tree, nothing should change.
=> Make `eslint` a peerDependency for `eslint-config-fb-strict`.

CONTRIBUTING.md
**Summary**
It may be confusing for users to clone from jest repo instead of a fork.
=> Update clone link in CONTRIBUTING.md

packages/jest-editor-support/README.md, packages/jest-editor-support/package.json
**Summary**
TypeScript is a 20Mb dependency of editor-support, this should allow using editor-support without TypeScript and not incur into any penalties.
A better way to do this will be to require to pass a parser to editor-support.
**Test plan**
=> Making TS a peer dependency

packages/babel-jest/src/index.js
**Summary**
* Does not add `istanbul ignore next` comments if you're not instrumenting.
* The transform cache key now depends on `bebel-jest` itself as well.
* `babel-core` is lazily loaded - so if you have a fully primed cache, you never load babel.
**Test plan**
`npm test`.
Used it in a project.
=> Only set necessary babel opts in babel-jest

lerna.json, package.json, packages/babel-jest/package.json, packages/jest-cli/src/lib/__tests__/formatTestNameByPattern-test.js, packages/jest-cli/src/lib/setState.js, packages/jest-config/package.json, packages/jest-config/src/__tests__/normalize-test.js, packages/jest-environment-jsdom/package.json, packages/jest-haste-map/package.json, packages/jest-haste-map/src/crawlers/watchman.js, packages/jest-jasmine2/src/jasmine-async.js, packages/jest-jasmine2/src/jest-expect.js, packages/jest-runtime/package.json, packages/jest-util/package.json, packages/jest-validate/package.json, packages/pretty-format/package.json, yarn.lock
**Summary**
* Updates dependencies to their latest versions.
* Flow at FB is at 0.39 and was showing errors for people, this fixes up some types.
**Test plan**
* yarn test
* running the normalize test in isolation would throw.
=> Update deps, small cleanups, fix flow.

packages/jest-diff/src/index.js, packages/jest-matchers/src/asymmetric-matchers.js
**Summary**
In response to https://github.com/facebook/jest/pull/2878#issuecomment-279711868
**Test plan**
Tests added in #2878 still pass
=> In AsymmetricMatcher rename expectedType method as getExpectedType

packages/jest-cli/src/__tests__/watch-test.js, packages/jest-cli/src/watch.js
**Summary**
Fix passing testPathPattern from cli to the watch mode.
**Test plan**
I wrote tests for that and checked on the local machine.
=> Fix passing testPathPattern in watch mode

packages/jest-cli/src/TestNamePatternPrompt.js, packages/jest-cli/src/__tests__/__snapshots__/watch-test-name-pattern-mode-test.js.snap
**Summary**
Polish up usage messages for test name pattern mode.
**Test plan**
=> Polish up usage messages for test name pattern mode

circle.yml
don't run circle when commits are made to gh-pages branch
=> ignore gh-pages

packages/jest-cli/src/TestNamePatternPrompt.js, packages/jest-cli/src/TestPathPatternPrompt.js, website/siteConfig.js
**Summary**
Just driving by, fixing up master.
**Test plan**
yarn test
(this is broken because travis is so slow I yolomerge everything)
=> Unbreak master.

packages/jest-snapshot/src/__tests__/utils-test.js, packages/jest-snapshot/src/utils.js
**Summary**
Simplify `getSnapshotData()` by avoiding unnecessary `try/catch`, as advised here: https://github.com/facebook/jest/pull/2896/files/165e0a6a75b6356aa234b049ea71e6a8598305d5#r101520015
**Test plan**
jest
=> Snapshot version followup refactor

CHANGELOG.md
=> Update Jest 19 changelog

packages/jest-cli/src/TestNamePatternPrompt.js, packages/jest-cli/src/TestPathPatternPrompt.js, packages/jest-cli/src/__tests__/__snapshots__/watch-filename-pattern-mode-test.js.snap
=> Align pattern mode usages

packages/jest-editor-support/src/TestReconciler.js, packages/jest-editor-support/src/types.js, website/siteConfig.js
**Summary**
It's reconciliation, not reconcilation.
**Test plan**
flow
=> Fix typo in jest-editor-support type.

packages/jest-snapshot/src/__tests__/utils-test.js, packages/jest-snapshot/src/utils.js
**Summary**
@thymikee I changed my mind. I hope you are ok with this.
**Test plan**
yarn test
=> * “people on” -> “users of”

packages/jest-snapshot/package.json, packages/jest-snapshot/src/__tests__/utils-test.js, packages/jest-snapshot/src/utils.js
**Summary**
Add a little colours to these sad errors!
**Test plan**
jest
=> Snap version colors

website/siteConfig.js
The entries should be in alphabetical order, with some exceptions (first few entries up through Cisco's are pinned to the top intentionally, due to recognizability of these companies).
=> Alphabetize users in the showcase

packages/jest-cli/src/__tests__/SearchSource-test.js
**Summary**
Fix unhandled promise rejection by returning a Promise from SearchSource tests
**Test plan**
jest
=> Handle async tests properly for SearchSource

docs/JestObjectAPI.md
**Summary**
Feel free to adjust the description
cc: @cpojer
=> Add jest.spyOn to documentation

packages/jest-cli/src/TestWorker.js
**Summary**
We weren't removing disconnect event listeners. This approach may be more verbose than what's possible but this is a quick fix and we don't have Promise.finally so I didn't wanna get all confused ;)
**Test plan**
When running Jest on the jest repo, see no more "RUNS" leftovers at the end of a test run.
=> Clean up listeners properly.

packages/eslint-plugin-jest/src/index.js
Greetings,
this fixes issue #2953
=> Fix ESLint plugin recommended config

packages/jest-cli/src/lib/__tests__/isValidPath-test.js
Fixes a failing test Windows introduced by #2963
=> Fix isValidPath failing Windows test

packages/babel-jest/package.json
**Summary**
Add description to babel-jest package.json. This is shown on yarnpkg.com and npmjs.com. Most of the other packages also miss the description
=> chore(babel-jest): add description to package.json

README.md, docs/CLI.md, docs/GettingStarted.md
**Summary**
Fixes #2530 
**Test plan**
pictures!
=> Explain various ways of how to use Jest from CLI

CONTRIBUTING.md
**Summary**
Adding the directions for the additional workflow to be followed, if changes are made to the Website or Documentation in [CONTRIBUTING.md](CONTRIBUTING.md). This will save maintainers in providing out directions again, in case some issue occurs with PR. Thanks! Emerged from my discussion with Dmitrii [here](https://github.com/facebook/jest/pull/3023#issuecomment-283163149) 
**Test plan**
Not needed
=> add directions for changes made to website in CONTRIBUTING.md

packages/jest-cli/src/cli/args.js, packages/jest-cli/src/cli/index.js
**Summary**
Add link to documentation when running `jest help`
**Test plan**
=> Add documentation note in help menu

docs/MockFunctionAPI.md
**Summary**
Added some clarifications to the mock function API docs where the existing documentation was incomplete or misleading.
**Test plan**
N/A
=> Adds some clarifications to mock function API docs

packages/jest-jasmine2/src/jasmine-async.js
This PR is a spin-off of #2903.
**Summary**
Cleans the code, so the two functions promisifying both `it` (`fit`, `test` etc.) and lifecycle functions (`beforeAll`, `afterAll`, `beforeEach`, and `afterEach`) follow the same conventions.
The code is repeated, however [duplication is far cheaper than the wrong abstraction](https://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction).
**Test plan**
`yarn test` passes
=> Cleanup promisify of test and lifecycle functions

.vscode/settings.json, docs/ExpectAPI.md, packages/jest-matchers/src/__tests__/matchers-test.js, packages/jest-matchers/src/matchers.js
**Summary**
Documents `.toHaveProperty` matcher in the Expect API Document. The reference for matcher can be found at this [line](https://github.com/facebook/jest/blob/master/packages/jest-matchers/src/matchers.js#L456). Thank you! 
**Test plan**
Code makes a change to the documentation. Doesn't make any code changes.
=> Document `.toHaveProperty` matcher in Expect API Doc

scripts/postinstall.js
**Summary**
Locally on MBP 15 it's `41.98s` vs `18.63s`
**Test plan**
CI passes
=> Set lerna concurrency to 1 only on CI

package.json
**Summary**
Same as the script in the OP of #3057
Mostly so I can run it when doing changes to the code base
**Test plan**
Run it? 😄
=> Add prettier script to root package.json

package.json, yarn.lock
**Summary**
This version drops lots of deps, see yarn.lock
**Test plan**
jest
=> Bump eslint-plugin-markdown to v1.0.0.beta-4

docs/TutorialReact.md
**Summary**
Fix link to getting started documentation.
=> Fix bug in TutorialReact.md

integration_tests/__tests__/auto-clear-mocks-test.js, integration_tests/__tests__/auto-reset-mocks-test.js, integration_tests/__tests__/config-test.js, integration_tests/__tests__/resolve-test.js, integration_tests/__tests__/runtime-internal-module-registry-test.js, integration_tests/__tests__/set-immediate-test.js, integration_tests/__tests__/setup_test_framework_script_file_cli_config-test.js, integration_tests/__tests__/snapshot-serializers-test.js, integration_tests/__tests__/snapshot-test.js, integration_tests/__tests__/test-environment-test.js, integration_tests/__tests__/testNamePattern-test.js, integration_tests/__tests__/timer-resetMocks-test.js, integration_tests/__tests__/toThrowErrorMatchingSnapshot-test.js, integration_tests/runJest.js
**Summary**
Uses `cross-spawn` for integration tests.  This allows some integration tests to be run on Windows.
**Test plan**
=> Use `cross-spawn` in integration tests.

packages/jest-util/src/__tests__/FakeTimers-test.js
**Summary**
Removes the `skipOnWindows` call in `FakeTimers-test`.
**Test plan**
Nothing should change.  AppVeyor should still pass.
=> [jest-util] Run `FakeTimers-test` on Windows.

.flowconfig, package.json, yarn.lock
**Summary**
* Upgrade to the latest flow.
* Add the `[version]` config to `.flowconfig` to ensure that the right flow version is used.
**Test plan**
`flow`
=> Upgrade to flow 0.41.0

packages/jest-jasmine2/src/setup-jest-globals.js
**Summary**
Fixes snapshots on Node 4.
**Test plan**
Circle CI pass
=> Use function instead of arrow for addAssertionErrors

docs/GettingStarted.md
=> 📝 install jest types for TypeScript

packages/jest-cli/src/runTest.js, packages/jest-runtime/src/index.js, packages/jest-runtime/src/transform.js
**Summary**
Fixes #3060
**Test plan**
We may want to add an integration test for this.
=> Cache reading of test file to avoid duplicate calls

docs/CLI.md
**Summary**
Fix a typo in the docs
=> fix typo in the docs for --no-cache

integration_tests/__tests__/empty_suite_error-test.js, integration_tests/__tests__/env-test.js, integration_tests/__tests__/jasmine_async-test.js, integration_tests/__tests__/json_reporter-test.js, integration_tests/__tests__/no-test-found-test.js, integration_tests/__tests__/stack_trace-test.js, integration_tests/__tests__/test-in-root-test.js, integration_tests/__tests__/testResultsProcessor-test.js, integration_tests/__tests__/toMatchSnapshot-test.js, integration_tests/__tests__/verbose-test.js
**Summary**
Enables some integration tests that can run on Windows without any changes.
**Test plan**
Nothing should change.  AppVeyor should report 81 tests being skipped instead of 112.
=> Run more integration tests on Windows.

packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/reporters/VerboseReporter.js
**Summary**
This is necessary for #3156, so I'm just pulling it out into a separate PR so we can get it in today.
**Test plan**
jest
=> Don’t pass config to the VerboseReporter.

docs/ExpectAPI.md
**Summary**
I was helping someone get started with Jest and they didn't find this helper cause they were searching for the word "deep" since it's a common term to refer to this behavior. Adding the keyword "deep" will help people find and understand what this does.
**Test plan**
n/a
=> Clarify that toEqual is sometimes known as "deep"

docs/Configuration.md
=> Add availability note to resolver option

packages/jest-jasmine2/src/__tests__/p-timeout-test.js, packages/jest-jasmine2/src/__tests__/queueRunner-test.js, packages/jest-jasmine2/src/expectationResultFactory.js, packages/jest-jasmine2/src/p-timeout.js, packages/jest-jasmine2/src/queueRunner.js
**Summary**
This is the result of running `yarn prettier`. 
Confusing to see lint errors the first time you run the test suite after cloning the project.
**Test plan**
CI & `yarn test`
=> fix linting

packages/jest-jasmine2/src/queueRunner.js
**Summary**
Replace `...args` with function call to `arguments`
**Test plan**
CI green
=> Get rid of spread to fix node 4

docs/GettingStarted.md
This PR aims to fix documentation due to missing curly braces in a json snippet.
=> fix json content

.eslintrc
Ref: t17052325, t17052384, t17052168
Lint rules passed anyway.
=> Add stricter flow lint rules

docs/TestingAsyncCode.md
=> Add back docs for the old way of testing promises

website/core/center.js
**Summary**
A lint error occurs as a `props` never get reassigned within `website/core/center.js` and the variable for it is declared using a `let`, which leads to a lint error and tests not getting passed 100% within the application. I have made a slight change in `website/core/center.js` on how we are using the `let` and `const` within our application. 
**Test plan**
This PR solves a lint error, and doesn't make any change to the UI or output in any way.
=> Fix Lint Error in `website`

packages/jest-jasmine2/src/assert-support.js
**Summary**
Fixes flow
**Test plan**
Flow green
=> Fix flow for assert-support

docs/Troubleshooting.md
I missed this section before because I kept searching for "CI"
=> Add CI keyword to title so it comes up in search

docs/TutorialAsync.md
Reduces requirements for this feature to work.
Touches docs.
=> Update TutorialAsync.md to use 'env' preset

integration_tests/__tests__/showConfig-test.js, packages/jest-cli/src/lib/__tests__/logDebugMessages-test.js, packages/jest-cli/src/lib/logDebugMessages.js, packages/jest-jasmine2/src/treeProcessor.js
**Summary**
Cleaned up a few things I wasn't super happy with.
**Test plan**
jest
=> Minor lint fixes.

packages/eslint-plugin-jest/src/rules/__tests__/valid-expect-test.js, packages/eslint-plugin-jest/src/rules/types.js, packages/eslint-plugin-jest/src/rules/valid-expect.js
**Summary**
Second part of #3082. Again I'm bested by a Flow error... Ideas for the ignore?
**Test plan**
N/A
=> Add better location to valid-expect

packages/eslint-plugin-jest/src/rules/valid-expect.js, scripts/test_examples.js
**Summary**
The examples are now run using the multi-project runner, which serves as an integration test.
**Test plan**
yarn test-examples
=> Use multi project runner for examples.

packages/jest-haste-map/src/index.js, types/HasteMap.js
Replaces Object, any or Function types with stronger types
=> Strengthening flow types

packages/jest-config/src/defaults.js
**Summary**
In the interest of time, I skipped CI on @jeanlauliac's diff. I fixed it up to make flow and eslint happy. We need to ship this at FB asap.
**Test plan**
jest
=> Lint fixes.

circle.yml, website/core/nav/HeaderNav.js, website/siteConfig.js
Have been having an issue where the website build step does not run unless deployed on a master branch.
I have moved the website build code into the test step to allow final configuration changes to the website build process.
Please do not accept this PR until then.
Update: Build properly configured.
=> Forcing Circle to run website build step, but not commit

crowdin.yaml
Added missing crowdin.yaml configuration environment variable.
=> Crowdin environment error wasn't caught by Circle.

packages/jest-cli/src/lib/logDebugMessages.js, packages/jest-cli/src/runTest.js, packages/jest-runtime/src/cli/index.js, types/Environment.js, types/TestRunner.js
**Summary**
This makes dynamic requires be typed properly and connects different packages in Jest better.
**Test plan**
flow
=> Strict types

docs/MockFunctionAPI.md
**Summary**
Documenting an undocumented function.
`mockFn.mockRestore` has been used in one example but not documented. 
**Test plan**
N/A
=> Document mockFn#mockRestore.

packages/babel-plugin-jest-hoist/src/index.js, packages/jest-changed-files/src/git.js, packages/jest-changed-files/src/hg.js, packages/jest-changed-files/src/index.js, packages/jest-cli/src/SearchSource.js, packages/pretty-format/src/plugins/ReactElement.js, packages/pretty-format/src/plugins/ReactTestComponent.js
**Summary**
Couple of files were not covered by Flow (took them from https://github.com/facebook/jest/issues/3169 but not all)
**Test plan**
CI
=> Add flow to uncovered files

.flowconfig
**Summary**
Fixes flow typecheck
**Test plan**
yarn lint
=> Exclude conventional-changelog-core from flow typecheck

packages/jest-config/src/normalize.js
**Summary**
Easy fix, tough debugging.
=> Fix watch not being normalized

packages/jest-phabricator/README.md
The unit_engine option should be unit.engine
**Summary**
Fixed typo, unit_engine should be unit.engine
**Test plan**
No testing needed
=> Fixed typo

website/core/nav/SideNav.js, website/i18n/en.json
Fixes: https://github.com/facebook/jest/issues/3453
**Summary**
Defaults the string in sidebar to the one in the document's frontmatter. This will default rendering strings that haven't been included yet in the i18n/en.json file as English.
=> Sidebar: Default to current title stored in document front matter

website/core/nav/HeaderNav.js, website/src/jest/css/jest.css
**Summary**
Moving the Languages drop down from far left.
**Test Plan**
Verified by building site locally.
=> Move Language drop down to left of Search Bar

integration_tests/__tests__/toMatchSnapshot-test.js, integration_tests/__tests__/toThrowErrorMatchingSnapshot-test.js, package.json, packages/jest-cli/src/TestNamePatternPrompt.js, packages/jest-cli/src/TestPathPatternPrompt.js, packages/jest-cli/src/reporters/utils.js, packages/jest-cli/src/runJest.js, packages/jest-config/src/normalize.js, packages/jest-config/src/utils.js, packages/jest-editor-support/src/__tests__/TestReconciler-test.js, packages/jest-snapshot/src/utils.js, packages/jest-validate/src/__tests__/fixtures/jestConfig.js, packages/pretty-format/src/__tests__/AsymmetricMatcher-test.js, packages/pretty-format/src/__tests__/ConvertAnsi-test.js, scripts/prettier.js, yarn.lock
It didn't revert cleanly, but I _think_ this is correct 😄
/cc @vjeux
=> Use prettier 1.3.1

website/i18n/en.json
**Summary**
This fixes #3466. I was wanting to learn more about Jest this morning and saw that the descriptions of the two sections were the same. I assumed they shouldn't be and found the former version of the description.
**Test plan**
N/A, just a string change.
=> fix homepage documentation regression

website/src/jest/css/jest.css
**Summary**
Fixes the dropdown box so it renders at proper location on web and mobile.
=> Fix drop down box on mobile and web

README.md, website/core/JestIndex.js, website/core/home/HomeSplash.js, website/i18n/en.json
**Summary**
Let's promote @rogeliog's work a little bit more on the front page ;)
**Test plan**
=> Add “Watch Talks” to the Jest website.

website/server/convert.js
**Summary**
When you click button CONTINUE READING and PREVIOUS it will redirect you to Page Not Found.
**Test plan**
=> Fix pagination page not found

website/layout/DocsLayout.js, website/server/convert.js
revert changes in https://github.com/facebook/jest/pull/3480 and provide a quickfix for the issue that was being fixed there
=> fix navigation related issue

website/server/convert.js, website/server/generate.js, website/server/server.js, website/server/translation.js, website/server/translationPre.js
**Summary**
Localized base folders weren't being converted (es-ES).
Due to how files and folders get removed prior to building webpages the base localization folder wasn't being created prior to being converted into html. This PR aims fixes that.
**Test plan**
Run through build process, check that Spanish landing page loads.
=> Resolving race condition in website build process for localized base folders

README.md, website/server/convert.js
**Summary**
Fixes: #3488 - This PR should hide the markers we use to insert the GettingStarted.md into the README.md file.
**Test plan**
=> Changes README's generated markers to html comments

CHANGELOG.md, blog/2017-05-06-jest-20-delightful-testing-multi-project-runner.md
**Summary**
Couple of stylistic adjustments to blog post and changelog. Also changed collapsing watch mode from bugfix to new feature.
=> Jest 20 blog post and changelog adjustments

website/languages.js
**Summary**
The Portuguese Brazilian community has worked hard to get the majority of translation work done! I am excited to switch this on!
**Test Plan**
This change enables the processing of pt-BR language files from Crowd In. No test is needed, but a manual check will be performed.
=> Enabling Portuguese Brazilian

website/core/Site.js
**Summary**
Exposes translated tagline on landing pages
**Test plan**
Verified by manually checking 'yarn test' build files for /index.html /en/index.html /pt-BR/index.html and /docs/pt-BR/timer-mocks.html
=> Exposing the localized tagline as the page's title

packages/babel-jest/src/index.js
**Summary**
Typo in PACAKAGE_JSON
**Test plan**
Verified manually testing
=> fix PACKAGE typo

docs/en/ExpectAPI.md
Fixes #3529
**Summary**
**Test plan**
=> Updating docs for `.toEqual`

examples/jquery/__tests__/fetchCurrentUser-test.js
**Changing current example (jQuery test) for simplify the understanding**
**The motivation for this change is why the output for current example (in verbose mode) is very strange**
**N/A**
=> Update fetchCurrentUser-test.js (jQuery Example)

docs/en/GettingStarted.md
cc @cpojer
**Summary**
The instructions for installing via Yarn are slightly different than with npm. This meanwhile also gives a backlink to the detail page on Yarn, as discussed
=> docs(gettingStarted): add Yarn install

.vscode/extensions.json, .vscode/settings.json
+ recommends some extensions which cover the features of the codebase
**Summary**
Improves the default experience when using vscode in the codebase, @thymikee am I missing anything interesting?
**Test plan**
I used it. 👯‍♂️ 👯
=> [Dev] Improves the VS Code default settings,

.vscode/settings.json
**Summary**
This will set the project settings for prettier to be the same as Jest's - continuing #3592 
**Test plan**
"Works on my computer"
=> [Dev] Adds prettier defaults for VS Code

packages/jest-haste-map/src/__tests__/index-test.js
I'd like to fix the problems we've had with jest not recovering from module duplication. As a first step, I propose we refactor the unit test a little bit so that it's easier to add new new tests. This is two-fold. First, I switched functions over to `async`/`await`, making it easier to read and to reduce nesting. Second, I wrote a wrapper for `it()` so that we can write each watch-mode test in separate jest test case. That'll gives us better reporting when things break, if they do, and does not really increase complexity, as you can see.
This changeset only switches over the very first test case. I'd like to get approval of that technique first, and I'll switch the remaining tests in a separate changeset.
**Test plan**
I ran:
node ./packages/jest-cli/bin/jest.js …
=> jest-haste-map: simplify watch-mode test structure

danger/README.md
**Summary**
Changing occured to occurred.
**Test plan**
No test plan needed.
=> Fix typo. in README.md

packages/jest-config/src/reporterValidationErrors.js
It was only a comment so no worries
**Summary**
**Test plan**
=> added an 'l' to Vaidation

packages/jest-editor-support/src/parsers/BabylonParser.js
small typos in comments.
**Summary**
Fixing a couple typos in the comments 
**Test plan**
get some human eyes to verify 😄
=> Fixing typos

website/i18n/en.json
**Summary**
Fix minor typo on the homepage
=> fix minor typo

packages/jest-editor-support/src/parsers/BabylonParser.js
**Summary**
I can fix spelling mistakes and I am a pro in git.
**Test plan**
I write perfect code, just kidding - there's nothing like that in the world.
=> Changed expetected spelling

danger/README.md, packages/jest-config/src/reporterValidationErrors.js, packages/jest-config/src/vendor/jsonlint.js
**Summary**
Fix a typo. Change retreive to retrieve.
**Test plan**
No tests needed.
=> Fix retrieve typo

packages/jest-resolve/src/index.js
**Summary**
This change is to strengthen the flow types of a particular file in an effort to eventually enable stricter ESLint rules found in https://github.com/facebook/jest/pull/3300.
**Test plan**
All tests pass.
=> Strengthen flowtypes for file 'jest/packages/jest-resolve/src/index.js'

docs/en/Configuration.md
**Summary**
Fix unexpected comma
**Test plan**
None
=> [docs] Fix typo in reporter example

docs/en/MockFunctions.md
This helps with #3627 
Consider it a work in progress for feedback 😄
=> Add an example of using a mock function in a test.

docs/en/TestingFrameworks.md
**Summary**
Added web components test example
**Test plan**
Following the article provided in the pr test output
=> Testing WebComponents with Jest and Webpack

fixtures/parserTests.js, packages/jest-cli/src/runJest.js, packages/jest-cli/src/watch.js, packages/jest-editor-support/src/parsers/BabylonParser.js, packages/jest-environment-node/src/index.js, packages/jest-util/src/FakeTimers.js
**Summary**
This change is to strengthen the flow types of a particular file in an effort to eventually enable stricter ESLint rules found in https://github.com/facebook/jest/pull/3300.
**Test plan**
All tests pass.
=> Strengthen flow types in a few more modules

docs/en/Troubleshooting.md, integration_tests/__tests__/__snapshots__/timeouts-test.js.snap, integration_tests/__tests__/timeouts-test.js, packages/jest-cli/src/__tests__/SearchSource-test.js, packages/jest-runtime/src/index.js, testSetupFile.js
i'm cleaning up Jasmine references form our codebase so it's easier to switch to another framework in the future.
=> jest.setTestTimeout

docs/en/JestObjectAPI.md
**Summary**
This is to document a new method so consumers will know it exists.
**Test plan**
This is just documentation so there isn't any code to test.
=> Document jest.setTestTimeout()

website/translators.txt
Add Marcelo Dapper (mdapper) as a translator for Portugese, Brazilian
**Summary**
**Test plan**
=> Add translator name for Portugese, Brazilian

website/translators.txt
**Summary**
Added my name into the translator list.
**Test plan**
N/A
=> Added my name into the translator list

website/languages.js
**Summary**
the word "中文" represent all types of **zh** (both zh-Hans and zh-Hant) canonically. "简体中文" is better for zh-Hans.
**Test plan**
Nothing but one word change (indentation by the way).
=> [WebSite] Normalize language title about zh.

examples/snapshot/package.json, packages/babel-jest/src/index.js
fix issue: https://github.com/facebook/jest/issues/3736
=> add source map support for better debugging experience

website/translators.txt
Added my name along with the handle on the translator list.
=> Added my name on translator list

packages/jest-runtime/src/ScriptTransformer.js
very small thing, but super confusing when trying to debug transform/coverage logic
=> refactor shouldInstrument()

website/translators.txt
**Summary**
- Changing Portugese to Portuguese.
- Removing duplicate reference to @mdapper
**Test plan**
- No test plan needed.
=> Removing duplicate translator and Fix typo

examples/typescript/package.json
**Summary**
Without this dependency, typescript complains that `it`, `test`, `expect` etc. are not defined.
**Test plan**
I included this dependency, and it worked for me.
=> Include jest types in typescript example

docs/en/TutorialReactNative.md
This is just a minor fix in sentence structure.
=> Fix grammar in React Native docs

integration_tests/__tests__/__snapshots__/custom-reporters-test.js.snap, integration_tests/custom_reporters/reporters/TestReporter.js, packages/jest-cli/src/TestRunner.js, packages/jest-cli/src/reporters/SummaryReporter.js
https://github.com/facebook/jest/pull/3828#event-1124892898
=> make reporter options to be consistent between default and custom reporters

packages/jest-jasmine2/package.json, packages/jest-jasmine2/src/queueRunner.js
https://github.com/facebook/jest/pull/3594
=> remove `once` package

.flowconfig, package.json, yarn.lock
**Summary**
Just a version bump.
=> Bump Flow to 0.48

packages/jest-snapshot/src/__tests__/utils.test.js, packages/jest/bin/jest.js, packages/pretty-format/perf/test.js
**Summary**
I noticed #3786 had some conflicts. We can land a couple of the changes in that PR to avoid conflicts later.
**Test plan**
Tests should pass
=> Land parts of #3786

docs/en/JestObjectAPI.md
**Summary**
Fix `jest.doMock` example to call `jest.resetModules` after each test.
**Test plan**
Without calling `resetModules` multiple `doMock` calls won't work, only the first one would be applied. https://github.com/facebook/jest/issues/2649#issuecomment-311328129
=> Fix doMock example

packages/jest-cli/src/reporters/__tests__/default_reporter.test.js
Reverts facebook/jest#3946 (1)
=> Revert "Fix linting"

.eslintrc.js, packages/jest-matchers/src/matchers.js, website/core/DocsSidebar.js, website/core/Marked.js, website/core/nav/HeaderNav.js
**Summary**
Fix the website
**Test plan**
`npm start` in `/website` should not explode on syntax errors
=> Don't add trailing commas to the webapp

integration_tests/__tests__/only_changed.test.js
highlevel test for `-o` option to make sure the behavior stays the same before i start changing things
=> --onlyChanged tests

docs/en/SnapshotTesting.md
**Summary**
before: this [this egghead video]
after: this [egghead video]
=> Docs: duplicate 'this'

docs/en/ExpectAPI.md
**Summary**
Typo fix
**Test plan**
-
=> Docs: fix typo

docs/en/Troubleshooting.md
Fixes #4004
**Summary**
Adds a note that Travis CI for open source projects only include 2 cores.
**Test plan**
n/a
=> Update Travis CI performance troubleshooting

.flowconfig, package.json, yarn.lock
**Summary**
No changes needed, which is always nice
**Test plan**
`yarn flow`
=> Upgrade flow to 0.50

README.md
**Summary**
I wanted to add the badge to my own repositories, and I thought it was cool to make it easy for everyone to add the badge on their READMEs.
Inspired by [prettier](https://github.com/prettier/prettier).
**Test plan**
Check the README has a badge section.
=> Add Badge section to README

packages/eslint-config-fb-strict/package.json
**Summary**
Trying to update ESLint to version 4 on yarnpkg/yarn and need this update for it to install and work properly.
**Test plan**
N/A
=> Update: Accept ESLint 4 as a peer dependency

packages/eslint-config-fb-strict/package.json
**Summary**
This upgrades eslint-config-fb to the final 2.0.0 version, which fixes support for ESLint 4
**Test plan**
<3 CI
=> Upgrade: eslint-config-fbjs@^2.0.0

packages/jest-cli/src/cli/args.js
**Summary**
This is the fix of the small typo.
**Test plan**
Nothing.
=> Fix small typo in packages/jest-cli/src/cli/args.js

packages/jest-resolve-dependencies/src/__tests__/__fixtures__/node_modules/@myorg/pkg/index.js, packages/jest-resolve-dependencies/src/__tests__/__fixtures__/node_modules/@myorg/pkg/package.json, packages/jest-resolve-dependencies/src/__tests__/__fixtures__/scoped.js, packages/jest-resolve-dependencies/src/__tests__/dependency_resolver.test.js
I thought this would be a failing test. It wasn't. Better to add it to the repo than for me to delete it.
=> Add dependency resolver test for scoped packages

packages/jest-cli/src/test_worker.js
fixes: https://github.com/facebook/jest/issues/4011
=> Fix moduleMap constructor in watch mode

integration_tests/__tests__/force_exit.test.js, packages/jest-cli/src/cli/index.js, packages/jest-config/src/normalize.js
looks like this was broken for a while
=> fix forceExit

docs/en/MockFunctionAPI.md
**Summary**
* Fix sample code of mock class constructors to work.
**Test plan**
=> Fix sample code of mock class constructors documentation

docs/en/Troubleshooting.md
=> Add note on debugging with Node inspector

test_utils.js
both PRs had green builds, but ended up conflicting with each other in master
=> fix flow issue caused by conflicting merges

package.json, yarn.lock
=> Revert "supprots-color@4.2.1"

scripts/build.js
to unblock https://github.com/facebook/jest/pull/4149 to use independent parallelized build for node@4
=> node@4 ./scripts/build

appveyor.yml, packages/jest-cli/src/cli/index.js, packages/jest-config/src/index.js, packages/jest-runtime/src/cli/index.js
based on https://github.com/facebook/jest/issues/4135#issuecomment-318545208
seems like updating yarn fixed the issue. I'm changing the api of `jest-config` package to make sure the integration works
cc @bestander
=> update yarn in appveyor and test if we get packages linked properly

integration_tests/__tests__/log_heap_usage.test.js, packages/jest-cli/src/run_test.js
fixes https://github.com/facebook/jest/issues/4167
=> fix --logHeapUsage

packages/jest-cli/src/run_jest.js
**Summary**
Edit the message displayed when when no test for changed files found
closes #4186
**Test plan**
`yarn test` - all tests passed
=> Add extra info to no tests for changed files message

packages/jest-config/src/defaults.js, types/Config.js
adding anything to `defaults.js` makes it not overwritable :'(
won't write a test cause it's a super edge case
=> fix changedFilesWithAncestor

packages/pretty-format/src/plugins/convert_ansi.js
**Summary**
Remaining work:
* Update README.md with a few more installments
* Research trimming in HTMLElement plugin
* Improve Seq in Immutable plugin
**Test plan**
Existing tests
=> Replace print with serialize in ConvertAnsi plugin

docs/en/CLI.md
This explanation by @thymikee worked like a charm! https://github.com/facebook/jest/issues/3705#issuecomment-312199902
=> Explain how to clear the cache

website/languages.js
Japanese language hit 87% on Crowdin. Enabling.
=> Enabling Japanese!

docs/en/GettingStarted.md
**Summary**
This commit adds a note that explains that you have to re-enable transpiling of modules for your test environment.
I spent about an hour trying to get this to work, but only got compilation errors. This note would've saved me that hour.
=> Add note about enabling module transpilation

docs/en/MockFunctionAPI.md
**Summary**
As per discussion at [https://github.com/facebook/jest/issues/4256](https://github.com/facebook/jest/issues/4256)
need to add: jest.mock('./SomeClass');
**Test plan**
All fine in [repl.it](https://repl.it/KHfC/6)
**Other consideration**
The example here is different in respect with [the API docs](https://facebook.github.io/jest/docs/mock-function-api.html#mockfnmockimplementationfn)
Here it just miss to point on local path
=> mockFn.mockImplementation(fn): fix example

.circleci/config.yml
**Summary**
We're trying to fix website deploy.
**Test plan**
CI for test-and-deploy green
=> Run update method before installing JRE on Circle

packages/pretty-format/README.md
**Summary**
Replaced former **Plugins** section with **Writing plugins**
Last planned doc PR for `pretty-format` in Jest 21
**Test plan**
Second pair of eyes :)
=> Document test, serialize, and print in pretty-format/README.md

packages/jest-phabricator/package.json, packages/jest-util/package.json
**Summary**
From what I can tell these were unused dependencies. Leftovers after refactors?
**Test plan**
`jest`
=> Remove unused deps

docs/en/Configuration.md
A follow-up pull request to #4185 with updates to docs.
=> Updated config doc with info on glob coverage thresholds

integration_tests/__tests__/__snapshots__/list_tests.test.js.snap, integration_tests/__tests__/list_tests.test.js, packages/jest-cli/src/lib/__tests__/is_valid_path.test.js, packages/jest-haste-map/src/__tests__/get_mock_name.test.js, packages/jest-runtime/src/__tests__/runtime_mock.test.js
**Summary**
CI is currently failing in AppVeyor
**Test plan**
It seems that all of them are "path" related.
=> Fix AppVeyor

docs/en/Configuration.md, docs/en/GettingStarted.md, packages/jest-repl/src/cli/args.js
How to use TypeScript + Jest is already documented in ts-jest: a single source of truth with up-to-date documentation always win.
=> Update TypeScript + Jest getting started

package.json, yarn.lock
**Summary**
Noticed the changed `yarn.lock` when installing the repo
**Test plan**
`./jest`
=> Update Jest's own dependency on the eslint plugin

packages/jest-diff/src/diff_strings.js
**Summary**
Improve in small ways now and mainly reduce complexity of code diff in future pull request. 
* For `Diff` replace `{diff: string, isDifferent: boolean}` with `string | null`
* In `formatChunks` and `formatHunks` return if no differences before initializing variables
* In `formatChunks` replace `map` with `reduce` to eliminate some string concatenation and mainly be able in the future to display differences within **adjacent pairs** of removed and added chunks
**Test plan**
Existing tests verify no change to behavior of package.
=> Flatten temporary data structures in jest-diff

packages/jest-mock/src/index.js
**Summary**
Return mock in `mockClear` and `mockReset` to allow chain, e.g. setup right after reset
**Test plan**
```js
const mock = jest.fn();
mock.mockReset().mockImplementation(() => 1);
```
=> Allow chaining mockClear and mockReset

packages/jest-runner/src/run_test.js
**Summary**
fix [issues_4458](https://github.com/facebook/jest/issues/4458).
as @cpojer mentioned I invert the verbose/silent checks 
**Test plan**
=> Fix `--silent --verbose` problem

CHANGELOG.md
**Summary**
I'm not sure if this is wanted. I noticed heading inconsistency when I was reading the changelog. Feel free to reject.
**Test plan**
No change in code.
=> Consistent changelog heading

website/languages.js
**Summary**
This is a single change that will effect the way the website is built. No other change is being made.
=> Enable 'Romanian' language.

docs/en/Configuration.md
=> Missing `or` to clarify the distinct configuration

docs/en/TestingFrameworks.md
**Summary**
Not sure if you want more than one per framework, but figured I'd submit my writeup for integrating AngularJS tests with Jest in case. Thanks!
**Test plan**
Just a docs change
=> Add new AngularJS writeup

packages/jest-config/src/resolve_config_path.js
**Summary**
Bad spelling is bad.
**Test plan**
=> Fixed a minor spelling error

.github/CODEOWNERS
**Summary**
I'm a little confused about why I never get pinged by GitHub - I don't want @cpojer to feel like he has to ping me on every PR, when [GitHub say they](https://help.github.com/articles/about-codeowners/) can do it for him 👍 
**Test plan**
Hope the next one assigns me ;)
=> Update CODEOWNERS for jest-editor-support

packages/jest-editor-support/src/Snapshot.js
**Summary**
Node 4 test suite is broken. Why the Circle CI badge is green in the readme is beyond me 😕 Something odd with Circle 2?
/cc @orta 
fancy
**Test plan**
CI for node 4 should be green.
=> Fix editor support test for node 4

docs/en/MockFunctionAPI.md, docs/en/MockFunctions.md
**Summary** 
See #4646
**Test plan**
Docs only
=> Mock name availability docs

docs/en/TestingFrameworks.md
=> Add Vuejs series testing with Jest

docs/MockFunctions.md
=> Broken link.

.gitignore, docs/TestingFrameworks.md, website/i18n/en.json, website/sidebars.json
**Summary**
This reimplements the sidebar changes from PR #4651, I also cleaned up duplicates from .gitignore.
=> Reimplements sidebar changes from #4651 & Final .gitignore cleanup

docs/CLI.md, docs/Configuration.md, docs/ExpectAPI.md, docs/GettingStarted.md, docs/JestObjectAPI.md, docs/ManualMocks.md, docs/SetupAndTeardown.md, docs/SnapshotTesting.md, docs/Troubleshooting.md, docs/TutorialAsync.md, docs/TutorialReact.md, docs/TutorialReactNative.md, docs/Webpack.md, website/sidebars.json
**Summary**
After #4675, I found more broken links in the documentation site. So I continue to fix it.
I believe this PR also fixes #4679
**Test plan**
=> Fix more broken links in documentation

integration_tests/__tests__/multi_project_runner.test.js, packages/jest-cli/src/run_jest.js
**Summary**
This attempts to fix #4410 by removing duplicates in the output of `--listTests`
**Test plan**
Add new tests provided in #4452
=> remove duplicates in listtest output

.flowconfig, package.json, packages/eslint-plugin-jest/src/rules/no_focused_tests.js, packages/eslint-plugin-jest/src/rules/no_identical_title.js, packages/jest-cli/src/lib/handle_deprecation_warnings.js, packages/jest-cli/src/reporters/coverage_reporter.js, packages/jest-cli/src/test_scheduler.js, packages/jest-cli/src/watch.js, packages/jest-config/src/set_from_argv.js, packages/jest-docblock/src/index.js, packages/jest-editor-support/src/Snapshot.js, packages/jest-haste-map/src/index.js, packages/jest-jasmine2/src/p_timeout.js, packages/jest-jasmine2/src/queue_runner.js, packages/jest-mock/src/index.js, packages/jest-repl/src/cli/repl.js, packages/jest-resolve/src/index.js, packages/jest-runtime/src/index.js, packages/jest-runtime/src/script_transformer.js, packages/jest-worker/src/index.js, packages/pretty-format/src/__tests__/immutable.test.js, packages/pretty-format/src/__tests__/react.test.js, packages/pretty-format/src/index.js, types/HasteMap.js, yarn.lock
**Summary**
We're a bit behind on the flow releases. I'm not really happy that I had to add a bunch of `$FlowFixMe`s, so if someone who knows flow better would go over, that'd be great!
(I was at least able to remove a few old `$FlowFixMe`s).
**Test plan**
`yarn typecheck`
=> Update to flow 0.57.2

website/pages/en/users.js
**Summary**
The URL of `siteConfig.js` is incorrect. There is a risk of editing the `siteConfig.js` of another repository.
**Test plan**
open `http://localhost:8080/jest/users.html`
=> Fix siteConfig.js URL

docs/Configuration.md
Clarify the TestEnvironment usage.
=> Update Configuration.md on Async TestEnvironment API

.github/PULL_REQUEST_TEMPLATE.md
**Summary**
Updating the changelog is always something we have to ask for, and is often forgotten by ourselves as well.
Not sure if this is the correct way of trying to enforce it.
Is danger.js ready? I don't know why it was removed. /cc @orta
EDIT: #3925
**Test plan**
N/A
=> Note the need for changelog update in PR template

.circleci/config.yml, .vscode/settings.json, package.json
**Summary**
Basically update Node and Yarn versions. Also on `circleci/node:8.7.0` container there's already newest yarn installed, so I removed installation steps there.
**Test plan**
CircleCI green
=> chore: update CircleCI config

website/pages/en/index.js
=> fix loading Github button making page jump

docs/MigrationGuide.md
=> Make the github link clickable

flow-typed/npm/jest_v21.x.x.js
**Summary**
The one in the source tree was outdated. I'm not sure of its purpose though, should we just delete it? It was added in #4124
**Test plan**
Green CI
=> Update to jest@21 from flow-typed

integration_tests/request_animation_frame/__tests__/request_animation_frame.test.js, packages/jest-environment-jsdom/src/index.js
Fixes https://github.com/facebook/jest/issues/4779.
Wrote it in the browser, did not test. I think it's right tho.
=> Add a simple cancelAnimationFrame polyfill

.eslintignore, .eslintrc.js, types/HasteMap.js, types/Reporters.js
**Summary**
Noticed `types` directory was not linted when I forgot a semi, and was not yelled at.
**Test plan**
Green CI
=> Lint types/ directory

packages/jest-cli/src/cli/index.js
=> fix unhandled rejection warning

packages/jest-cli/package.json, packages/jest-haste-map/package.json, packages/jest-runner/package.json, yarn.lock
**Summary**
This ensures compatibility with the incoming node@9 (expected today or tomorrow).
See #4731 and linked issues
**Test plan**
Still green CI, can test with node rc locally as well.
=> Force latest version of worker-farm

.travis.yml
**Summary**
PR can be disabled in the Travis UI. Which I've done
**Test plan**
#yolo
=> Only build master branch on travis

.flowconfig, package.json, yarn.lock
**Summary**
It's new and shiny.
Might want to drop the second commit, not sure 🙂  The warnings are nice (especially as unused ignores is now a warning instead of an error), and emojis are sweet, but everybody might not agree
**Test plan**
=> Upgrade to Flow 0.58

docs/Troubleshooting.md
**Summary**
Simply updated the docs...
**Test plan**
Read the docs 😄
=> Fixes #4816 – Updated debugging documentation

docs/JestObjectAPI.md
Update link to MockFunction, issue #4819
=> Update link to MockFunction in the documents

types/TestResult.js
**Summary**
Local `yarn lint` has 1 error and 2 warnings. Fix the error.
**Test plan**
pass CI
=> Fix prettier lint error

CHANGELOG.md
**Summary**
* Add #4669 to CHANGELOG.
**Test plan**
Docs only
=> Fix asynchronous test will fail due to timeout issue.

CODE_OF_CONDUCT.md, CONTRIBUTING.md
**Summary**
Move code of conduct from contributing.md to it's own file in the root of the project. This will complete Jest's community profile on Github [see here](https://github.com/facebook/jest/community)
=> Move code of conduct

package.json, website/README.md, website/package.json, yarn.lock
**Summary**
See #4924
**Test plan**
N/A
=> Include the website as part of yarn workspaces

website/pages/en/help.js
**Summary**
Y’all are building a strong JavaScript Foundation 💛
**Test plan**
yarn lint
=> Fix prettier lint error in website/pages/en/help.js

docs/CLI.md, docs/Configuration.md, docs/JestObjectAPI.md, docs/MockFunctionAPI.md, docs/MockFunctions.md, docs/TimerMocks.md
**Summary**
Ref #4948.
**Test plan**
Docs only
=> docs: change version notices from 21.3.0 to 22.0.0

integration_tests/__tests__/multi_project_runner.test.js, packages/jest-cli/src/get_no_test_found.js
**Summary**
Fixed the message text when no tests are found and multiple projects are used.
**Test plan**
Run the updated test
=> Fix message when no tests are found.

docs/GettingStarted.md
Yarn is a link, so why not NPM?
**Summary**
**Test plan**
=> Makes NPM a link like Yarn is

CHANGELOG.md, docs/CLI.md, docs/Configuration.md, docs/ExpectAPI.md, docs/GettingStarted.md, docs/GlobalAPI.md, docs/JestObjectAPI.md, docs/Troubleshooting.md, docs/Webpack.md, package.json, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/matchers.js, packages/jest-cli/src/lib/watch_plugin_registry.js, packages/jest-cli/src/reporters/coverage_reporter.js, packages/pretty-format/README.md, packages/pretty-format/src/index.js, website/blog/2016-06-22-jest-13.md, website/blog/2016-07-27-jest-14.md, website/blog/2017-02-21-jest-19-immersive-watch-mode-test-platform-improvements.md, website/blog/2017-05-06-jest-20-delightful-testing-multi-project-runner.md, yarn.lock
**Summary**
Upgrade to the latest release of prettier.
The changes are getting really small, I love it :D
**Test plan**
Green CI
=> style: upgrade to prettier 1.9

.flowconfig, package.json, packages/jest-phabricator/src/index.js, yarn.lock
**Summary**
Just choring, nothing interesting.
**Test plan**
Green CI
=> Bump Flow to 0.61

docs/Configuration.md
**Summary**
I often end up redirecting people to this [React Native Guide](http://facebook.github.io/jest/docs/en/tutorial-react-native.html#transformignorepatterns-customization) just so they can better understand what's going on with `transformIgnorePatterns`. I think it's good to point them there directly from this config option description.
**Test plan**
Please check the grammar
=> Docs: Mention transformIgnorePatterns whitelist use case

CHANGELOG.md, packages/jest-cli/src/run_jest.js
Issue https://github.com/facebook/jest/issues/5049
=> Do not support --watch inside non-version-controlled environments

docs/TimerMocks.md
**Summary**
I think `.mock.calls.length` is a little bit _out of Jest style_ to be features in official docs.
**Test plan**
=> Use `toHaveBeenCalledTimes` and `toHaveBeenLastCalledWith` in examples

packages/jest-util/src/__tests__/install_common_globals.test.js, packages/jest-util/src/install_common_globals.js
Whops!
I'm checking why the test didn't catch that.
=> Nice & fast fix

.github/SUPPORT.md
**Summary**
See https://help.github.com/articles/adding-support-resources-to-your-project/
Maybe people will read it 🙂 The text could maybe be expanded?
**Test plan**
Docs only
=> chore: add support file

packages/jest-config/src/normalize.js
=> fix: path resolve with global setup/teardown opts

website/blog/2017-12-18-jest-22.md
**Summary**
fixing stuff
**Test plan**
=> Fix backticks in Jest 22 blog post link

docs/JestPlatform.md, website/i18n/en.json, website/sidebars.json
**Summary**
Add section to the docs that showcases the various npm packages that jest publishes. Closes #5032 
**Test plan**
Run the website dev server and navigate to the "Jest Platform" section in the docs.
___
I'm still missing a lot of packages. Not sure if all of them should be included. 
Let me know what you guys think. I believe there's still plenty of room for improvement.
=> Add jest-platform section to the docs (WIP)

CHANGELOG.md
**Summary**
See #5126
**Test plan**
Docs only
=> docs(changelog): update for 20.0.1

.circleci/config.yml
**Summary**
See https://circleci.com/gh/facebook/jest/10855. Not needed with docusaurus@master, but it's not published (https://github.com/facebook/Docusaurus/pull/321). 
**Test plan**
Hail Mary?
=> chore(ci): install rsync

docs/CLI.md
**Summary**
Hello, this PR adds documentation for the new `--passWithNoTests` flag added in v22.0.0 via https://github.com/facebook/jest/pull/3672
=> Docs: add information about --passWithNoTests flag

website/translators.txt
=> Update translators file

.circleci/config.yml
Testing the publishing bot after giving it write access to the repo
=> Small config comment change

CHANGELOG.md, docs/SetupAndTeardown.md
**Summary**
Formatting of my code excerpt in the docs was not quite right, so fixed that.
**Test plan**
Docs fix only, changes verified visually in the github markdown renderer.
=> Fix code formatting

docs/TutorialReact.md
=> Fix typo in test file name in React documentation

README.md
**Summary**
These two links are 404ing because the correct path needs a `/doc/` in front of the articles urls. They have been updated to go to the official documentation pages. 
**Test plan**
This is a link update that does not required a test plan.
=> Updates broken links in README

packages/jest-editor-support/src/__tests__/process.test.js, packages/jest-editor-support/src/__tests__/runner.test.js
**Summary**
Two quick changes to fix **master**. Didn't add to the change log since it should've been right the first time.
cc @SimenB 
**Test plan**
Tests don't need to be changed.
CircleCI already looks good for the fork: https://circleci.com/gh/seanpoulter/jest/tree/fix-5340
=> Fix failing tests from #5340

.github/PULL_REQUEST_TEMPLATE.md
Minor update to the PR template to use headings for each section (similar to the [Docusaurus](https://github.com/facebook/Docusaurus/blob/master/.github/PULL_REQUEST_TEMPLATE.md) repo)
- N/A
**Before**
**After**
=> Update PR template to use headings

docs/TutorialReact.md
I'm not sure it's really a problem, but it was the only occurrence of BrE spelling across the docs.
You can check [behavior](https://github.com/facebook/jest/search?q=behavior) & [behaviour](https://github.com/facebook/jest/search?q=behaviour) search quries to understand the motivation better.
=> docs: use AmE spelling of behavior

README.md
Update webpack's website url to https://webpack.js.org
=> Update Webpack URL

CHANGELOG.md
Add changelog for move test summary to after coverage report(issue_4104)
=> Add changelog for move test summary to after coverage report(issue_4104)

website/pages/en/users.js
Center aligns the text in users page.
| Before | After |
|:--|:--|
=> Centre align text in users page

website/pages/en/videos.js
As per CSS rules, video's are hidden for mobile resolutions.
This at least lets the user view them by clicking on the title.
Going forward we should make a proper layout for mobile users.
* Should be able to click title to view video.
=> Add hyperlink to video URL

packages/jest-message-util/src/index.js
Used native string `trim()` instead of 2 regexps.
=> Use native trim instead of regexp

packages/jest-docblock/src/index.js
User native `trimLeft`, `trimRight` instead of RegExp
=> Use native trimLeft, trimRight instead of regexp

website/i18n/en.json, website/package.json, yarn.lock
Upgrade Docusaurus to 1.0.6. 
Fixes https://github.com/facebook/jest/issues/5299
Built the website and it seems to look nominal.
=> chore(website): Upgrade Docusaurus to 1.0.6

packages/expect/src/jasmine_utils.js
Use `Object.is` for check equal numbers.
=> Simplify check -0 in jasmine-utils

.flowconfig, package.json, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init.js, packages/jest-jasmine2/src/jasmine/jasmine_light.js, packages/jest-jasmine2/src/queue_runner.js, types/Circus.js, yarn.lock
Flow bump. I had to adjust one type in `jest-circus` which I'm not sure about so cc @aaronabramov about that.
Nothing breaks
=> chore(deps): upgrade flow to 0.66

website/blog/2016-07-27-jest-14.md
Info on fix: https://github.com/facebook/jest/issues/5607
=> Fix Aaron's name and twitter handle in Jest 14 blog post

website/pages/en/users.js
=> Jest got too popular

docs/ExpectAPI.md
Updated dockumentation about how `expect.toHaveProperty` works with dot in property name.
Close #5653
=> Explain how expect.toHaveProperty works with dot in property name

packages/jest-editor-support/src/Runner.js
Removed needless `replace(/\n$/, '')`, because next `trim()` will do it.
=> Remove needless replace by regexp

packages/babel-plugin-jest-hoist/src/index.js
Fix https://github.com/facebook/jest/issues/5689
=> Add parseInt, parseFloat and isNaN to mock whitelist

docs/TestingFrameworks.md
=> Fix Redux link url

packages/expect/src/__tests__/is_error.test.js, packages/expect/src/__tests__/spy_matchers.test.js, website/siteConfig.js
Aaron's talk is great. I added it to the list of videos. cc @aaronabramov 
Also fixed a few lint warnings.
Tested the website.
=> Add Aaron's talk to the website

docs/MockFunctions.md
Typo in comment: 
// or you could use the follwing...
Change to:
// or you could use the following...
Fix simple typo: follwing --> following
N/A
=> Typo: Follwing

docs/MockFunctions.md
Fixed a typo
`mockImpementation` => `mockImplementation`
n/a
=> Fix impementation typo

.github/ISSUE_TEMPLATE.md
See https://github.com/facebook/jest/issues/5760
=> add envinfo to ISSUE_TEMPLATE

website/versioned_docs/version-22.4/MockFunctions.md
Impementation -> Implementation
=> Fix typo in MockFunctions.md

CHANGELOG.md
=> Add missing changelog for #5816

packages/babel-jest/package.json, yarn.lock
Fixes #5797 
and istanbuljs/istanbuljs#145
=> fix: update dependency explicitly for babel-plugin-istanbul

CHANGELOG.md
This is very simple and straightforward as far as I can tell so not sure if I need to do much here. Let me know.
Inconsistent header styling in changelog
None
=> fix a header in changelog

packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/jest-matcher-utils/src/index.js
Spotted this tweet, https://twitter.com/qrohlf/status/977923268035338240 - realized that the english could be improved here. Think it's an awesome message @rogeliog 👍
=> Improve the english on visual difference message

docs/Troubleshooting.md
`jest` is way past version `0.9.0` so docs mentioning that version are not as relevant and is just noise. Less is more.
None. Documentation update.
=> Remove very old docs from Troubleshooting.md

CHANGELOG.md
As @SimenB pointed out, I missed the CI complaining about my indentation. My apologies!
N/A
=> Fix indentation from #5909

docs/JestObjectAPI.md
This pr is going to correct documentation for `jest.spyOn(object, methodName, accessType?)`.
=> doc: fix spyOn example test

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
See --> https://github.com/facebook/jest/issues/5985
Hope that helps!
=> inline readme with react's readme #5985

docs/JestObjectAPI.md
There was an incorrect reference to 'video' object in the example code, which should have been to 'audio'. Fixed all wrong occurrences in jest object documentation.
=> Fixed incorrect reference to 'video' object.

packages/jest-cli/src/cli/args.js
Reopen #5694 
Already discussed in #5694
=> [jest-cli] Add missing args testEnvironmentOptions and runner (reopen #5694)

integration-tests/__tests__/__snapshots__/require_after_teardown.test.js.snap, integration-tests/__tests__/require_after_teardown.test.js
Test added in #5888 fails because of changes in #5889. This fixes the test
=> fix failing test

packages/jest-leak-detector/src/__tests__/__snapshots__/index.test.js.snap, packages/jest-leak-detector/src/__tests__/index.test.js, packages/jest-leak-detector/src/index.js
Simplify check for primitive type
Unit tests have already been written, but I've added a few more.
=> Simplify check for primitive type

packages/jest-resolve-dependencies/src/index.js
1) Function `compact` looks like simple `arr.filter(Boolean)` and used only once.
2) Moved check `paths.size` to start of function
=> Simplify DependencyResolver

docs/Es6ClassMocks.md
Motivation is described in this issue: https://github.com/facebook/jest/issues/6065
basically, I think it is helpful to be explicit about the behavior of jest's automock on objects that have arrow functions on them.
=> [docs] Update Es6ClassMocks.md

package.json
This PR introduces a basic sanity test to verify that we didn't accidentally introduce a memory regression.
=> Leak detection

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATES/bug.md, .github/ISSUE_TEMPLATES/feature.md, .github/ISSUE_TEMPLATES/question.md, .github/ISSUE_TEMPLATES/regression.md
This PR adds 4 new issue templates:
- Bug Report
- Feature Proposal
- Regression Report
- Questions/Help
=> Add more templates

.github/ISSUE_TEMPLATE/feature.md
Minor description update to feature template
=> Fix feature template description

examples/getting-started/sum.test.js
Fixes example file to be consistent with README
https://github.com/facebook/jest/issues/6134
N/A
=> Update example file to match styling in README

CHANGELOG.md, docs/ManualMocks.md
The PR improves the documentation on mocking methods not implemented in JSDOM.
(No test plan as this doesn't change the code)
=> Add explanation on how to mock methods not implemented in JSDOM

integration-tests/__tests__/__snapshots__/failures.test.js.snap, integration-tests/failures/__tests__/during_tests.test.js, jest, packages/jest-jasmine2/src/is_error.js, packages/jest-jasmine2/src/jasmine/Env.js, packages/jest-jasmine2/src/jasmine_async.js
Discovered this one when preparing my talk...
Test added
=> set correct stack trace for async rejections of non-errors

integration-tests/filter/my-clowny-filter.js, integration-tests/filter/my-filter.js, integration-tests/filter/my-secondary-filter.js, packages/jest-cli/src/search_source.js
Closes https://github.com/facebook/jest/issues/6219. This change enables us to introduce new features to filtering (like make Jest responsible of printing stuff) without breaking changes.
cc @mjesun 
No new tests added
=> Change filter API to account for future updates

integration-tests/__tests__/jasmine_async.test.js, integration-tests/jasmine-async/__tests__/promise_before_all.test.js, packages/jest-circus/src/__mocks__/test_event_handler.js, packages/jest-circus/src/__mocks__/test_utils.js, packages/jest-circus/src/__tests__/__snapshots__/after_all-test.js.snap, packages/jest-circus/src/__tests__/__snapshots__/base_test-test.js.snap, packages/jest-circus/src/__tests__/after_all-test.js, packages/jest-circus/src/__tests__/base_test-test.js, packages/jest-circus/src/event_handler.js, packages/jest-circus/src/format_node_assert_errors.js, packages/jest-circus/src/index.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init.js, packages/jest-circus/src/run.js, packages/jest-circus/src/state.js, packages/jest-circus/src/utils.js, types/Circus.js
not the full async support, but basic cases like returning promises, using done and passing 3rd argument to specify a timeout
=> jest-circus async support

website/sidebars.json, website/versioned_sidebars/version-23.0-sidebars.json
Missed this with the 23 release
=> Add watch plugin docs to the sidebar

scripts/SkipOnJestCircus.js, scripts/SkipOnWindows.js
These are not being used. @rickhanlonii
=> Remove unused .test methods

integration-tests/__tests__/timer_use_real_timers.test.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter.js
Basically repeating myself XD https://github.com/facebook/jest/pull/3858
Related to #4362
`integration-tests/__tests__/timer_use_real_timers.test.js` pass
=> jest-circus: useRealTimers override fake in config

.circleci/config.yml
=> Run circus tests on node 10

docs/WatchPlugins.md
Fixes watch mode docs (see https://github.com/facebook/jest/pull/5895#discussion_r191058695)
=> Fix watch mode docs (utf 8 now)
