jestjs/jest

docs/en/MigrationGuide.md, packages/jest-cli/package.json
**Summary**
The migration-guide documentation hasn't been updated for some time and [jest-codemods](https://github.com/skovhus/jest-codemods) now supports upgrading from even more test frameworks to Jest.
**Test plan**
Before:
After:
=> Update migration guide with jest-codemods transformers

docs/en/ExpectAPI.md
This is just a documentation change to clarify that `toContain` and `toContainEqual` matchers work on arrays and strings (but not objects) rather than the more ambiguous "list".
This also adds consistency, since all other api method docs refer to "arrays", rather than "lists".
**Summary**
**Test plan**
=> Clarify what objects toContain and toContainEqual can be used on

docs/en/Troubleshooting.md
This updates `Troubleshooting.md` to include how to use Node v8.4’s `—inspect` protocol - now that #1652 has landed.
I also added a section about how to debug Jest tests using VS Code - but I understand if this should be omitted on Jest’s docs.  
This closes #4287 and relates to [create-react-app #594](https://github.com/facebookincubator/create-react-app/issues/594)
=> Updating Troubleshooting.md to include `--inspect`

integration_tests/__tests__/find_related_files.test.js, packages/jest-cli/src/reporters/summary_reporter.js
* fixes #4247
* added tests for findRelatedTests summary message
**Summary**
This fixes the summary message and was reported in 4247.
**Test plan**
1. yarn run build && yarn run test was passing
**Assumptions**
1. findRelatedTests can be used only when path pattern  is present in args
2. if findRelatedTests is not present and path pattern is provided in args, then the summary message will always be like,
_Ran all test suites matching a.js_
3. findRelatedTests & onlyChanged can not be used together
4. onlyChanged can not be used when path pattern is present in command
=> Correct summary message for flag --findRelatedTests.

integration_tests/__tests__/jest_require_mock.test.js, packages/jest-haste-map/src/lib/__tests__/extract_requires.test.js, packages/jest-haste-map/src/lib/extract_requires.js, packages/jest-runtime/src/index.js, types/Jest.js
**Summary**
Implements jest.requireMock
Similar to #4260
**Test plan**
Added jest_require_mock.test.js, and added to extract_requires.test.js for testing. Ran yarn test, partial output below
`jeffreylai-mbp:jest jeffreylai$ yarn test
Using globally installed version of Yarn
yarn test v0.28.1
$ yarn run typecheck --silent && yarn run lint --silent && yarn run jest --silent && yarn run test-examples --silent
Using globally installed version of Yarn
Found 0 errors
Using globally installed version of Yarn
Using globally installed version of Yarn
...
<Test outputs>
...
Test Suites: 162 passed, 162 total
Tests:       1502 passed, 1502 total
Snapshots:   671 passed, 671 total
Time:        100.887s
Ran all test suites.
Using globally installed version of Yarn
$ cd …
=> Implement 'jest.requireMock'

docs/en/Troubleshooting.md
I've added steps describing debugging Jest tests in WebStorm (similar to #4312).
Please let me know if you think, it shouldn't be in the Jest docs or should be in a different section of the docs (e.g. Guides - Debugging tests).
Thank you!
=> Added about debugging in WebStorm

docs/en/Troubleshooting.md
Sorry! 
PR I submitted yesterday broke the Troubleshooting page. I was missing a closing `}` in the markdown file.
Closes #4319
=> Fixes Troubleshooting Doc

packages/jest-resolve/src/default_resolver.js
**Summary**
Related to #2925. Clean up resolve() logic. Provide useful names for variables and functions. Test that a directory exists before attempting to resolve files within it.
Introduces slight performance improvements by testing whether a directory exists before attempting to resolve (potentially 10+) paths within the directory. Also tidies up code to meet style guidelines and usefully name variables + methods.
**Test plan**
Passes all tests.
=> optimize resolve

packages/pretty-format/README.md
**Summary**
Submitting as a small chunk in case it is off target for audience of `pretty-format` package.
**Test plan**
Review who can see the forest when I am deep in the trees
=> Add Usage in Jest to pretty-format/README.md

packages/jest-diff/src/__tests__/diff.test.js, packages/jest-diff/src/index.js
**Summary**
* Rewrote condition with `RegExp.test` because `String.match` is equivalent to `RegExp.exec` which returns either `null` or an array, therefore first condition was always false.
* Removed explicit conversion with `String` constructor, because `switch (aType) case 'string'` and have already returned if `expectedType !== getType(b)` or string asymmetric matcher.
**Test plan**
* Deleted `stripAnsi` from 2 existing tests with `toBe(null)` assertion
* Added 2 tests for either a or b is one line. The test for a one line and b multi line failed first.
=> Replace match with test and omit redundant String conversion in jest-diff

integration_tests/__tests__/__snapshots__/failures.test.js.snap, packages/jest-diff/src/diff_strings.js
**Summary**
Join lines with newline instead of concatenating newline to each line, and then trimming result.
Is the `trim` method redundant? What about leading spaces? Glad you asked:
* For default `--colors` option, ansi codes “protect” leading space if first line is unchanged.
* For `--no-colors` option, leading space is trimmed. Inconsistent and seems like a bug.
**Test plan**
If you approve, I will update this PR:
* delete 2 occurrences of `trim` method
* update snapshot `works with node assert` in `integration_tests/__tests__/failures.test.js`
```diff
-    Object {
+      Object {
"a": Object {
"b": Object {
-       "c": 6,
+       "c": 5,
},
-    Object {
+      Object {
"a": Object {
"b": Object {
-       "c": 7,
+       "c": 5,
},
-    Object {
+      Object {
-   "a": 2,
+   "a": …
```
=> Join lines with newline in jest-diff

packages/jest-environment-jsdom/src/index.js
**Summary**
As discussed in #3299, existing tests use an old-style HTML DOCTYPE, which makes it hard to test some modern web tools such as [KaTeX](https://github.com/Khan/KaTeX); see https://github.com/Khan/KaTeX/issues/664.  This small tweak uses the recommended HTML5 DOCTYPE, which is probably a better default.  Other issues such as #2460 could deal with the more general problem of making this configurable, but a reasonable default seems like a good start.
**Test plan**
We've tested over on the KaTeX side that it removes our warning about being in quirks mode. See https://github.com/Khan/KaTeX/pull/747#issuecomment-312021303
=> Use modern HTML5 <!DOCTYPE>, as discussed in #3299

packages/jest-jasmine2/src/jasmine/Env.js
**Summary**
I have recently started using Jest and I really like it. I tried adding nested it/test conditions, but I didn't realize that was not allowed, because both tests will succeed (nested test, however, never runs). I've added some changes to throw an error to let the devs know that such pattern is not allowed.
**Test plan**
```javascript
test('make sure 2 equals 3', () => {
test('nested test confuses the devs', () => {
expect(2).toBe(3);
})
});
```
```javascript
FAIL  ./jest-it.test.js
● make sure 2 equals 3
Test `nested test confuses the devs` cannot run because it is nested in `make sure 2 equals 3`
at Env.it (../jest/packages/jest-jasmine2/build/jasmine/Env.js:396:15)
at Object.<anonymous>.test (jest-it.test.js:4:3)
at Promise (<anonymous>)
at <anonymous>
at …
```
=> Throw Error When Using Nested It Specs

integration_tests/__tests__/__snapshots__/coverage_report.test.js.snap, integration_tests/__tests__/json_reporter.test.js, integration_tests/json_reporter/__tests__/sum.test.js, packages/jest-util/src/format_test_results.js
**Summary**
This addresses the need brought up in #2479 
The motivation I have is that in order to properly report our test runs to regulatory agencies, we are planning on using the JSON output to feed reports.  But our unit tests can be nested a couple of layers deep in 'describe' and 'in' blocks.  Currently, the JSON output only includes the title of the nearest test block, thus, losing the context of its parents.
For example, we want to see:
- passwords
- size
- too short
- too long
and not just:
- too long
**Test plan**
I've altered the sum.test.js file to create tests with zero, one, and many ancestors, and added checks for the new ancestorTitles property.
=> Adding ancestorTitles property to JSON test output

packages/jest-snapshot/src/index.js
**Summary**
I need to review created snapshots. By default, it just creates a new snapshot without any information and to do the review I must find this snapshot manually in test.snap.
When I use the `--ci` flag, I can review the snapshot, and when it looks ok, I can just press `u`.
**Test plan**
Added "Received value" + snapshot content.
=> Output created snapshot when using --ci option

packages/pretty-format/src/__tests__/html_element.test.js, packages/pretty-format/src/plugins/html_element.js
**Summary**
Because HTML5 and React make SVG so easy to use, it’s realistic to serialize elements in tests.
**Question**: Too late to rename this property of `plugins` as **DOMElement**?
**Test plan**
Added 2 tests. In this case, testing for failure first paid off.
=> Support SVG elements in HTMLElement plugin

integration_tests/__tests__/__snapshots__/show_config.test.js.snap, packages/jest-cli/src/cli/args.js, packages/jest-cli/src/lib/__tests__/is_valid_path.test.js, packages/jest-cli/src/lib/is_valid_path.js, packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/defaults.js, packages/jest-config/src/index.js, packages/jest-config/src/normalize.js, packages/jest-config/src/valid_config.js, packages/jest-validate/src/__tests__/fixtures/jest_config.js, test_utils.js, types/Argv.js, types/Config.js
**Summary**
Add a configure argument `watchPathIgnorePatterns` to exclude patterns which should not trigger test re-run in watch mode.
**Test plan**
* Add test in `packages/jest-cli/src/lib/__tests__/is_valid_path.test.js` for testing the new exclude patterns.
* Add test in `packages/jest-config/src/__tests__/normalize.test.js` for testing the normalize path for the new arguments.
* Change snapshot in `integration_tests/__tests__/__snapshots__/show_config.test.js.snap` for new snapshot with the arguments.
=> Add watchPathIgnorePatterns to exclude paths to trigger test re-run in watch mode

packages/jest-cli/src/reporters/coverage_reporter.js
**Summary**
Use "inputSourceMap" instead of read from file.
The "babel-plugin-istanbul" can use the input source map from "inputSourceMap" or "inlineSourceMap".
The final source map from babel is not suitable for the coverage re-mapping.
The "istanbul" will ignore the "inputSourceMap", if it already registered.
=> Use "inputSourceMap" for coverage re-mapping.

packages/jest-snapshot/package.json, packages/jest-snapshot/src/utils.js
**Summary**
We are using `jest-util` to create the snapshot folder, but it pulls in loads of code and `jest-validate` into vm contexts, which shouldn't be there…
**Test plan**
jest + manual logging for presence of these modules in the contexts.
=> Remove `jest-util` from `jest-snapshot`.

docs/en/Configuration.md
Failed to update document for #4331 sorry for that.
**Summary**
Update document for new argument `watchPathIgnorePatterns`
**Test plan**
Only document update, no test.
=> update document for watchPathIgnorePatterns

packages/jest-circus/src/format_node_assert_errors.js, packages/jest-config/package.json, packages/jest-diff/package.json, packages/jest-matcher-utils/src/index.js, packages/jest-matchers/src/index.js
**Summary**
Might help with intermittent ` 'default' is not exported by packages/jest-matcher-utils/build/index.js`
**Test plan**
`jest`
=> Make jest-matcher-utils use ESM exports

packages/pretty-format/src/plugins/html_element.js, packages/pretty-format/src/plugins/lib/markup.js
**Summary**
* Decided against any special case for indentation “problem” of multiline strings, but found duplicate code for text nodes, therefore…
* Refactor to encapsulate all formatting details in `markup.js` so the 3 plugins become adaptors for data structure of React elements, React test objects, and DOM elements.
**Test plan**
Existing tests
=> Provide printText and printComment in markup.js for HTMLElement plugin

fixtures/failing_jsons/failing_jest_json.json, packages/jest-editor-support/index.d.ts, packages/jest-editor-support/src/__tests__/test_reconciler.test.js, packages/jest-editor-support/src/test_reconciler.js, packages/jest-editor-support/src/types.js
**Summary**
Allow jest-editor-support to distinguish skipped tests
**Test plan**
Automated test added
=> add skipped tests support for jest-editor-support

integration_tests/__tests__/multi_project_runner.test.js, packages/jest-cli/src/get_no_test_found.js, packages/jest-cli/src/get_no_test_found_message.js, packages/jest-cli/src/get_no_test_found_related_to_changed_files.js, packages/jest-cli/src/get_no_test_found_verbose.js, packages/jest-cli/src/pluralize.js, packages/jest-cli/src/run_jest.js
**Summary**
Unified 'No test found' message for non-verbose MPR
Will now look like:
```
No tests found
In /Projects/jest
X files checked across Y projects. for more details run with `--verbose`
Pattern: xyz321 - 0 matches
```
Resolves #4324 
**Test plan**
=> Unified 'no tests found' message for non-verbose MPR

packages/pretty-format/src/__tests__/react.test.js, packages/pretty-format/src/plugins/react_element.js
**Summary**
Fixes #3823
The same “tag name” for anonymous function and undefined type seems confusing, therefore:
* `<Unknown>` if type is anonymous function as it has been
* `<UNDEFINED>` if type is neither string nor function
We think it seems easier to see and solve the problem if tests make it obvious (assuming that people review snapshots before committing :) than if the plugin throws an error.
**Test plan**
Updated the existing test for this case
=> Return UNDEFINED if type neither string nor function in ReactElement plugin

package.json, yarn.lock
**Summary**
Currently a missing peer dep warning is printed, and `karma start --watch` fails.
**Test plan**
N/A
=> Add missing watchify dependency

.flowconfig, examples/react-native/Intro.js, examples/react-native/index.android.js, examples/react-native/index.ios.js, package.json, packages/jest-repl/src/cli/repl.js, packages/pretty-format/src/__tests__/immutable.test.js, packages/pretty-format/src/__tests__/react.test.js, packages/pretty-format/src/plugins/react_element.js, test_utils.js, yarn.lock
**Summary**
Tried to upgrade, and using `flow-upgrade`, but there's still tons of errors in pretty-format tests. I'm guessing I shouldn't just litter the tests with `FlowFixMe`s?
/cc @pedrottimark
**Test plan**
`yarn flow` (currently failing)
=> Flow upgrade

fixtures/callExpressionWithoutText.example, fixtures/parser_tests.js, packages/jest-test-typescript-parser/src/type_script_parser.js
**Summary**
vscode-jest failed to highlight failed jest tests on editor, due to the `packages/jest-test-typescript-parser/test_script_parser.js` crash:
> TypeError: Cannot read property 'text' of undefined
Basically, `test_script_parser.js` @line 40 failed to check if `element` is null before calling `element.text`.
```
while (!expectText) {
expectText = element.text;
element = element.expression;
}
```
This would crash if the callable node doesn't have the text portion:
```
[1,2,3].forEach(n => {...});
```
Fix is easy and minimal, also added a test case, see below.
**Test plan**
- no UI change. 
- added new parser test example: `fixures/CallExpressionWithoutText.example` 
- added 2 new test cases in `fixures/parser_tests.js`
=> fix typescript jest test crash

packages/jest-cli/src/reporters/__tests__/__snapshots__/get_snapshot_status.test.js.snap, packages/jest-cli/src/reporters/__tests__/default_reporter.test.js, packages/jest-cli/src/reporters/__tests__/get_snapshot_status.test.js, packages/jest-cli/src/reporters/default_reporter.js, packages/jest-cli/src/reporters/get_snapshot_status.js
Improved the jest terminal reporter to show snapshot info per test. The snapshot summary shown at the end of the test run shows some generic info like *"2 snapshots written in 1 test suite"*, *"1 obsolete snapshot file found"*. However, it wasn't always immediately clear in what test suite these snapshot changes had occurred. This PR attempts to resolve this by showing all the snapshot changes per test file so that it is immediately clear what happened after a test run. I am curious to hear what you think!
This addresses issue #3581.
I was also thinking that it would be nice if the name of the snapshot which has been updated is shown in the terminal rather than simply stating *"2 snapshots written"* or *"2 obsolete snapshots found*". Adding the name to the output does not seem very …
=> Improved the jest reporter with snapshot info per test.

packages/jest-cli/src/reporters/__tests__/__snapshots__/get_snapshot_summary.test.js.snap, packages/jest-cli/src/reporters/__tests__/get_snapshot_summary.test.js, packages/jest-cli/src/reporters/get_snapshot_summary.js, packages/jest-cli/src/reporters/summary_reporter.js
I noticed that the coverage for the jest-cli reporters was not very high so I decided I could add some value by writing some tests for it:)
I split the creation of the snapshot summary to a separate file (`get_snapshot_summary.js`). 
I wanted to write a test for the snapshot summary text printed in the console at the end of a text. However, the `summary_reporter.js` in which the snapshot summary creation is contained requires a lot of overhead to set up making focused testing difficult. This is why I split the creation of the snapshot summary from the reporting about it.
I am hoping that test coverage of the reporters can be gradually improved by splitting them up into smaller units with well defined and focused responsibilities that are easily testable. 
Let me know what you think!
=> Separated the snapshot summary creation from the printing to improve testability.

packages/jest-circus/src/utils.js
**Summary**
This isn't related to any particular open issue with jest-circus, but I noticed it while reading through the code to familiarize myself with it, and so decided to submit it on the side as a small improvement.
To provide better interop for Promise libraries such as bluebird and Q, this changes
the part of jest-circus that detects a returned Promise from a test or hook to only
check that the value is an object with a then method on it, rather than checking that
the value is instanceof Promise. This is considered the standard way of checking for
a Promises/A+-compliant Promise. As an added bonus, this check works cross-realm.
**Test plan**
I think we should add an integration test to this that pulls in bluebird, Q, or jQuery deferred, and verifies that the test runs as expected, …
=> Change Promise detection code in jest-circus to support non-global Promise implementations

packages/jest-cli/src/reporters/utils.js
**Summary**
Display name is hard to read in white terminals
**Test plan**
=> Remove .dim from displayName for better readability

packages/jest-cli/src/get_no_test_found_message.js
**Summary**
#4354 Did a great job on providing a better "no test found" message for MPR.
I feel that we should show the "verbose" message when there is only one project or when the user is not trying to specify a project at all.
**Test plan**
=> Use "verbose" no test found message when there is only one project

docs/en/Configuration.md
**Summary**
Fixes: https://github.com/facebook/jest/issues/4394
**Test plan**
=> Specify watchPathIgnorePatterns will only be available in Jest 21+

packages/babel-jest/src/index.js
**Summary**
In babel v7 `babel-core.transform()` returns null if a file is ignored.
This change makes babel-jest not throw a TypeError in this case.
**Test plan**
Tested by modifying local installed babel-jest in babel, while trying to get jest running in babel itself.
=> fix(babel): Handle ignored files in babel v7

packages/babel-jest/package.json
**Summary**
We will be releasing a beta soon, and babel-jest should support this as well.
=> babel-jest: Support upcoming beta

docs/en/Configuration.md, integration_tests/__tests__/__snapshots__/module_name_mapper.test.js.snap, packages/jest-cli/src/reporters/default_reporter.js, packages/jest-cli/src/reporters/utils.js, packages/jest-cli/src/run_jest.js, packages/jest-config/src/index.js, packages/jest-resolve/src/__tests__/resolve.test.js, packages/jest-resolve/src/default_resolver.js, packages/jest-resolve/src/index.js, packages/jest-runner/src/run_test.js, packages/jest-runtime/src/index.js, test_utils.js, types/Config.js
Also, improve error message when moduleNameMapper doesn't resolve to a module.
**Summary**
1. The existing moduleNameMapper implementation doesn't invoke the customer resolver with the custom resolver option. This makes it impossible to write custom resolvers that work in all cases. 
2. If a moduleNameMapper was _not_ specified, then the custom resolver would not be run at all. 
This PR solves the two problems above. 
1) It passes through the resolver configuration option so that the custom resolver could be used after the moduleMapMapper mapped the module. Additionally, the error message was improved with exactly which moduleName (including the mapped version) was causing the problem. 
2) If the moduleNameMapper isn't specified, it sends everything through to the resolver, unmapped. …
=> Allow custom resolver to be used with[out] moduleNameMapper

integration_tests/__tests__/__snapshots__/list_tests.test.js.snap, integration_tests/__tests__/list_tests.test.js, packages/jest-cli/src/run_jest.js
**Summary**
Always print the output of the `--listTests` option to console.log, even when using `--json` flag (which is otherwise redirected to stderr) or the `--stdErr` flag.
See issue: https://github.com/facebook/jest/issues/4388
**Test plan**
Updated the existing test
=> Make listTests always print to console.log

packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init.js, packages/jest-cli/src/test_result_helpers.js, packages/jest-runner/src/run_test.js, types/TestResult.js
**Summary**
Adds project [displayName](https://github.com/facebook/jest/pull/4327) to TestResult type and ensures the value is propagated through to testResultsProcessor.
Resolves https://github.com/facebook/jest/issues/4406
[Sample testResultsProcessor output](https://gist.githubusercontent.com/palmerj3/6bbc332f5f25173941796eae2a1c278a/raw/61f6180154c7d8b93fb14241dba33b64fc484131/gistfile1.txt) in a multi-project environment where one project has a displayName defined and one does not.
**Test plan**
Run tests locally
=> Add displayName to TestResult

packages/pretty-format/src/__tests__/immutable.test.js
**Summary**
After changes for upgrade to Flow 0.53.1, `immutable.test.js` had 2 occurrences of:
>console.warn node_modules/react/lib/lowPriorityWarning.js:40
>    Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
After reading [https://flow.org/en/docs/react/types/](https://flow.org/en/docs/react/types/)
> If you want to access them [utility types] then you should import React as a namespace `import * as React from 'react'`
> if you import React with: `import React from 'react'` you will be able to access `React.createElement()`
These tests depend only on `React.createElement()` …
=> Fix React PropTypes warning in tests for Immutable plugin

packages/jest-cli/src/cli/args.js
**Summary**
The throw was added to clarify a complex behavior, like matching `--onlyChanged` with a pattern. However, this makes impossible to have a default to run tests related to the commit that can also be overridden via CLI with `--all`, or use a pattern. Which, in fact, [it already existed](https://github.com/facebook/jest/blob/master/packages/jest-config/src/normalize.js#L502-L504).
**Test plan**
Run `jest --onlyChanged foo`; and all `foo` tests should be run without throwing an exception. This is because the pattern will take precedence over `--onlyChanged`.
=> Remove existing throw

package.json
**Summary**
- removes the silent flag from package.json scripts
- closes #4449
Due to a change in `yarn` the `--silent` flag needs to be removed from package.json scripts.
**Test plan**
run `yarn test`
=> --silent flag

packages/jest-resolve/src/node_modules_paths.js
**Summary**
This aligns Jest with the behaviour of Node where it takes precedence of `NODE_PATH` over resolving modules relative to `node_modules`.
**Test plan**
yolo
=> Take precedence of NODE_PATH when resolving node_modules directories

packages/jest-docblock/README.md
**Summary**
Adds README with documentation to jest-docblock.
Per https://github.com/prettier/prettier/pull/2772#discussion_r137921858
**Test plan**
Text-only; no tests
=> Add README to jest-docblock

packages/jest-runtime/src/index.js, types/Jest.js
**Summary**
Apparently `restoreAllMocks` was not exposed to `jest` object.
Fixes https://github.com/facebook/jest/issues/4436
**Test plan**
Flow
=> Expose restoreAllMocks to  object

packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
**Summary**
When creating mock functions, jest-mock attempts to copy over the existing name of the function being mocked. However, it creates the mock functions using `Function()` (a form of eval), using string interpolation to specify the function name in the code being evaluated. This means that only function names consisting of valid characters for JS identifiers can be used.
Currently there is some code which attempts to sanitize function names so they are valid, but it only replaces spaces and hypens. Other invalid characters remain.
I've expanded the regex used to include other special characters in the ASCII space, while leaving ASCII chars which are valid for identifiers, as well as unicode characters (for people coding in non-Latin alphabets, for example).
**Test plan**
- yarn …
=> Fix function name sanitization in jest-mock

.eslintrc.js, packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
**Summary**
As per discussion [here](https://github.com/facebook/jest/pull/4464/files#r138264201).
This also fixes eslint by disabling `flowtype/require-valid-file-annotation` for `*.md` files
**Test plan**
Added a test for multiple reserved words
=> Make FUNCTION_NAME_RESERVED_PATTERN stateless

docs/en/ExpectAPI.md
**Summary**
Make it clear how to use the `.toThrow` method.
**Test plan**
Just docs.
=> Improve docs for 

packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/matchers.js
**Summary**
EDITED:
* Call `diff` **if and only if** `valuePassed && hasEndProp`
* Call `pretty-format` for received property value, **not** for its parent object
* Received is `lastTraversedObject` **if and only if** `traversedPath` non-empty and incomplete
**Test plan**
Updated 3 snapshots
=> Call jest-diff and pretty-format more precisely in toHaveProperty matcher

packages/jest-resolve/src/default_resolver.js
**Summary**
A recent change to take precedence of NODE_PATH for module resolution (https://github.com/facebook/jest/pull/4453) made this issue more likely to occur since NODE_PATH could contain non-existent directories. While this could have occurred prior to the change, it was less likely since it is more common that modules are in local `node_modules`.
Either way, non-existent directories should be treated the same way as non-existent files during module resolution. The equivalent case for `statSync` returning `ENOENT` for files is `ENOTDIR` for directories. We may want to add `ENOTDIR` to `isFile` as well.
**Test plan**
1. `yarn test`
2. Link cli into another project, export NODE_PATH environment variable as a non-existent directory, no longer see cryptic `Cannot find module` error. …
=> [jest-resolve] Prevent default resolver failure when potential resolution directory does not exist

docs/en/Configuration.md, docs/en/ManualMocks.md
**Summary**
A clearer explanation for where `__mocks__` should live in order to mock modules from `node_modules` when a config is using `roots` to point to another directoy than the root directory.
**Test plan**
Docs only.
=> [docs] Clarify where `__mocks__` should live when using `roots`

packages/expect/src/__tests__/assertion_counts.test.js, packages/expect/src/extract_expected_assertions_errors.js
**Summary**
`.hasAssertions` leaked to every `test` case following the one it was declared in.
Also decided to extract `setState` call to a function named `resetAssertionsState` so it's easier to understand what it does.
Fixes #4496.
**Test plan**
Empty test without assertions. Fails on current master.
=> fix: Reset local state of assertions when using hasAssertions

packages/jest-runner/src/run_test.js
**Summary**
Local `yarn test` fails
**Test plan**
CI green for `ci/circleci: test-node-6`
Don’t know about `continuous-integration/appveyor/pr` though
=> Fix prettier error in jest-runner

integration_tests/__tests__/__snapshots__/failures.test.js.snap, packages/expect/src/__tests__/assertion_counts.test.js, packages/jest-cli/src/reporters/default_reporter.js, packages/jest-cli/src/reporters/verbose_reporter.js, packages/jest-runner/src/run_test.js
**Summary**
This is a fix for this issue https://github.com/facebook/jest/issues/4264
When running a single test that has many test cases the error messages are printed before the list of failing/passing tests which makes us to scroll up every time just to see the error message.
This Pull Request change the behavior of print error messages to put them after the list of tests
So the behavior is going to switch from the actual:
to this:
=> Print errors after test structure in verbose mode

packages/expect/src/__tests__/stacktrace.test.js, packages/expect/src/index.js
**Summary**
Fixes https://github.com/facebook/jest/issues/4515
**Test plan**
No test plan yet.
=> Do not modify stack trace of JestAssertionError

packages/jest-diff/src/__tests__/diff.test.js, packages/jest-diff/src/diff_strings.js
**Summary**
**Problem 1**: outer element
For example, if component changes to render a sibling element, it also returns an outer element in React 15 and earlier.
* For default **unexpanded** option, `formatHunks` function makes sure that strings **end with newline**. Therefore, it displays an inserted (or deleted) outer element **clearly**:
```diff
+ <header>
<h1>
Jest
</h1>
+   <h2>
+     Delightful Javascript Testing
+   </h2>
+ </header>
```
* For **expand** option, `formatChunks` function **doesn’t**. Therefore it displays the `</h1>` end tag of the original outer element **unclearly** as a pair of deleted and inserted lines:
```diff
+ <header>
<h1>
Jest
- </h1>
+   </h1>
+   <h2>
+     Delightful Javascript Testing
+   </h2>
+ </header>
```
**Problem 2**: presence or absence of …
=> Display outer element and trailing newline consistently in jest-diff

docs/en/JestObjectAPI.md
**Summary**
The `restoreAllMocks` function was added in `v20.1.0` but exposed in `v21.1.0`, i.e. people will get `jest.restoreAllMocks is not a function` error before `v21.1.0`, the actual available version should be `v21.1.0+`.
[CHANGLOG v21.1.0](https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-211): Expose restoreAllMocks to object (#4463)
**Test plan**
docs only
=> docs(restoreAllMocks): available in Jest 21.1.0+

packages/jest-diff/src/__tests__/__snapshots__/diff.test.js.snap, packages/jest-diff/src/diff_strings.js
**Summary**
Improve in a small way now and mainly reduce complexity of code diff in the next pull request:
In `formatHunks` replace `map` with `reduce` to eliminate some string concatenation and mainly be able to display more detail via `diffChars` within **adjacent sequences** of removed and added lines.
**Test plan**
Updated 6 snapshots in which replacing newline in `createPatchMark` function with `join('\n')` in `formatHunks` got rid of escape sequences to reopen and immediately close yellow on the next line.
=> Replace a map method with reduce in jest-diff

docs/en/ManualMocks.md, docs/en/TutorialAsync.md
**Summary**
I just spent 5 hours trying to figure out why my tests were passing on all developer's computers, but were failing on CI. It turns out we had named our `__mocks__` folders in all uppercase, `__MOCKS__`, instead of the correct lowercase name. Apparently this is not a problem on Windows or macOS, but breaks on other Unix systems like Ubuntu or Debian. At least that was my reasoning.
I don't think this is a rare mistake to make, as many boilerplates and tutorials set up jest to look for `__TESTS__` folders (and `.spec` and `.test` files of course), which makes it natural to name the mock folders uppercase as well. (this i purely speculation though)
To make sure this doesn't happen for others in the future, I thought it would be wise to call this out explicitly in the docs. …
=> docs: add warning about uppercase __MOCKS__ folders

packages/eslint-plugin-jest/docs/rules/no-disabled-tests.md, packages/eslint-plugin-jest/src/index.js, packages/eslint-plugin-jest/src/rules/__tests__/no_skipped_tests.test.js, packages/eslint-plugin-jest/src/rules/no_disabled_tests.js, packages/eslint-plugin-jest/src/rules/types.js
**Summary**
This change affects the `jest/no-disabled-tests` rule of the Jest eslint plugin
This update allows the rule to recognize more disabled/skipped/pending tests, in line with information for [Pending Specs in Jasmine](https://jasmine.github.io/2.0/introduction.html#section-Pending_Specs)
The existing rule already recognizes:
* tests that append ".skip" (e.g. `it.skip(...)`)
* tests that prepend "x" (e.g. `xit(...)`)
This change adds:
* tests that don't contain a function body (e.g. `it('foo')"`)
* tests that contain a call to "pending()" (e.g. `it('foo', () => { pending(); })`)
**Test plan**
Additional test cases for the rule changes have been added to `__tests__/no_disabled_tests.test.js`
_[This file was renamed from `__tests__/no_skipped_tests.test.js` to better match both the …
=> Allow eslint-plugin-jest to recognize more disabled tests

packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/__tests__/__snapshots__/spy_matchers.test.js.snap, packages/expect/src/__tests__/__snapshots__/to_throw_matchers.test.js.snap, packages/jest-cli/src/lib/__tests__/__snapshots__/format_test_name_by_pattern.test.js.snap, packages/jest-cli/src/reporters/__tests__/__snapshots__/get_snapshot_status.test.js.snap, packages/jest-cli/src/reporters/__tests__/__snapshots__/get_snapshot_summary.test.js.snap, packages/jest-cli/src/reporters/__tests__/__snapshots__/utils.test.js.snap, packages/jest-config/src/__tests__/__snapshots__/normalize.test.js.snap, packages/jest-diff/src/__tests__/__snapshots__/diff.test.js.snap, packages/jest-jasmine2/src/__tests__/__snapshots__/matchers.test.js.snap, packages/jest-matcher-utils/src/__tests__/__snapshots__/index.test.js.snap, packages/jest-message-util/src/__tests__/__snapshots__/messages.test.js.snap, packages/jest-util/src/__tests__/__snapshots__/validate_cli_options.test.js.snap, packages/jest-validate/src/__tests__/__snapshots__/validate.test.js.snap, packages/pretty-format/src/__tests__/__snapshots__/react.test.js.snap, packages/pretty-format/src/plugins/convert_ansi.js
**Summary**
* Because colors share same `close` sequences, some closing tags didn’t match opening tags
* Without `close` sequences (which are shared, by the way) for `bold` and `dim` their opening tags didn’t match closing tags
The mismatches confused me a bit in the beginning.
Adding the missing `cyan` theme color confused us when we reviewed #3429 
Additional colors:
* `gray` (also known as bright black) in default theme for `pretty-format` plugin
* `yellow` in default theme for `pretty-format` plugin also in `jest-diff`
* `white` in `jest-cli`
Additional modifier:
* `inverse` is used in `jest-cli` also will be useful in `jest-diff` and `jest-matcher-utils`
Additional `close` sequences:
* `bold`
* `dim`
**Residue**: While reviewing the snapshots, a few mismatched `</>` confused me …
=> Add missing escape sequences to ConvertAnsi plugin

packages/jest-cli/src/cli/index.js
**Summary**
This fixes #4448.  The change in #4254 caused `createHasteMap` to get false for watch.  To not have to change watch logic elsewhere, I just added an or condition when we pass watch to the `createHasteMap` call.
**Test plan**
I'm open to options on testing this.  It doesn't appear it was tested before and not really sure the best way for catch this in a test.
=> Fix watchAll not running tests on save

packages/jest-diff/src/__tests__/__snapshots__/diff.test.js.snap, packages/jest-diff/src/__tests__/diff.test.js, packages/jest-diff/src/diff_strings.js, packages/pretty-format/src/plugins/convert_ansi.js
**Summary**
* Replace explicit background colors with `inverse` for removed, added, in-changed lines.
* Mid-course change: add `bgYellow` for unchanged lines which didn’t have highlight. The dim stack trace and gray lines caused a perceptual conflict instead of a contrast. Also as Scott said, gray was not light enough. I think yellow looks better on Windows. It looks like pollen on the following illustrations from MacOS Terminal. Also better not to churn snapshots of diffs.
Removed lines are **bgGreen** at left and **inverse** of green at right, that is the same:
Added lines are **bgRed** at left and **inverse** of red at right, that is the same:
Indentation-changed lines are **bgCyan** at left and **inverse** of cyan at right, that is the same:
Unchanged lines are unhighlighted at left …
=> Simplify highlight for leading and trailing spaces in jest-diff

packages/jest-editor-support/src/Settings.js, packages/jest-editor-support/src/__tests__/settings.test.js
**Summary**
jest 21.0.0
--showConfig flag will return configs
=> --showConfig change to show all config, jest-editor-support fails

packages/jest-runtime/package.json
**Summary**
It's still not possible to use Jest with Babel 7 due to some kind of a conflict between Babel versions because `jest-runtime` requires `babel-core@^6`. Moving `babel-core` to peer dependencies such as in `babel-jest` resolves the problem.
**Test plan**
Existing tests should pass.
=> jest-runtime: move babel-core to peer dependencies

docs/en/GlobalAPI.md
**Summary**
Updated general API docs. I've missed mention about an optional parameter of the test function.
I've run into an issue that my test hangs because I've defined the parameter for the test callback. Could be handy to mention that.
=> docs: mention about optional `done` argument in test fn

packages/jest-diff/src/__tests__/__snapshots__/diff.test.js.snap, packages/jest-diff/src/__tests__/diff.test.js, packages/jest-diff/src/diff_strings.js
**Summary**
Original goal was to see if text node following element does or doesn’t have a leading space.
What if multiple leading spaces? Oops :(
* If even number, highlight isn’t needed to see them. For example, indentation in `pre` element.
* If odd number, the last seems most important to see. Especially if it’s an indentation error.
Baseline before this PR at left and improved from this PR at right:
By the way, visually unexpected indentation of first line of text because child of `pre` element.
Caused me to learn more than I wanted to know about regex in replace.
**Test plan**
Added a snapshot test to specify intended (ha ha, misspelled as indented :) behavior.
Aha, it is possible to use snapshots to fail at first, and then update to improved result.
=> Highlight only last of odd length leading spaces in jest-diff

.vscode/settings.json
**Summary**
Following https://github.com/flowtype/flow-for-vscode#setup they recommend setting `"javascript.validate.enable": false` in workspace settings, otherwise I get errors like "... can only be used in a .ts file".
As I am new to flow and vscode I might be wrong, let me know vscode users contributing to Jest how it works for you today?
**Test plan**
None, it's an editor setting
=> chore(vscode): ease flow usage

packages/jest-docblock/README.md, packages/jest-docblock/src/__tests__/index.test.js, packages/jest-docblock/src/index.js
**Summary**
Prettier is implementing a `--insertPragma` flag to insert a `@format` pragma to the top of files.
During implementation it became apparent that a `stripDocblock` function would be helpful for replacing docblocks.  E.g.:
```js
const newFileContents = newDocblock + '\n' + stripDocblock(oldFileContents);
```
This PR introduces a new function, `strip(contents: string)` for returning the whole file _except_ the top docblock.
**Test Plan**
Basic unit tests
=> [jest-docblock] add strip

packages/jest-docblock/src/__tests__/index.test.js, packages/jest-docblock/src/index.js
Follow-up to #4517.
**Summary**
I noticed the regular expressions used to trim down the docblock were trimming out some useful information: leading whitespace.
```js
/**
* foo()
*   .bar()
*/
```
`require('jest-docblock').parseWithComments(...).comments` was being producing
```js
foo()
.bar()
```
This PR preserves all **but the first, if present** space on each line, such that the output is:
```js
foo()
.bar()
```
**Test plan**
Unit tests added and passing.
=> [jest-docblock] Preserve leading whitespace in docblock comments

packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/to_throw_matchers.js, packages/jest-matcher-utils/src/index.js
**Summary**
Reduce package coupling and eliminate potential inconsistency between fg and bg colors.
Make `printExpected` and `printReceived` follow example of `printActualErrorMessage` to color trailing spaces within the string **before** coloring the entire string, because closing escape sequence for foreground color preceding newline causes regex for background color not to match.
**Test plan**
* Added a snapshot (with wrong result at first) of improved behavior in `matchers.test.js`
* Attached screen shot to confirm no regression in `to-throw-matchers.js`
P.S. Again to Yarn team: we who are about to test (package interdependencies) salute you!
=> Call chalk.inverse for trailing spaces in jest-matcher-utils

packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/utils.js, yarn.lock
**Summary**
`rootDir` was not replaced in custom `testEnvironment`, so it was harder to use custom unpublished environments. This PR fixes it.
**Test plan**
Added a test.
=> Support rootDir tag in testEnvironment

packages/jest-diff/src/__tests__/__snapshots__/diff.test.js.snap, packages/jest-diff/src/__tests__/diff.test.js
**Summary**
Before designing new tests for char diff:
* cover last uncovered line in `diff_strings.js`
* cover one additional line in `index.js` but leave 6 related to asymmetric matcher
In `diff.test.js`
* Factored out `const NO_DIFF_MESSAGE = 'Compared values have no visual difference.';`
* Moved `toJSON` function from module scope to `describe` block where it is used
**Test plan**
* Added **unexpanded** tests under **no visual difference** to hit `if (hunks.length === 0) { return null; }` in `diff_strings.js`
* Deleted one test under **oneline strings** that is redundant with **no visual difference**
* Added tests under refactored **falls back to not call toJSON** to hit `catch (e) { hasThrown = true; }` in `index.js`
=> Increase coverage in jest-diff

packages/jest-cli/src/__tests__/cli/args.test.js, packages/jest-cli/src/cli/args.js
**Summary**
In this commit, we are adding a new validation in the `check` method of the `jest-cli` package, so we raise an exception if the user tries to run Jest with undefined `maxWorkers`
Some users were confusing `-w` as an alias to `--watch`, but in fact, `-w` is an alias to `--maxWorkers`. This change will also make this distinction clearer.
Also, a new test file was added to the `jest-cli` package, in order to unit test the `check` method.
Fixes issue #4577 
**Test plan**
```shell
jest --maxWorkers
jest --maxWorkers 2
```
=> Check if the maxWorkers has a value and raises an exception otherwise

packages/babel-plugin-jest-hoist/src/index.js
**Summary**
Update error message in `babel-plugin-jest-hoist` to specify only inline functions are accepted as a second parameter to `jest.mock` (explicit automock).
We spent some time troubleshooting because it refused to accept any function we gave to it, until I read the code and saw that previously declared functions get seen as "identifiers", only inline/arrow functions are seen as "function".
**Test plan**
Not familiar with test strategy for error messages, if the builds fail I will modify whatever tests assert on that error message.
=> Fix #4588 error text inline function

packages/jest-worker/README.md, packages/jest-worker/package.json, packages/jest-worker/src/__performance_tests__/test.js, packages/jest-worker/src/__performance_tests__/workers/jest_worker.js, packages/jest-worker/src/__performance_tests__/workers/pi.js, packages/jest-worker/src/__performance_tests__/workers/worker_farm.js, packages/jest-worker/src/__tests__/child.test.js, packages/jest-worker/src/__tests__/index.test.js, packages/jest-worker/src/__tests__/worker.test.js, packages/jest-worker/src/child.js, packages/jest-worker/src/index.js, packages/jest-worker/src/types.js, packages/jest-worker/src/worker.js, yarn.lock
This PR introduces a new module, `jest-worker`, intended to allow heavy task parallelization over multiple workers. 
The module has a few advantages over the currently one used both in `jest` and `metro-bundler`:
* 100% `flow`-ified.
* 100% test coverage on it, all statements, methods and branches.
* Slightly faster than the currenly used one.
* Natively provides a `Promise` based interface, which allow us to avoid the extra wrapping layer in order to be used with `async`/`await.
* It only has one single dependency (`merge-stream`), which we could also remove.
* Lazily instantiated code in worker, meaning no code is loaded on child processes until the first call is done (lazy require). This allows to spawn a farm with minimal RAM consumption, and only load them when needed.
* Sticky …
=> Initial version of jest-worker

packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/jasmine/Env.js, packages/jest-jasmine2/src/jasmine/Spec.js, packages/jest-jasmine2/src/jasmine/jasmine_light.js
**Summary**
Adds testPath to jest-jasmine2 reporter callbacks.
For jest reporter callbacks such as onTestStart we are provided with the associated file path of the test being reported on. This adds this functionality to jest-jasmine2 reporters.
My personal (and organizational) need for this is that I need a jasmine reporter that is capable of properly uniquely identifying a particular test block. I do this by utilizing both the fullName and the relative file path of the test.
For large projects it is not at all unheard of for fullName (e.g. nested test description + it block description) to not be unique.
Before (specStarted):
```
{
id: 'spec0',
description: 'should play',
fullName: 'playlist should play',
failedExpectations: [],
passedExpectations: [],
pendingReason: ''
}
```
After …
=> Add testPath to jest-jasmine2 reporter callbacks

packages/jest-runtime/src/__tests__/defaultResolver.js, packages/jest-runtime/src/__tests__/runtime_require_mock.test.js, packages/jest-runtime/src/index.js
This is a bug fix for  #4427
**Test plan**
A regression test was added to prevent this from happening in the future.
=> Manual user mocks not working with custom resolver #4427

packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
**Summary**
Mocking constructor wasn't supported inside `mockImplementationOnce`. 
Fixes #4595.
**Test plan**
Added a test with mocking constructor.
=> Support mocking constructor in mockImplementationOnce

packages/jest-util/src/__tests__/fake_timers.test.js, packages/jest-util/src/fake_timers.js
**Summary**
Nested calls to timer mocks (`setTimeout`/`setInterval`) inside `setImmediate` were unreliable with `jest.runOnlyPendingTimers`.
To fix this, we need to store the timers object before executing immediates – simply clone timers (assigning will hold the reference) at the very beginning of `jest.runOnlyPendingTimers` so we're sure we're going to run only pending timers :D. Otherwise the timers object gets populated with timers that should not be there yet.
Fixes #3048
**Test plan**
Updated the existing test to support currently failing case
=> Fix runOnlyPendingTimers for setTimeout inside setImmediate

packages/jest-cli/package.json, yarn.lock
**Summary**
Jest currently resolves to the version of `node-notifier` with the fix, but let's make it explicit.
Fixes #3177
**Test plan**
#yolo
=> Bump node-notifier version

docs/en/Troubleshooting.md
**Summary**
I had an issue where `coveragePathIgnorePatterns` didn't have any effect, which was caused by some leftover config in my `.babelrc` from when I was using Mocha + Nyc. I documented the cause and fix to help others facing the same issue.
**Test plan**
This is just documentation, no test plan needed.
=> docs: add info about `coveragePathIgnorePatterns`

packages/jest-get-type/src/__tests__/index.test.js, packages/jest-get-type/src/index.js
**Summary**
Add support for type `date` to `jest-get-type`.
Btw, any reason why `jest-get-type` exists, over just using [kindof](https://github.com/moll/js-kindof) (or some other module doing the same thing)?
**Test plan**
New test added
=> Add support for date in jest-get-type

packages/jest-cli/src/__tests__/search_source.test.js, packages/jest-runtime/src/__tests__/runtime_require_module.test.js, packages/jest-runtime/src/__tests__/test_root/RequireRegularModule.js, packages/jest-runtime/src/__tests__/test_root/inner_parent_module.js, packages/jest-runtime/src/__tests__/test_root/node_modules/module-needing-parent/index.js, packages/jest-runtime/src/__tests__/test_root/node_modules/module-needing-parent/node_modules/parent-module/index.js, packages/jest-runtime/src/__tests__/test_root/node_modules/parent-module/index.js, packages/jest-runtime/src/index.js
**Summary**
Fixes #4567. ~This leaves out `id` and `exports`, but it implements `require` (which I need, and is my motivation for doing this) and `filename`/`id` which should be enough for `require-dir` to work.~
`module.parent` is now fully implemented.
**Test plan**
New tests added
=> Implement module.parent

packages/jest-runtime/src/__tests__/runtime_require_module.test.js, packages/jest-runtime/src/__tests__/test_root/RegularModule.js, packages/jest-runtime/src/index.js
**Summary**
As mentioned in https://github.com/facebook/jest/pull/4614#issuecomment-334922559 there are 2 ways that `module` in normal node and `module` in jest diverge (at the top level, #4614 addresses `module.parent` being faked).
1. `module.require`should not be enumerable.
1. `module.loaded` is missing in jest's implementation. (https://nodejs.org/api/modules.html#modules_module_loaded)
This PR fixes both of those issues.
**Test plan**
New test added
=> Add `module.loaded`, and `module.require` should not be enumerable

packages/jest-environment-jsdom/src/__tests__/jsdom_environment.test.js, packages/jest-environment-jsdom/src/index.js, packages/jest-environment-node/src/__tests__/node_environment.test.js, packages/jest-environment-node/src/index.js, packages/jest-util/src/__tests__/fake_timers.test.js, packages/jest-util/src/fake_timers.js
Fixes #4559. Not entirely sure if this is the right approach. Let me know if there's a better way!
Some thoughts:
- I'm a little unsure about the name TimerRef (I consider it to be a reference to the timer that is used to clear it)
-  ~~we might want to assert if ref/unref are really functions but I noticed this isn't always done in other places in the codebase~~
- maybe we also need to verify the return values of ref/unref?
- ~~I had to shuffle the FakeTimer constructor args a little bit since some are optional. I considered making timerConfig an optional arg with a default implementation but given that FakeTimer is generic about TimerRef, I couldn't get Flow to typecheck it properly~~.
Any feedback is more then welcome.
Thanks!
=> Implement node Timer api when running in node environment.

packages/jest-cli/src/reporters/summary_reporter.js
**Summary**
Fixes #4440. Check if `npm_lifecycle_script` calls `jest` directly because it's possible that projects wrap the invocation of jest with some script. If jest is called directly, the snapshot update command is something like `yarn test -u` (note: the `--` has been removed). Else suggest people "re-run jest with `-u`".
I `yarn link`'ed `jest-cli` to `my-app` which has this `package.json`:
```
➜  my-app cat package.json
{
"name": "my-app",
"version": "0.1.0",
"private": true,
"dependencies": {
"react": "^16.0.0",
"react-dom": "^16.0.0"
},
"scripts": {
"test-call-jest-indirectly": "./run-tests.sh",
"test-call-jest-directly": "jest"
},
"devDependencies": {
"babel-preset-es2015": "^6.24.1",
"babel-preset-react": "^6.24.1",
"jest": "^21.2.1",
"react-test-renderer": "^16.0.0"
}
}
``` …
=> Check if npm_lifecycle_script calls jest directly

docs/en/MoreResources.md
**Summary**
The example 'test' link for 'React' repository was broken. Updated it with the right path.
=> In 'Learn by example' section example tests for React broken link fixed in the Doc

packages/jest-editor-support/index.d.ts
**Summary**
If you have the typescript compiler with "no implict anys" turned on, then importing jest-editor-support will fail.
**Test plan**
None, this should be fine.
=> Adds an 'any' to the typedef for updateFileWithJestStatus in editor support

docs/en/CLI.md, docs/en/MigrationGuide.md, docs/en/SnapshotTesting.md, docs/en/TestingFrameworks.md, docs/en/Troubleshooting.md, docs/en/TutorialAsync.md, docs/en/TutorialReact.md, docs/en/TutorialReactNative.md, website/i18n/en.json
Pull request related to issue #4638 
**Summary**
This modification creates a new category called "Framework Guides" whose intent is to group all guides related to testing web frameworks with Jest.
As mentioned in the issue #4638, this modification minimize the feeling that React is "the framework" and everything else is branded as "other".
**Test plan**
**Set up:**
- Clone the repo
- run: yarn install
- cd into the website folder
- run: npm ./server/generate.js
- run: yarn start
**Check:**
- Testing React Apps
- Testing React Native Apps
- Testing Web Frameworks
The menu content before this change is as follows:
The menu content after this change:
=> Added a new category called Framework Guides

docs/en/TestingFrameworks.md
**Summary**
The Web Components example is pointing to a Stack Overflow Documentation page, a service that was discontinued.
Since no other information is provided besides the link, I removed this from the documentation.
Ideally a new resource should be added, but I don't have any suggestions.
**Test plan**
I was unable to build the website (a package is incompatible with my system), but since this is a simple documentation change, I decided to submit it anyway.
=> Remove unavailable link from docs/testing-frameworks

packages/jest-cli/src/cli/index.js, packages/jest-runtime/src/cli/index.js
**Summary**
It turns out that jest-runtime doesn't patch fs with graceful-fs. This PR fixes it.
I also removed some unnecessary underscores in the jest-cli entry point.
**Test plan**
Manually verified fs is patched in jest-runtime.
=> Use graceful-fs in jest-runtime.

.gitignore
**Summary**
This ignores the crowdin files from repo.
=> Ignore translated doc files

docs/UsingMatchers.md
Adding a missing `/en/` to two links at the bottom of the '[Using matchers](https://facebook.github.io/jest/docs/en/using-matchers.html)' doc page as they are currently 404ing on production.
Review the two text snippets reproduced below and verify the links now go to the correct page.
**Link 1:**
"This is just a taste. For a complete list of matchers, check out the [reference docs](https://facebook.github.io/jest/docs/en/expect.html)."
**Link 2:**
"Once you've learned about the matchers that are available, a good next step is to check out how Jest lets you [test asynchronous code](https://facebook.github.io/jest/docs/en/asynchronous.html)."
=> Update UsingMatchers.md to fix broken links

packages/pretty-format/src/__tests__/dom_element.test.js, packages/pretty-format/src/plugins/dom_element.js
**Summary**
Fixes #4645
An SVG element has constructor name:
* `HTMLUnknownElement` in jsdom 9 and jsdom 10
* `Element` in jsdom 11
The regexp has always had `?` but it didn’t work as intended without parentheses.
Therefore `pretty-format` attempted to serialize SVG elements as ordinary objects.
**Test plan**
Added a test (which failed first) to match `Element` as `val.constructor.name`
@SimenB Thank you for outstanding example of repro repo!
For your info, I rewrote `{ plugins: prettyFormat.plugins }` because `plugins` option value needs to be an array but `plugins` prop value is an object :)
=> Fix DOMElement plugin to format SVG in jsdom 11

CHANGELOG.md, docs/CLI.md
**Summary**
Changelog & docs for #4430 
**Test plan**
Ensure tests run & docs build. Please proofread for content.
=> Clear cache docs

CHANGELOG.md, docs/MockFunctions.md, packages/jest-snapshot/package.json, packages/jest-snapshot/src/__tests__/__snapshots__/mock_serializer.test.js.snap, packages/jest-snapshot/src/__tests__/mock_serializer.test.js, packages/jest-snapshot/src/__tests__/plugins.test.js, packages/jest-snapshot/src/mock_serializer.js, packages/jest-snapshot/src/plugins.js
**Summary**
This adds a serializer to be able to easily assert on the calls of a mock.
This is very easy to implement in userland, so I understand if it's not merged 🙂 But it's been useful for me, so maybe it'll be useful for others?
(I started creating a separate module for this, but I got annoyed that I couldn't use `mock.getMockName()`, so here's a PR)
**Test plan**
New tests added
=> Add a serializer for jest.fn to jest-snapshot

docs/GettingStarted.md
[MAY BE DUPE OF #4663 ]
Looks like you recently internationalized without fixing this link.
**Summary**
Ahhh, just a broken link in the docs.  
**Test plan**
No code, just a URL.  
Bad❌  https://facebook.github.io/jest/docs/cli.html
Good ✅ https://facebook.github.io/jest/docs/en/cli.html
=> Fix bad link to jest cli docs

docs/CLI.md, docs/GettingStarted.md, docs/GlobalAPI.md, docs/ManualMocks.md, docs/MockFunctions.md, docs/MoreResources.md, docs/UsingMatchers.md
Fix applied like specified in Docusaurus documentation about linking to other docs: https://docusaurus.io/docs/en/doc-markdown.html#linking-other-documents
Fixes #4674
**Summary**
**Test plan**
=> Fix links to other documentation pages

docs/GettingStarted.md
Using Matchers link was broken. I changed the formatting. 
(using the 'Jest CLI Options' as an example)
=> UsingMatchers Link Updated

integration_tests/utils.js
**Summary**
Node 8.7 brings extra `new` before `Promise(<anonymous>)` in stack traces, so updated the regex accordingly.
**Test plan**
Travis green
=> Fix tests on Node 8.7

integration_tests/utils.js
**Summary**
As @SimenB pointed out in https://github.com/facebook/jest/pull/4680#discussion_r144473570 the regex should be updated, so it works on older and newer versions of Node 8
**Test plan**
Make sure all CI pass.
=> Make cleanupStackTrace work on older and newer Node 8 version

CHANGELOG.md, integration_tests/__tests__/test_environment_async.test.js, integration_tests/test-environment-async/__tests__/custom.test.js, integration_tests/test-environment-async/package.json, integration_tests/test-environment-async/test-environment.js, package.json, packages/jest-environment-jsdom/src/index.js, packages/jest-environment-node/src/index.js, packages/jest-runner/src/run_test.js, types/Environment.js, yarn.lock
**Summary**
Adding Async Test Environment APIs based on @cpojer's comments on #3420 & #3832
Fixes #3420
**Test plan**
_Example Puppeteer Environment_
```
class PuppeteerEnvironment extends NodeEnvironment {
constructor(config) {
super(config)
}
async setup() {
await super.setup()
this.global.__BROWSER__ = await puppeteer.launch()
}
async teardown() {
await this.global.__BROWSER__.close()
await super.teardown()
}
runScript(script) {
return super.runScript(script)
}
}
=> Add Async Test Environment APIs

packages/jest-runtime/src/script_transformer.js
**Summary**
Ignore cache write EPERM errors on Windows if we're reasonably sure they came from a cross-process race condition
**Test plan**
Race conditions are hard to test for, but I was able to verify this patch resolved the cache write errors I was seeing on Windows as part of a Jest 21 upgrade by logging out errors caught by this check and seeing several hits (alongside passing tests).
This is ideally a temporary fix for #4444. It seems the real fix is upstream at https://github.com/isaacs/node-graceful-fs/pull/119, but in the meantime, this will unblock Windows users trying to upgrade to Jest 21 or later.
=> ignore cache write EPERM errors on Windows

integration_tests/__tests__/jasmine_async.test.js, integration_tests/jasmine_async/__tests__/async_test_fails.test.js, packages/jest-environment-jsdom/src/index.js
* Send error event to Node.js process.
**Summary**
Execute following asynchronous test.
```js
it('asynchronous test', (done) => {
setTimeout(function() {
expect(false).toBeTruthy();
done();
}, 1 * 1000);
});
```
Expect:
```
expect(received).toBeTruthy()
Expected value to be truthy, instead received
false
```
Actual:
```
Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```
**Test plan**
Above test result as expected.
```
● describe ? asynchronous test
expect(received).toBeTruthy()
Expected value to be truthy, instead received
false
at __tests__/test.spec.js:23:21
at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
at ontimeout (timers.js:365:14)
at tryOnTimeout (timers.js:237:5)
at …
```
=> Fix asynchronous test will fail due to timeout issue.

CHANGELOG.md, integration_tests/utils.js, packages/jest-message-util/package.json, packages/jest-message-util/src/__tests__/__snapshots__/messages.test.js.snap, packages/jest-message-util/src/__tests__/messages.test.js, packages/jest-message-util/src/index.js, yarn.lock
**Summary**
As discussed in #4686, this removes node core stuff from the stacktraces we present to the user, not just from our own tests.
Stack trace with this PR:
Without this PR:
**Test plan**
New test added
=> Always remove node internals from stacktraces

packages/jest-util/src/__tests__/__snapshots__/validate_cli_options.test.js.snap, packages/jest-util/src/validate_cli_options.js
**Summary**
Update link of CLI args documentation when a user types a wrong argument. For instance:
```
./node_modules/.bin/jest --timeout=10000
Unrecognized option "timeout".
CLI Options Documentation:
http://facebook.github.io/jest/docs/cli.html
```
Link is currently broken (404).
**Test plan**
```
./jest --timeout=foo
```
And clicking on the link opens correct page.
=> Update CLI options link

packages/jest-cli/src/__tests__/watch.test.js, packages/jest-cli/src/__tests__/watch_filename_pattern_mode.test.js, packages/jest-cli/src/lib/update_global_config.js, packages/jest-cli/src/watch.js
**Summary**
This attempts to fix #4722  by making passWithNoTests default to true in watch mode
**Test plan**
Added new test in watch.test.js - 'passWithNoTest should be set to true in watch mode'
=> Make passWithNoTests default to true in watch mode (#4722)

packages/jest-editor-support/index.d.ts, packages/jest-editor-support/src/Runner.js, packages/jest-editor-support/src/types.js
**Summary**
Im creating my own vscode extension and need to be able start specific test in specific file and attach debugger to it...
**Test plan**
Added 2 new options:
- testNamePattern
if present process arguments --testNamePattern $testNamePattern will be added (see doc)
- testFileNamePattern
if present its value will be added as process argument (to filter test files)
---
Basically same as my previous PR #4712 except debugger part, because that would break backward-compatibility... (and new PR because i nuked my prev fork and created new one to clean up my commits)
=> added support for calling single test in single file

website/package.json
**Summary**
I've added fixes to Docusaurus to create a file at base of /docs folder that routes people to /docs/en/file.html
=> Update Docusaurus to fix rerouting broken links in docs

docs/CLI.md
Resolve #4732 
**Summary**
Despite the name, I got confused with exactly what `--testNamePattern` was used for and found I wasn't alone [StackOverflow](https://stackoverflow.com/questions/45913349/using-jest-testnamepattern-regex-or-t-option-in-package-json/)
**Test plan**
To resolve it I added an example in the docs CLI section. I ran the docs server locally and was satisfied. It's a simple change so I do not expect there should be no issue with publishing.
=> Document testNamePattern example (#4732)

packages/jest-resolve/package.json, packages/jest-resolve/src/__tests__/is_builtin_module.test.js, packages/jest-resolve/src/default_resolver.js, packages/jest-resolve/src/index.js, packages/jest-resolve/src/is_builtin_module.js
This removes the usage of the `is-builtin-module` dependency in the `jest-resolve` package to utilize a less strict method of checking for builtin node dependencies.
The change is to fix #4677 which causes jest to break when any node package is making use of a builtin filtered out by the `is-builtin-module` package. [The author has made clear that they will not include the packages](https://github.com/sindresorhus/builtin-modules/issues/2) so jest should not be utilizing this package any longer.
Using the [following repo to test for the issue](https://github.com/CNDW/mock-couch-jest)
**Before**
```
travis@travis-XPS-15-9560:~/Projects/bugreport$ yarn test
yarn test v1.0.1
$ jest
FAIL  ./test.spec.js
Some thing :
✕ should be true (26ms)
● Some thing : › should be true
Cannot find module …
```
=> adds missing node builtin modules to jest-resolve package

docs/JestObjectAPI.md, docs/TimerMocks.md, packages/jest-util/src/fake_timers.js
**Summary**
Updated docs to clarify confusing behaviour of `runTimersToTime()` (see #4723).
I've noted that the function actually advances fake timers *by* a given time (as opposed to advancing *to* a given time).
=> Update docs to clarify runTimersToTime

CHANGELOG.md, packages/jest-resolve/src/__tests__/is_builtin_module.test.js, packages/jest-resolve/src/is_builtin_module.js
**Summary**
Added an entry to the changelog for #4740, as well as using ESM exports
**Test plan**
Mostly docs change, but green CI is also expected
=> Add changelog entry for #4740

packages/jest-runtime/src/__tests__/Runtime-sourceMaps.test.js
**Summary**
Test is currently failing onde node 4 and node 6, but it's not run. (See #4630). Not sure if the fix is what we want?
/cc @felipeochoa
#3458
**Test plan**
Green CI
=> Fix Runtime-sourcemap test

CHANGELOG.md, docs/JestObjectAPI.md, docs/TimerMocks.md, examples/timer/__tests__/timer_game.test.js, flow-typed/npm/jest_v20.x.x.js, packages/jest-runtime/src/index.js, packages/jest-util/src/__tests__/fake_timers.test.js, packages/jest-util/src/fake_timers.js, types/Environment.js, types/Jest.js
**Summary**
As per #4723: added an alias for runTimersToTime, using the name suggested in the original issue.
I decided to make `runTimersToTime` the alias of `advanceTimersByTime`, on the assumption that the old name might be dropped in future.
**Test plan**
Does this need to be tested, as it's just an alias of an existing function?
=> Add advanceTimersByTime(), keep runTimersToTime() as alias

CHANGELOG.md, integration_tests/__tests__/resolve.test.js, integration_tests/resolve/__tests__/resolve.test.js, packages/jest-resolve/src/default_resolver.js
**Summary**
We bumped into a problem trying to use Yarn Workspaces with Jest in the React repo.
It is the same issue as described in https://github.com/facebook/jest/issues/3830.
In our case, we had `packages/*` symlinked through `node_modules`.
We noticed that importing the same file with the path `root/packages/react/module` from a test in `root/packages/react/folder/__tests__` produced a different instantiation depending on how it is imported:
* Through the `react/folder/module` symlink.
* Or by the relative `../module` path.
This is because the old resolving mechanism established resolved paths as:
* `react/folder/module` => `repo/node_modules/react/folder/module.js`
* `../module` => `repo/packages/react/folder/module.js`
So Jest treated them as two different modules. This created …
=> Preserve module identity for symlinks

integration_tests/__tests__/nested_event_loop.test.js, integration_tests/nested_event_loop/__tests__/nested_event_loop.test.js, integration_tests/nested_event_loop/package.json, packages/jest-environment-jsdom/src/index.js
This add a failing integration test for behavior React relies on.
It passes before https://github.com/facebook/jest/pull/4669, but now fails.
<s>Demonstrates</s> Fixes https://github.com/facebook/jest/issues/4764.
=> Don't report errors errors as unhandled if there is an existing "error" event handler

CHANGELOG.md, packages/jest-config/src/__tests__/__snapshots__/normalize.test.js.snap, packages/jest-config/src/__tests__/jest-preset.json, packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js
=> include error message for preset json

.circleci/config.yml, CHANGELOG.md, packages/jest-cli/package.json, packages/jest/package.json
**Summary**
https://github.com/facebook/jest/pull/4767#discussion_r147131131
I'm thinking it's a good idea to do this separately from other changes which require node 4.
(also :tada:)
**Test plan**
Passing CI
=> Drop support for node 4

CHANGELOG.md, package.json, packages/jest-environment-jsdom/package.json, packages/jest-environment-jsdom/src/index.js, yarn.lock
**Summary**
Now that we've dropped node 4, we can finally do this
**Test plan**
Green CI
=> Upgrade to JSDOM@11

packages/jest-environment-jsdom/package.json, packages/jest-environment-jsdom/src/index.js, yarn.lock
**Summary**
@Zirro pointed out an issue in https://github.com/facebook/jest/pull/4770#issuecomment-340017198. While jsdom might release before before Jest 22, in case it doesn't this means we don't have to remember it.
Also changed the name of `this.document` as pointed it in that PR.
**Test plan**
Green CI
=> Pin jsdom to 11.2

CHANGELOG.md, packages/expect/src/index.js, packages/pretty-format/src/__tests__/pretty_format.test.js, packages/pretty-format/src/index.js
**Summary**
In this commit, we are creating a new custom error called `PrettyFormatPluginError`, this error is thrown by `prettyFormat` function when a serializer throws an error.
In the `expect` module, we skip `Error.captureStackTrace` if the error name is `PrettyFormatPluginError`, this way the stack trace stays intact.
Fixes #3302
**Test plan**
Given a test file `foo.test.js`:
```js
test("should match the snapshot", () => {
const bar = {
foo: {
x: 1,
y: 2
}
};
expect(bar).toMatchSnapshot();
});
```
And a custom snapshot serializer `my-serializer-module.js`
```js
test: val => {
throw new Error("Where is this error?");
},
print: val => ""
};
```
And a `package.json`:
```json
{
"jest": {
"snapshotSerializers": ["./my-serializer-module"]
}
}
```
When `jest` is run, with …
=> Fix stack trace for errors thrown by snapshot serializers

docs/ExpectAPI.md
In the [comment](https://github.com/facebook/jest/issues/1377#issuecomment-339112450) in issue #1377  it was highlighted that the `.rejects` example in the docs doesn’t work. This PR fixes that by introducing a simpler example.
=> Fixed broken example in the docs.

packages/jest-haste-map/src/__tests__/index.test.js
**Summary**
`jest-haste-map` doesn't properly recover from duplicates when such state is stored in the cache (on the other hand, processing of duplicate by the watching mode is already correct and covered by tests). This changeset adds a test that demonstrate the brokeness. Next step will be to fix the behavior, and we can then switch the test to the correct values.
**Test plan**
yarn jest packages/jest-haste-map/src/__tests__/index.test.js
=> jest-haste-map: add test to demo broken duplicates behavior

packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js
**Summary**
When we load the haste map from the cache, we need to keep track of all the files that were removed, or even which module name changed, so that we can recover other modules with which there were potentially sharing names before. For example, if we delete a module "Strawberry", maybe this allows another module that's the legitimate Strawberry to be available. Or, if we renamed a module's name from "Strawberry" to "Blackberry", maybe this allows another module to be deduplicated the same way.
**Test plan**
Unit test. However, I must add another test case to test file renames (not just deletion) before I land. Opening the PR to get a first feedback on the code.
=> jest-haste-map: properly recover duplicates when files change

packages/jest-worker/README.md, packages/jest-worker/src/__tests__/child.test.js, packages/jest-worker/src/__tests__/index.test.js, packages/jest-worker/src/__tests__/worker.test.js, packages/jest-worker/src/index.js, packages/jest-worker/src/types.js, packages/jest-worker/src/worker.js
One of the requirements of the API was that we needed a way of ending childs that unexpectedly leave. We introduce the `maxRetries` variable; which measures how many times a child can be restarted (per call), before emitting an `error` event.
Tests were added so that a 100% coverage is still ensured on the module, as it was before. Also, `WorkerOptions` type was made stricter by making required the `forkOptions` property (which was anyway always passed).
=> Add max retries per call, defaulting to 3

packages/jest-mock/src/index.js
While developing, I found annoying that an invalid `spyOn` returns a very cryptic error, caused by the lack of checking on `fn`; it calls `fn._isMockFunction` without checking first if `fn` is actually something. 
This PR improves the messaging we give when we find these kind of errors.
Primitive keys cannot be spied because of how they work, see the [ECMA-262 specification](https://www.ecma-international.org/ecma-262/8.0/index.html#sec-getv) for more info:
>  If the value is not an object, the property lookup is performed using a wrapper object appropriate for the type of the value [...]
=> Improve error messaging from "spyOn"

packages/jest-haste-map/package.json, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/__tests__/worker.test.js, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/types.js, packages/jest-haste-map/src/worker.js, yarn.lock
Move all the `jest-haste-map` logic from `worker-farm` to `jest-worker`. Tests also needed some updates (mostly because mocking is a bit different now).
The best thing is that Flow types can now be shared! So the parent file imports the type of the callback, and uses it for typing the interface that the worker exposes.
No more callbacks, no more `Promise` wrapping... feels good 😄
=> Migrate jest-haste-map to jest-worker

CHANGELOG.md
**Summary**
See https://github.com/facebook/jest/issues/4829#issuecomment-341558679
**Test plan**
Docs only
=> Mark #4668 as breaking

integration_tests/__tests__/watch_requires_hq_or_git.test.js, integration_tests/watch_requires_hq_or_git/__tests__/example.test.js, integration_tests/watch_requires_hq_or_git/package.json, packages/jest-cli/src/cli/index.js
**Summary**
Whenever you run `jest --watch` in a non git/hq repository you will see the following error:
```
Determining test suites to run...Error: This promise must be present when running with -o.
at /path/to/node_modules/jest-cli/build/search_source.js:192:17
at next (native)
at step (/path/to/node_modules/jest-cli/build/search_source.js:20:362)
at /path/to/node_modules/jest-cli/build/search_source.js:20:592
at /path/to/node_modules/jest-cli/build/search_source.js:20:273
at SearchSource.getTestPaths (/path/to/node_modules/jest-cli/build/search_source.js:204:10)
at /path/to/node_modules/jest-cli/build/run_jest.js:45:31
at next (native)
at step (/path/to/node_modules/jest-cli/build/run_jest.js:24:380)
at /path/to/node_modules/jest-cli/build/run_jest.js:24:540
```
To make it work I would …
=> Use watchAll fallback for non git/hq projects

packages/jest-cli/package.json, packages/jest-cli/src/generate_empty_coverage.js, packages/jest-cli/src/reporters/__tests__/coverage_worker.test.js, packages/jest-cli/src/reporters/coverage_reporter.js, packages/jest-cli/src/reporters/coverage_worker.js, yarn.lock
This PR migrates `jest-cli` to use `jest-worker`, instead of `worker-farm`. As a consequence of this, some additional changes were done:
* `pify` is not needed anymore as well.
*  Interfaces are now shared between parent and child processes, so we ensure they stay in sync.
* Tests needed small adjustments as well.
Although it increases the scope of the diff, I found convenient to migrate `_addUntestedFiles`, from a `Promise`-based approach to an `async`/`await` approach. The reasoning behind it is that I also moved the logic for printing the error from the worker to the parent and simplified it.
=> Migrate jest-cli to jest-worker

packages/jest-runner/package.json, packages/jest-runner/src/__tests__/test_runner.test.js, packages/jest-runner/src/index.js, packages/jest-runner/src/test_worker.js
This PR migrates `jest-runner` to use `jest-worker`, instead of `worker-farm`. As a consequence of this, some additional changes were done:
* `pify` is not needed anymore as well.
*  Interfaces are now shared between parent and child processes, so we ensure they stay in sync.
* Tests needed small adjustments as well.
=> Migrate jest-runner to jest-worker

CHANGELOG.md, packages/jest-docblock/src/__tests__/index.test.js, packages/jest-docblock/src/index.js, yarn.lock
**summary**
I recently [discovered](https://github.com/Automattic/wp-calypso/pull/18726/files#r144200619) that the `parseWithComments` function is stripping away links from pragmas.  I've created a failing test case to illustrate the issue.
Is this intentional?
If not I can update the pull-request with a fix
---
Example In:
```js
/**
* @see: https://example.com
*/
```
Example Out:
```js
/**
* @see:
*/
```
=> [jest-docblock] pragmas should preserve urls

packages/jest-snapshot/src/__tests__/__snapshots__/mock_serializer.test.js.snap, packages/jest-snapshot/src/mock_serializer.js
**Summary**
Fixes #4835. /cc @mjesun 
**Test plan**
Changed snapshots
=> Print jest mock fuctions as `MockFunction` in jest-snapshot

packages/jest-snapshot/src/__tests__/__snapshots__/mock_serializer.test.js.snap, packages/jest-snapshot/src/__tests__/mock_serializer.test.js, packages/jest-snapshot/src/mock_serializer.js
**Summary**
Balance the following constraints /cc @mjesun
Before a mock function has been called, serialize it **similar to function**, especially when it is property of JavaScript object or React element.
Example adapted from https://github.com/facebook/jest/issues/4829#issue-270743476
```js
Object {
"hasMore": [MockFunction],
"loadMore": [MockFunction],
"refetchConnection": [MockFunction],
}
```
Serialize non-empty array so it is **impossible to accidentally match** with an object https://github.com/facebook/jest/issues/4835#issue-271013580
EDIT selected different example which has **non-default name** from a test case:
```js
Object {
"fn": [MockFunction MyConstructor] {
"calls": Array [
Array [
Object {
"name": "some fine name",
},
],
],
},
}
```
This pull request makes incremental …
=> Omit empty calls array in plugin for mock functions

integration_tests/__tests__/jest_changed_files.test.js, integration_tests/test-environment-async/__tests__/custom.test.js, package.json, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/__tests__/spy_matchers.test.js, packages/expect/src/matchers.js, packages/jest-circus/src/utils.js, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/get_no_test_found_verbose.js, packages/jest-cli/src/reporters/coverage_reporter.js, packages/jest-config/src/normalize.js, packages/jest-diff/src/__tests__/diff.test.js, packages/jest-docblock/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js, packages/jest-resolve/src/__tests__/resolve.test.js, packages/jest-resolve/src/index.js, packages/jest-runtime/src/__tests__/instrumentation.test.js, packages/jest-runtime/src/__tests__/script_transformer.test.js, packages/pretty-format/src/__tests__/immutable.test.js, packages/pretty-format/src/index.js, packages/pretty-format/src/plugins/immutable.js, types/Environment.js, types/Process.js, yarn.lock
**Summary**
This upgrades to the fresh prettier 1.8 release. It also formats all markdown files with it.
I'm not sure if the md lint should be part of the normal `yarn lint` run?
I tried removing the ignore of md files from the prettier eslint rule, but prettier then expected trailing newline in the codeblock. So I left it alone 🙂 
**Test plan**
Green CI
=> Upgrade to Prettier 1.8

packages/jest-environment-node/src/index.js, packages/jest-util/src/fake_timers.js
Fixes #4830; references to timers can be null.
=> Fix timers: reference can be null

docs/TimerMocks.md
**Summary**
`runTimersToTime` was renamed to `advanceTimersByTime` in 21.3.0. This updates the docs to show the functionality exists in previous versions.
=> Add availability note for advanceTimersByTime

CHANGELOG.md, packages/jest-mock/README.md, packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
**Summary**
This PR adds the internal behaviour to the mock state to record a timestamp on every invocation to allow community matchers to solve #4402.
I'm happy to add the matcher wanted in #4402 to [jest-extended](https://github.com/jest-community/jest-extended/issues/98)
**Test plan**
=> Mock timestamp

packages/jest-cli/package.json, packages/jest-cli/src/__tests__/__snapshots__/watch.test.js.snap, packages/jest-cli/src/__tests__/watch.test.js, packages/jest-cli/src/lib/watch_plugin_registry.js, packages/jest-cli/src/types.js, packages/jest-cli/src/watch.js, packages/jest-config/src/index.js, packages/jest-config/src/valid_config.js, test_utils.js, types/Config.js
Resolves #4824
This is my first nontrivial contribution to Jest so please be gentle :)
This makes watch mode pluggable, allowing for arbitrary watch plugin
modules to be registered in the global config and used to generate
prompt messages and key listeners when watch mode is activated.
When a particular plugin is activated, Jest no longer handles keypresses
until the plugin calls the `end` callback (see #4824 for design details)
This currently does not implement any existing watch functionality as a
plugin and is rather adding the infrastructure to do so. That will
follow soon :)
@cpojer @aaronabramov I'm not sure if the globalConfig is the best place
for this (to be honest I can't make sense of the the sheer number of
config types). I also haven't gotten around to running a manual test …
=> Implement pluggable watch mode

packages/jest-cli/src/lib/watch_plugin_registry.js
**Summary**
Local `yarn lint` now reports 4 errors because upgrade to prettier 1.8 in #4852 was merged after #4841 was opened:
```sh
38:30  error  Replace `pluginModulePath` with `⏎··········pluginModulePath⏎········`  prettier/prettier
48:30  error  Replace `pluginModulePath` with `⏎··········pluginModulePath⏎········`  prettier/prettier
53:30  error  Replace `pluginModulePath` with `⏎··········pluginModulePath⏎········`  prettier/prettier
61:30  error  Replace `pluginModulePath` with `⏎··········pluginModulePath⏎········`  prettier/prettier
```
**Test plan**
yarn lint
=> Fix prettier lint errors in watch_plugin_registry.js

CHANGELOG.md, docs/ExpectAPI.md, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/index.js, packages/expect/src/to_throw_matchers.js
fixes #3601
From docs
```js
return expect(Promise.reject('octopus')).rejects.toBe('octopus');
```
In real app, an `Error` object must be rejected.  
Fixed to
```js
return expect(Promise.reject(new Error('octopus'))).rejects.toThrow('octopus');
```
=>  fix .toThrow for promises

packages/jest-resolve/src/__tests__/resolve.test.js, packages/jest-resolve/src/index.js
**Summary**
Currently, react native files with extensions other than `.js` aren't imported when running jest in a react native environment. This is because of a hardcoded `.js` in the jest resolver. It should use the configuration's `moduleFileExtensions`.
**Test plan**
For a jest config of
```js
globals: {
"ts-jest": {
tsConfigFile: "tsconfig.test.json",
},
},
preset: "react-native",
moduleFileExtensions: [
"js",
"jsx",
"ts",
"tsx",
],
};
```
a test of
```js
import testEnvironment from "../__mocks__/testImport";
describe("Native test environment", () => {
it("finds the native version of the dependency", () => {
expect(testEnvironment).toBe("native");
});
});
```
`__mocks__/testImport`
```ts
export default "web";
```
`__mocks__/testImport.native`
```ts
export default …
```
=> Use extensions from configuration for react native module resolution

CHANGELOG.md, docs/Configuration.md
**Summary**
The Sample code for using a custom environment in testEnvironment doesn't show where the NodeEnvironment is coming from. This PR includes this missing dependency.
**Test plan**
Using jest@test with similar sample code resulted in this error message:
ReferenceError: NodeEnvironment is not defined. 
Including jest-environment-node@test solved the issue and using a custom environment worked as expected.
=> Include missing dependency in TestEnvironment sample code

packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/jasmine/Env.js, packages/jest-runtime/src/index.js, packages/jest-util/src/__tests__/create_process_object.test.js, packages/jest-util/src/__tests__/deep_cyclic_copy.test.js, packages/jest-util/src/create_process_object.js, packages/jest-util/src/deep_cyclic_copy.js, packages/jest-util/src/install_common_globals.js
This diff rewrites how the fake `process` variable is created and injected; in order to better mimic the way it looks and improve sandboxing. Now, `process` is built from `Process.prototype`, then all the constructors on the prototype chain are executed (i.e. `Process`, `EventEmitter`, and `Object`); and finally the remaining properties are copied as before.
This gives as a result an object that can independently handle events added via `process.on`, but also passes validations like `Object.getPrototypeOf(process) !== Object.prototype`.
The risk is that someone is already using `process.on` to try attaching to the **real** `process`; and this will make the test break. But I think it's fine.
=> Rewrite how common globals are installed in "global"

CHANGELOG.md, docs/SetupAndTeardown.md
**Summary**
Add clarification for hook execution order. Existing problem may include:
* Misconception that the top-level `before` hooks are ran before each `describe` _or_ `test` block, and not necessarily every `test` block (although this is addressed in the docs with the sentence "By default, the `before` and `after` blocks apply to every test in a file.", this illustration makes it more explicit)
* Confusion about the execution order of nested `beforeAll` hook in relation to top-level `beforeEach`
* Likewise, confusion about the execution order of nested `afterAll` hook in relation to top-level `afterEach`
**Test plan**
I could not test the website / formatting is correct due to #4911 and #4912, but it is valid Markdown and fits within 80 character line-length limit.
=> Add clarification for hook execution order

.circleci/config.yml, packages/jest-leak-detector/.npmignore, packages/jest-leak-detector/README.md, packages/jest-leak-detector/package.json, packages/jest-leak-detector/src/__tests__/__snapshots__/index.test.js.snap, packages/jest-leak-detector/src/__tests__/index.test.js, packages/jest-leak-detector/src/index.js, yarn.lock
This PR introduces a new module, `jest-leak-detector` intended to verify that an object is garbage collectable after a set of operations. Its usage is done by creating a `LeakDetector` instance with the object we want to test; and later calling `LeakDetector.isLeaked()`, which will return a boolean indicating if the object has still references.
This is a second evolution of #4873, where we use `weak` to create the weak reference instead of using a `WeakSet`, which was a hack. Thanks to @arcanis for the suggestion!
=> Initial version of jest-leak-detector

docs/ExpectAPI.md, docs/UsingMatchers.md, packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/matchers.js, packages/jest-jasmine2/src/__tests__/__snapshots__/matchers.test.js.snap
**Summary**
This replaces the strict equality (`===`) check with `Object.is` in the `toBe` matcher. `Object.is` works exactly the same as triple equals except:
```
> Object.is(NaN, NaN)
true
> NaN === NaN
false
```
```
> Object.is(-0, +0)
false
> -0 === +0
true
```
Hence, this allows us to fix #4907.
**Test plan**
Added two tests for `toBe` matcher. I couldn't test the docs due to #4911 and #4912, but changes are trivial.
=> Replace identity equality with Object.is in toBe matcher

packages/jest-editor-support/src/Runner.js
* Allow additional arguments to runJestWithUpdateForSnapshots method
**Summary**
This allows passing custom parameters to the `runJestWithUpdateForSnapshots` method allowing to update specific snapshots by a test name pattern.
=> Additional arguments to runJestWithUpdateForSnapshots

packages/jest-worker/src/__tests__/index.test.js, packages/jest-worker/src/index.js
When all workers are idling (i.e. they are not doing any work), worker `1` keeps getting all the jobs. This is due to the `for` loop that pushes sequentially all jobs from worker `0` to worker `n-1`. Unless explicitly wanted (because of a `computeWorkerKey` present), this is usually not a desired behavior.
Adding an offset and a modulo should do the trick. When all workers are busy, the logic is not affected, though; the first available worker will still pick the job.
=> Rotate workers when they are all idling

CHANGELOG.md, packages/jest-runtime/package.json
**Summary**
This reverts commit 1fcffab0b86e16e84ce66d2321e03a4744268f74.
As discussed in #4557
**Test plan**
=> Revert "jest-runtime: move babel-core to peer dependenies (#4557)"

website/README.md, website/package.json
Running `npm i` installs `docusaurus 1.0.0-beta.13`, and that makes `npm start` and `npm run build` to fail. This PR fixes the issue by keeping docusaurus at 1.0.0-beta.4.  
I also updated the instructions on how to run the server. They're right now.
=> Website: Fix npm start from failing

CHANGELOG.md, docs/Configuration.md, packages/jest-cli/src/reporters/__tests__/coverage_reporter.test.js, packages/jest-cli/src/reporters/coverage_reporter.js
**Summary**
Right now you can specify a global threshold in Jest and a threshold for files that match a glob pattern. But you can't specify a threshold for a given directory. This pull request adds that functionality without taking away any functionality from before. With this pull request there will be three possible ways to set a coverage threshold:
1. `global` applies the threshold to every covered file.
2. `path` applies the threshold to a path (either a directory or a file).
3. `glob` applies the threshold to any file matching a glob pattern.
For example, before you could do:
```json
{
"coverageThreshold": {
"global": {
"branches": 50,
"functions": 50,
"lines": 50,
"statements": 50
},
"./src/components/**/*.js": {
"branches": 40,
"statements": 40
}, …
```
=> Add combined coverage threshold for directories

packages/jest-worker/src/__tests__/index.test.js, packages/jest-worker/src/index.js
As mentioned in https://github.com/facebook/jest/issues/4897#issuecomment-344918711, jest-worker runs in `silent` mode by default to be able to pipe everything to a stream.
Overriding the forkOptions with `silent: false` causes it to fail because the stream is not piped. This PR fixes this small issue, while keeping the same default behavior.
https://github.com/facebook/jest/issues/4897
```
TypeError: Cannot read property 'once' of null
at PassThrough.add (/Users/rogelioguzman/dev/jest/node_modules/merge-stream/index.js:27:11)
at new exports.default (/Users/rogelioguzman/dev/jest/packages/jest-worker/build/index.js:80:14)
at BaseTestRunner.runTests (/Users/rogelioguzman/dev/create-jest-runner/build/createJestRunner.js:44:22)
at /Users/rogelioguzman/dev/jest/packages/jest-cli/build/test_sch …
```
=> Fix jest-worker when `silent: false`

packages/jest-cli/package.json, packages/jest-cli/src/__tests__/watch.test.js, packages/jest-cli/src/lib/watch_plugin_registry.js, packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js
**Summary**
This PRs does a couple of small things
This was not being normalized and and it also adds more tests to it.
It was previously using a relative path to the src directory, which meant that it was never using the transpiled version, resulting in this error.
```
/Users/rogelioguzman/dev/jest/packages/jest-resolve/src/default_resolver.js:10
import type {Path} from 'types/Config';
^^^^^^
SyntaxError: Unexpected token import
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:588:28)
at Object.Module._extensions..js (module.js:635:10)
at Module.load (module.js:545:32)
at tryModuleLoad (module.js:508:12)
at Function.Module._load (module.js:500:3)
at Module.require (module.js:568:17)
at require (internal/module.js:11:18)
at …
```
=> Couple of small fixes for watchPlugins

packages/jest-runner/src/index.js
**Summary**
When locally running tests, the IO differs between children and parent workers, resulting in Travis-on-master-like failures caused by suppressed colors. Inheriting the stdio for `jest-runner` workers fixes the thing. 
**Test plan**
Tests run fine locally.
=> Inherit stdio for jest-runner

CHANGELOG.md, packages/pretty-format/src/__tests__/immutable.test.js, packages/pretty-format/src/__tests__/pretty_format.test.js, packages/pretty-format/src/index.js, packages/pretty-format/src/plugins/immutable.js
**Summary**
Fixes #4580 and #4922
Because the mock identity object for CSS Modules returns the key as the value for **any** key:
* Comparing sentinel properties to `true` avoids **false positive** in `Immutable` plugin `test` method
* Comparing `val.constructor === 'function'` avoids **undefined** as name of object
See [Mocking CSS Modules](http://facebook.github.io/jest/docs/en/webpack.html#mocking-css-modules)
**Test plan**
Added 2 tests which failed before changes to code, and then fixed them to fail for right reason :)
=> Fix errors when identity-obj-proxy mocks CSS Modules

packages/pretty-format/src/plugins/immutable.js
**Summary**
This `typeof` jumped out at me when I looked at diffs related to #4850
The incorrect code was working because Immutable Record has `_keys` property in v3, so let’s call `getRecordEntries` regardless of version.
**Test plan**
Confirmed by local test with immutable 3.8.1
=> Refactor to delete incorrect typeof in Immutable plugin

website/blog/2017-01-30-a-great-developer-experience.md, website/pages/en/index.js
We recently [changed Repl.it](https://repl.it/site/blog/new_repls) so that repls are auto-saved. That also means that we create a repl every time someone goes to `repl.it/languages/<language>`.
So right now every time the Jest homepage is loaded we're creating a new repl. Instead I'm changing this to link to a pre-existing one I created. Folks who click "open in repl.it" will then be able to fork it and do whatever with it.
=> Update Repl.it urls to use direct Url

docs/GettingStarted.md
In some shells like zsh, copying and pasting 
```
npm install --save-dev babel-jest babel-core@^7.0.0-0 @babel/core
```
Might produce:
```
zsh: no matches found: babel-core@^7.0.0-0
```
Which can lead to confusion, so placing it under quotes might help
=> put npm install command within quotes in the doc

packages/jest-runtime/src/__tests__/script_transformer.test.js, packages/jest-runtime/src/script_transformer.js
This PR adds an extra, optional parameter, into the `Options` object passed to `transform`. The option is named `isCoreModule`, and it is intended to be used later by the re-injection of native modules inside the contexts.
It is required to ensure that modules are never transformed or instrumented, but that they are wrapped and returned as a `vm.Script` instance.
=> Add an extra option to inform that a module is a core NodeJS module

packages/jest-util/src/__tests__/install_common_globals.test.js, packages/jest-util/src/install_common_globals.js
This adds `DTRACE_` globals to the fake `global` object. This is required to
1. make a better sandboxing, and
2. allow future work of re-injecting native modules possible (since things like `net.Socket` do call these methods).
Methods are wrapped in another file so if people modifies them (e.g. by adding a static property) they will not prevent garbage collection.
=> Add additional globals

packages/jest-haste-map/src/crawlers/__tests__/node.test.js, packages/jest-util/src/__tests__/deep_cyclic_copy.test.js, packages/jest-util/src/create_process_object.js, packages/jest-util/src/deep_cyclic_copy.js
This PR improves the way the `process` object is created in two ways:
1. It aims to rewrite the way deep cyclic cloning is done:
1. It uses a specialized method for `Array`s.
2. It copies properties by using `getOwnPropertyDescriptors` and `defineProperties`.
3. It gives a blacklist argument for the root level object.
​
2. Using the blacklist, it avoids copying `mainModule`, which contains a reference to the main module, plus all of the other modules loaded so far in memory.
The total improvement on a raw Node instance is approximately of 40%; but the improvement grows as the amount of previously loaded modules also grows. In my case, I've been able to observe up to 20x performance by artificially loading a bunch of modules before calling `createProcessObject`.
=> Improve process object creation

integration_tests/__tests__/leak_detection.test.js, integration_tests/__tests__/require_all_modules.test.js, integration_tests/leak-detection/package.json, integration_tests/leak-detection/test.js, integration_tests/require-all-modules/package.json, integration_tests/require-all-modules/test.js, jest-inspect, packages/jest-editor-support/src/__tests__/runner.test.js, packages/jest-jasmine2/src/index.js, packages/jest-message-util/src/index.js, packages/jest-runner/src/run_test.js, packages/jest-runtime/src/index.js, packages/jest-runtime/src/script_transformer.js, packages/jest-util/src/__tests__/create_process_object.test.js, packages/jest-util/src/index.js, packages/jest-util/src/install_common_globals.js
This PR improves the sandboxing for native modules. Every time a native require is detected, Jest will:
* introduce it inside the sandbox by re-evaluating its source code, exposed through `process.binding('natives')`; which differs from the previous approach where `require(moduleName)` was done on the main context; and
​
* switch the `require` logic to know it's inside a native module (thus, `internal/util` will not resolve to the NPM `internal` module, but to the native Node one).
This kills all memory leaks related to `process` and native module modification. I have added an integration test with the most common use cases. Executing the test (`./jest leak_detection`) on a previous commit will fail because of detected leaks.
**It also makes the `jest` test suite leak free itself (tried …
=> Re-inject native Node modules

packages/jest-leak-detector/package.json, packages/jest-leak-detector/src/index.js
On systems that do not support Node bindings, adding `weak` as a dependency will make it crash. Since most of the times `jest-leak-detector` is not used at all, making the dependency optional and delaying its instantiation will fix the issue.
Tested by running `./jest jest-leak-detector`.
=> Make "weak" optional dependency and check it at runtime

CHANGELOG.md, packages/jest-util/package.json, packages/jest-util/src/fake_timers.js
**Summary**
`jest-util` should not depend on `jest-mock`.
**Test plan**
Green CI
=> fix: jest-util should not depend on jest-mock

CHANGELOG.md, integration_tests/__tests__/jasmine_async.test.js, integration_tests/__tests__/timeouts.test.js, packages/jest-jasmine2/src/__tests__/queue_runner.test.js, packages/jest-jasmine2/src/queue_runner.js
> Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
* Using old `jasmine.DEFAULT_TIMEOUT_INTERVAL` api.
* Does not say how long the timeout is.
> Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
Improved developer usability and understanding.
* Updated API method `jest.setTimeout`.
* Shows the value of `timeout` used.
Updated test in `queue_runner`.
=> Update Timeout error message to `jest.timeout` and display current timeout value

docs/ExpectAPI.md
**Summary**
Emphasise that `.rejects` and `.resolves` still require the assertion to be returned, in response to #4997.
**Test plan**
Validated output was valid at least [in GitHub's Markdown renderer](https://github.com/Vinnl/jest/blob/08a7a8505716fc85270ea78abb940d124336ed15/docs/ExpectAPI.md#resolves).
=> Emphasise required return

CHANGELOG.md, docs/ExpectAPI.md
Fixes: https://github.com/facebook/jest/issues/4916
**Summary**
Update `expect.anything()` sample code. Calling `[1].map(mock);` fails because `map` adds two extra parameters to the mock call (`index` and `array`).
**Test plan**
expect-anything.test.js
```js
test('map calls its argument with a non-null argument', () => {
const mock = jest.fn();
[1].map(x => mock(x));
expect(mock).toBeCalledWith(expect.anything());
});
```
```bash
> jest "test/expect-anything.test.js"
PASS  test/expect-anything.test.js
✓ map calls its argument with a non-null argument (5ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Time:        0.592s, estimated 1s
Ran all test suites matching /test\/expect-anything.test.js/i.
```
=> docs: update expect.anything() example

CHANGELOG.md, integration_tests/__tests__/transform-linked-modules.test.js, integration_tests/transform-linked-modules/__tests__/linked-modules.test.js, integration_tests/transform-linked-modules/ignored/normal.js, integration_tests/transform-linked-modules/ignored/symlink.js, integration_tests/transform-linked-modules/package.json, integration_tests/transform-linked-modules/package/index.js, integration_tests/transform-linked-modules/preprocessor.js, packages/jest-runtime/src/script_transformer.js
**Summary**
This will use the realpath to match the transformers in case the path
is a symlink. This will solve an issue where files which are linked by
lerna or npm link are not transformed.
Currently a solution for this problem would be a configuration like:
```json
{
"transformIgnorePatterns": [
"<rootDir>/node_modules/"
]
}
```
=> Use realpath to match transformers

packages/jest-leak-detector/src/index.js
Make sure that the error we got is related to `MODULE_NOT_FOUND` to show a meaningful message. If not, throw the error as-is.
=> Ensure thrown error is related to module not found

CHANGELOG.md, integration_tests/__tests__/__snapshots__/to_throw_error_matching_snapshot.test.js.snap, integration_tests/__tests__/to_throw_error_matching_snapshot.test.js, packages/expect/src/index.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest_expect.js, packages/jest-jasmine2/src/jest_expect.js, packages/jest-snapshot/src/__tests__/throw_matcher.test.js, packages/jest-snapshot/src/index.js
**Summary**
Resolve #4946
**Test plan**
`yarn jest --testPathPattern="throw_matcher"`
=> Fix throw matcher error support

packages/jest-environment-jsdom/package.json, yarn.lock
`jsdom` in `11.4.0` has a bug related to how the `files` property is treated in `<input type="file">`'s. This got fixed by the awesome JSDOM folks in https://github.com/tmpvar/jsdom/issues/2063; so upgrading will fix the issue for us as well.
=> Upgrade "jsdom" to the latest version (11.5.1)

CHANGELOG.md, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init.js, packages/jest-cli/src/reporters/__tests__/__snapshots__/get_snapshot_status.test.js.snap, packages/jest-cli/src/reporters/__tests__/get_snapshot_status.test.js, packages/jest-cli/src/reporters/get_snapshot_status.js, packages/jest-cli/src/test_result_helpers.js, packages/jest-cli/src/test_scheduler.js, packages/jest-jasmine2/src/index.js, packages/jest-snapshot/src/State.js, types/TestResult.js
**Summary**
Resolve #5005
**Test plan**
=> Explain which snapshots are obsolete

packages/jest-config/src/normalize.js
It makes sense to have `onlyChanged` set to false when we pass `all`; but when passing a `testPathPattern`, `onlyChanged` has to acquire the value of `watch`. This is needed so that `get_changed_files_promise.js` actually creates and returns the corresponding promise.
=> Fix watch mode when a pattern is passed

packages/jest-util/src/create_process_object.js
The native `EventEmitter` module will not create an `_events` collection, if there is already an existing one ([see code here](https://github.com/nodejs/node/blob/master/lib/events.js#L66-L69)).
This causes that the existing listeners are not re-initialized in the deep copied `process` object, so tests triggering listeners will also trigger the original Jest listeners. The fix is simple: avoid copying the `_events` property so the object gets re-initialized.
Also fixes the `./child` test from `jest-worker` when running in parallel mode.
=> Fix test and improve process sandboxing

package.json, packages/jest-runtime/src/__tests__/runtime_jest_fn.js
**Summary**
I discovered that the `testMatch` in the root package.json meant that a few test suites did not run.
One was simply old, so I deleted it. Then a bunch of extra files in `__tests__` tried to run, so I ignored them.
But it still leaves 3 tests which fails.
**Test plan**
Green CI (eventually)
=> Remove testMatch from package.json

CHANGELOG.md, packages/jest-cli/src/cli/index.js, packages/jest-runtime/src/script_transformer.js, packages/jest-util/src/index.js
**Summary**
Fixes #5030
Node 9.2 includes https://github.com/nodejs/node/pull/15776, which added more strict input checking (in addition to adding the API we really should be using). Passing in the encoding we want fixes the crash.
**Test plan**
Manual verification of node 9.2.
=> Use `fs.realpathSync.native` if available

CHANGELOG.md, packages/pretty-format/src/__tests__/pretty_format.test.js, packages/pretty-format/src/index.js, types/PrettyFormat.js
Fixes #4956
If the returned value also has `toJSON` method:
* It can cause an error: Maximum call stack size exceeded
* It customizes stringification behavior beyond the contract with `JSON.stringify`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior
Can y’all think of another way to fix this?
I don’t think plugins need another arg. However, they can call printer with optional arg if needed.
**Test plan**
Updated title and expected result of existing test
=> Do not call toJSON recursively in pretty-format

CHANGELOG.md, packages/jest-jasmine2/src/index.js
**Summary**
When jsdom is installed, source-map-support does this:
https://github.com/evanw/node-source-map-support/blob/master/source-map-support.js#L110
Which for me caused a massive slowdown. With this patch my tests go from 99s to 74s to run and an individual test suite 16s to 4s.
**Test plan**
Jest can only run in node - I am not sure this needs tests?
=> don't let source-map-support use xhr - 25-75% speed improvement

examples/react-native/__tests__/__snapshots__/intro.test.js.snap, examples/react-native/package.json, examples/react-native/yarn.lock
**Summary**
Turns out we were still using RN 0.4 and React 15. I upgrade those + update the snapshots for the RN repo. The downside is that it now uses `RTCScrollView` to render. This is an RN thing and not a Jest thing and we can fix it later.
**Test plan**
On Node.js 9, Jest will pass the RN test
=> Make Jest work with latest react-native on node 9.

.circleci/config.yml, integration_tests/__tests__/failures.test.js
**Summary**
Node 9 is out, we should test on it.
Thoughts on doing full CI run on node 8, and partial on node 6? Node 8 is LTS now, and it should speed up the build somewhat
**Test plan**
Green CI
=> Build on node 9 on Circle

CHANGELOG.md, packages/jest-config/src/__tests__/__snapshots__/normalize.test.js.snap, packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js
**Summary**
This fixes #3793 by adding the path separator escaping that is used in watch mode to the `--testPathPattern` and default `<regexForTestFiles>` command line arguments.
<br/>
**Test plan**
Since there were no existing tests for `testPathPattern`, this PR adds tests for the existing behavior as well as the fix for path separator escaping on Windows systems.
I have confirmed this works on my Windows setup:
```
yarn build
yarn jest jest-config/src/__tests__/normalize
```
This would previously fail with:
```
Pattern: jest-config/src/__tests__/normalize - 0 matches
```
But now runs the added tests:
```
Ran all test suites matching /jest-config\\src\\__tests__\\normalize/i.
```
=> Escape Windows path separator in testPathPattern CLI arguments

docs/GlobalAPI.md
Add documentation for methods that accept the `timeout` param. I believe all of these methods accept the param (but I may have miss some?)
Fixes #5055
=> Add docs for the timeout paramter

CHANGELOG.md, packages/jest-cli/src/cli/args.js, packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js, types/Argv.js
**Summary**
This PR changes:
* the type of the `--testPathPattern` arg to match the multiple allowed values
* the way multiple `--testPathPattern` args are joined to form a valid regular expression
* the way `--testPathPattern` args are joined with the default `<regexForTestFiles>` args
This closes #5037.
<br/>
**Test plan**
Tests have been added to check the way the args are joined.
Evaluating the two test cases from #5037 also produce expected patterns:
```
> jest --testPathPattern=aa --testPathPattern=bb
...
WAS: Pattern: aa,bb
NOW: Pattern: aa|bb
> jest aa --testPathPattern=bb
...
WAS: Pattern: bb
NOW: Pattern: aa|bb
```
=> Use all --testPathPattern and <regexForTestFiles> args in testPathPattern

CHANGELOG.md, docs/GlobalAPI.md, packages/jest-worker/README.md, packages/jest-worker/src/__tests__/worker.test.js, packages/jest-worker/src/worker.js
**Summary**
Using `jest-worker` when debugging caused it to crash. This ports over code from worker-farm which automatically filters away `/--(debug|inspect)(-brk)?`. (https://github.com/rvagg/node-worker-farm/blob/f63d988c307a6805e03b1650f8ef0fb7ca6f1546/lib/fork.js#L8-L11)
**Test plan**
Modified test to illustrate the filtering behaviour.
=> Remove `debug` and `inspect` flags from the arguments sent to the child

integration_tests/__tests__/override-globals.test.js, integration_tests/override-globals/__tests__/index.js, integration_tests/override-globals/index.js, integration_tests/override-globals/package.json, packages/jest-jasmine2/package.json, packages/jest-jasmine2/src/jasmine/Env.js, packages/jest-jasmine2/src/p_cancelable.js, packages/jest-jasmine2/src/p_timeout.js, packages/jest-jasmine2/src/queue_runner.js, packages/jest-jasmine2/src/reporter.js, packages/jest-jasmine2/src/tree_processor.js, packages/jest-util/src/install_common_globals.js, yarn.lock
The new version of Jasmine (i.e. `jasmine_light.js`) uses `Promise`s in its core. Since this file (plus all its transitive dependencies) are injected into the context, they end up using the **child context `Promise`**, which could be overridden, thus freezing Jest forever. This did not happen before, essentially because the old `vendor/jasmine` did not use them.
The solution proposed here is to add a non-writable, non-enumerable, non-configurable global property called `__originalGlobals__`, where these ones are stored; then force use them inside `jest-jasmine2`. A test was also added to verify the code actually works, although this approach is not 100% correct still, since code like `Promise.prototype.then = () => 'banana'` would still make Jest crash.
_A proper solution is to not inject …
=> Always enforce the usage of the original Promise

flow-typed/resolve.js
**Summary**
We added this to Flow in v0.25 (about 2 years ago), but never actually
deprecated the legacy `declare var exports` syntax. Hoping to do that
soon, so clearing up uses that I can find.
**Test plan**
flow
=> Use `declare module.exports` syntax for flow libdefs

CHANGELOG.md, docs/Configuration.md, docs/TimerMocks.md, integration_tests/__tests__/__snapshots__/failures.test.js.snap, integration_tests/__tests__/failures.test.js, packages/jest-message-util/package.json, packages/jest-message-util/src/index.js, yarn.lock
**Summary**
I had a bit of time this morning, so tried to throw something together for #3415. This is not ready to merge, but pushing to get some early feedback.
**Test plan**
Eventually green CI.
=> feat(jest-message-util): render codeframe on failure

README.md
**Summary**
The link in the 'Contributing' section of the README points to the [Good First Task](https://github.com/facebook/jest/labels/Good%20First%20Task) label. Following it shows 0 issues. Looks like the suggested label is [Good First Issue](https://github.com/facebook/jest/labels/Good%20First%20Issue) -- updating the link to point there instead.
**Test plan**
Verify following the link in the README shows good first issues.
=> Point contributing link in README to 'Good First Issue' label.

docs/Puppeteer.md, website/sidebars.json
Added a guide for usage with puppeteer
=> docs: add jest-puppeteer example

packages/jest-config/src/valid_config.js
This will fix the false warnings on using the Global Setup/Teardown options
=> fix: add global setup/teardown to valid_config

integration_tests/__tests__/__snapshots__/failures.test.js.snap, integration_tests/__tests__/coverage_remapping.test.js, integration_tests/__tests__/failures.test.js, integration_tests/failures/__tests__/async_failures.test.js, integration_tests/failures/__tests__/test_macro.test.js, integration_tests/failures/macros.js, packages/jest-message-util/src/index.js
**Summary**
Fixes a couple of issues with the new code frame.
In particular it fixes async assertions and having an `expect` in another file than the test file.
I would like to fix async assertions to have a codeframe, but that can be done separately (currently it's not in the stack trace at all).
**Test plan**
Tests added
=> Codeframe fixes

packages/jest-cli/package.json, packages/jest-cli/src/cli/index.js, packages/jest-runtime/package.json, packages/jest-runtime/src/script_transformer.js, packages/jest-util/src/index.js, yarn.lock
**Summary**
See https://github.com/facebook/jest/pull/5085#discussion_r157338862
Quick and dirty extraction
**Test plan**
Green CI
=> refactor: extract realpath native into a separate module

integration_tests/__tests__/__snapshots__/failures.test.js.snap, integration_tests/__tests__/failures.test.js, integration_tests/failures/__tests__/__snapshots__/snapshot.test.js.snap, integration_tests/failures/__tests__/snapshot.test.js, website/blog/2017-12-18-jest-22.md, yarn.lock
**Summary**
This is just adding a regression test. This was broken and fixed in #5094, but I would like to have a test for it so we don't regress
**Test plan**
Green CI
=> test(jest-message-util): add test for codeframe and snapshot test

CHANGELOG.md
**Summary**
Ref #5112. Maybe it would have helped if it was marked as breaking in the changelog, and they would have checked it and seen the new option for the old behavior.
**Test plan**
Docs only
=> docs(changelog): mark #3672 as breaking

CHANGELOG.md, docs/Configuration.md, docs/JestPlatform.md, integration_tests/__tests__/__snapshots__/coverage_remapping.test.js.snap, integration_tests/__tests__/coverage_remapping.test.js, packages/jest-runtime/src/__tests__/script_transformer.test.js, packages/jest-runtime/src/script_transformer.js
**Summary**
See #5109. This partially reverts #3458 to unblock.
A quick patch release might be a good idea
**Test plan**
The added assertion (on status `0`) fails for the old code, as the integration test actually failed in the same way...
=> fix(jest-runtime): only write map files to disk when `mapCoverage: true`

integration_tests/utils.js
**Summary**
We're seeing some errors from slow running tests in seconds instead of millis. This strips them out from test results in integration tests.
**Test plan**
Green CI
=> test: handle both `ms` and `s` in test timings

packages/jest-config/src/normalize.js, packages/jest-editor-support/src/Runner.js, packages/jest-resolve/src/index.js
> Please remember to update CHANGELOG.md in the root of the project if you have not done so. -->
Do I need to update `CHANGELOG.md` for unofficial fixes?
**Summary**
I fixed Node.js 4 support to use Jest 22 in PostCSS, Autoprefixer, and Browserslist according to our plan in https://github.com/facebook/jest/issues/5122
**Test plan**
I didn’t fix `...` in tests since Node.js 4 support is unofficial
=> Fix unofficial Node.js 4 support

.babelrc, package.json, packages/jest-config/src/normalize.js, packages/jest-editor-support/src/Runner.js, packages/jest-jasmine2/src/index.js, packages/jest-resolve/src/index.js
**Summary**
Improve unofficial Node.js 4 support
**Test plan**
No tests since support is unofficial
=> Fix Node.js 4 support

website/sidebars.json
Moves the API Reference to the bottom, and places regular Guides above Framework guides.
Run docusaurus in `website/` folder:
=> [Website] Reorganize sidebar

packages/jest-cli/src/watch.js
Prints a new line before quitting watch mode, to prevent mid-line shell prompts. More details in #5150.
=> New line before quitting watch mode

CHANGELOG.md, packages/jest-config/src/__tests__/resolve_config_path.test.js, packages/jest-config/src/resolve_config_path.js
**Summary**
Related issue is #5141 
**Test plan**
No additional test
=> Update condition to avoid infinite recursion in Windows platform

CHANGELOG.md, docs/GlobalAPI.md, integration_tests/__tests__/jasmine_async.test.js, integration_tests/jasmine_async/__tests__/generator.test.js, packages/jest-jasmine2/package.json, packages/jest-jasmine2/src/jasmine_async.js, yarn.lock
**Summary**
Fixes #2666
Easy enough to do, and brings some more feature parity with ava (https://github.com/avajs/ava/blob/965cbc65d82b12019cdf6a3257b3198dd4181b79/readme.md#generator-function-support).
Also, I was bored, and this was the lowest hanging fruit I could find with some people behind it :P I didn't update the docs much as `async-await` is to be preferred. Can point it out if we want it, though.
(Feel free to close this if you _really_ don't want it, but I don't see the harm, tbh (6 lines of code))
**Test plan**
Integration test added. I didn't see any unit tests for the promisification happening to `it` already.
=> feat: add support for generator functions in specs

docs/Configuration.md
This is a follow up on #5183. Added a few words about how to pass variables from custom test environment file to test suites with globals.
=> docs: globals in custom test environment

packages/jest-editor-support/index.d.ts, packages/jest-editor-support/src/Runner.js, packages/jest-editor-support/src/__tests__/runner.test.js, packages/jest-editor-support/src/types.js
**Summary**
When running Jest in watch mode, the test results that follow the "No tests found related to files changed since last commit" message will be empty. This PR adds detection for this message, and emits this info with the JSON test results. This behavior is required for jest-community/vscode-jest#213.
**Test plan**
Tests have been added, and I've confirmed the expected behavior debugging `vscode-jest`.
/cc @orta
=> Add meta-data arg to JSON event

docs/Configuration.md
=> Configurations.md typo: "(or) to"

packages/jest-editor-support/index.d.ts, packages/jest-editor-support/src/Runner.js, packages/jest-editor-support/src/__tests__/runner.test.js, packages/jest-editor-support/src/types.js
**Summary**
This builds on recent changes from #5208 that required us to check what message Jest has printed to `stderr`. Since we know two of the message types, we may as well emit this information to the clients.
It's a bit dirty with a `const` in `types.js` but it seems to be the way to go with Flow-typed enums. :man_shrugging: 
**Test plan**
Tests have been added and the feature works when debugging vscode-jest with this version of jest-editor-support.
/cc @orta
=> Emit stderr message type if identified

CHANGELOG.md, docs/SetupAndTeardown.md
**Summary**
There is no documentation of the order in which `describe` and `test` handlers are run, nor any mention of any guarantees that jest makes about their synchronicity. I believe the intention is that tests within a single file are always run one after another unless `test.concurrent` is used, so I wanted to formalize that in the docs. 
Obviously if that's not true it would be good to see an explanation in the docs of why!
**Test plan**
Docs changes only and I've checked visually the markdown renders fine.
=> Improve documentation of `describe` and `test` ordering.

.circleci/config.yml
**Summary**
Use the `docusaurus-bot` (maybe temporarily) to unblock publishing the site until we can get the `jest-bot` in order.
**Test plan**
Try it live
=> Use docusaurus-bot for publishing

CHANGELOG.md, packages/jest-regex-util/src/__tests__/__snapshots__/index.test.js.snap, packages/jest-regex-util/src/__tests__/index.test.js, packages/jest-regex-util/src/index.js
**Summary**
PR #5054 introduced a regression when handling escaped Windows path separators in the
`--testPathPattern`. The PR applied the same escaping as the "Watch Usage" prompt, which incorrectly escapes `path\\.*file` as `path\\\.*file`.
This PR fixes the common regular expression escaping used in the "Watch Usage" prompt and the `--testPathPattern` CLI argument with unit tests.
<br/>
**Test plan**
New unit tests have been added to confirm the regular expression escaping behavior. I've also added a snapshot to test the 8 test cases documented in #5216. I'm happy to record GIFs from a Linux and Windows system if you feel it's necessary.
<br/>
**Lessons learned**
Sorry folks. I hastily submitted #5054 without adding enough tests to be confident in the regular expression escaping. I was …
=> Fix --testPathPattern escaping for '\\' on Windows

CHANGELOG.md, docs/CLI.md, integration_tests/__tests__/jest_changed_files.test.js, packages/jest-changed-files/src/git.js, packages/jest-cli/src/cli/args.js
**Summary**
as requested in https://github.com/facebook/jest/pull/5188, this PR adds git support for the `--changedFilesWithAncestor` flag.
**Test plan**
If this is working, you should be able to do this in the jest repo:
`yarn jest -- --onlyChanged --changedFilesWithAncestor`
=> Git support for --changedFilesWithAncestor

README.md
**Summary**
Avoid second `npm install jest` by adding to initial command.
**Test plan**
just update readme.
=> Add jest to babel and ts dependency prepair.

CHANGELOG.md, packages/jest-util/src/__tests__/is_interactive.test.js, packages/jest-util/src/is_interative.js
**Summary**
Fixes #5236 and related issues outside of Emacs. Essentially, the issue is that `isInteractive` only checks `process.stdin.isTTY` and CI environment variables, but it should treat a shell with `TERM` set to `dumb` as noninteractive even if is has a TTY (not all TTYs support interactive escape codes). Note that while Emacs' Compilation mode supports interactive comint processes with a prefix argument, it is still not supported with this Jest patch (for example `jest --watch` will ignore input).
**Test plan**
- `yarn test packages/jest-util/src/__tests__/is_interactive.test.js` passes
- Running `yarn link` and `jest` in another project in Emacs successfully hides mode escape codes (though is an extra `[999D` right after the last `PASS` line that I can't figure out how to …
=> Treat dumb terminals as noninteractive

CHANGELOG.md, integration_tests/__tests__/__snapshots__/console.test.js.snap, integration_tests/__tests__/console.test.js, integration_tests/console-jsdom/__tests__/console.test.js, integration_tests/console-jsdom/package.json, packages/jest-environment-jsdom/src/index.js, packages/jest-runner/src/run_test.js, types/Environment.js
**Summary**
This ensures the console used in jsdom's virtualConsole is the same as the one used in the tests.
Closes #5223
**Test plan**
I'm not sure of the best way to test this. Help appreciated :) I did make this work by manually changing the code in my `node_modules` of the reproduction repo and things worked as expected :)
Thanks!
=> pass testConsole to TestEnvironment

packages/jest-environment-jsdom/src/index.js
As suggested by @thymikee in https://github.com/facebook/jest/pull/5227#discussion_r159994421
=> jest-environment-jsdom: add ? to options parameter

CHANGELOG.md, packages/jest-cli/src/__tests__/search_source.test.js, packages/jest-cli/src/__tests__/test_root_with_(parentheses)/__testtests__/test.js, packages/jest-cli/src/__tests__/test_root_with_(parentheses)/module.jsx, packages/jest-config/src/normalize.js, packages/jest-config/src/utils.js
**Summary**
This is an attempt to address https://github.com/facebook/jest/issues/4838 and https://github.com/facebookincubator/create-react-app/issues/3404. Currently, some tests aren't found when the user is running Jest in a project where the path contains parentheses *and* they have the `<rootDir>` token in one of the `testMatch` strings. This seems to be because `testMatch` is treated as an array of Globs, but rootDir is dropped into those Globs unaltered.
For an example, given this configuration:
```json
{
"rootDir": "/(parens)/",
"testMatch": [
"<rootDir>**/*.test.js"
]
}
```
Jest will end up with `/(parens)/**/*.test.js` as a `testMatch` pattern. This will match the file at `/parens/src/index.test.js`, rather than file `/(parens)/src/index.test.js`, since micromatch will treat the …
=> Escape glob characters in rootDir before interpolating into testMatch

integration_tests/__tests__/__snapshots__/cli-accepts-exact-filenames.test.js.snap, integration_tests/__tests__/cli-accepts-exact-filenames.test.js, integration_tests/__tests__/find_related_files.test.js, packages/jest-cli/src/search_source.js
**Summary**
Fixes #3755 and #3793
**Test plan**
Examples provided in issues above.
Added an ability to run tests by provided filenames: `jest ../foo.js ../tests/bar.js ./src/baz.js`
Will add tests if fixes are ok.
=> Allow unmatched test paths from CLI

CHANGELOG.md, packages/jest-diff/src/index.js, packages/jest-matcher-utils/src/index.js, packages/jest-snapshot/src/plugins.js, packages/pretty-format/src/__tests__/dom_collection.test.js, packages/pretty-format/src/index.js, packages/pretty-format/src/plugins/dom_collection.js
**Summary**
Resolve #5233
**Test plan**
I'm added tests for that and all tests is passed.
=> Pretty format for DOMStringMap and NamedNodeMap

CHANGELOG.md
@SimenB should if be a "breaking" instead of "fixes"?
=> Add changelog for asymmetric matchers types PR #5069

CHANGELOG.md, packages/jest-leak-detector/package.json, packages/jest-leak-detector/src/index.js
Fully remove the module from the package, and leave the developer willing to use it to install it on the parent package. This way we will avoid crashing or waiting for a timeout if the machine cannot compile it or has no internet connection.
Keeping it as an optional dependency means that the network timeout has to be triggered; which can take a lot of time depending on the setup.
=> Fully remove weak and check only in runtime

CHANGELOG.md, packages/jest-cli/src/constants.js
This is pretty much the same as https://github.com/facebookincubator/create-react-app/pull/2071.
It seems to work better for more recent Windows versions (according to my testing in https://github.com/facebookincubator/create-react-app/pull/2071#issuecomment-311741543 which I did a few months ago). I haven't verified this again but I can re-test with a Windows laptop in a few days.
=> Use a better console-clearing string on Windows

docs/GlobalAPI.md
**Summary**
It was not clear that the test.only applies just to a single file, since the jest parallels the tests
**Test plan**
Just docs changes
=> Clarifying the docs about test.only

packages/jest-phabricator/.npmignore
Remove unneeded `example` folder in the resulting NPM package.
=> Remove example folder from package

docs/Webpack.md
**Summary**
A un-escaped reference to `<rootDir>` in a blockquote was being interpreted as an HTML tag, causing it not to appear in the rendered docs — the result of which is  a slightly confusing read. This PR surrounds the tag in `backticks` to ensure it's rendered correctly. (See screenshots below)
**Test plan**
I've verified this fix by running the docs website locally, e.g.:
```bash
$ yarn && yarn build
$ cd website && yarn start # Verify regression exists in `master` (see screenshot #1)
$ cd -
$ nvim docs/Webpack.md  # Fix typo
$ cd website && yarn start # Verify regression is fixed (see screenshot #2)
```
=> [docs] Fix Markdown syntax typo in Webpack docs.

CHANGELOG.md, packages/jest-jasmine2/src/index.js
This PR fixes a memory leak introduced in https://github.com/facebook/jest/pull/5020
Fixes https://github.com/facebook/jest/issues/5234
Fixes https://github.com/facebook/jest/issues/5239
Fixes https://github.com/facebook/jest/issues/5157
I initially confirmed that `--detectLeaks` is broken for all tests. The next step was to figure out if this was a bug in the way we detect leaks or if it's a legit leak. Using [this repo](https://github.com/kand/jest-22-mem-leak), I walked the commits backward to find the last passing test.
That lead me to [this commit](https://github.com/facebook/jest/commit/3d2eb37e757c2e3e0e10d6fd079f81dc020cbb58). Nothing there is related to the leak detection, so I figured it must be a legit leak. From there I commented out lines until I could prove which line would …
=> Fix memory leak from snapshot printing

CHANGELOG.md, docs/CLI.md
**Summary**
Adds missing change log entry from #5269 for @SimenB.
Also adds a note to the CLI docs for `jest <regexForTestFiles>` and `jest --testPathPattern` that Windows users can use `/` as a path separator, or should escape `\` as `\\`.
**Test plan**
N/A
**Change log**:
This one's a chore -- we don't need an entry.
cc @SimenB
=> Add #5269 to docs and change log

CHANGELOG.md, CONTRIBUTING.md, docs/TutorialReact.md, docs/TutorialReactNative.md
Closes #5258.
**Summary**
Update the documentation to describe the warnings that are emitted by React 16 when using Enzyme, mocked components and snapshot testing.
Also fix the website instructions in the contribution guidelines.
**Test plan**
1. Started website
2. Checked new docs additions rendered OK
3. Checked link from React Native tutorial to React Tutorial works.
=> Document caveat with mocks, Enzyme, snapshots and React 16

docs/Configuration.md, docs/JestObjectAPI.md, docs/JestPlatform.md, docs/SnapshotTesting.md, docs/TimerMocks.md
Fixes a few typos and a broken link
Fixes this link:
=> Fix typos in documentation

packages/jest-util/src/__tests__/deep_cyclic_copy.test.js, packages/jest-util/src/deep_cyclic_copy.js
@thymikee pointed out some bugs with the last PR that were missed before merge:
- A test that was missing a flag
- The blacklist would only work for the first key
Updated tests to add a second blacklist key
=> Cleanup from last review

CHANGELOG.md, packages/jest-cli/src/get_no_test_found_related_to_changed_files.js
**Address** https://github.com/facebook/jest/issues/5305
**Summary**
It was a case of operator precedence. 
`let msg = "\n" + isTrue ? "a": "b"  // a` 
Added the ternary operator expression inside a pair of simple brackets. 
`let msg = "\n" + (isTrue ? "a": "b") // <newline>a`
**Test plan**
Firstly, I tried out the changes in create-react-app. The screenshots are of the same. 
Secondly, I ran `jest -o` after making my changes in the jest repo. All the relevant tests passed. 
Before:
After:
=> Fix missing newline after "no files changed"

packages/jest-cli/src/__tests__/watch.test.js, packages/jest-cli/src/watch.js
Fixes #4869
I'm not sure if current behavior was intended, but this fix works for me.
Also I wonder if it'd be enough to always reset to `new` instead of `none`, since it runs in the watch mode?
=> Fix updateSnapshot resetting after updating snapshots in watch mode

CHANGELOG.md, docs/CLI.md, packages/jest-cli/src/__tests__/cli/args.test.js, packages/jest-cli/src/cli/args.js
**Summary**
This came up in a discussion on another PR of mine, so I decided to fix it: https://github.com/facebook/jest/pull/5189#discussion_r158933030
**Test plan**
```
~/src/jest$ yarn jest --listTests | wc -l
220
~/src/jest$ yarn jest --listTests --lastCommit | wc -l
4
~/src/jest$ yarn jest --listTests --changedFilesWithAncestor | wc -l
4
```
before this change, all 3 commands would output `220`
=> make --lastCommit and --changedFilesWithAncestor work without --onlyChanged

CHANGELOG.md
**Summary**
`spyOn` on getters and setters is available starting from Jest v. 22.0.5, see #5107
=> chore: include #5107 in CHANGELOG.md

packages/jest-cli/package.json, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/reporters/coverage_worker.js, packages/jest-cli/src/reporters/notify_reporter.js, packages/jest-cli/src/run_jest.js, packages/jest-cli/src/test_scheduler.js, packages/jest-cli/src/watch.js, packages/jest-runner/package.json, packages/jest-runner/src/index.js, packages/jest-runner/src/test_worker.js, packages/jest-runtime/package.json, packages/jest-runtime/src/cli/index.js, yarn.lock
Changing all `process.exit` to `exit`. This prevents sudden truncation of Jest output when finishing test execution, if the output information is too big (I've seen issues when the JSON output is above 256 KiB). As per the Node docs, `process.exit()` will not wait up until all buffers are flushed, and will try to quit as soon as possible.
Tests are still passing since `exit` uses `process.exit` underneath.
=> Move from "process.exit" to "exit

CHANGELOG.md, integration-tests/__tests__/__snapshots__/cli-accepts-exact-filenames.test.js.snap, integration-tests/__tests__/cli-accepts-exact-filenames.test.js, packages/jest-cli/src/search_source.js
**Summary**
This PR fixes #5272 by fixing the regression introduced in #3882.
#3882 allows directly specifying file names as arguments to the `jest` CLI but this unintentionally breaks existing behavior when a test directory is passed as the sole argument to `jest`.
**Fix details**
*Symptom*: When `*.test.js` files are stored in a directory e.g. `test`, invoking `jest test` on v22.0.5+ results in the following:
```
FAIL  ./test
EISDIR: illegal operation on a directory, read
at Object.readSync (node_modules/graceful-fs/polyfills.js:138:28)
Test Suites: 1 failed, 1 total
Tests:       0 total
Time:        0.03s
Ran all test suites matching /test/i.
```
*Root cause*: The change allowing directly running tests by file name does not ensure that …
=> Verify passed test path is a file before resolving

packages/jest-snapshot/src/index.js
**Summary**
The value after "Received value" is missing a space
**Test plan**
@SimenB  Do we need to update the CHANGELOG.md for this?
=> Add space to "received snapshot" message

website/static/css/custom.css
This fixes the layout of the video on the homepage for both web and mobile ( e.g. [here](https://github.com/facebook/jest/blob/dfdca8b1/website/src/jest/css/jest.css#L1721-L1746) )
Before:
After:
=> Bring back some of the Jest homepage changes for mobile

CHANGELOG.md, integration-tests/__tests__/__snapshots__/execute-tests-once-in-mpr.js.snap, integration-tests/__tests__/cli-accepts-exact-filenames.test.js, integration-tests/__tests__/execute-tests-once-in-mpr.js, packages/jest-cli/src/search_source.js
When executing a test by path (not sure why this is a thing?) we were returning `true` for each call in a project configured. This is because as soon as a test is a file, we returned `true`, not checking if the file actually belongs to the project being tested.
This has popped up multiple times (e.g. #5332).
=> Fix bug: MPR executes tests multiple times

packages/jest-runtime/src/__tests__/runtime_jest_fn.js
**Summary**
An asynchronous test did not return its promise.
Picked up by the new eslint rule https://github.com/jest-community/eslint-plugin-jest/pull/42. 🎉 
/cc @tushardhole
**Test plan**
Green CI
=> test: make sure to return promise from test

docs/GettingStarted.md
preset-es2015 was already deprecated and should be replaced by preset-env
you will see this info when installing preset-es2015
> We're super 😸 excited that you're trying to use ES2015 syntax, but instead of making more yearly presets 😭 , Babel now has a ?better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a …
=> replace preset-es2015 with preset-env

CHANGELOG.md, docs/Configuration.md, docs/TutorialReact.md, docs/TutorialReactNative.md
**Summary**
Noticed 21.1.1 was missing from the changelog. I also ran `yarn lint:md` while I was at it.
**Test plan**
Docs only
=> chore: add missing release to changelog

CHANGELOG.md, packages/jest-util/src/Console.js, packages/jest-util/src/buffered_console.js, packages/jest-util/src/null_console.js, types/Console.js
The `console` global is overridden with a custom implementation in order to be able to buffer it per test. However, the "`debug`" method is missing in either of the implementations (`CustomConsole` and `BufferedConsole`), so when doing `console.debug` you end up calling the real implementation.
This causes troubles, and especially when using the `jsdom` environment, where an extra indirection layer is added via `VirtualConsole`, which re-wraps methods once again.
=> Add "debug" method to console

CHANGELOG.md, packages/jest/bin/jest.js, packages/jest/package.json
**Summary**
Related to #5304. I didn't test it well enough. That changed worked with a globally installed `jest-cli` and a local installation of `jest-cli`. It did _not_ work for a global `jest` install and a local `jest` install if `jest-cli` is within `node_modules/jest/jest-cli` instead of at the top level.
This change fixes that.
(I want to point out that the original code before #5304 didn't work in the same case (as it hardcoded a `node_modules/jest-clil` path) - and why I think so many projects have both `jest` and `jest-cli` in their dependencies.)
**Test plan**
Local testing with a globally installed `jest` (with this change applied) and a local `node_modules/jest/jest-cli` installation.
=> fix(jest): `import-local` should be used in main jest pakage

types/Jest.js
**Summary**
Stricter type for flow type checking, it helps developers to know exactly what are the values expected by the function.
This PR makes clear the value of `accessType` input parameter of `spyOn` function is either `get` or `set`
**Test plan**
**NA** (not a bug)
=> Adjust flow type for accessType parameter in spyOn function

docs/Webpack.md
**Summary**
Found a broken link while browsing webpack setup page. This pull request fixes that link.
**Test plan**
If there's some way to resolve deep markdown links with the static site generator then broken links like this would never make it past the build step.
=> Fix link to babel setup doc from webpack doc

CHANGELOG.md, docs/MockFunctionAPI.md, packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
**Summary**
I find myself doing the following very often when testing async code:
```js
// ...
const asyncFn = jest.fn().mockReturnValue(Promise.resolve(result)):
// or...
const asyncFn = jest.fn().mockReturnValue(Promise.reject(err)):
// ...
```
This PR adds four utility methods to `MockInstance`, automating the creation of async mock functions:
```js
// ...
const asyncFn = jest.fn().mockResolvedValue(result):
// and...
const asyncFn = jest.fn().mockResolvedValueOnce(result):
// and...
const asyncFn = jest.fn().mockRejectedValue(result):
// and...
const asyncFn = jest.fn().mockRejectedValueOnce(result):
// ...
```
**Test plan**
**NA** (Not a bug)
---
This PR means to gather info on usage first, if people find this useful I'll continue to add the docs to this feature and updating the …
=> Adding async versions of mockReturnValue & mockreturnValueOnce

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/__tests__/utils.test.js, packages/expect/src/utils.js
**Summary**
Checking for object own property with `Object.prototype.hasOwnProperty.call(object, value)` won't work on class instance getters. To support that, we can fall back to checking `object.constructor.prototype`, because we know `object` is an Object so we can actually get its class prototype which stores the getter.
Also refactored the code a bit for perf (remove unnecessary `delete`) and readability (flattened if/else branching, use `?w=1` to review)
Resolves https://github.com/facebook/jest/issues/5339
**Test plan**
Added a test or two.
=> fix: Support class instances in .toHaveProperty() matcher

packages/jest-cli/package.json
**Summary**
All info in https://github.com/facebook/jest/issues/5365#issuecomment-359544588
**Test plan**
=> [jest-cli] Bump `node-notifier` to fix a memory leak issue (fixes #5365)

packages/jest-cli/src/reporters/coverage_reporter.js
**Summary**
Fixes a typo in the options when spawning coverage workers. This change does not change the behaviour of the code as there is a fallback in `jest-worker` that resolves to the same method. https://github.com/facebook/jest/blob/master/packages/jest-worker/src/index.js#L95
**Test plan**
[Matches the expected option in `jest-worker`.](https://github.com/facebook/jest/blob/master/packages/jest-worker/src/index.js#L92)
=> fix(jest-cli): fix typo in options when spawning workers

README.md, docs/Configuration.md, docs/ExpectAPI.md, docs/GettingStarted.md, docs/MigrationGuide.md, docs/MockFunctionAPI.md, docs/SnapshotTesting.md, docs/Troubleshooting.md, docs/TutorialReact.md, docs/TutorialReactNative.md, docs/Webpack.md, package.json, packages/babel-jest/README.md, packages/jest-changed-files/README.md, packages/jest-docblock/README.md, packages/jest-mock/README.md, packages/jest-phabricator/README.md, packages/jest-validate/README.md, packages/jest-worker/README.md, website/README.md
**Summary**
Added appropriate language markers for fencing blocks in markdown files that were missing them.
**Test plan**
=> Added some languages to missing markdown fencing blocks

docs/MockFunctionAPI.md
Changed the duplicated mockRejectedValueOnce to mockResolveValueOnce
**Summary**
Someone made a typo and described the method `mockResolveValueOnce` but made the section header `mockRejectedValueOnce` which already exists and has it own description.
**Test plan**
Simple doc change.
=> mockRejectedValueOnce -> mockResolveValueOnce

README.md, docs/TutorialReact.md
Because `babel-preset-es2015` is deprecated and `babel-preset-env` is a drop-in replacement.
**Summary**
Replace es2015 with env because `babel-preset-es2015` is deprecated and `babel-preset-env` is a drop-in replacement.
**Test plan**
N/A
=> docs: replace es2015 with env

CHANGELOG.md, packages/jest-cli/src/reporters/summary_reporter.js
**Summary**
The snapshot summary told me to use `npm test -u` but it didn't work and needs special option -- to update snapshot.
This fix tells the correct command to update snapshot for npm.
**Test plan**
With `npm test`, I got this summary.
With `yarn test`.
=> Fix npm update command for snapshot summary

CHANGELOG.md, integration-tests/__tests__/__snapshots__/failures.test.js.snap, packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/index.js
**Summary**
Fix #5361 
**Test plan**
Pass non-promise values into reject matchers synchronously
=> Make `rejects` and `resolves` synchronous

packages/jest-editor-support/README.md
**Summary**
Adds @Raathigesh's majestic to the README 👍
=> Update jest-editor-extension's README.md

docs/JestObjectAPI.md
**Summary**
Currently the API Doc doesn't have the link to go to jest.spyOn(object, methodName, accessType?). This PR makes the developers easy to navigate to jest.spyOn(object, methodName, accessType?) method description by clicking the link on the list of methods on the top of the API doc page.
**Test plan**
- Run `yarn start` in the website directory.
- Browse to `http://localhost:3000/jest/docs/en/jest-object.html` using any browsers
- Check if the list of methods contain `jest.spyOn(object, methodName, accessType?)`
- Click on the link `jest.spyOn(object, methodName, accessType?)` and see if it navigates correctly to the usage description of the method
=> Add link to the list of methods to go to spyOn accessType for Jest Object API doc

CHANGELOG.md, packages/jest-resolve/src/__tests__/resolve.test.js, packages/jest-resolve/src/node_modules_paths.js
**Summary**
It resolves #5377 
**Test plan**
I ran `yarn test` and it passed correctly
I signed the CLA
=> Load modules from node_modules before custom paths

appveyor.yml
**Summary**
It's better to keep yarn up-to-date for CI build. This PR replaces yarn v1.1 with yarn v1.3.2 for AppVeyor.
**Test plan**
**N.A.**
=> Use yarn v1.3.2 for AppVeyor CI build

CHANGELOG.md, packages/jest-resolve/src/is_builtin_module.js
**Summary**
We don't currently get the list of builtins from node core, as we use the wrong API. See https://nodejs.org/api/modules.html#modules_module_builtinmodules
**Test plan**
Tested using `console.log` locally on node 9.4.0 that the list exists.
=> fix: get builtin modules from node core

.flowconfig, package.json, packages/jest-cli/src/reporters/Status.js, packages/jest-haste-map/src/index.js, yarn.lock
**Summary**
Keeping things up to date.
* `setInterval`/ has now `IntervalID` type
* adjusted typing around worker usage a bit (cc @mjesun) 
**Test plan**
CI green
=> chore: Use Flow 0.64.0

CHANGELOG.md, packages/babel-jest/src/index.js
**Summary**
Per https://github.com/facebook/jest/issues/5326, babel has an issue with retainLines that causes failures on decorators with async methods. Since babel already provides sourcemaps, we don't need to retainLines
**Test plan**
yarn test passed
=> Remove retainLines from babel-jest

.babelrc, CHANGELOG.md
From @SimenB in https://github.com/facebook/jest/pull/5439
- N/A
=> Correct changelog link, remove retainLines from ./.babelrc

packages/jest-cli/src/cli/index.js, packages/jest-runtime/src/cli/index.js
Use `process.exitCode` instead of recursively calling `process.exit()` on a `exit` event.
Fixes #5332. The reason why it stopped working when merged #5313 is because on every single call to `process.exit()`, the `process.exitCode` is checked just before exiting. However the `exit` module implementation does not do that, so the code was never set.
In turn, looking at [the `process.exit` implementation](https://github.com/nodejs/node/blob/master/lib/internal/process.js#L141-L150), it is clear that calling `process.exit()` from an `exit` event will have no effect but changing the exit code. Thus we can safely remove the second `exit()` call and only modify the exit code, so that the native method picks it. A bit confusing, I know.
=> Fix recursive process.exit calls

README.md
Minor fix: update link to Webpack guide as the current one is broken.
=> Docs: Fix link to Webpack guide

.babelrc
This PR fixes master by rolling back the `retainLines` change
It looks like removing the retainLines gave the integration tests the wrong line number. For example in this test (and the rest from what I could tell), the snapshot is correct:
=> Fix master, add back retainLines to ./.babelrc

CHANGELOG.md, packages/jest-cli/src/__tests__/__snapshots__/watch.test.js.snap, packages/jest-cli/src/__tests__/watch.test.js, packages/jest-cli/src/watch.js
This PR will not show the interactive option in watch mode if there are no failed snapshot tests. This can happen if one or more test descriptions have changed.
Fixes https://github.com/facebook/jest/issues/5444
I added tests for the `u` option as well as `i` in watch mode
=> Hide interactive mode if there are no failed snapshot tests

packages/jest-cli/src/__tests__/search_source.test.js, packages/jest-cli/src/search_source.js
When verifying if a test belongs to a particular project, the root of the project is part of the checks we perform (`roots` is checked against the filename via a regular expression). However, the regular expression did not include a trailing slash (either `/` or `\` for Windows), which causes to wrongly recognize tests as part of a pattern. For instance:
* Root A: `/foo/bar/folder`.
* Root B: `/foo/bar/folder-with-something`.
All tests inside B are executed also through config A, since B starts with A. This leads to tests getting executed twice if not crashing. Adding a trailing slash fixes the problem.
=> Add a trailing slash to the root pattern

packages/jest-util/src/__tests__/create_process_object.test.js, packages/jest-util/src/create_process_object.js
When we fully sandboxed `process`, we removed the ability of the `env` object to perform case-insensitive matches when used in Windows. The proposed solution uses a `Proxy` instance over a shared prototype object, and emulates the behavior by using a secondary lookup object.
Another behavior that  `process.env` has is that all values are always stored as strings, regardless of their value (numbers, booleans...). This behavior has also been mimicked in the new implementation.
Tests were also added to ensure that both behaviors are well respected in different platforms. Fixes #5322.
=> Make "process.env" case insensitive in Windows

CHANGELOG.md, packages/jest-util/src/__tests__/create_process_object.test.js, packages/jest-util/src/create_process_object.js
Get/Set behavior was implemented, but we lacked deletion. This PR adds it, along with some tests.
=> Support deletion in process.env too

packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/lib/watchman_watcher.js, packages/jest-util/src/create_process_object.js
This is just a fork of the WatchmanWatcher as modified in https://github.com/amasad/sane/pull/106. I also modified a few things (ex. use const/let) to make it pass the linter. However, no logic should have been changed by this changeset.
The reason for forking is that (1) the new `fresh_instance` is hard to fit into the model of `sane`, that wasn't designed for that possibility and (2) `sane` doesn't fit very well around watchman model to start with. With watchman, one is not supposed to do the file system crawling and watching operations separately. The reason for that is that files may have changed before you even start watching. Instead, "add" events are generated when you start watching, or you have to use the concept of clock specs to ensure continuity.
So overall the PR on `sane` …
=> jest-haste-map: Fork watchman watcher so we can fix things

packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/matchers.js, packages/jest-jasmine2/src/__tests__/__snapshots__/matchers.test.js.snap, packages/jest-matcher-utils/src/index.js
**Summary**
First in series of pull requests for clearer shorter report when assertion fails.
To warm up, let’s sweat some small stuff :) //cc @thymikee @rickhanlonii
Apply two principles from *The Non-Designer’s Design Book* by Robin Williams:
1. **Contrast**: Format comma separating primary and secondary argument as **dim** instead of regular for `toHaveProperty` assertion.
2. **Contrast**: Format comma separating primary and secondary argument as **dim** instead of green for `toBeCloseTo` which concatenated names instead of providing secondary as option.
3. **Proximity**: Format supplementary information as **dim comment** [EDIT on 2018-02-05: `// Object.is equality` to be parallel with `// strict equality` and `// deep equality` in next PR] at end of line instead labels in label …
=> Improve description line when assertion fails: part 1

packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js
`--all` must override any `--onlyChanged` flag.
=> Let "--all" override "--onlyChanged"

packages/jest-util/src/create_process_object.js
Because many projects must support Node.js 4 until LTS end (August 2018) we decided for silent support of Node.js. For example, big projects like Autoprefixer and PostCSS must support Node.js 4, so we run tests on Travis CI with Node.js 4.
`Proxy` is used for a small win32 fix. Maybe it could be fixed even without Proxy, but I made a small `if` to be clean.
Since it is silent support of Node.js 4 I didn’t add tests.
=> Fix Node.js 4 support with Proxy

CHANGELOG.md, packages/jest-worker/README.md, packages/jest-worker/src/__tests__/index.test.js, packages/jest-worker/src/__tests__/worker.test.js, packages/jest-worker/src/index.js, packages/jest-worker/src/types.js, packages/jest-worker/src/worker.js
This PR is related to issue #2284 
When trying to run integration tests in parallel, there could be a race of conditions.
For example when two tests are trying to modify the same record in a database at the same time.
To get full isolation, the user can choose one of two solutions:
1. Run the test serially.  -> _slow..._ 😞 
2. Create a different DB/server for each worker. -> _unlocks the full potential of the machine_ 😉 
But in order to use the second, you need unique identifiers for each worker, so you could assign each test to a different server.
For example:
```js
const port = 3000 + process.env.JEST_WORKER_ID
```
Assign a unique id for each worker and pass it to the child process. It will be available via `process.env.JEST_WORKER_ID`.
* The first index would be `1`.
* We store the id …
=> Add unique id for each worker and pass it to the child process

CHANGELOG.md, packages/babel-jest/src/index.js
This reverts commit 6635d93fc3813d386af73ff226db0bffd30a753d.
This change unfortunately broke the stacktraces. We need #5177 before we can safely remove it.
Since the jest repo has `retainLines` in its own babelrc, there is in practice no change in this repo.
=> Revert "Remove retainLines from babel-jest (#5439)"

packages/jest-jasmine2/src/jasmine/Env.js, packages/jest-jasmine2/src/jasmine/Suite.js
**Summary**
Add `testPath` to `jest-jasmine2` reporter callbacks.
Before:
```
{
id: 'suite0',
description: 'tests',
fullName: '',
failedExpectations: [],
}
```
After
```
id: 'suite0',
description: 'tests',
fullName: '',
failedExpectations: [],
testPath: '/src/__tests__/foo.test.js' 
```
**Test plan**
See #4594
=> Add testPath to suite in jest-jasmine2 reporter callbacks

packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/jasmine_utils.js, packages/expect/src/utils.js
Immutable.js structures, that do not maintain order, should be equal regardless of the insertion order. This follows how native `Set` and `Map` are compared.
As `toEqual` should provide deep equality, `Immutable.is` (or `.equals` on a structure) cannot be used.
Sentinels are used for identifying the structures, as we do [in pretty-format](https://github.com/facebook/jest/blob/master/packages/pretty-format/src/plugins/immutable.js#L14).
Fixes #4618 (includes additional info and reasons)
Added most used Immutable.js structures to unit tests: `List`, `Map`, `OrdereMap`, `Set`, `OrderedSet`.
=> Ignore order on unordered Immutable.js structures, fixes #4618

CHANGELOG.md, packages/jest-docblock/README.md, packages/jest-docblock/src/__tests__/index.test.js, packages/jest-docblock/src/index.js, packages/jest-haste-map/src/worker.js
Currently, when `jest-docblock` parses:
```js
/**
* @foo x
* @foo y
*/
```
we get `{ foo: 'y' }`.
This PR changes it to `{ foo: ['x', 'y'] }` when there are multiple.
The PR also adds support for that in `docblock.print()`.
Unit tests added and passing.
cc @vjeux
=> feat(jest-docblock): support multiple of the same @pragma

website/pages/en/index.js, website/pages/en/videos.js, website/siteConfig.js
Prettier is failing on master, this PR contains the fixes.
=> fix lint on website

packages/jest-haste-map/src/__tests__/index.test.js
When you have two files `A.js` and `A.ios.js`, removing the second one will not properly update `jest-haste-map` cache. This causes `jest` or dependents to crash, as they try to access a now non-existent path. This changeset adds a test that reproduce the issue, along with complementary tests to verify other variations on the theme are not broken. These tests try to ensure that the follow-up fix will not break the platform-specific files handling in other ways.
=> jest-haste-map: add test to demonstrate broken behavior for platform-specific files

CHANGELOG.md, packages/jest-util/src/Console.js, packages/jest-util/src/__tests__/buffered_console.test.js, packages/jest-util/src/__tests__/console.test.js, packages/jest-util/src/buffered_console.js, types/Console.js
:wave: Hey
This PR solves issue #3756.
The addition of missing methods to `custom console` and `buffered console`.
* **custom console** - make expectations on the stdout by mocking `_logToParentConsole` method.
* **buffered console** - make expectations on the stdout via the buffer.
* There are code duplications between `custom console` and `buffered console`.
* All the simple methods (`log`, `warn`, `info`) aren't tested, should we get full coverage there?
* should we add integration tests for some of the methods?
* `console.table` method is missing.
Let me know what can be improved, thanks!
=> add methods to custom and buffered consoles

CHANGELOG.md, packages/jest-editor-support/index.d.ts, packages/jest-editor-support/src/Runner.js, packages/jest-editor-support/src/__tests__/runner.test.js
I am trying to integrate jest-editor-support into a project which does not have source controll. AFAIK the watch mode of jest needs to run in a git repository to work. This PR will add a watchAll flag which will work in other projects as well.
=> Add watchAll flag to jest-editor-support

.gitignore, CHANGELOG.md, packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js
All values given to `collectCoverageFrom` are relative to the root directory, so usage of `<rootDir>` results in invalid file paths. With these changes, `<rootDir>` will be silently replaced.
I ran into this issue because I did not read the docs and expected `<rootDir>` to be usable within all paths. When I realized using `<rootDir>` in `collectCoverageFrom` did not work, I raised an issue (https://github.com/facebook/jest/issues/5499).
A contributor (@SimenB) suggested silently replacing the `<rootDir>` values, allowing it to be used. I took a look at the code that handles the configuration, found the place to patch it in and here we have the pull request!
I added a unit test that asserts the old and new behaviour. They work properly in tandem. :-)
=> refactor: strip <rootDir> from collectCoverageFrom values

CHANGELOG.md, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js, website/pages/en/videos.js
Another fix for `jest-haste-map` 😁 
This changeset fixes the bug that was reproduced by the test I added a few days ago, where platform-specific file removals aren't taken into account. I traced this back to the fact the logic just copies the entire module metadata for a particular Haste name, without discriminating between platforms. That means if any of the files for that Haste name is still here, all the platforms already cached are included in the new map, even if some of these files were deleted. With the new logic, we only copy over the data for the platform of the file being processed.
I didn't check how that behaves for the watch mode but I suspect this fixes the bug for it as well. I can follow up with another test for that.
=> jest-haste-map: fix bug where platform-specific files are removed

CHANGELOG.md, docs/CLI.md, integration-tests/__tests__/__snapshots__/coverage_report.test.js.snap, integration-tests/__tests__/coverage_report.test.js, packages/jest-cli/src/cli/args.js
This PR address issue #5198.
Improves the behaviour of `collectCoverageFrom` CLI option by allowing passing multiple glob patterns.
For example:
```bash
jest --collectCoverageFrom foo/**/*.js bar/**/*.js
```
I added a simple integration test that covers this use case.
=> support multiple glob patterns for collectCoverageFrom

appveyor.yml
Based on https://yarnpkg.com/lang/en/docs/install-ci/#appveyor-tab AppVeyor should have Yarn preinstalled. This should speedup the builds.
AppVeyor green
=> Use preinstalled Yarn on Appveyor

integration-tests/__tests__/babel_plugin_jest_hoist.test.js, integration-tests/__tests__/coverage_remapping.test.js, integration-tests/__tests__/native_async_mock.test.js, integration-tests/__tests__/transform.test.js, integration-tests/__tests__/typescript_coverage.test.js, integration-tests/utils.js
Use `cross-spawn` for running Yarn in integration tests, which should unblock running some tests on Windows.
Observe AppVeyor
=> Use `cross-spawn` for running Yarn in integration tests

packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js, packages/jest-haste-map/src/crawlers/watchman.js
This patch fixes a long-standing issue with the watchman crawler. Watchman always returns POSIX-style paths with forward-slashes in it and Jest uses the "raw" `roots` array which has Windows-style paths in it. This makes the fast but naive `isDescendant` check that simply does a `.startsWith` check and causes failures in listening folders or checks.
Run the test suite on Windows. If you keep the updated tests and undo the changes in the `watchman` crawler, the tests fail on Windows. With the fix in place, tests pass.
=> fix(watchman): Fix watchman checks on Windows

packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter.js
I want to try and see what it takes to get `jest-circus` to feature parity with jasmine.
It seems like there's only  11 tests that are failing in jest master if i switch default framework to use `jest-circus`
we moved to using `imports` since the last time i ran it, this PR fixes the integration to properly require `expect` module into runtime
=> Fix jest-circus setup logic

packages/jest-message-util/src/index.js
Optimized finding top frame.
- Used only 1 `loop` instead of 6 `loops`.
- Break loop after found first matched item.
=> Optimize finding top frame in formatPaths

CHANGELOG.md, packages/jest-cli/src/plugins/quit.js, packages/jest-cli/src/watch.js
**Summary**
The issue is detailed in #5028.  The summary is that it's not possible to force Jest to quite while the inspector is still open when the `--watch` parameter is provided.
**Test plan**
There currently aren't any tests (that I could see) for handling the `q` key or `Ctrl-C`/`Ctrl-D`, nor for the setup of `stdin.setRawMode(true)`, so I didn't add any for this either.  However, it's a simple 2 lines of code and only runs on quit, so it's unlikely to cause any unwanted side-effects.
=> Revert setRawMode on --watch quit (fixes #5028)

packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js
v8 (in Node 8+) has a new function called [`v8.serialize`](https://nodejs.org/api/v8.html#v8_v8_serialize_value) which can be used to encode/decode JavaScript data structures faster than JSON. This diff changes `jest-haste-map` to use the new function in newer versions of Node and falls back to JSON if the serializer/deserializer aren't available. It also does a v8 version check to ensure we aren't trying to read a possible outdated binary blob. Making the cache work across node versions is a non goal and will be broken by this feature. If a user upgrades node, the function will throw and recreate the haste map.
I benchmarked this on a 73mb haste map and got the following results averaged over 10 runs:
* v8.deserialize: 1621.34
* JSON.parse: 1810.15
* v8.serialize: 608.28
* …
=> Use v8.serialize when available.

packages/jest-message-util/src/index.js
Minor optimize getting stack trace.
- Used 1 `map` instead of 3 `maps`
- Get rid of `bind`
=> Optimize getting stack trace in message-util

CHANGELOG.md, docs/MongoDB.md, website/sidebars.json
Inspired by https://github.com/facebook/jest/pull/5093 I added an example how to setup jest with mongodb in-memory server to write tests
Tests are running in CI using example: https://circleci.com/gh/vladgolubev/jest-mongodb
=> docs: add jest-mongodb example

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/spy_matchers.test.js.snap, packages/expect/src/__tests__/spy_matchers.test.js, packages/expect/src/spy_matchers.js
Issue: https://github.com/facebook/jest/issues/5197
Specifically, formatMismatchedArgs will not add an error message when the received array gets extra argument(s) w/ undefined value since expected[i] and received[i] will both equal undefined (where received[i] is explicitly set to undefined whereas expected[i] is not in the array)
Tested using @mrfunkycold repo: https://github.com/mrfunkycold/jest-demo.  New error message:
● testFile › 1. when invoked › 1. fails to print the error line
expect(jest.fn()).toHaveBeenCalledWith(expected)
Expected mock function to have been called with:
Did not expect argument 2 but it was called with undefined.
11 | 
12 |     it('1. fails to print the error line', () => {
> 13 |       expect(logger).toHaveBeenCalledWith('errorMsg');
14 |     });
15 |   }); …
=> Issue #5197: Add descriptive error to Expect CalledWith methods when missing optional arguments

packages/pretty-format/src/index.js
`Objest.is` is the easiest way to compare `0` and `-0`. Also it doesn't need special check for `NaN`, because `String` work corrent.
=> Simplify check for -0 in printNumber

.eslintrc.js, packages/jest-cli/src/search_source.js
Noticed the lint warning on CI (it's set to warn for some reason in the underlying fb config: https://github.com/facebook/fbjs/blob/4369c7dfeb1ab0de27feb3e9245f599c8edd6a5c/packages/eslint-config-fbjs/index.js#L264). Any reason not to error here?
No lint errors
=> chore: make no-unused-vars eslint rule error

CHANGELOG.md, packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js
I discovered that `transform` option set in Jest preset is completely overridden when the same option is provided in the Jest config that extends such preset. I run into this issue when working on the preset for WordPress core: https://github.com/WordPress/gutenberg/pull/4705. It turned out that behavior differs from another option that uses `object` as data representations: `moduleNameMapper`. This PR tries to introduce consistency in the code and allow to merge values from `transform` option set in both config and preset.
`@wordpress/jest-preset-default`:
```json
{
"transform": {
"^.+\\.jsx?$": "babel-jest",
"\\.pegjs$": "<rootDir>/node_modules/@wordpress/jest-preset-default/scripts/pegjs-transform.js
} 
}
```
`jest.config.js`:
```json
{
"preset": "@wordpress/jest-preset-default", …
```
=> Make it possible to merge `transform` option with preset

CHANGELOG.md, docs/Configuration.md
This PR addresses issue: #4379. Please let me know if something should be changed.
Simply docs, no tests 🙂
=> add a documentation note for project displayName configuration

docs/UsingMatchers.md
⚠️ I have not added an entry to the changelog for this, as it seems perhaps too minor a change to log. However if that is the protocol on this project, I will add one.
This change makes it easier to jump right to the full list of available matchers. There's already a link at the bottom of the page, but this brings it to the fore to make it easier to find.
This is a simple docs amendment. No tests changed.
=> docs: link to full list of matchers in opening paragraph

packages/expect/src/spy_matchers.js
Optimize print calls. Used simple `while` instead of chains `slice->reverse->map`
=> Optimize print calls in spy matches

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/utils.js
Fixes #5359 -- makes toMatchObject work when comparing `Error`s with ordinary objects. This is accomplished by extending subset matching algorithm to include prototype properties of the object under test.
Added two test cases in `matchers.test.js`. No other tests were modified.
However, `yarn test` fails with the following error:
```FAIL  integration-tests/__tests__/timeouts.test.js (9.407s)
● exceeds the timeout
expect(received).toMatch(expected)
Expected value to match:
/(jest\.setTimeout|jasmine\.DEFAULT_TIMEOUT_INTERVAL|Exceeded timeout)/
Received:
"PASS __tests__/a-banana.js
✓ banana
"
```
Bonkers. Let's see if CI catches that one too.
=> fix: make Errors match with ordinary objects (fixes #5359)

CHANGELOG.md
#5611 introduced a mistake in CHANGELOG.md, attributing the PR to `enzyme` instead of `expect`. Duh.
=> fix: correcting a mislabeled CHANGELOG.md entry

packages/jest-cli/src/search_source.js, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/blacklist.js, packages/jest-haste-map/src/worker.js
Avoids `jest-haste-map` reading formats we know they are binary, even when requested to do so via `extensions`. This fixes a bug in Metro, where, in order to process assets, we need to pass Haste the corresponding extensions, but causes an OOM when opening a ~600 Mb video.
=> Avoid loading files that we know are binary ahead of time

packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js, packages/jest-haste-map/src/crawlers/watchman.js
Watchman crawler was ignoring the `relative_path` field in the response of
a `watch-project` call, requiring it to match watch roots with the actual
project roots afterward. Not only this was inefficient, it was also faulty
due to the naive `.startsWith()` check in `isDescendant()`. This was causing
issues both with Windows file paths (#5553) and after that with case-insensitive
file systems where the names from Watchman did not match the casing of the passed
roots.
This patch replaces all that logic by taking the `relative_path` field into account
and does some consolidation along with using `async`/`await` instead of promises.
Run the updated test suite on all platforms and make sure it passes. I've also
verified this on some internal Windows repos by manually patching the built module …
=> fix(watchman): Overhauls how Watchman crawler works fixing Windows

CHANGELOG.md, packages/jest-util/src/Console.js, packages/jest-util/src/__tests__/buffered_console.test.js, packages/jest-util/src/__tests__/console.test.js, packages/jest-util/src/buffered_console.js
This is a fix for #5574 
There was a mistake in #5514, where the `console.assert` behaviour was accidenitly implemented wrong.
Here there is a fix for the tests and the behaviour to use `assert` module and log when there is an assertion error.
=> fix console & buffered console assert behaviour

CHANGELOG.md, integration-tests/__tests__/require_main.test.js, integration-tests/require-main/__tests__/loader.test.js, integration-tests/require-main/example.js, integration-tests/require-main/loader.js, integration-tests/require-main/package.json, packages/jest-runtime/src/__tests__/runtime_require_mock.test.js, packages/jest-runtime/src/__tests__/runtime_require_module.test.js, packages/jest-runtime/src/__tests__/test_root/modules_with_main/export_main.js, packages/jest-runtime/src/__tests__/test_root/modules_with_main/re_export_main.js, packages/jest-runtime/src/index.js
Closes #2150 
Expose property `require.main` when testing and set it to module from which the tests are being executed. Currently this property is not set, which is inconsistent with default Node behaviour ([Node ref](https://nodejs.org/api/modules.html#modules_accessing_the_main_module)) and the use case was present in #2150.
Appropriate unit and integration test cases were added to test if the property is provided in concrete modules and mocks.
Note 1: Module with test suite has to be manually added to `_moduleRegistry`, since the runtime is created manually instead of using the one from the `jest-runtime` in which the test are being run.
Note 2: This implementation assumes, that `module.parent` is set correctly and in order to find `main` module it traverse parents until `module.id` …
=> Provide `require.main` property

CHANGELOG.md, README.md, docs/Troubleshooting.md
=> Update Node version support in README and docs

packages/jest-cli/src/__tests__/__snapshots__/watch.test.js.snap, packages/jest-cli/src/__tests__/watch.test.js, packages/jest-cli/src/base_watch_plugin.js, packages/jest-cli/src/plugins/quit.js, packages/jest-cli/src/plugins/test_name_pattern.js, packages/jest-cli/src/plugins/test_path_pattern.js, packages/jest-cli/src/plugins/update_snapshots.js, packages/jest-cli/src/plugins/update_snapshots_interactive.js, packages/jest-cli/src/types.js, packages/jest-cli/src/watch.js
This is one of the items of https://github.com/facebook/jest/issues/5478
This is the proposed API, feedback is MORE than welcome
```js
interface WatchPlugin {
+apply?: (hooks: JestHookSubscriber) => void;
+getUsageData?: (globalConfig: GlobalConfig) => ?UsageData;
+onKey?: (value: string) => void;
+runInteractive?: (
globalConfig: GlobalConfig,
updateConfigAndRun: Function,
) => Promise<void | boolean>;
}
```
* @rickhanlonii I changed `showPrompt` -> `run` -> `runInteractive` just because I felt it was a bit more explicit, thoughts?
* Right now the internal plugins use the `BaseWatchPlugin`, I find this a bit awkward. It would be nice to get rid of it. We currently inject `stdin` and `stdout` in the constructor(this is for handling stuff like `--useStderr`). What would be another good way …
=> Small polish to the plugins API

packages/jest-cli/src/__tests__/__snapshots__/watch.test.js.snap, packages/jest-cli/src/__tests__/watch.test.js, packages/jest-cli/src/plugins/update_snapshots_interactive.js
Removes an accidental snapshot that I left while debugging #5572 
It also ensure that `_failedSnapshotTestPaths` is initialized to match its type _(`Array<*>`)_
=> Remove debug snapshot

CHANGELOG.md, packages/jest-editor-support/index.d.ts
The TypeScript definition within `jest-editor-support` was outdated. I have updated it based on the Flow type files.
There shouldn't be necessary any tests as I copied them from the existing code. The only non-backward-compatible change is replacing `**M**essageTypes` by `**m**essageTypes` in order to keep it consistent to the Flow type file.
=> [jest-editor-support] update TypeScript definition

CHANGELOG.md, docs/ManualMocks.md
This adds info on how to mock scoped modules to the Manual Mocks docs page as it wasn't clear how this process would work.  
~~(changelog modification pushing shortly once I have a PR ID)~~
=> Add how to mock scoped modules to Manual Mocks doc

packages/jest-haste-map/src/crawlers/watchman.js
This is a follow up to #5615 where it made all async watchman
commands serialized when converting them from promises to `async`
functions.
Existing Watchman crawler tests should pass, maybe slightly faster.
=> fix(watchman): Parallelize Watchman calls in crawler again

packages/jest-haste-map/src/index.js
Despite `_buildFileMap` has a `try`/`catch`, and can catch the error, there are more places from where `read()` is called, like `readModuleMap`, where the call is not guarded. Thus, we have to implement a full guard *inside*, in order to be sure that we do not crash.
=> Force haste map regeneration on deserialization error

integration-tests/runJest.js
We are having test failures due to mismatched snapshots on TravisCI
and on some other systems since colors are not consistently used
during tests. This patch forces colors to be off during tests via
`runJest` so they are always consistent.
Existing tests should pass. TravisCI builds should also be fixed.
=> tests(colors): Force-disable colors on tests for consistent snapshots

packages/expect/src/__tests__/matchers.test.js
Follow up to #5646. Forces `chalk` to be turned on in matcher tests for
consistent snapshot output. Should fix tests on TravisCI.
Existing tests should pass. TravisCI should pass.
=> tests(chalk): Force chalk to on in matcher tests for consistency

README.md
The README.md points to the wrong "Good First Issue" link, there should be a 👋 in the link.
Not applicable.
=> Fix Good First Issue link in README.md

CHANGELOG.md, packages/jest-editor-support/index.d.ts, packages/jest-editor-support/src/Settings.js, packages/jest-editor-support/src/__tests__/settings.test.js
We recently added support to the `jest-editor-support` Runner to spawn the process in a shell. This made it a bit easier to support Windows binaries in `node_modules/.bin`. Unfortunately we missed the other call in Settings. 
The other change to `index.d.ts` is a small change to fix a TypeScript error. You'll notice that the `editor` namespace is not defined anywhere in the file.
Tests have been added.
=> Update `jest-editor-support` `Settings` to use spawn in shell option

.circleci/config.yml, CHANGELOG.md, packages/jest-editor-support/src/__tests__/settings.test.js
Fix a test from #5658 (cc @orta) and adjust circle config a bit
=> Fix: unbreak master

CHANGELOG.md, integration-tests/__tests__/multi_project_runner.test.js, packages/jest-cli/src/cli/index.js
Before:
After:
Updated the existing test.
cc @pedrottimark
=> Improve the error message when 2 projects resolve to the same config

scripts/build.js
currently we ignore files in `__tests__` when we run our build, but we still transform all the `__mocks__` files.
These files introduce a lot of noise during our CI builds
this PR adds `__mocks__` to the ignore list
=> exclude __mocks__ from the build step

package.json, packages/jest-circus/src/__mocks__/test_event_handler.js, packages/jest-circus/src/__mocks__/test_utils.js, packages/jest-circus/src/__tests__/__snapshots__/hooks.test.js.snap, packages/jest-circus/src/__tests__/hooks.test.js
utility function that runs a test using `jest-circus` and logs every event that goes through the event handler. (see snapshot test)
This is useful to test the definition and execution flow and make sure future work won't break the flow. (e.g. `beforeEach` suddenly isn't invoked before test)
=> jest-circus test utilities

integration-tests/__tests__/jest_changed_files.test.js
some versions of mercurial don't allow to use `master` as a bookmark name and this test failed on some machines. this PR renames the bookmark to `main` instead
=> don't use `master` as hg bookmark name

integration-tests/__tests__/multi_project_runner.test.js
this test always fails if watchman is installed on the machine (true for facebook laptops)
this is obviously a monkeypatch.
would jest be open to adding an env variable check?
like
```js
const watchmanEnabled = !!process.env.JEST_USE_WATCHMAN;
```
this will remove the rest of the noise (we have a few dozen warnings during the full test run).
we can't easily remove them by passing `--no-watchman` because most of the tests run in the subprocess
=> don't use watchman in MPR test

docs/MockFunctionAPI.md
To make the MockFunctionAPI doc to be consistent about which Jest version the new APIs are available like other API docs
- Run `yarn start` in the website directory.
- Browse to http://localhost:3000/jest/docs/en/mock-function-api.html using any browsers
- Check if the 4 methods **mockFn.mockResolvedValue(value)**, **mockFn.mockResolvedValueOnce(value)**, **mockFn.mockRejectedValue(value)**, **mockFn.mockRejectedValueOnce(value)** have the text `Available in Jest 22.2.0+`
=> Update MockFunctionAPI doc to be consistent like other API docs

.circleci/config.yml
Should fix #5687 and fix #5526.
- put the CircleCi build to broken state
- fix it
=> Fix restore-cache issue on CircleCi

docs/MoreResources.md
Link to React tests is broken. Replaced the value with an existing url
=> Fix MoreResources.md react link

CHANGELOG.md, docs/TutorialReact.md, packages/jest-runtime/src/__tests__/__snapshots__/script_transformer.test.js.snap, packages/jest-runtime/src/script_transformer.js
In theory, this shouldn't be needed anymore. Committing from GitHub, trusting CI to yell at me if something is wrong.
All should be green
=> remove retainLines from coverage instrumentation

packages/jest-jasmine2/src/__tests__/Suite.test.js, packages/jest-jasmine2/src/jasmine/Suite.js
because we can have a "describe" block but no "it" blocks inside
Fixes #5531
=> fixes #5531

examples/snapshot/package.json
The original `package.json` uses the latest version of all the packages except for React which is fixed to `15.4.2`. This now breaks the unit tests unless you upgrade to React 16+.
To test the changes:
```bash
cd examples/snapshot
yarn install
yarn jest
```
=> Example should use always the latest React version

CHANGELOG.md, docs/MockFunctions.md
I find the current docs on mocking lacking in the area of mocking an existing module. The hope is this example will show people a simple, real-world way to mock node modules (whether from npm or in their own projects). 
I looked through all the docs and couldn't find a clear example like this so I hope it is helpful to others!
Not relevant
=> Add some docs on using `jest.mock(...)`

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/to_throw_matchers.test.js.snap, packages/expect/src/__tests__/is_error.test.js, packages/expect/src/__tests__/to_throw_matchers.test.js, packages/expect/src/index.js, packages/expect/src/to_throw_matchers.js, packages/expect/src/utils.js
Fix 1)
Fixes `rejects.not` path, where previously regular (non-promise) matcher was used.
Fix 2)
Current behavior of `toThrow` matcher allows to pass on any resolved/rejected promise. For example:
```
// Will successfully pass the test
test('Resolved promise', async () => {
await expect(Promise.resolve('anything')).resolves.toThrow();
});
```
I propose to pass `toThrow` tests only if promise resolves/rejects to `Error` object. Also see https://github.com/facebook/jest/pull/4884#issue-152281796
Tests have been added and run successfully.
=> [WIP] Make toThrow matcher pass only if Error-like object is returned from promises

packages/jest-cli/src/__tests__/watch.test.js, packages/jest-cli/src/jest_hooks.js, packages/jest-cli/src/watch.js
Feedback would be awesome!
If we want to enable stuff like test path typeahead in plugins, it seems that we would need to provide a way to get access to all the test files.
=> Add fsChange hook for plugins

CHANGELOG.md, packages/babel-jest/src/index.js, packages/jest-runtime/src/script_transformer.js
Our build system does not cache the results of building a project when it emits warnings. We noticed that when jest ran on some of our larger files, it was emitting a warning of the form: 
[BABEL] Note: The code generator has deoptimised the styling of "[Path to File]" as it exceeds the max of "500KB".
Digging in deeper shows that script_transformer.js runs babel for coverage mode, but does not respect any existing babel configurations. This particular babel warning is only emitted when [compact](https://babeljs.io/docs/usage/api/) is left with the default value of auto, setting it to either true or false would cause this warning to no longer be emitted. I set it to false since it matches the behavior of auto for most files.
Should be a reasonably safe change.
=> Set compact to false to avoid Babel warnings on large files (Fixes #5703)

CHANGELOG.md, packages/jest-config/src/utils.js
Printing out rootDir when runtime file is not found.
Given the following jest project configuration. Jest should log the `rootDir` to the standard output if the `setupFile` is not found.
```
{
"setupFiles": [
"<rootDir>/config/polyfills.js"
]
}
```
=> Add rootDir to runtime FileNotFound error message (#5693)

CHANGELOG.md, packages/jest-cli/src/jest_hooks.js, packages/jest-cli/src/watch.js
Changelog for #5708 and update fs -> file
=> Add changelog for fileChange and update fs -> file

CHANGELOG.md, docs/ExpectAPI.md, integration-tests/toThrowErrorMatchingSnapshot/__tests__/accept-custom-snapshot-name.test.js, packages/expect/src/__tests__/asymmetric_matchers.test.js, packages/expect/src/__tests__/utils.test.js, packages/expect/src/asymmetric_matchers.js, packages/expect/src/index.js, packages/expect/src/utils.js
Closes #5510 
Add inverse asymmetric matchers for `arrayContaining`, `objectContaining`, `stringContaining`, and `stringMatching`.
Added unit tests.
~~Should I add inverse matchers for `.any` and `.anything`?~~
=> add inverse expect asymmetric matchers

CHANGELOG.md, docs/MockFunctionAPI.md, packages/jest-mock/src/index.js
`mockRejectedValue[Once]` may cause an unhandled rejection. It is not easy to understand why this happens if you haven't already encountered this problem.
Details in related [issue](https://github.com/facebook/jest/issues/5721).
=> implement mockResolved/RejectedValue methods using mockImplementation

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/__tests__/matchers.test.js
Changes from #5367  also affected `toMatchObject`. I added some test cases to proof that behavior and expanded the changelog entry.
It is probably a good idea to show class instance properties when the objects did not match. Currently the diff only shows properties for which `.hasOwnProperty` is true.
https://github.com/facebook/jest/blob/74bf072e43789bf5bcfe85f2aa9492905c4d2e9a/packages/expect/src/utils.js#L93-L97
=> docs: Expand changelog entry for #5367

.vscode/launch.json, .vscode/tasks.json
Now you can trigger the watcher inside the editor, and use the debugging tool to look through the transpiled code. 
Couldn't get source maps working, gave it ~2 hours. Mainly it's a limitation on vscode's side that a sourcemap url change can only be reflected with one glob, e.g. `app/source/*` -> `app/dist/*`, but for yarn workspace/lerna repos, it needs to to be `app/packages/*/source/*`  -> `app/packages/*/dist/*`.
It still works well if you throw `debugger // eslint-disable-line` anywhere in the codebase though, and that was enough for me to be productive 👍
=> Add support for debugging Jest inside the current file

CHANGELOG.md, docs/Puppeteer.md
At Smooth Code, we use Jest + Puppeteer testing in a lot of projects. I decided to open source our configuration under [Jest Puppeteer](https://github.com/smooth-code/jest-puppeteer).
I think it could be valuable to mention it in Puppeteer section since it makes Puppeteer testing easy.
=> docs: mention Jest Puppeteer Preset

CHANGELOG.md, integration-tests/__tests__/expect_in_vm.test.js, integration-tests/expect-in-vm/__tests__/expect-in-vm.test.js, integration-tests/expect-in-vm/package.json, packages/expect/src/matchers.js, packages/expect/src/to_throw_matchers.js
`instanceof RegExp` will not be true for RegExp objects created inside of a different NodeJS VM or Window.
This commit fixes this issue by checking for the existence of `test` function on the object instead.
Added integration test which otherwise failed without this fix.
=> fix(expect): do not rely on 'instanceof RegExp'

CHANGELOG.md, docs/Configuration.md, packages/jest-cli/src/__tests__/test_scheduler.test.js, packages/jest-cli/src/test_scheduler.js
Some runners for tools that can not be run in parallel need a way
to specify that they should not be executed in parallel. This commits
adds this functionality. This closes #5706
Unit tests are included
=> Enable single thread mode for runner

CHANGELOG.md, docs/MockFunctionAPI.md, docs/MockFunctions.md, packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
Enhances function mocks to a expose a list of return values on the `mock` property. 
Fixes #5738.
Added a few new unit tests to `jest_mock.test.js` to specifically test the new feature. Ran `yarn jest -- jest_mock` to confirm that both the new unit tests and all pre-existing unit tests for `jest-mock` are passing.
Please let me know if there are any additional scenarios I should unit test.
=> Enhance function mocks to expose a list of returned values.

.prettierignore, .vscode/settings.json, docs/Configuration.md, examples/typescript/package.json, integration-tests/__tests__/__snapshots__/show_config.test.js.snap, integration-tests/typescript-coverage/__tests__/covered-test.ts, integration-tests/typescript-coverage/covered.ts, integration-tests/typescript-coverage/package.json, packages/jest-config/src/defaults.js, packages/jest-config/src/valid_config.js, packages/jest-editor-support/src/Settings.js
I just noticed we use non-idiomatic glob pattern as a default `testMatch`. It works only because of `micromatch` (glob lib we use) special feature called [_regex logical "or"_](https://github.com/micromatch/micromatch#matching-features). 
I think we shouldn't spread invalid glob patterns, so instead of `something.(foo|bar)` we should go with `something.+(foo|bar)` for example.
Tests should pass
=> Use valid glob pattern instead of micromatch-specific

docs/ManualMocks.md
demonstration code is here: https://github.com/antialias/jest-test/tree/automock-false-does-not-use-manual-mocks
```js
// jest.config.js
automock: false
}
```
```js
// src/a.js
module.exports = 'not mocked'
```
```js
// src/__mocks__/a.js
module.exports = 'mocked'
```
```js
// src/__tests__/a.js
const a = require('../a')
describe('a module', function () {
it('is not mocked', function () {
expect(a).toEqual('not mocked')
})
})
```
=> manual mocks do not automatically take precedence over modules unless automock is true

docs/Configuration.md
The `clearMocks` section of the _Configuring Jest_ document seems to be out of order. It appears that the sections of this page are meant to be kept in alphabetical order. I noticed the issue because of the autogenerated TOC.
I hope this helps :D
=> Fixes ordering of clearMocks in Configuring Jest

CHANGELOG.md, docs/MockFunctionAPI.md, packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
Allows unit tests to easily access references to errors that were thrown by all calls to a mock function.
`MockFunctionState` has a new `thrownErrors` property that is an array containing an entry for each call to the mock. If a call to the mock threw an error, a reference to the thrown error is stored in the array. Otherwise, `undefined` is stored in the array.
Also fixes: https://github.com/facebook/jest/issues/5761
Added a new unit test. Ran `yarn run jest jest_mock` to confirm that new and existing mock unit tests are passing.
=> [jest-mock] Track thrown errors in MockFunctionState

integration-tests/__tests__/__snapshots__/jest.config.js.test.js.snap, integration-tests/__tests__/jest.config.js.test.js, integration-tests/__tests__/version.test.js, packages/jest-config/src/index.js
It appears that the file name is called `jest.config.js` in [the configuration documentation](https://facebook.github.io/jest/docs/en/configuration.html).
No tests necessary - only comments and test labels have been changed.
=> Fix config filename

packages/jest-worker/src/__performance_tests__/test.js, packages/jest-worker/src/__performance_tests__/workers/jest_worker.js, packages/jest-worker/src/__performance_tests__/workers/worker_farm.js, packages/jest-worker/src/types.js, packages/jest-worker/src/worker.js
This PR modifies the way internal worker queues are managed, passing from an array to a linked-list, improving a 10% the current benchmark, and 400% over a new benchmark.
When `jest-worker` was initially benchmarked, it was done by using not so many jobs (~10k), but very heavy in time. While this is the usual approach (few jobs, lots of time per job), sometimes you have the opposite (i.e. lots of jobs, but each of them very fast). _This is actually what `jest-haste-map` does._
Since the internal queue was an array, re-indexing the queue is a `O(n)` operation, which becomes especially relevant on the second scenario. Switching to a linked list means that all operations for advancing the queue become `O(1)`, no matter its length. This results in massive speed improvements on really long …
=> Improve jest-worker (up to 4x)

integration-tests/__tests__/__snapshots__/transform.test.js.snap, package.json, packages/jest-cli/package.json, yarn.lock
There is a problem with the current version of `istanbul-api` depedency.
It uses an older version of `istanbul-lib-instrument` which causes the tests to fail when they run with the `--coverage` flag.
The bug is the following:
The bug was fixed 6 days ago at `istanbul-lib-instrument` and is [this line](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/src/visitor.js#L23). `istanbul-api` updated their dependency [with the fixed version](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-api/package.json#L43)
So this pull request brings this fix to Jest.
=> Update istanbul depedency to fix coverage issue

docs/Puppeteer.md
I deprecated "jest-puppeteer-preset" in favor of "jest-puppeteer". It is just a fix in documentation.
=> Replace jest-puppeteer-preset by jest-puppeteer

docs/Es6ClassMocks.md
The correct location for mocks is `__mocks__/`, not `__mocks/`.
I didn't add anything in the CHANGELOG as I don't think it's worth it for a typo fix.
N/A
=> Fix typo in Es6ClassMocks.md

CHANGELOG.md, integration-tests/__tests__/global_setup.test.js, integration-tests/__tests__/global_teardown.test.js, integration-tests/global-setup/invalid_setup.js, integration-tests/global-teardown/invalid_teardown.js, packages/jest-cli/src/run_jest.js
This PR solves #5628 by providing a descriptive error message for cases that `globalSetup` or `globalTeardown` does not export a function.
Verify that we see the wanted error in stdout after using an invalid `globalSetup`/`globalTeardown` file.
=> add a descriptive error for invalid globalSetup or globalTeardown

packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/constants.js, packages/jest-haste-map/src/crawlers/__tests__/node.test.js, packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js, packages/jest-haste-map/src/crawlers/node.js, packages/jest-haste-map/src/crawlers/watchman.js, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/types.js, packages/jest-haste-map/src/worker.js, types/HasteMap.js
Adds support to `jest-haste-map` to provide in their public API the SHA-1 of the file. This SHA-1 is extracted from `watchman` when possible, and when not, it is processed by the worker tied to `jest-haste-map`. This however only happens when requested via the `sha1` option when building the Haste Map.
The benefits of this are mainly related to cache invalidation, which is the same reason on why it first got built in `watchman` itself.
I've added tests to confirm that when the SHA-1 is `null`, and it is requested by the user,  the worker will process it (which is what happens with the `node` crawler).
=> Implement SHA-1 support in jest-haste-map

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/spy_matchers.test.js.snap, packages/expect/src/spy_matchers.js
Solves #5843 
Old output:
New output:
=> Improve output format for mismatchedArgs in mock/spy calls

CHANGELOG.md, integration-tests/__tests__/__snapshots__/failures.test.js.snap, integration-tests/__tests__/__snapshots__/globals.test.js.snap, scripts/build.js
=> Run prettier on output in build dirs

CHANGELOG.md, packages/jest-runner/src/__tests__/test_runner.test.js, packages/jest-runner/src/index.js
Following #5494, provide `process.env.JEST_WORKER_ID="1"` for cases when Jest runs the tests on the main process.
https://github.com/facebook/jest/blob/6a77ee37ec2d46ece7e9cfd0f891d11c113cc4c4/packages/jest-cli/src/test_scheduler.js#L88-L96
So our tests code could stay the same, without the need to check whether `process.env.JEST_WORKER_ID` is `undefined`.
Test that after we run jest with `{serial: true}` `process.env.JEST_WORKER_ID` will be `"1"`
=> assign process.env.JEST_WORKER_ID=1 when in runInBand mode

packages/expect/README.md
It's kind of weird that [the expect package on npm](https://www.npmjs.com/package/expect) doesn't have a readme. This adds a simple one which directs users to Jest's docs for `expect`.
N/A
=> Create basic readme for expect package

packages/jest-haste-map/src/haste_fs.js
In order to access the SHA-1, if requested, we need to expose a public getter.
=> Expose SHA-1s via HasteFS

CONTRIBUTING.md
CONTRIBUTING.md has links to Yarn and homebrew, but not Mercurial.
This PR adds link to Mercurial website https://www.mercurial-scm.org/ if contributors want to find more info.
It's just a documentation update in CONTRIBUTING.md, testing not necessary.
=> Added link to Mercurial

CHANGELOG.md, integration-tests/__tests__/__snapshots__/globals.test.js.snap, packages/jest-jasmine2/src/jasmine/Env.js, packages/jest-jasmine2/src/tree_processor.js
As agreed with @rickhanlonii, I've extracted the refactorings I've done for #5673:
1. Previously the `topSuite` was being setup separately to other suites, but in fact all suites require the same setup steps (mainly `defaultResourcesForRunnable`). This PR removes the duplicated logic from `Env.execute` and instead uses the same, unified suite logic that only differs in the way it's reported (e.g. `reporter.suiteDone` vs `reporter.jasmineDone` for the `topSuite`).
2. Moved out `executionSetup` and `executionTeardown` into separate functions to simplify the body of `Env.execute`. By reusing `currentlyExecutingSuites`'s `length` property for setup and teardown checks, it makes the method more robust.
3. Made it easier to understand what is going on in the `treeProcessor` function, by …
=> Refactor: unify handling of topSuite and children suites + increase readability

CHANGELOG.md, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/lib/__tests__/extract_requires.test.js, packages/jest-haste-map/src/lib/extract_requires.js
Support `import('some-module')` when building up a dependency tree within `jest-haste-map`.
Assertion added
=> haste-map: Support extracting dynamic `import`s

docs/Configuration.md
the previous link brought to the deprecated istanbul github project.
=> use up-to-date link to istanbul reporters

docs/CLI.md
A documentation note, following the discussion on #5882
Should clarify that the regex on testNamePattern is matched against the full name of the test.
=> add a note that testNamePattern regex is matched against full name

packages/jest-util/src/create_process_object.js
When creating a mock object for `process`, `process.send` is just referenced from the parent context, which means that a test has access to the real IPC channel established by `jest-worker`, thus breaking the sandbox.
As per the Node definition, `process.send` is not defined if the Node process hasn't started off a `fork` call; but this shouldn't be an issue, because `send` has always been exposed and no one complained so far 🙃
This should also fix #5891.
=> Override "process.send" with a mock

CHANGELOG.md, packages/jest-editor-support/index.d.ts, packages/jest-editor-support/src/Runner.js, packages/jest-editor-support/src/__tests__/runner.test.js, packages/jest-editor-support/src/types.js
Folks who are using the vscode-jest extension have reported that there are ANSI color codes appearing in the inline error messages. This PR adds an option to the test runner that will start Jest using the `--no-color` CLI arg.
This PR will close jest-community/vscode-jest#279.
Is it possible to have this PR deployed in v21 or v22?
I've added a test that should provide enough code coverage for this quick change.
=> Add an option to use --no-color chalk CLI argument

website/versioned_docs/version-22.4/MockFunctionAPI.md
The sugar mentioned here is slightly different on master and 22.4
Closes https://github.com/facebook/jest/issues/5839
=> Fix 22.4 docs for mockResolveValue

packages/jest-config/package.json, packages/jest-runtime/package.json
I noticed that jest-runtime doesn't make any require to babel-jest, so it doesn't need to be there. Inversely, jest-config needs babel-jest to be able to work properly (because of [normalize](https://github.com/facebook/jest/blob/master/packages/jest-config/src/normalize.js#L105-L137)), so it needs to be declared as a dependency.
I guess it was put this way so that babel-core would be used for both jest-config and jest-runtime, but that's an optimization that should be left to the package manager.
Existing tests should pass, no new test should be needed.
=> Moves babel-jest into jest-config rather than jest-runtime

CHANGELOG.md, integration-tests/__tests__/regex_(char_in_path.test.js, packages/jest-regex-util/src/__tests__/index.test.js, packages/jest-regex-util/src/index.js
=> Fix handling regex symbols in tests path on Windows

CHANGELOG.md, docs/CLI.md, integration-tests/__tests__/coverage_report.test.js, packages/jest-cli/src/cli/args.js
The change in https://github.com/facebook/jest/pull/5537 was breaking, and not one we're looking to keep. Instead, the option should be repeated for multiple values.
Closes https://github.com/facebook/jest/issues/5905
- Updated the existing test to use multiple args, snapshot does not need updated
=> Switch collectCoverageFrom back to a string

docs/ExpectAPI.md, website/versioned_docs/version-22.0/ExpectAPI.md, website/versioned_docs/version-22.1/ExpectAPI.md, website/versioned_docs/version-22.2/ExpectAPI.md, website/versioned_docs/version-22.3/ExpectAPI.md, website/versioned_docs/version-22.4/ExpectAPI.md
Summary:
The current docs indicate that a test like the following should fail,
but it actually passes:
```js
function scary() {
throw new Error("...Boo!");
}
it("should be scary", () => {
// Should fail, according to current docs: not an exact match.
// Actually passes.
expect(() => scary()).toThrow("Boo");
});
```
We can see in the implementation that the actual behavior is that
strings are simply injected into `RegExp`s, without anchors:
https://github.com/facebook/jest/blob/5a21be3e07c223ba9fbb434f26bce96da0dddd31/packages/expect/src/to_throw_matchers.js#L53-L55
This patch corrects the docs accordingly. Inspecting prior versions of
the code indicates that this behavior has been present back to at least
v22.0, so I have updated historical docs, too.
Test Plan:
Create a new project, and …
=> Correct docs about `expect.toThrow(String)`

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/spy_matchers.test.js.snap, packages/expect/src/spy_matchers.js
Pull request based on https://twitter.com/lukesobek/status/982508206919442432 to extend the message `.toHaveBeenCalled`  returns on failure
from `Expected mock function to have been called.`  
to `Expected mock function to have been called, but it was not called.`
The pull request puts the behavior of .toHaveBeenCalled in line with other .toHaveBeenCalled... explicitly stating what was expected and what the result was.
2 related snapshots were updated, jest returned a fully green run
=> Extends .toHaveBeenCalled message

packages/jest-environment-jsdom/src/index.js
The `load` event is triggered asynchronously by JSDom, and, [since it happens into the constructor](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/Window.js#L595), nothing can be done.
However, an early check for `document` existence is done before (as you wouldn't be able to check its status if it's already gone). Based on this, for synchronous tests, we can skip the `load` event, which was anyway triggered later.
=> Dispose document when tearing down JSDom environment

docs/ExpectAPI.md
Describe in #5926
None. Documentation update.
=> [expect] correct documentation for stringMatching, not.stringMatching to be in sync with Flow type

integration-tests/Utils.js, integration-tests/__tests__/__snapshots__/globals.test.js.snap, integration-tests/__tests__/__snapshots__/show_config.test.js.snap, integration-tests/__tests__/globals.test.js, packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js
The `babel-jest` default transform is currently located through `Resolver.findNodeModules`. This has the inconvenient that when using a custom resolver, this new custom resolver will be completely  bypassed.
Given that `require.resolve` is the standard and safe way to obtain the requirable path to a package, I think we should use it whenever possible, at least until the custom resolver has been properly setup (ie after the config has been normalized).
Two notes:
- This might be a slight breaking change if users were specifying different version of `babel-jest` than the default. I'm not sure it's often the case, so it doesn't feel too problematic.
- The `regenerator` package is still located using `Resolver.findNodeModules`. It would be nice to fix this as well, but since this package is …
=> Updates babel-jest resolution

CHANGELOG.md, docs/ExpectAPI.md, integration-tests/resolve-node-module/__mocks__/mock-module-alt/index.js, integration-tests/resolve-node-module/__mocks__/mock-module-alt/package.json, integration-tests/resolve-node-module/__tests__/resolve-node-module.test.js, packages/jest-resolve/src/default_resolver.js
Resolves #5967.
#5967 resolved an issue with module resolution when the main entry in package.json is set to ".".  However, there are other ways to refer to the current directory, such as "./" (or even "././").  This PR generalises the fix by checking whether the resolved path for package main differs from the resolved path for ".".
New test added to explicitly test "./" along with ".".
=> Generalise package main resolving issue

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/matchers.js, packages/jest-matcher-utils/src/index.js
Suggest `toContainEqual` as per #5924
=> Suggest toContainEqual

CHANGELOG.md, integration-tests/__tests__/generator_mock.test.js, integration-tests/generator-mock/__tests__/generator_mock.test.js, integration-tests/generator-mock/index.js, integration-tests/generator-mock/package.json, packages/jest-mock/src/index.js
Fixes #5979 
Integration Tests Included
=> Add auto-mock support for generators

CHANGELOG.md, integration-tests/__tests__/__snapshots__/failures.test.js.snap, integration-tests/__tests__/failures.test.js, integration-tests/__tests__/stack_trace.test.js, integration-tests/failures/__tests__/during_tests.test.js, packages/jest-jasmine2/package.json, packages/jest-jasmine2/src/__tests__/expectation_result_factory.test.js, packages/jest-jasmine2/src/expectation_result_factory.js, packages/jest-jasmine2/src/jasmine/Env.js
See #3839 - hopefully this helps. If not, properly showing non-Error objects is still a win.
This is mostly lifted from https://github.com/jasmine/jasmine/commit/8807bbb85042a845c81149bf6c2865b477989399#diff-f41e57b2889bae3046aa9f352699785c . The original tests for Env were removed so I just tested manually and that seemed fine.
=> jest-jasmine2: pretty-print non-Error errors

CHANGELOG.md, integration-tests/__tests__/stack_trace.test.js, packages/jest-jasmine2/src/index.js
I'm not really sure why this is needed. The runtime error is thrown from the jest environment (either node or jsdom), shouldn't the sourcemap-support be installed properly there?
/cc @jwbay @felipeochoa 
Fixes #5925.
New assertion added to existing test which fails without the code change.
=> install sourcecmap-support into normal runtime as well

packages/jest-util/src/fake_timers.js
This pull request contains follow up ESLint fix for https://github.com/facebook/jest/pull/5966
_code grep did show that eslint has been also disabled also in other places in jest code for sepcial cases - i guess this one will counter one?_
> as reported in https://github.com/facebook/jest/pull/5966#issuecomment-381396303
/cc @SimenB @AhnpGit 
run linter> `yarn lint`
=> Disable eslint no-bitwise for mock timer delay check

CHANGELOG.md, packages/babel-jest/src/__tests__/index.js, packages/babel-jest/src/index.js, packages/jest-runtime/src/script_transformer.js, types/Transform.js
Seeing as we're gearing up for a major, I thought we could land this now.
Ref discussion in #5177
Green CI
=> always return object from babel-jest transform

CHANGELOG.md, integration-tests/__tests__/__snapshots__/custom_matcher_stack_trace.test.js.snap, integration-tests/__tests__/__snapshots__/failures.test.js.snap, integration-tests/__tests__/__snapshots__/globals.test.js.snap, integration-tests/__tests__/failures.test.js, packages/jest-message-util/src/index.js
Cuz it's useful and the implementation is "free" for us 🙂 
Updated snapshots
=> include columns in stack frames

CHANGELOG.md, integration-tests/__tests__/__snapshots__/require_after_teardown.test.js.snap, integration-tests/__tests__/require_after_teardown.test.js, integration-tests/require-after-teardown/__tests__/late-require.test.js, integration-tests/require-after-teardown/index.js, integration-tests/require-after-teardown/package.json, packages/jest-runtime/package.json, packages/jest-runtime/src/index.js
Instead of this:
Do this: 
While still not super pretty, it's _better_.
Integration test included
=> Throw a more useful error when trying to require modules after the test environment is torn down

packages/jest-jasmine2/src/tree_processor.js
Fixes #5964 by partly restoring behavior from before #5585.
Moves the `wrapChildren` into higher scope to enforce undocumented execution order of `beforeEach` added inside of tests.
=> fix(treeProcessor): revert a small change from the #5585 refactoring

CHANGELOG.md, integration-tests/__tests__/__snapshots__/failures.test.js.snap, integration-tests/__tests__/failures.test.js, packages/expect/src/extract_expected_assertions_errors.js, packages/expect/src/index.js
Pointing back to the failing test is nice.
Half of #5104
Green CI
=> add stack trace on expect.(has)Assertions

integration-tests/custom-resolver/__tests__/custom-resolver.test.js, integration-tests/custom-resolver/fake-regenerator.js, integration-tests/custom-resolver/resolver.js, packages/jest-config/src/normalize.js
This diff is just a followup to #5976 - I missed this call because it uses `findNodeModule` instead of `resolve` like the others (because it doesn't want to throw if the result cannot be found).
Tests should continue to pass.
=> Makes regenerator go through custom resolvers as well

CHANGELOG.md, integration-tests/__tests__/__snapshots__/failures.test.js.snap, integration-tests/__tests__/failures.test.js, integration-tests/failures/__tests__/__snapshots__/snapshot_named.test.js.snap, integration-tests/failures/__tests__/snapshot_named.test.js, packages/jest-snapshot/src/State.js, packages/jest-snapshot/src/index.js
Implements #6003.
Added [named snapshot unit test](https://github.com/hroemer/jest/blob/issue-6003/integration-tests/failures/__tests__/snapshot_named.test.js) and additional test in [failures.test.js](https://github.com/hroemer/jest/blob/issue-6003/integration-tests/__tests__/failures.test.js#L107:L115)
=> #6003: include snapshot name in error message

integration-tests/__tests__/__snapshots__/failures.test.js.snap, packages/jest-jasmine2/src/expectation_result_factory.js, packages/jest-jasmine2/src/jasmine/Env.js
See https://github.com/facebook/jest/pull/6008/files#r182010622.
No changelog as it's a bug fix for a PR merged to master today.
Green CI
=> fix stack-trace when calling `done` with non-error

docs/ManualMocks.md, website/versioned_docs/version-22.4/ManualMocks.md
For me, it was really not clear from docs where exactly in terms of proper scope I have to call `jest.mock('moduleName')` function, so I spent a couple of hours thinking that the mock function itself was broken and I even created this issue [issues#5993](https://github.com/facebook/jest/issues/5993)
Pull request changes documentation of ManualMock.md (the version of docs is 22.4)
To test it navigate to the root directory of the project and run next commands:
```
cd website 
yarn
yarn start
```
Then open Jest website and navigate to API -> "Manual Mocks" and see changes
Tests can be run from the root project directory via:
```
yarn test
```
=> Clarify position mock function call in docs

docs/Configuration.md
Single quoted strings are not allowed in JSON
=> Fix testMatch config in docs

integration-tests/custom-resolver/__mocks__/manual-mock.js, integration-tests/custom-resolver/__tests__/custom-resolver.test.js, integration-tests/custom-resolver/bar.js, integration-tests/custom-resolver/manual-mock.js, packages/jest-resolve/src/__tests__/resolve.test.js, packages/jest-resolve/src/index.js
#4174 introduced a few lines of code that broke automocking when using custom resolvers (reported as #4985). This new diff reverts the part of the code responsible for the breakage.
I'm not entirely sure what was the purpose of the previous code - if I understand correctly it was ensuring that resolvers were correctly called when calling `require()` from within a mock, but I added an integration test and it seems to work fine even with the code removed.
Maybe @midzelis can shed some light on this?
I've added a test to make sure that automocking would continue working, removed a unit test that was testing the behavior of `getMockModule` (since it was testing the behavior causing the bug), and added a new test to make sure that `require()` calls work with manual mocking + custom resolvers.
=> Fixes automocks when using resolvers

packages/jest-haste-map/src/crawlers/watchman.js
Just found that `content.sha1hex` can be an error object (the docum... _oh, wait_), which is not very good since we do not check the validity of the property getting returned.
This PR adds a defensive line verifying it is a string, and also asserts that the length is `40`, because a SHA-1 is formed by 20 bytes, and the encoding transmission is `hex`. The validity check is not perfect, but it's good enough IMO.
When returning `null`, it falls back to computing it on the worker, as the Node crawler does right now.
=> Ensure that watchman returned a SHA-1

CHANGELOG.md, integration-tests/__tests__/__snapshots__/failures.test.js.snap, integration-tests/__tests__/failures.test.js, packages/jest-jasmine2/src/assert_support.js, packages/jest-jasmine2/src/jasmine/Spec.js
Node 10 should drop tomorrow. While Jest works just fine (after a bug fix in `rc.1`), our test suite will break because of some breaking changes in the messages from `assert`.
This PR normalizes the message across different node version (going as far as extracting the whole `ifError` out of the snapshot), and makes sure to remove the generated message from the stack trace.
The last one is pretty critical (I wonder if we should do a patch release for jest 22, even though it's a pain due to the landed majors), as the diff from node differ (hah) from ours - to the point where I think it'll confuse consumers of Jest. See: ![image](https://user-images.githubusercontent.com/1404810/39114230-7f825e22-46de-11e8-8352-026fd1102634.png)
CI should still be green. Will add node 10 to circle whenever …
=> Fix test suite for Node 10

CHANGELOG.md, integration-tests/__tests__/__snapshots__/failures.test.js.snap, integration-tests/__tests__/failures.test.js, packages/jest-jasmine2/src/assert_support.js
We've merged node 10 compat into master (#6055), but because we've landed breaking changes leading up to a v23, we cannot release it.
I think the changes to the message from the assert module (a diff view with swapped `+` and `-` from what Jest uses) are large enough that it will confuse users of Jest, so we should make a patch release of Jest 22 with just the removal of that diff.
In this PR, I've basically cherry picked #6055 on top of the 22.4.2 release commit. I've also setup a https://github.com/facebook/jest/tree/22.x branch which this can be merged to.
See this screenshot for example of the output this PR cleans up: ![image](https://user-images.githubusercontent.com/1404810/39114230-7f825e22-46de-11e8-8352-026fd1102634.png)
Green CI. `node@10.0.0-rc.2` also passes with this change.
=> remove assert message from stack

docs/Es6ClassMocks.md
Fix `JavaScript` naming in docs.
=> Change Javascript -> JavaScript

CHANGELOG.md, packages/babel-plugin-jest-hoist/src/index.js
This PR adds the `console` global variable to the whitelisted identifiers.
The issue is mainly with CIs that use this. The issue cannot be seen if you don't have any mocks locally.
```
/Users/vagrant/git/node_modules/react-native/jest/setup.js: babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
Invalid variable access: console
Whitelisted objects: Array, ArrayBuffer, Boolean, DataView, Date, Error, EvalError, Float32Array, Float64Array, Function, Generator, GeneratorFunction, Infinity, Int16Array, Int32Array, Int8Array, InternalError, Intl, JSON, Map, Math, NaN, Number, Object, Promise, Proxy, RangeError, ReferenceError, Reflect, RegExp, Set, String, Symbol, SyntaxError, TypeError, URIError, …
```
=> add console global to the whitelisted identifiers

CHANGELOG.md, packages/jest-worker/src/__tests__/index-integration.test.js, packages/jest-worker/src/__tests__/index.test.js, packages/jest-worker/src/__tests__/worker.test.js, packages/jest-worker/src/index.js, packages/jest-worker/src/types.js, packages/jest-worker/src/worker.js
The cache for making workers of jest-worker sticky to a worker using `computeWorkerKey` used to only be set after the worker had processed the request.
This caused issues when doing multiple calls in parallel, since they would be distributed along workers, ignoring the `computeWorkerKey` param.
This fixes #5956.
Unit tests
=> Stick calls to workers before processing them

CHANGELOG.md
It referred to another PR instead of the one actually containing the changes. See [PR#6075](https://github.com/facebook/jest/pull/6075).
_none_
=> Fix incorrect `console` global variable pr

CHANGELOG.md, integration-tests/__tests__/__snapshots__/failures.test.js.snap, packages/jest-jasmine2/src/jasmine/Env.js, packages/jest-jasmine2/src/tree_processor.js
The TreeProcessor refactor introduced a change on the behavior of `beforeEach` inside `it`. While this is an edge case, Facebook (and potentially anyone using inline requires) is relying in it.
Some fixes have been suggested, but for the moment we'll just revert the change. cc / @niieani
=> Revert changes on the TreeProcessor (#6006 and #5885)

.circleci/config.yml
Node 10 is out, let's make sure we work. We should as #6055 is merged 🤞 
Green CI
=> Test with Node 10 on CI

CHANGELOG.md, integration-tests/__tests__/__snapshots__/globals.test.js.snap, integration-tests/__tests__/stack_trace.test.js, packages/jest-jasmine2/src/index.js
In #5945 we accidentally introduced a memory leak that makes all tests leak. This was detected with the help of @SimenB, by running the `--detectLeaks` flag against the own suite.
It turns out that the fix needs to be done in `source-map-support`, for which [a PR has been put up](https://github.com/evanw/node-source-map-support/pull/215). In the meantime, we will revert the commit.
=> Revert changes for source map suppport (#5945)

.editorconfig
Trailing whitespace is significant in snapshot files, so they should not be trimmed when edited manually.
N/A
=> chore: don't strip trailing whitespace in snapshot files

integration-tests/__tests__/__snapshots__/globals.test.js.snap, integration-tests/__tests__/globals.test.js
A random snapshot is breaking, so we'll fix it by doing some replacements of space characters.
=> Fix snapshots

CHANGELOG.md, packages/pretty-format/src/__tests__/react.test.js, packages/pretty-format/src/plugins/react_element.js, yarn.lock
Supersedes https://github.com/facebook/jest/pull/6076 and adds support for formatting the new Context api. Naming for the `Context` components is up for grabs.
The PR also includes an upgrade of React since it's necessary to test. However once https://github.com/facebook/jest/pull/6090 is merged I can rebase this PR.  
Run tests and make sure they pass.
=> Support forwardRef and Context in pretty-format

integration-tests/multi-project-config-root/bar/__tests__/boggus-bar.test.js, integration-tests/multi-project-config-root/foo/__tests__/boggus-foo.test.js, integration-tests/multi-project-config-root/package.json, packages/jest-config/src/index.js, packages/jest-config/src/normalize.js
This diff fixes #5479 by allowing project configurations to specify a custom rootDir that only applies to them.
I added an integration test.
=> Allows projects to specify individual root dirs

CHANGELOG.md, packages/jest-message-util/src/__tests__/__snapshots__/messages.test.js.snap, packages/jest-message-util/src/__tests__/messages.test.js, packages/jest-message-util/src/index.js
=> jest-message-util: don't exclude trace lines with `vendor` anymore

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/jest-matcher-utils/src/index.js
change with regards to #6103 
```
•100% ➜ node -v && yarn -v
v8.9.3
1.6.0
•100% ➜ yarn test
yarn run v1.6.0
$ yarn typecheck && yarn lint && yarn jest
$ flow check --include-warnings
Found 0 errors
$ eslint . --cache --ext js,md
$ node ./packages/jest-cli/bin/jest.js
PASS  integration-tests/__tests__/babel_plugin_jest_hoist.test.js (5.885s)
PASS  integration-tests/__tests__/test_path_pattern_reporter_message.test.js (9.984s)
PASS  integration-tests/__tests__/jasmine_async.test.js (15.625s)
PASS  integration-tests/__tests__/snapshot.test.js (23.556s)
PASS  integration-tests/__tests__/jest_changed_files.test.js (13.844s)
PASS  integration-tests/__tests__/transform.test.js (26.693s)
PASS  integration-tests/__tests__/multi_project_runner.test.js (28.2s)
PASS …
```
=> Change "suggest to equal" message to be more advisory

CHANGELOG.md, website/versioned_docs/version-22.3/SnapshotTesting.md
Fixes #5812
cc: @thymikee @SimenB 
As explained in the issue referenced above (opened by @thymikee), Jest's [Snapshot Testing Guide](https://facebook.github.io/jest/docs/en/snapshot-testing.html) could benefit from some clearer usage guidelines. 
The issue's wording specifically called out adding content that would help devs avoid common mistakes and misuses of snapshot testing. After giving the page a good read it seemed like the guide already had the nucleus of this content with the "Tests Should Be Deterministic" section.
Added some content that closely follows the recommendations outlined in the @kentcdodds's article [Effective Snapshot Testing](https://blog.kentcdodds.com/effective-snapshot-testing-e0d1a2c28eca) referenced in the issue, then grouped this and the existing "Tests …
=> Add a 'best practices' section to the Snapshot Testing Guide

docs/SnapshotTesting.md
In https://github.com/facebook/jest/pull/6101 we added the docs to 22.3 and 22.4 but not master
=> Add snapshot best practices to master docs

CHANGELOG.md, integration-tests/transform/multiple-transformers/__tests__/__snapshots__/multiple_transformers.test.js.snap, packages/pretty-format/src/__tests__/__snapshots__/react.test.js.snap, packages/pretty-format/src/__tests__/react.test.js, packages/pretty-format/src/plugins/react_element.js, packages/pretty-format/src/plugins/react_test_component.js
React plugins for `pretty-format` should not output `undefined` props. 
This matches the behavior of React itself and makes Jest Snapshot tests accurate with the real component representation.
Given the following component:
```
const Link = (props) => <a href="/" target={props.newTab && '_blank'}>link!</a>;
```
Before:
Input | React | Pretty Format
----- | ----- | -----
`<Link />` | `<a href="/">link!</a>` | `<a href="/" target={undefined}>link!</a>`
After:
Input | React | Pretty Format
----- | ----- | -----
`<Link />` | `<a href="/">link!</a>` | `<a href="/">link!</a>`
New unit tests in `pretty-format` to match expectations. These new tests were failing before the fix:
=> Remove undefined props when pretty-format'ing React elements

integration-tests/__tests__/__snapshots__/failures.test.js.snap, integration-tests/__tests__/__snapshots__/snapshot.test.js.snap, integration-tests/__tests__/snapshot.test.js, integration-tests/__tests__/to_match_snapshot.test.js, integration-tests/__tests__/to_throw_error_matching_snapshot.test.js, packages/jest-cli/src/reporters/__tests__/__snapshots__/get_snapshot_status.test.js.snap, packages/jest-cli/src/reporters/__tests__/__snapshots__/get_snapshot_summary.test.js.snap, packages/jest-cli/src/reporters/__tests__/__snapshots__/summary_reporter.test.js.snap, packages/jest-cli/src/reporters/__tests__/get_snapshot_summary.test.js, packages/jest-cli/src/reporters/__tests__/summary_reporter.test.js, packages/jest-cli/src/reporters/get_snapshot_status.js, packages/jest-cli/src/reporters/get_snapshot_summary.js, packages/jest-cli/src/reporters/summary_reporter.js, packages/jest-cli/src/reporters/utils.js, packages/jest-cli/src/test_result_helpers.js, types/TestResult.js
This PR makes a number of improvements to the snapshot and test summary outputs, including:
- Printing obsolete test files and names (closes https://github.com/facebook/jest/issues/6074)
- Makes the language for "added" vs "written" more consistent 
- Makes the syntax consistent for "x snapshots (failed|written|obsolete)"
- Makes ordering consistent for in-test summaries and end of test summaries
- Fixes the update notes so they have consistent language and dimming
- Adds obsolete snapshot and file information to the Test Summary
- Switches "obsolete" information to yellow
- Switches "removed" information to green to match "updated"
Updated and added unit and integration tests
For all of these, the left is 22.4 and the right is this PR
=> Better snapshot summaries 

CHANGELOG.md, packages/jest-cli/src/__tests__/watch.test.js, packages/jest-cli/src/get_no_test_found_failed.js, packages/jest-cli/src/watch.js
Fixes #6167 
Changed the 
"Press `f` to run all tests. " to "Press f to quit "only failed tests" mode" when inside only failed tests mode.
Scenario is covered by the "shows the correct usage for the f key in "only failed tests" mode". 
Also:
And
=> fix the #6167 - F key misleading message

CHANGELOG.md, packages/jest-cli/src/reporters/__tests__/summary_reporter.test.js
Forgot a changelog entry and left in some personal todos in #6181 🙈
=> Minor cleanups from #6181

CHANGELOG.md, packages/jest-environment-jsdom/src/__mocks__/index.js, packages/jest-runtime/src/index.js, packages/jest-util/src/__tests__/fake_timers.test.js, types/Jest.js
It's not documented, people should use `jest.fn` instead. Ref #2533, it's been long enough, IMO 🙂 
Green CI
=> chore: remove `jest.genMockFn` and `jest.genMockFunction`

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/spy_matchers.test.js.snap, packages/expect/src/__tests__/spy_matchers.test.js, packages/expect/src/spy_matchers.js
Fixes #6192 
As detailed in the issue, this features a mock’s custom name more prominently in an error message
I have added the necessary tests to the test suite and ensured they failed expectedly when making changes before updating the snapshots
=> include custom mock names in error messages

packages/jest-editor-support/index.d.ts
According to [the implementation](https://github.com/facebook/jest/blob/f4f51914d577dc53748f599f3f626dfe3154883e/packages/jest-editor-support/src/Snapshot.js#L106) the first parameter of Snapshot constructor is optional.
#trivial
=> [jest-editor-support] update definition

CHANGELOG.md, integration-tests/__tests__/version.test.js, jest, packages/jest-cli/src/cli/index.js
This is just less code on our side. Behaves the same
Green CI
=> chore: use yargs's built-in `version` instead of rolling our own

CHANGELOG.md, integration-tests/__tests__/__snapshots__/failures.test.js.snap, packages/expect/src/matchers.js, packages/expect/src/spy_matchers.js, packages/expect/src/utils.js, packages/jest-diff/src/__tests__/__snapshots__/diff.test.js.snap, packages/jest-diff/src/__tests__/diff.test.js, packages/jest-diff/src/diff_strings.js, packages/jest-diff/src/index.js
Fixes https://github.com/facebook/jest/issues/5657
Adjusted existing tests
=> Support returning diff from oneline strings

CHANGELOG.md, integration-tests/__tests__/__snapshots__/custom_matcher_stack_trace.test.js.snap, integration-tests/__tests__/__snapshots__/detect_open_handles.js.snap, integration-tests/__tests__/__snapshots__/each.test.js.snap, integration-tests/__tests__/__snapshots__/expect-async-matcher.test.js.snap, integration-tests/__tests__/__snapshots__/failures.test.js.snap, integration-tests/__tests__/__snapshots__/module_name_mapper.test.js.snap, integration-tests/__tests__/failures.test.js, packages/expect/src/__tests__/__snapshots__/to_throw_matchers.test.js.snap, packages/jest-jasmine2/src/expectation_result_factory.js, packages/jest-message-util/src/__tests__/__snapshots__/messages.test.js.snap, packages/jest-message-util/src/index.js
We currently indent all lines in error messages the same, regardless of whether or not that line has any content.
This diff just checks if a line is truthy before indenting it.
EDIT: It also has some other minor cleanup of stack traces
Updated snapshots
=> chore: avoid adding trailing whitespace to blank lines in stack traces

packages/jest-environment-node/src/index.js
Fixes #6228 - adds URL and URLSearchParams that is attached to `global` since Node 10
=> Fixes #6228

CHANGELOG.md, packages/jest-snapshot/src/__tests__/__snapshots__/mock_serializer.test.js.snap, packages/jest-snapshot/src/__tests__/mock_serializer.test.js, packages/jest-snapshot/src/mock_serializer.js
Mock functions have recently been updated to not only track params for each call, but also the result of each call (whether it threw an error, what value was returned/thrown).
This PR adds that new information to the serialized representation of a mock function.
As requested in this comment: https://github.com/facebook/jest/pull/5752#issuecomment-386791326
* Updated existing mock_serializer.test.js unit tests to expect additional results data, and updated the mock functions in some tests to actually return a value.
* Added a new unit test to mock_serializer.test.js that involves a call to a mock that returns a value, and another call to the same mock that throws.
* Ran `yarn run jest mock_serializer` and reviewed all snapshot mismatches (caused by the new expected data).
* Ran `yarn run …
=> [jest-mock] Include tracked call results in serialized mock

CHANGELOG.md, docs/WatchPlugins.md, packages/jest-cli/src/__tests__/watch.test.js, packages/jest-cli/src/jest_hooks.js, packages/jest-cli/src/plugins/update_snapshots.js, packages/jest-cli/src/plugins/update_snapshots_interactive.js, packages/jest-cli/src/types.js, packages/jest-cli/src/watch.js
Changed the watch plugin hooks names to be a bit more expressive.
Basically:
* `fileChange` -> `onFileChange`
* `testRunComplete` -> `onTestRunComplete`
Waiting for https://github.com/facebook/jest/pull/5895 to merge so the API is updated in the docs as well.
Adjusted tests
=> Overhaul watch plugin hooks names

CHANGELOG.md, docs/ExpectAPI.md, docs/SnapshotTesting.md, integration-tests/__tests__/to_match_snapshot.test.js, packages/expect/src/__tests__/extend.test.js, packages/expect/src/index.js, packages/jest-snapshot/src/State.js, packages/jest-snapshot/src/index.js, packages/jest-snapshot/src/plugins.js, website/i18n/en.json
This PR introduces a new snapshot testing concept I'm calling "property matchers" (feedback on naming welcome)
Closes https://github.com/facebook/jest/issues/5847
You can now pass an object with asymmetric matchers into `toMatchSnapshot` which are then written to the snapshot instead of the original values:
These matchers are checked _before_ the snapshot is written or checked:
Note: it's weird that there is a note to re-run with `-u` to update, which will not update the snapshot since it's not the written value that fails. Recommend following up with a change to the reporter logic.
Also note: a diff would be a nice followup
- Added integration tests
- No existing tests changed
=> Add snapshot property matchers

README.md
As of Jest 23 we can officially label Jest blazing
=> Add blazing badge

.flowconfig, package.json, packages/jest-circus/src/__mocks__/test_event_handler.js, packages/jest-circus/src/__mocks__/test_utils.js, packages/jest-circus/src/__tests__/after_all-test.js, packages/jest-circus/src/__tests__/base_test-test.js, packages/jest-circus/src/__tests__/circus_it_test_error.test.js, packages/jest-circus/src/__tests__/hooks.test.js, packages/jest-circus/src/event_handler.js, packages/jest-circus/src/format_node_assert_errors.js, packages/jest-circus/src/index.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter.js, packages/jest-circus/src/run.js, packages/jest-circus/src/state.js, packages/jest-circus/src/utils.js, yarn.lock
update flow, add `strict` mode and make `jest-circus` use `@flow strict-local`
flow strict caught a problem with importing `expect`, turns out it wasn't typed and was imported as `any`.
how do other modules get types? e.g. `import {...} from `jest-snapshot` in the same file had proper types
=> update flow && add flow strict

integration-tests/__tests__/__snapshots__/test_name_pattern.test.js.snap, integration-tests/testNamePattern/__tests__/test_name_pattern.test.js, packages/jest-circus/src/event_handler.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init.js, packages/jest-circus/src/run.js, packages/jest-circus/src/state.js, types/Circus.js
stacked on top of `flow-strict` commit
fixes the support for `--testNamePattern` in `jest-circus`
=> Test name pattern

integration-tests/__tests__/snapshot.test.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter.js
new snapshot summary that wasn't included in `jest-circus`
=> [jest-circus] snapshot support

integration-tests/__tests__/timeouts.test.js, integration-tests/__tests__/unexpected-token.test.js, packages/jest-runtime/src/helpers.js, packages/jest-runtime/src/script_transformer.js
We had _a lot_ of issues with "unexpected token" errors. Time to actually throw something more descriptive :)
Attaching a screenshot (the part above `/Users/...` is added with this PR):
Pretty please check the language if we can make the message easier to comprehend 🙏 
Integration test
=> Add descriptive message for 'unexpected token' errors

integration-tests/__tests__/lifecycles.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init.js, packages/jest-circus/src/run.js, packages/jest-circus/src/utils.js, types/Circus.js
this adds a concept of `unhandledErrors`
any unhandled error is treated as `testExecError` and fails the test (even though all test could be passing)
afterEach hook's logic is pretty bizarre in Jasmine (it reports 0 test passed even if all tests succeeded) 
with this implementation it'll report tests normally, but fail the whole suite at the end.
Error formatting logic is a bit weird because of Jasmin error format, but it all lives under `legacy` code dir and we'll rewrite it after `jest-circus` ships
=> [jest-circus] lifecycle (after All errors)

integration-tests/__tests__/__snapshots__/globals.test.js.snap, integration-tests/__tests__/globals.test.js, packages/jest-circus/package.json, packages/jest-circus/src/event_handler.js, packages/jest-circus/src/utils.js, packages/jest-jasmine2/src/jasmine/Suite.js, packages/jest-util/src/convert_descriptor_to_string.js, packages/jest-util/src/index.js
Part of #4362
Globals are green
=> jest-circus: support globals

integration-tests/__tests__/__snapshots__/failures.test.js.snap, integration-tests/__tests__/failures.test.js, packages/jest-circus/package.json, packages/jest-circus/src/event_handler.js, packages/jest-circus/src/format_node_assert_errors.js, packages/jest-circus/src/index.js, packages/jest-circus/src/utils.js, packages/jest-jasmine2/src/assert_support.js, types/Circus.js
A first pass at making jest-circus support the same async stack traces that jest-jasmine does. I'm not totally happy with the implementation, so happy to take feedback.
See #4362 for instructions on how to run with circus.
Note that jest-circus will still fail the test because of #6277, but all other tests are green
/cc @captbaritone I'm not allowed to assign you
=> Add async stack traces for circus

integration-tests/__tests__/each.test.js, packages/jest-runner/src/run_test.js, scripts/SkipOnJestCircus.js
Relates to #4362
You can now run our test with: `JEST_CIRCUS=1 ./jest` and it will use Jest circus.
This will:
1. Make it easy to run a test locally with Jest Circus
2. Enable us to flag individual tests as known to be failing on Jest
Circus.
3. Make it easy to run Jest Circus on other code bases.
4. Once 2 is complete, we can setup a second CI run that uses Jest
Circus to ensure we don't regress.
@aaronabramov
=> Run with Jest Circus when passing the JEST_CIRCUS env variable as 1

packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init.js, packages/jest-circus/src/run.js, packages/jest-circus/src/utils.js
That's not a scalable solution, but that's what we're doing now.
We should create a lint rule that looks for usage of global, overridable variables (e.g. `Promise`, `setTimeout`) and warns if you're using them from `global` object prompting to capture the original values in the closure
=> [jest-circus] override-globals

flow-typed/co.js, flow-typed/is-generator-fn.js
they are used in jasmine (currently type of `any`)and i'm going to use them in `jest-circus` as well
=> [jest-circus] add types for generator packages

integration-tests/__tests__/location_in_results.test.js, packages/jest-circus/package.json, packages/jest-circus/src/event_handler.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init.js, packages/jest-circus/src/run.js, packages/jest-circus/src/state.js, packages/jest-circus/src/utils.js, scripts/SkipOnJestCircus.js, types/Circus.js
Part of #4362 
@SimenB 
@aaronabramov importing `stack-utils` in `packages/jest-circus/src/utils.js` breaks flow-strict. Thoughts?
=> Add `testLocationInResults` support to jest-circus

CHANGELOG.md, flow-typed/npm/jest_v21.x.x.js, packages/pretty-format/src/__tests__/asymmetric_matcher.test.js, packages/pretty-format/src/plugins/asymmetric_matcher.js
=> fix: handle inverse asymmetric matchers correctly

integration-tests/__tests__/__snapshots__/failures.test.js.snap, integration-tests/__tests__/failures.test.js, integration-tests/failures/__tests__/async_failures.test.js, packages/jest-circus/src/utils.js
By not providing a new error, some later code will make sure to append the stack from `asyncError`.
We should probably still fix #6277, fwiw, but this allows us to enable the failures test.
Green CI.
=> [jest-circus] fix stack frame for test timeout

CHANGELOG.md, integration-tests/__tests__/__snapshots__/each.test.js.snap, packages/jest-each/package.json, packages/jest-each/src/bind.js, packages/jest-each/src/index.js, packages/jest-jasmine2/package.json, packages/jest-jasmine2/src/each.js
Move `jest-jasemine2` each code to `jest-each` and make `jest-jasmine2` depend on `jest-each`
All the existing tests should still be passing
=> Move jest-jasemine2 each code to jest-each

packages/jest-circus/runner.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter.js, packages/jest-runner/src/run_test.js
This will make it easier to use jest-circus using the regular runner config.
@aaronabramov
=> Make the jest-circus export compatible with regular runners

CHANGELOG.md, packages/expect/src/__tests__/utils.test.js, packages/expect/src/utils.js
This fixes the issue brought up in #6235 
```
test.only("foo", () => {
expect({ foo: null }).toMatchObject({ foo: { bar: "baz" } });
});
```
This code above gives a TypeError as opposed to a nice assertion error.
Added a few tests for the subsetEqulity function.
I've signed the CLA.
=> toMatchObject throws TypeError when a source property is null

CHANGELOG.md, e2e/__tests__/haste_map_sha1.test.js, packages/jest-haste-map/src/__tests__/worker.test.js, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/worker.js
Although Jest itself does not use SHA-1s yet, this part of the code is used by https://github.com/facebook/metro, where provided SHA-1s are used to compute cache keys.
When using `watchman` as a crawler, everything works well, but when using the Node crawler, Metro breaks on the first `node_modules` file it finds. This is because the Node crawler does not compute SHA-1s, and leaves this duty to the worker. Because `node_modules` are not processed to extract dependencies, their SHA-1 was never computed and Metro crashed.
This diff introduces a new, lightweight method in `worker.js`, which sole mission is to compute the SHA-1. It is called instead of `worker` when the file will be dropped from heavy processing, and only when SHA-1s are requested.
_Note: all tests pass, but I haven't tested …
=> Make jest-haste-map compute SHA-1s for excluded files too

CHANGELOG.md, e2e/__tests__/__snapshots__/each.test.js.snap, e2e/each/__tests__/failure.test.js, e2e/each/__tests__/success.test.js, packages/jest-each/src/__tests__/array.test.js, packages/jest-each/src/bind.js
Fixes https://github.com/facebook/jest/issues/6348
- Add unit test
- Add e2e tests
=> [jest-each] Feature: handle 1d array

docs/ExpectAPI.md
Minor bug for `nthCalledWith` shortcut function.
=> Documentation: nthCalledWith() minor bug

packages/jest-runner/src/run_test.js
Looks like we don't need this code anymore? cc @cpojer 
Stacked on https://github.com/facebook/jest/pull/6359 for greenness.
This change makes jest-circus consistently faster than jasmine by ~5% in my completely unscientific test runs.
🍏
=> Remove eagerly evaluated jasmine from jest-runner

docs/MockFunctions.md, website/versioned_docs/version-23.0/MockFunctions.md
```returnValues``` was replaced with ```results```. This updates the docs for the change.
Issue #6324 has more information about this change if needed.
https://github.com/facebook/jest/pull/6172/files#diff-3eb46e5efb818eec731c401704f180feR42 
Verify website docs display correctly.
=> Update docs to use results instead of returnValues for mock functions

e2e/__tests__/__snapshots__/error-on-deprecated.test.js.snap, e2e/__tests__/__snapshots__/timeouts_legacy.test.js.snap, e2e/__tests__/error-on-deprecated.test.js, e2e/__tests__/timeouts_legacy.test.js, e2e/error-on-deprecated/__tests__/DEFAULT_TIMEOUT_INTERVAL.test.js, packages/jest-jasmine2/src/error_on_private.js, packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/jasmine/Env.js, packages/jest-jasmine2/src/jasmine/jasmine_light.js, packages/jest-runtime/src/index.js
Followup from https://github.com/facebook/jest/pull/6339.
I figured I'd split this out into a separate PR since it seems a little invasive just to give a nice deprecation error.
=> Allow --errorOnDeprecated to error on DEFAULT_TIMEOUT_INTERVAL

CHANGELOG.md, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/jasmine_utils.js
`toEqual` matcher could not handle _symbol_ based properties in _array_'s, causing jest to throw:
Minimal example:
```javascript
const mySymbol = Symbol("test");
const actual1 = [];
actual1[mySymbol] = 3;
const expected = [];
expected[mySymbol] = 3;
expect(actual1).toEqual(expected);
```
Throws:
```
TypeError: allKeys[x].match is not a function
at Object.test (packages/expect/src/__tests__/matchers.test.js:456:21)
```
The cause of this issue is this [line](https://github.com/facebook/jest/blob/241588a08edadbcaef7cc93bb11aad3b9cbad73b/packages/expect/src/jasmine_utils.js#L225) which assumes that all property names of arrays are strings and hence `.match` can be called on them. 
This assumption does not held for symbol based properties. If the property name is a symbol, it is never an …
=> Fix: Symbol based properties in arrays causes `toEqual` to throw

CHANGELOG.md, docs/GlobalAPI.md, packages/jest-each/README.md
Adds docs for https://github.com/facebook/jest/pull/6351
=> Add 1 dimensional array docs

docs/MongoDB.md
In the example file setup.js the variables `mongod` and `mongoFileConfigPath` are undefined. I think they are `mongoserver` and `globalConfigPath`.
none
=> Using Jest with MongoDB example - wrong variables

docs/Configuration.md
As requested in https://github.com/facebook/jest/issues/5974 I added to the docs a note to reflect the fact that the test files regex is tested against the absolute path. 
I actually opened this PR to understand how can I test changes in the docs. I would love to get such help.
=> add note in configuration docs

packages/jest-resolve/package.json
In earlier versions of `browser-resolve`, the sync behavior did not properly resolve module extensions due to a divergence between their sync and async implementations.  This was resolved in https://github.com/defunctzombie/node-browser-resolve/pull/90 which should align their sync/async behaviors and allow extensions to be resolved propery when using the `browser` flag.
All tests required were committed in the referenced pull request for `browser-resolve`.  This was a patch release to `browser-resolve`, so the caret range defined would have implicitly picked up this patch in the future on `yarn install`, we're just being explicit about wanting this fix.
=> Fix extensions not being respected when using '--browser' (#6005)

CONTRIBUTING.md
The CONTRIBUTING.md is currently lacking a command in the process of linking build version of jest. 
Yarn's link command should be run both in jest-cli folder and in the project as well. 
(Here is yarn's output while running `yarn link` inside jest-cli
Relevant lines in CONTRIBUTING.md after the change:
=> add explanation how to link build version

CHANGELOG.md, e2e/babel-plugin-jest-hoist/__test_modules__/f.js, e2e/babel-plugin-jest-hoist/__tests__/integration.test.js, packages/babel-plugin-jest-hoist/src/index.js
Fix facebook/react-native#19120
Fix #6504
[/e2e/babel-plugin-jest-hoist/\_\_tests\_\_/integration.test.js](https://github.com/facebook/jest/pull/6505/files#diff-77ef7c4590fe5646da3c7a75612fd1b1R64)
=> [babel-plugin-jest-hoist] Fix MockNativeMethods access in react-native

CHANGELOG.md, docs/Configuration.md, e2e/__tests__/global_setup.test.js, e2e/__tests__/global_teardown.test.js, e2e/global-setup/custom_tests_dir/pass.test.js, e2e/global-setup/setup-with-config.js, e2e/global-teardown/custom_tests_dir/pass.test.js, e2e/global-teardown/teardown-with-config.js, packages/jest-cli/src/run_jest.js
This PR fixes #5957.
`globalSetup` and `globalTeardown` functions will receive Jest's `globalConfig` object as a parameter.
Pass a specific parameter to the configuration, `console.log` it from the `globalSetup`/`globalTeardown` functions and verify it shows up in the stdout.
=> global setup and global teardown now gets globalConfig as a parameter

packages/jest-haste-map/src/worker.js
Ran into this failing because of a git branch named `package.json` and it was hard to debug. This adds the path to the error.
It makes #4839 easier to debug
I edited the code in-place in node_modules and here present the untested clean version 😬
=> jest-haste-map: improve JSON parse error

e2e/__tests__/no_test_found.test.js, packages/jest-cli/src/get_no_test_found.js
This file is untyped, but the `testRun.matches.length` value here comes from https://github.com/facebook/jest/blob/master/packages/jest-cli/src/search_source.js#L27 where it is optional, so we need to handle the case where the property is not present at all.
`testRun.matches` is actually a Frankenstein's Monster version of the `SearchResult` type, since it's had other properties grafted onto it along the way via `Object.assign` https://github.com/facebook/jest/blob/master/packages/jest-cli/src/run_jest.js#L72-L75
This makes actually typing this file rather difficult.
Looks like our use of `Object.assign` is making the types in this portion of the code base worthless in a number of different places. Are there any patterns which can help us avoid this?
=> Avoid NaN in 'no test found' message

packages/jest-cli/src/run_jest.js, types/Config.js
When we assign a variable to the result of `Object.assign({}, ...)` the
typing for that variable is lost. Therefore we were able to access
`globalConfig.coveragePathIgnorePatterns` even though it didn't exist in
the type.
Commenting these `Object.assign` cases revealed the missing type
property.
=> Adding missing attribute to GlobalConfig type

website/package.json, website/pages/en/index.js, website/siteConfig.js, yarn.lock
Docusuarus 1.3.0 brings about some backwards-incompatible CSS changes. So the team is helping the major users update 😄 
Thankfully Jest doesn't have much custom CSS, so there isn't too much to be done.
Changes made:
- Upgraded Docusaurus - CSS changes
- The landing page logo was invisible to the user because it was a white-outline logo on a white background. Changed it to the non-outline version.
- Changed the theme of the syntax highlighting to a "ocean". It has more contrast and looks better. Hopefully it's welcome. If not I'd be glad to revert it.
- Enabled in-page navigation in `siteConfig.js` for better user experience while browsing the docs.
Ran the site locally and visited every page.
=> Update Docusaurus to 1.3.0

packages/jest-runtime/src/__tests__/script_transformer.test.js, packages/jest-util/src/__tests__/get_callsite.test.js
Fixes https://github.com/facebook/jest/issues/6529
jest.mock('fn') does not seem to include fs.ReadStream or fs.WriteStream in the resulting mocked module. This updates the tests to specify them in the mock.
I'm assuming larger work is required in jest-mock to address this directly.
All tests pass locally on 10.5.x
=> Node 10.5.x compatibility on CI for tests

CHANGELOG.md, README.md, docs/SnapshotTesting.md, packages/jest-cli/package.json, packages/jest-runtime/src/index.js, packages/jest-util/src/__tests__/__snapshots__/fake_timers.test.js.snap, packages/jest-util/src/fake_timers.js, packages/jest/package.json, website/blog/2016-03-11-javascript-unit-testing-performance.md, website/blog/2016-07-27-jest-14.md, website/blog/2016-09-01-jest-15.md, website/blog/2016-10-03-jest-16.md, website/blog/2017-01-30-a-great-developer-experience.md, website/blog/2017-02-21-jest-19-immersive-watch-mode-test-platform-improvements.md, website/blog/2017-05-06-jest-20-delightful-testing-multi-project-runner.md, website/blog/2017-12-18-jest-22.md, website/blog/2018-05-29-jest-23-blazing-fast-delightful-testing.md, website/pages/en/index.js, website/siteConfig.js, website/static/img/favicon/browserconfig.xml, website/static/img/favicon/manifest.json, website/versioned_docs/version-22.0/MoreResources.md, website/versioned_docs/version-22.0/SnapshotTesting.md, website/versioned_docs/version-22.1/SnapshotTesting.md, website/versioned_docs/version-22.2/SnapshotTesting.md, website/versioned_docs/version-22.3/SnapshotTesting.md, website/versioned_docs/version-23.0/SnapshotTesting.md
This PR switches a few remaining items (like images and links) over to the new jestjs.io domain, and fixes the deploy to not break the CNAME file
=> Switch to jestjs.io

.eslintrc.js, website/fetchSuporters.js
By letting the fetchSupporters run on node 6
Fixes CI 🎉 
This PR should be green?
=> Use prettier ignore pragmas to un-break the CI build

packages/jest-editor-support/index.d.ts, packages/jest-editor-support/src/Process.js, packages/jest-editor-support/src/Runner.js, packages/jest-editor-support/src/Settings.js, packages/jest-editor-support/src/__tests__/runner.test.js, packages/jest-editor-support/src/__tests__/settings.test.js, packages/jest-editor-support/src/project_workspace.js, packages/jest-editor-support/src/types.js
This PR mainly to address jest 23.x compatibility and config parsing issues:
- jest-editor-support in 23.x no longer trigger test results processing due to #4858: [jest-community/vscode-jest/316](https://github.com/jest-community/vscode-jest/issues/316) 
- Setting parser failed to extract jest settings sometimes, such as in CRA env: [jest-community/vscode-jest/337](https://github.com/jest-community/vscode-jest/issues/337)
plus some clean up and self-diagnosis:
- update the typescript typings
- added a debug flag in workspace
- added new unit tests
- test vscode-jest:
- with jest 23.x repo, as well as non 23.x (backward compatible)
- with CRA js/ts repo to make sure settings are extracted properly.
---
would also like to request @orta, @seanpoulter or @stephtr to review this PR.
=> [jest-editor-support]: jest 23.x compatibility

.circleci/config.yml
Current CircleCI integration is such that it will install docusaurus, generate english file for strings & then install jre -> install crowdin -> upload crowdin docs -> download crowdin docs -> try to deploy website regardless whether it is a pull request or not.
I think it is much better to skip deploying the website if it is just a pull request & only deploy when it has been pushed to master.
Another change is addition of large resource class for website deploy based on https://github.com/facebook/jest/issues/6567#issuecomment-401694249
Look at circleci jobs of test-deploy-website for this PR.
=> Skip deploy website if it is a pull request

docs/CLI.md
Update CLI docs to include `--reporters` CLI argument documentation (and limitations).
Just a documentation update. No testing.
=> Add reporter documentation to CLI docs

CHANGELOG.md, packages/jest-cli/src/__tests__/snapshot_interactive_mode.test.js, packages/jest-cli/src/plugins/update_snapshots_interactive.js, types/TestResult.js
This fixes a regression with interactive snapshot mode where it would fail to find any tests to run in the file. Problem here is it was using the test title with regex pattern to say match the title exactly. But `testNamePattern` also includes any `describe` blocks in the title, so we need to include that as well.
I switched from using the test `title` to `fullName` and it appears to be working as expected now. Since @rickhanlonii, you did the improvements recently, I'd love some feedback from you on this and if it is the correct way to solve it. Also if there is some end to end test that could be done to ensure this is working as intended.
This fix should resolve #6485 and #6431.
All tests pass.
=> Fix `testNamePattern` value with interactive snapshots

CHANGELOG.md, docs/WatchPlugins.md, packages/jest-cli/src/__tests__/__snapshots__/watch.test.js.snap, packages/jest-cli/src/__tests__/watch.test.js, packages/jest-cli/src/watch.js, packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js, types/Config.js, website/versioned_docs/version-23.0/WatchPlugins.md
This should make it enable plugins to customize their `keys` and also allow for custom behavior within plugins, for example, the usage of `globs` in `jest-watch-typeahead`
```
"watchPlugins": [
[
"jest-watch-typeahead/filename",
{
"key": "g",
"prompt": "to filter with a glob",
"strategy": "glob"
}
],
[
"jest-watch-typeahead/filename",
{
"key": "k",
"prompt": "to have a custom prompt"
}
]
],
```
Relates to https://github.com/jest-community/jest-watch-typeahead/issues/9 and https://github.com/jest-community/jest-watch-typeahead/issues/10
I'm not sure if something else needs to be updated in the config parsing. cc: @thymikee
=> Allow watch plugin to be configured

.circleci/config.yml, website/pages/en/index.js
This is successor of #6590. 
Changes:
1. CircleCI will try to build jest website when it is a *PULL REQUEST* instead of just skipping it. This is to ensure that there is nothing wrong with building the website
2. Use a safe getter function (inspired from Facebook idx function to access deeply nested values of an object)
Notice this
```js
translation[this.props.language]['localized-strings'].tagline
```
This can cause build error which will return an unhandled promise. Currently jest use Docusaurus 1.3.0 which doesn't give non zero exit code when there is a build error. This is fixed in Docusaurus >= 1.3.1
Current local `yarn build` has an unhandled promise (build error)
Current website deploy has an unhandled promise (build error)
https://circleci.com/gh/facebook/jest/27857
1. Ensure that …
=> Test Jest website build for every PR

CHANGELOG.md, docs/Configuration.md
The documentation at the moment describes the behavior of Jest when `resetModules` is set to `true`, but leaves the default/false case unclarified. I had a misconception that the module registry would not be reset at all in the false case, where it's still reset between different test files. This misconception was clarified by SimienB in issue #6007.
The reporter of issue #4413 also had this question.
This commit updates the documentation of `resetModules` to explain the default case more explicitly.
=> Update docs to detail resetModules: false behavior

packages/expect/src/matchers.js
`toBe` expected argument should be `any`.
=> Fix toBe incorrect expected type (#6551)

website/package.json, website/siteConfig.js, yarn.lock
1. Update Docusaurus to 1.3.2 based on https://github.com/facebook/jest/issues/6640#issuecomment-402938248. This version has few bug fixes which is important imho. In additions:
- Being able to easily debug commit that cause 404 / broken build in gh-pages branch
Consider this commit https://github.com/endiliey/endiliey.github.io/commit/4c6abe0786e2be11cda2ae7c8d847e957d6ba89d
Now the deploy commit on `gh-pages` shows the correct triggering commit
https://github.com/endiliey/endiliey.github.io/commit/936bbc3e2fa8d647aa824e138d52f7b8fbf17b2e
Make debugging life easier 👍 
- Search docs depending on current version of docs
(refer to test plan below)
2. Expose algolia api key for easy debugging
cc @yangshun @JoelMarcey 
1. Static website build works without non-zero exit code
```
cd website …
```
=> Update Docusaurus to 1.3.2

CHANGELOG.md, packages/jest-cli/src/test_scheduler.js
When using the `watch` mode, we use the TTY as an input mechanism (for keystrokes), so that different options can be selected. When only one test is selected, it will run by default in band, which causes the TTY to be unresponsive.
Blacklisting "in band" mode when using the `watch` mode fixes the issue, since tests are executed in workers, freeing the main process.
Fixes #6599.
=> Always use workers when using the watch mode

CHANGELOG.md, e2e/__tests__/__snapshots__/module_name_mapper.test.js.snap, packages/jest-cli/src/watch.js, packages/jest-resolve-dependencies/src/index.js, packages/jest-resolve/src/index.js
We've reprinted only `error.stack` while being in watch mode, which caused "Could not locate module" errors to vanish, because they had their stack cleared (for reasons known to me at the time of writing, which are not relevant now).
Also improved the resolver error message just a bit.
Fixes #4524
No time for tests because I'm heading off on vacation 😎🌴, but hey, I have screenshots!
Before:
After (watch mode resolver errors now shine as never before):
To get rid of this extra "Error: " I'd need to only print `error.message` which I think is safer not to do, as proven by `error.stack` version, but maybe I worry to much (just no time for thorough testing).
The regular run is unaffected:
=> fix: properly reprint resolver errors in watch mode

packages/jest-snapshot/src/State.js
This PR fixes a typo when adding an inline snapshot `Couln't` -> `Couldn't`
Just a typo fix
=> Fix typo when adding inline snapshot

CHANGELOG.md, e2e/__tests__/__snapshots__/test_name_pattern_skipped.test.js.snap, e2e/__tests__/test_name_pattern_skipped.test.js, e2e/testNamePattern_skipped/__tests__/test_name_pattern_skipped.test.js, e2e/testNamePattern_skipped/package.json, packages/jest-jasmine2/src/tree_processor.js
Fix a regression on jest-jasmine for non marching test suites.
https://github.com/facebook/jest/issues/6415
https://github.com/Crispioso/possible-jest-bug
=> Fix regression on non-matching suites (#6415)

docs/BypassingModuleMocks.md, website/sidebars.json
First – thanks so much for this project, I've been using Jest for a couple of years and have benefited from it a lot!
I've been in the situation a few times where I've had a problem that could be solved by `require.requireActual` but didn't know about it because it seems to be quite hidden away in the docs (as far as I could tell, it's only really documented in the "Globals" section of the API reference). As a result of not knowing about it, I've wasted quite a lot of hours writing my own manual mocks rather than using Jest's automocking features. This PR adds a section to the docs entitled "Bypassing module mocks" which presents an issue similar to one I encountered recently, and talks the reader through how `require.requireActual` can solve the problem.
Let me know what you think. I've …
=> Add docs section to highlight jest.requireActual

website/siteConfig.js
Reduce duplication of Algolia API Key by referencing env variable within siteConfig. Follow up of https://github.com/facebook/jest/pull/6644#issuecomment-403763538.
Netlify test at https://deploy-preview-6666--jest-preview.netlify.com/. Seems to be working as I can search in the preview.
cc @endiliey
=> Use process.env.ALGOLIA_JEST_API_KEY within siteConfig instead

CHANGELOG.md, e2e/__tests__/__snapshots__/module_name_mapper.test.js.snap, e2e/__tests__/resolve-get-paths.test.js, e2e/__tests__/resolve-with-paths.test.js, e2e/resolve-get-paths/__tests__/resolve-get-paths.test.js, e2e/resolve-get-paths/package.json, e2e/resolve-with-paths/__tests__/resolve-with-paths.test.js, e2e/resolve-with-paths/dir/mod.js, e2e/resolve-with-paths/package.json, packages/jest-resolve/src/__tests__/resolve.test.js, packages/jest-resolve/src/index.js, packages/jest-runtime/src/index.js, types/Resolve.js
Implement `require.resolve` with `options.paths`
and implement `require.resolve.paths`.
Closes #6206 
e2e tests added
jest-resolve unit test for `resolveModule` paths override added
=> require.resolve with options.paths + require.resolve.paths

CHANGELOG.md, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/__tests__/worker.test.js, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/types.js, packages/jest-haste-map/src/worker.js
Metro also uses `jest-haste-map`, but there is no need to extract dependencies from it, since Metro has its own algorithms. This PR implements a boolean flag that avoids reading from the filesystem when we do not want to extract dependencies. The default is kept to `true` so it's backwards compatible.
I also added specific tests for non-UTF-8 files, and for non-computed dependencies too. The argument is made mandatory at the worker level.
=> Avoid reading files from Haste map if not needed

packages/jest-circus/src/__tests__/__snapshots__/hooks.test.js.snap, packages/jest-circus/src/__tests__/hooks.test.js, packages/jest-circus/src/utils.js
found a nasty bug where this test:
```js
beforeEach(() => console.log(1));
beforeEach(() => console.log(2));
test('test', () => console.log('test'));
```
would print:
```
2
1
test
```
=> fix beforeEach hook execution order

packages/jest-circus/src/__tests__/__snapshots__/after_all.test.js.snap, packages/jest-circus/src/__tests__/__snapshots__/hooks.test.js.snap, packages/jest-circus/src/__tests__/after_all.test.js, packages/jest-circus/src/__tests__/hooks.test.js, packages/jest-circus/src/utils.js
hm... i don't even know how be broke it, but apparently we did :)
`beforeAll` hooks weren't executing at all if there's no other tests in the immediate describe block.
=> fix beforeAll hooks in jest-circus

packages/jest-cli/src/__tests__/watch.test.js
A test inside #6473 was unfortunately incorrect and "passed by mistake". This was due to the TTS or an `it.each` call not using interpolation on dynamic scenario variables, mostly.  This fixes it.
Additionally, in the meantime an extra call to `updateGlobalConfig` had been added to each watch test run, making the original test obsolete in its mock calls inspection. Updated.
Well, the tests keep passing, only this time they're correct 😉 so they're actually exercising the scenarios.
Ping @rogeliog @thymikee @SimenB for review.
Refs #6693
=> Fix tests for recent broader-options watch plugins PR

docs/ExpectAPI.md
Documentation refers to `expect.extends`, rather than `expect.extend`.
There is no `.extends` method for `expect`, so this avoids confusion for documentation consumers.
No UI changes.  Strictly a doc edit.
=> Fix typo in ExpectAPI.md

CHANGELOG.md, packages/babel-jest/src/index.js
Previously the options passed to `createTransformer()` were not taken into account when generating the cache key, causing incorrect cache hits when the options had changed.
Fixes #6698.
I've repeated the STR from #6698 in a locally linked copy of Jest, and it no longer reproduces. I did not add a test, since there are no existing tests for `getCacheKey()`.
=> Include createTransformer options in babel-jest's getCacheKey()

CHANGELOG.md, e2e/Utils.js, e2e/__tests__/dependency_clash.test.js, packages/jest-circus/package.json, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init.js, packages/jest-jasmine2/package.json, packages/jest-jasmine2/src/setup_jest_globals.js, packages/jest-snapshot/package.json, packages/jest-snapshot/src/State.js, packages/jest-snapshot/src/__tests__/inline_snapshots.test.js, packages/jest-snapshot/src/inline_snapshots.js
to fix the bug i moved `prettier` and `babel-traverse` outside of node VM, so it is only required once per worker (and not in each individual test).
by doing this we'll also avoid taking the source code of our these dependencies through our resolution/transformation pipeline, which solves the issue of conflicting module names (since babel is no longer required from within the test code any more)
old description:
>It seems like a pretty serious bug, i don't have a fix yet, but i'm submitting the repro in case anyone >knows what's the best way to approach it.
>
>TL;DR:
>- we use `@providesModule` system at fb that let's us require files directly by their names (e.g. >`require('myModule111')` that'll resolve to `some/dir/myModule111.js`)
>- npm can import dependencies that have similar names …
=> fix dependency name clash bug

CHANGELOG.md, README.md
Currently the link in the contributors image points to: https://github.com/facebook/jest/blob/master/graphs/contributors which is a 404.
This PR updates the link to be absolute and points it to https://github.com/facebook/jest/graphs/contributors
=> Fix broken contributors graph link

CHANGELOG.md, e2e/__tests__/jest_changed_files.test.js, packages/jest-changed-files/src/git.js, packages/jest-changed-files/src/hg.js, packages/jest-changed-files/src/index.js, types/ChangedFiles.js
Given a monorepo setup under git version control, we saw `jest --watch` commands take significantly longer in a Docker container host mount (`rw:cached`) than when on the host directly. Tracked the issue down to the fact that `git` and `hg` command used to determine `lastCommit` changes were traversing the entire repository, and not just paths specified in the Jest config `roots` values. Given the mounted container latency, things like basic `lstat` gathering be intensive in a large repository. The `roots` we had specified are rather shallow themselves and only contain things we want to test with Jest. When limiting the scope of the `git` command to just the `roots` paths, we saw change determination drop from 2.5m to 3s in our container.
This implementation seem to align more closely …
=> perf(changed-files): limit git and hg commands to specified roots

docs/CLI.md
Noting that `--coverage` maps to `--collectCoverage` in docs since the latter is not listed anywhere.
None necessary.
=> docs: noted --coverage aliased by --collectCoverage

packages/babel-jest/README.md
I got an error when I tried to use following command from readme:  
```yarn add --dev babel-jest babel-core@^7.0.0-0 @babel/core```
 It should be similar with command from getting the start page (https://jestjs.io/docs/en/getting-started), `babel-core@^7.0.0-0` in single quotes
```yarn add --dev babel-jest 'babel-core@^7.0.0-0' @babel/core```
=> packages/babel-jest - fix readme

CHANGELOG.md, docs/ExpectAPI.md, website/versioned_docs/version-23.3/ExpectAPI.md
Found an error in the docs for `expect.objectContaining(object)` describing what properties are matched by the method. The previous sentence seem to have been copy/pasted from `expect.not.objectContaining(object)`.
=> Docs/ExpectAPI: Correct docs for `objectContaining`

CHANGELOG.md, e2e/__tests__/test_retries.test.js, e2e/test-retries/__tests__/e2e.test.js, packages/jest-circus/src/__mocks__/test_event_handler.js, packages/jest-circus/src/event_handler.js, packages/jest-circus/src/run.js, types/Circus.js
Fixes https://github.com/facebook/jest/issues/6727
retryTimes initial implementation did not actually fully retry a test on failure due to logic in jest-circus which would not run a test if previous errors occurred. This PR updates that logic to handle test retries and adds a new e2e regression test that tests more than the reporter API (invocations).
Adds an e2e test inspired heavily by the referenced issue above.
=> Fix retryTimes and add e2e regression test

CHANGELOG.md, e2e/__tests__/to_match_inline_snapshot.test.js, packages/jest-jasmine2/src/setup_jest_globals.js
This PR fixes https://github.com/facebook/jest/issues/6702 by seizing to local require prettier in jest-jasmine2. Instead `require(config.prettierPath)` is used. This prevents the issue where mocking native modules like `path` and `fs` that prettier depends on would cause `toMatchInlineSnapshot` to fail.
Run the new unit test introduced in this PR.
=> fix: `matchInlineSnapshot` when prettier dependencies are mocked

CHANGELOG.md, e2e/__tests__/__snapshots__/show_config.test.js.snap, packages/jest-cli/src/lib/__tests__/__snapshots__/init.test.js.snap, packages/jest-config/src/defaults.js, packages/jest-config/src/valid_config.js, packages/jest-validate/src/__tests__/fixtures/jest_config.js
Updates jests default value for testURL from 'about:blank' to 'http://localhost'.
This ensures that JSDOM doesn't throw a security error for tests using the jsdom environment.
Should fix https://github.com/facebook/jest/issues/6766
All tests pass
cc @thymikee @SimenB
=> Update testURL default value from about:blank to localhost

CHANGELOG.md, e2e/__tests__/__snapshots__/find_related_files.test.js.snap, e2e/__tests__/find_related_files.test.js, packages/jest-config/package.json, packages/jest-config/src/normalize.js
Fixes #6462 by adding a check to the `collectCoverage` + `findRelatedTests` normalization.
If there's `collectCoverageFrom` patterns defined in the config it'll reduce (map + filter) to ensure that the generated patterns do not override existing patterns.
It is also no longer overwritten, existing patterns are merged with the dynamic ones.
Expand upon the existing `--findRelatedTests` to cover the specific edge cases related to `collectCoverageFrom` patterns.
=> Fix --coverage with --findRelatedTests overwriting collectCoverageFrom options

docs/ExpectAPI.md, docs/SnapshotTesting.md
Docs are updated to clarify the use of literal values when used as property matchers, as opposed to just asymmetric matchers. The actual behaviour is to check and pass any value as it is but the docs weren't clear about that.
Closes #6774.
=> [Docs] Clarified the use of literal values as property matchers in toMatchSnapshot()

CHANGELOG.md, e2e/__tests__/__snapshots__/to_match_inline_snapshot.test.js.snap, e2e/__tests__/to_match_inline_snapshot.test.js, packages/jest-snapshot/src/State.js
Currently when a snapshot is migrated from `toMatchSnapshot` to `toMatchInlineSnapshot`, the external snapshot becomes orphaned and there is no way to remove it (other than manually editing/deleting the file).
This change marks the migrated snapshot as obsolete, thus it can be deleted with `--updateSnapshot`.
```
Snapshots:   1 obsolete, 1 written, 1 total
```
Added an E2E test that writes an external snapshot, changes the code to `toMatchInlineSnapshot`, then runs Jest without `-u` to verify the snapshot is marked as obsolete, then with `-u` to verify the snapshot is removed.
Fixes #6655
=> Mark snapshots as obsolete when moved to an inline snapshot

CHANGELOG.md, e2e/__tests__/__snapshots__/process_exit.test.js.snap, e2e/__tests__/process_exit.test.js, e2e/process-exit/__tests__/test.js, e2e/process-exit/package.json, packages/jest-runner/src/run_test.js
Currently jest just exits without any helpful info if `process.exit` is invoked from user-code.
See the following test file:
```js
process.exit(1);
test('some test', async () => {
await new Promise(resolve => setTimeout(resolve, 500));
})
```
It currently looks like this:
With the changes in this PR it looks like this:
I wanted to stick it along with the fake `process.send` from #5904, but to format the error I need `config`, and passing that through felt like meh. Can move it there, though?
Integration test added
=> print stack trace on calls to process.exit

e2e/__tests__/__snapshots__/to_match_inline_snapshot.test.js.snap, e2e/__tests__/to_match_inline_snapshot.test.js, packages/jest-snapshot/src/__tests__/inline_snapshots.test.js
An issue with inline snapshots was raised in #6744, while I could not reproduce it, I did write test cases which could prevent regressions. Feel free to merge or decline 😄
=> [Inline Snapshots] Add test cases for #6744

docs/WatchPlugins.md
Just a typo fix: Remove a duplicated ')' on Documentation of WatchPlugin.
No test
=> Typo fix: Remove a duplicated ')'

CHANGELOG.md, packages/jest-cli/src/__tests__/__snapshots__/notify_reporter.test.js.snap, packages/jest-cli/src/__tests__/notify_reporter.test.js, packages/jest-cli/src/reporters/notify_reporter.js
This change adds package name to notification in NotifyReporter when using `--notify` flag or `notify` configuration option. This clarifies which package is being tested which is especially useful when watching tests in mono-repos and with multiple IDEs opened.
First I'm trying to get hasteFS from the first context to get the module name (must be a better way). Then I'm falling back to `rootDir` and otherwise to original behavior without an additional title. 
Before:
After:
=> Add package name to NotifyReporter notification

packages/jest-cli/src/lib/__tests__/init.test.js
Following to @SimenB's [advice](https://github.com/facebook/jest/pull/6442#issuecomment-399333786), mock `console.log` in `init` tests to reduce noise. 
All tests pass (without nonessential logs)
=> mock console.log to reduce noise from the tests

docs/Configuration.md
Due to breaking changes in an upgrade of the dependency micromatch
from ^2.3.11 to ^3.1.10 many users saw their coverage reporting
failing because their glob matching was in an unsupported format.
Adding the help text here gives users a good starting point for
debugging when they run into issues related to this option. This will
help alleviate support issues (such as #6563) concerning this configuration
option.
Give users a hint as to what could be causing an unexpected summary output when running coverage reporting with Jest. 
This lowers the barrier to troubleshooting this configuration issue since it points to what I would consider the most likely cause of the unexpected output when using this configuration option (an unsupported or malformed glob). Jest doesn't raise any errors in …
=> Add help for configuration of collectCoverageFrom

CHANGELOG.md, e2e/__tests__/__snapshots__/detect_open_handles.js.snap, e2e/__tests__/detect_open_handles.js, e2e/detect-open-handles/__tests__/inside.js, package.json, packages/jest-circus/src/run.js, packages/jest-circus/src/utils.js, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/collectHandles.js, packages/jest-jasmine2/src/jasmine_async.js
@thymikee found this one before the tweet storm yesterday 😅
Added test
=> fix: handle open handles from inside tests

docs/ExpectAPI.md
This docs don't cover this because it is assumed dot notation is for nested properties.
=> Add dot containing keys example to .toHaveProperty docs

CHANGELOG.md, docs/JestObjectAPI.md, website/versioned_docs/version-22.0/JestObjectAPI.md, website/versioned_docs/version-22.1/JestObjectAPI.md, website/versioned_docs/version-22.2/JestObjectAPI.md, website/versioned_docs/version-22.3/JestObjectAPI.md, website/versioned_docs/version-22.4/JestObjectAPI.md, website/versioned_docs/version-23.0/JestObjectAPI.md, website/versioned_docs/version-23.1/JestObjectAPI.md, website/versioned_docs/version-23.2/JestObjectAPI.md, website/versioned_docs/version-23.3/JestObjectAPI.md
Improve documentation of `jest.setTimeout` (so that consumers use it correctly, e.g. see #6557).
None (documentation only).
=> [doc] add note explaining when `jest.setTimeout` should be called

CHANGELOG.md, website/versioned_docs/version-22.0/TutorialReact.md, website/versioned_docs/version-22.1/TutorialReact.md, website/versioned_docs/version-22.2/TutorialReact.md, website/versioned_docs/version-22.3/TutorialReact.md, website/versioned_docs/version-22.4/TutorialReact.md, website/versioned_docs/version-23.0/TutorialReact.md
Fixed bug in example code: mutated the previous state without the use of a callback in _setState_
=> [Docs] Fixed bug in example code

docs/Puppeteer.md
Add variable timeout example to more understand.
=> Add Variable Timeout

CHANGELOG.md, docs/ExpectAPI.md
Add docs for how to write custom matchers that use snapshot testing, following up from this: https://github.com/facebook/jest/issues/6144#issuecomment-391702983
/cc @thymikee
=> [docs]: Add custom toMatchSnapshot matcher docs

CHANGELOG.md, packages/jest-circus/src/index.js, packages/jest-each/src/__tests__/array.test.js, packages/jest-each/src/__tests__/template.test.js, packages/jest-each/src/bind.js, packages/jest-each/src/index.js, packages/jest-jasmine2/src/each.js
Currently `jest-each` assumes if a test callback has more arguments than supplied in the data (array/template) then the extra argument is a `done` callback. This logic should not apply for `describe` blocks as they do not support `done` callbacks (or any args for that matter).
Fixes: #6838 
Updated unit tests to check `describe` blocks aren't invoked with `done`
=> [jest-each]: Add flag to prevent done callback being supplied to describe

CHANGELOG.md, docs/Configuration.md
Following the issue at #6538.
This PR improves the documentation regarding preset configuration.
=> improve preset documentation

CHANGELOG.md, packages/jest-config/src/__tests__/__snapshots__/normalize.test.js.snap, packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js
After the discussion on #6538
This PR adds a descriptive error message for a case when preset module exists but doesn't have `jest-preset.js` or `jest-preset.json` files at the root
Add a test case for it in `normalize.test.js`
=> improve "preset not found" error message

docs/MockFunctions.md
This PR fixes an issue with the current documentation: https://jestjs.io/docs/en/mock-functions#using-a-mock-function
I think the reader may be confused by the example in the section "Using a mock function".
Consider these few lines taken from the example:
```js
const mockCallback = jest.fn();
forEach([0, 1], mockCallback);
// ... snip ...
// The return value of the first call to the function was 42
expect(mockCallback.mock.results[0].value).toBe(42);
```
The last assertion is actually going to fail: we didn't provide an implementation for our mock. The return value is `undefined`.
With this PR, I configured the mock with a custom implementation `x => 42 + x` so that the assertion will pass.
Another solution would be to remove the last assertion entirely from the example. This is …
=> [docs] Fix MockFunctions: implementation is not provided

CHANGELOG.md, docs/CLI.md
Several of us have been bitten by `--projects` doing something different than expected, so this PR adds clarification to the docs.
As requested by @SimenB in #5595 with a smiley, which made all the difference.
=> [DOCS] Clarify --projects CLI option

README.md
Fixes #6891
Added Codecov badge as discussed in #6891 so that it's easy for new contributors to find latest code coverage for Jest
=> Added Codecov badge next to CI badges

.vscode/extensions.json
adamvoss.yaml is unpublished from Marketplace
https://marketplace.visualstudio.com/items?itemName=adamvoss.yaml
The one by Redhat is most popular (with 1.6M installs)
https://marketplace.visualstudio.com/search?term=YAML&target=VSCode
VSCode shows the following error with adamvoss.yaml recommendation:
=> Replace YAML extension of adamvoss with redhat

CHANGELOG.md, docs/ExpectAPI.md, packages/expect/src/__tests__/__snapshots__/extend.test.js.snap, packages/expect/src/__tests__/extend.test.js, packages/expect/src/jest_matchers_object.js
Refs #5503
`expect.extend` allows users to add their own custom matchers, with an asymmetric equivalent being made at the same time. Variadic Matchers are supported, but not variadic asymmetric matchers. This PR hopes to help move us closer to supporting that.
This enables community matchers such as those in [expect-more-jest](https://github.com/JamieMason/expect-more/tree/master/packages/expect-more-jest/#expect-more-jest).
I have updated the existing tests created in #5503 to be an example of a variadic asymmetric matcher, checked the changed snapshots are correct, and then updated them.
=> fix: support variadic custom asymmetric matchers

CHANGELOG.md, packages/babel-jest/src/index.js
Fixes #6908 
With the arrival of Babel 7.0.0 comes support for `.js` configuration files from Babel.
[See here for details.](https://babeljs.io/blog/2018/08/27/7.0.0#javascript-config-files)
> We are introducing babel.config.js. It isn't a requirement or even a replacement for .babelrc, but having this may be useful in certain cases.
> *.js configuration files are fairly common in the JavaScript ecosystem. ESLint and Webpack both allow for .eslintrc.js and webpack.config.js configuration files, respectively.
This PR adds support for the new config file added by the Babel team.
=> Added support for babel.config.js

CHANGELOG.md, packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
Mocks don't implement inherited static properties. E.g.:
Bar.js:
```javascript
class Foo {
static foo() {}
}
class Bar extends Foo {}
```
Bar-test.js:
```javascript
jest.mock('./Bar');
const Bar = require('./Bar');
Bar.foo; // undefined
```
See updated tests.
=> Mock inherited static properties and methods

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/matchers.js
When using `toBeInstanceOf()` on an `undefined` or `null` value Jest attempts to use `undefined.constructor` in its error message, which throws a TypeError along the lines of "TypeError: Cannot read property 'constructor' of undefined"
This makes the matcher more robust and returns a normal matcher error along the lines of "Expected X, received X"
Also added two snapshot tests for `toBeInstanceOf()` for `undefined` and `null` and confirmed reasonable error messages are now returned for these values.
=> `[expect]` Fix TypeError in `toBeInstanceOf` on `null` or `undefined`

CHANGELOG.md, packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
Reverts facebook/jest#6921
This causes some errors in Facebook tests, which means it could be breaking something. I'll investigate further and create a new PR.
=> Revert "Mock inherited static properties and methods"

CHANGELOG.md, packages/jest-resolve/src/__tests__/resolve.test.js, packages/jest-resolve/src/node_modules_paths.js
Fixes #6880. As discussed in #6906, wrap `realpath` call in try-catch and invoke only once, since it should be enough to resolve the canonical path.
Updated the existing tests to make sure nothing breaks.
@arcanis, @SimenB, @thymikee, @palmerj3
=> jest-resolve - only resolve realpath once in try-catch

CHANGELOG.md, flow-typed/npm/jest_v23.x.x.js, packages/jest-circus/src/__tests__/hooks_error.test.js, packages/jest-circus/src/index.js, packages/jest-jasmine2/src/__tests__/hooks_error.test.js, packages/jest-jasmine2/src/jasmine/Env.js, packages/jest-jasmine2/src/jasmine/jasmine_light.js
This pull request handles the case where the callback function for the jest hooks `beforeEach, beforeAll, afterEach, afterAll` are not functions in issue #6789. This PR also handles every other primitive type. PR #6917 only handles a smaller set of cases whereas this one does.
I've updated the test suites in both these files.
https://github.com/facebook/jest/blob/master/packages/jest-circus/src/__tests__/hooks_error.test.js
https://github.com/facebook/jest/blob/master/packages/jest-jasmine2/src/__tests__/hooks_error.test.js
=> Validate hook functions first argument

flow-typed/npm/jest_v23.x.x.js
This PR updates flow typings from #6931 so that they are more inline with what #6351 fixed
Edit: 
Something seems to be an issue the registry. Some of the CI installs are failing due to it. https://status.npmjs.org/incidents/v22ffls5cd6h
=> Update flow typing for x.each function calls

CHANGELOG.md, package.json
After `yarn` and `yarn jest` the result of `yarn clean-all` is that `git status` displays:
```
deleted:    e2e/presets/js/node_modules/jest-preset-js/jest-preset.js
deleted:    e2e/presets/js/node_modules/jest-preset-js/mapper.js
deleted:    e2e/presets/json/node_modules/jest-preset-json/jest-preset.json
deleted:    e2e/presets/json/node_modules/jest-preset-json/mapper.js
```
#6185 added these files and made an exception in `.gitignore` but not in `package.json` file.
Y’all are welcome to improve the `find` command in new `clean-e2e` script. I wrote it as clear and cross platform as I know how.
I used `find . -type d \( -name node_modules -prune \) -print` to explore `node_modules` directories:
1. After `git clone` there are 2 under `./e2e` and 4 under `./packages`
``` …
```
=> scripts: Don’t remove node_modules from subdirectories of presets in e2e tests

docs/MockFunctions.md
According to the API documentation of `getMockName` function ( https://jestjs.io/docs/en/mock-function-api#mockfngetmockname ), the getMockName function should be called via `mockFunc.getMockName()`, not `mockFunc.mock.getMockName()`.
Is there anything else I need to do?
=> [docs] Fix getMockName example of Mock Function document

CONTRIBUTING.md
Associated Issue: #6966 
Adding a note in CONTRIBUTING.md about the fact that Python is required to be able to run `yarn install`.
=> Add note about Python dependency in CONTRIBUTING

CHANGELOG.md, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/crawlers/__tests__/node.test.js, packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js, packages/jest-haste-map/src/crawlers/node.js, packages/jest-haste-map/src/crawlers/watchman.js, packages/jest-haste-map/src/haste_fs.js, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/module_map.js, packages/jest-resolve/src/__tests__/resolve.test.js, packages/jest-runner/src/__tests__/test_runner.test.js, packages/jest-runner/src/index.js, packages/jest-runner/src/test_worker.js, types/HasteMap.js
This changes the data structure used to store the metadata for files, modules, mocks and duplicated modules in the Haste Map from `Object` (without prototypes) to `Map`.
The performance of `Map` is much better than `Object` to implement dictionaries when they contain a large amount of entries, which is usually what we have here. After testing this change in Facebook we've seen a ~20% reduction of the time to run all tests, which is a massive performance improvement for us.
This only modifies the internal data structures used by Jest and its end users will not be affected by it (other than performance). The change in the `jest-haste-map` package is breaking though, as it might affect other packages depending on it (including jest packages, which have been updated here).
I've updated all …
=> HasteMap with native maps

CHANGELOG.md, README.md, docs/GettingStarted.md, website/versioned_docs/version-22.0/GettingStarted.md, website/versioned_docs/version-22.1/GettingStarted.md, website/versioned_docs/version-22.2/GettingStarted.md, website/versioned_docs/version-22.3/GettingStarted.md, website/versioned_docs/version-22.4/GettingStarted.md, website/versioned_docs/version-23.2/GettingStarted.md
resolves #6720
yarn cannot find a package with semvar `^7.0.0-0`. Further, the `7.0.0-beta#` builds do not work. The accurate package version is `^7.0.0-bridge.0`.
(The quotation marks around the package in the documentation also cause an error.)
`yarn add --dev babel-core@^7.0.0-0`
The package `babel-core@^7.0.0-bridge.0` should be added.
[Issue in @babel/babel-bridge](https://github.com/babel/babel-bridge/issues/5)
No code changes.
=> Fix for Babel7 bridge package name in documentation.

CHANGELOG.md, packages/jest-jasmine2/src/jasmine/Spec.js, packages/jest-jasmine2/src/jasmine_async.js, packages/jest-jasmine2/src/queue_runner.js
see also https://crbug.com/v8/7142
Error object keep references to all "context"s in the stack. This will lead to memory leaks if the Error objects are stored somewhere persistent. This is an "optimization" of v8, since constructing the `stack` property as string can be expensive.
Accessing the `stack` property will force stringifying of these internal objects and discards references, which allows scopes to be garbage-collected.
A similar fix was made here: https://github.com/mochajs/mocha/issues/3119
These memory leaks are usually very small since very few people store large objects outside of `it()`. In the webpack test suite the `it()` is called from the bundle after compiling. Here the bundle and the Compilation is in the stack. This causes memory leaks.
I believe but can't prove yet, …
=> Fix a memory leak in Error objects

.vscode/launch.json
This is a fix to ensure debugger stops at correct breakpoint in VSCode
Refs: https://github.com/facebook/jest/issues/6918
The contributors who use VSCode editor are not able to use debugger, as it doesn't stop at correct points as described in #6918
The issue was discussed in https://github.com/jest-community/vscode-jest/issues/372 where @connectdotz pointed out debugger configuration to be added as Jest uses flow ([documentation](https://github.com/flowtype/flow-for-vscode#debugger-configuration))
This PR adds that debugger configuration `"runtimeArgs": ["-r", "flow-remove-types/register"]` in VSCode launch configuration
* Screen recording of the issue:
[![Debug Jest with current test file not stopping at correct breakpoint](https://img.youtube.com/vi/VZUJyI3GeYY/0.jpg)](https://www.youtu …
=> chore: add runtimeArgs in VSCode launch.json

CHANGELOG.md, packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js, packages/jest-haste-map/src/crawlers/watchman.js
The current implementation of the watchman crawler ignores any previous information for files with different modification time. This modifies that part to also preserve the information for files with the same sha-1.
Updated the test suite.
=> Preserve info from files with matching SHA-1s

CHANGELOG.md, packages/jest-haste-map/src/index.js
This PR modifies the function `getWhiteList` in `jest-haste-map` to handle flipping the path separator on `@scoped/modules` on Windows. This allows Haste to properly resolve JS files inside of scoped modules on Windows.
Needed to resolve https://github.com/facebook/metro/issues/241 and https://github.com/facebook/metro/pull/249
Using a version of `jest-haste-map` patched with this patch, and the test suite in my Metro pull request, all tests pass
=> jest-haste-map: Fixed Haste whitelist generation for scoped modules on Windows

CHANGELOG.md, docs/GettingStarted.md, examples/babel-7/__tests__/index.test.js, examples/babel-7/babel.config.js, examples/babel-7/index.js, examples/babel-7/package.json, website/versioned_docs/version-22.0/GettingStarted.md, website/versioned_docs/version-22.1/GettingStarted.md, website/versioned_docs/version-22.2/GettingStarted.md, website/versioned_docs/version-22.3/GettingStarted.md, website/versioned_docs/version-22.4/GettingStarted.md, website/versioned_docs/version-23.2/GettingStarted.md, yarn.lock
A lot of people are struggling with running Babel 7 using Jest. This adds a minimal example (all you have to do is install the bridge package for `babel-core`, but it doesn't seem like stating that in the docs is enough).
For fun, I added the typescript preset as well as just module transformation.
Closes #6913.
Green CI.
=> add example using babel 7

CHANGELOG.md, docs/ExpectAPI.md, website/versioned_docs/version-22.0/ExpectAPI.md, website/versioned_docs/version-22.1/ExpectAPI.md, website/versioned_docs/version-22.2/ExpectAPI.md, website/versioned_docs/version-22.3/ExpectAPI.md, website/versioned_docs/version-23.0/ExpectAPI.md, website/versioned_docs/version-23.1/ExpectAPI.md, website/versioned_docs/version-23.2/ExpectAPI.md, website/versioned_docs/version-23.3/ExpectAPI.md, website/versioned_docs/version-23.4/ExpectAPI.md, website/versioned_docs/version-23.5/ExpectAPI.md, website/versioned_docs/version-23.6/ExpectAPI.md
Better safe than sorry, especially because I missed additions for `.toBe` in 22.2
`yarn lint:md` which I should have done in the first place ;)
=> docs: Replace shallow equality with referential identity in `ExpectAPI.md`

CHANGELOG.md, packages/jest-changed-files/package.json, packages/jest-changed-files/src/git.js, packages/jest-changed-files/src/hg.js, yarn.lock
This is just something I've had on my todo list for quite some time. It simplifies our code a great deal.
Green CI
=> refactor: use execa instead of child_process for VCS commands

CHANGELOG.md, packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
Fixes #6994 and #6995, and generalizes some code from jest-mock.
Re-applies #6921 fixing its bugs.
Added new test cases and tested in FB infra.
=> Fix mocking inherited static properties and prototype-less objects

packages/jest-mock/src/__tests__/jest_mock.test.js
Just fixing some indentation issues introduced in #7003.
=> Fix indentation of template literals in test

CHANGELOG.md, packages/jest-haste-map/src/haste_fs.js, packages/jest-resolve-dependencies/src/index.js
This method is faster if the consumer only want to traverse the files (no need to create a new array). It is especially relevant if the number of files in the map is large.
Only flow typechecking. This file isn't unit tested, but the code is so simple it doesn't really need it. Manually tested in the terminal.
Edit: tested through jest-resolve-dependencies, where it's used now
=> Added method to get an iterator for all files in HasteFS

CHANGELOG.md, packages/jest-worker/README.md, packages/jest-worker/src/__tests__/child.test.js, packages/jest-worker/src/__tests__/index.test.js, packages/jest-worker/src/__tests__/worker.test.js, packages/jest-worker/src/child.js, packages/jest-worker/src/index.js, packages/jest-worker/src/types.js, packages/jest-worker/src/worker.js
There is no way to make `jest-worker` call an `initialize` method before calling a method in the worker for the first time. 
This PR adds the possibility to call an `initialize` method if it exists in the worker and an `initializeArgs` option has been passed (I've opted to not call by default this method to not make this PR a breaking change, but I can change this easily).
Also, to make the behaviour consistent, I've added some logic to call an `end` method in the worker if it exists when the Worker farm is being ended.
I've created unit tests to verify the behaviour
=> Add option to call initialize and end methods in workers

packages/babel-jest/README.md
This makes babel-jest's docs congruent with what `babel-core` suggests. From [babel-core@7.0.0-bridge.0 docs](https://www.npmjs.com/package/babel-core/v/7.0.0-bridge.0):
> to install Babel 6, they could now do
>
> `npm i some-package babel-core@^7.0.0-bridge @babel/core
Nothing to test, this is just a documentation change.
=> babel-jest: Suggest the correct bridge version

CHANGELOG.md, e2e/__tests__/only_changed.test.js, packages/jest-cli/src/getNoTestFoundRelatedToChangedFiles.js, packages/jest-editor-support/src/Runner.js, packages/jest-editor-support/src/__tests__/runner.test.js
This pull request makes a quality of life improvement as referred here (#7026). If a `changedSince` flag is being used, the test runner should update the message being shown to reflect the ref that `changedSince` is being pointed to. This PR also updates the runner to be aware of this new message format. 
I've added tests cases in https://github.com/facebook/jest/blob/master/e2e/__tests__/only_changed.test.js and https://github.com/facebook/jest/blob/master/packages/jest-editor-support/src/__tests__/runner.test.js to reflect the changes.
=> Fix message when changedSince is being used 

packages/jest-editor-support/src/Runner.js, packages/jest-editor-support/src/__tests__/runner.test.js
This pull request updates the regular expression that was wrongly written in #7028 where the tests were passing because the tests were written wrongly. The quotation marks were missing in the regular expression.
The tests in `jest-editor-support/src/__tests__/runner.tests.js` have been updated with the the quotation marks in place.
=> Fix regular expression for matching message for findMessageType

CHANGELOG.md, e2e/__tests__/promise_reject.test.js, e2e/promise-reject/package.json, packages/jest-jasmine2/src/is_error.js
This PR fixes the scenario where a test returns a promise which rejects to null. 
Fixes #6896
Closes #6897
An end to end test has been added to test for this scenario. 
Note that the test assertion has two cases due to jest-jasmine and jest-circus returning different outputs for this case. 
Edit: 
Acknowledging @Pajn here for the work he has done in #6897. 
Just noting that #6897 should also be closed when this PR is accepted.
=> Fix jest crashing when potentialError is null

CHANGELOG.md, docs/CLI.md, website/versioned_docs/version-22.0/CLI.md, website/versioned_docs/version-22.2/CLI.md, website/versioned_docs/version-22.3/CLI.md, website/versioned_docs/version-22.4/CLI.md, website/versioned_docs/version-23.0/CLI.md, website/versioned_docs/version-23.1/CLI.md, website/versioned_docs/version-23.2/CLI.md, website/versioned_docs/version-23.3/CLI.md, website/versioned_docs/version-23.5/CLI.md, website/versioned_docs/version-23.6/CLI.md
This PR fixes #7034 By adding documentation for `--runTestsByPath` CLI parameter
=> document `--runTestsByPath` CLI parameter

CHANGELOG.md, e2e/__tests__/reset_modules.test.js, e2e/reset_modules/__tests__/reset_modules.test.js, e2e/reset_modules/package.json, packages/jest-mock/src/index.js, packages/jest-runtime/src/index.js
Fixes #7009
`resetModules` checks if `_isMockFunction` is truthy on all properties of the global object, which can lead to TypeErrors when a global property is mocked using `identity-obj-proxy`. Changing the condition to check if `_isMockFunction` is true rather than truthy will fix the issue and keep the original intent of the code, so it shouldn't cause any breaking changes.
Tests all ran OK.
=> Check _isMockFunction is true rather than truthy on global properties

CHANGELOG.md, e2e/__tests__/__snapshots__/failures.test.js.snap, e2e/failures/__tests__/node_assertion_error.test.js, packages/jest-jasmine2/src/jasmine/Env.js
While jest-circus worked just like it should (🎉), jest-jasmine only checked for node assert on thrown errors, not rejected ones (from async errors).
Not sure about the best way to fix the test assertion for Circus. Failure looks like this: 
Fixes #6752
Test added
=> fix: show stack traces on async assert errors

CHANGELOG.md, scripts/build.js
I noticed empty `build/__tests__` folder in the installed `diff-sequences@23.2.0` package.
Although I didn’t find where that problem was fixed between 23.4.0 and 23.4.1, I did find change in assumption as reason for many empty subfolders in `build` folder.
Comment in `scripts/build.js` file:
> Non-js or files matching IGNORE_PATTERN will be copied without transpiling.
For a long while, files in folders matching `IGNORE_PATTERN` are **not** copied, so `buildFile` function can return early before `mkdirp` call.
The diff after code is moved with a change takes a second look to understand what happened :(
`yarn build-clean` and `yarn build` and `yarn jest`
| after `yarn build` | baseline | improved |
| ---: | ---: | ---: |
| files | 250 | 250 |
| folders | 189 | 56 |
| `__tests__` or …
=> scripts: Don’t make empty subfolders for ignored files in build folder

CHANGELOG.md, docs/GlobalAPI.md, e2e/__tests__/__snapshots__/globals.test.js.snap, e2e/__tests__/__snapshots__/test-todo.test.js.snap, e2e/__tests__/test-todo.test.js, e2e/test-todo/__tests__/statuses.test.js, e2e/test-todo/__tests__/todo_multiple_args.test.js, e2e/test-todo/__tests__/todo_no_args.test.js, e2e/test-todo/__tests__/todo_non_string.test.js, e2e/test-todo/package.json, packages/jest-circus/src/__tests__/circus_it_test_error.test.js, packages/jest-circus/src/__tests__/circus_todo_test_error.test.js, packages/jest-circus/src/event_handler.js, packages/jest-circus/src/index.js, packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init.js, packages/jest-circus/src/run.js, packages/jest-cli/src/constants.js, packages/jest-cli/src/reporters/utils.js, packages/jest-cli/src/reporters/verbose_reporter.js, packages/jest-cli/src/testResultHelpers.js, packages/jest-jasmine2/src/__tests__/it_test_error.test.js, packages/jest-jasmine2/src/__tests__/todo_error.test.js, packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/jasmine/Env.js, packages/jest-jasmine2/src/jasmine/Spec.js, packages/jest-jasmine2/src/jasmine/jasmine_light.js, packages/jest-jasmine2/src/reporter.js, packages/jest-runner/src/run_test.js, types/Circus.js, types/TestResult.js
Adds `test.todo` and `it.todo` similar to [ava's todo](https://github.com/avajs/ava#test-placeholders-todo). I'm opening this up early for feedback from @SimenB @thymikee @rickhanlonii @aaronabramov :smile:
Motivation: see [comment](https://github.com/facebook/jest/pull/6602#issuecomment-421764515) by @SimenB 
Closes #6430 #6602 and addresses #6256
This change re-introduces the behaviour of planning a test, similar to Jest@22 `test('do something')`
- unit tests ✅
- e2e tests ✅
Given this test suite:
```js
it('passes', () => {
expect(10).toBe(10);
});
it('fails', () => {
expect(10).toBe(101);
});
it.skip('skips', () => {
expect(10).toBe(101);
});
it.todo('todo');
```
The new output will look like:
- Add docs
- Add typings
=> Add test.todo

CHANGELOG.md, packages/jest-circus/src/index.js, packages/jest-cli/src/collectHandles.js, packages/jest-each/package.json, packages/jest-each/src/bind.js, packages/jest-jasmine2/src/error_on_private.js, packages/jest-jasmine2/src/jasmine/Env.js, packages/jest-runner/src/run_test.js, packages/jest-util/src/__tests__/error_with_stack.test.js, packages/jest-util/src/error_with_stack.js, packages/jest-util/src/index.js
Removes the duplication of:
```js
const error = new Error('whatever');
if (Error.captureStackTrace) {
Error.captureStackTrace(error, someFunction);
}
```
Motivation: see @SimenB's https://github.com/facebook/jest/pull/7033#discussion_r219711554
- Added unit test for new class
- All existing test should pass
I've not updated the `expect` package with this change as I believe it cannot depend on `jest-util` because of bundling for the browser, is this correct? cc/ @thymikee @rickhanlonii
=> [jest-util] Add ErrorWithStack class

CHANGELOG.md, e2e/__tests__/haste_map_sha1.test.js, packages/jest-haste-map/src/__tests__/__snapshots__/index.test.js.snap, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/__tests__/worker.test.js, packages/jest-haste-map/src/crawlers/__tests__/node.test.js, packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js, packages/jest-haste-map/src/crawlers/node.js, packages/jest-haste-map/src/crawlers/watchman.js, packages/jest-haste-map/src/haste_fs.js, packages/jest-haste-map/src/index.js, packages/jest-haste-map/src/lib/__tests__/fast_path.test.js, packages/jest-haste-map/src/lib/fast_path.js, packages/jest-haste-map/src/module_map.js, packages/jest-haste-map/src/types.js, packages/jest-haste-map/src/worker.js, packages/jest-resolve/src/__tests__/resolve.test.js, packages/jest-runtime/src/index.js, types/HasteMap.js
At the moment all paths in the haste map are absolute, which is convenient as all the operations in Jest use absolute paths. This has a problem though: haste maps can't be remotely cached.
This PR makes all paths in the haste map relative so they can be cached and reused in different servers (remote caching).
The approach used is to have relative paths in the haste map but make it transparent for its users (making them absolute in all the operations).
I also tried making all paths relative during serialization/deserialization, but it has a significant impact in startup time. With this approach the cost is distributed across the whole test run and the impact isn't significant overall.
I've updated all tests and tested it in FB-infra (both single and watch mode).
=> Used relative paths in haste map

e2e/__tests__/fake-promises.test.js, e2e/fake-promises/asap/__tests__/generator.test.js, e2e/fake-promises/asap/fake-promises.js, e2e/fake-promises/asap/package.json, e2e/fake-promises/immediate/__tests__/generator.test.js, e2e/fake-promises/immediate/fake-promises.js, e2e/fake-promises/immediate/package.json, package.json, packages/jest-util/src/__tests__/fake_timers.test.js, yarn.lock
Based on my understanding on how FB uses fake timers to drive promises synchronously, adding a couple of integration tests.
Related to #5165.
Green CI
=> chore: add integration test for driving promises with fake timers

CHANGELOG.md, e2e/__tests__/__snapshots__/coverage_report.test.js.snap, e2e/__tests__/coverage_report.test.js, packages/jest-cli/src/reporters/coverage_reporter.js
Prevent text-summary from always being displayed when covereage is
configured. The reporters the configuration specifies should be used.
If no reporters are specified, then add the default text-summary.
Fixes #7048
Not really sure how to write tests for this.
=> fix: coverage summary reporting

docs/SnapshotTesting.md
Images were broken in the repo docs since the directory were they are located has changed and links weren't updated
Website running in local doesnt break with this change:
=> Docs: Fixed img links in SnapshotTesting.md

CHANGELOG.md, docs/Configuration.md, website/versioned_docs/version-22.0/Configuration.md, website/versioned_docs/version-22.1/Configuration.md, website/versioned_docs/version-22.2/Configuration.md, website/versioned_docs/version-22.3/Configuration.md, website/versioned_docs/version-22.4/Configuration.md, website/versioned_docs/version-23.0/Configuration.md, website/versioned_docs/version-23.1/Configuration.md, website/versioned_docs/version-23.2/Configuration.md, website/versioned_docs/version-23.3/Configuration.md, website/versioned_docs/version-23.4/Configuration.md, website/versioned_docs/version-23.5/Configuration.md, website/versioned_docs/version-23.6/Configuration.md
The configuration docs indicate that the default `coverageReporters` value is `["json", "lcov", "text", "clover"]`. However, the [default values](https://github.com/facebook/jest/blob/0418cab88c5e927c94a02ecb445fc694e6b2bbda/packages/jest-config/src/Defaults.js#L30) (this should be for all versions of the docs) have also included "clover" as one of the reporters. So by default, a `clover.xml` file will be generated. 
Here it is on my local (highlight is from cmd/ctrl + F in Chrome):
=> add "clover" to coverageReports default value

CHANGELOG.md, docs/Puppeteer.md
Add missing export statement in puppeteer_environment.js
Just found that the puppeteer_environment.js under docs/Puppeteer.md doesn't export the environment
=> Add missing export statement

CHANGELOG.md, packages/jest-cli/src/cli/index.js, packages/jest-config/src/__tests__/readConfigs.test.js, packages/jest-config/src/index.js
This just moves the method to get the normalized configuration from the command line args and the project list to `jest-config`.
Added a smoke test in `jest-config` (just like we did for `readConfig`) and the current tests for `jest-cli` should still pass.
=> Add `readConfigs` method to `jest-config`

CHANGELOG.md, packages/pretty-format/src/__tests__/dom_collection.test.js, packages/pretty-format/src/plugins/dom_collection.js
Fixes #7121
**Problem**: When `pretty-format` serializes a `jsdom` object instance for which no plugin matches, it takes a “stupid amount of time” on the property with key `Symbol(impl)` and then fails.
**Solution**: Support HTML collection classes to write assertions for received values:
* element properties `childNodes`, `children`, `elements`, `options`
* `getElementsByTagName` and so on
* `querySelectorAll`
Also added support for `config.min` option to omit class name.
Be aware that class names can be moving targets even in browsers:
* `form.elements` returned `HTMLFormControlsCollection`
* `fieldset.elements` returned `HTMLCollection`
despite the claim at [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormControlsCollection)
> The …
=> pretty-format: Support HTMLCollection and NodeList in DOMCollection plugin

CHANGELOG.md, e2e/__tests__/__snapshots__/show_config.test.js.snap, packages/jest-cli/src/runJest.js, packages/jest-config/src/Defaults.js, types/Config.js
`cwd` is assigned to the project configuration in `jest-cli`, which makes it harder to get a normalized project configuration just using `jest-config`. This adds that configuration to the defaults so anyone using it directly can have exactly the same configuration `jest-cli` would have with the same parameters.
I ran all current tests and manually tested that the configuration contained the default `cwd`.
=> Move assignment of cwd to default config

CHANGELOG.md, docs/TutorialReactNative.md, packages/jest-docblock/src/__tests__/index.test.js
We don't support this feature anymore so it's better to remove all references to it.
Only changes in docs and the values in a test file (that passes).
=> Clean references to @providesModule

packages/jest-docblock/src/__tests__/index.test.js
Fix a lint warning introduced in #7147.
`yarn run lint`
=> Fix lint warning

CHANGELOG.md, packages/jest-config/src/__mocks__/os.js, packages/jest-config/src/__tests__/getMaxWorkers.test.js, packages/jest-config/src/getMaxWorkers.js
Jest is using `getMaxWorkers` to figure out how many CPUs to use in parallel to run the test suite. However, it's using node's `os.cpus()`, which unfortunately might not return an answer if the corresponding system information is not available.
That's what happens under [termux](https://termux.com), a popular terminal emulator for Android. Using termux, we get:
```
> os = require('os')
...
> os.cpus()
undefined
```
This small detail is crashing jest, since it's trying to read `length` from an undefined object:
```js
const cpus = os.cpus().length;
```
The proposed solution is to default the result of `getMaxWorkers` to 1 when `os.cpus()` is undefined. This is enough to fix the crash.
Coverage for `getMaxWorkers` was updated to reflect the new changes.
In addition, to verify the goal of the …
=> Fix `getMaxWorkers` on termux

README.md
This fixes the 'Good First Issue' url in the readme under the 'Contributing' section.
Currently when the link is clicked it will redirect users to the 'Issues' page for this project, but no issues will be displayed because the label has an error in its formatting.
=> Fix for 'Good First Issue' url in readme

CHANGELOG.md, docs/Troubleshooting.md, website/versioned_docs/version-23.6/Troubleshooting.md
Add a note on `test.each` synchronous setup.
Motivation: https://github.com/facebook/jest/issues/7100#issuecomment-429042239
=> [docs] Add synchronous test.each setup

website/sidebars.json, website/versioned_sidebars/version-22.0-sidebars.json, website/versioned_sidebars/version-22.1-sidebars.json, website/versioned_sidebars/version-22.2-sidebars.json, website/versioned_sidebars/version-22.3-sidebars.json, website/versioned_sidebars/version-23.0-sidebars.json, website/versioned_sidebars/version-23.4-sidebars.json
FIXES: #7133
The document "DOM Manipulation" is archived with all other guides but was inaccessible through the website sidebar, this commit make this page accessible through the sidebar
I ran `yarn build` and `yarn start` on the website folder, and the page "DOM Manipulation" was visible on the sidebar under the "Guides" section as desired
=> Add the "DOM Manipulation" page to the section "guides" on the website

CHANGELOG.md, packages/jest-mock/src/index.js
There is function for checking object type
```js
function isA(typeName: string, value: any): boolean {
return Object.prototype.toString.apply(value) === '[object ' + typeName + ']';
}
```
But this function called many times for same object. (12 times for same ref)
```js
isA('Number', ref) ||
isA('String', ref) ||
isA('Boolean', ref) ||
isA('Symbol', ref)
... 
```
My fix added caching object name to avoid needless `Object.prototype.toString.apply(value) === '[object ' + typeName + ']'`.
We just can get object name only once.
```js
function getObjectType(value: any): string {
return Object.prototype.toString.apply(value).slice(8, -1);
}
typeName === 'Number' ||
typeName === 'String' ||
typeName === 'Boolean' ||
typeName === 'Symbol'
...
```
=> Simpify getting object type name

README.md
A link correction was missing in readme. https://github.com/facebook/jest/pull/7157
=> Fix 'Good First Issue' url in README (#7157) [ci skip]

docs/CLI.md, packages/jest-cli/src/cli/args.js, website/versioned_docs/version-22.0/CLI.md, website/versioned_docs/version-22.2/CLI.md, website/versioned_docs/version-22.3/CLI.md, website/versioned_docs/version-22.4/CLI.md, website/versioned_docs/version-23.0/CLI.md, website/versioned_docs/version-23.1/CLI.md, website/versioned_docs/version-23.2/CLI.md, website/versioned_docs/version-23.3/CLI.md, website/versioned_docs/version-23.5/CLI.md, website/versioned_docs/version-23.6/CLI.md
Current directory brings current working directory to mind and therefore is IMHO confusing.
https://github.com/facebook/jest/blob/87a5a67c483b4bd37cc8e351d8a145d7bcbd1690/packages/jest-config/src/readConfigFileAndSetRootDir.js#L54-L55
=> Update info about how rootDir is set (if not explicitly specified)

CHANGELOG.md, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js, packages/jest-runtime/src/index.js
This removes the need to pass an ignore pattern to new instances of `HasteMap` and updates `jest-runtime` so it doesn't pass one unless it's necessary.
Updated the current tests and tested in FB infra.
=> Make ignorePattern optional in HasteMap

CHANGELOG.md, e2e/__tests__/multi_project_runner.test.js, packages/jest-runtime/src/__tests__/script_transformer.test.js, packages/jest-runtime/src/script_transformer.js
`jest-runtime` uses an in-memory cache system (a simple "global" `Map`) to avoid reading a file when it gets required multiple times by separate tests.
This cache system uses the filename, the modified time and the `instrumented` boolean as the key (see the `getScriptCacheKey()` method), and it's used across different projects. This causes incorrect transformations when tests from two separate projects that have different transformers require the same file.
To fix this issue I've decided to refactor a bit the global objects that are defined in `script_transformer.js`: instead of having multiple of them (`configToJsonMap`, `cache` and `ignoreCache`, each of them with different keys), I've merged them into a single `ProjectCache` object that gets initialized when `ScriptTransformer` is …
=> Fix cache of transformed files with multiple projects

CHANGELOG.md, docs/Configuration.md, website/versioned_docs/version-23.6/Configuration.md
See #7174 for issue. `setupFiles` documentation was misleading. This PR makes it clearer that setupFiles are only expected to run once per test file, not once per test.
N/A (documentation change)
=> update setupFiles documentation for improved clarity

CHANGELOG.md, e2e/coverage-transform-instrumented/Preprocessor.js, packages/babel-jest/src/index.js, packages/babel-preset-jest/index.js
=> feat: export babel-preset-jest as a function

packages/jest-message-util/package.json, scripts/browserBuild.js, yarn.lock
Allows us to not worry about syntax of our dependencies (like babel).
Both lint of the code and the browser test should still pass.
Would be great if the karma test actually ran on IE 11 or something and not just chrome. Anyways, not related to this change 🙂
=> chore: transpile everything for browsers

packages/jest-message-util/src/index.js
Used regexp instead of split-map-join for adding indent for not empty line in message report.
It works 2x faster.
https://jsperf.com/regexp-vssplit-map-join
=> Use regexp instead of split-map-join

e2e/__tests__/dependency_clash.test.js
That test was supposed to test the interaction between Haste modules and installed node_modules, so changing it to use relative paths made it useless. This fixes it by using `hasteImplModulePath` to convert it into a Haste module.
Just ran the test.
=> Fix dependency clash test modified in #6104

CHANGELOG.md, packages/jest-validate/README.md, packages/jest-validate/src/__tests__/__snapshots__/validate.test.js.snap, packages/jest-validate/src/__tests__/validate.test.js, packages/jest-validate/src/condition.js, packages/jest-validate/src/default_config.js, packages/jest-validate/src/errors.js, packages/jest-validate/src/index.js
Split from https://github.com/facebook/jest/pull/7194
Prerequisite to resolving https://github.com/facebook/jest/issues/7180
This PR provides a syntax for `jest-validate` to accept more than one example for a single config value, which can be of different types. This allows overloading config options to accept multiple types.
- existing unit tests pass (except as expected where internal config changed types)
- added unit tests to cover new valid and error conditions
=> Allow multilple valid types

CHANGELOG.md, packages/jest-haste-map/src/index.js
This makes it easier for tools to interact with the file without making assumptions about how it's generated.
It's just a getter for a class field, so just Flow type checking.
=> Add getCacheFilePath to HasteMap

CHANGELOG.md
This marks the change in relative paths in the haste map as breaking (as the `rootDir` is now required in the constructor) and moves a breaking change that was in "Fixes" to "Features".
=> Move breaking changes to "features" in CHANGELOG

CHANGELOG.md, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js
This simplifies the remote caching of haste map files. Right now the haste map name is structured as `haste-map-${name}-${rootDirHash}-${configHash}`. This modifies the `configHash` so it's not affected by the `rootDirHash` (and passes the project name so it's still taken into account).
Updated unit tests.
=> Remove redundant information from the config hash part of the haste map

CHANGELOG.md, packages/jest-cli/src/watch.js
This PR fixes a regression that was introduced here. https://github.com/facebook/jest/pull/5399/files#diff-d8a3d0a3a8b42ab87b18835ad8f7cb46L208
Pressing a key of an interactive watch plugin should interrupt the running tests, otherwise, the output gets messed up.
Pressing "p" while tests were running, does not interrupt test run and the output breaks.
Pressing "p" while tests were running, interrupts the tests run
=> Interrupt tests if interactive watch plugin key is pressed

docs/TutorialReact.md
The description claims to use DOM yet the code snippet shows text. PR changes the text to DOM.
Documentation precision
=> Updated documentation: "Snapshot Testing with Mocks...": option 2) should show use of DOM

CHANGELOG.md, e2e/__tests__/coverage_report.test.js, e2e/__tests__/coverage_threshold.test.js, e2e/__tests__/find_related_files.test.js, e2e/__tests__/module_name_mapper.test.js, e2e/__tests__/transform.test.js, e2e/__tests__/typescript_coverage.test.js, e2e/runJest.js
This change ensures that the tests work regardless of the value of
`FORCE_COLOR` environment variable. There are environments where this
variable is set to 1 and the tests fail. For example the tests fail when
they are run from Jetbrains IDEs (Rubymine, Webstorm and etc).
istanbul-* packages were updated because 1.* version uses old `support-colors` package that doesn't allow to disable colors with `FORCE_COLOR=0`. Instead it interpreters zero value in the same way as 1 or anything else by forcing colors. The latest version of istanbul uses the updated package that disables colors if `FORCE_COLOR=0`
I suppose this patch is the logical final for #5646 and #5652.
If you run tests on master with defined FORCE_COLOR=1 you will receive this:
```powershell
PS E:\src\jest> $Env:FORCE_COLOR=1; …
```
=> Use FORCE_COLOR=0 for all tests

CHANGELOG.md, packages/jest-changed-files/src/hg.js
#6732 improved the commands used to check the files that have checked for both Mercurial and Git repositories, but caused a bug on Mercurial repositories.
Turns out that executing `hg status -A` returns every single file on the repository, which is wrong (and extreeeemely slow for huge repos like FB's one 😅).
This PR changes the arguments passed to the `hg` command when `lastCommit` is `true` to fix the problem.
`jest-changed-files` does not have any tests (which is understandable since testing its functionality is not straightforward), so I've done some manual testing:
1. Execute manually `hg status -amnu --change . <some_folders>` on a Mercurial repository and check that it always returns the changed files from the current commit.
2. Patch this PR into our internal codebase with a WIP …
=> Do not return all files when checking changed files from last commit

e2e/__tests__/watch_mode_update_snapshot.test.js
I left a commented `afterAll` block after merging #7141. It doesn't impact in the test results since it simply leaves a directory in a `tmp` location, which then gets cleaned up in the next test run.
N/A
=> Uncomment afterAll in watch mode e2e test

e2e/__tests__/__snapshots__/module_name_mapper.test.js.snap, e2e/__tests__/__snapshots__/resolve_no_file_extensions.test.js.snap, packages/jest-resolve/src/index.js
Method `this._supportsNativePlatform()` calls very offten. But it is not required, because it just checks: 
```js
_supportsNativePlatform() {
(this._options.platforms || []).indexOf(NATIVE_PLATFORM) !== -1;
}
```
We can check it once in `constructor` and use simple boolean flag.
=> Cache checking supports native platform

CHANGELOG.md, e2e/__tests__/__snapshots__/timeouts.test.js.snap, e2e/__tests__/timeouts.test.js, packages/jest-circus/src/event_handler.js, packages/jest-circus/src/utils.js, packages/jest-jasmine2/src/__tests__/p_timeout.test.js, packages/jest-jasmine2/src/p_timeout.js, packages/jest-jasmine2/src/queue_runner.js
#7074 made sync tests fail if they finished after the defined timeout. That's a breaking change whose benefits don't compensate the upgrade cost and there's a valid workaround to implement it in userland. See the comments in #6947.
Unit and e2e tests.
=> Revert sync timeouts

CHANGELOG.md, docs/JestObjectAPI.md, packages/jest-environment-jsdom/src/__mocks__/index.js, packages/jest-runtime/src/index.js, packages/jest-util/src/__tests__/fake_timers.test.js, packages/jest-util/src/fake_timers.js, types/Environment.js, types/Jest.js
Part of #5171, but as it's pretty breaking on its own, it'd be great to land separately
Green CI
=> chore: remove long-deprecated timer globals

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/matchers.js
This pull request updates the failure message returned by toStrictEqual so that it is more inline with what #7105 envisions.
The matcher is tested with a snapshot test. 
Here are a few screenshots of the before and after along with the test file.
Before: (I had to minimize the image to fit both tests in one screen)
After:
=> Update toStrictEqual failure message

CHANGELOG.md, packages/jest-each/src/__tests__/__snapshots__/array.test.js.snap, packages/jest-each/src/__tests__/__snapshots__/template.test.js.snap, packages/jest-each/src/__tests__/array.test.js, packages/jest-each/src/__tests__/template.test.js, packages/jest-each/src/bind.js
Motivation: @SimenB's https://github.com/facebook/jest/issues/7100#issuecomment-429042239
> We should probably throw on empty arrays as well, not just non-arrays
- Unit tests
=> [jest-each]: Add empty string/array validation check

CHANGELOG.md, packages/jest-haste-map/src/HasteFS.js, packages/jest-resolve-dependencies/src/index.js
Currently, `hasteFS.getFileIterator()` converts all file paths to absolute, which can be expensive when `jest-haste-map` tracks a lot of files.
This PR changes the behaviour and makes `getFileIterator()` return relative paths (the same way that `hasteFS` now accepts relative paths, and creates a new method (`getAbsoluteFileIterator()`) which returns the absolute paths.
Unit tests
=> Make getFileIterator() return relative paths

CHANGELOG.md, e2e/__tests__/__snapshots__/expect-async-matcher.test.js.snap, e2e/__tests__/__snapshots__/failures.test.js.snap, packages/jest-message-util/src/__tests__/__snapshots__/messages.test.js.snap, packages/jest-message-util/src/__tests__/messages.test.js, packages/jest-message-util/src/index.js, packages/jest-runtime/src/script_transformer.js
Previously, _addMissingMessageToStack decides not to add in the message to what we display, because it can't identify it as a stack. If we fix that by setting stack to include the message upfront (as many browsers do anyway), then it is printed but not prominently -- it is grayed out and with the stack with still only "Error" on the first line. Now if separateMessageFromStack can't tell where the stack begins, we assume the first line is the message -- which will cause it to be displayed more prominently.
We could also try to detect code frames in separateMessageFromStack specifically (as we do stacks) but that doesn't seem trivial, in part because the code frame has already been colorized by the time it gets here.
Before:
After:
=> Improve message/stack parsing for Babel code frame errors

CHANGELOG.md, packages/jest-haste-map/src/lib/__tests__/fast_path.test.js, packages/jest-haste-map/src/lib/fast_path.js
close #7323
ex)
`dirname: foo/bar`
`filename: foo/barbaz/index.js`
And relative() return `az/index.js`.
Expected return `../barbaz/index.js`
Added a test with fix commit.
=> fix: get relative path in haste map

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/utils.js
I'm not super excited about the fix, so any feedback is welcome! It got hairy really quick, and looking at the docs for `Object.create`, I can see how this is a weird edge case that some have run into (including myself)
This problem is discussed in #6730 .
In short, objects created using unconventional means such as `Object.create(null)` will not have a `constructor` property, causing an exception to be throw in "packages/expect/src/utils.js" `hasOwnProperty` function.
This odd behavior of JS objects is discussed in depth in the [MDN docs here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#Custom_and_Null_objects).
Added a test case to the unit tests for `toMatchObject` matcher. The included test case will throw an error `TypeError: Cannot …
=> handle objects with no constructor in hasOwnProperty

CHANGELOG.md, packages/jest-haste-map/src/ModuleMap.js, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js, types/HasteMap.js
`jest-haste-map` had a bug when recovering from a haste name collision: it was using the `type` from the deleted file instead of the type from the remaining file in the haste map.
This PR fixes this issue, while it also changes the internal data structure that holds the duplicated modules. 
I've split the PR into two commits: the first one only fixes the issue and the second one converts the `duplicates` structure into a `Map`. We can discard the second commit if needed.
I've marked the change as a breaking change since the duplicated modules are part of the public API of `jest-haste-map` (although it should be very rare for a user to rely on this).
I've created a new unit test that ensures the correct behaviour (that test would fail currently in master).
=> Fix recovery of haste collisions

CHANGELOG.md, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js
Some code in the haste map checked if the module ID changed to determine if the file should be rechecked for duplication or not. The module ID isn't available at that point (it's extracted later from the filename) so it was returning all the files all the time.
Also improved the data structure used to store those deprecated files to remove the number of newly allocated objects.
Updated tests.
=> Fix duplicate module detection

CHANGELOG.md
We had an issue about the change in coverage reporters and it wasn't marked as breaking in the changelog. Given that's a change in the behaviour it should be properly specified there.
=> Mark change as breaking in changelog

CHANGELOG.md, e2e/__tests__/__snapshots__/show_config.test.js.snap, packages/jest-config/src/Defaults.js, packages/jest-config/src/ValidConfig.js, packages/jest-runtime/src/index.js, types/Config.js
The HasteMap class has an option to compute the sha-1 of files and use it to determine if a file has changed if the modification times differ. This is used by external packages (e.g. Metro) but the option wasn't exposed in Jest. It's exposed as an option instead of enabling it by default because it has a performance impact that only pays off for some use cases (like remote caching, where mtimes differ).
This is difficult to test e2e (as it'll mostly be used with watchman and remote caching where mtime is lost) and we don't test that options are forwarded in the different packages in unit tests, so I trust Flow typing and manual testing here.
=> Add computeSha1 option

CHANGELOG.md, docs/Configuration.md, e2e/__tests__/find_related_files.test.js, packages/jest-haste-map/src/__tests__/dependencyExtractor.js, packages/jest-haste-map/src/lib/__tests__/dependencyExtractor.js, packages/jest-haste-map/src/lib/dependencyExtractor.js, packages/jest-haste-map/src/worker.js
Changed the interface for the new dependency extractors feature to be a namespace/object instead of a function. This is a prerequisite to add `getCacheKey` to invalidate any caches that have been created using this logic when it changes (#7350).
Updated unit tests
=> Use namespace for dependency extractor

CHANGELOG.md, docs/Configuration.md, packages/jest-haste-map/src/__tests__/dependencyExtractor.js, packages/jest-haste-map/src/__tests__/haste_impl.js, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.js
Right now the `hasteImplModulePath` (used to extract "global" module names from file paths) and `dependencyExtractor` options are not taken into account to compute the cache key for the haste map. Those options affect a great deal how the haste map is generated, so if they change the haste map should be regenerated (e.g. if we change the dependency extractor to add a new type of dependency, they won't be included in the files that are currently cached in the haste map).
Added unit tests to check this.
=> Accept additional cache keys for haste map

.circleci/config.yml, CHANGELOG.md, package.json, scripts/checkCopyrightHeaders.js, yarn.lock
Added a script to verify that source files contain the Facebook copyright header. Facebook has an internal tool to verify it and will help aligning them.
```bash
echo '// Non-empty' > packages/jest/foo.js
git add packages/jest/foo.js
yarn run check-copyright-headers
```
The output should be something like:
```
Facebook copyright header check failed for the following files:
packages/jest/foo.js
Please include the header or blacklist the files in `scripts/checkCopyrightHeaders.js`
error Command failed with exit code 1.
```
And the exit code must be 1 if it failed and 0 otherwise.
The `lint-and-typecheck` job should check this. Example: https://circleci.com/gh/facebook/jest/39078
=> Add check for copyright headers

CHANGELOG.md, packages/jest-cli/src/cli/index.js
I'm working on an internal CLI that runs jest, eslint, and sasslint all in one single process for our frontend team to run from their `package.json`'s
Aka something like, `"test": "cli test"`.
The code `process.on('exit', () => (process.exitCode = code));` adds a listener that is overriding the exit codes we're setting so that when jest is successful, and eslint or sasslint fail, I can't exit with a failing code.
Therefore our CI's are reporting as passed even though the linting fails.
It seems as though there's no reason to actually set the error code at all unless it's non-zero?
Let me know what the thoughts here are. I can come back in and add more, add some additional tests, etc if this looks like an ok change.
Thanks!
Pretty much just make sure that jest still reports a non-zero exit …
=> fix: only set error codes when they are non zero

CHANGELOG.md, docs/GettingStarted.md
fixes #7369
Explanation when jest set NODE_ENV environment variable was misleading.
Should now be cleared
no code changes made
=> Clearify conditional setting of NODE_ENV

CHANGELOG.md, e2e/__tests__/__snapshots__/show_config.test.js.snap, packages/jest-cli/src/cli/args.js, types/Argv.js
Fixes #7406 by setting default value of ``prettierPath`` to ``undefined``  in argv.  Also added ``prettierPath`` key to ``Argv`` type.
Updated snapshots
=> Fix: prettierPath not working via config file

CHANGELOG.md, docs/ExpectAPI.md
The example for a custom matcher 'message' property returns a string, it should be a function.
`Types of property 'message' are incompatible. Type 'string' is not assignable to type '() => string'` so updated accordingly
=> Fix Custom Matchers API example message property

docs/Architecture.md, website/sidebars.json
This adds the video discussing Jest's architecture to the "Guides" section of the docs. It's me, staring at your empty eyes as you try to grasp the silly architecture we came up with. Yay!
Looks like this:
=> Add Jest Architecture overview to docs.

CHANGELOG.md, packages/pretty-format/src/__tests__/prettyFormat.test.js, packages/pretty-format/src/collections.js
Fixes #7443
Breaking change for upcoming major upgrade to Jest 24
cc @austinalameda @mweststrate
Goals:
* Make snapshot tests consistent with `toEqual` matcher.
* Omit implementation details from formatted object instances (for example, jsdom element or MobX observable).
Added 2 test cases:
| before | after | description |
| :--- | :--- | :--- |
| passed | passed | prints an object without non-enumerable properties which have string key |
| failed | passed | prints an object without non-enumerable properties which have symbol key |
=> pretty-format: Omit non-enumerable symbol properties

CHANGELOG.md, docs/CLI.md
testPathIgnorePatterns exist as part of the [SearchSource](https://github.com/facebook/jest/blob/d5c74a2a6b62f50f3c54e322f8f4fa703d5c3393/packages/jest-cli/src/SearchSource.js#L72) but it is not documented. I provide a simple definition so people can use it.
=> Update CLI documentation

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/regression.md
Thank you @github https://blog.github.com/changelog/2018-12-05-issue-template-automation-improvements/
=> Add issue template labels

CHANGELOG.md, TestUtils.js, docs/CLI.md, docs/Configuration.md, docs/WatchPlugins.md, e2e/__tests__/__snapshots__/show_config.test.js.snap, packages/jest-cli/src/TestScheduler.js, packages/jest-cli/src/__tests__/TestScheduler.test.js, packages/jest-cli/src/cli/args.js, packages/jest-cli/src/lib/__tests__/__snapshots__/init.test.js.snap, packages/jest-cli/src/lib/update_global_config.js, packages/jest-config/src/Defaults.js, packages/jest-config/src/Descriptions.js, packages/jest-config/src/ValidConfig.js, packages/jest-config/src/normalize.js, packages/jest-validate/src/__tests__/fixtures/jestConfig.js, types/Argv.js, types/Config.js
Sometimes when running a full suite of tests there might be a config change (or some other failure) that leads to a catastrophic failure.  Instead of continuing to run the entire suite, have an early exit after say `15` failures, something must be seriously wrong so abort the run.
Typically in CI mode we'll want to try to let the tests run so we can see all the failures at one time (which is why bail is not quite enough).  But in the event of everything failing there's no need to continue running.  We had a case where a branch of code was generating 100GB worth of logs because of test failures, with this change it would have been able to early abort.
Unit tests
=> allow `bail` setting to control when to bail out of a failing test run

CHANGELOG.md, docs/CLI.md, packages/jest-config/src/__tests__/getMaxWorkers.test.js, packages/jest-config/src/getMaxWorkers.js
We have various machines in use between 4-16 threads but we always need to have spare threads available for other things like puppeteer/chrome. Doing this will allow simple `--maxWorkers=50%` to always have spare CPU available;
```
$ node ./packages/jest-cli/bin/jest.js getMaxWorkers.test.js
PASS  packages/jest-config/src/__tests__/getMaxWorkers.test.js
getMaxWorkers
√ Returns 1 when runInBand (3ms)
√ Returns 1 when the OS CPUs are not available (1ms)
√ Returns the `maxWorkers` when specified
√ Returns based on the number of cpus (1ms)
% based
√ 50% = 2 workers
√ < 0 workers should become 1 (1ms)
√ 0% shouldn't break
Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Time:        1.315s, estimated 2s
Ran all test suites matching /getMaxWorkers.test.js/i. …
```
=> Allow % based configuration of max workers

CHANGELOG.md, docs/CLI.md, e2e/__tests__/supports-dashed-args.js, packages/jest-cli/src/__tests__/cli/args.test.js, packages/jest-cli/src/cli/index.js, packages/jest-validate/package.json, packages/jest-validate/src/validateCLIOptions.js, yarn.lock
Fixes #7424.
Added tests & ran:
```sh
yarn build && yarn jest
```
=> Support dashed args

docs/TimerMocks.md, website/versioned_docs/version-22.0/TimerMocks.md, website/versioned_docs/version-22.2/TimerMocks.md, website/versioned_docs/version-22.3/TimerMocks.md, website/versioned_docs/version-23.0/TimerMocks.md
Fixes #7516.  Replaces a link to a slightly inappropriate video with a link to a different video.
Click the "Great Scott!" link on the Timer Mocks documentation page.
=> Docs: changed "Great Scott!" link

CHANGELOG.md, docs/Configuration.md, e2e/__tests__/test_environment_async.test.js, e2e/test-environment-async/TestEnvironment.js, packages/jest-environment-jsdom/src/index.js, packages/jest-runner/src/runTest.js, types/Environment.js
The [`testEnvironment`](https://jestjs.io/docs/en/configuration#testenvironment-string) feature enables a whole new suite of tests to be written with Jest.
However the following use case can present itself:
1. an application has an async setup with involves a connection task and a resource bootstrapping task (e.g. prepare some external resources).
2. the application's connection task is slow, but is safe to run several times (since it has already initialized connections to the external resources) - so running this in a `setupFiles` is less than optimal, as we would pay the price for this task on each test file
1. the application's bootstrap task needs to be configurable per test file - we currently don't have any option to do this.
1. the application's bootstrap task can not run in the …
=> Test environment gets current file path as option

CHANGELOG.md, packages/jest-cli/src/SnapshotInteractiveMode.js, packages/jest-cli/src/__tests__/SnapshotInteractiveMode.test.js, packages/jest-cli/src/__tests__/__snapshots__/SnapshotInteractiveMode.test.js.snap, packages/jest-cli/src/__tests__/__snapshots__/watch_filename_pattern_mode.test.js.snap, packages/jest-cli/src/__tests__/watch_filename_pattern_mode.test.js, packages/jest-cli/src/__tests__/watch_test_name_pattern_mode.test.js, packages/jest-cli/src/constants.js, packages/jest-cli/src/reporters/verbose_reporter.js, packages/jest-cli/src/watch.js, packages/jest-util/src/index.js, packages/jest-util/src/specialChars.js, packages/jest-watcher/package.json, packages/jest-watcher/src/PatternPrompt.js
`clearScreen` is quite aggressive and can e.g. brick the user's shell theme.
Better use `eraseScreen` and `cursorTo(0, 0)` instead.
Pattern prompts and interactive snapshot mode use `ansiEscapes.clearScreen`, which can sometimes clear more than it should - in this case the shell theme (note the background color changing from dark gray to black when pressing `p` in watch mode):
I can reproduce this behavior running bash & zsh inside [kitty](https://github.com/kovidgoyal/kitty) on macOS & Linux with the minimal [base16-shell](https://github.com/chriskempson/base16-shell) theming setup as described in its readme Installation/Configuration sections.
The combination of `eraseScreen` and `cursorTo(0, 0)` achieves the same goal as `clearScreen`, but does not exhibit its problems:
Open question: …
=> avoid ANSI clearScreen

packages/jest-each/src/bind.js
Array.push works faster than Array.concat for reduce.
I tested it with array (100 elements). In chrome it works more than 60x faster.
https://jsperf.com/reduce-concat-vs-reduce-push
=> [jest-each] Use array.push instead of array.concat

website/pages/en/index.js
This PR removes a stray logo from the homepage. I went back a year and it was never visible on the page, so just going to remove it.
=> Remove stray logo from homepage

CHANGELOG.md, packages/jest-resolve/src/isBuiltinModule.js
See #5855
@rubennorte could you make a new release with this?
Har to test since the newest versions of all the versions of node we support has the property. It _does_ work on older versions of node, though.
=> fix: handle builtinModules missing

README.md
I think it would be nice having a `Follow on Twitter` badge showing the current follower count redirecting to the corresponding Twitter page for `fbjest` :thinking: 
> It looks like this:
[![Twitter](https://img.shields.io/twitter/follow/code.svg?style=social&label=Follow)](https://twitter.com/intent/follow?screen_name=code)
=> Add follow on twitter badge 

CHANGELOG.md, e2e/__tests__/transform.test.js, e2e/transform/babel-jest/__tests__/changed_cwd.test.js, packages/babel-jest/src/index.js
Fixes #7438. See that for motivation
Test added
=> fix: set cwd in babel-jest

e2e/Utils.js, e2e/__tests__/__snapshots__/custom_matcher_stack_trace.test.js.snap, e2e/__tests__/__snapshots__/each.test.js.snap, e2e/__tests__/__snapshots__/empty-describe-with-hooks.test.js.snap, e2e/__tests__/__snapshots__/error-on-deprecated.test.js.snap, e2e/__tests__/__snapshots__/expect-async-matcher.test.js.snap, e2e/__tests__/__snapshots__/failures.test.js.snap, e2e/__tests__/__snapshots__/globals.test.js.snap, e2e/__tests__/__snapshots__/module_name_mapper.test.js.snap, e2e/__tests__/__snapshots__/resolve_no_file_extensions.test.js.snap, e2e/__tests__/__snapshots__/test-todo.test.js.snap, e2e/__tests__/__snapshots__/watch_mode_only_failed.test.js.snap, e2e/__tests__/__snapshots__/watch_mode_update_snapshot.test.js.snap, e2e/__tests__/failures.test.js, packages/jest-message-util/src/__tests__/__snapshots__/messages.test.js.snap, packages/jest-message-util/src/index.js, packages/pretty-format/src/__tests__/prettyFormat.test.js
Node 4 is unsupported by Jest since #4769. This PR removes leftover (mostly test) code that performs special handling if running in Node 4.
Updated snapshots now include more stack trace data, because stripping it out to make it consistent across Node 4 and 6+ is no longer necessary.
=> cleanup node 4 legacy code

CHANGELOG.md, e2e/__tests__/version.test.js, packages/jest-cli/src/cli/index.js
#7562 (cc @SimenB) used `__dirname.includes('packages/jest-cli')` to determine whether Jest is running from a local clone of the Jest project (as opposed to a regular node_modules installation). We found a cleaner solution than the `includes` there, but this gave me an idea for something else that could use this information: Indicating that Jest is running from a local clone when called with `--version`.
I often `yarn link` Jest into 10+ projects and probably do not always remember to unlink it afterwards. So if Jest behaves strangely, `yarn jest --version` telling me that it might be because I'm unintentionally running the local Jest clone would be nice (and more cross-platform than `realpath node_modules/jest-cli/`)
TODO how can we e2e test that it does NOT print `-dev` in a production …
=> print version ending in -dev when running a local Jest clone

docs/ExpectAPI.md, website/versioned_docs/version-22.0/ExpectAPI.md, website/versioned_docs/version-22.1/ExpectAPI.md, website/versioned_docs/version-22.2/ExpectAPI.md, website/versioned_docs/version-22.3/ExpectAPI.md, website/versioned_docs/version-23.0/ExpectAPI.md, website/versioned_docs/version-23.1/ExpectAPI.md, website/versioned_docs/version-23.2/ExpectAPI.md, website/versioned_docs/version-23.3/ExpectAPI.md, website/versioned_docs/version-23.4/ExpectAPI.md, website/versioned_docs/version-23.5/ExpectAPI.md, website/versioned_docs/version-23.6/ExpectAPI.md
> Closes #7577 
Present Issue
--------------
`toBeNan()` matcher was added in #1265 which was not documented.
Proposed solution
------------------
Added `toBeNaN()` along with other matchers to the docs.
=> Add toBeNaN matcher to docs

CHANGELOG.md, docs/ExpectAPI.md, packages/expect/src/__tests__/matchers.test.js, packages/expect/src/matchers.js, packages/expect/src/utils.js
Fixes the bug raised in https://github.com/facebook/jest/issues/7586.
Unit tests are included to cover the case.
=> fix: toStrictEqual considers array sparseness (resolves #7586)

CHANGELOG.md, e2e/__tests__/haste_map_size.test.js, packages/jest-cli/src/TestSequencer.js, packages/jest-cli/src/__tests__/test_sequencer.test.js, packages/jest-haste-map/src/HasteFS.js, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/constants.js, packages/jest-haste-map/src/crawlers/__tests__/node.test.js, packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js, packages/jest-haste-map/src/crawlers/node.js, packages/jest-haste-map/src/crawlers/watchman.js, packages/jest-haste-map/src/index.js, types/HasteMap.js
This PR adds a file size field to the haste map file metadata and exposes `hasteFS.getSize(path)`.
It also updates `TestSequencer` to use the file size data from the `hasteFS` instead of `statSync`ing on its own.
This will become more important if the number of file size checks increases because of #7553.
cc @SimenB @cpojer @rubennorte 
The "low-level" internals like HasteMap are pretty new to me, I'd appreciate a review from someone familiar with it who knows what implications this change could have :) e.g. what happens with existing serialized haste maps? Is this breaking?
And this will certainly need approval from someone from FB.
Added e2e test `haste_map_size` similar to `haste_map_sha1`. `TestSequencer` still works.
=> HasteFS file size

package.json, packages/jest-cli/package.json, packages/jest-haste-map/package.json, packages/jest-runner/package.json, packages/jest-runtime/package.json, packages/jest-util/package.json, yarn.lock
To include https://github.com/isaacs/node-graceful-fs/pull/137
Green CI
=> chore: upgrade graceful-fs to avoid mem leak

CHANGELOG.md, packages/jest-config/package.json, packages/jest-config/src/normalize.js, yarn.lock
See discussion in #7556.
Result: 
Previous result:
Does anyone think this might mess up somehow?
Not sure how to write a test for this.
=> fix: normalize rootDir and cwd to their realpath

packages/jest-cli/src/__tests__/SearchSource.test.js, packages/jest-resolve-dependencies/src/__tests__/dependency_resolver.test.js, packages/jest-runner/src/runTest.js, packages/jest-runtime/src/__mocks__/createRuntime.js, packages/jest-runtime/src/cli/index.js, packages/jest-runtime/src/index.js
`jest-runtime` was inadvertently migrated to export ESM in #7016 and it's actually a breaking change. This should have been part of #7602.
Current tests.
=> Migrate back to CommonJS export for jest-runtime

.circleci/config.yml, packages/jest-cli/src/TestSequencer.js, packages/jest-cli/src/lib/watch_plugins_helpers.js
Jest tests currently fail on Node 11, which is annoying because I (like probably many others) have Node 11 installed as their default environment on dev machines.
The test sequencer and watch mode usage are affected, both because Node 11 (via a v8 update) now has a stable `Array.sort`, revealing that our compareFunctions were inconsistent.
Tests that previously passed on Node 10 but failed on Node 11 now pass on both.
CI now runs the tests on Node 11 as well.
=> Fix tests on Node 11 and run them in CircleCI

website/static/css/custom.css
> This is in response to a minor tweak required as mentioned in #7265 
* Adjusted font sizes a bit
* Removed underline from the Jest-version header.
=> Navbar header fixes

e2e/__tests__/snapshot.test.js
My working directory is following.
`~/works/node.js/jest/`
Expect:
`yarn test` pass.
Actual:
`yarn test` fail.
`ENOENT: no such file or directory, open '~/works/node_copy.js/jest/e2e/snapshot/__tests__/snapshot.test.js'`
`yarn test` pass.
=> Fix tests does not pass in specific pass issue.

CHANGELOG.md, e2e/__tests__/env.test.js, e2e/env-test/__tests__/equivalent.test.js, packages/jest-environment-node/src/index.js
In node environment Buffer class buffer property become ArrayBuffer.
* Set ArrayBuffer to global.ArrayBuffer.
* Add tests.
In the following code.
```js
const bufFromArray = Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72]);
bufFromArray.buffer instanceof ArrayBuffer; // (A)
const bufFromArrayBuffer = Buffer.from(new ArrayBuffer(6));
bufFromArrayBuffer.buffer instanceof ArrayBuffer; // (B)
```
Execute in each environment.(`--env=node`, `--env=jsdom`, and `node`)
**Expect:**
- (A) and (B) are always true.
**Actual:**
- In `--env=node`, (A) is not true.
ref.
https://nodejs.org/api/buffer.html#buffer_buf_buffer
- The same results in all environments.
=> Fix buffer property is not ArrayBuffer issue.

packages/babel-jest/src/index.js, packages/jest-cli/src/SearchSource.js, packages/jest-cli/src/getNoTestFound.js, packages/jest-cli/src/getNoTestsFoundMessage.js, packages/jest-cli/src/lib/init/index.js, packages/jest-cli/src/runJest.js, packages/jest-resolve/src/index.js, packages/jest-runtime/src/cli/index.js, types/TestRunner.js, yarn.lock
More from #7556. There's quite a few places we access `cwd`, even though we have a `cwd` in `ProjectConfig` already. Instead of `realpath`ing them again, we should reuse the one from config.
Also consistently `realpath` `cwd` in the places where we don't have `config`.
/cc @willsmythe
Green CI
=> chore: make sure to call `realpath` when accessing `cwd`

.azure-pipelines-steps.yml, .azure-pipelines.yml, CHANGELOG.md, e2e/Utils.js, e2e/__tests__/hasteMapSize.test.js, e2e/runJest.js, packages/jest-cli/src/SearchSource.js, packages/jest-config/src/getCacheDirectory.js
As discussed in #7211, this PR is to add initial support for CI on Azure Pipelines across Mac, Windows, and Linux. Currently, Travis doesn't run master on Windows so there's a test gap.
This PR adds the azure-pipelines.yaml file to run test-ci-partial on the 3 OS's with Node 10. This PR can also be updated to run multiple versions of Node if that's desired. Some of the tests were updated as well.
The tests on Windows are currently failing. One appears to be path separator related and another fs.watch related (which can be finicky on Windows).
You can see the [output](https://willsmythe.visualstudio.com/jest/_build/results?buildId=323) of the fork @willsmythe set up. He also set up [test reporting](https://willsmythe.visualstudio.com/jest/_build/results?buildId=323&view=ms.vss-test-web.test …
=> chore: initial Azure Pipelines support

README.md
Scoped to the `master` branch.
This PR should automatically kick off a build in Azure Pipelines since #7556 was merged and the pipeline set up.
=> Add Azure Pipelines build badge

e2e/__tests__/__snapshots__/failures.test.js.snap, e2e/failures/__tests__/duringTests.test.js, examples/enzyme/__tests__/CheckboxWithLabel-test.js, examples/react/__tests__/CheckboxWithLabel-test.js, examples/snapshot/__tests__/clock.react.test.js, examples/snapshot/__tests__/link.react.test.js, package.json, packages/jest-environment-node/src/index.js, packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/jasmine/CallTracker.js, packages/jest-jasmine2/src/jasmine/ReportDispatcher.js, packages/jest-jasmine2/src/jasmine/SpyStrategy.js, packages/jest-jasmine2/src/jasmine/Timer.js, packages/jest-util/src/FakeTimers.js, packages/jest-util/src/__tests__/fakeTimers.test.js, packages/jest-worker/package.json, packages/jest-worker/src/index.js, packages/jest-worker/src/types.js, yarn.lock
=> chore: remove unused eslint disable comments

CHANGELOG.md, e2e/__tests__/babelPluginJestHoist.test.js, e2e/babel-plugin-jest-hoist/__tests__/typescript.test.ts, e2e/babel-plugin-jest-hoist/babel.config.js, e2e/babel-plugin-jest-hoist/entry.ts, e2e/babel-plugin-jest-hoist/package.json, e2e/babel-plugin-jest-hoist/types.ts, e2e/babel-plugin-jest-hoist/yarn.lock, packages/babel-plugin-jest-hoist/src/index.js
Closes #7634, fixes #7633 
Now that I've looked at the rest of babel-plugin-jest-hoist too, it's actually a lot easier.
My ugly stateful visitor ideas were nice and everything, but turns out we've already had this solved properly for Flow 🙈 
e2e test added by @SimenB, checked that it fails with babel-plugin-jest-hoist from master.
=> babel-plugin-jest-hoist: Ignore TS type annotations when looking for out-of-scope references

CHANGELOG.md, packages/jest-config/src/index.js
The previous code was calling `existsSync` by passing a `root` to it, which could either be a string or a Jest configuration object. The `existsSync` implementation currently accepts both, but this behavior is frowned upon and [might be deprecated](https://github.com/nodejs/node/blob/master/lib/fs.js#L221-L226) in later Node releases. This diff simply checks whether the root is a path before calling `existsSync` on it.
cc @rubennorte 
Not easy to test since it currently works even without the PR 😄
=> Stops calling existsSync on object configs

CHANGELOG.md, e2e/custom-resolver/package.json, e2e/global-setup/babel.config.js, e2e/global-setup/package.json, e2e/global-setup/projects.jest.config.js, e2e/global-setup/setup.js, e2e/global-teardown/package.json, e2e/global-teardown/projects.jest.config.js, packages/jest-cli/package.json, packages/jest-cli/src/runGlobalHook.js, yarn.lock
Fixes #5164. A caveat is that this can not transpile stuff in `node_modules`. This is because in order to transpile using e.g. `babel-jest`, we would need to load `babel-jest`, which means we cannot transpile it.
We _could_ try to do static analysis on the transformer modules defined in the config and create a dependency tree of the only files we won't transform, but I'm not sure if it's worth it (or possible). Stuff in `node_modules` should be runnable in node either way.
EDIT: If people want, we can disable `node-modules` ignoring, and try to catch errors during transform. By default, Jest has `transformIgnorePattern` on `node_modules`, so shouldn't make a huge difference
I added a flow annotation to an existing test to show the transform happens.
=> Run code transforms over `global{Setup,Teardown}`

docs/Configuration.md, website/versioned_docs/version-22.0/Configuration.md, website/versioned_docs/version-22.1/Configuration.md, website/versioned_docs/version-22.2/Configuration.md, website/versioned_docs/version-22.3/Configuration.md, website/versioned_docs/version-22.4/Configuration.md, website/versioned_docs/version-23.0/Configuration.md, website/versioned_docs/version-23.1/Configuration.md, website/versioned_docs/version-23.2/Configuration.md, website/versioned_docs/version-23.3/Configuration.md, website/versioned_docs/version-23.4/Configuration.md, website/versioned_docs/version-23.5/Configuration.md, website/versioned_docs/version-23.6/Configuration.md
Adds note that the `moduleFileExtensions` configuration evaluates the array of file extensions from left-to-right. This may seem self-evident, but personally after dealing with Webpack loaders which work in the opposite direction, I think it doesn't hurt to point out.
See issue #7563 for the original discussion on this matter. If someone is more knowledgable about performance, perhaps we could also add a note that in a TypeScript project, moving the `.ts` and `.tsx` extensions to the beginning could be advantageous (per @thymikee).
=> Update docs re: `moduleFileExtensions` to add ordering note (left-to-right)

CHANGELOG.md, packages/jest-mock/src/__tests__/jest_mock.test.js, packages/jest-mock/src/index.js
Fixes #7624 
Added one assertion for the name itself and
added one test case that should closely resembles #7624
=> Fix automock for numeric function names

website/blog/2017-12-18-jest-22.md, website/blog/2018-05-29-jest-23-blazing-fast-delightful-testing.md, website/blog/2018-06-27-supporting-jest-open-source.md
THey take unnecessary room currently in the lits: https://jestjs.io/blog/
Check netlify preview
=> add missing truncate comment to recent blog posts

CHANGELOG.md, e2e/__tests__/__snapshots__/failures.test.js.snap, packages/expect/package.json, packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap, packages/expect/src/matchers.js, packages/expect/src/spyMatchers.js, packages/jest-circus/package.json, packages/jest-circus/src/formatNodeAssertErrors.js, packages/jest-diff/src/__tests__/diff.test.js, packages/jest-diff/src/index.js, packages/jest-jasmine2/package.json, packages/jest-jasmine2/src/assertionErrorMessage.js, packages/jest-matcher-utils/package.json, packages/jest-matcher-utils/src/__tests__/index.test.js, packages/jest-matcher-utils/src/index.js
Currently, `jest-diff` returns `null` when diffing numbers or booleans (or `NO_DIFF_MESSAGE` if they are equal).
This is because the matchers that use jest-diff already print something like
```
Expected: 2
Received: 1
```
if they differ, so the jest-diff output would be redundant.
This behavior is unintuitive if you are using `jest-diff` for something other than Jest's test failure output.
I stumbled upon this trying to build a `diff`-like CLI for `jest-diff`.
It was also quite inexplicable to me when I first read the jest-diff code ("why does it just not do anything if a and b are numbers?"), so I think this piece of code needed clarification in general.
This PR changes jest-diff to behave like normal diffing by default, with an `omitTrivial` option that the matchers use to tell …
=> Jest diff numbers and booleans

e2e/__tests__/__snapshots__/customReporters.test.js.snap, e2e/__tests__/customReporters.test.js, website/blog/2018-05-29-jest-23-blazing-fast-delightful-testing.md
Our test data has been obsolete for [more than a year](https://twitter.com/fbjest/status/879057512749826048)! 😱
Uses more realistic names in our tests ;)
cc @aaronabramov
=> Name fixes

docs/SnapshotTesting.md
Replaces references to "images" and "screenshots" in the intro to snapshot testing.
I am new to snapshot testing and felt that this introductory paragraph was misleading by implying that the comparison is made between two images rather than two `snapshots` - text-based representations of the UI.
Snapshot testing does not use images or screenshots, as described in the docs [below](https://jestjs.io/docs/en/snapshot-testing#what-s-the-difference-between-snapshot-testing-and-visual-regression-testing). The use of these words can cause confusion between visual regression and snapshot testing for those unfamiliar with the difference.
Hope this can help avoid confusion for others coming to jest for the first time. Thanks!
n/a
=> Docs - Snapshot Testing - Remove references to `images` and `screenshots`

docs/GettingStarted.md
Some other docs cleanup as well.
=> docs: using Babel 6 with Jest 24

packages/jest-runtime/package.json, yarn.lock
EDIT: We can probably just bump the version instead, hopefully the PR will land really quick 🙂 https://github.com/npm/write-file-atomic/pull/37#issuecomment-456582603
~Due to `worker_threads` sharing `process.pid` with its parent, `write-file-atomic` doesn't really work when run inside a worker. See this example (using `jest-worker@24.0.0-alpha.12`):~
```js
// worker.js
const {default: Worker} = require('jest-worker');
const w = new Worker(require.resolve('./file'));
w.getStdout().pipe(process.stdout);
w.getStderr().pipe(process.stderr);
console.log('parent pid', process.pid);
Promise.all([w.hello(), w.hello(), w.hello(), w.hello(), w.hello()])
.catch(e => {
console.error(e);
})
.then(() => w.end());
```
```js
// file.js
module.exports.hello = () => console.log('child pid', process.pid); …
```
=> fix: upgrade `write-atomic-file` to support worker_threads

CHANGELOG.md, packages/jest-cli/src/reporters/coverage_reporter.js, packages/jest-haste-map/src/index.js, packages/jest-runner/src/index.js, packages/jest-worker/README.md, packages/jest-worker/src/WorkerPool.js, packages/jest-worker/src/__tests__/WorkerPool.test.js, packages/jest-worker/src/index.js, packages/jest-worker/src/types.js
There are certain issues around `worker_threads` (notably missing `process.umask`, which makes a few dependencies throw). While these issues are getting fixed (https://github.com/npm/write-file-atomic/pull/37 & https://github.com/nodejs/node/pull/25526) I think we should be on the safe side with Jest 24 and wait for the dust to settle before using it in Jest.
However, the default behavior is still to use it if available, this PR explicitly disables it in the places we use `jest-worker` internally.
Unit test added. This should also fix CI for node 11.
=> fix: add option to disable `worker_threads` in `jest-worker`

CHANGELOG.md, packages/expect/src/__tests__/utils.test.js, packages/expect/src/utils.js
`expect(object).toHaveProperty('foo')` throws if `'foo'` is an inherited property of `object` (not an own property or a getter in its prototype). According to the documentation, inherited properties should work as well.
Added unit test.
=> Fix toHaveProperty matcher for inherited properties

website/package.json, yarn.lock
I personally just want https://github.com/facebook/Docusaurus/pull/1193 in, as it looks really off in the current version 😅
https://github.com/facebook/Docusaurus/pull/1063 is fantastic though, maybe we could update our config snippets to be both js and json? Might be overkill
Huge lockfile change since they've removed `imagemin`, I'm not sure if it was in purpose? https://github.com/facebook/Docusaurus/pull/1162#issuecomment-457107798
Check netlify, looked good locally
=> chore: upgrade docusaurus

CHANGELOG.md, e2e/__tests__/__snapshots__/moduleNameMapper.test.js.snap, e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.js.snap, e2e/resolve/Test5.js, e2e/resolve/__mocks__/Test5.js, e2e/resolve/__mocks__/Test6.js, e2e/resolve/__tests__/resolve.test.js, e2e/resolve/hasteImpl.js, e2e/resolve/package.json, packages/jest-resolve/src/index.js, packages/jest-runtime/src/index.js
With the current implementation, mocks can be required by using `require('MyMockName')`, but `require.resolve` fails. This is because the resolver only checks for existence of a Haste name under the "module" map, but not under the "moduleMock" map.
This PR fixes it, by adding a secondary check after a Haste name, to ensure the proper Haste file is loaded if present.
=> Ensure mocks get resolved too

CHANGELOG.md, e2e/__tests__/__snapshots__/each.test.js.snap, e2e/each/__tests__/failure.test.js, packages/jest-each/package.json, packages/jest-each/src/__tests__/template.test.js, packages/jest-each/src/bind.js, yarn.lock
Closes: #7689
- Updated tests for this use case
=> [jest-each] Add primitive pretty printing

CHANGELOG.md, packages/expect/src/__tests__/__snapshots__/toThrowMatchers.test.js.snap, packages/expect/src/__tests__/toThrowMatchers.test.js, packages/expect/src/toThrowMatchers.js
Fixes #7692
* `Received message:` in report when assertion fails for any object which has a `message` prop
* Support **asymmetric matchers** as expected values that were broken in #7621
All existing tests pass
Added 8 tests and 4 snapshots for each of the following scenarios:
* asymmetric any-Class: `.toThrow(expect.any(Class))`
* asymmetric anything: `.toThrow(expect.anything())`
* asymmetric no-symbol: `.toThrow(customMatcher)`
* asymmetric objectContaining: `.toThrow(expect.objectContaing(props))`
* error-message: `expect(() => { throw { message: 'whatever'}; })`
This quote from original pull request still applies to **any-Class** scenario:
> Depending on how classes that extend Error set name property of instances, that report can still seem confusing, but I think that will have to …
=> expect: fix regression in toThrow for message prop and asymmetric matchers

CHANGELOG.md, website/pages/en/index.js
Currently the `Get Help` link is directing to https://jestjs.io/docs/en/help but should be going to https://jestjs.io/en/help.
=> [website]: Fix broken help link on homepage

.eslintrc.js, CHANGELOG.md, yarn.lock
Extracting the noisy parts of #7707 and #7714 into a separate PR
Green CI, this doesn't really change anything. We might consider running yarn with `--frozen-lockfile` on ci?
=> chore: run yarn after new release

CHANGELOG.md, e2e/__tests__/runProgramatically.test.js, e2e/run-programatically/index.js, packages/jest-cli/src/cli/index.js, packages/jest-cli/src/jest.js, packages/jest-cli/src/version.js
Fixes #7704
I tested it 😀 `node -p "require('jest').run(process.argv.slice(2))"` before and after this change
=> fix: break dependency cycle in jest-cli

CHANGELOG.md, packages/jest-config/src/__tests__/normalize.test.js, packages/jest-config/src/normalize.js
`setupFilesAfterEnv` config from preset is ignored according to #7719
Linked `jest` to https://github.com/sbekrin/jest-24-setup-files-after-env-bug and run tests.
=> First setup presets before options validation

.azure-pipelines-steps.yml, .circleci/config.yml, .flowconfig, .travis.yml, appveyor.yml
To ensure reproducible builds
Green CI
=> chore(ci): run yarn with `frozen-lockfile`

CHANGELOG.md, package.json, yarn.lock
Updates jest-junit to ^6.2.0.
jest-junit 6.2.0 removes the dependency on jest-config so it removes babel-core and babel-jest so it should reduce the install time and be more compatible with future releases.
This PR
=> Upgrade jest-junit to 6.2.0
