integration-tests/__tests__/jasmine_async.test.js, packages/jest-circus/package.json, packages/jest-circus/src/utils.js
see last commit only.
do we even need this? do people still use generators for flow control?
=> [jest-circus] generator based tests support

.circleci/config.yml, .travis.yml, CHANGELOG.md, package.json
Should speed up the feedback loop.
Blazing CI
=> Separate lint-and-typecheck from testing on CI

packages/jest-jasmine2/src/index.js, packages/jest-jasmine2/src/reporter.js
=> Don't pass unused environment variable

packages/jest-circus/src/utils.js, packages/jest-message-util/src/index.js, packages/jest-runtime/src/script_transformer.js
Tests + Flow
Similar to #6319
@aaronabramov @SimenB
=> Remove a few more unused variables

CHANGELOG.md
This PR fixes a number of broken pull request links in the CHANGELOG.md file.
N/A
=> Fix broken changelog links

CHANGELOG.md
=> Add changelog entry for #6350

e2e/transform-linked-modules/ignored/symlink.js
It was changed in this commit https://github.com/facebook/jest/commit/92563185b07611fb4eca6faaee02499416726a3d, probably in a rush.
CI green
=> Add symlink back to transform-linked-modules test

docs/WatchPlugins.md, website/versioned_docs/version-23.0/WatchPlugins.md
Hi 👋
I just made a custom watch plugin (thanks for adding this functionality!), and it took me a bit of hunting to find how to connect it up to Jest. Thought it worth adding to the docs?
P.S. If I have the method wrong, would love to hear if there's a better way to do it.
=> Update WatchPlugins.md with how to add watch plugin to config

docs/Configuration.md
Organize configuration properties alphabetically.
While working on #6403 I've noticed that some properties were misplaced.
=> organize the config alphabetically

docs/GettingStarted.md
=> minor grammatical point GettingStarted.md

.prettierignore
`package.json` is now formatted just like `JSON.stringify`, see [Prettier 1.13 Blog](https://prettier.io/blog/2018/05/27/1.13.0.html#added-json-stringify-parser-for-jsonstringify-style-formatting-4450-by-ikatyang).
Mess up `package.json` and <kbd>save</kbd> with `formatOnSave` enabled?
=> chore: remove unnecessary .prettierignore

README.md
Fixing the README to point to jestjs.io.
Tested the links on my [branch](https://github.com/RhysBower/jest/tree/jestjs).
=> Switch README to jestjs.io

website/pages/en/index.js
=> Fix open collective link

website/blog/2018-06-27-supporting-jest-open-source.md
=> Fix typo in open collective blog post

.circleci/config.yml
Node 9 was dropped from support this weekend.
https://github.com/nodejs/Release/blob/bc9d936e153b9fafd7f7c203f139d02035ca6862/schedule.json#L44
Still green CI
=> Stop testing on Node 9

website/versioned_docs/version-23.0/MongoDB.md
This pull request is regarding #6568 , This will fix the variable mismatch in mongoDB docs setup sample.
=> Website > Docs > mongoDB : Fixed the variable mismatch in the setup sample

website/pages/en/help.js
=> Fix broken url in help.js

docs/Configuration.md, website/versioned_docs/version-23.0/Configuration.md
This pull request closes #6595 
Unnecessary.
=> Add reference to <rootDir> in setupTestFrameworkScriptFile docs

packages/jest-resolve/src/index.js
Absolut is a swedish vodka brand.
=> Fix typo in _getAbsolutPath

.circleci/config.yml, .github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/regression.md, .travis.yml, appveyor.yml, crowdin.yaml, docs/Webpack.md, website/versioned_docs/version-22.0/Webpack.md, website/versioned_docs/version-22.1/Webpack.md, website/versioned_docs/version-22.2/Webpack.md, website/versioned_docs/version-22.3/Webpack.md, website/versioned_docs/version-22.4/Webpack.md, website/versioned_docs/version-23.0/Webpack.md, yarn.lock
Upgrades prettier to a version supporting yaml, it only changed indentation and quotation. No changes to JS, which is awesome.
Green CI
=> Upgrade prettier

CHANGELOG.md, packages/jest-config/src/normalize.js
=> Fix incorrect testEnvironmentOptions warning

docs/TestingFrameworks.md
Added an article to show how to use jest to test an Express.js app.
Just updated the documentation. No tests required.
=> Add Express.js jesting section.

docs/SnapshotTesting.md
=> Grammar fixes

jest.config.ci.js, package.json, yarn.lock
`useDots: true` is way nicer than messing with environment variables.
CI should still have dots for progress
=> chore: use useDots option in silent reporter

docs/TestingAsyncCode.md
According to https://github.com/facebook/jest/pull/4884
=> docs: fix `rejects.toMatch` on `rejects.toThrow`

docs/Configuration.md, website/versioned_docs/version-22.0/Configuration.md, website/versioned_docs/version-22.1/Configuration.md, website/versioned_docs/version-22.2/Configuration.md, website/versioned_docs/version-22.3/Configuration.md, website/versioned_docs/version-22.4/Configuration.md, website/versioned_docs/version-23.0/Configuration.md, website/versioned_docs/version-23.1/Configuration.md, website/versioned_docs/version-23.2/Configuration.md, website/versioned_docs/version-23.3/Configuration.md, website/versioned_docs/version-23.4/Configuration.md, website/versioned_docs/version-23.5/Configuration.md, website/versioned_docs/version-23.6/Configuration.md
This corrects a small grammar error in the docs.
=> Fix small grammar error in docs

website/core/Footer.js
Lefotver from #6163, I think? It currently 404s
=> chore(website): remove link to users from footer

yarn.lock
Yarn 1.10 (now stable) has added an integrity field
N/A
=> chore: update lockfile with integrity field

website/static/css/jest.css
This line is no longer needed
Tested locally
=> Fix help page centering

package.json, packages/jest-cli/package.json, yarn.lock
=> chore: upgrade strip-ansi

CHANGELOG.md
This PR fixes a broken pull request link in the CHANGELOG.md file.
N/A
=> Fix broken changelog link

CHANGELOG.md, e2e/__tests__/__snapshots__/timeouts.test.js.snap, e2e/__tests__/timeouts.test.js, packages/jest-circus/src/event_handler.js, packages/jest-circus/src/run.js, packages/jest-circus/src/utils.js, packages/jest-jasmine2/src/__tests__/p_timeout.test.js, packages/jest-jasmine2/src/p_timeout.js, packages/jest-jasmine2/src/queue_runner.js
Building on #6950, this adds an e2e test and the requested circus fix.
closes #6947
To Do:
The e2e test is failing and I'm having trouble figuring out why, so I'd like to see if it fails on CI too.
=> Fix synchronous timeouts

packages/jest-cli/src/getChangedFilesPromise.js
=> Fix filter to exclude empty lines

packages/jest-snapshot/src/index.js
Minor refactoring. `map` without `return` looks very strange.
Used `forEach` instead of `filter->map`.
=> Optimize refactoring cleanup files

packages/jest-jasmine2/src/tree_processor.js
Just simplified `if` branches.
=> Simplify checking hasEnabledTest

docs/Configuration.md, website/versioned_docs/version-22.0/Configuration.md, website/versioned_docs/version-22.1/Configuration.md, website/versioned_docs/version-22.2/Configuration.md, website/versioned_docs/version-22.3/Configuration.md, website/versioned_docs/version-22.4/Configuration.md, website/versioned_docs/version-23.0/Configuration.md, website/versioned_docs/version-23.1/Configuration.md, website/versioned_docs/version-23.2/Configuration.md, website/versioned_docs/version-23.3/Configuration.md, website/versioned_docs/version-23.4/Configuration.md, website/versioned_docs/version-23.5/Configuration.md, website/versioned_docs/version-23.6/Configuration.md
Just a minor JSON error on configuration document.
=> Docs: fix JSON in Configuration.md

e2e/each/__tests__/describe-only.test.js, e2e/each/__tests__/each-only.test.js, yarn.lock
Noticed it failing on the babel 7 PR after clearing out the lockfile. Can land separately
Green CI
=> chore: upgrade eslint plugin

packages/expect/src/matchers.js
Reduce the count of `getType` calls
=> Remove needless getType call in matches

website/versioned_docs/version-22.0/GettingStarted.md, website/versioned_docs/version-22.0/TutorialAsync.md, website/versioned_docs/version-22.1/GettingStarted.md, website/versioned_docs/version-22.2/GettingStarted.md, website/versioned_docs/version-22.2/TutorialAsync.md, website/versioned_docs/version-22.3/GettingStarted.md, website/versioned_docs/version-22.3/TutorialAsync.md, website/versioned_docs/version-22.4/GettingStarted.md, website/versioned_docs/version-23.2/GettingStarted.md, website/versioned_docs/version-23.5/TutorialAsync.md
Babel changed its Domain to https. Old http link is not being redirected to the new one.
Closes #7178
=> Babel https link update in multiple doc files

e2e/override-globals/setup.js
=> Adding copyright headers to e2e/override-globals/setup.js

CHANGELOG.md, docs/Configuration.md, website/versioned_docs/version-23.5/Configuration.md, website/versioned_docs/version-23.6/Configuration.md
Adds correct default `testUrl` parameter to docs
=> Add correct testURL default in docs

docs/JestObjectAPI.md
Came up in #5171. I've just rearranged, fixed some dead and missing links in the "methods" section, and added the headers.
Check out the netlify deploy
=> chore(docs): re-arrange Jets object docs into sections

CHANGELOG.md, docs/MockFunctions.md
Remove duplicate code
The duplicate code confuses users.
=> Remove duplicate

.flowconfig, package.json, packages/expect/src/jasmineUtils.js, packages/jest-cli/src/lib/__tests__/init.test.js, packages/jest-cli/src/reporters/verbose_reporter.js, packages/jest-config/src/normalize.js, packages/jest-snapshot/src/__tests__/inline_snapshots.test.js, packages/jest-watcher/src/lib/format_test_name_by_pattern.js, packages/pretty-format/src/__tests__/react.test.js, types/Matchers.js, types/TestResult.js, yarn.lock
Been a while since the last update.
Flow should pass
=> feat: upgrade Flow to 0.85.0

README.md
Add PR welcoming badge to the ``` README ``` file
=> Add PR welcoming badge

docs/GettingStarted.md
Minor doc edit. The page starts out with both `yarn` and `npm` language for install, so it should contain both commands when it comes time to run. Unsure about further commands in the page though.
Minor doc edit only!
=> include npm command in addition to yarn command

docs/TutorialReact.md
- TutorialReact.md
before:
Another option is to swizzling console.warn and **supress** specific warnings.
after:
Another option is to swizzling console.warn and **suppress** specific warnings.
=> Fix typo in docs.

website/package.json, yarn.lock
Update Docusaurus dependency
Fix #7439 
```
cd website
yarn
yarn start
```
=> chore: update docusaurus to v1.6.0

e2e/__tests__/failures.test.js
CI has been failing lately. Node 8.13 came with some `assert` changes (https://github.com/nodejs/node/pull/23223), one of which broke one of our assertions.
Green CI
=> chore: fix failures e2e test for node 8

packages/jest-resolve-dependencies/src/index.js
Removed filter + map and use single reduce.
Reason: it works 2x faster
=> Use reduce instead of filter+map in dependency_resolver

CHANGELOG.md, packages/jest-cli/src/getNoTestFound.js, packages/jest-cli/src/getNoTestFoundVerbose.js
We've gotten some issue here and there about it, thoughts on advertising the flag in the message?
Docs: https://jestjs.io/docs/en/cli#passwithnotests
=> chore: print info about passWithNoTests flag

e2e/runJest.js, packages/expect/src/matchers.js, packages/jest-snapshot/src/index.js, packages/jest-worker/src/__tests__/Farm.test.js, website/versioned_docs/version-23.0/MockFunctionAPI.md, website/versioned_docs/version-23.1/MockFunctionAPI.md
before:
**the the**
after:
**the**
=>  Remove duplicate 'the'.

docs/MongoDB.md
=> fix: test code does not work

docs/MongoDB.md, website/versioned_docs/version-22.3/MongoDB.md, website/versioned_docs/version-23.0/MongoDB.md, website/versioned_docs/version-23.2/MongoDB.md
The repo (and user) for the mongodb example doesn't exist anymore
Keeping the docs up to date
No code added
=> Removed dead link

website/static/css/custom.css
This PR is in response to a minor suggestion as requested in #7576 
Corresponding issue: #7265 
> Adjusted styling so that the Navbar header elements are better aligned.
=> website: Minor styling fix

packages/jest-circus/src/run.js, packages/jest-cli/src/lib/init/questions.js
=> Code Refactor and typo

docs/Configuration.md, website/versioned_docs/version-22.0/Configuration.md, website/versioned_docs/version-22.1/Configuration.md, website/versioned_docs/version-22.2/Configuration.md, website/versioned_docs/version-22.3/Configuration.md, website/versioned_docs/version-22.4/Configuration.md, website/versioned_docs/version-23.0/Configuration.md, website/versioned_docs/version-23.1/Configuration.md, website/versioned_docs/version-23.2/Configuration.md, website/versioned_docs/version-23.3/Configuration.md, website/versioned_docs/version-23.4/Configuration.md, website/versioned_docs/version-23.5/Configuration.md, website/versioned_docs/version-23.6/Configuration.md
As mentioned in #7670
Docs only
=> document how to get a newer version of jsdom

docs/Configuration.md, website/versioned_docs/version-22.0/Configuration.md, website/versioned_docs/version-22.1/Configuration.md, website/versioned_docs/version-22.2/Configuration.md, website/versioned_docs/version-22.3/Configuration.md, website/versioned_docs/version-22.4/Configuration.md, website/versioned_docs/version-23.0/Configuration.md, website/versioned_docs/version-23.1/Configuration.md, website/versioned_docs/version-23.2/Configuration.md, website/versioned_docs/version-23.3/Configuration.md, website/versioned_docs/version-23.4/Configuration.md, website/versioned_docs/version-23.5/Configuration.md, website/versioned_docs/version-23.6/Configuration.md
Current docs got out of sync with versioned docs because my #7673 review suggestion was applied to the versioned docs but not the current.
@SimenB
=> sync doc versions on jsdom configuration

website/siteConfig.js
Gives a litte share button on blog posts. Not sure what else it does (it's supposed to stick a link into the footer, but we have a custom one)
(Did not turn on fb comments)
Check netlify
=> add twitter links

CHANGELOG.md, packages/jest-cli/src/reporters/coverage_reporter.js, packages/jest-haste-map/src/index.js, packages/jest-runner/src/index.js, packages/jest-worker/README.md, packages/jest-worker/src/WorkerPool.js, packages/jest-worker/src/__tests__/WorkerPool.test.js, packages/jest-worker/src/__tests__/thread-integration.test.js, packages/jest-worker/src/index.js, packages/jest-worker/src/types.js
As discussed, a follow-up to #7681
Tests and docs tweaked
=> make worker_threads opt-in, not opt-out

website/pages/en/index.js
This fixes a typo in the website's features (isolated) section.
=> Fix typo in website's features (isolated) section

website/pages/en/index.js
I usually try not to be pedantic, but since it's placed so prominently on the landing page:
#7721 improved the phrasing, but looks like in order to make it [correct English](https://english.stackexchange.com/a/15371), we would have to use "in parallel" (which is weird because of double "in") or "parallelly" (which is so rare that my browser considers it a typo 😅).
This would be my suggestion to rephrase it :)
=> Rephrase "isolated" section on the landing page

jest.config.js, package.json, website/package.json, yarn.lock
Some opportunities for cleanup that messing around with Yarn pnp in #7726 has revealed and @SimenB pointed out
=> dependency and resolution cleanup

docs/MockFunctions.md, website/versioned_docs/version-23.x/MockFunctions.md, website/versioned_docs/version-24.0/MockFunctions.md
Refactored the example code in the **Mocking Modules** section to fix a reference to a non-existing variable.
=> docs: Fix example code in MockFunctions.md

docs/ExpectAPI.md, website/versioned_docs/version-23.x/ExpectAPI.md, website/versioned_docs/version-24.0/ExpectAPI.md
This pr just fixes a broken document link.
=> Fix broken link for inline snapshots

docs/Puppeteer.md, website/versioned_docs/version-22.x/Puppeteer.md, website/versioned_docs/version-23.x/Puppeteer.md, website/versioned_docs/version-24.0/Puppeteer.md
=> Addressing malfunctioning code snippet.

.github/ISSUE_TEMPLATE/question.md, docs/CLI.md, website/versioned_docs/version-22.x/CLI.md, website/versioned_docs/version-23.x/CLI.md, website/versioned_docs/version-24.0/CLI.md, website/versioned_docs/version-24.1/CLI.md
Fixes #7743 
Show a JSON structure that shows what structure --json --outputFile=<filename> has
The PR only affects the docs as indicated in the screenshot below, it was tested on a local machine
=> Update version docs

packages/pretty-format/src/index.ts
I think we should use `symbol`
=> Use symbol instead of Symbol

packages/jest-jasmine2/src/index.js
=> Typo fix in code comment

package.json, packages/pretty-format/src/__tests__/setPrettyPrint.ts, yarn.lock
Allows us to remove an ignore
Green CI
=> chore: upgrade @types/jest

packages/jest-cli/src/lib/__tests__/__snapshots__/init.test.js.snap, packages/jest-config/src/Descriptions.js
Fix small typo in jest config initialization comment
=> Fix typo in config init

packages/jest-worker/src/index.ts
=> Align readme

.eslintrc.js, packages/jest-phabricator/src/index.ts, packages/jest-types/package.json, packages/jest-types/src/TestResult.ts
They are more correct (see changed code), and less maintenance for us. Could have been part of #7965 when I tweaked the types, but I didn't think that far.
Green CI
=> chore: remove custom coverage typings

CHANGELOG.md, website/static/landing.js
[Jest front page](https://jestjs.io) has a console.log, which is useless for general production purposes.
This pull request deletes console log from the front page:
=> Remove console.log from the front page

CHANGELOG.md, e2e/__tests__/runProgrammatically.test.ts, e2e/run-programmatically/babel.config.js, e2e/run-programmatically/cjs.js, e2e/run-programmatically/esm.js, packages/jest-cli/src/index.ts
=> export functions compatible with `import jest from 'jest'`

.github/ISSUE_TEMPLATE/bug.md
Adjust labels in bug template to make our lives easier. No changelog :P
Tested on my fork: https://github.com/thymikee/jest/issues/new/choose
=> chore: improve bug template labels for easier maintenance

docs/ExpectAPI.md, website/versioned_docs/version-22.x/ExpectAPI.md, website/versioned_docs/version-23.x/ExpectAPI.md, website/versioned_docs/version-24.0/ExpectAPI.md
=> less React-focused snapshot docs

scripts/buildTs.js
=> fix buildTs on Windows using npm-which

CONTRIBUTING.md
Might decrease the number of docs PRs where we have to ask for also changing the `versioned_docs` by a little bit :)
=> contributing: `versioned_docs`

docs/MigrationGuide.md
_This is my first and probably only contribution to this repo. Hope this helps._
=> Update link to ShouldJS repo

packages/jest-each/README.md
Fix minor typo in test.skip snippet for jest-each
=> Fix typo in test.skip snippet for jest-each

CHANGELOG.md, packages/expect/src/__tests__/utils.test.js, packages/expect/src/utils.ts
Hopefully fix #8259 
Added negative cases outlined in revert and added a few extras
=> [expect] Add negative equality tests

docs/Configuration.md, website/versioned_docs/version-22.x/Configuration.md, website/versioned_docs/version-23.x/Configuration.md, website/versioned_docs/version-24.0/Configuration.md, website/versioned_docs/version-24.1/Configuration.md, website/versioned_docs/version-24.6/Configuration.md
=> Fix link example default jasmine2 test runner package.

docs/MigrationGuide.md, website/versioned_docs/version-22.x/MigrationGuide.md, website/versioned_docs/version-24.6/MigrationGuide.md
simplifies it down to one step, is less invasive because it'll clean up once it's done, and can guarantee that the user will always get 'latest' version if not locally installed/pinned.
I tried it locally and it seemed to work? You can try yourself by just running `npx jest-codemods`
=> use the npx version of jest-codemods in documentation

e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap, e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap, packages/jest-reporters/src/__tests__/summary_reporter.test.js, packages/jest-reporters/src/summary_reporter.ts, packages/jest-resolve/src/index.ts
Cache some env variables from `process.env` to avoid needless system call
=> Cache env in reporter

packages/jest-util/src/__tests__/createProcessObject.test.ts, packages/jest-util/src/createProcessObject.ts
Current implementation of the `Proxy for process.env` is very heavy because of win32 checking inside methods for each `delete`, `get` action.
current implementation for delete property with support for both 'win32' and 'not win32' platforms
```ts
deleteProperty(_target, key) {
for (const name in real) {
if (real.hasOwnProperty(name)) {
if (typeof key === 'string' && process.platform === 'win32') {
// Linux and MacOS will never get here
if (name.toLowerCase() === key.toLowerCase()) {
delete real[name];
delete lookup[name.toLowerCase()];
}
} else {
if (key === name) {
delete real[name];
delete lookup[name];
}
}
}
}
return true;
}
```
For `not win32` we can use simple implementation without `for loop`:
```ts
deleteProperty(_target: any, key: any) {
delete real[key];
delete lookup[key]; …
```
=> [jest-util] optimize proxy env

packages/jest-each/README.md
=> [jest-each] Update "Importing" section of the doc

docs/TimerMocks.md
The missing apostrophe was bugging me :P
Just a typo/grammar fix in the docs for timer mocks.
I channelled my inner Englishman and peered at the screen. Seems alright, guvna.
=> docs: s/Times/Time's

packages/jest-config/src/normalize.ts, packages/jest-config/src/utils.ts
Adjusted typing's for _replaceRootDirTags and fix related issue in `normalize.ts`.
Note: did change functionality in `_replaceRootDirInObject`, (not used anywhere else and not exported) , i moved the null check within `_replaceRootDirTags` to simplify typings.
See: #8436
No compile errors
=> chore(jest-config): util types

website/package.json, yarn.lock
=> chore: bump docusaurus

docs/MockFunctions.md, website/versioned_docs/version-23.x/MockFunctions.md, website/versioned_docs/version-24.0/MockFunctions.md
=> Mocking Modules Demo code bug fix

packages/jest-leak-detector/README.md
=> doc: Fix usage

docs/Configuration.md, website/versioned_docs/version-24.1/Configuration.md, website/versioned_docs/version-24.6/Configuration.md
[docs] added defaultResolver as one of the options passed to resolver in config.
No code change, just docs
=> [docs] add defaultResolver as one of the options passed to resolver.

website/fetchSupporters.js, website/pages/en/index.js
The current endpoint used is old and deprecated. See: https://github.com/opencollective/opencollective/issues/2037
This PR update to a new REST endpoint that is linked to the Open Collective GraphQL API v2.
This is supported by the Open Collective Engineering team, so happy to help if there is any problem with the endpoint or the data returned.
=> Update Open Collective API

package.json, packages/jest-changed-files/src/index.ts, packages/jest-circus/src/utils.ts, packages/jest-core/src/SearchSource.ts, packages/jest-core/src/TestScheduler.ts, packages/jest-haste-map/src/HasteFS.ts, packages/jest-haste-map/src/lib/dependencyExtractor.ts, packages/jest-jasmine2/src/errorOnPrivate.ts, packages/jest-mock/src/index.ts, packages/jest-types/src/Circus.ts, packages/jest-util/src/deepCyclicCopy.ts, yarn.lock
We're one minor behind. Not that it makes much difference 🙂 
Green CI
=> chore: bump TypeScript version

docs/Configuration.md, website/versioned_docs/version-24.0/Configuration.md, website/versioned_docs/version-24.1/Configuration.md, website/versioned_docs/version-24.6/Configuration.md, website/versioned_docs/version-24.8/Configuration.md
As the title.
Tested with `yarn start` in website.
before:
<kbd><img width="429" border=1 alt="before" src="https://user-images.githubusercontent.com/1908099/60357493-b5185080-9a0e-11e9-94c8-30d9a9c91fe8.png"></kbd>
after:
<kbd><img width="416" alt="after" src="https://user-images.githubusercontent.com/1908099/60357492-b5185080-9a0e-11e9-8f8e-08f96e26bd39.png"></kbd>
=> docs: Fix breaking markdown syntax.

.yarnrc
Getting an outdated warning is annoying
Green CI
=> chore: upgrade yarn

website/pages/en/index.js
Updates the jest usage stats on the website.
Fixes #8635
N/A
=> chore: update jest usage stats on the website

README.md
Include Table of Contents for better navigation experience.
=> feat(docs): Add Table of Contents

CONTRIBUTING.md
Documenting some stuff I ran into for my first contribution to save other newbs the trouble 🙂 
I'm not super familiar with jest contribution, so if this stuff is off-base let me know of course~
No code changes, just documentation.
=> Contrib instructs tweaks:Node version, `yarn jest`

.yarnrc
https://yarnpkg.com/blog/2019/07/12/recommended-security-update/
Green CI
=> chore: bump yarn

packages/jest-cli/package.json, packages/jest-cli/src/cli/args.ts, packages/jest-repl/package.json, packages/jest-runtime/package.json, packages/jest-types/package.json, packages/jest-watcher/package.json, yarn.lock
=> chore: bump yargs

docs/TutorialReact.md, website/versioned_docs/version-23.x/TutorialReact.md, website/versioned_docs/version-24.0/TutorialReact.md, website/versioned_docs/version-24.8/TutorialReact.md
Documentation fix for #7437
- `Another option is to swizzling console.warn` updated to `Another option is to swizzle the console.warn`
- `supress` typo updated to `suppress`
Not Applicable due to only markdown files are updated.
=> Issue 7437  documention update

packages/jest-core/README.md
=> Fix typeo in readme

packages/expect/src/__tests__/toThrowMatchers.test.js
Found some tests that were not correctly testing the right `expect` function.
n/a
=> fix(expect): test with current version of expect

e2e/browser-support/browserTest.js
=> chore: rely on browser field for browser tests

docs/Configuration.md, website/versioned_docs/version-24.0/Configuration.md, website/versioned_docs/version-24.1/Configuration.md, website/versioned_docs/version-24.6/Configuration.md, website/versioned_docs/version-24.8/Configuration.md
The `testRegex` section id in `Configuration.md` changed in 24+ since it can take an array now too.
Updated broken links accordingly.
=> chore(config.md): correct links to testRegex

website/versioned_docs/version-24.8/CLI.md
https://github.com/facebook/jest/pull/8456#issuecomment-517660665
=> remove unreleased `--testTimeout` feature from versioned_docs

CONTRIBUTING.md
This makes a one-word grammatical fix.
Before this change:
After:
[CONTRIBUTING.md](https://github.com/facebook/jest/blob/master/CONTRIBUTING.md#changelog-entries) says to update CHANGELOG.md for "significant changes to the documentation," so it is not updated for this PR.
=> Fix grammar: "a known issues"->"a known issue"

.github/ISSUE_TEMPLATE/bug.md
people not often remove placeholders from templates
=> bug.md: highlights placeholder should be removed

package.json, yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/
Green CI
=> chore: bump to TS 3.6

examples/timer/__tests__/infinite_timer_game.test.js
It fixes a typo: "it's" is a contraction for "it is" whereas "its" is possessive.
n/a
=> docs: fix typo comment

docs/ManualMocks.md, website/versioned_docs/version-22.x/ManualMocks.md, website/versioned_docs/version-23.x/ManualMocks.md
Just add a link to make navigation simpler.
=> docs: Setup a link for requireActual method

packages/jest-fake-timers/package.json, yarn.lock
no changelog as the current version hasn't been published
green ci
=> chore: bump lolex to v5

docs/Es6ClassMocks.md, docs/TutorialAsync.md, packages/pretty-format/README.md, website/versioned_docs/version-22.x/TutorialAsync.md, website/versioned_docs/version-23.x/Es6ClassMocks.md, website/versioned_docs/version-23.x/TutorialAsync.md, website/versioned_docs/version-24.0/Es6ClassMocks.md, website/versioned_docs/version-24.0/TutorialAsync.md
A continuation of #9040. All of the credit goes to @thymikee, I just put it in a PR 😄 
Only word changes, so as long as the documentation still builds and renders - I'd say we're good.
=> Docs: More inclusive wording

docs/MockFunctions.md
The documentation seems to be outdated. Or at least it is conflicting with the current state of the expectations documentation.
Update mock functions guide to use the current expectations.
None? Maybe the code in docs should be automatically tested, so that it can not go out of sync with the implementation 🤷‍♂ But if so, that would be out of scope for this PR.
=> doc: Update mock expectations

packages/jest-reporters/src/coverage_reporter.ts, packages/jest-types/src/Config.ts
- Improve typespec of CoverageThreshold
=> Improve coverage threshold value

website/pages/en/index.js
=> Update wording on website homepage

README.md
nitpicking
A small grammatical adjustment, but I figured I should contribute it if I found it.
=> docs: add missing commas

package.json, packages/jest-core/package.json, packages/jest-haste-map/package.json, packages/jest-runner/package.json, packages/jest-runtime/package.json, packages/jest-source-map/package.json, packages/jest-transform/package.json, yarn.lock
Created by `yarn upgrade graceful-fs`.\
This PR closes #9062
Run linter and test suite.
=> fix: update graceful-fs to 4.2.3

README.md, docs/GettingStarted.md, website/versioned_docs/version-22.x/GettingStarted.md, website/versioned_docs/version-23.x/GettingStarted.md, website/versioned_docs/version-24.0/GettingStarted.md, website/versioned_docs/version-24.6/GettingStarted.md
Updates links to webpack docs to the "new" webpack page
=> Update link to webpack docs

.azure-pipelines-steps.yml, .circleci/config.yml, .travis.yml, package.json
To make the script easier to run (also for CITGM)
Green CI, and only running TS build on the typecheck build, not the others
=> chore: move "quick-install" to npm script

packages/jest-transform/src/types.ts
Set method `getCacheKey` as optional in types.
=> jest-transform: Fix optional type for getCacheKey in transform

packages/jest-cli/package.json, packages/jest-repl/package.json, packages/jest-runtime/package.json, packages/jest-watcher/package.json, yarn.lock
Just dropping node 6. https://github.com/yargs/yargs/releases/tag/v15.0.0
Green CI
=> chore: upgrade to yargs 15

packages/jest-reporters/src/index.ts
I'm trying to write a reporter outside of this repo, and these types are really needed in order to avoid the extra dependencies
Green CI (it's just extra type exports 🤷‍♂)
=> chore: export extra types from @jest/reporters

docs/MockFunctions.md, website/versioned_docs/version-22.x/MockFunctions.md, website/versioned_docs/version-23.x/MockFunctions.md, website/versioned_docs/version-24.0/MockFunctions.md
=> return wrong

packages/jest-core/src/getChangedFilesPromise.ts
Little optimization of collection array of roots. I used push instead of creating new object each itaretion.
https://jsperf.com/jest-roots-reduce-spread
=> Optimize collect array of roots

package.json, packages/expect/package.json, packages/jest-snapshot/src/__tests__/printSnapshot.test.ts, packages/pretty-format/package.json, packages/pretty-format/src/__tests__/ConvertAnsi.test.ts, packages/pretty-format/src/index.ts, packages/pretty-format/src/plugins/ConvertAnsi.ts, packages/test-utils/package.json, packages/test-utils/src/alignedAnsiStyleSerializer.ts, yarn.lock
It comes with its own types now.
/cc @pedrottimark probably conflicts with your PR
Green CI
=> chore: bump ansi-styles

packages/jest-circus/src/eventHandler.ts, packages/jest-circus/src/run.ts, packages/jest-circus/src/utils.ts, packages/jest-haste-map/package.json, packages/jest-haste-map/src/index.ts, yarn.lock
=> chore: type invariant as assert function

docs/TestingFrameworks.md
Update TestingFrameworks.md For Hapi.js
=> docs: add Hapi.js article to "Testing Frameworks"

CONTRIBUTING.md
Mentioned in https://github.com/facebook/jest/pull/9278#discussion_r355124236 by @SimenB.
Add section in `CONTRIBUTING.md` about alphabetical order in `CHANGELOG.md`
N/A
---
Should I add this PR in CHANGELOG? 🤔
=> Add section about alphabetical order in CHANGELOG

docs/Configuration.md, website/versioned_docs/version-22.x/Configuration.md, website/versioned_docs/version-23.x/Configuration.md, website/versioned_docs/version-24.0/Configuration.md, website/versioned_docs/version-24.1/Configuration.md, website/versioned_docs/version-24.6/Configuration.md, website/versioned_docs/version-24.8/Configuration.md, website/versioned_docs/version-24.9/Configuration.md
=> docs: Updated misleading description in documentation

CONTRIBUTING.md
Added info about how to contribute in docs translation
The Contributions.md does't had info about where to make translations
Closes #9120
=> How to translate docs

e2e/__tests__/__snapshots__/coverageRemapping.test.ts.snap, e2e/async-regenerator/yarn.lock, e2e/babel-plugin-jest-hoist/yarn.lock, e2e/coverage-remapping/package.json, e2e/coverage-remapping/yarn.lock, e2e/coverage-report/yarn.lock, e2e/expect-async-matcher/yarn.lock, e2e/failures/yarn.lock, e2e/global-setup/yarn.lock, e2e/global-teardown/yarn.lock, e2e/stack-trace-source-maps/package.json, e2e/stack-trace-source-maps/yarn.lock, e2e/transform/babel-jest-manual/yarn.lock, e2e/transform/babel-jest/yarn.lock, e2e/transform/multiple-transformers/yarn.lock, e2e/transform/transformer-config/yarn.lock, e2e/typescript-coverage/yarn.lock, examples/mongodb/package.json, package.json, packages/jest-snapshot/package.json, packages/jest-transform/package.json, yarn.lock
=> chore: refresh lockfile

.circleci/website.sh
So 4425a1f5255748fc1c68639c05157b6eedf1c595 is deployed
Inspect CI output
=> chore: deploy website when website deploy script changes

website/fetchSupporters.js, website/package.json, website/versioned_docs/version-22.x/SnapshotTesting.md, yarn.lock
https://docs.opencollective.com/help/contributing/development/api
>The future of the Open Collective API is our public GraphQL API.
>Our REST API is still supported but we're not working on it anymore.
I've ran it locally, seems to work correctly
=> chore: fetch open collective supporters via gql api

packages/jest-core/src/SearchSource.ts
I just optimized collecting `collectCoverageFrom`.
Single `forEach` instaed of (`filter` + `map` + `forEach`).
=> jest-core: optimize collecting collectCoverageFrom

yarn.lock
New minor, why not 🤷‍♂ 
Green CI
=> chore: bump babel

packages/jest-reporters/src/__tests__/coverage_reporter.test.js
Locally I get 
CI gets this:
This change fixes it locally, if CI is happy I'll merge it
Green CI
=> chore: fix flaky test

.gitignore, examples/mongodb/teardown.js
This came via #7849. @saenglert I assume this is fine?
Running the example no longer gives a diff
=> chore: delete mongo config file in teardown

docs/JestObjectAPI.md, website/versioned_docs/version-22.x/JestObjectAPI.md, website/versioned_docs/version-23.x/JestObjectAPI.md, website/versioned_docs/version-24.x/JestObjectAPI.md
SpyOn section does not include a link to the mock function description. Added a link to that.
Not necessary - documentation fix.
=> Add link to mock function documentation

packages/jest-cli/src/cli/args.ts
I ran `jest --help` and noticed the extra space in the `--ci` option.
I just removed a space, I'm sure CI would catch any errors :)
=> Remove extra space from --ci description

packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts, packages/jest-environment-jsdom/src/index.ts, packages/jest-environment-node/src/index.ts, packages/jest-haste-map/src/lib/FSEventsWatcher.ts, packages/jest-jasmine2/src/index.ts, packages/jest-jasmine2/src/jasmine/Env.ts, packages/jest-repl/src/cli/index.ts, packages/jest-resolve/src/index.ts, packages/jest-runner/src/runTest.ts, packages/jest-runtime/src/index.ts, packages/pretty-format/src/index.ts
Following up from #9539.
Green CI
=> chore: type all exported functions

.github/workflows/nodejs.yml
Follow-up from #9101. Not sure why the tests are failing...
Green CI at some point
=> chore: run GH Actions on windows as well

packages/jest-matcher-utils/package.json
IntelliJ based IDEs can't find the types without it.
I made the change locally in the `node_modules` folder of a project and the IDE correctly picks up the types.
=> chore(jest-matcher-utils): Add pkg.types

package.json, packages/jest-reporters/src/coverage_reporter.ts, yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/
We won't be able to use much of the new syntax (https://github.com/typescript-eslint/typescript-eslint/pull/1465) but the stricter checks etc are 👍 
Green CI
=> chore: bump to typescript@3.8

docs/TutorialReact.md, docs/TutorialReactNative.md
Updated the React and React Native Links
=> docs: Updated links

.azure-pipelines.yml
I've gotten some emails about this. https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/
Green CI
=> chore: bump version of macos on azure

CHANGELOG.md, docs/Troubleshooting.md, packages/jest-haste-map/src/crawlers/watchman.ts, website/versioned_docs/version-22.x/Troubleshooting.md, website/versioned_docs/version-23.x/Troubleshooting.md, website/versioned_docs/version-24.x/Troubleshooting.md
Fix the link to the watchman troubleshooting page.
=> chore: fix broken link watchman

CHANGELOG.md
sorry wrong change log for #9762 @SimenB
=> Update CHANGELOG.md for #9762

CONTRIBUTING.md
Add CLA link to `CONTRIBUTING.md` to make it easier to find.
=> docs: add CLA link to contributing docs

.azure-pipelines-steps.yml
Updating a outdated comment.
The YAML still parses the same, and still validates.  Comment is updated without regressions.
=> update comment to match config

packages/jest-core/src/SearchSource.ts
Minor optimize matching paths. One `.map` instead of two `.map`.
=> [jest-core] minor optimize matching paths

packages/jest-resolve/package.json, yarn.lock
It uses `fs.realpath.native`, which is faster (especially on windows): https://github.com/facebook/jest/issues/9776#issuecomment-610681415
Green CI
=> chore: bump resolve package

CHANGELOG.md, docs/GlobalAPI.md, docs/JestObjectAPI.md, e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap, e2e/__tests__/importedGlobals.test.ts, e2e/imported-globals/__tests__/env.test.js, e2e/imported-globals/babel.config.js, e2e/imported-globals/package.json, e2e/native-esm/__tests__/native-esm.test.js, packages/jest-globals/.npmignore, packages/jest-globals/package.json, packages/jest-globals/src/__tests__/index.ts, packages/jest-globals/src/index.ts, packages/jest-globals/tsconfig.json, packages/jest-runtime/package.json, packages/jest-runtime/src/index.ts, packages/jest-runtime/tsconfig.json
Brings back the reverted #9801. Needs Babel plugin fix before we can land this. EDIT: Or land this first so we can merge master into the other PR?
@jeysal feel free to push to this branch if you want 🙂 Or we can land the babel plugin fixes first
Green CI.
=> feat: add `@jest/globals` package for importing globals explicitly

packages/jest-resolve/src/index.ts, packages/jest-runtime/src/helpers.ts, packages/jest-worker/src/WorkerPool.ts
I've had this diff in a stash for quite some time now, let's land it 😀 Makes exactly zero difference, but syntacyically pleasing
green ci
=> chore: remove unused catch clauses

e2e/__tests__/pnp.test.ts
Fixed a minor typo within test description.
N/A
=> minor typographical fix

CHANGELOG.md, packages/jest-runtime/src/index.ts
=> fix: remove warning when mutating `require.cache`

packages/jest-leak-detector/package.json, yarn.lock
Minimum node of 10 should be only breaking change. This is just a dev dep regardless, but wanna verify it doesn't break on CI
Green CI.
=> chore: update to weak-napi@2

website/blog/2020-05-05-jest-26.md
=> Add migration notes for breaking changes

website/versioned_docs/version-26.0/Configuration.md, website/versioned_docs/version-26.0/JestObjectAPI.md, website/versioned_docs/version-26.0/JestPlatform.md
Just noticed we miss modern fake timers in 26 docs, so fixing. Adjusted other docs as well. Don't think changelog is necessary :D 
CI
=> docs: fix Configuration, JestPlatform and JestObjectAPI docs for 26

website/versioned_docs/version-26.0/JestObjectAPI.md
Followup fix for #9985
Website test CI
=> docs: fix jest-object ids for docusaurs

website/pages/en/index.js
=> chore: add missing comma

CHANGELOG.md, packages/jest-core/src/cli/index.ts
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯
🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 🔟✖💯 …
=> 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

packages/jest-reporters/package.json, packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap, packages/jest-transform/src/__tests__/script_transformer.test.js, yarn.lock
Testing to see if it breaks anything
Green CI
=> chore: bump `istanbul-lib-instrument`

packages/jest-transform/src/ScriptTransformer.ts
Minor refactor `_getTransformer` to avoid needless defining `let transform`.
=> chore: minor optimize getTransformer

docs/JestPlatform.md
Minor fix to jest-diff example to make it work.
=> docs: fix jest-diff example

docs/GlobalAPI.md, website/versioned_docs/version-25.x/GlobalAPI.md
Fixes https://github.com/facebook/jest/issues/10103
Documentation was referencing aliases that did not exist, so update the docs to remove those references.
Any reference to `ftest` alias has been removed
=> chore: Remove references to ftest alias

.azure-pipelines-steps.yml
=> chore: use non-beta cache task on azure pipelines

packages/jest-core/src/getChangedFilesPromise.ts
Removes unreachable code
```typescript
// We do process.exit, so this is dead code
return Promise.reject(e);
```
Location: `packages/jest-core/src/getChangedFilesPromise.ts line 41`
N/A
=> fix: remove unreachable code

docs/Configuration.md, docs/TutorialReactNative.md, website/versioned_docs/version-22.x/Configuration.md, website/versioned_docs/version-22.x/TutorialReactNative.md, website/versioned_docs/version-23.x/Configuration.md, website/versioned_docs/version-24.x/Configuration.md, website/versioned_docs/version-24.x/TutorialReactNative.md, website/versioned_docs/version-25.x/Configuration.md, website/versioned_docs/version-25.x/TutorialReactNative.md, website/versioned_docs/version-26.0/Configuration.md
A part of continuous effort to get rid of non-inclusive terms like "whitelist" and "blacklist" implying that white = good and black = bad.
n/a
=> Replace non-inclusive terms in documentation with alternatives

CHANGELOG.md, packages/babel-plugin-jest-hoist/src/index.ts
Part **1 of 4**  of continuous effort to get rid of non-inclusive terms like "whitelist" and "blacklist" implying that white = good and black = bad.
n/a
=> Replace non-inclusive "WHITELISTED_IDENTIFIERS" term with "ALLOWED_IDENTIFIERS"

.github/dependabot.yml
Just for GitHub actions for now. Could possibly add it for dependencies as well, but meh.
Docs: https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot
I don't think it does anything before it's merged, so not much.
=> chore: add dependabot for GH Actions

e2e/Utils.ts, e2e/__tests__/asyncRegenerator.test.ts, e2e/__tests__/babelPluginJestHoist.test.ts, e2e/__tests__/chaiAssertionLibrary.ts, e2e/__tests__/console.test.ts, e2e/__tests__/coverageHandlebars.test.ts, e2e/__tests__/coverageRemapping.test.ts, e2e/__tests__/coverageReport.test.ts, e2e/__tests__/coverageTransformInstrumented.test.ts, e2e/__tests__/expectAsyncMatcher.test.ts, e2e/__tests__/failures.test.ts, e2e/__tests__/globalSetup.test.ts, e2e/__tests__/globalTeardown.test.ts, e2e/__tests__/nativeAsyncMock.test.ts, e2e/__tests__/pnp.test.ts, e2e/__tests__/stackTraceSourceMaps.test.ts, e2e/__tests__/stackTraceSourceMapsWithCoverage.test.ts, e2e/__tests__/transform.test.ts, e2e/__tests__/typescriptCoverage.test.ts
Extracted from #10188 to reduce its diff
Green CI
=> chore: add `runYarn` helper for e2e tests

packages/jest-resolve/package.json, packages/jest-resolve/src/defaultResolver.ts, yarn.lock
Another one from #10188 to reduce its diff
Green CI
=> chore: update jest-pnp-resolver

e2e/__tests__/esmConfigFile.test.ts
https://nodejs.org/en/blog/release/v12.17.0/
Green CI. Circle won't have the new version yet (as it uses docker, and the docker image haven't been updated), but maybe GH Actions will? If not, I'll wait with merging until we can verify the test pass.
EDIT:
Let's hold off on merging then, there is absolutely no rush here.
EDIT2:
=> chore: run esm config test on node 12

scripts/buildTs.js
I find it a bit easier to read. I've got some more incoming changes that needs this.
Ignore whitespace on this one: https://github.com/facebook/jest/pull/10249/files?w=1
Green CI
=> chore: use async-await in buildTs script

docs/CLI.md, docs/Configuration.md, docs/DynamoDB.md, docs/Es6ClassMocks.md, docs/ExpectAPI.md, docs/GettingStarted.md, docs/JestCommunity.md, docs/JestObjectAPI.md, docs/ManualMocks.md, docs/MockFunctionAPI.md, docs/MockFunctions.md, docs/MongoDB.md, docs/Puppeteer.md, docs/SnapshotTesting.md, docs/TestingAsyncCode.md, docs/TestingFrameworks.md, docs/TimerMocks.md, docs/Troubleshooting.md, docs/TutorialAsync.md, docs/TutorialReact.md, docs/TutorialReactNative.md, docs/UsingMatchers.md, docs/Webpack.md, website/versioned_docs/version-26.0/CLI.md, website/versioned_docs/version-26.0/Configuration.md, website/versioned_docs/version-26.0/JestObjectAPI.md
Fixing a few typos, and enhancing the clarity of a few sentences, in the docs.
N/A
=> fixing few typos and enhancing clarity in few sentences, in docs

website/versioned_docs/version-22.x/Es6ClassMocks.md
After #7674 files versioned_docs/version-22.2/Es6ClassMocks.md and versioned_docs/version-22.3/Es6ClassMocks.md were deleted.
website/versioned_sidebars/version-22.x-sidebars.json contains stirng "version-22.x-es6-class-mocks",
but needed file doesn't exists in directory.
Page https://jestjs.io/docs/en/22.x/es6-class-mocks must be founded.
=> docs: restore deleted page

packages/jest-reporters/src/types.ts, packages/jest-resolve-dependencies/src/index.ts, packages/jest-resolve/src/index.ts, packages/jest-runner/src/runTest.ts, packages/jest-runner/src/testWorker.ts, packages/jest-runner/src/types.ts, packages/jest-runtime/src/types.ts
Triggers proper import elision 
Green CI
=> chore: remove some usage of import = require

CONTRIBUTING.md, README.md
=> add spaces between texts and contributors images

packages/jest-cli/src/__tests__/cli/args.test.ts, packages/jest-config/src/__tests__/getMaxWorkers.test.ts, packages/jest-config/src/__tests__/readConfigs.test.ts, packages/jest-matcher-utils/src/__tests__/index.test.ts, packages/jest-serializer/src/__tests__/index.test.ts, packages/jest-source-map/src/__tests__/getCallsite.test.ts, packages/jest-test-result/src/__tests__/formatTestResults.test.ts, packages/pretty-format/src/__tests__/prettyFormat.test.ts, packages/pretty-format/src/__tests__/react.test.tsx
Minor cleanup to some `@ts-expect-error` comments - some were not needed, others needed moving because of formatting.
Let CI do its thing.
=> chore: update `@ts-expect-error` comments and tests

CHANGELOG.md, docs/SnapshotTesting.md
Change the mobile app to web app in documentation
=> Update the term "mobile app" to "web app" in snapshot testing documentation

e2e/coverage-report/__mocks__/sumDependency.js, package.json, yarn.lock
Why not.
EDIT: One reason why is `@typescript-eslint` complaining about the version number. Theoretically fixed tomorrow when they have a new release: https://github.com/typescript-eslint/typescript-eslint/issues/2260#issuecomment-677853883
Green CI
=> chore: upgrade to typescript@4

package.json, yarn.lock
We're also broken due to #10444, so let's bump
Green CI
=> chore: bump prettier

.circleci/config.yml
=> chore: use orb instead of docker image for CircleCI

package.json, packages/expect/src/extractExpectedAssertionsErrors.ts, packages/expect/src/jestMatchersObject.ts, packages/expect/src/types.ts, packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts, packages/jest-circus/src/legacy-code-todo-rewrite/jestExpect.ts, packages/jest-jasmine2/src/index.ts, packages/jest-jasmine2/src/setup_jest_globals.ts, packages/jest-runtime/src/index.ts, scripts/buildUtils.js, yarn.lock
Extracted noise from some other feature branches
Green CI
=> chore: clean types of circus initialization types

packages/jest-worker/README.md
Just a duplicate line in documentation, likely an artifact of a past merge.
No tests, literally a single line in the docs.
=> docs(worker): removed duplicated description for `setupArgs`

docs/GettingStarted.md
fix link in documention (getting startted page). Change npm link to directly go to npm package for jest..
=> docs: fix link in getting started page

package.json, packages/jest-reporters/package.json, website/fetchSupporters.js, website/package.json, yarn.lock
`v8-to-istanbul` had to revert, so a good idea for us to pull in the fixed version.
Green CI
=> chore: bump deps

README.md
Added MIT Licence Badge and aligned all the badges to the center including twitter badge
Added MIT Licence Badge and aligned all badges to the center
MIT Licence Badge
Aligned to Center
=> chore(docs): Added MIT Licence Badge and aligned all badges

.github/PULL_REQUEST_TEMPLATE.md
fix grammar in PULL_REQUEST_TEMPLATE
Green CI 😄
=> chore: fix grammar in PULL_REQUEST_TEMPLATE

.github/ISSUE_TEMPLATE/feature.md
Marked section descriptions as comments as they are for the author's eye only.
NA
=> chore: update feature request template

README.md, docs/GettingStarted.md, website/versioned_docs/version-24.x/GettingStarted.md
To improve the doc on how to handle Typescript type-checking for Jest as mentioned in https://github.com/facebook/jest/issues/10704
=> Improve the doc on how to do type-checking for test files

.github/ISSUE_TEMPLATE/bug.md
Maybe it'll cause people to include it? If it helps even 1 issue I'm happy
🤷
=> chore: link to SO's guide for reproduction in bug template

docs/ECMAScriptModules.md, website/versioned_docs/version-26.0/ECMAScriptModules.md
I think this is useful
Docs only
=> chore(docs): note how to get `jest` object in ESM tests

packages/babel-plugin-jest-hoist/package.json, packages/jest-reporters/package.json, packages/jest-worker/package.json, yarn.lock
=> chore: update dependencies

.gitignore
remove a redundant entry from gitignore - `/packages/*/package-lock.json`
As we already have - https://github.com/facebook/jest/blob/1205299a25f5b928c96d2962b4793e46265ae0e9/.gitignore#L39
Green CI
=> chore: remove a redundant entry from gitignore

packages/babel-plugin-jest-hoist/package.json, packages/babel-plugin-jest-hoist/src/index.ts, yarn.lock
This fails. @jeysal would you be able to take a look?
Green CI at some point 🙂
=> chore: bump `@babel/core` types

packages/jest-runtime/src/index.ts
This should have been part of #10620.
Green CI
=> fix: tell transformers Jest supports dynamic imports

CHANGELOG.md, packages/babel-preset-jest/package.json, yarn.lock
This enables TLA and our test for native ESM passes with `babel-jest` enabled
Green CI
=> chore: update node babel syntax preset

e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap, e2e/native-esm/__tests__/native-esm.test.js, e2e/native-esm/namespaceExport.js
https://github.com/facebook/jest/pull/10750/files#r515502740
Just adding a test, no logic changes
=> chore: add test verifying namespace export support

packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.ts.snap, packages/jest-transform/src/__tests__/script_transformer.test.ts
Fixing the test for #10753 turned out super painful. This will make it easier, but can land now
Green CI
=> chore: rewrite script-transformer test in TS

docs/Configuration.md, packages/jest-types/src/Config.ts, website/versioned_docs/version-22.x/Configuration.md, website/versioned_docs/version-23.x/Configuration.md, website/versioned_docs/version-24.x/Configuration.md, website/versioned_docs/version-25.x/Configuration.md, website/versioned_docs/version-26.0/Configuration.md, website/versioned_docs/version-26.2/Configuration.md, website/versioned_docs/version-26.4/Configuration.md, website/versioned_docs/version-26.5/Configuration.md, website/versioned_docs/version-26.6/Configuration.md
Pulls in the docs from #9351 (minus the new option) into all versioned docs
Green CI
=> chore: document `haste` config option

e2e/async-regenerator/yarn.lock, e2e/babel-plugin-jest-hoist/yarn.lock, e2e/console-winston/yarn.lock, e2e/coverage-handlebars/yarn.lock, e2e/coverage-report/yarn.lock, e2e/coverage-transform-instrumented/yarn.lock, e2e/expect-async-matcher/yarn.lock, e2e/failures/yarn.lock, e2e/global-setup/yarn.lock, e2e/global-teardown/yarn.lock, e2e/transform/babel-jest-manual/yarn.lock, e2e/transform/babel-jest/yarn.lock, e2e/transform/multiple-transformers/yarn.lock, e2e/transform/transformer-config/yarn.lock, yarn.lock
=> chore: refresh lockfiles

packages/babel-jest/src/index.ts, yarn.lock
Type addition upstreamed
Green CI
=> chore: bump babel core types

docs/TutorialReactNative.md, website/versioned_docs/version-22.x/TutorialReactNative.md, website/versioned_docs/version-25.x/TutorialReactNative.md
Placing React Native styles after component improves readability also this the way [React Native](https://reactnative.dev/) official documentation declare styles on their components.  Let me know your thoughts on this Thanks!
=> chore(docs): update TutorialReactNative.md

e2e/__tests__/jestChangedFiles.test.ts, e2e/__tests__/onlyChanged.test.ts
Regression from #10827
Green Windows CI
=> chore: fix failing windows test

.github/ISSUE_TEMPLATE/regression.md
update regression issue template
Marked section descriptions as comments as they are for the author's eye only.
Added link to Stack Overflow guide for reproduction.
NA
=> chore: update regression issue template

CONTRIBUTING.md
Fixes https://github.com/facebook/jest/issues/10734
NA
=> docs: update instructions to try dev build of Jest in another project

CHANGELOG.md, packages/jest-util/src/createProcessObject.ts
Considering we drop support for Node 8, this compromise can be removed.
https://github.com/facebook/jest/pull/9136
Green CI
=> no longer detecting enumerable when add domain

examples/react-native/jest.config.js
Something is weird here, it passed a bunch of times for me before it started failing. Might have been a cached transform, but CI is also passing...
Green CI.
=> chore: fix react-native example

package.json, patches/fsevents.patch, yarn.lock
Adds a patch with https://github.com/fsevents/fsevents/pull/348. I'm not sure if the builtin patch is still applied or not? I'm guessing that's only needed for PnP though, which we don't use
Verified patch is applied on install
=> chore: patch fsevents ts file

package.json, yarn.lock
Publishing v27 makes the examples pull in a version of jest from the registry, which doesn't necessarily work with what's in the repo. This diff forces all dependencies on `jest` and `babel-jest` to resolve to the ones in this repo
Green CI
=> chore: fix failing tests

packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/crawlers/__tests__/node.test.js, packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js, packages/jest-haste-map/src/watchers/FSEventsWatcher.ts, packages/jest-runtime/src/__tests__/Runtime-sourceMaps.test.js, packages/jest-runtime/src/__tests__/runtime_create_mock_from_module.test.js, packages/jest-runtime/src/__tests__/runtime_environment.test.js, packages/jest-runtime/src/__tests__/runtime_internal_module.test.js, packages/jest-runtime/src/__tests__/runtime_jest_fn.js, packages/jest-runtime/src/__tests__/runtime_jest_spy_on.test.js, packages/jest-runtime/src/__tests__/runtime_mock.test.js, packages/jest-runtime/src/__tests__/runtime_module_directories.test.js, packages/jest-runtime/src/__tests__/runtime_node_path.test.js, packages/jest-runtime/src/__tests__/runtime_require_actual.test.js, packages/jest-runtime/src/__tests__/runtime_require_cache.test.js, packages/jest-runtime/src/__tests__/runtime_require_mock.test.js, packages/jest-runtime/src/__tests__/runtime_require_module.test.js, packages/jest-runtime/src/__tests__/runtime_require_module_or_mock.test.js, packages/jest-runtime/src/__tests__/runtime_require_module_or_mock_transitive_deps.test.js
I find the tests way easier to read when they're like this. Make sure to ignore whitespace when looking this over: https://github.com/facebook/jest/pull/10970/files?w=1
Green CI
=> chore: use async-await in tests

e2e/__tests__/jestChangedFiles.test.ts, e2e/__tests__/onlyChanged.test.ts
From https://github.com/facebook/jest/pull/10958/files#r545159992
Green CI
=> chore: improve git version detection in tests

package.json, packages/jest-core/package.json, packages/jest-core/src/TestWatcher.ts, packages/jest-runner/package.json, packages/jest-runner/src/index.ts, packages/jest-runner/src/types.ts, yarn.lock
=> chore: update emittery

website/pages/en/help.js
Notes that volunteers, not FB team run Jest pretty much nowadays
=> Update the help text

website/versioned_docs/version-26.x/TestingAsyncCode.md
Just fix a little typo and let the lint pass!
Before
After
=> fix(website): fix typo in 26.x TestingAsyncCode

packages/babel-jest/package.json, packages/babel-jest/src/loadBabelConfig.ts, yarn.lock
=> chore: bump @types/babel__core to get rid of custom types

docs/CLI.md
As I was translating, I noticed that the sentence division took place in a strange place.
=> docs: Fix incorrect period position

docs/ManualMocks.md, website/versioned_docs/version-25.x/ManualMocks.md, website/versioned_docs/version-26.x/ManualMocks.md
As per the discussion in the issue #10500, this PR adds clarification regarding the term "scoped modules".
=> (docs): add clarification for scoped modules

CHANGELOG.md, README.md, docs/MockFunctionAPI.md, e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap, e2e/__tests__/__snapshots__/wrongEnv.test.ts.snap, e2e/__tests__/supportsDashedArgs.ts, examples/mongodb/jest.config.js, packages/expect/README.md, packages/expect/src/types.ts, packages/jest-circus/README.md, packages/jest-cli/src/init/__tests__/__snapshots__/init.test.js.snap, packages/jest-cli/src/init/generateConfigFile.ts, packages/jest-config/src/Deprecated.ts, packages/jest-message-util/src/index.ts, packages/jest-runtime/src/__tests__/__snapshots__/runtime_require_module_no_ext.test.js.snap, packages/jest-runtime/src/helpers.ts, packages/jest-runtime/src/index.ts, packages/jest-snapshot/src/SnapshotResolver.ts, packages/jest-snapshot/src/__tests__/__snapshots__/SnapshotResolver.test.ts.snap, packages/jest-transform/src/enhanceUnexpectedTokenMessage.ts, packages/jest-validate/src/__tests__/__snapshots__/validateCLIOptions.test.js.snap, packages/jest-validate/src/validateCLIOptions.ts, test-types/top-level-globals.test.ts, test-types/top-level-jest-namespace.test.ts, website/versioned_docs/version-25.x/JestObjectAPI.md, website/versioned_docs/version-25.x/MockFunctionAPI.md, website/versioned_docs/version-25.x/TutorialAsync.md, website/versioned_docs/version-26.x/JestObjectAPI.md, website/versioned_docs/version-26.x/MockFunctionAPI.md, website/versioned_docs/version-26.x/TutorialAsync.md
`/en` and `.html` is not needed. In addition, I changed a couple of instances of hard-coded URLs to reference the markdown file instead.
/cc @slorber 
Verify preview looks good & green CI
=> chore: update website links to avoid redirects

docs/Configuration.md, website/versioned_docs/version-25.x/Configuration.md, website/versioned_docs/version-26.x/Configuration.md
hello, I'm quite sure that is a copy-paste error 🙂 
Thanks!
=> docs: fix error in transformIgnorePatterns

docs/Configuration.md, website/versioned_docs/version-25.x/Configuration.md, website/versioned_docs/version-26.x/Configuration.md
Add documentation for `maxWorkers` configuration option. The content is copied from https://jestjs.io/docs/26.x/cli#--maxworkersnumstring
Closes #11273 
Start doc server and check if `maxWorkers` is available in:
- http://localhost:3000/docs/next/configuration
- http://localhost:3000/docs/configuration
- http://localhost:3000/docs/25.x/configuration
=> docs(configuration): add `maxWorkers` option documentation

CHANGELOG.md, website/src/pages/index.js
The current link to Node.js website on the top page links to https://nodejs.org/en/. But it should be https://nodejs.org/ so that users can visit the localized website instead of the English one.
=> Remove a language code from the link to the Node.js website

CONTRIBUTING.md
As of today, the LTS version is 14. Bumping the version recommended in `CONTRIBUTING.md`.
N/A, markdown file.
=> docs: bump recommended node version to LTS

.circleci/config.yml, .github/workflows/nodejs.yml
https://nodejs.org/en/blog/release/v16.0.0/
Green CI
=> chore: add node v16 to CI

docs/SetupAndTeardown.md, website/versioned_docs/version-25.x/SetupAndTeardown.md, website/versioned_docs/version-26.x/SetupAndTeardown.md
"Wiener" doesn't mean sausage in this context, but rather "from Vienna". "Schnitzel" may be translated as "cutlet". "Wiener Würstchen" would be a sausage.
=> docs: "Wiener" isn't always a sausage

examples/manual-mocks/__tests__/user.test.js
Fixed typo.
```
orginal -> original
```
=> chore: Fix typo in user.test.js

CHANGELOG.md
=> docs: Add micromatch change to changelog

docs/Configuration.md, website/versioned_docs/version-25.x/Configuration.md, website/versioned_docs/version-26.x/Configuration.md
=> docs: JS type hinting for the configuration

docs/SetupAndTeardown.md, website/versioned_docs/version-25.x/SetupAndTeardown.md, website/versioned_docs/version-26.x/SetupAndTeardown.md
https://github.com/facebook/jest/pull/11312 pointed out a factual issue in the documentation that incorrectly classified [Wiener Schnitzel](https://en.wikipedia.org/wiki/Wiener_schnitzel) as a sausage. I appreciate that the issue was rectified and I am going to invite the entire Jest team for Schnitzel in Austria one day so that a similar mistake will not be repeated again.
However, the above Pull Request introduced another inconsistency. While in Germany sausages are referred to as "Vienna Sausages" (English) or "Wiener Würstchen" (German), they are referred to as "Frankfurter (sausages)" or "Frankfurter Würstl" in Austria and the Netherlands. This means that people from those countries reading the Jest documentation will be confused, and non-German speaking people will be confused …
=> Bring back the Schnitzel

docs/ManualMocks.md, website/versioned_docs/version-25.x/ManualMocks.md, website/versioned_docs/version-26.x/ManualMocks.md
=> Update ManualMocks.md to clarify on "automatically" mocking manual mocks

website/static/css/jest.css
Fixed typo.
```
alway -> always
```
=> chore: Fix typo in jest.css

.github/workflows/lock.yml
Just following up #11343 to reduce CI runs
=> chore: run lock workflow every day instead of every hour

docs/Puppeteer.md
I was reviewing the docs and didn't want to have to search for info on how to configure Jest :)
=> Link to Jest config

packages/jest-core/src/lib/updateGlobalConfig.ts
I just removed needless property assignment.
=> chore: remove needless assign

docs/Puppeteer.md, website/versioned_docs/version-25.x/Puppeteer.md, website/versioned_docs/version-26.x/Puppeteer.md, website/versioned_docs/version-27.0/Puppeteer.md
Use Promises API of [fs](https://nodejs.org/api/fs.html) module in [Puppeteer.md](https://jestjs.io/docs/puppeteer)
By reducing synchronous functions, it brings harmony to the sample code.
This is a document-only change.
=> docs: Use Promises API of fs module in Puppeteer.md

.github/workflows/nodejs.yml
=> chore: use builtin dep caching in actions/setup-node

docs/ECMAScriptModules.md, website/versioned_docs/version-27.0/ECMAScriptModules.md
=> docs: update ECMAScript Modules file extension examples

docs/Configuration.md, website/versioned_docs/version-25.x/Configuration.md, website/versioned_docs/version-26.x/Configuration.md, website/versioned_docs/version-27.0/Configuration.md
Add testExecError to testResultsProcessor docs for results processor authors
Add testExecError to testResultsProcessor docs for results processor authors
N/A - docs change
=> Add testExecError to testResultsProcessor docs

examples/react/.babelrc.js, examples/react/package.json, examples/snapshot/__tests__/link.react.test.js, yarn.lock
=> chore: get rid of warnings when running react tests

.github/workflows/nodejs.yml, website/docusaurus.config.js
=> Rename main branch to main

.circleci/config.yml, .github/workflows/nodejs.yml, packages/jest-config/package.json, packages/jest-config/src/__tests__/normalize.test.ts, yarn.lock
https://nodejs.org/en/blog/release/v16.9.1/
See #11822
Green CI
=> chore: remove node version pinning from CI

README.md
`npm t[est]` to test.
README change only.
=> chore: update `npm` instructions in README

docs/CodeTransformation.md, website/versioned_docs/version-27.0/CodeTransformation.md, website/versioned_docs/version-27.1/CodeTransformation.md, website/versioned_docs/version-27.2/CodeTransformation.md
=> Docs: docs/CodeTransformation.md (typo fix)

CONTRIBUTING.md
Node 16 has been moved to Active LTS, so we should recommend it instead.
No.
=> chore(CONTRIBUTING.md): recommend using node v16

website/src/pages/index.js
Stats are outdated on the homepage :)
=> docwebsite: update download stats

packages/jest-reporters/package.json, yarn.lock
After https://github.com/istanbuljs/istanbuljs/issues/631 this should be fine
Green CI
=> chore: bump istanbul-lib-instrument

CHANGELOG.md, packages/jest-environment-node/src/index.ts
AbortSignal is available in Node.js >= 15.
=> jest-environment-node: Add AbortSignal

package.json, tsconfig.json, yarn.lock
A tiny bit less config (and natural to update when dropping node versions)
Green CI
=> chore(tsconfig): extend base node 10 config

package.json, packages/jest-environment-jsdom/package.json, patches/@types-jsdom.patch, tsconfig.json, yarn.lock
Less likely to introduce type errors
Green CI
=> chore(tsconfig): remove dom types

website/videos.json
i changed it a while ago and was recently informed that it could be a security concern to have a dead link in here
see more https://fburl.com/kijuy4wr (meta only)
=> fix url in websites videos page

README.md
| Before | After |
| :-: | :-: |
| <img width="385" alt="CleanShot 2022-01-05 at 00 07 46@2x" src="https://user-images.githubusercontent.com/8186898/148088444-5db78dde-3d73-4fd5-9127-c5480c1fcc38.png"> | <img width="375" alt="CleanShot 2022-01-05 at 00 09 36@2x" src="https://user-images.githubusercontent.com/8186898/148088579-7cc0890d-788a-471b-b01e-8a656603d6fe.png"> |
No.
=> chore: fix twitter badge

packages/jest-config/src/resolveConfigPath.ts
`packcage.json`  ---> `package.json`
=> chore: correct file path in comment

website/static/css/jest.css
Adding `align-items: baseline` to `.logos` to prevent some logos like Twitter from being weirdly aligned.
| Before | After |
| - | - |
| <img src="https://user-images.githubusercontent.com/7189823/148293864-0e47942f-f5b4-485c-9809-6661289ef715.png" /> | <img src="https://user-images.githubusercontent.com/7189823/148293830-5cef3f47-abbd-404a-a190-ed06da772553.png" /> |
=> chore: better alignment for homepage logos

.circleci/config.yml, .github/workflows/nodejs.yml, e2e/native-esm/__tests__/native-esm.test.js
It is now LTS, so we can use it for all the jobs that doesn't run on multiple versions
Green CI
=> chore: use Node 16 more on CI

.eslintrc.js, scripts/build.js, scripts/buildTs.js, scripts/buildUtils.js, scripts/watch.js
Doubtful it matters, but less FS is always good 🙂 
Green CI
=> chore: read package.json less during build

e2e/global-teardown-esm/__tests__/test.js
=> Revert "chore: remove unused import from test"

examples/react-native/__tests__/__snapshots__/intro.test.js.snap, examples/react-native/package.json, package.json, yarn.lock
=> chore: update react-native in example

packages/jest-worker/src/workers/NodeThreadsWorker.ts, packages/jest-worker/src/workers/__tests__/NodeThreadsWorker.test.js
Noticed while working on bundling, this cannot generate an absolute path to disk after build
Green CI
=> chore: load node thread child via require.resolve

jest.config.js
Exclude type tests from code coverage.
N/A
=> chore: exclude type tests from coverage

packages/jest-transform/package.json, yarn.lock
=> chore: update `write-file-atomic` again

.eslintrc.js, docs/Configuration.md, docs/TutorialReact.md, package.json, website/versioned_docs/version-25.x/Configuration.md, website/versioned_docs/version-26.x/Configuration.md, website/versioned_docs/version-27.0/Configuration.md, website/versioned_docs/version-27.1/Configuration.md, website/versioned_docs/version-27.2/Configuration.md, website/versioned_docs/version-27.4/Configuration.md, website/versioned_docs/version-27.5/Configuration.md, yarn.lock
=> chore: update eslint-plugin-markdown

docs/TutorialReact.md, website/package.json, website/src/components/v1/MarkdownBlock.js, website/versioned_docs/version-25.x/TutorialReact.md, website/versioned_docs/version-26.x/SnapshotTesting.md, website/versioned_docs/version-26.x/TutorialReact.md, website/versioned_docs/version-27.0/SnapshotTesting.md, website/versioned_docs/version-27.0/TutorialReact.md, website/versioned_docs/version-27.1/SnapshotTesting.md, website/versioned_docs/version-27.1/TutorialReact.md, website/versioned_docs/version-27.2/SnapshotTesting.md, website/versioned_docs/version-27.2/TutorialReact.md, website/versioned_docs/version-27.4/SnapshotTesting.md, website/versioned_docs/version-27.4/TutorialReact.md, website/versioned_docs/version-27.5/TutorialReact.md, yarn.lock
Why not
Green CI, and correct looking deploy preview
=> chore: update website dependencies

docs/GettingStarted.md, website/versioned_docs/version-25.x/GettingStarted.md, website/versioned_docs/version-26.x/GettingStarted.md, website/versioned_docs/version-27.0/GettingStarted.md, website/versioned_docs/version-27.1/GettingStarted.md, website/versioned_docs/version-27.2/GettingStarted.md, website/versioned_docs/version-27.4/GettingStarted.md, website/versioned_docs/version-27.5/GettingStarted.md
Fixed #12333
Some documents are changed in #12306, resulting in breaking links to the TypeScript section.
=> docs(GettingStarted): add the title of using TypeScript section

.yarnrc.yml, website/docusaurus.config.js, website/package.json, yarn.lock
Updates some old deps and gets rid of lots of peer dep warnings
Green CI, and clicking around in the preview deployments.
(last time it failed on some crowdin stuff when merged to `main`, so will also watch it there)
=> chore: update docusaurus

e2e/__tests__/__snapshots__/complexItemsInErrors.ts.snap, e2e/__tests__/complexItemsInErrors.ts
This adds 2 tests
1. Guarding against serialization regression like https://github.com/facebook/jest/pull/10981#issuecomment-790392647
2. A test (skipped, but works with proper serialization) for big ints (#11617)
Green CI
=> chore: add tests for some serialization issues in workers

packages/jest-matcher-utils/src/index.ts
`value` and `print` are connected
Green CI
=> chore: type printWithType more accurately

packages/jest-circus/src/types.ts, packages/jest-jasmine2/src/jasmine/jasmineLight.ts
I think we did this since we couldn't use symbols as keys or some such. I think that's been fixed in TS for a long time
Green CI
=> chore: do not cast symbol to string

examples/angular/.babelrc.js, examples/angular/package.json, examples/enzyme/package.json, examples/react-testing-library/package.json, examples/snapshot/package.json, yarn.lock
It's shipped by default in `preset-env`, so we don't need an explicit dep
Green CI
=> chore: remove explicit `@babel/plugin-proposal-class-properties`

.eslintrc.js, docs/Configuration.md, e2e/snapshot-serializers/__tests__/snapshot.test.js, e2e/snapshot-serializers/utils.js, packages/expect/src/jestMatchersObject.ts, packages/jest-cli/src/cli/args.ts, packages/jest-each/src/table/interpolation.ts, packages/jest-fake-timers/src/legacyFakeTimers.ts, packages/jest-mock/src/__tests__/index.test.ts, packages/jest-util/src/__tests__/createProcessObject.test.ts, packages/jest-util/src/createProcessObject.ts, packages/jest-worker/src/index.ts, packages/pretty-format/src/index.ts, website/versioned_docs/version-25.x/Configuration.md, website/versioned_docs/version-26.x/Configuration.md, website/versioned_docs/version-27.0/Configuration.md, website/versioned_docs/version-27.1/Configuration.md, website/versioned_docs/version-27.2/Configuration.md, website/versioned_docs/version-27.4/Configuration.md, website/versioned_docs/version-27.5/Configuration.md
Fixes #12026  
In the past , i pulled a PR #12158 to fix this, but deleted the branch so i am closing the previous one and this one should act as stated.
=> fix: add `no-prototype-builtins` lint rule and fix occurrences

.github/workflows/nodejs.yml
Copied from https://github.com/nodejs/node/pull/42017
Will push a bit to this PR, verifying stuff is cancelled (like circle already does)
=> chore(ci): cancel redundant workflow runs

docs/CLI.md, docs/DynamoDB.md, docs/GettingStarted.md, docs/MongoDB.md, docs/Puppeteer.md, docs/Troubleshooting.md, docs/TutorialReact.md, docs/Webpack.md, website/docusaurus.config.js, website/package.json, website/versioned_docs/version-25.x/GettingStarted.md, website/versioned_docs/version-26.x/GettingStarted.md, website/versioned_docs/version-27.0/GettingStarted.md, website/versioned_docs/version-27.1/GettingStarted.md, website/versioned_docs/version-27.2/GettingStarted.md, website/versioned_docs/version-27.4/GettingStarted.md, website/versioned_docs/version-27.5/GettingStarted.md, yarn.lock
Probably easier for beginners as `npm` ships with `node`. I only did it for `next` docs.
Also removed a _horribly_ dated Babel 6 caveat (from all versions).
View deploy preview
=> docs(website): use `npm2yarn` plugin

docs/Configuration.md, website/versioned_docs/version-27.4/Configuration.md, website/versioned_docs/version-27.5/Configuration.md
Noticed this outdated info
Verify deployment preview
=> docs(website): correct information about `exports` support

docs/GettingStarted.md, website/versioned_docs/version-25.x/GettingStarted.md, website/versioned_docs/version-26.x/GettingStarted.md, website/versioned_docs/version-27.0/GettingStarted.md, website/versioned_docs/version-27.1/GettingStarted.md, website/versioned_docs/version-27.2/GettingStarted.md
A bit much in the ToC
Verify deployment preview
=> docs: use extra heading level for typescript in getting started

docs/MongoDB.md, website/versioned_docs/version-25.x/MongoDB.md, website/versioned_docs/version-26.x/MongoDB.md, website/versioned_docs/version-27.0/MongoDB.md, website/versioned_docs/version-27.1/MongoDB.md, website/versioned_docs/version-27.2/MongoDB.md, website/versioned_docs/version-27.4/MongoDB.md, website/versioned_docs/version-27.5/MongoDB.md
this pr updates the mongodb example .
=> docs(MongoDB): use `useUnifiedTopology`

e2e/__tests__/__snapshots__/circusDeclarationErrors.test.ts.snap, packages/jest-circus/src/eventHandler.ts
Just wanted some lighter for this evening. To fix a simple TODO? Searched, found and fix. Somehow feels like this was too easy ;D
Tests should pass.
=> chore: fix simple todo in `jest-circus`

package.json, yarn.lock
Since we're on 28 alpha, we can pull in v27 safely.
Green CI
=> chore: bump `@types/jest`

e2e/__tests__/onlyChanged.test.ts
=> chore(e2e/tests): assert on correct variable

packages/jest-mock/src/index.ts
Just noticed that `FunctionType` does nothing in `jest-mock`. The type was introduced with my recent refactor. It was helpful while moving types around, but it really does nothing anymore. Safe to remove.
Green CI
=> refactor(jest-mock): remove `FunctionType`

e2e/__tests__/detectOpenHandles.ts
`async_hooks` is node@8, so quite old at this point
Green CI
=> chore: stop skipping detect open handles test

packages/jest-circus/src/formatNodeAssertErrors.ts, packages/jest-jasmine2/src/assertionErrorMessage.ts, packages/jest-source-map/src/__tests__/getCallsite.test.ts, packages/jest-transform/src/__tests__/ScriptTransformer.test.ts, packages/pretty-format/src/__tests__/DOMCollection.test.ts
In theory dead code, so let's remove it
Green CI
=> chore: remove some node 10 compat code

package.json, packages/expect/package.json, packages/jest-expect/package.json, packages/jest-mock/package.json, packages/jest-types/package.json, yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-4-6/
Green CI
=> chore: update typescript

website/siteConfig.js
Fix broken search on the archived versions deployment at archive.jestjs.io  
See https://github.com/facebook/jest/issues/12539
cc @shortcuts
Preview search works:
https://deploy-preview-12543--jest-archive.netlify.app/
=> fix: update Algolia config for archive.jestjs.io 

packages/jest-fake-timers/package.json, yarn.lock
=> fix: update @sinonjs/fake-timers

packages/jest-util/package.json, yarn.lock
micromatch is replaced by picomatch in `jest-util`, so we don't need @types/micromatch either.
CI Green
=> chore(deps): remove unused @types/micromatch

docs/CLI.md, website/versioned_docs/version-25.x/CLI.md, website/versioned_docs/version-26.x/CLI.md, website/versioned_docs/version-27.0/CLI.md, website/versioned_docs/version-27.1/CLI.md, website/versioned_docs/version-27.2/CLI.md, website/versioned_docs/version-27.4/CLI.md, website/versioned_docs/version-27.5/CLI.md
fix https://github.com/facebook/jest/issues/12261
=> docs: add doc for `--testMatch` CLI option

docs/TestingFrameworks.md, website/versioned_docs/version-25.x/TestingFrameworks.md, website/versioned_docs/version-26.x/TestingFrameworks.md, website/versioned_docs/version-27.0/TestingFrameworks.md, website/versioned_docs/version-27.1/TestingFrameworks.md, website/versioned_docs/version-27.2/TestingFrameworks.md, website/versioned_docs/version-27.4/TestingFrameworks.md, website/versioned_docs/version-27.5/TestingFrameworks.md
fix the broken link in the website and in docs, the author's website is no longer available, but the code examples are still available in github
doc update only
=> docs: fix broken link in TestingFrameworks.md

jest.config.mjs
We're running about 10 tests that are used in e2e tests, no need to do so
Green CI
=> chore: do not run tests of e2e tests

.yarnrc.yml, examples/react-native/package.json, package.json, yarn.lock
Extracted from #12689 to make it a bit smaller
Green CI
=> chore: update react-native

package.json, yarn.lock
update dependency @microsoft/api-extractor to 7.23.0 to support typescript 4.6
see changelog of api-extractor: https://github.com/microsoft/rushstack/blob/main/apps/api-extractor/CHANGELOG.md#7230
Green CI
=> update dependency @microsoft/api-extractor to 7.23.0

docs/UpgradingToJest28.md
#8923 is potentially hugely breaking for folks, so let's call it out explicitly
🤷
=> docs: add mention of expect breaking change to upgrade guide

docs/UpgradingToJest28.md, website/versioned_docs/version-28.0/UpgradingToJest28.md
Gotten a couple of issues in the last day, making it more visible hopefully helps
🤷
=> chore: add more details about known issues with `exports`

e2e/__tests__/detectOpenHandles.ts, e2e/detect-open-handles/__tests__/worker.js
Fixes #11707
Linked issue was actually fixed in #12705, but it needed node 18.1.0 (the linked node issue). Now that is available, we can land the test
=> chore: add test that unreffed workers are not reported

docs/Configuration.md, website/versioned_docs/version-25.x/Configuration.md, website/versioned_docs/version-26.x/Configuration.md, website/versioned_docs/version-27.x/Configuration.md, website/versioned_docs/version-28.0/Configuration.md, website/versioned_docs/version-28.1/Configuration.md
Add two missing admonitions to `Configuration.md`.
Lint should pass.
=> docs: add two more admonitions to `Configuration.md` 

CONTRIBUTING.md
=> Grammatically updated the contribution.md

package.json, packages/diff-sequences/package.json, packages/expect/package.json, packages/expect/src/__tests__/matchers-toContain.property.test.ts, packages/expect/src/__tests__/matchers-toContainEqual.property.test.ts, packages/expect/src/__tests__/matchers-toEqual.property.test.ts, packages/expect/src/__tests__/matchers-toStrictEqual.property.test.ts, yarn.lock
=> chore: update ts-node

.eslintrc.cjs, e2e/__tests__/__snapshots__/testFailing.test.ts.snap, e2e/__tests__/__snapshots__/testFailingJasmine.test.ts.snap, e2e/test-failing/__tests__/worksWithOnlyMode.test.js, yarn.lock
=> chore: update eslint

packages/jest-reporters/package.json, packages/jest-source-map/package.json, packages/jest-transform/package.json, yarn.lock
No code changes, but force an update of `@jridgewell/trace-mapping` which has some fixes we want
Green CI
=> chore: update `v8-to-istanbul`

packages/jest-fake-timers/package.json, packages/jest-fake-timers/src/__tests__/modernFakeTimers.test.ts, yarn.lock
They now verify no double install, so we need to tweak our test
Green CI
=> chore: update `@sinonjs/fake-timers`

package.json, website/package.json, yarn.lock
Why not 😀 
Verify deploy preview
=> chore: update `docusaurus` to `beta.21`

packages/jest-schemas/package.json, yarn.lock
=> feat: upgrade TypeBox

CHANGELOG.md
Fixed typo in changeme.md file.
=> chore: fixed changelog.md typo

CHANGELOG.md, docs/UpgradingToJest29.md, packages/jest-environment-jsdom/package.json, packages/jest-environment-jsdom/src/index.ts, yarn.lock
Removed in #13037, now back
Green CI
=> fix: re-add `@types/jsdom`

website/package.json, yarn.lock
https://docusaurus.io/blog/2022/08/01/announcing-docusaurus-2.0
Deployment preview
=> chore: upgrade to docusaurus 2 stable

docs/UpgradingToJest29.md
Closes #13039
Deployment preview
=> docs: link to v28 upgrade guide from the v29 one

packages/jest-reporters/package.json, packages/jest-source-map/package.json, packages/jest-transform/package.json, yarn.lock
Closes #12998.
Not sure it'd update all the versions needed to fix the underlying issue, but I don't think there's more we can do here
N/A
=> chore: update @jridgewell/trace-mapping

e2e/Utils.ts, e2e/__tests__/snapshotMockFs.test.ts, packages/jest-core/package.json, packages/jest-core/src/__tests__/watchFileChanges.test.ts, packages/jest-core/src/cli/index.ts, scripts/bundleTs.mjs, scripts/cleanE2e.mjs, scripts/remove-examples.mjs, scripts/verifyOldTs.mjs, scripts/verifyPnP.mjs, yarn.lock
`fs.rm` is in Node 14
Green CI
=> fix: replace non-CLI `rimraf` usage

docs/Configuration.md, website/versioned_docs/version-29.0/Configuration.md
One admonition is missing in Configuration docs. Would be nice to add it.
=> docs: add missing admonition in Configuration docs

packages/jest-core/src/plugins/UpdateSnapshotsInteractive.ts, yarn.lock
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.36.0
Green CI
=> chore: update ts-eslint for TS 4.8 compatibility

CHANGELOG.md
1. Fix a typo in the changelog
2. Contribute a PR which will allow me to run workflows without manual approvals from a maintainer :)
=> docs: fix changelog typos

docs/CodeTransformation.md, website/versioned_docs/version-27.x/CodeTransformation.md, website/versioned_docs/version-28.x/CodeTransformation.md, website/versioned_docs/version-29.0/CodeTransformation.md
=> docs: code transform admonitions

docs/ExpectAPI.md, website/versioned_docs/version-25.x/ExpectAPI.md, website/versioned_docs/version-26.x/ExpectAPI.md, website/versioned_docs/version-27.x/ExpectAPI.md, website/versioned_docs/version-28.x/ExpectAPI.md, website/versioned_docs/version-29.0/ExpectAPI.md
=> docs: expect admonitions

docs/Troubleshooting.md, website/versioned_docs/version-25.x/Troubleshooting.md, website/versioned_docs/version-26.x/Troubleshooting.md, website/versioned_docs/version-27.x/Troubleshooting.md, website/versioned_docs/version-28.x/Troubleshooting.md, website/versioned_docs/version-29.0/Troubleshooting.md
=> docs: troubleshooting admonitions

docs/Puppeteer.md, website/versioned_docs/version-25.x/Puppeteer.md, website/versioned_docs/version-26.x/Puppeteer.md, website/versioned_docs/version-27.x/Puppeteer.md, website/versioned_docs/version-28.x/Puppeteer.md, website/versioned_docs/version-29.0/Puppeteer.md
=> docs: puppeteer admonitions

docs/Es6ClassMocks.md, website/versioned_docs/version-25.x/Es6ClassMocks.md, website/versioned_docs/version-26.x/Es6ClassMocks.md, website/versioned_docs/version-27.x/Es6ClassMocks.md, website/versioned_docs/version-28.x/Es6ClassMocks.md, website/versioned_docs/version-29.0/Es6ClassMocks.md
=> docs: ES6 class mocks admonitions

docs/GettingStarted.md, website/versioned_docs/version-25.x/GettingStarted.md, website/versioned_docs/version-26.x/GettingStarted.md, website/versioned_docs/version-27.x/GettingStarted.md, website/versioned_docs/version-28.x/GettingStarted.md, website/versioned_docs/version-29.0/GettingStarted.md
=> docs: getting Started admonitions

website/versioned_docs/version-25.x/Webpack.md, website/versioned_docs/version-26.x/Webpack.md, website/versioned_docs/version-27.x/Webpack.md, website/versioned_docs/version-28.x/Webpack.md, website/versioned_docs/version-29.0/Webpack.md
=> docs: add admonitions to all versions of webpack docs

docs/CLI.md, website/versioned_docs/version-25.x/CLI.md, website/versioned_docs/version-26.x/CLI.md, website/versioned_docs/version-27.x/CLI.md, website/versioned_docs/version-28.x/CLI.md, website/versioned_docs/version-29.0/CLI.md
=> docs: CLI admonitions

docs/TutorialReactNative.md, website/versioned_docs/version-25.x/TutorialReactNative.md, website/versioned_docs/version-26.x/TutorialReactNative.md, website/versioned_docs/version-27.x/TutorialReactNative.md, website/versioned_docs/version-28.x/TutorialReactNative.md, website/versioned_docs/version-29.0/TutorialReactNative.md
=> docs: React Native tutorial admonitions

docs/UsingMatchers.md, website/versioned_docs/version-25.x/UsingMatchers.md, website/versioned_docs/version-26.x/UsingMatchers.md, website/versioned_docs/version-27.x/UsingMatchers.md, website/versioned_docs/version-28.x/UsingMatchers.md, website/versioned_docs/version-29.0/UsingMatchers.md
=> docs: matchers admonitions

scripts/buildTs.mjs, scripts/bundleTs.mjs
Top-level await is available from node 14, so we don't need the extra wrapper.
[(ignore whitespace)](https://github.com/facebook/jest/pull/13365/files?w=1)
Green CI
=> chore: use TLA in build scripts

packages/jest-transform/src/ScriptTransformer.ts, packages/jest-transform/src/__tests__/ScriptTransformer.test.ts, packages/jest-transform/src/enhanceUnexpectedTokenMessage.ts, packages/jest-transform/src/types.ts, scripts/lintTs.mjs
Fixed some type errors and introduced some new ones (since things are no longer `any`)
Green CI
=> chore: lint jest-transform with type info

.circleci/config.yml
Shouldn't make much of a difference, but let's update
Green CI
=> chore(ci): use latest CircleCI orb

package.json, packages/pretty-format/src/__tests__/AsymmetricMatcher.test.ts, packages/pretty-format/src/__tests__/DOMCollection.test.ts, packages/pretty-format/src/__tests__/DOMElement.test.ts, packages/pretty-format/src/__tests__/Immutable.test.ts, packages/pretty-format/src/__tests__/ReactElement.test.ts, packages/pretty-format/src/__tests__/react.test.tsx, packages/pretty-format/src/__tests__/setPrettyPrint.ts
Adding typechecks for tests of `pretty-format` package.
Green CI.
=> chore: add typecheck for tests of `pretty-format`

packages/expect/src/__tests__/matchers-toStrictEqual.property.test.ts, packages/jest-console/src/BufferedConsole.ts, packages/jest-console/src/CustomConsole.ts, packages/jest-console/src/getConsoleOutput.ts, packages/jest-haste-map/src/watchers/WatchmanWatcher.js, packages/jest-snapshot/src/__tests__/utils.test.ts, scripts/build.mjs, scripts/buildTs.mjs, scripts/buildUtils.mjs, scripts/lintTs.mjs
=> chore: run type lint on @jest/console

packages/jest-regex-util/src/__tests__/index.test.ts, packages/jest-test-sequencer/src/__tests__/test_sequencer.test.ts, packages/jest-test-sequencer/src/index.ts, scripts/lintTs.mjs
=> chore: run type lint on @jest/test-sequencer

yarn.lock
Partly #13422 to reduce the diff
Green CI
=> chore: update some babel deps

docs/Configuration.md, website/versioned_docs/version-25.x/Configuration.md, website/versioned_docs/version-26.x/Configuration.md, website/versioned_docs/version-27.x/Configuration.md, website/versioned_docs/version-28.x/Configuration.md, website/versioned_docs/version-29.0/Configuration.md, website/versioned_docs/version-29.1/Configuration.md
I fixed the typo correcting "pakcage" to "package" in the tip outlined in the issue request in all the versions of the configurations.md file.
=> Fixed the typo outlined in issue 13429.

.gitignore, .yarnrc.yml, website/README.md, website/babel.config.js, website/docusaurus.config.js, website/package.json, website/tsconfig.json, yarn.lock
=> chore: bump website deps

packages/jest-diff/src/__tests__/diff.test.ts, packages/jest-mock/src/index.ts, packages/jest-repl/src/cli/repl.ts, packages/jest-repl/src/cli/runtime-cli.ts, packages/jest-repl/src/cli/version.ts, packages/jest-reporters/src/Status.ts, scripts/lintTs.mjs
I ran the autofix on all packages, and fixed a few errors in `jest-diff` and `jest-repl`
Green CI
=> chore: ts lint some more

jest.config.mjs, packages/jest-validate/src/__tests__/__fixtures__/jestConfig.ts, packages/jest-validate/src/__tests__/validate.test.ts
Renamed `__fixtures__` folder to keep the repo tidier and fixed few types in that fixture.
Green CI.
=> refactor(jest-validate) rename `__fixtures__` folder

.circleci/config.yml, .github/workflows/test.yml
https://nodejs.org/en/blog/announcements/v19-release-announce/
I made some changes in #13467. Hopefully enough (but I don't think so, as mentioned there)
Green CI?
=> chore: test node 19 on CI

.github/dependabot.yml
In theory it works now: https://github.blog/changelog/2022-10-20-dependabot-can-now-generate-security-and-version-updates-for-yarn-v2-and-v3/
🤷
=> chore: use dependabot for updates

docs/Configuration.md, docs/WatchPlugins.md, website/versioned_docs/version-25.x/Configuration.md, website/versioned_docs/version-25.x/WatchPlugins.md, website/versioned_docs/version-26.x/Configuration.md, website/versioned_docs/version-26.x/WatchPlugins.md, website/versioned_docs/version-27.x/Configuration.md, website/versioned_docs/version-27.x/WatchPlugins.md, website/versioned_docs/version-28.x/Configuration.md, website/versioned_docs/version-28.x/UpgradingToJest28.md, website/versioned_docs/version-28.x/WatchPlugins.md, website/versioned_docs/version-29.0/Configuration.md, website/versioned_docs/version-29.0/WatchPlugins.md, website/versioned_docs/version-29.1/Configuration.md, website/versioned_docs/version-29.1/WatchPlugins.md, website/versioned_docs/version-29.2/Configuration.md, website/versioned_docs/version-29.2/WatchPlugins.md
Fixes links so they point to the correct line numbers.
=> docs: correct line numbers in GH links

packages/expect/src/spyMatchers.ts, packages/expect/src/toThrowMatchers.ts
Noticed `this.utils` was unavailable on the spy matchers.
Green CI
=> chore(expect): type spy and throwing matchers correctly

yarn.lock
https://docusaurus.io/blog/releases/2.2
Deploy preview
=> chore(docs): update docusaurus

docs/Webpack.md, website/versioned_docs/version-25.x/Webpack.md, website/versioned_docs/version-26.x/Webpack.md, website/versioned_docs/version-27.x/Webpack.md, website/versioned_docs/version-28.x/Webpack.md, website/versioned_docs/version-29.0/Webpack.md, website/versioned_docs/version-29.1/Webpack.md, website/versioned_docs/version-29.2/Webpack.md
Fix https://github.com/facebook/jest/issues/12556
Closes https://github.com/facebook/jest/pull/12823 by @abdih.
I refrected some comments by @NetworkRock and @mrazauskas for the PR https://github.com/facebook/jest/pull/12823.
- Change to lower case `Webpack` -> `webpack`
- https://github.com/facebook/jest/pull/12823#discussion_r956614241
- Change package.json to jest.config.js
- https://github.com/facebook/jest/pull/12823#discussion_r956615125
- Apply commit suggestions by @mrazauskas
- I didn't apply [this line](https://github.com/facebook/jest/pull/12823/files#diff-ac63ebbe4ece2fd0f7836dc3e286a8414cb82f73da736b44a32426f49150e98eR222) because I cannot figure out the reason.
=> Doc: Update documentation on usage with Webpack

docs/Webpack.md, website/versioned_docs/version-25.x/Webpack.md, website/versioned_docs/version-26.x/Webpack.md, website/versioned_docs/version-27.x/Webpack.md, website/versioned_docs/version-28.x/Webpack.md, website/versioned_docs/version-29.0/Webpack.md, website/versioned_docs/version-29.1/Webpack.md, website/versioned_docs/version-29.2/Webpack.md
Fixing lint issue introduced in #13556.
Green CI.
=> chore: fix lint issue introduced in #13556

CHANGELOG.md, packages/jest-fake-timers/package.json, yarn.lock
https://github.com/sinonjs/fake-timers/blob/main/CHANGELOG.md#1000--2022-11-08
We dropped Node 12 in Jest 29, so this change is not breaking for us
Green CI
=> fix: update `@sinonjs/fake-timers`

.yarn/patches/ts-node-npm-10.9.1-6c268be7f4.patch, package.json, yarn.lock
Alternative to #13701
Closes #13690
Closes #13701
CI
=> chore: attempt to patch ts-node

docs/ManualMocks.md, website/versioned_docs/version-25.x/ManualMocks.md, website/versioned_docs/version-26.x/ManualMocks.md, website/versioned_docs/version-27.x/ManualMocks.md, website/versioned_docs/version-28.x/ManualMocks.md, website/versioned_docs/version-29.0/ManualMocks.md, website/versioned_docs/version-29.1/ManualMocks.md, website/versioned_docs/version-29.2/ManualMocks.md, website/versioned_docs/version-29.3/ManualMocks.md
=> chore(website): ManualMocks admonitions

docs/UpgradingToJest29.md, website/versioned_docs/version-29.0/UpgradingToJest29.md, website/versioned_docs/version-29.1/UpgradingToJest29.md, website/versioned_docs/version-29.2/UpgradingToJest29.md, website/versioned_docs/version-29.3/UpgradingToJest29.md
=> chore(website): UpgradingToJest29 admonitions

packages/jest-config/src/normalize.ts, packages/jest-leak-detector/package.json, yarn.lock
=> chore: add missing dev dep for `jest-leak-detector`

packages/jest-config/package.json, packages/jest-snapshot/package.json, packages/jest-test-result/package.json, packages/jest-test-result/tsconfig.json, yarn.lock
=> chore: add some more missing deps

docs/CLI.md, website/versioned_docs/version-25.x/CLI.md, website/versioned_docs/version-26.x/CLI.md, website/versioned_docs/version-27.x/CLI.md, website/versioned_docs/version-28.x/CLI.md, website/versioned_docs/version-29.0/CLI.md, website/versioned_docs/version-29.1/CLI.md, website/versioned_docs/version-29.2/CLI.md, website/versioned_docs/version-29.3/CLI.md
Following up #13708
Ups.. Just noticed a typo which I left in the above mentioned PR.
Green CI.
=> docs: fix in CLI documentation

packages/babel-plugin-jest-hoist/package.json, packages/babel-plugin-jest-hoist/src/__tests__/__snapshots__/hoistPlugin.test.ts.snap, yarn.lock
Kept back in #13798, but fixed now
Green CI
=> chore: update babel-plugin-tester

package.json, yarn.lock
This PR removes the unused dependency progress from the project. It helps to keep the project clean and maintainable.
ci green
=> Remove unused dependency 'progress'

docs/Webpack.md, website/versioned_docs/version-25.x/Webpack.md, website/versioned_docs/version-26.x/Webpack.md, website/versioned_docs/version-27.x/Webpack.md, website/versioned_docs/version-28.x/Webpack.md, website/versioned_docs/version-29.0/Webpack.md, website/versioned_docs/version-29.1/Webpack.md, website/versioned_docs/version-29.2/Webpack.md, website/versioned_docs/version-29.3/Webpack.md, website/versioned_docs/version-29.4/Webpack.md
Remove extraneous tab symbol in Using with webpack page.
=> docs: remove extraneous tab symbol

docs/MockFunctionAPI.md
Ups.. Just found a mistake which I left in in #13870. Fixing it here.
Deploy preview
=> docs: fix a mistake introduced in #13870

docs/ExpectAPI.md, website/versioned_docs/version-25.x/ExpectAPI.md, website/versioned_docs/version-26.x/ExpectAPI.md, website/versioned_docs/version-27.x/ExpectAPI.md, website/versioned_docs/version-28.x/ExpectAPI.md, website/versioned_docs/version-29.0/ExpectAPI.md, website/versioned_docs/version-29.1/ExpectAPI.md, website/versioned_docs/version-29.2/ExpectAPI.md, website/versioned_docs/version-29.3/ExpectAPI.md, website/versioned_docs/version-29.4/ExpectAPI.md
Closes #13589
The above mentioned PR got stale unfortunately. I rebased it and added one of my suggestions.
=> docs: add few missing admonitions to the Expect API page

packages/jest-each/src/__tests__/template.test.ts, packages/jest-each/src/table/interpolation.ts
I just a little simplified `interpolateVariables`. To avoid chains of `reduce` and reduce code.
There were already tests, but I added a little.
=> jest-each: simplify interpolation

packages/jest-config/src/setFromArgv.ts
Just avoided 1 loop by putting checking inside `reduce`
=> [jest-config] simplify filter-reduce

e2e/Utils.ts
=> chore: retry cleanup in e2e tests

docs/ECMAScriptModules.md, website/versioned_docs/version-25.x/ECMAScriptModules.md, website/versioned_docs/version-26.x/ECMAScriptModules.md, website/versioned_docs/version-27.x/ECMAScriptModules.md, website/versioned_docs/version-28.x/ECMAScriptModules.md, website/versioned_docs/version-29.0/ECMAScriptModules.md, website/versioned_docs/version-29.1/ECMAScriptModules.md, website/versioned_docs/version-29.2/ECMAScriptModules.md, website/versioned_docs/version-29.3/ECMAScriptModules.md, website/versioned_docs/version-29.4/ECMAScriptModules.md, website/versioned_docs/version-29.5/ECMAScriptModules.md
When "etc." is at the end of a sentence, you don't need another period.
See https://english.stackexchange.com/a/8385.
=> fix: remove period

packages/jest-resolve/src/__tests__/resolve.test.ts, packages/jest-resolve/src/nodeModulesPaths.ts
A little optimization of nodeModulesPaths(avoid creating new collection each reduce itaration).
It was already covered with tests, but I added a small one.
=> Optimize node modules path

package.json, packages/expect-utils/package.json, packages/expect/package.json, packages/jest-cli/package.json, packages/jest-expect/package.json, packages/jest-mock/package.json, packages/jest-reporters/package.json, packages/jest-resolve/package.json, packages/jest-runner/package.json, packages/jest-snapshot/package.json, packages/jest-types/package.json, packages/jest-worker/package.json, packages/jest/package.json, yarn.lock
=> chore: update tsd runner

README.md, docs/MoreResources.md, website/blog/2017-01-30-a-great-developer-experience.md, website/blog/2017-02-21-jest-19-immersive-watch-mode-test-platform-improvements.md, website/blog/2018-06-27-supporting-jest-open-source.md, website/docusaurus.config.js, website/src/pages/help.js, website/src/pages/index.js, website/versioned_docs/version-25.x/MoreResources.md, website/versioned_docs/version-26.x/MoreResources.md, website/versioned_docs/version-27.x/MoreResources.md, website/versioned_docs/version-28.x/MoreResources.md, website/versioned_docs/version-29.0/MoreResources.md, website/versioned_docs/version-29.1/MoreResources.md, website/versioned_docs/version-29.2/MoreResources.md, website/versioned_docs/version-29.3/MoreResources.md, website/versioned_docs/version-29.4/MoreResources.md, website/versioned_docs/version-29.5/MoreResources.md
* The codebase had the wrong Twitter URL path.
* Changed it to the correct Twitter URL path and also renamed all `fbjest` instances with `jestjs_`.
=> fix: Fixes #14146 Twitter Navigation URL

website/src/pages/index.js
This video is an embarrassment. Jest is no longer a Meta project, let's get rid of it.
=> Remove 1-minute video.

packages/jest-schemas/package.json, yarn.lock
v0.28 (which #14219 upgrades to) drops support for Node 14
Green CI
=> fix: upgrade typebox

packages/jest-haste-map/src/watchers/FSEventsWatcher.ts, yarn.lock
=> chore: upgrade to TS 5.1

package.json, scripts/verifyOldTs.mjs, tsconfig.json, tsconfig.typetest.json, yarn.lock
=> chore: upgrade @tsconfig/node14

packages/jest-circus/package.json, packages/jest-circus/src/__mocks__/testUtils.ts, yarn.lock
See https://github.com/babel/babel/pull/15740#issuecomment-1619594944
Green CI?
=> chore: use `fs.rm` instead of `fs.unlink` in test

e2e/async-regenerator/yarn.lock, e2e/babel-plugin-jest-hoist/yarn.lock, e2e/browser-resolver/yarn.lock, e2e/console-winston/yarn.lock, e2e/coverage-remapping/yarn.lock, e2e/coverage-report/yarn.lock, e2e/coverage-transform-instrumented/yarn.lock, e2e/expect-async-matcher/yarn.lock, e2e/failures/yarn.lock, e2e/global-setup/yarn.lock, e2e/global-teardown/yarn.lock, e2e/native-esm/yarn.lock, e2e/stack-trace-source-maps-with-coverage/yarn.lock, e2e/stack-trace-source-maps/yarn.lock, e2e/transform/babel-jest-async/yarn.lock, e2e/transform/babel-jest-manual/yarn.lock, e2e/transform/babel-jest/yarn.lock, e2e/transform/multiple-transformers/yarn.lock, e2e/transform/transform-snapshotResolver/yarn.lock, e2e/transform/transform-testrunner/yarn.lock, e2e/transform/transformer-config/yarn.lock, e2e/typescript-coverage/yarn.lock
Dependabot is reporting all the instances of `semver` in there, so let's just update them all.
Green CI
=> chore: refresh lockfiles of integration tests

yarn.lock
=> chore: update babel deps

.yarnrc.yml, examples/react-native/package.json, yarn.lock
https://reactnative.dev/blog/2023/06/21/0.72-metro-package-exports-symlinks
Green CI
=> chore: upgrade react-native in example

CONTRIBUTING.md
Since `circus` is the default runner, section about `JEST_CIRCUS` environment variable is deprecated
I checked that `JEST_JASMINE=1` doesn't run `jest-circus`
=> chore: Actualize `contributing` docs

packages/jest-core/src/lib/activeFiltersMessage.ts
`messages` always an array with 1 element. This element cant be empty because `\n` + `chalk` at the begin. So there is no need to use filter and join for this. The result always the string from `0` element.
=> Simplify active filters

yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/
Green CI
=> chore: upgrade TypeScript

.github/workflows/nodejs.yml, .github/workflows/test.yml, docs/Troubleshooting.md, website/versioned_docs/version-29.4/Troubleshooting.md, website/versioned_docs/version-29.5/Troubleshooting.md, website/versioned_docs/version-29.6/Troubleshooting.md
Runs on Node 20 instead of Node 16 - meaning `os.availableParallelism` is available for it.
Green CI, verifying how many workers are used.
=> chore: upgrade `github-actions-cpu-cores`

packages/jest-changed-files/src/index.ts
I simplified getting repos for Git and Mercurial.
=> changed-files: simplify find repos

.yarn/patches/psl-npm-1.9.0-a546edad1a.patch, .yarnrc.yml, package.json, yarn.lock
See https://github.com/nodejs/citgm/pull/959#issuecomment-1712467647
Green CI
=> chore: patch psl to avoid deprecation warning

packages/jest-changed-files/src/index.ts
Removed `map` after `Array.from`.
=> changed-files: simplify Array.from

packages/jest-core/src/FailedTestsCache.ts
I removed 2 `filter` and moved check inside `reduce` to avoid needless iteration.
=> Remove a couple filters and move to reduce

packages/jest-diff/src/getAlignedDiffs.ts, packages/jest-environment-jsdom/src/index.ts, packages/jest-environment-node/src/index.ts, packages/jest-fake-timers/src/legacyFakeTimers.ts, packages/jest-haste-map/src/index.ts, packages/jest-jasmine2/src/jasmine/Env.ts, packages/jest-reporters/src/NotifyReporter.ts, packages/jest-reporters/src/__tests__/GitHubActionsReporter.test.ts, packages/jest-worker/src/workers/__tests__/ChildProcessWorker.test.ts, packages/jest-worker/src/workers/__tests__/WorkerEdgeCases.test.ts, packages/jest-worker/src/workers/__tests__/threadChild.test.ts, scripts/lintTs.mjs, yarn.lock
Noticed the new `create-jest` package was not linted, so I changed the list from an allowlist to a denylist.
All changes within `packages/` where done with `--fix`
Also upgraded all ESLint related dependencies.
Green CI
=> chore: lint more packages with types

scripts/buildTs.mjs
I removed needless `map` call and regexp.
=> fix: simplify getting testUtilsReferences

scripts/buildTs.mjs
I just removed one filter call
=> fix: optimize filter in build ts

CHANGELOG.md, packages/jest-schemas/package.json, yarn.lock
Might hold off with this until v30 as it might be breaking for consumers
Green CI
=> chore: update typebox dependencies

CHANGELOG.md, scripts/bundleTs.mjs
Following up #12348. Just avoiding cruft in the published tarballs.
Green CI
=> chore: remove empty directories from `build/`

packages/jest-jasmine2/src/setup_jest_globals.ts
For this case, it is more efficient to use a regular loop with a counter instead of creating a new array and reversing it.
=> fix: optimize addSerializer in setupJestGlobals

packages/jest-diff/src/getAlignedDiffs.ts
`Array.prototype.entries` is slower because it creates an additional iterator and a new array at each step.
=> fix(diff): optimize for loop in diff

packages/jest-haste-map/package.json, packages/jest-haste-map/src/types.ts
There's no reason to have it
Guess when we added it 😅 (#9913)
Green CI
=> chore: remove `@types/graceful-fs` dependency

packages/jest-transform/src/__tests__/ScriptTransformer.test.ts
Code scanning discovered this one. I tried going back and figuring out what this line _tried_ to do, without luck
Green CI
=> chore: do not string replace with self in test

package.json, scripts/build.mjs, scripts/buildUtils.mjs, scripts/watch.mjs, yarn.lock
We don't need a custom watcher, the multicompiler from webpack is more than capable
I've tested locally
=> chore: use webpack watcher in watch mode

constraints.pro, yarn.lock
Why not. I wanna set up more lint rules, so just upping to latest versions first makes sense to me
Green CI
=> chore: update ESLint dependencies

netlify.toml
To unblock #14629
Verify deployment still goes well
=> chore: use Node 20 to build website on Netlify

.circleci/config.yml, .github/workflows/test.yml
New versions, new CI updates.
This is also interesting to us as lots of memory leak fixes for `vm` modules have landed in v21
Green CI
=> chore: test against Node v21 on CI

CONTRIBUTING.md, package.json
Updated `CONTRIBUTING.md` to recommend `corepack enable` instead of installing `yarn` manually.
Due to `actions/setup-node` for some inexplicable reason not supporting `corepack`, I've kept the checked in version of yarn, which is what will be used
Green CI
=> chore: update installation instructions for Yarn

tsconfig.json, yarn.lock
Why not.
I also removed `ignoreDeprecations` as we replaced it with the ESLint rules in #14662.
Additionally, I upgraded all ESLint deps as we needed to upgrade `ts-eslint` anyways for the new TS version.
Green CI
=> chore: upgrade to TypeScript@5.3

CHANGELOG.md, packages/jest-schemas/package.json, yarn.lock
=> chore: upgrade typebox

examples/react-native/__tests__/__snapshots__/intro.test.js.snap, examples/react-native/babel.config.js, examples/react-native/package.json, yarn.lock
=> chore: update React Native example

e2e/native-esm/__tests__/native-esm-wasm.test.js, e2e/native-esm/__tests__/native-esm.test.js, packages/create-jest/src/runCreate.ts, packages/expect/src/matchers.ts, packages/expect/src/print.ts, packages/expect/src/spyMatchers.ts, packages/expect/src/toThrowMatchers.ts, packages/jest-config/src/normalize.ts, packages/jest-diff/src/getAlignedDiffs.ts, packages/jest-haste-map/src/__tests__/index.test.js, packages/jest-haste-map/src/index.ts, packages/jest-matcher-utils/src/index.ts, packages/jest-mock/src/index.ts, packages/jest-resolve/src/resolver.ts, packages/jest-snapshot/src/printSnapshot.ts, packages/jest-validate/src/utils.ts, packages/pretty-format/src/index.ts, scripts/buildUtils.mjs, yarn.lock
To keep #14777 cleaner
Green CI
=> chore: upgrade prettier

yarn.lock
Seeing some type test errors in #14777, so let's land that separately
Green CI
=> chore: upgrade TSD

.github/workflows/test-nightly.yml
Missed this one in #14782
Green CI
=> chore(ci): retry one more build

.eslintrc.cjs, e2e/__tests__/__snapshots__/customMatcherStackTrace.test.ts.snap, e2e/custom-matcher-stack-trace/__tests__/sync.test.js, packages/expect-utils/src/utils.ts, packages/expect/src/__tests__/asymmetricMatchers.test.ts, packages/expect/src/__tests__/matchers.test.js, packages/jest-circus/src/__tests__/shuffleArray.test.ts, packages/jest-core/src/cli/index.ts, packages/jest-matcher-utils/src/__tests__/index.test.ts, packages/pretty-format/src/__tests__/prettyFormat.test.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/new-for-builtins.md
Green CI
=> chore: correctly use `new` for JS builtins

.eslintrc.cjs, packages/expect/src/__tests__/assertionCounts.test.ts, packages/jest-config/src/setFromArgv.ts, packages/jest-core/src/SearchSource.ts, packages/jest-matcher-utils/src/Replaceable.ts, packages/pretty-format/src/plugins/DOMCollection.ts
These arrays are tiny, so probably doesn't make a measurable difference.
Green CI
=> chore: prefer Set over Array for existence checks

.eslintrc.cjs, e2e/custom-reporters/reporters/TestReporter.js, packages/jest-message-util/src/__tests__/__snapshots__/messages.test.ts.snap, packages/jest-message-util/src/__tests__/messages.test.ts, packages/jest-reporters/src/Status.ts, packages/jest-reporters/src/__tests__/GitHubActionsReporter.test.ts, packages/jest-util/src/clearLine.ts, packages/jest-util/src/specialChars.ts
Why not. Consistency is good
Green CI
=> chore: prefer unicode escapes over hex

.eslintrc.cjs, docs/MockFunctions.md, packages/jest-diff/src/getAlignedDiffs.ts, packages/jest-reporters/src/GitHubActionsReporter.ts, packages/jest-snapshot/src/utils.ts, website/versioned_docs/version-29.4/MockFunctions.md, website/versioned_docs/version-29.5/MockFunctions.md, website/versioned_docs/version-29.6/MockFunctions.md, website/versioned_docs/version-29.7/MockFunctions.md
=> chore: use more for-of loops

.eslintrc.cjs, e2e/__tests__/__snapshots__/testRetries.test.ts.snap, e2e/test-retries/__tests__/waitBeforeRetry.test.js, e2e/test-retries/__tests__/waitBeforeRetryFakeTimers.test.js, packages/jest-console/src/CustomConsole.ts, packages/jest-jasmine2/src/jasmine/Timer.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-date-now.md
Green CI
=> chore: prefer `Date.now`

.eslintrc.cjs, e2e/__tests__/hasteMapSize.test.ts, packages/jest-changed-files/src/index.ts, packages/jest-core/src/runJest.ts, packages/jest-snapshot/src/worker.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-await-expression-member.md
Green CI
=> chore: avoid await expressions

.eslintrc.cjs, packages/expect/src/asymmetricMatchers.ts, packages/jest-haste-map/src/crawlers/__tests__/node.test.js, packages/jest-matcher-utils/src/index.ts, packages/jest-util/src/deepCyclicCopy.ts, packages/jest-validate/src/utils.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-typeof-undefined.md
Green CI
=> chore: no `typeof undefined`

.eslintrc.cjs, packages/jest-haste-map/src/index.ts, packages/jest-message-util/src/index.ts, packages/jest-reporters/src/GitHubActionsReporter.ts, packages/jest-transform/src/ScriptTransformer.ts, packages/jest-util/src/deepCyclicCopy.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-object-as-default-parameter.md
Green CI
=> chore: avoid objects as default parameters

.eslintrc.cjs, e2e/__tests__/__snapshots__/testFailingJasmine.test.ts.snap, packages/expect/src/index.ts, packages/jest-circus/src/utils.ts, packages/jest-fake-timers/src/legacyFakeTimers.ts, packages/jest-fake-timers/src/modernFakeTimers.ts, packages/jest-jasmine2/src/jasmine/Spec.ts, packages/jest-jasmine2/src/jasmineAsyncInstall.ts, packages/jest-jasmine2/src/queueRunner.ts, packages/jest-runner/src/index.ts, packages/jest-snapshot/src/State.ts
Every instance in the code base was on purpose empty, but it doesn't hurt.
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/error-message.md
Green CI
=> chore: enforce errors are given messages

packages/jest-jasmine2/src/index.ts, packages/jest-mock/src/index.ts, packages/jest-runner/src/runTest.ts, packages/jest-worker/src/types.ts, yarn.lock
=> chore: update prettier to 3.2

README.md
Per the [onboarding checklist,](https://github.com/openjs-foundation/project-status/issues/67) ads copyright notice to Github READMe.
=> Onboarding: Update README.md To Have Copyright

CHANGELOG.md, packages/jest-reporters/package.json, yarn.lock
Drops `source-map` in favour of `@jridgewell/trace-mapping`
Green CI
=> chore: update `istanbul-lib-source-maps`

packages/jest-worker/src/workers/__tests__/WorkerEdgeCases.test.ts
Our nightly build always fails the same test we skipped in #14968
🤷
=> chore: skip flaky test on Node 22 as well

.eslintrc.cjs, package.json, packages/babel-preset-jest/index.js, yarn.lock
Didn't really find anything in the code we distribute, but still
Green CI
=> chore: update `eslint-plugin-unicorn`

package.json, yarn.lock
It dropped Node 14, but not 16, so that we can upgrade the version here in Jest
Green CI
=> chore: upgrade to new Jest ESLint plugin

e2e/__tests__/__snapshots__/each.test.ts.snap, yarn.lock
Somehow this causes a slight change in the snapshots for `jest-each`
Green CI
=> chore: update babel dependencies

CONTRIBUTING.md
@bensternthal I had a call with an intro to STF, where it came up that the release process wasn't documented incase I became unavailable.
I also removed some FB references which no longer apply.
Closes #15136
N/A
=> chore: add publishing instructions docs

CHANGELOG.md, e2e/coverage-transform-instrumented/package.json, e2e/coverage-transform-instrumented/yarn.lock, packages/babel-jest/package.json, packages/jest-transform/package.json, yarn.lock
Let's see if there's a regression here as well.
https://github.com/istanbuljs/istanbuljs/pull/706#issuecomment-2200012354
CI?
=> chore: update istanbul deps

e2e/__tests__/nativeEsm.test.ts
https://github.com/nodejs/citgm/pull/1063#issuecomment-2212411376
Green CI
=> chore: do not log `isolated-vm` error in tests

packages/jest-mock/src/index.ts
A little simplification in checks
Green CI
=> Simplify checks 

.eslintrc.cjs, docs/ExpectAPI.md, e2e/__tests__/jsonReporter.test.ts, packages/expect-utils/src/jasmineUtils.ts, packages/expect/src/asymmetricMatchers.ts, packages/jest-haste-map/src/crawlers/__tests__/node.test.js, packages/jest-repl/src/cli/runtime-cli.ts, packages/jest-reporters/src/wrapAnsiString.ts, packages/jest-test-sequencer/src/index.ts, website/versioned_docs/version-29.4/ExpectAPI.md, website/versioned_docs/version-29.5/ExpectAPI.md, website/versioned_docs/version-29.6/ExpectAPI.md, website/versioned_docs/version-29.7/ExpectAPI.md
No idea why this was disabled
Green CI
=> chore: enable `eqeqeq` lint rule

packages/jest-circus/src/utils.ts
I removed the creation of a new collection `result.beforeEach` in each iteration."
Perf example
https://gist.github.com/Connormiha/feed0d799a97152cac8030b119f7b85e
=> fix: optimize collection beforeEach hooks

packages/jest-circus/src/utils.ts
`then` and `catch` have the some code and catch throws error next. Single `finally` has the some behavior.
=> fix: simplify promise finally action

packages/jest-runtime/src/index.ts, yarn.lock
=> chore: update @types/node

package.json, packages/expect/src/matchers.ts, yarn.lock
=> chore: update eslint-plugin-unicorn

e2e/__tests__/__snapshots__/console.test.ts.snap, e2e/console-winston/yarn.lock
To unblock https://github.com/jestjs/jest/pull/15252
Green CI
=> chore: update winston dep

package.json, packages/jest-config/package.json, packages/jest-core/package.json, packages/jest-haste-map/package.json, packages/jest-message-util/package.json, packages/jest-transform/package.json, yarn.lock
Previous version is vulnerable. Also bumping in package.json even though in semver range to be a bit helpful downstream
Green CI
=> chore: update micromatch

yarn.lock
=> chore: update rollup

yarn.lock
=> chore: update "vulnerable" deps

website/blog/2016-03-11-javascript-unit-testing-performance.md, website/blog/2016-04-12-jest-11.md, website/blog/2016-06-22-jest-13.md, website/blog/2016-07-27-jest-14.md, website/blog/2016-09-01-jest-15.md, website/blog/2016-10-03-jest-16.md, website/blog/2016-12-15-2016-in-jest.md, website/blog/2017-01-30-a-great-developer-experience.md, website/blog/2017-02-21-jest-19-immersive-watch-mode-test-platform-improvements.md, website/blog/2017-05-06-jest-20-delightful-testing-multi-project-runner.md, website/blog/2017-12-18-jest-22.md, website/blog/2018-05-29-jest-23-blazing-fast-delightful-testing.md, website/blog/2018-06-27-supporting-jest-open-source.md, website/blog/2019-01-25-jest-24-refreshing-polished-typescript-friendly.md, website/blog/2020-01-21-jest-25.md, website/blog/2020-05-05-jest-26.md, website/blog/2021-03-09-jest-website-upgrade.md, website/blog/2021-05-25-jest-27.md, website/blog/2022-04-25-jest-28.md, website/blog/2022-05-11-jest-joins-openjs.md, website/blog/2022-08-25-jest-29.md, website/blog/authors.yml, yarn.lock
I noticed the website's deploy was broken. In the hope of better error messages, I decided to upgrade the website dependencies. Then I saw the failure is due to some faulty translations which I'll try to fix in CrowdIn. But still, this doesn't hurt
Deploy preview
=> chore: update website deps

packages/jest-get-type/src/index.ts
`value` cannot be null/undefiend anymore due to checks above
=> [jest-get-type] minor simplification

e2e/__tests__/multiProjectRunner.test.ts, e2e/__tests__/runtimeInternalModuleRegistry.test.ts, e2e/__tests__/testFailingSnapshot.test.js, packages/diff-sequences/src/__tests__/index.test.ts, packages/diff-sequences/src/index.ts, packages/jest-circus/src/__tests__/__snapshots__/hooks.test.ts.snap, packages/jest-circus/src/__tests__/hooks.test.ts, packages/jest-resolve/src/__tests__/resolve.test.ts, packages/jest-runtime/src/__tests__/runtime_require_module.test.js, packages/jest-snapshot/src/State.ts, packages/jest-snapshot/src/index.ts, packages/jest-types/src/Circus.ts
=> chore: Fix typos

.circleci/config.yml
Not sure why renovate didn't send a PR (#14833), but w/e.
From looking at the diff, seems the pain change is added support for pnpm, and no real breaking changes. We'll see!
Green CI
=> chore(circle-ci): update Node orb

e2e/__tests__/complexItemsInErrors.ts, yarn.lock
I think this was fixed in #15191
Green CI
=> chore: enable disabled `BigInt` test

packages/jest-source-map/src/getCallsite.ts, yarn.lock
=> chore: update `http-proxy-middleware`

packages/diff-sequences/package.json, packages/diff-sequences/src/__tests__/index.property.test.ts, packages/expect/package.json, yarn.lock
#15478 still updates after #15579, so let's update it
Green CI
=> chore: update fast-check

docs/MockFunctions.md
=> chore: fix prettier violation

docs/UpgradingToJest30.md
In https://github.com/jestjs/jest/pull/15473 JSDOM was updated to v26.
N/A, docs only change
=> Update v30 upgrade guide to mention correct JSDOM version

packages/jest-resolve-dependencies/src/__tests__/dependency_resolver.test.ts, packages/jest-runtime/src/index.ts
related https://github.com/jestjs/jest/issues/15556#issuecomment-2937937881
It seems also being the root cause of CI failing.
cc @cpojer 
N/A
=> fix: `node` condition should be included in `cjsConditions`

CHANGELOG.md, packages/jest-environment-node/src/__tests__/globals_cleanup_3.test.ts, packages/jest-matcher-utils/src/__tests__/deepCyclicCopyReplaceable.test.ts, packages/jest-matcher-utils/src/deepCyclicCopyReplaceable.ts, packages/jest-util/src/garbage-collection-utils.ts
=> Globals cleanup: make protection property writable

website/blog/2016-09-01-jest-15.md
=> chore: fix typo

packages/jest-message-util/src/index.ts
I simplified the code by replacing the `reduce` with the inner loop with a `flatMap`.
=> fix: simplified reduce with inner loop

CHANGELOG.md, packages/jest-snapshot-utils/src/__tests__/utils.test.ts, packages/jest-snapshot-utils/src/utils.ts
The current phrasing is not grammatically correct
=> fix(snapshot-utils): improve wording of snapshot guide link change error

SECURITY.md, packages/jest-console/src/__tests__/CustomConsole.test.ts
Fixes currently broken CI in `main` branch
- Prettify a not-yet-linted SECURITY.md
- Accommodate [a Node v24 change in `assert` lib](https://github.com/nodejs/node/commit/d35bd2088e2daa001edabeb030de59f20ec6d8e9#diff-968e57a9f4d4ce7494523f71b2594d844620c2794a68049cce33fcdc8c7c7b7c) with slightly different expected result.
Green CI
=> chore: fix broken CI
