- CHANGELOG.md
- e2e/__tests__/globalSetup.test.js
- packages/jest-cli/src/runJest.js
- packages/jest-cli/src/watch.js
Fixes #7740.
Also adds a stack trace to that error:
~~Needs to add a test, but I've confirmed it fixes the problem.~~ Test added
> fix: do not run global hooks if there are no tests

- CHANGELOG.md
- e2e/__tests__/__snapshots__/moduleNameMapper.test.js.snap
- e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.js.snap
- packages/jest-resolve/src/__tests__/resolve.test.js
- packages/jest-resolve/src/defaultResolver.js
- packages/jest-resolve/src/index.js
- yarn.lock
Fixes https://github.com/arcanis/jest-pnp-resolver/issues/1
Test updated
> feat: pass defaultResolver into custom resolvers

- CHANGELOG.md
- packages/jest-runtime/package.json
- yarn.lock
Closes #7709. We're also seeing this error in CI, e.g. https://dev.azure.com/jestjs/jest/_build/results?buildId=264
I _think_ this is caused by https://github.com/npm/write-file-atomic/commit/3365a4df7d6117473905ec3f633d9a1bb42b6b17
EDIT: If that's the case, 2.4.1 should be safe actually. Lemme try that.
Green Windows build on azure.
> rollback write-file-atomic

- .flowconfig
- CHANGELOG.md
- e2e/__tests__/__snapshots__/consoleAfterTeardown.test.js.snap
- e2e/__tests__/consoleAfterTeardown.test.js
- e2e/__tests__/forceExit.test.js
- e2e/console-after-teardown/__tests__/console.test.js
- e2e/console-after-teardown/package.json
- packages/jest-runner/package.json
- packages/jest-runner/src/runTest.js
- packages/jest-util/src/CustomConsole.js
Ref #3853
With this test:
```js
test('throws error', () => {
setTimeout(() => {
console.log('hello!');
}, 500);
});
```
Before this PR:
After this PR:
Integration test added
> fix: print log entries if logging happens after teardown

- packages/expect/src/toThrowMatchers.js
* Simplify ternary expression, see https://github.com/facebook/jest/pull/7697#discussion_r250949126
* Factor out `hasMessage` but leave explicit strict equality conditions, see https://github.com/facebook/jest/pull/7697#pullrequestreview-196485232
* Attempted to import `AsymmetricMatcher` with added `asymmetricMatch` property from `types/Matchers.js` but Flow reported type errors, see https://github.com/facebook/jest/pull/7697#discussion_r250951098
Not necessary to update change log, true?
All existing tests pass
> expect: Make change requested in toThrowMatchers

- CHANGELOG.md
- e2e/__tests__/multiProjectRunner.test.js
- packages/jest-config/package.json
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/index.js
- packages/jest-config/src/normalize.js
Fixes #7732 ~~by basically reverting a change within #5862 (https://github.com/facebook/jest/commit/a370c21539aad54f79d577b3b95203351b1fc169).~~
~~Restored the tests from the linked commit, and added a new one (`minimal config is stable across runs'`)~~
Added a new test to check two runs of `normalize` are stable, plus an e2e test checking name specifically, both for linked config and inline config
> fix: make sure generated `name` in config is stable across runs of Jest

- CHANGELOG.md
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/normalize.js
Fixes #7736 
@SimenB Did end up doing the check in the config 😅 This still feels like weird coupling with `jest-runner`s implementation details, but I tried throwing in `jest-runner` and it was just bad UX because it took so long to get to that point - plus there was no good place to throw without spamming the error for every test :/
Added normalize test
> allow moduleFileExtensions without 'js' for custom runners

- docs/Configuration.md
- website/versioned_docs/version-24.0/Configuration.md
This PR fixes a couple of typos in the `snapshotResolver` configuration docs.
> Fix typos in snapshotResolver configuration docs

- docs/ExpectAPI.md
- website/versioned_docs/version-22.x/ExpectAPI.md
- website/versioned_docs/version-23.x/ExpectAPI.md
- website/versioned_docs/version-24.0/ExpectAPI.md
before:
**arrays arrays**
after:
**arrays**
> Remove duplicate 'arrays' in ExpectAPI.md.

- CHANGELOG.md
- packages/jest-cli/src/testResultHelpers.js
Fixes https://github.com/jest-community/jest-runner-eslint/issues/64
It works 😅 Any tests I write is gonna feel pretty convoluted...
> fix: handle missing todo in test result

- CHANGELOG.md
- e2e/__tests__/__snapshots__/transform.test.js.snap
- e2e/__tests__/transform.test.js
- e2e/transform/babel-jest-ignored/__tests__/ignoredFile.test.js
- e2e/transform/babel-jest-ignored/babel.config.js
- e2e/transform/babel-jest-ignored/package.json
- packages/babel-jest/package.json
- packages/babel-jest/src/index.js
If we don't wanna throw, we should just coerce the return value from `loadPartialConfig` to an empty config I guess.
Not sure what the impact on coverage is.
Fixes #7765.
E2E test added
> fix: make babel-jest warn when file to tarnsform is ignored by babel

- CHANGELOG.md
- e2e/babel-plugin-jest-hoist/__tests__/typescript.test.ts
- packages/babel-plugin-jest-hoist/src/index.js
Fixes #7798. Essentially the same as #7641.
Existing e2e test expanded
> fix: ignore TS type references when looking for out-of-scope references

- .github/ISSUE_TEMPLATE/question.md
Trivial. Replace "form" with "forum" in issue template.
Skipped tests, as this is a minor typo fix in a GitHub issue template.
> Fix typo in question.md issue template

- CHANGELOG.md
- packages/jest-regex-util/package.json
- packages/jest-regex-util/src/__tests__/index.test.ts
- packages/jest-regex-util/src/index.ts
- packages/jest-regex-util/tsconfig.json
Diff:
<details>
```diff
diff --git a/packages/jest-regex-util/build/index.js b/packages/jest-regex-util/build/index.js
index 310d6876b..f3611a56f 100644
--- a/packages/jest-regex-util/build/index.js
+++ b/packages/jest-regex-util/build/index.js
@@ -17,7 +17,6 @@ function _interopRequireDefault(obj) {
*
- *
*/
const escapePathForRegex = dir => {
if (_path.default.sep === '\\') {
@@ -40,7 +39,7 @@ const replacePathSepForRegex = string => {
if (_path.default.sep === '\\') {
return string.replace(
/(\/|(.)?\\(?![[\]{}()*+?.^$|\\]))/g,
-      (_match, p1, p2) => (p2 && p2 !== '\\' ? p2 + '\\\\' : '\\\\')
+      (_match, _, p2) => (p2 && p2 !== '\\' ? p2 + '\\\\' : '\\\\') …
```
> Migrate jest-regex-util to Typescript

- CHANGELOG.md
- e2e/__tests__/jestChangedFiles.test.js
- packages/jest-changed-files/package.json
- packages/jest-changed-files/src/git.ts
- packages/jest-changed-files/src/hg.ts
- packages/jest-changed-files/src/index.ts
- packages/jest-changed-files/src/types.ts
- packages/jest-changed-files/tsconfig.json
Diff:
<details>
```diff
diff --git a/packages/jest-changed-files/build/hg.js b/packages/jest-changed-files/build/hg.js
index 97a84e96f..27a021d87 100644
--- a/packages/jest-changed-files/build/hg.js
+++ b/packages/jest-changed-files/build/hg.js
@@ -94,7 +94,7 @@ function _defineProperty(obj, key, value) {
}
const env = _objectSpread({}, process.env, {
-  HGPLAIN: 1
+  HGPLAIN: '1'
});
const ANCESTORS = [
diff --git a/packages/jest-changed-files/build/index.js b/packages/jest-changed-files/build/index.js
index dbd84f818..5e7db85f2 100644
--- a/packages/jest-changed-files/build/index.js
+++ b/packages/jest-changed-files/build/index.js
@@ -5,10 +5,6 @@ Object.defineProperty(exports, '__esModule', {
});
exports.findRepos = exports.getChangedFilesForRoots = void 0;
-var _git = …
```
> Migrate jest-changed-files to Typescript

- e2e/__tests__/multiProjectRunner.test.js
It doesn't make sense to wrap a `runJust` call into `stripAnsi` since the latter works only with strings.
`runJest` returns an object so stripAnsi just passes it along.
Materials:
- Commit where the code was added in the first place: https://github.com/facebook/jest/commit/e12cab63f06cabaf4e38c18fac18cf463fc10e1f#diff-4cf7d6c79ff377b63522b3af20e34e8eR307
- stripAnsi source code: https://github.com/chalk/strip-ansi/blob/097894423fedb6b4dca3005ad45608b893fcdcf8/index.js
> Remove redundant stripAnsi

- CHANGELOG.md
- packages/jest-docblock/src/__tests__/index.test.ts
- packages/jest-docblock/src/index.ts
- packages/jest-docblock/tsconfig.json
Built diff:
<details>
```diff
diff --git c/packages/jest-docblock/build/index.js w/packages/jest-docblock/build/index.js
index 8c60ffcd1..24f2b052c 100644
--- c/packages/jest-docblock/build/index.js
+++ w/packages/jest-docblock/build/index.js
@@ -9,20 +9,20 @@ exports.parse = parse;
exports.parseWithComments = parseWithComments;
exports.print = print;
-function _detectNewline() {
-  const data = _interopRequireDefault(require('detect-newline'));
+function _os() {
+  const data = require('os');
-  _detectNewline = function _detectNewline() {
+  _os = function _os() {
return data;
};
return data;
}
-function _os() {
-  const data = require('os');
+function _detectNewline() {
+  const data = _interopRequireDefault(require('detect-newline'));
-  _os = function _os() {
+  _detectNewline = …
```
> chore: migrate jest-docblock to TypeScript

- CHANGELOG.md
- packages/jest-serializer/package.json
- packages/jest-serializer/src/__tests__/index.test.ts
- packages/jest-serializer/src/global.d.ts
- packages/jest-serializer/src/index.ts
- packages/jest-serializer/tsconfig.json
Jumping on a TS train 🚂
<details>
```diff
diff --git a/packages/jest-serializer/build/index.js b/packages/jest-serializer/build/index.js
index b6a60150d..1c0d8cdb7 100644
--- a/packages/jest-serializer/build/index.js
+++ b/packages/jest-serializer/build/index.js
@@ -3,8 +3,6 @@
*
- *
- *
*/
'use strict';
@@ -49,7 +47,7 @@ const JS_TYPE = '__$t__';
const JS_VALUE = '__$v__';
const JS_VF = '__$f__';
-function replacer(key, value) {
+function replacer(_key, value) {
// NaN cannot be in a switch statement, because NaN !== NaN.
if (Number.isNaN(value)) {
return {
@@ -110,7 +108,7 @@ function replacer(key, value) {
return value;
}
-function reviver(key, value) {
+function …
```
> chore: migrate jest-serializer to TypeScript

- .eslintrc.js
- CHANGELOG.md
- packages/jest-mock/package.json
- packages/jest-mock/src/__tests__/index.test.ts
- packages/jest-mock/src/index.ts
- packages/jest-mock/tsconfig.json
- packages/jest-types/src/Mocks.ts
- packages/jest-types/src/index.ts
- packages/jest-util/src/FakeTimers.ts
- packages/jest-util/src/__tests__/fakeTimers.test.ts
- packages/jest-util/tsconfig.json
build/index.js
<details>
```diff
diff --git a/packages/jest-mock/build/index.js b/packages/jest-mock/build/index.js
index 76dc3630f..91ed19a0c 100644
--- a/packages/jest-mock/build/index.js
+++ b/packages/jest-mock/build/index.js
@@ -5,8 +5,6 @@
*
- *
- *
*/
/**
@@ -83,63 +81,82 @@ function matchArity(fn, length) {
switch (length) {
case 1:
-      mockConstructor = function mockConstructor(a) {
+      mockConstructor = function mockConstructor(_a) {
return fn.apply(this, arguments);
};
break;
case 2:
-      mockConstructor = function mockConstructor(a, b) {
+      mockConstructor = function mockConstructor(_a, _b) {
return fn.apply(this, arguments);
};
break;
case 3: …
```
> chore: migrate jest-mock to TypeScript

- CHANGELOG.md
- packages/jest-mock/src/index.ts
Produces better public interface to the module.
See: https://github.com/facebook/jest/pull/7847#issuecomment-462126951 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32882
CI happy
> chore: followup to jest-mock TS migration

- CHANGELOG.md
- packages/jest-cli/src/reporters/coverage_reporter.js
- packages/jest-haste-map/src/index.js
- packages/jest-runner/src/index.js
- packages/jest-worker/package.json
- packages/jest-worker/src/Farm.ts
- packages/jest-worker/src/WorkerPool.ts
- packages/jest-worker/src/base/BaseWorkerPool.ts
- packages/jest-worker/src/index.ts
- packages/jest-worker/src/types.ts
- packages/jest-worker/src/workers/ChildProcessWorker.ts
- packages/jest-worker/src/workers/NodeThreadsWorker.ts
- packages/jest-worker/src/workers/__tests__/ChildProcessWorker.test.js
- packages/jest-worker/src/workers/__tests__/NodeThreadsWorker.test.js
- packages/jest-worker/src/workers/processChild.ts
- packages/jest-worker/src/workers/threadChild.ts
- packages/jest-worker/tsconfig.json
I left the tests alone as there were way too many typer errors for the effort I wanted to put into it :P
At some point we can probably make the types smarter (having it infer exports from the file coming in, filtering by `exposedMethods` etc). My hope is that someone will contribute that as a PR at some point 😀 
built diff:
<details>
```diff
diff --git i/packages/jest-worker/build/Farm.js w/packages/jest-worker/build/Farm.js
index ed652e867..f16fe5df8 100644
--- i/packages/jest-worker/build/Farm.js
+++ w/packages/jest-worker/build/Farm.js
@@ -1,11 +1,3 @@
-/**
- * Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
- *
- * This source code is licensed under the MIT license found in the
- * LICENSE file in the root directory of this source tree.
- *
- *
- */
'use strict'; …
```
> chore: migrate jest-worker to TypeScript

- .azure-pipelines.yml
- .gitignore
- e2e/runJest.js
One option for addressing #7760 
* Change e2e/runJest.js to invoke node directly to avoid issue with hung process/test when invoked asynchronously ("until" method)
* Refactor to avoid duplication between runJest and until methods
* Undo downgrade of Yarn (to 1.9.4) in Azure Pipelines Windows jobs
* Add /reports/* to .gitignore (these are junit test reports normally created in CI runs)
See #7760 for details
Tested on Windows, Linux, mac
> fix: Windows-specific test timeout issues introduced by Yarn 1.13.0

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/matchers.js
For 4 matchers which correspond to `>`, `>=`, `<`, `<=` number comparison operators:
* Repeat `not` and operator following `Expected:` label
For these matchers which define expected intervals, I have not thought of any additional way to reduce apparent weirdness when received value is equal to expected boundary.
Residue for future pull request, in call to `ensureNumbers` helper function:
* Delete period in matcher name to display matcher name in regular black instead of dim color
* Provide `options` as argument to display `promise` and `isNot`
Updated 66 snapshots. To save mental effort, review as 33 adjacent pairs of snapshots.
|  | matcher |
| ---: | :--- |
| 14 | …
> expect: Improve report when matcher fails, part 7

- CONTRIBUTING.md
Only one sentence about changelog entries in the PR template so far.
Info about chore & maintenance section might also be useful (#7872),
plus even though I always knew it was possible, I only recently started appreciating GitHub's web editing feature for changelog entries 😅
> contributing guide section about changelog entries

- CHANGELOG.md
- e2e/__tests__/__snapshots__/transform.test.js.snap
- packages/babel-jest/package.json
- packages/babel-jest/src/__tests__/index.ts
- packages/babel-jest/src/index.ts
- packages/babel-jest/tsconfig.json
- packages/jest-types/package.json
- packages/jest-types/src/Transform.ts
- packages/jest-types/src/index.ts
Built diff:
<details>
```diff
diff --git c/packages/babel-jest/build/index.js w/packages/babel-jest/build/index.js
index 09b426d20..fc3dd7f8d 100644
--- c/packages/babel-jest/build/index.js
+++ w/packages/babel-jest/build/index.js
@@ -102,8 +102,9 @@ const jestPresetPath = require.resolve('babel-preset-jest');
const babelIstanbulPlugin = require.resolve('babel-plugin-istanbul');
-const createTransformer = options => {
+const createTransformer = (options = {}) => {
options = _objectSpread({}, options, {
+    // @ts-ignore: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32955
caller: {
name: 'babel-jest',
supportsStaticESM: false
@@ -112,9 +113,9 @@ const createTransformer = options => {
plugins: (options && options.plugins) || [],
presets: ((options && options.presets) || …
```
> chore: migrate babel-jest to TypeScript

- packages/jest-haste-map/src/index.ts
- packages/jest-mock/src/index.ts
- packages/jest-util/src/FakeTimers.ts
- packages/jest-watcher/src/BaseWatchPlugin.ts
- packages/jest-watcher/src/JestHooks.ts
- packages/jest-watcher/src/PatternPrompt.ts
- packages/jest-watcher/src/lib/Prompt.ts
- packages/jest-worker/src/Farm.ts
- packages/jest-worker/src/base/BaseWorkerPool.ts
- packages/jest-worker/src/index.ts
- packages/jest-worker/src/workers/ChildProcessWorker.ts
- packages/jest-worker/src/workers/NodeThreadsWorker.ts
Guides consumers away from private APIs. Also makes the type definitions smaller in some cases since we don't expose as much
Built diff:
<details>
```diff
diff --git i/packages/jest-mock/build/index.d.ts w/packages/jest-mock/build/index.d.ts
index 5dfae37ba..42348609a 100644
--- i/packages/jest-mock/build/index.d.ts
+++ w/packages/jest-mock/build/index.d.ts
@@ -51,7 +51,7 @@ interface Mock<T, Y extends unknown[] = unknown[]> extends Function, MockInstanc
interface SpyInstance<T, Y extends unknown[]> extends MockInstance<T, Y> {
}
interface MockInstance<T, Y extends unknown[]> {
-    _isMockFunction: boolean;
+    _isMockFunction: true;
_protoImpl: Function;
getMockName(): string;
getMockImplementation(): Function | undefined;
diff --git i/packages/jest-util/build/FakeTimers.d.ts …
```
> chore: use more `private`

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/matchers.js
For `.toBeCloseTo` matcher:
* Display matcher name in regular **black** instead of dim color
* Display expected and received **difference** to make criterion more transparent
* Repeat **not** following `Expected:` and `Expected difference:` labels
* Experiment to **omit** received value if it is **equal to** the `not` expected value (am happy if y’all can suggest as an alternative a concise explicit way to communicate that is reason why test fails)
Residue for future pull requests:
1. In call to `ensureNumbers` helper function:
* delete period in matcher name to display matcher name in regular black instead of dim color
* provide `options` as argument to display `promise` and `isNot`
2. Decide whether `.toBeCloseTo` throws matcher …
> expect: Improve report when matcher fails, part 8

- CHANGELOG.md
- e2e/__tests__/__snapshots__/moduleNameMapper.test.js.snap
- e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.js.snap
- package.json
- packages/jest-cli/package.json
- packages/jest-config/package.json
- packages/jest-haste-map/src/ModuleMap.ts
- packages/jest-resolve/package.json
- packages/jest-resolve/src/__tests__/isBuiltinModule.test.ts
- packages/jest-resolve/src/__tests__/resolve.test.ts
- packages/jest-resolve/src/defaultResolver.ts
- packages/jest-resolve/src/index.ts
- packages/jest-resolve/src/isBuiltinModule.ts
- packages/jest-resolve/src/nodeModulesPaths.ts
- packages/jest-resolve/src/types.ts
- packages/jest-resolve/tsconfig.json
- packages/jest-runtime/package.json
- yarn.lock
As expected, had to tweak `jest-haste-map`'s types a bit to match `undefined | null` stuff. Can revisit later and be more consistent across the board
Built diff:
<details>
```diff
diff --git c/packages/jest-resolve/build/defaultResolver.js w/packages/jest-resolve/build/defaultResolver.js
index fab1abcb1..60db7374c 100644
--- c/packages/jest-resolve/build/defaultResolver.js
+++ w/packages/jest-resolve/build/defaultResolver.js
@@ -5,30 +5,30 @@ Object.defineProperty(exports, '__esModule', {
});
exports.default = defaultResolver;
-function _browserResolve() {
-  const data = _interopRequireDefault(require('browser-resolve'));
+function _fs() {
+  const data = _interopRequireDefault(require('fs'));
-  _browserResolve = function _browserResolve() {
+  _fs = function _fs() {
return data;
}; …
```
> chore: migrate jest-resolve to TypeScript

- CHANGELOG.md
- packages/pretty-format/src/__tests__/react.test.tsx
- packages/pretty-format/src/plugins/ReactElement.ts
* Handle memo components in the `getType` function so that a name like `Memo(ComponentName)` is shown instead of `UNDEFINED`.
This fixes #7883.
Added one test similar to the ones for `forwardRef` and `Context`.
> Support React.memo in pretty-format

- CHANGELOG.md
- packages/jest-validate/src/__tests__/validate.test.js
- packages/jest-validate/src/condition.js
`jest-validate` distinguishes between sync and async functions, but it should not. Fixes #7894.
```js
const { validate } = require('jest-validate')
assert(validate({ name: async () => {} }, { exampleConfig: { name: () => {} } }).isValid)
assert(validate({ name: () => {} }, { exampleConfig: { name: async () => {} } }).isValid)
assert(validate({ name: async () => {} }, { exampleConfig: { name: async () => {} } }).isValid)
assert(validate({ name: () => {} }, { exampleConfig: { name: () => {} } }).isValid)
```
> fix: validating async functions (#7894)

- CHANGELOG.md
- packages/jest-cli/package.json
- packages/jest-runtime/src/__tests__/__snapshots__/script_transformer.test.js.snap
- yarn.lock
`jest-cli` is affected by a vulnerability published today on NPM: https://www.npmjs.com/advisories/755
This updates the offending package `istanbul-api` and subsequently `istanbul-reports` to the version needed to no longer have the `handlebars` vulnerability.
I used `yarn upgrade istantbul-api@2.1.1` in the directory `jest/packages/jest-cli`
> Fixes Prototype Pollution vulnerability in Handlebars dependency

- CHANGELOG.md
- TestUtils.js
- TestUtils.ts
- packages/jest-core/src/lib/__tests__/is_valid_path.test.js
- packages/jest-reporters/src/__tests__/generateEmptyCoverage.test.js
- packages/jest-runtime/src/__tests__/instrumentation.test.js
- packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap
- packages/jest-transform/src/__tests__/script_transformer.test.js
- packages/jest-transform/src/__tests__/should_instrument.test.js
- packages/jest-transform/src/shouldInstrument.ts
`shouldInstrument` function expects the config object to be normalized, but some of the unit tests don't respect that so I've tried to change this. When we will be sure that the received config is normalized we can remove the additional checks from the conditions in `shouldInstrument.js` file.
This is work in progress, but I've wanted to hear your opinion regarding my modified version of `testShouldInstrument` function in the `should_instrument.test.js` file. Can you think of any cases that can break this? Is it better to just simply provide a normalized config as an argument every time?
I'm taking care of the failed unit tests right now, any clues how to approach this?
Adjusted unit tests. If we are certain that `shouldInstrument` receives normalized config, I think it should be enough.
> Normalize config and remove unecessary checks

- CHANGELOG.md
- docs/Es6ClassMocks.md
- website/versioned_docs/version-23.x/Es6ClassMocks.md
- website/versioned_docs/version-24.0/Es6ClassMocks.md
> Add missing import to docs

- packages/babel-preset-jest/package.json
The `@babel/plugin-syntax-object-rest-spread` package has peer dependencies on `@babel/core`, which means that `babel-preset-jest` also depends on it.
n/a
> Adds @babel/core to the peer dependencies

- CHANGELOG.md
- packages/jest-worker/src/Farm.ts
- packages/jest-worker/src/__tests__/Farm.test.js
- packages/jest-worker/src/types.ts
Nodes in a linked list were shared among all lists for each worker; which is not what we would like to do. The expected part to be shared is only the request object (which uses the first position as a lock between jobs); but the wrapper object for the linked list needs to be unique.
I also added a test that would crash without the fix.
> Fix queue management in jest-worker

- CHANGELOG.md
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/normalize.js
When loading a `jest-preset.js`, which does some computation or load other packages, errors can occur.
This PR will help preset-developers to see the error message and stack. Currently only the misleading error message `Module jest-preset-angular should have "jest-preset.js" or "jest-preset.json" file at the root.` is displayed.
Inspired by https://github.com/thymikee/jest-preset-angular/pull/230, kudos to @thymikee 
Unit test added
> feat: print error msg & stack on preset normalization error

- CHANGELOG.md
- packages/jest-resolve-dependencies/package.json
- packages/jest-resolve-dependencies/src/__tests__/dependency_resolver.test.ts
- packages/jest-resolve-dependencies/src/index.ts
- packages/jest-resolve-dependencies/tsconfig.json
- packages/jest-resolve/src/index.ts
- packages/jest-snapshot/src/index.ts
- packages/jest-snapshot/src/snapshot_resolver.ts
- packages/jest-types/src/Resolve.ts
- packages/jest-types/src/Snapshot.ts
- packages/jest-types/src/index.ts
migrate `jest-resolve-dependencies` to TypeScript
> chore: migrate jest-resolve-dependencies to TypeScript

- CHANGELOG.md
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/utils.ts
Fixes #7937: `toStrictEqual` does not consider arrays with objects having undefined values correctly
Before that change, the following assertion was failing:
```js
expect([{a: undefined}]).not.toStrictEqual([{}]);
```
Now it passes as expected.
> `toStrictEqual` does not consider arrays with objects having undefined values correctly

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/matchers.ts
- packages/jest-matcher-utils/src/__tests__/__snapshots__/index.test.ts.snap
- packages/jest-matcher-utils/src/__tests__/index.test.ts
- packages/jest-matcher-utils/src/index.ts
For matcher error in:
* `.toBeCloseTo`
* `.toBeGreaterThan`
* `.toBeGreaterThanOrEqual`
* `.toBeLessThan`
* `.toBeLessThanOrEqual`
When expected or received must be a number:
* Because matcher name does not include period, display in black instead of dim color
* With options argument, display `.not` or `.rejects` or `.resolves`
In `ensureActualIsNumber` and `ensureExpectedIsNumber` functions:
* Support backward compatible `[.not]` and dim matcher name if it does include period.
* Delete `'This matcher'` default for `matcherName` arg. I doubt it has ever been used.
**Residue** provide options to `ensureExpectedIsNumber` calls when we improve spy matchers:
* `.toHaveBeenCalledTimes` and `.toBeCalledTimes`
* `.toHaveReturnedTimes` and `.toReturn`
* jest-matcher-utils: updated 2 snapshot …
> expect, jest-matcher-utils: Improve report when matcher fails, part 9

- CHANGELOG.md
- babel.config.js
- package.json
- packages/jest-haste-map/src/index.ts
- packages/jest-resolve-dependencies/src/__tests__/dependency_resolver.test.ts
- packages/jest-resolve/src/__tests__/resolve.test.ts
- packages/jest-transform/src/ScriptTransformer.ts
- yarn.lock
`jest-haste-map` wants to do both `export = HasteMap` and multiple `export type SomeType`. Until we migrate it over to use a proper ESM default export, the way to do this in TypeScript is namespaces - see [this StackOverflow answer](https://stackoverflow.com/a/51238234). This fixes our `jest-haste-map/build/index.d.ts`:
<details>
<summary>Diff</summary>
```diff
diff --git a/tmp/old/index.d.ts b/tmp/new/index.d.ts
index ff4589f52..d2fe5bd75 100644
--- a/tmp/old/index.d.ts
+++ b/tmp/new/index.d.ts
@@ -4,9 +4,180 @@
*/
+/// <reference types="node" />
+import EventEmitter from 'events';
+import { Config } from '@jest/types';
+import H from './constants';
import HasteFS …
```
> fix jest-haste-map-types

- package.json
- yarn.lock
Upgraded to a version of `babel-plugin-typescript-strip-namespaces` that uses only es5 trailing commas. @SimenB 
test-node-6 green
> fix Node 6 build

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/matchers.ts
- packages/jest-matcher-utils/src/index.ts
For `.toHaveLength` matcher:
* Display matcher name in regular **black** instead of dim color
* Call `ensureExpectedIsNonNegativeInteger` function with `options` argument
* Display **not** following `Expected length:` label
* Experiment to **omit** received value if it is **equal to** the `not` expected value (am happy if y’all can suggest as an alternative a concise explicit way to communicate that is reason why test fails)
* Updated 14 snapshot tests
* Rewrote 2 snapshot tests for `.not`
* Added 4 snapshot tests for `.rejects` and `.resolves`
See also pictures in following comment
> expect: Improve report when matcher fails, part 10

- CHANGELOG.md
- e2e/__tests__/jestChangedFiles.test.js
- packages/jest-changed-files/src/git.ts
Fixes #7956.
Previously, `getChangedFilesFromRoots` would return parts of commit messages as if they were files, if the commit message contained multiple paragraphs of text.
I've updated the e2e tests in `jestChangedFiles.test.js` to include a commit message that includes multiple paragraphs (for both `hg` and `git`).
I decided on augmenting existing tests instead of making new ones to prevent an increase in running time.
In the case of `hg`, one of the files in the repository has had its contents changed to be on multiple lines, and one of the commits to be made with `hg commit -l filename`
It could have been done with `sh -c echo "line1\\nline2" | hg commit -l -"`, but that would have required a change of functionality in `Utils.js#run`, which I didn't feel like. 😄 
For `git`, the …
> fix(jest-changed-files): only return files from `getChangedFilesFromRoots`

- CHANGELOG.md
- packages/jest-phabricator/package.json
- packages/jest-phabricator/src/index.ts
- packages/jest-phabricator/tsconfig.json
- packages/jest-types/src/TestResult.ts
<details>
<summary>Diff</summary>
```diff
diff --git a/packages/jest-phabricator/build/index.js b/packages/jest-phabricator/build/index.js
index a55e39432..5874e38b8 100644
--- a/packages/jest-phabricator/build/index.js
+++ b/packages/jest-phabricator/build/index.js
@@ -37,7 +37,6 @@ function _defineProperty(obj, key, value) {
*
- *
*/
function summarize(coverageMap) {
const summaries = Object.create(null);
@@ -62,7 +61,6 @@ function summarize(coverageMap) {
}
module.exports = function(results) {
-  // $FlowFixMe: This should work, but it does not.
return _objectSpread({}, results, {
coverageMap: results.coverageMap && summarize(results.coverageMap)
});
``` …
> Migrate jest-phabricator to TypeScript

- docs/Configuration.md
- website/versioned_docs/version-24.0/Configuration.md
- website/versioned_docs/version-24.1/Configuration.md
Reference: https://github.com/facebook/jest/blob/master/types/TestResult.js#L128
This PR simply updates the documentation for `testResultsProcessor`. https://jestjs.io/docs/en/configuration#testresultsprocessor-string
Run `jest` with `--json`. The JSON output will contain a numeric `numTodoTests` property.
> (docs) Add missing numTodoTests in Result Object.

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/jasmineUtils.ts
Fixes #7941: `toStrictEqual` fails to distinguish 0 from 5e-324
The real problem is that the `equal` operation defined into `jasmineUtils` is not symmetric.
Before that change, the following assertion was failing:
```js
expect(0).not.toStrictEqual(5e-324);
```
Now it passes as expected.
> Fix asymmetric equal for Number

- CHANGELOG.md
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
- packages/jest-environment/src/index.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-runtime/src/cli/index.ts
- packages/jest-runtime/src/index.ts
Played around with it in #7985, and these were the changes I had to make to allow us to do `class NodeEnvironment extends JestEnvironment` and get proper typings
Green CI
> chore: cleanup JestEnvironment types

- docs/GettingStarted.md
- website/versioned_docs/version-24.0/GettingStarted.md
The instructions said that support for typescript was included "out of the box" but failed to mention that it is necessary to install and configure `@babel/preset-typescript`.
N/A
> Improve instructions for enabling typescript support

- CHANGELOG.md
- packages/jest-repl/package.json
- packages/jest-repl/src/cli/args.ts
- packages/jest-repl/src/cli/index.ts
- packages/jest-repl/src/cli/repl.ts
- packages/jest-repl/tsconfig.json
This PR migrates jest-repl to typescript. 
Notes:
1. I have one ts-ignore in index.ts
2. Importing package.json outside of the rootDir causes the compiler to fail
> [WIP] Migrate jest-repl to typescript

- CHANGELOG.md
- packages/jest-haste-map/src/index.ts
The `skipHastePackages` option prevents reading of `package.json` files and keeps them out of the module map. It's important to fixing package deduplication in Metro (see here: https://github.com/facebook/metro/issues/350), especially after symlink support is merged (see here: https://github.com/facebook/metro/pull/257).
With support for symlinks in `node_modules`, it's very easy for the dependencies of one "locally developed" package to collide with another package's dependencies, which results in frustrating errors that are entirely avoidable.
I tested it manually. Works great! I don't have time to get familiar with your test suite.
> feat: add "skipHastePackages" option

- CHANGELOG.md
- packages/jest-haste-map/src/__tests__/__snapshots__/index.test.js.snap
- packages/jest-haste-map/src/__tests__/index.test.js
- packages/jest-haste-map/src/index.ts
- packages/jest-runtime/src/__tests__/runtime_require_mock.test.js
This PR changes the way duplicated mocks and haste names are reported. The current way allows to have multiple times the same name, but emits a warning. After two years of having the warning in, I can tell you **no one** looks at it; so this diff starts enforcing them to be unique.
I also took the opportunity to standardize and simplify error messaging, since it was nearly impossible to read.
**Before:**
```
jest-haste-map: duplicate manual mock found:
Module name: subdir/Blueberry
Duplicate Mock path: /project/fruits2/__mocks__/subdir/Blueberry.js
This warning is caused by two manual mock files with the same file name.
Jest will use the mock file found in:
/project/fruits2/__mocks__/subdir/Blueberry.js
Please delete one of the following two files: …
```
> Simplify and enforce duplicate haste map errors

- CHANGELOG.md
- e2e/__tests__/failures.test.ts
- e2e/failures/__tests__/errorAfterTestComplete.test.js
- packages/jest-circus/src/utils.ts
- packages/jest-jasmine2/src/jasmine/Env.js
This is #6794 with a test.
The error isn't pretty, but I think it's fine. Since we're tearing down (and use lazy requires), we might get an error when trying to prettify it
Green CI
> Fix missing error after test

- e2e/__tests__/detectOpenHandles.ts
- packages/jest-circus/src/utils.ts
I thought the failure in #8005 was flaky - it wasn't :( This fixes the test.
Green CI
> chore: fix broken test in circus

- .eslintrc.js
- packages/expect/src/spyMatchers.ts
- packages/jest-changed-files/src/index.ts
- packages/jest-config/src/normalize.ts
- packages/jest-diff/src/diffStrings.ts
- packages/jest-docblock/src/index.ts
- packages/jest-message-util/src/index.ts
- packages/jest-mock/src/index.ts
- packages/jest-resolve-dependencies/src/index.ts
- packages/jest-resolve/src/index.ts
- packages/jest-resolve/src/nodeModulesPaths.ts
- packages/jest-runtime/src/index.ts
- packages/jest-snapshot/src/__tests__/plugins.test.ts
- packages/jest-snapshot/src/inline_snapshots.ts
- packages/jest-snapshot/src/snapshot_resolver.ts
- packages/jest-validate/src/validateCLIOptions.ts
- packages/pretty-format/src/__tests__/AsymmetricMatcher.test.ts
- packages/pretty-format/src/__tests__/prettyFormat.test.ts
- packages/pretty-format/src/index.ts
- packages/pretty-format/src/plugins/ReactElement.ts
The TypeScript sources currently use `Array<T>` and `T[]` inconsistently.
This makes it harder to grep for e.g. `Array<Test>` or `Test[]` because you might miss some of them that use the other syntax.
It might also confuse TS beginners who wonder what the difference between the two might be.
`eslint-typescript` has the `array-type` rule to enforce one syntax or the other (or alternatively `[]` for simple types and `Array` for complex ones).
I've set it to `'array'` (`[]`) and run the auto fixer, but I'd be open to discussion / links to convince me why another option would be better ;)
> use typescript-eslint array-type rule

- CHANGELOG.md
- CONTRIBUTING.md
New contributors to jest may not know about how to use `jest_circus` when running the jest test suite. 
This PR updates the `CONTRIBUTING.md` to add information about that.
> Update contributing to add information about jest_circus

- CHANGELOG.md
- packages/jest-each/src/bind.ts
- packages/jest-each/src/index.ts
- packages/jest-each/src/table/array.ts
- packages/jest-each/src/table/template.ts
- packages/jest-each/src/validation.ts
- packages/jest-types/src/Global.ts
This PR refactors `jest-each` to make it more modular and have better type definitions both of which I am hoping will make it easier to maintain.
All existing tests (unit and e2e) should still pass.
> [jest-each] refactor into multiple files with better types

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/matchers.ts
- packages/expect/src/print.ts
- packages/jest-matcher-utils/src/index.ts
For `.toContain`, `.toContainEqual`, and `.toMatch`:
* Display `rejects` or `resolves` in matcher hint
* Display comment in hint when `toContain` or `toContainEqual` throw matcher error
* Display `not` following expected label
* Inverse highlight the not-expected substring or array item in received value
Your critique about clarity is especially welcome, because I had to wrestle with the code not to add any more `any` type than the one already in `toContain` matcher.
**Design discussion** your thoughts are welcome for a possible future pull request:
* Is `// indexOf` comment in matcher hint for `toContain` confusing if received is iterable (for example, set) instead of …
> expect: Improve report when matcher fails, part 11

- CHANGELOG.md
- packages/jest-environment-node/src/index.ts
Added missing globals to jest-environment-node. Use the same approach as the URL. 
These were added in node 11:  https://nodejs.org/api/globals.html#globals_textdecoder
I tested locally with yarn link. I am not sure if pipeline have node11?
> Added missing TextEncoder and TextDecoder to jest-envirotment-node

- CHANGELOG.md
- packages/jest-circus/package.json
- packages/jest-circus/src/formatNodeAssertErrors.ts
- packages/jest-circus/tsconfig.json
- packages/jest-diff/src/index.ts
- packages/jest-matcher-utils/src/index.ts
We want to export `DiffOptions` from `jest-diff` so it can be used as a parameter at usage sites
Green CI
> chore: export `DiffOptions` from `jest-diff`

- .eslintrc.js
- packages/expect/src/asymmetricMatchers.ts
- packages/expect/src/types.ts
- packages/jest-circus/src/types.ts
- packages/jest-config/src/ReporterValidationErrors.ts
- packages/jest-diff/src/index.ts
- packages/jest-environment/src/index.ts
- packages/jest-haste-map/src/index.ts
- packages/jest-mock/src/index.ts
- packages/jest-runtime/src/index.ts
- packages/jest-source-map/src/__tests__/getCallsite.test.ts
- packages/jest-types/src/Config.ts
- packages/jest-types/src/TestResult.ts
- packages/jest-util/src/createProcessObject.ts
- packages/jest-worker/src/index.ts
- packages/pretty-format/src/collections.ts
- packages/pretty-format/src/plugins/ReactTestComponent.ts
All changes were autofixed
Green CI
> chore: use `ban-types` eslint rule

- CHANGELOG.md
- packages/jest-circus/src/globalErrorHandlers.ts
- packages/jest-core/src/ReporterDispatcher.ts
- packages/jest-core/src/TestScheduler.ts
- packages/jest-core/src/types.ts
- packages/jest-core/tsconfig.json
- packages/jest-haste-map/src/crawlers/node.ts
- packages/jest-reporters/src/index.ts
- packages/jest-worker/src/workers/ChildProcessWorker.ts
- yarn.lock
Forgot to clean this up, and (probably due to a race condition due to missing `references` entry) this didn't show up on CI.
Green CI
> chore: use types from @jest/reporter in @jest/core

- packages/jest-haste-map/package.json
- packages/jest-haste-map/src/index.ts
- yarn.lock
A module called `merge` that is dependent on by transitive dependencies of `jest-haste-map` contains a vulnerability. With this PR, I am updating `sane` (the direct dependency) that will remove this vulnerability.
Note that it is still part of the overall `yarn.lock` because of react-native depending on Metro depending on an older version of `jest-haste-map`. This will eventually be all upgraded in the future, but we gotta start somewhere :)
> Upgrade sane to 4.0.3

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/toThrowMatchers.test.js.snap
- packages/expect/src/__tests__/toThrowMatchers.test.js
- packages/expect/src/toThrowMatchers.ts
For `.toThrow` and `.toThrowError` matchers:
* Display `not` following expected label
* Inverse highlight not-expected substring or pattern in received error message
* Omit received error message for object instance because criterion is `===` strict equality
**Residue**
* Improve report for **error class** if received `error.name` is not the same as `error.constructor.name` probably together with `.toBeInstanceOf` matcher
* Breaking change to require `.exec` method in addition to `.test` method for RegExp
Change error message to more realistic `"Invalid array length"` in 6 `.not` snapshots
Chore in snapshot names:
* replace `.toThrow()` and `.toThrowError()` with `toThrow` and `toThrowError`
* replace `strings` with `substring` …
> expect: Improve report when matcher fails, part 12

- CHANGELOG.md
- docs/Configuration.md
- website/versioned_docs/version-22.x/Configuration.md
- website/versioned_docs/version-23.x/Configuration.md
- website/versioned_docs/version-24.0/Configuration.md
- website/versioned_docs/version-24.1/Configuration.md
Add info related to manual mocks for node module mocks.
Closes #8049
> Add note to automock configuration

- CHANGELOG.md
- packages/jest-util/src/createProcessObject.ts
If we do not do this, Jest fails horribly on Node 12 (tested with yesterday's nightly release)
Beyond this failure, the only things that fails are the leak detector tests since `weak` does not compile on Node 12
Green CI (although we don't test node 12 yet, at least avoid regressions)
> fix: handle process[toString] being readonly on newer nodes

- CHANGELOG.md
- packages/jest-haste-map/src/__tests__/index.test.js
- packages/jest-haste-map/src/crawlers/__tests__/node.test.js
- packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js
- packages/jest-haste-map/src/crawlers/node.ts
- packages/jest-haste-map/src/crawlers/watchman.ts
- packages/jest-haste-map/src/index.ts
This is a minor PR to improve the performance of tracking deleted files by taking advantage of Watchman when available.
Currently, deleted files are tracked within jest-haste-map by:
1. Making a shallow copy of the Haste Map files before building the file map.
2. Filtering the shallow copy against the generated file map to remove all files that still exist.
Benchmarking this operation against a large locally-generated test Haste Map of 300k~ files with one deletion, the operation currently takes about 150ms on my machine and grows linearly with more files tracked. Using Watchman makes it almost free and only grows with the number of files changed.
I've updated the non-Watchman implementation to also track deleted files within the crawler to keep the interface consistent, although that …
> Optimize haste map tracking of deleted files with Watchman.

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/matchers.ts
For more information, see https://github.com/facebook/jest/pull/7986#issuecomment-470148520
Commented out one test until it is time to make a breaking change
> expect: Revert change to distinguish undefined value from no property

- packages/jest-changed-files/src/hg.ts
When running in `master` with Mercurial, it throws due to an empty revision set. This PR fixes it, see reply in https://github.com/facebook/jest/pull/7880#issuecomment-468968754.
Tested locally with the use of `hg log --rev`, under bookmarks, branches and public commits.
> Fix pattern for HG changed files

- CHANGELOG.md
- e2e/__tests__/fatalWorkerError.test.ts
- packages/jest-worker/src/workers/ChildProcessWorker.ts
- packages/jest-worker/src/workers/NodeThreadsWorker.ts
- packages/jest-worker/src/workers/__tests__/ChildProcessWorker.test.js
- packages/jest-worker/src/workers/__tests__/NodeThreadsWorker.test.js
Handling of errors in workers in `jest-worker` worker is broken which causes several observable issues:
- Jobs are never retried
- Errors are not notified (as we're waiting for the retries), so Jest hangs when a worker has an error (fixes #8068)
Added unit tests for the workers to make sure messages are re-send to the workers after they're initialized, and an e2e test that makes sure we handle fatal errors in tests properly.
> Fix retries and error notification in workers

- CHANGELOG.md
- packages/jest-worker/src/types.ts
- packages/jest-worker/src/workers/ChildProcessWorker.ts
- packages/jest-worker/src/workers/NodeThreadsWorker.ts
A `null` check was added in https://github.com/facebook/jest/pull/8045#discussion_r262154917. However, it most certainly _can_ be `null`, and the type definition for `WorkerInterface` was wrong. `jest-runner` even guards against it: https://github.com/facebook/jest/blob/1fd565168dbf5b49780df959a214148eb35d32db/packages/jest-runner/src/index.ts#L113-L114
Fixes #8078
Not really a testable change since the unit tests mock out `child_process.fork`. However, the type is now corrected.
> fix: jest-worker can return `null` for `getStdout()`

- CHANGELOG.md
- packages/jest-worker/package.json
- packages/jest-worker/src/workers/ChildProcessWorker.ts
- packages/jest-worker/src/workers/NodeThreadsWorker.ts
- packages/jest-worker/src/workers/__tests__/ChildProcessWorker.test.js
- packages/jest-worker/src/workers/__tests__/NodeThreadsWorker.test.js
A worker pool exposes a unified stdout and stderr resulting from the combination of all the outputs from the workers it contains. The problem is that the workers only expose stdout/stderr from the first child they spawn and never re-attach the output of any subsequent child they might spawn after an initial one dies (for retries).
This changes both worker implementations (child process and node threads) to return a merged stream, resulting of the combination of all their possible children, so that output isn't lost.
Added unit tests for both
> Re-attach stdout and stderr from new processes after retries

- .yarnrc
- tsconfig.json
This diff uses the `yarn-path` configuration settings to ensure that Jest always run with the specified Yarn release, regardless of the one used in the global environment.
I've also removed `workspaces-experimental` since it's not required anymore.
Ran `yarn -v` in the repo, got `1.15`. CI should print it as well.
> Bumps Yarn to 1.15

- CHANGELOG.md
- packages/expect/src/index.ts
- packages/expect/src/types.ts
We know which matchers we have, no reason to just have it as an index string.
Future improvements:
- verify that extending the exported `Matcher` interface actually mixes new matchers into the correct interface
- move snapshot matchers out. They should be added wherever we declare the global `expect` variable (or potentially mixed in in `jest-circus`/`jest-jasmine2` if possible)
- get rid of type casts and actually ensure statically that
- all matchers adhere to the contract
- we export all the matchers we say we do
- we don't export any matchers we don't say we do
TS build should still succeed
> add matchers to expect type

- CHANGELOG.md
- e2e/__tests__/__snapshots__/showConfig.test.ts.snap
- packages/jest-config/src/Defaults.ts
- packages/jest-config/src/ValidConfig.ts
- packages/jest-runtime/src/index.ts
- packages/jest-types/src/Config.ts
- types/Config.js
This will let people configure whether two mocks with the same name should crash or not. However, as other `haste` options, it will not be documented.
> Expose throwOnModuleCollision

- CHANGELOG.md
This changelog entry was incorrectly added to the previous version instead of to master.
> Move changelog entry to the proper version

- CHANGELOG.md
- package.json
- packages/jest-circus/package.json
- packages/jest-console/package.json
- packages/jest-environment/package.json
- packages/jest-fake-timers/package.json
- packages/jest-haste-map/package.json
- packages/jest-util/package.json
- packages/jest-watcher/package.json
- packages/jest-worker/package.json
- yarn.lock
Fixes #8092. 
> Anybody wanna send a PR? We can just add @types/node to the root package.json and remove it from the individual packages.
> Note that this is just @types/node, all other @types/* should remain
https://github.com/facebook/jest/issues/8092#issuecomment-472339505
N/A.
> Move @types/node to the root package.json

- CHANGELOG.md
- docs/ExpectAPI.md
- website/versioned_docs/version-24.0/ExpectAPI.md
Fixes #8059
We fix the doc now, and then at next major version will make breaking change to throw new errors when `toMatchSnapshot` has unexpected combinations of arguments.
For example, if first argument is object, but second argument is not object. /cc @morungos
* Append `?` to optional arguments in headings.
* Rewrite corresponding prose so `optional` always occurs.
For local test of website to make sure `?` didn’t break links, I had to make corresponding changes to the versioned doc, but I forget if I needed to commit that change, or is it is automatic?
| matcher | optional arguments |
| :--- | :--- |
| `toBeCloseTo` | `numDigits` |
| `toHaveProperty` | `value` |
| `toMatchSnapshot` | `propertyMatchers` and `snapshotName` |
| `toMatchInlineSnapshot` | `propertyMatchers` |
| `toThrow` …
> chore: Improve description of optional arguments in ExpectAPI.md

- CHANGELOG.md
- packages/pretty-format/src/__tests__/prettyFormat.test.ts
- packages/pretty-format/src/index.ts
I was experimenting with BigInt numbers and noticed that Jest will not print these correctly in diffs. For example, for
```js
const f = {
a: BigInt(1),
b: BigInt(2)
}
```
Jest would print the diff something like
```
Received: f {a: {}, b: {}}
Expected: f {a: {}, b: {}}
```
because `pretty-format` thinks `BigInt` is an object.
I made BigInts print with an `n` appended, like they print in the browser and Node so that the above would print something like this instead
```js
Received: f {a: 1n, b: 2n}
Expected: f {a: 2n, b: 1n}
```
I added unit tests that mimic the unit tests for number types.
> Add support for bigint to pretty-format

- CHANGELOG.md
- packages/jest-each/src/index.ts
Fixes: #8144 
Types should pass
> [jest-each] Fix test function type

- CHANGELOG.md
- packages/jest-fake-timers/src/__tests__/jestFakeTimers.test.ts
- packages/jest-fake-timers/src/jestFakeTimers.ts
I assume this is how the getTimerCount method was supposed to work. Otherwise it's pretty useless.
I included moving to Map, so that the function doesn't incur an O(n) size check, because I'm running this in a pretty tight loop.
Added unit test.
> fix: getTimerCount not taking immediates and ticks into account

- CHANGELOG.md
- jest.config.js
- package.json
- yarn.lock
I love the typeahead so much and think Jest should use it internally too!
> Add typeahead watch plugin

- packages/jest-circus/src/types.ts
For some circus events that we attach `asyncError`s to ourselves in `index.ts`, we actually know that we're not going to attach something that's not an `Error`, so we can be more precise than `Exception` (which is an alias of `any`). Events that get `asyncError`s thrown by user code keep `asyncError: Exception` (`any`).
This e.g. types the `.message = ` in https://github.com/facebook/jest/blob/b97ac394ae4b1b5b8b8b69eb1d7b373642746c02/packages/jest-circus/src/eventHandler.ts#L46
correctly instead of just allowing it because of `any`
> more precise circus asyncError types

- .gitignore
- CHANGELOG.md
- package.json
- scripts/buildTs.js
- yarn.lock
The RC had a bug, so using nightly for now. It works surprisingly well and subsequent builds are way faster than with `3.3` :)
Green CI.
>  chore: upgrade TS to 3.4.0-dev* for inceremental builds

- docs/ExpectAPI.md
- website/versioned_docs/version-22.x/ExpectAPI.md
- website/versioned_docs/version-23.x/ExpectAPI.md
- website/versioned_docs/version-24.0/ExpectAPI.md
A small note in `expect.extend()` documentation for TypeScript users since it's not obvious how to declare  types for custom marchers. 
Thanks, keep it up!
> TypeScript custom matchers declaration snippet

- CHANGELOG.md
- packages/jest-worker/package.json
- packages/jest-worker/src/workers/processChild.ts
Follow up to https://github.com/facebook/jest/pull/5313.
Test failure seems unrelated.
> Move from "process.exit" to "exit"

- CHANGELOG.md
- packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js
- packages/jest-haste-map/src/crawlers/watchman.ts
- packages/jest-haste-map/src/index.ts
At Facebook, in a common situation where you've changed a couple of files in the largest haste map, this PR cuts off 25%~ of the startup time. In other less common situations where you've working on a smaller haste map, the improvement is 60%~.
The improvement is gained by:
- Not re-serializing and writing the haste map to disk if it was loaded off of disk and then not changed.
- Not re-creating from scratch the `map` and `mocks` part of the haste map on startup when we know what specific files were changed. Instead, just re-process only the specific changed files.
I've benchmarked the startup time by:
1. Setting up a single test
2. Running once to prime the cache
3. Changing a test file
4. Running the test again with `--skipFilter` (measuring at this point via `time`)
I've been a bit …
> Perf improvements - avoid persisting haste map / processing files when not changed.

- CHANGELOG.md
- e2e/__tests__/testEnvironment.test.ts
- e2e/test-environment/EsmDefaultEnvironment.js
- e2e/test-environment/__tests__/esmDefault.test.js
- packages/jest-core/src/runGlobalHook.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-util/src/index.ts
- packages/jest-util/src/interopRequireDefault.ts
Like #7750, but for `testEnvironment`s
Added e2e test
> support 'export default TestEnvironment'

- e2e/__tests__/hasteMapMockChanged.test.ts
- packages/jest-haste-map/src/index.ts
This fixes a regression introduced by: https://github.com/facebook/jest/pull/8153
I've fixed it by using the same logic already present for modules, which also check to be sure the file path isn't a match before warning.
I added an e2e test that catches the behavior to ensure this regression will not happen again.
To reproduce manually:
1. Run `yarn jest packages/jest-haste-map/src/__tests__/index.test.js` (or any other test)
2. Make any change to a mock file, for example add a comment to `packages/jest-config/src/__mocks__/fs.js`
3. Run Jest again, the warning `jest-haste-map: duplicate manual mock found: fs` incorrectly shows up
> Fix incorrect duplicate mock warning.

- CHANGELOG.md
- packages/jest-reporters/src/__tests__/__snapshots__/generateEmptyCoverage.test.js.snap
- packages/jest-reporters/src/__tests__/generateEmptyCoverage.test.js
- packages/jest-reporters/src/generateEmptyCoverage.ts
This PR is meant to fix https://github.com/facebook/jest/issues/7758. In the provided GitHub issue link there are repro steps, also an explanation of the fix applied in this PR https://github.com/facebook/jest/issues/7758#issuecomment-474390342.
A new pair of tests were added to cover these changes.
> Jest Output:
```
➜  jest git:(fix-cannot-read-property-converageData-of-null) yarn jest-coverage -u packages/jest-reporters/src/__tests__/generateEmptyCoverage.test.js
yarn run v1.15.0
$ yarn jest --coverage -u packages/jest-reporters/src/__tests__/generateEmptyCoverage.test.js
$ node ./packages/jest-cli/bin/jest.js --coverage -u packages/jest-reporters/src/__tests__/generateEmptyCoverage.test.js
PASS  packages/jest-reporters/src/__tests__/generateEmptyCoverage.test.js
generateEmptyCoverage …
```
> fix: Error Cannot read property converageData of null #7758

- package.json
For `e2e/global-setup-node-modules/node_modules/example/index.js` see https://github.com/facebook/jest/pull/8143#issuecomment-474836744
Edited `clean-e2e` script:
* Added `-not \( -path ./e2e/global-setup-node-modules -prune \)`
* Edited `-mindepth 1` because `-mindepth 2` filtered out the exception
/cc @Volune
We give `CHANGELOG.md` a miss for small follow-up fix, true?
`yarn clean-all && yarn`
`git status`
`yarn test`
> Add exception to clean-e2e for global-setup-node-modules

- CHANGELOG.md
- packages/pretty-format/src/__tests__/react.test.tsx
- packages/pretty-format/src/plugins/ReactElement.ts
Resolves #8178
> The ReactElement is not aware of the React.Suspense component type, and as a result it causes snapshots to display "UNDEFINED". Fortunately it looks like this serializer is built on top of react-is which already exports a isSuspense so it should hopefully be easy to add this. 😄
- Added unit test. Verified that it failed previously with `UNDEFINED` as described in the bug report. It now passes.
> Support React.Suspense in snapshots.

- CHANGELOG.md
- packages/jest-haste-map/src/HasteFS.ts
- packages/jest-haste-map/src/__tests__/index.test.js
- packages/jest-haste-map/src/constants.ts
- packages/jest-haste-map/src/crawlers/__tests__/node.test.js
- packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js
- packages/jest-haste-map/src/crawlers/node.ts
- packages/jest-haste-map/src/crawlers/watchman.ts
- packages/jest-haste-map/src/index.ts
- packages/jest-haste-map/src/types.ts
This simple PR is the result of a ridiculous number of attempts to specifically optimize the serialization and deserialization of the haste map followed by a simple realization: creating arrays is expensive. :)
Currently, we store each file's dependencies as an expensive array. However, we don't typically access many file dependencies, so it's not time well-spent.
I've modified the data structure to store the file dependencies as a much cheaper string (tab separated) that is deserialized to an array on-demand. No change to the public interface, but now we're not doing any unnecessary work.
I profiled both the full Jest run time and the read/persist time to ensure I had a clear view into the characteristics of this change. It's somewhere in the neighborhood of a 10%~ startup time …
> Optimize haste map data structure for serialization/deserialization.

- docs/ExpectAPI.md
- website/versioned_docs/version-22.x/ExpectAPI.md
- website/versioned_docs/version-23.x/ExpectAPI.md
- website/versioned_docs/version-24.0/ExpectAPI.md
I added a function definition to give greater context to weird octopus reference ¯\_(ツ)_/¯
As a junior developer that is new to Jest, I found this example really confusing. To make it clearer (the octopus reference really threw me off), I added a simple function to add context.
> made toHaveBeenCalled example clearer

- CHANGELOG.md
- e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
- e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
- packages/jest-resolve/src/index.ts
`jest-resolve` is called heavily by `jest-resolve-dependencies` when finding related tests. Benchmarking the simple change from `Object` to `Map` for the internal cache shows an 18% improvement in the total run time of `dependencyResolver.resolveInverse` for a test data set of 300k~ files, although obviously the performance characteristics are going to vary depending on the data set.
At Facebook, this PR means when I run just Jest to look at my changed files and run the appropriate tests, it boots up 2 seconds faster.
- All tests pass. New tests not appropriate for this simple change.
- Tested manually.
- Benchmarked to ensure performance improvement.
> jest-resolve 18% performance optimization

- CHANGELOG.md
- packages/jest-core/src/SearchSource.ts
- packages/jest-core/src/getNoTestFoundVerbose.ts
- packages/jest-core/src/types.ts
This PR is a 15% performance improvement for `SearchSource.findMatchingTests`. I benchmarked a test data set of 300k files at 975ms~ with the current code. The same search pattern now executes in 830ms~.
At Facebook, this means that for the common use case of triggering `jest MyFileName`, Jest will launch >100ms faster. Sometimes you have to take the small wins. :)
I optimized this by looking for inefficiencies in code that is called for every file. In this case:
- One of the inner functions triggered for each file called `Object.keys` for the `stats` object every time. Not efficient.
- Dummy functions were being created that always returned true. It still costs CPU time to call a function, even an extremely fast one. Better to never call it.
I refactored away the issues by adapting the …
> Improve performance of SearchSource.findMatchingTests by 15%

- CHANGELOG.md
- e2e/__tests__/__snapshots__/toMatchInlineSnapshot.test.ts.snap
- packages/jest-haste-map/src/index.ts
- packages/jest-snapshot/src/__tests__/inline_snapshots.test.ts
- packages/jest-snapshot/src/index.ts
- packages/jest-snapshot/src/inline_snapshots.ts
Inline snapshots are currently ugly. Not only are they not indented by default, but the matcher will fail if you indent them manually. This PR adds support for indented inline snapshots.
A few things to note:
- Non-indented snapshots will continue to pass and will not be updated automatically unless a snapshot in the file is updated.
- The extra indentation is not reflected in the reporter.
When/if this PR is accepted, I'll be trying to make a PR into Prettier for better UX, since Prettier won't currently update your inline snapshots formatting automatically.
- All existing tests pass, including e2e snapshot tests for inline tests.
- Added a few more test cases specifically for this feature.
- Tested manually against real tests.
> Indented inline snapshots.

- docs/CLI.md
- packages/jest-config/src/__tests__/getMaxWorkers.test.ts
- packages/jest-config/src/getMaxWorkers.ts
- website/versioned_docs/version-22.x/CLI.md
- website/versioned_docs/version-23.x/CLI.md
- website/versioned_docs/version-24.0/CLI.md
- website/versioned_docs/version-24.1/CLI.md
Revert change to number of CPUs and add docs to resolve @cpojer comment:
https://github.com/facebook/jest/pull/8201#issuecomment-476221537
Benchmarked Jest non-e2e test performance for this branch from 14.973s to 16.504s, which is still a massive win over the original 23.234s and probably points to further optimizations being possible since I'd hope that giving it 5 extra CPUs would do more for the performance.
- All tests pass, including the test that specifically touches this number.
> Watch mode number of CPUs & documentation.

- docs/Configuration.md
- website/versioned_docs/version-24.1/Configuration.md
A link in the documentation around reporters seems to be broken since the big move to Typescript. This PR updates the link to the appropriate location. 🎉
> Docs: Fixing link to reporter interface

- .circleci/config.yml
- e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
- e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
- packages/expect/src/jasmineUtils.ts
- packages/jest-cli/src/init/__tests__/init.test.js
- packages/jest-config/src/setFromArgv.ts
- packages/jest-jasmine2/src/assertionErrorMessage.ts
- packages/jest-jasmine2/src/index.ts
- packages/jest-jasmine2/src/setup_jest_globals.ts
- packages/jest-resolve/src/index.ts
- packages/jest-util/src/deepCyclicCopy.ts
- packages/jest-worker/src/WorkerPool.ts
- packages/jest-worker/src/workers/processChild.ts
> remove flow leftovers

- CHANGELOG.md
- packages/jest-worker/src/workers/ChildProcessWorker.ts
- packages/jest-worker/src/workers/NodeThreadsWorker.ts
- packages/jest-worker/src/workers/__tests__/ChildProcessWorker.test.js
- packages/jest-worker/src/workers/__tests__/NodeThreadsWorker.test.js
Fixes #8204 
It's weird that it's 1-indexed (I looked at making our `workerId` 1-indexed too for consistency, but that would make our code really weird), but I guess it's documented, used to work like that and still does for `runInBand` 🤷‍♂️
> fix 1-indexed JEST_WORKER_ID

- CHANGELOG.md
- packages/jest-config/src/Defaults.ts
- packages/jest-config/src/ValidConfig.ts
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/normalize.ts
- packages/jest-types/src/Config.ts
Fixes #7857, check that issue for details
> use default cwd even if config contains a cwd property

- CHANGELOG.md
- packages/jest-resolve-dependencies/package.json
- packages/jest-resolve-dependencies/src/index.ts
- packages/jest-resolve/package.json
- packages/jest-resolve/src/index.ts
- packages/jest-snapshot/package.json
- packages/jest-snapshot/src/index.ts
Resolves https://github.com/facebook/jest/issues/8107
Please see the issue for the motivation.
Moved peerDependencies that are served inside the monorepo to dependencies.
N/A
> Remove monorepo-internal peer dependencies (temporarily)

- CHANGELOG.md
- e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
- e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
- packages/jest-resolve/src/index.ts
- packages/jest-runtime/src/__tests__/runtime_require_actual.test.js
This PR fixes #7981 , requireActual not work with moduleNameMapper, witch currently throws an error. 
This PR make `jest-resolve` `resolveModule` invoke `resolveStubModuleName`, which resolves module with moduleNameMapper. `resolveStubModuleName` is invoked before `resolveModuleFromDirIfExists`, so that moduleNameMapper config can override default behavior.
Test requireActual with a moduleNameMapper configuration, and it should resolve the module successfully.
> Fix requireActual fail with moduleNameMapper

- CHANGELOG.md
- packages/jest-runtime/src/__tests__/runtime_require_module.test.js
- packages/jest-runtime/src/index.ts
Quick benchmark of getting `Map` vs `Object` for string keys of various lengths on Node v11:
```
get object key x   278 ops/sec ±2.28% (85 runs sampled)
get map key    x 1,716 ops/sec ±1.35% (93 runs sampled)
```
- All tests pass.
- Tested against FB's test suite.
> Performance: use Map for jest-runtime module registry.

- CHANGELOG.md
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
- packages/jest-console/src/BufferedConsole.ts
- packages/jest-console/src/CustomConsole.ts
- packages/jest-console/src/__tests__/bufferedConsole.test.ts
- packages/jest-core/src/ReporterDispatcher.ts
- packages/jest-reporters/src/default_reporter.ts
- packages/jest-test-result/src/helpers.ts
- packages/jest-test-result/src/types.ts
The reference to the console output is printed to `stdout` when the test completes and not used afterwards. Unfortunately, it's currently preserved, never being released. It's not used after that point and can be garbage collected.
I also standardized the "no buffer" output to `undefined`, when it previously could have been an empty array or `null`.
- All tests pass.
- Console output still works as expected.
- Memory does not leak.
- JSON output is unchanged.
> Memory leak fix: release console output reference after printed to stdout.

- CHANGELOG.md
- packages/jest-core/src/ReporterDispatcher.ts
- packages/jest-reporters/src/coverage_reporter.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-test-result/src/formatTestResults.ts
- packages/jest-test-result/src/types.ts
Previously, `sourceMaps`:
- Was always populated with a call to `getSourceMapInfo` and set to an object, even when it was guaranteed to be empty.
- Was never released from memory.
It's companion, `coverage`, was released from memory but unfortunately using the `delete` operator, which is significantly slower than `= undefined` even with modern V8 versions:
https://jsperf.com/delete-vs-undefined-vs-null/87
I've resolved the leak and minor performance issues along with a minor change to `formatTestResults` that is slightly more efficient for the same result.
- All tests pass.
- Memory and performance characteristics verified.
> Memory leak fix: release source map info after processed and minor optimizations

- CHANGELOG.md
- packages/jest-transform/src/ScriptTransformer.ts
This PR improves performance by caching the regular expression string -> `RegExp` conversion.
Benchmarks on cached regular expression vs. creating new each time:
```
new regex x   596 ops/sec ±0.95% (97 runs sampled)
cached regex  x 1,668 ops/sec ±0.61% (97 runs sampled)
```
For large projects, Jest may process a LOT of files. The more workers in use, the higher chance that the same file is processed multiple times. Additionally, each time it's hit multiple regular expressions may be tested against.
The benchmark I used:
```js
suite.add('new regex', function() {
for (var i = 0; i < 10000; i++) {
new RegExp('^.+\\.[jt]sx?$').test(
'jest/packages/jest-haste-map/src/__tests__/haste_impl.js'
);
}
});
suite.add('cached regex', function() {
const regex = new RegExp('^.+\\.[jt]sx?$');
for (var i …
```
> Performance: Cache regular expression instead of creating anew for every file in ScriptTransformer.

- CHANGELOG.md
- packages/jest-haste-map/src/ModuleMap.ts
- packages/jest-runner/src/__tests__/testRunner.test.js
- packages/jest-runner/src/index.ts
- packages/jest-runner/src/testWorker.ts
This PR unifies the way module maps are passed to the worker. Previously, we did it one way for watch mode and a different way for non-watch mode because our watch mode way was a lot slower.
I fixed that slowness for watch mode and realized while doing some performance and memory profiling that the watch mode way is now actually faster on a few levels:
1) It's straight-up faster to transmit it to the process because the module map is significantly smaller than the whole haste map you have to deserialize if you get at it via the file.
2) If you load the whole haste map and want to discard half of it, suddenly there is a bunch of stuff that will need to be GC'd in the future. This happens in the worker because it only wants the module map but has to deserialize the whole file.
3) Not …
> Unify worker module map transmission w/ small perf benefit.

- jest.config.js
- package.json
- packages/expect/src/__tests__/__arbitraries__/sharedSettings.ts
- packages/expect/src/__tests__/matchers-toContain.property.test.ts
- packages/expect/src/__tests__/matchers-toContainEqual.property.test.ts
- packages/expect/src/__tests__/matchers-toEqual.property.test.ts
- packages/expect/src/__tests__/matchers-toStrictEqual.property.test.ts
- yarn.lock
Following discussions with @jeysal and @SimenB in the PR #7938, I open a PR to add property based tests into the CI of Jest.
**In a nutshell what it property based testing:**
Property based can be classified as being some kind of fuzzing technic. The need for such technic comes from the fact that it is difficult and barely impossible to cover all the edge cases a code can have with classical unit-tests (so called example based tests).
Property based framework relies on assessing whether a property stays true for any valid inputs. It can be summarized by the following *mathematical* statement:
> for all (x, y, ...)
> such as precondition(x, y, ...) holds
> property(x, y, ...) is true
In case of failure, it is able to reduce the randomly generated `x`, `y` to smaller entries to be more …
> Add fuzzing based tests in Jest (retry PR8012)

- CHANGELOG.md
- packages/jest-haste-map/package.json
- packages/jest-haste-map/src/index.ts
- packages/jest-haste-map/src/lib/FSEventsWatcher.ts
- yarn.lock
Resolves https://github.com/facebook/jest/issues/8088 by vendoring FSEvents.
Ideally in the long-term this can be removed with the next release of `fsevents`. See @SimenB's comment here: https://github.com/facebook/jest/issues/8088#issuecomment-479046441
Changes to FSEvents when brought over from sane:
- Added type safety
- Converted `Object` `_tracked` to `Set` for perf.
- Works locally.
- Tests pass.
- Was previously used code, so was previously well tested in the wild.
Additional sanity checks appreciated.
> Fix fs watcher EMFILE error.

- packages/jest-test-sequencer/package.json
Directory field incorrect in new package.
Not applicable.
> Fix `jest-test-sequencer` incorrect directory field.

- CHANGELOG.md
- packages/jest-console/src/CustomConsole.ts
- packages/jest-console/src/__tests__/CustomConsole.test.ts
- packages/jest-runner/src/runTest.ts
When using the CLI in `jest-runtime`, `console.error`, `console.warn` and `console.assert` print to stdout, which is wrong. `CustomConsole` should print to the given `stderr` when calling those methods.
Added unit tests in `CustomConsole`.
> CustomConsole: print console.error and console.assert to stderr

- CHANGELOG.md
- e2e/__tests__/__snapshots__/showConfig.test.ts.snap
- packages/jest-config/src/normalize.ts
The default value of the test sequencer isn't resolved unless explicitly set (we only iterate on `options`, which contains the user-defined options but not the default ones). This diff ensures that we call `require.resolve` to obtain the real default path of the sequencer (since `@jest/core` is making the require call, it would fail otherwise under PnP).
I modified the code in my cache and checked that my tests were running. We probably should try to add an integration test for PnP at some point.
> Resolves the test sequencer even when not explicitly set

- CHANGELOG.md
- e2e/__tests__/__snapshots__/toMatchInlineSnapshot.test.ts.snap
- e2e/__tests__/toMatchInlineSnapshot.test.ts
- packages/jest-snapshot/src/__tests__/inline_snapshots.test.ts
- packages/jest-snapshot/src/index.ts
- packages/jest-snapshot/src/inline_snapshots.ts
Problem as reported by @zertosh :
> One issue I found though is that if your output has new lines somewhere, they become just indented whitespace - as expected. But most editors have automatic trailing whitespace removal, so you end up changing the test just by saving.
The obvious concern here is that, if for whatever reason a snapshot is relying on whitespace on a certain line, we don't want to impact that... even if some editors are going to automatically remove it.
To resolve, I've just stopped indenting empty lines IF they are completely empty.
- Added unit test to verify behavior. The test previously fails, it now passes.
- Added e2e tests for behavior.
> Inline snapshots: do not indent empty lines.

- packages/expect/package.json
- packages/jest-snapshot/package.json
- yarn.lock
Trying out Yarn PnP some more again revealed a few things we can do better
We'll see if CI passes.
> cleanup from trying out yarn pnp

- CHANGELOG.md
- packages/jest-runtime/src/index.ts
This leak is caused by this line:
https://github.com/facebook/jest/blob/01044dabf2253287a5a84e6a87b8505b559e9257/packages/jest-runtime/src/index.ts#L693
The `moduleRegistry` is preserved in the closure and never GC'd, along with all modules within the registry, making it a pretty nasty memory leak. I'm fairly certain it's also a bug fix: when you reset the registry, this reference to the registry continued referencing the old version. That doesn't make sense after a reset.
This code is now a map and easy to clear but until very recently it was a normal `Object` which explains why it was 'cleared' in this way.
command: `yarn jest --logHeapUsage --w=1 packages/`
`--expose-gc` enabled to trigger gc manually after each test for accurate readings on the leak
without circus:
295 MB -> 262 MB …
> Fix module registry memory leak.

- CHANGELOG.md
- docs/CLI.md
- packages/jest-cli/src/cli/args.ts
- packages/jest-core/src/TestScheduler.ts
- packages/jest-core/src/__tests__/testSchedulerHelper.test.js
- packages/jest-core/src/testSchedulerHelper.ts
`detectOpenHandles` makes no sense without `runInBand`, because it cannot detect leaks in workers.
I've also changed `shouldRunInBand` to just accept the config object, otherwise it would have lots of params.
Added one `test.each` line. Also tested manually.
> detectOpenHandles imply runInBand

- docs/Es6ClassMocks.md
- website/versioned_docs/version-23.x/Es6ClassMocks.md
- website/versioned_docs/version-24.0/Es6ClassMocks.md
The docs don't explicitly say that in the `mockImplementation` example `const mockPlaySoundFile = jest.fn();` is relying on some behind-the-scenes magic. Not sure why but the explanation didn't click for me and it seems like I'm not the only one. This is an attempt to highlight this point
For reference: https://github.com/facebook/jest/issues/2567#issuecomment-462520630
> Emphasize 'mock' variable name exception in docs

- docs/Webpack.md
I got married, changed my last name, and therefore changed my GitHub name. This is updating the URL to match my new GitHub URL. Nothing else changed and this fixes a broken link.
> Updated URL to fix broken link

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
As prerequisite to improve `toEqual` matcher report, fix a confusing mistake in its tests:
* `{pass: true}` is label for snapshot when `.not.toEqual` fails (it’s a double negative :)
* verify that opposite assertion passes like similar tests of `toHaveProperty` matcher
Bonus change for `'failure message matches the expected snapshot'`:
* move test of different values for same key to `{pass: fail}` tests
* remove test of same values for same key because it is redundant with `{pass: true}` tests
* Updated names of 48 snapshot tests
* Moved and renamed 1 snapshot test
* Deleted 1 snapshot test
> chore: Fix label and add opposite assertion for toEqual tests

- CHANGELOG.md
- packages/jest-haste-map/src/index.ts
I forgot in my previous PR to forward the `mapper` option from the `JestHasteMap` options to the crawler option. It went unnoticed because the tests directly instantiate the crawler and because in Metro this logic wasn't necessary because the PnP resolution bypassed the Haste map.
I noticed the problem by removing this bypass, which highlighted that the mapper never got called 😞 
Modified my Jest copy locally, checked that the mapper was called as it should be.
> Fixes the jest-haste-map mapper option

- docs/ExpectAPI.md
I propose to remove this example, since it contradicts the previous and next examples, and it also doesn't work (the assertion fails). On top of that, the comment does not fit.
Just run the example to see that the assertion fails.
> Remove confusing, non-working example

- CHANGELOG.md
- e2e/__tests__/__snapshots__/cliHandlesExactFilenames.test.ts.snap
- e2e/__tests__/__snapshots__/consoleLogOutputWhenRunInBand.test.ts.snap
- e2e/__tests__/__snapshots__/detectOpenHandles.ts.snap
- packages/jest-cli/src/cli/index.ts
Currently, the `--forceExit` warning is misleading because it's a bold, red message for something that you've specifically opted in to. When I run tests, my eye is looking for red to show me that something failed. If my project needs to use `--forceExit`, I shouldn't see red every single time. Red should be reserved for errors.
I've updated the message. It's now on one line and white. It's something you will see every single run, it shouldn't draw your eye too much.
Similarly, the "Jest did not exit for one second" message is currently shown in red. This message shouldn't show every time and should catch the user's eye. However, it's not an error by itself, it's a warning. It's possible that the test run completes successfully after this message is printed. I've updated the color to …
> Update --forceExit and "did not exit for one second" message colors.

- CHANGELOG.md
- docs/DynamoDB.md
- website/sidebars.json
Inspired by MongoDB usage example, I created a Jest DynamoDB preset based on [dynamodb-local](https://github.com/rynop/dynamodb-local) package
Tests are passing for a library which uses this preset: https://circleci.com/gh/shelfio/dynamodb-parallel-scan/tree/master
> Add DynamoDB usage example

- CHANGELOG.md
- e2e/__tests__/declarationErrors.test.ts
- e2e/declaration-errors/__tests__/describeThrow.test.js
- packages/jest-jasmine2/src/jasmine/Env.ts
Fixes the describe warning part of #8334 (intentionally not marking this as closing the whole issue)
Added e2e test case that fails with master build (the stdout `toBe('')` check).
> jest-jasmine2: fix describe return value warning being shown if describe throws

- CHANGELOG.md
- packages/jest-each/src/__tests__/array.test.ts
- packages/jest-each/src/table/array.ts
Fixes #8286
Basically what is happening is the valid placeholder values are interpolated and then have a knock on effect to the next value to be interpolated into the test title.
This PR stops this from happening by adding an escape to any placeholder values (`%d`) and then removes the all occurrences of the escape at the end of the formatting
See unit tests.
> [jest-each] Fix bug with placeholder values

- CHANGELOG.md
- docs/MongoDB.md
- website/versioned_docs/version-23.x/MongoDB.md
- website/versioned_docs/version-24.0/MongoDB.md
I've just published a Jest preset to simplify usage. Since I was the author of the original tutorial, the code underneath remained the same
> Simplify mongodb example by using preset

- CHANGELOG.md
- packages/jest-environment-jsdom/src/index.ts
I have described an issue at https://github.com/facebook/jest/issues/8347.
We know ignores were not emitted by Typescript creating declaration files (ref https://github.com/Microsoft/TypeScript/issues/20360) and we can't build in your Typescript project if not skip checking types in libraries using.
I re-declared `global` prototype in JSDOMEnvironment class. I checked in my project and build files.
> Declare global prototype in JSDOMEnvironment to fix issue #8347

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/matchers.ts
- packages/expect/src/print.ts
For `toHaveProperty` matcher:
* Display promise `rejects` or `resolves` in matcher hint
* Replace obscure `pass must be initialized` error with `expected path must not be an empty array`
* Omit redundant or distracting information, as described below
When **negative** assertion fails:
* Display `not` between expected label and value
* Display received value **only** if it has different serialization
* Display unique report for edge case
When **positive** assertion fails:
* If received path is not complete: Display value of last received property
* If received path is complete: Display either diff (without `Difference` label) or stringify values, **not both**
**Residue**:
* chore to rewrite `getPath` as iterative algorithm and …
> expect: Improve report when matcher fails, part 17

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/matchers.ts
For `toMatchObject` matcher:
* Display promise `rejects` or `resolves` in matcher hint
* Omit redundant or distracting information, as described below
When **negative** assertion fails:
* Display `not` between expected label and value
* Display received value **only** if it has different serialization
When **positive** assertion fails:
* Display either diff (without `Difference` label) or stringify values, **not both**
**Residue**: there is room for improvement through possible future data-driven diff
**Faithful reviewers**: thank you for heroic effort to go through `matchers.ts` together!
* There may be a small part 19 to improve `toThrow(Class)` in `toThrowMatchers.js`
* And then a well deserved rest before improving reports …
> expect: Improve report when matcher fails, part 18

- .azure-pipelines-steps.yml
- .circleci/config.yml
- .travis.yml
- scripts/remove-postinstall.js
We're dropping Node 6 support shortly and it's already failing on CI because it can't compile the TypeScript without dying. Stop running it now since it's failing regardless.
- CI should stop running Node 6.
> Stop running TS builds on CI beyond dedicated lint job

- CHANGELOG.md
- packages/expect/src/__tests__/asymmetricMatchers.test.js
- packages/expect/src/jasmineUtils.ts
Helper for getting function name in some cases returns wrong function name.
For example: If we somehow lost the property `name` in function, then we used regExp that failed with async function, function generator and function with `$` in name.
One more rare case if toString method was changed.
I added tests for these cases
> Fix getting function name for rare cases

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/__snapshots__/toThrowMatchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/__tests__/toThrowMatchers.test.js
- packages/expect/src/matchers.ts
- packages/expect/src/print.ts
- packages/expect/src/toThrowMatchers.ts
Follow up on residue from #7621 and #8077 according to recent improvements
For `toBeInstanceOf` matcher:
Factor out `printConstructorName` similar to `printWithType` function in `jest-matcher-utils`
* Positive assertion: show received value **only if** it is not function with prototype **otherwise** display received constructor name
* Negative assertion: instead of received value, show received constructor name **only if** it is not equal to expected assertion name
For `toThrow(Constructor)` matcher:
* Display constructor name consistent with `toBeInstanceOf`
* Omit expected and received `name` property, because it is usually redundant with constructor name
**Residue**: why TypeScript errors for `received: unknown` in `printReceivedConstructorName`
| matcher | pass | snapshots |
| :--- | …
> expect: Improve report when matcher fails, part 19

- CHANGELOG.md
- e2e/__tests__/__snapshots__/failures.test.ts.snap
- e2e/__tests__/failures.test.ts
- e2e/babel-plugin-jest-hoist/__tests__/integration.test.js
- e2e/babel-plugin-jest-hoist/__tests__/integrationAutomockOff.test.js
- e2e/babel-plugin-jest-hoist/__tests__/typescript.test.ts
- e2e/failures/__tests__/assertionCount.test.js
- e2e/failures/__tests__/assertionError.test.js
- e2e/failures/__tests__/asyncFailures.test.js
- e2e/failures/__tests__/errorAfterTestComplete.test.js
- e2e/failures/__tests__/snapshot.test.js
- e2e/failures/__tests__/snapshotWithHint.test.js
- e2e/failures/__tests__/testMacro.test.js
- e2e/snapshot-mock-fs/__tests__/snapshot.test.js
- e2e/snapshot/__tests__/secondSnapshot.test.js
- e2e/snapshot/__tests__/snapshot.test.js
- packages/jest-runtime/src/__tests__/Runtime-sourceMaps.test.js
Delete 14 occurrences of ` * @emails oncall+jsinfra` line in header comment:
* `e2e/babel-plugin-jest-hoist/__tests__/integration.test.js`
* `e2e/babel-plugin-jest-hoist/__tests__/integrationAutomockOff.test.js`
* `e2e/babel-plugin-jest-hoist/__tests__/typescript.test.ts`
* `e2e/failures/__tests__/assertionCount.test.js`
* `e2e/failures/__tests__/assertionError.test.js`
* `e2e/failures/__tests__/asyncFailures.test.js`
* `e2e/failures/__tests__/errorAfterTestComplete.test.js`
* `e2e/failures/__tests__/snapshot.test.js`
* `e2e/failures/__tests__/snapshotWithHint.test.js`
* `e2e/failures/__tests__/testMacro.test.js`
* `e2e/snapshot-mock-fs/__tests__/snapshot.test.js`
* `e2e/snapshot/__tests__/secondSnapshot.test.js`
* `e2e/snapshot/__tests__/snapshot.test.js`
* …
> chore: Delete obsolete emails tag from header comment in test files

- CHANGELOG.md
- packages/expect/src/jasmineUtils.ts
Removed needless checking for `isEqualNode` because it checked before.
Used lazy checking for second object.
> [expect] optimize compare nodes

- docs/ExpectAPI.md
- website/versioned_docs/version-22.x/ExpectAPI.md
- website/versioned_docs/version-23.x/ExpectAPI.md
- website/versioned_docs/version-24.0/ExpectAPI.md
When user looks for function documentation he tries to write code as in examples, but notification about additional function wrap shows at the end. I think it will be better to place it on the top, so user will at first see that note. Closes https://github.com/facebook/jest/issues/8392
No test plan, only manual view checking.
> Place "Note" directly after function title

- CHANGELOG.md
- packages/jest-runtime/src/__tests__/runtime_require_module_or_mock.test.js
- packages/jest-runtime/src/index.ts
Fixes #8395 where virtual mocks could not be unmocked after previously being mocked.
Repro steps are in a test case and now pass.
> Fix virtual mocks not being unmockable after previously being mocked

- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/print.ts
Added a missing comment and condition
No update to CHANGELOG.md if we merge it in same batch as #8367
Added 1 snapshot
Example picture baseline at left and **improved at right**
> expect: Fix edge case in part 19

- packages/jest-transform/src/shouldInstrument.ts
Just used `includes` instead of `some` for performance reasons.
https://jsperf.com/includes-vs-some-12333
> [jest-transform] use includes instead of some

- CHANGELOG.md
- packages/jest-resolve/src/defaultResolver.ts
For the same path, the function `fs.statSync` can call many times. The more test files, the more often it will be called for the same file or directory.
I just added hash table to avoid repeated call for `fs.statSync`.
> Cache checked files in fs

- e2e/__tests__/__snapshots__/snapshotSerializers.test.ts.snap
- e2e/__tests__/snapshotSerializers.test.ts
- e2e/snapshot-serializers/__tests__/snapshot.test.js
- packages/jest-snapshot/src/__tests__/utils.test.ts
- packages/jest-snapshot/src/utils.ts
See: https://github.com/facebook/jest/pull/7089#issuecomment-488382735
- Added tests to catch these regression(s) in the future.
> Revert #7089 and add tests to catch the regression(s) in the future.

- CHANGELOG.md
- docs/MockFunctionAPI.md
- website/versioned_docs/version-22.x/MockFunctionAPI.md
- website/versioned_docs/version-23.x/MockFunctionAPI.md
- website/versioned_docs/version-24.0/MockFunctionAPI.md
A few places in the Mock Function docs refer to "simple sugar" functions. I've updated these to [syntactic sugar](https://en.wikipedia.org/wiki/Syntactic_sugar) to match the correct terminology.
> Simple sugar text correction in Mock Function docs

- .azure-pipelines-steps.yml
- .azure-pipelines.yml
This simplifies the Azure Pipelines-specific workaround that overrides the folder Jest gets cloned into during a CI build. See [azure-pipelines-steps.yml (line 22)](https://github.com/facebook/jest/blob/master/.azure-pipelines-steps.yml#L22). 
Why this change? There is now a property on the "checkout" step that makes it easy to set the target directory of "git clone". This avoids the need for a separate step that copies the source to a different folder. This also simplifies the YAML.
Here's why this workaround was (and still is) necessary:
> By default, Azure Pipelines clones to an "s" directory, which causes some Jest tests to fail due to the assumption by Jest that it is being run from a "jest" directory (see packages/jest-message-util/src/index.js PATH_JEST_PACKAGES for more details). …
> Simplify workaround that overrides Jest clone folder on Azure Pipelines

- CHANGELOG.md
- packages/jest-resolve/src/defaultResolver.ts
Just save `path.resolve('.')` to const because `isCurrentDirectory` called very often.
> [jest-resolve] cache current directory path

- docs/JestObjectAPI.md
- docs/MockFunctionAPI.md
- packages/jest-environment/src/index.ts
- website/versioned_docs/version-22.x/JestObjectAPI.md
- website/versioned_docs/version-22.x/MockFunctionAPI.md
- website/versioned_docs/version-23.x/JestObjectAPI.md
- website/versioned_docs/version-23.x/MockFunctionAPI.md
- website/versioned_docs/version-24.0/JestObjectAPI.md
- website/versioned_docs/version-24.0/MockFunctionAPI.md
Simple grammar change in the Mock Function API documentation
Simple Grammar change, makes it read a little better.
> Grammar correction in Mock Function docs

- website/blog/2019-01-25-jest-24-refreshing-polished-typescript-friendly.md
I think `concering` is supposed to be `concerning`
this is a minor change. not sure if the blog needs to be regenerated, or if simply merging this will fix the live site.
> fixing typo in blog post: concering -> concerning

- CHANGELOG.md
- packages/jest-get-type/src/__tests__/isPrimitive.test.ts
- packages/jest-get-type/src/index.ts
I just simplified checking for primitive type and improve performance.
There were already tests, but I added some more
> [jest-get-type] Simplify checking for primitive

- CHANGELOG.md
- LICENSE
I noticed `View license` as text of link on `jest` project page compared to `MIT` on `react` project page
This commit removes differences in the `LICENSE` file for Jest compared to React
* My theory is `For Jest software` line is causing GitHub not to match the license text as MIT
* For the copyright line, see https://github.com/facebook/react/pull/13593
See if GitHub matches the `LICENSE` file :)
> LICENSE: Follow copyright header guidelines and delete For Jest software

- CHANGELOG.md
- packages/babel-plugin-jest-hoist/src/index.ts
Ref #8427
As mentioned in #8427, Node v12 has changed the enumerability of `global.process` and `global.Buffer`, thus the list of allowed globals became much shorter. I believe, that suggested change will improve the testing experience because it provides more complete list of available globals that can be safely used in hoisted mocks.
I ran the e2e test for this plugin and it was all green.
```
npx jest
PASS  __tests__/typescript.test.ts
PASS  __tests__/integrationAutomockOff.test.js
PASS  __tests__/integration.test.js
Test Suites: 3 passed, 3 total
Tests:       12 passed, 12 total
Time:        2.25s
```
P.S. I signed the CLA.
> Fix babel-plugin-jest-hoist: getting full list of whitelisted globals

- CHANGELOG.md
- packages/jest-cli/src/cli/index.ts
- packages/jest-core/package.json
- packages/jest-core/src/__tests__/__fixtures__/watch_plugin_throws.js
- packages/jest-core/src/__tests__/__snapshots__/watch.test.js.snap
- packages/jest-core/src/__tests__/watch.test.js
- packages/jest-core/src/watch.ts
Follow up to https://github.com/jest-community/jest-watch-typeahead/pull/29
Any idea how we could get rid of the outer stack trace and / or "Test suite failed to run"? In the current state it IMO looks worse than just the plain error. @SimenB
Edit: fixed outer stack trace, updated screenshot 
Added snapshot test.
Manual test -> see screenshot
> make watch plugin initialization errors look nice

- packages/jest-config/src/ValidConfig.ts
- packages/jest-validate/src/condition.ts
Partof: #8436 
Fix typing's for (jest-validate)-multipleValidOptions , which removes a few `@ts-ignore TODO` in (jest-config)-ValidConfig
TS builds doesnt fail
> chore: multipleValidOptions types

- packages/jest-config/src/getMaxWorkers.ts
- packages/jest-types/src/Config.ts
Note: Creating separate isolated PR's for type adjustments that narrow the scope of effected files.
See #8436 
getMaxWorkers - has capability to parse percentage strings , Therefore we should add string to its type, and remove unnecessary casting. `const maxWorkers = (argv.maxWorkers as unknown) as number | string;` to `const maxWorkers = argv.maxWorkers`. Or depreceate
No type errors thrown on build
> chore: getMaxWorkers types

- CHANGELOG.md
- packages/jest-leak-detector/package.json
- packages/jest-leak-detector/src/index.ts
I removed function `isPrimitive` from `jest-leak-detector` because it is already implemented in `jest-get-type`. DRY
> [jest-leak-detector] remove code repeat

- packages/jest-environment/src/index.ts
- packages/jest-runtime/src/index.ts
* Updated ModuleWrapper type
* update wrapper usage
* **Removed moduleArguments variable**
Related: #8436
> chore(jest-environment) - update types and type usage in jest-runtime

- CHANGELOG.md
- docs/JestObjectAPI.md
- packages/jest-environment/src/index.ts
- website/versioned_docs/version-22.x/JestObjectAPI.md
- website/versioned_docs/version-23.x/JestObjectAPI.md
- website/versioned_docs/version-24.0/JestObjectAPI.md
I've spent  1 hour looking how to proper use ` jest.requireActual` until I found this comment: https://github.com/facebook/jest/issues/936#issuecomment-265074320
I think it's too good to not be in the docs.
Was just a quick change on the `.md` file. This is how it looks now:
> Add example to jest.requireActual

- docs/TutorialReact.md
- website/versioned_docs/version-22.x/TutorialReact.md
- website/versioned_docs/version-23.x/TutorialReact.md
- website/versioned_docs/version-24.0/TutorialReact.md
Correcting a link that leads to the documentation of Jest inside the create-react-app's documentation
https://jestjs.io/docs/en/tutorial-react
> Correcting a link that leads to the documentation of Jest inside the create-react-app's documentation

- docs/TestingAsyncCode.md
expect.assertions relevant only for tests expected to fail.
after locating this I also found a post about it in stackoverflow:
https://stackoverflow.com/questions/54706481/expect-assertions-in-async-await-function
So it seems to confuse many people.
> redundant and confusing line

- docs/Puppeteer.md
- website/versioned_docs/version-22.x/Puppeteer.md
- website/versioned_docs/version-23.x/Puppeteer.md
- website/versioned_docs/version-24.0/Puppeteer.md
I spent a few hours bashing my head on my desk until I found issue #7962 and the workaround suggested there.
The documentation currently uses `page.evaluate` in an example, but this example breaks with a rather obscure error when code coverage is generated for the test file.
By adding a notice, hopefully I can save someone else from becoming frustrated! :-)
I wasn't sure about the wording (I tried to keep it in the same style as the rest of the document), so if any edits are needed, no problem!
It's a doc change, no test plan.
> docs: Add notice for known bug with puppeteer

- CHANGELOG.md
- TestUtils.ts
- docs/CLI.md
- e2e/__tests__/__snapshots__/timeouts.test.ts.snap
- e2e/__tests__/timeouts.test.ts
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
- packages/jest-cli/src/cli/args.ts
- packages/jest-config/src/ValidConfig.ts
- packages/jest-config/src/__tests__/__snapshots__/normalize.test.js.snap
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/index.ts
- packages/jest-config/src/normalize.ts
- packages/jest-core/src/lib/__tests__/__snapshots__/log_debug_messages.test.ts.snap
- packages/jest-jasmine2/src/index.ts
- packages/jest-jasmine2/src/jasmine/jasmineLight.ts
- packages/jest-types/src/Config.ts
My motivation is. When I debug the unit tests in IntelliJ and I got a timeout error.
Other's motivation: #6216
I would like to set the timeout to Infinity when jest runner in debug mode if this PR is approved. I like the step by step development
I extended the timeout e2e tests with use cases
> feat: set global timeout in command line argument

- docs/MockFunctionAPI.md
- website/versioned_docs/version-22.x/MockFunctionAPI.md
- website/versioned_docs/version-23.x/MockFunctionAPI.md
- website/versioned_docs/version-24.0/MockFunctionAPI.md
this matches more what is being reported. Especially the bit about `"mockedFunction"` is important, because otherwise it's a bit confusing what `mockName` will help with.
> docs: update reported error text

- CHANGELOG.md
- packages/jest-snapshot/src/__tests__/inline_snapshots.test.ts
- packages/jest-snapshot/src/inline_snapshots.ts
Fixes #8424 by avoiding indenting inline snapshot if second line of inline snapshot already has been indented.
As described in #8424, existing and unmodified inline snapshot drifts every time inline snapshots are updated.
This pull request fixes this behavior.
1. Added unit test to trigger faulty behavior
2. Fixed code and verified that the faulty behavior was fixed by re-running the unit tests.
> Prevent drifting inline snapshots #8424

- CHANGELOG.md
- packages/pretty-format/src/__tests__/react.test.tsx
- packages/pretty-format/src/plugins/ReactElement.ts
Currently, the way `jest` and `enzyme` handle memoized components is out of sync. This leads to some snapshot tests rendering the incorrect memoized component's displayName. e.g.: while using the latest `react-redux` version, some connected components are memoized and they respect the custom `displayName`, it can be checked here: https://github.com/reduxjs/react-redux/blob/master/src/components/connectAdvanced.js#L416.
`enzyme` has fixed it here: https://github.com/airbnb/enzyme/pull/2137/files, notice that it checks for the type's displayName, before going to the type's type displayName.
Prior to this, when a memoized/connected `React.Node` is passed as another component's props, the snapshot tests of that component would return `<Memo(ConnectFunction)>`, now they return the correct …
> fix(pretty-format): Render custom displayName of memoized components

- CHANGELOG.md
- packages/jest-haste-map/src/__tests__/index.test.js
- packages/jest-haste-map/src/crawlers/node.ts
- packages/jest-haste-map/src/index.ts
The `mapper` option passed to HasteMap is not supported in Node crawler, so we shouldn't pass it there. It's likely a cause of a regression in React Native 0.60 RC: https://github.com/facebook/react-native/pull/25241#issuecomment-501442208.
The regression was a part of this refactoring: https://github.com/facebook/jest/pull/8056/files#diff-5c5055968e3661a18f280d5e3f10c969L738
Added extra assertion to validate that mapper is not passed to Node crawler.
cc @scotthovestadt @arcanis
> fix(jest-haste-map): don't throw on missing mapper in Node crawler

- docs/Configuration.md
- website/versioned_docs/version-22.x/Configuration.md
- website/versioned_docs/version-23.x/Configuration.md
- website/versioned_docs/version-24.0/Configuration.md
- website/versioned_docs/version-24.1/Configuration.md
- website/versioned_docs/version-24.6/Configuration.md
the documentation referenced was already removed in https://github.com/facebook/jest/pull/5903
> remove reference to automock penalty

- docs/ExpectAPI.md
- website/versioned_docs/version-22.x/ExpectAPI.md
- website/versioned_docs/version-23.x/ExpectAPI.md
- website/versioned_docs/version-24.0/ExpectAPI.md
Move `.toHaveLength` and `.toHaveProperty` to `.toHave` group to keep matchers in correct order.
Tested with `yarn start` in `website`.
> docs: move toHaveLength and toHaveProperty to toHave* group

- CHANGELOG.md
- e2e/__tests__/__snapshots__/failures.test.ts.snap
- e2e/__tests__/__snapshots__/watchModeUpdateSnapshot.test.ts.snap
- e2e/__tests__/toMatchSnapshot.test.ts
- packages/jest-snapshot/package.json
- packages/jest-snapshot/src/__tests__/__snapshots__/printDiffOrStringified.test.ts.snap
- packages/jest-snapshot/src/__tests__/printDiffOrStringified.test.ts
- packages/jest-snapshot/src/index.ts
- packages/jest-snapshot/src/print.ts
- packages/jest-snapshot/tsconfig.json
When expected and received are both **string**, snapshot matchers call `printDiffOrStringify`
If neither received nor expected (snapshot) is multiline, or either is empty:
* display following `Snapshot:` and `Received:` labels
If either received or expected (snapshot) is multiline, and neither is empty:
* if semantic cleanup leaves a common substring, highlight substring differences
* otherwise display line diff, however without enclosing double quote marks
The change in report for single-line strings affects a few tests:
* updated 1 `toMatch` assertion in `e2e/__tests__/toMatchSnapshot.test.ts`
* updated 2 snapshots in `e2e/__tests__/failures.test.ts`
* updated 1 snapshot in `watchModeUpdateSnapshot.test.ts`
Added `printDiffOrStringified.test.ts` in `jest-snapshot` package
See pictures …
> jest-snapshot: Highlight substring differences when matcher fails, part 3

- CHANGELOG.md
- docs/JestObjectAPI.md
- website/versioned_docs/version-22.x/JestObjectAPI.md
- website/versioned_docs/version-23.x/JestObjectAPI.md
- website/versioned_docs/version-24.0/JestObjectAPI.md
Currently there is no information on how to use `jest.doMock()` with ES6 modules. Doing that requires a few additional steps that are non-intuitive.
In this PR I expanded on the `jest.doMock()` API documentation to solve that problem.
The example code provided passes tests:
Please let me know if there is anything you'd like me to improve or if the PR isn't suitable.
> docs(jest.doMock): Add information for using ES6 modules with doMock

- CHANGELOG.md
- docs/ExpectAPI.md
- website/versioned_docs/version-24.0/ExpectAPI.md
This PR fixes #8581.
Tested changes made to the docs by:
1. Building the Jest website locally (following commands outlined in [CONTRIBUTING.md](https://github.com/facebook/jest/blob/master/CONTRIBUTING.md#additional-workflow-for-any-changes-made-to-website-or-docs))
2. Navigating to http://localhost:3001/docs/en/expect#thisutils
3. Inspecting changes made to the code example
> docs: Fix variable name in custom-matcher-api code example

- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
- packages/jest-each/package.json
- packages/jest-each/src/index.ts
- packages/jest-jasmine2/src/jestExpect.ts
- packages/jest-jasmine2/src/setup_jest_globals.ts
- packages/jest-types/src/Global.ts
> do not modify global types via declarations

- CHANGELOG.md
- packages/jest-core/src/__tests__/__snapshots__/getNoTestsFoundMessage.test.js.snap
- packages/jest-core/src/__tests__/getNoTestsFoundMessage.test.js
- packages/jest-core/src/getNoTestFoundPassWithNoTests.ts
- packages/jest-core/src/getNoTestsFoundMessage.ts
When running jest with '--passWithNoTests' but there are no tests to execute, it prints a superfluous warning. This PR removes this warning.
In both screenshots below there are no test files and jest is executed with `--passWithNoOptions`.
It used to log that it exited with code 1 and a message to use `--passWithNoOptions`, while it exits with code 0 and the option is already provided.
Closes #8594
Before: 
After:
> Fix warning message when there are no tests

- CHANGELOG.md
- docs/Configuration.md
- website/versioned_docs/version-24.8/Configuration.md
Fixes the example used in the Jest configuration docs, because `context` was not defined.
Documentation udpate
> Fix example used in custom environment docs

- packages/babel-jest/README.md
Typescript files require `.ts` or `.tsx` file extension. Now that babel can parse typescript with @babel/preset-typescript, we should use it.
I tried this out locally and it worked for both typescript and js files.
> Update setup instructions for typescript files

- CHANGELOG.md
- docs/Configuration.md
- e2e/__tests__/customTestSequencers.test.ts
- e2e/custom-test-sequencer/package.json
- e2e/custom-test-sequencer/testSequencerAsync.js
- packages/jest-core/src/runJest.ts
When overriding `testSequencer` with custom logic, forcing synchronous sorting can be limiting. One use-case is fetching test runtime from an endpoint instead of relying on the local cache; this requires an async roundtrip and is not currently possible.
This extremely simple PR adds the optional ability for `sort` to return a `Promise` without requiring it to.
- All existing tests pass.
- Added e2e test for async use of `sort`.
- Tested manually with real-world implementation.
> Support async sort in custom testSequencer.

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/spyMatchers.test.js.snap
- packages/expect/src/__tests__/spyMatchers.test.js
- packages/expect/src/spyMatchers.ts
Improve **Matcher error** reports for all 20 mock-spy matchers
Indentation changed in `spyMatchers.ts` because of `function` to access `this: MatcherState` but the actual changes are limited to:
* declare `expectedArgument` and `options`
* edit arguments in `ensureNoExpected` calls
* edit arguments in `ensureExpectedIsNumber` calls
* edit arguments in `ensureMock` calls
* rewrite `ensureMock` function
The `matcherName.slice(1)` is temporary to omit `.` in matcher error snapshots only
Future pull requests in this series will remove `.` from matcher names in `create` function calls
**Breaking Residue** for Jest 25
* Distinguish `ensureMock` from `ensureMockOrSpy` because Jasmine spy does not store return values, true?
* Replace `ensureExpectedIsNumber` with …
> expect: Improve report when mock-spy matcher fails, part 1

- packages/jest-resolve-dependencies/src/index.ts
Hey guys, I just explored your mechanism of retrieving a list of transitive inverse dependencies, and found this redundant `module`.
I assume that `file` and `module.file` are still the same after `filter(file)`, and no monkey patching occurs :)
> simplify `module.file` to `file`

- docs/JestObjectAPI.md
- website/versioned_docs/version-22.x/JestObjectAPI.md
- website/versioned_docs/version-23.x/JestObjectAPI.md
- website/versioned_docs/version-24.0/JestObjectAPI.md
Make warning about importing modules in the setup files making them unmockable more visible by using markdown's blockquote.
It is very easy to overlook this warning and it is important to understand why `jest.mock()` isn't working.
N/A
> docs: make warning more visible

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/spyMatchers.test.js.snap
- packages/expect/src/__tests__/spyMatchers.test.js
- packages/expect/src/spyMatchers.ts
For mock-spy matchers whose criterion is number of calls or returns:
* Replace sentences with `Expected` and `Received` labels and number values
For negative matcher:
* with expected times, repeat `not` following `Expected` label
* without expected times, display `>= 1` following `Expected` label
* without expected times, display args or value as lines with one-based call number as label
**Questions** to reviewers
1. What do you think about change to consistent `PRINT_LIMIT = 3` instead of:
```js
const CALL_PRINT_LIMIT = 3;
const RETURN_PRINT_LIMIT = 5;
```
2. For **return** matchers, is the number of **calls** relevant information [EDIT: if it is different from the number of returns] to include on an additional line in report …
> expect: Improve report when mock-spy matcher fails, part 2

- CHANGELOG.md
- packages/jest-mock/src/__tests__/index.test.ts
- packages/jest-mock/src/index.ts
Previously, when restoring a stubbed method that didn't exist in the `object` passed to `spyOn` we would always reassign to `object[methodName]` the previous result of `object[methodName]`.
Since `object[methodName]` causes the prototype chain to be traversed if we don't find `methodName` in `object` itself, this could cause us to assign the method that was previously in the prototype to a method in `object` which did not exist before.
This PR fixes #8625.
Also, @fongandrew actually deserves a lot of credit for this. He's done most of the hard work by providing an accurate report detailing what the expected behaviour should be and by helping out to get to the optimal solution. Thanks @fongandrew 💖 
You can reproduce this bug with the following snippet.
```js
it('supports mocking value in …
```
> Fix mock reassigning to previously unexisting method

- CHANGELOG.md
- packages/jest-haste-map/src/lib/__tests__/dependencyExtractor.test.js
- packages/jest-haste-map/src/lib/dependencyExtractor.ts
Jest previously wouldn't find changes to side-effect only imports when watching files.
https://github.com/facebook/jest/issues/8547
1. Added a test to make it fail
1. Made the test pass
1. Tried to ensure other tests failing / passing status were the same running a full `yarn jest`, but there's a fair amount of noise is pre-existing failures. Also tried to use `yarn jest --json --outputFile=[...]` before and after but a lot of noise there in comparing. Settled for similar looking summaries before / after that looks something like the below when run close together:
>Snapshot Summary
› 4 snapshots failed from 2 test suites. Inspect your code changes or run `yarn run jest -u` to update them.
>
> Test Suites: 7 failed, 328 passed, 335 total
Tests:       12 failed, 9 skipped, 3465 passed, 3486 …
> Issue 8547: side effect import deps extracted

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/spyMatchers.test.js.snap
- packages/expect/src/__tests__/spyMatchers.test.js
- packages/expect/src/spyMatchers.ts
Throw matcher error if `n` is not a positive safe integer:
* `toHaveBeenNthCalledWith` and `nthCalledWith`
* `toHaveNthReturnedWith` and `nthReturnedWith`
Because baseline code returns `pass: false` a negative assertion with invalid `n` cannot fail :(
Do y’all think to throw error instead of false negative (pardon pun) as:
* breaking change?
* fixed error?
For consistency with other matcher errors, display `received` instead of `jest.fn()` or mock name
`matcherName.slice(1)` is temporary until future pull requests which will delete period from names in calls to create matcher functions.
* Updated and renamed 8 snapshots for positive assertions
* Added 4 snapshots for negative assertions
Example pictures baseline at left and **improved at right**
Examples of positive assertions:
Examples …
> expect: Improve report when mock-spy matcher fails, part 3

- CHANGELOG.md
- packages/jest-cli/src/cli/index.ts
- packages/jest-cli/src/index.ts
- packages/jest-core/src/jest.ts
- packages/jest-core/src/version.ts
Makes sure `jest-cli` just exports the actual CLI running interface, nothing else
Green CI
> chore: move getVersion to jest-core from cli

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/spyMatchers.test.js.snap
- packages/expect/src/spyMatchers.ts
For `toHave*ReturnedWith` matchers:
* Replace sentences with `Expected` and `Received` labels
* For negative matcher, repeat `not` following `Expected` label
* At end of report, display `Received number of returns`
* If any calls didn’t return, display `Received number of calls`
Display up to 3 call results as context, so testers can diagnose problems: in code, or test, or both
Your **feedback** is especially welcome about questions:
1. For special case of exactly **one call**, is it clearer to display `Received value: whatever` on one line instead of two? (see pictures in following comments)
2. Is the following **context** relevant?
Read the following descriptions with the qualifier **if they exist**:
| matcher | context |
| …
> expect: Improve report when mock-spy matcher fails, part 4

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/spyMatchers.test.js.snap
- packages/expect/src/__tests__/spyMatchers.test.js
- packages/expect/src/spyMatchers.ts
Throw matcher error from `*Return*` matchers if received is a spy function, instead of `TypeError: received.getMockName is not a function`
* Change `isSpy` function to test for both `all` and `count` methods
* Rename `ensureMock` as `ensureMockOrSpy` for `*Call*` matchers
* Add `ensureMock` function for `*Return*` matchers
EDIT: Jasmine spy functions do not provide information about return values
* Defined `createSpy` in test file to return a mock of a spy function, because `jasmine.createSpy` is not defined when `jest-circus` is the test runner
* Added 10 passing positive and negative `*Called*` assertions with spy functions
* Replaced 4 failing positive and negative `*Called*` assertions with spy functions
* Updated 8 and removed 2 snapshots of matcher errors for `*Return*` assertions …
> expect: Throw matcher error when received cannot be jasmine spy

- .circleci/website.sh
- website/package.json
- yarn.lock
- Optimize jest website deploy by downloading only certain translation files. Instead of downloading files for 39 languages, we now only download 7 languages which is enabled. Faster CI :)
User can still go to https://crowdin.com/project/jest to translate other language
- Bump docusaurus to 1.12
Try downloading one language with jest crowdin api key
```bash
cd website
CROWDIN_JEST_PROJECT_ID=jest CROWDIN_JEST_API_KEY=<jest crowdin api key> yarn crowdin-download -l uk
```
> chore: download only enabled languages translation files

- CHANGELOG.md
- docs/TutorialReact.md
- website/versioned_docs/version-24.0/TutorialReact.md
- website/versioned_docs/version-24.8/TutorialReact.md
Updated react-testing-library imports to @testing-library/react in website examples.
I've recently sent a PR for updating references of react-testing-library to @testing-library/react in the docs (https://github.com/facebook/jest/pull/8753), but I might have missed the imports part in the examples in the documentation (website). So here is the missing update. Sorry!
Opened the website to make sure changes are displaying correctly.
> [docs] Updated react-testing-library imports in website

- CHANGELOG.md
- packages/jest-core/package.json
- packages/jest-core/src/runGlobalHook.ts
- packages/jest-transform/package.json
- packages/jest-transform/src/ScriptTransformer.ts
Extract transform logic in `jest-core` into @jest/transform as requested in #8751 
Since it is a refactor change the existing tests should pass
> refactor: Extract transform code to @jest-transform

- packages/jest-types/src/Global.ts
As per the documentation of [testEnvironment](https://jestjs.io/docs/en/configuration#testenvironment-string) 
> You can also pass variables from this module to your test suites by assigning them to this.global object 
However if I'm writing my environment in Typescript, assigning a variable in `this.global` is reported as an error by the compiler, due to the strict typing of `Global`
Based on a discussion from #8751 
Existing e2e tests should cover it.
> fix: Allow setting extra options in this.global for Typescript

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/__tests__/utils.test.js
- packages/expect/src/utils.ts
This PR fixes the StackOverflow caused by passing objects with circular references to `toMatchObject` as per described in #8663.
And many thanks to @leoselig for providing an accurate report 💖 
1. The object matching happens in the `toMatchObject` method of `expect`. [This method uses `equals` and passes two custom testers to it: `iterableEquality` and `subsetEquality`](https://github.com/facebook/jest/blob/b76f01bc1c93e2bc4f4f0ed9834227753d7d65cc/packages/expect/src/matchers.ts#L874).
2. The `equals` method will then [use the passed `customTesters` to check for equality between `a` and `b`](https://github.com/facebook/jest/blob/b76f01bc1c93e2bc4f4f0ed9834227753d7d65cc/packages/expect/src/jasmineUtils.ts#L80-L85). If a `customTester` returns something other than `undefined`, that result …
> Fix handling circular references correctly in objects (closes #8663)

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/spyMatchers.test.js.snap
- packages/expect/src/__tests__/spyMatchers.test.js
- packages/expect/src/spyMatchers.ts
For `.not.toHaveBeen*CalledWith` assertions:
* repeat `not` following `Expected` label
* replaced `called with no arguments` with `called with 0 arguments` to avoid double negative
* for special case of **one call**, display `Received: whatever` on one line
* but omit the line if received has **same serialization** as expected
Reason to separate pull requests:
* negative assertions adapt context logic from ReturnWith matchers in #8710
* positive assertions will need design discussion about diff for object args
Updated 40 snapshots
| | long name | short name |
| ---: | :--- | :--- |
| 2 | `toHaveBeenCalled` | `toBeCalled` |
| 12 | `toHaveBeenCalledWith` | `toBeCalledWith` |
| 12 | `toHaveBeenLastCalledWith` | `lastCalledWith` |
| 14 | `toHaveBeenNthCalledWith` | `nthCalledWith` |
See also …
> expect: Improve report when negative CalledWith assertion fails

- CHANGELOG.md
- docs/MockFunctions.md
- website/versioned_docs/version-22.x/MockFunctions.md
- website/versioned_docs/version-23.x/MockFunctions.md
- website/versioned_docs/version-24.0/MockFunctions.md
toContain won't work in the case of the example, because it will try to compare arrays with Object.is.
Documentation update.
> Fix MockFunctions example that was using toContain instead of toContainEqual

- CHANGELOG.md
- packages/jest-watcher/src/JestHooks.ts
Just cached `JestHookSubscriber` and `JestHookEmitter` to avoid creating new object on each `getSubscriber()`, `getEmitter()` calls.
> Cache JestHook emitters

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/spyMatchers.test.js.snap
- packages/expect/src/spyMatchers.ts
Fixes #7884
For positive `toHaveBeen*CalledWith` assertions:
* Replace sentences with `Expected` and `Received` labels
* Display `Number of calls` at end of report
* Display received call arguments on one line separated by commas with dim color if value is equal to expected, except for the following special cases:
Display line diff for received call which corresponds to expected call number:
* not indented if only one received call
* indented if multiple received calls
Residue: replace line diff with data-driven diff formatted on one line, when it becomes available
@bandersongit These improvements build on recent pull requests:
* #8755 for negative `toHaveBeen*CalledWith` matchers
* #8710 for `toHave*ReturnedWith` matchers
* …
> expect: Improve report when positive CalledWith assertion fails

- CHANGELOG.md
- packages/jest-matcher-utils/src/__tests__/index.test.ts
- packages/jest-matcher-utils/src/index.ts
* Prerequisite to change expected and received colors in diff when snapshot test fails
* Contrast for args which do not have received counterpart in the report: `precision`, `n`, `hint`
Baseline hint at left and prototype hint at right
Any color comments welcome now or we can discuss details in following pull requests
Added 3 tests for `expectedColor`, `receivedColor`, `secondArgumentColor`
> jest-matcher-utils: Add color options to matcherHint

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/spyMatchers.test.js.snap
- packages/expect/src/spyMatchers.ts
Display received value in **dim** color when it is **equal** to expected
Updated 12 snapshots
| | long name | short name |
| ---: | :--- | :--- |
| 0 | `toHaveReturnedWith` | `toReturnWith` |
| 1 | `toHaveLastReturnedWith` | `lastReturnedWith` |
| 5 | `toHaveNthReturnedWith` | `nthReturnedWith` |
See also pictures in following comments
Example pictures baseline at left and **improved at right** if it changed
> expect: Display equal values for ReturnedWith similar to CalledWith

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/__snapshots__/spyMatchers.test.js.snap
- packages/expect/src/matchers.ts
- packages/expect/src/spyMatchers.ts
- packages/jest-snapshot/src/index.ts
For matcher args which do **not** have a received counterpart in red color:
* `precision` in `toBeCloseTo`
* `n` in `toHaveBeenNthCalledWith` and `toHaveNthReturnedWith`
* `hint` in `toMatchSnapshot` and `toThrowErrorMatchingSnapshot`
Especially for matchers whose 2 arguments have different effect on criterion
However, either `path` or `value` in `toHaveProperty` can have received counterpart:
Updated 97 snapshots
| | matcher |
| ---: | :--- |
| 17 | `toBeCloseTo` |
| 15 | `nthCalledWith` |
| 25 | `nthReturnedWith` |
| 15 | `toHaveBeenNthCalledWith` |
| 25 | `toHaveNthReturnedWith` |
See also pictures in following comments
Baseline at left and **improved at right**
> expect, jest-snapshot: Change color from green for some args in matcher hints

- CHANGELOG.md
- scripts/checkCopyrightHeaders.js
What do y’all think? In the first draft of #8783 a joined substring found some mistakes:
* 6 files with extra redundant `All rights reserved.` line between copyright and license
* missing period at end of copyright line in `checkCopyrightHeaders.js` itself ;)
that searching for the 3 lines independently (in the merged code) does not find
`yarn check-copyright-headers`
After #8809 the script will pass when run locally on Windows system, correct?
Tim, thanks again for researching such a smart solution ❤️
> chore: Check copyright and license as one joined substring

- packages/jest-transform/src/ScriptTransformer.ts
Builds on #8756 by adding an override that does not require you to handle a promise unless you pass your own function which returns a promise. This is needed for #8330.
I'm not sure I got the type info correct here, can somebody who actually knows TS tell me if this is correct? 😅 If it's hard with overrides, I'm happy to have another go with 2 different methods rather than `if (isPromise)`.
/cc @M4rk9696 @G-Rath  
Still green CI
(purposefully no changelog entry as it's conceptually part of the unreleased #8756)
> feat: add sync way of requiring and transpiling module

- CHANGELOG.md
- packages/pretty-format/README.md
Fixes #8777
`yarn lint:prettier`
> chore: Delete obsolete link and simplify structure in pretty-format README

- CHANGELOG.md
- packages/jest-runner/src/index.ts
The following type are required to be exported from `jest-runner`, so that they can be imported when writing a runner in Typescript
Type signature of `runTests`
```js
async runTests(
tests: Array<Test>,
watcher: TestWatcher,
onStart: OnTestStart,
onResult: OnTestSuccess,
onFailure: OnTestFailure,
options: TestRunnerOptions,
): Promise<void>
```
Types needed to be exported
```
OnTestFailure
OnTestStart
OnTestSuccess
TestWatcher 
TestRunnerContext 
TestRunnerOptions
```
Needed for #8810 
/cc @SimenB 
The existing test cases should cover it, will be adding a test using the types when raising a PR for 
#8810
> Export necessary types from jest-runner

- CHANGELOG.md
- packages/jest-reporters/package.json
- packages/jest-reporters/src/notify_reporter.ts
- yarn.lock
See discussion https://github.com/facebook/jest/issues/8830
> Add timeout to prevent notifier from locking CPU on MacOS

- CHANGELOG.md
- packages/jest-haste-map/src/index.ts
This is a workaround for an issue that occurs in node 12.5.0 and newer, described in detail here:  https://github.com/nodejs/node/issues/29001
The behavior of the code in question is the same, however the change is enough to prevent locking the process into a "cancerous" state of memory growth.
This is one of the weirdest bugs I've ever debugged.
Under certain circumstances, Node process (starting from version 12.5.0, previous versions not affected), would not exit (even if we call `process.exit()` at the end of the file), and instead start to consume memory until it fills the whole available memory, using 100% CPU while at it.
Here's a reproduction based on the `HasteMap`:
https://gist.github.com/niieani/a527e9b2e6caf28e3021a50b938e4a91
Standard memory or CPU profiling doesn't show …
> Workaround a node >=12.5.0 bug that causes the process not to exit after tests have completed and cancerous memory growth

- docs/ManualMocks.md
- website/versioned_docs/version-23.x/ManualMocks.md
`addListener` and `removeListener` are [deprecated](https://github.com/microsoft/TypeScript/blob/602966ba4ecd0ef7923be61806b98755e2919501/lib/lib.dom.d.ts#L10380) in a favor of `addEventListener` and `removeEventListener`.
From [MediaQueryList/addListener](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener)
> This (addListener) is basically an alias for EventTarget.addEventListener(), for backwards compatibility purposes.
They are supported by all major browsers: [EventTarget/addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener)
BTW, `TSLint` is producing the following error when trying to use `addListener`:
```
ERROR: /app/Component.tsx:xx:xx - addListener is deprecated.
```
> Updated matchMedia methods

- docs/Configuration.md
- website/versioned_docs/version-22.x/Configuration.md
- website/versioned_docs/version-23.x/Configuration.md
- website/versioned_docs/version-24.0/Configuration.md
- website/versioned_docs/version-24.1/Configuration.md
- website/versioned_docs/version-24.6/Configuration.md
- website/versioned_docs/version-24.8/Configuration.md
- website/versioned_docs/version-24.9/Configuration.md
This makes a one-word grammatical fix.
Before this change:
After:
[CONTRIBUTING.md](https://github.com/facebook/jest/blob/master/CONTRIBUTING.md#changelog-entries) says to update CHANGELOG.md for "significant changes to the documentation," so it is not updated for this PR.
> Fix grammar: "your jest's config"->"your Jest..."

- docs/TestingFrameworks.md
At this time, using AngularJS is different from the past. Many articles are not mentioned, including `AngularJS 1.5+` component, using ES6 syntax, using webpack and installing Jest and related suites, where `angularjs-jest` in Jest greatly reduces the initial process of `angularjs.mock.module` and `angularjs.mock.inject`.
In my article, there are clear guidelines to help you use Jest to maintain an AngularJS test project.
```shell
npm install
npm run test
```
run jest
> add Jest work with AngularJS tutorial

- CHANGELOG.md
- docs/SnapshotTesting.md
- website/versioned_docs/version-22.x/Configuration.md
- website/versioned_docs/version-22.x/SnapshotTesting.md
- website/versioned_docs/version-23.x/Configuration.md
- website/versioned_docs/version-23.x/SnapshotTesting.md
- website/versioned_docs/version-24.0/Configuration.md
- website/versioned_docs/version-24.0/SnapshotTesting.md
Stumbled upon a broken link and figured I'd fix things up. Looks like the file was simply migrated to TypeScript from JS, but the link was never updated.
**Before**: 😢
**After** rebuilding the docs site [e.g., `cd website && yarn build && cd build/jest && serve`]): 👌
--------------
While I was at it, I grep'd through the docs codebase to see if I could find any other stray broken links, and found a few docs pointing to a `types/TestRunner.js` file that no longer exists. Looks like the 404 was [fixed](https://github.com/facebook/jest/pull/8214) in v24.1, but wasn't back-ported to earlier releases:
```console
λ rg types/TestRunner.js --files-with-matches
website/versioned_docs/version-24.0/Configuration.md
website/versioned_docs/version-23.x/Configuration.md …
```
> fix(docs): Update broken links in docs.

- CHANGELOG.md
Hey hey team Jest — I recently updated the CHANGELOG in #8847... and accidentally introduced a [linting failure in CI](https://circleci.com/gh/facebook/jest/69316?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). A little ironic because I only disabled my prettier autoformat config in vim so that it wouldn't create huge diffs in the other files I was touching. Whoops. 🙃 Sorry all! ❤️ This should set things straight, apart from the unrelated failure in the `jest-circus` job.
> fix(linter): Fix linting failure introduced in #8847 😓

- CHANGELOG.md
- packages/jest-leak-detector/README.md
- packages/jest-leak-detector/package.json
- packages/jest-leak-detector/src/__tests__/index.test.ts
- packages/jest-leak-detector/src/index.ts
- packages/jest-runner/src/runTest.ts
- yarn.lock
At https://github.com/facebook/jest/issues/8397, we know `weak` package doesn't work in Node version 12 and we use `weak-napi` package instead of `weak` in new version. `weak-napi`  have interface like `weak` package but it still have some [differences](https://github.com/node-ffi-napi/weak-napi#differences-from-node-weak) suck as:
```
GC callbacks are invoked at a suitable time (after the actual GC run has finished). This is nice because it means your process won’t potentially crash.
```
The consequence of this is that the `isLeaking` function in `jest-leak-detector` package return value must be converted into a promise to wait a bit time.
Fixes #8397
> Update `jest-leak-detector` package to be compatible with the new Node version

- CHANGELOG.md
- e2e/__tests__/config.test.ts
- e2e/environmentOptions/__tests__/environmentOptions.test.js
- packages/jest-environment-jsdom/package.json
- yarn.lock
> chore: upgrade jsdom

- .circleci/config.yml
- CHANGELOG.md
- e2e/__tests__/__snapshots__/errorOnDeprecated.test.ts.snap
- e2e/__tests__/__snapshots__/failures.test.ts.snap
- e2e/__tests__/errorOnDeprecated.test.ts
- e2e/__tests__/failures.test.ts
Node 12 is out, and it's shiny!
Probably gonna fail due to #8397
> chore: test on node 12

- CHANGELOG.md
- package.json
- packages/jest-config/package.json
- packages/jest-config/src/normalize.ts
- packages/jest-core/package.json
- packages/jest-core/src/SearchSource.ts
- packages/jest-haste-map/package.json
- packages/jest-haste-map/src/HasteFS.ts
- packages/jest-haste-map/src/lib/FSEventsWatcher.ts
- packages/jest-message-util/package.json
- packages/jest-message-util/src/index.ts
- packages/jest-transform/package.json
- packages/jest-transform/src/shouldInstrument.ts
- yarn.lock
Hopefully this fixes some of out performance issues.
Green CI
> chore: upgrade to micromatch v4

- CHANGELOG.md
- packages/jest-snapshot/src/__tests__/utils.test.ts
- packages/jest-snapshot/src/index.ts
- packages/jest-snapshot/src/utils.ts
Because a custom serializer might return a string with newlines or spaces at beginning or end, `trim` is not the correct method (pardon pun :) to remove the two newlines that were added at beginning and end of multiline content.
Example of the problem: https://github.com/facebook/jest/pull/8850#issuecomment-522970938 and https://github.com/facebook/jest/pull/8850#issuecomment-523065051
Added 7 tests
See also pictures in the following comment for local end-to-end test
> jest-snapshot: Remove only the added newlines in multiline snapshots

- CHANGELOG.md
- packages/jest-config/src/__tests__/__snapshots__/normalize.test.js.snap
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/color.ts
- packages/jest-config/src/normalize.ts
Follow up to @natealcedo's #8025, automatically generating reasonable defaults for that feature.
BREAKING CHANGE:
See comment that was removed. Looks like it'll have to wait until 25 :|
TODO add changelog when there's a section to put it in without having to rebase ;)
Added normalize tests. Tried on work project, tests are white, lints are green :)
> set default display name color based on runner

- packages/jest-leak-detector/package.json
- packages/jest-leak-detector/src/index.ts
Discovered we still need this when upgrading to 25 at work.
```sh-session
$ docker run --interactive --tty --rm node:lts-alpine yarn add weak-napi
$ docker run --interactive --tty --rm node:lts-alpine sh -c "apk add --no-cache python && yarn add weak-napi"
```
You need to install quite a bit of stuff
This is essentially #5252 again
Dunno...
> chore: make `weak-napi` optional

- CHANGELOG.md
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
- packages/jest-jasmine2/src/reporter.ts
- packages/jest-test-result/src/helpers.ts
- packages/jest-test-result/src/index.ts
Based on a suggestion in #8823
Creating an util in `@jest/test-result` which will create an empty `TestResult`
/cc @SimenB 
Existing test cases should work after the change
> Add util to create empty testResult

- CHANGELOG.md
- e2e/Utils.ts
- e2e/__tests__/fatalWorkerError.test.ts
- e2e/__tests__/workerForceExit.test.ts
- package.json
- packages/jest-runner/src/__tests__/testRunner.test.ts
- packages/jest-runner/src/index.ts
- packages/jest-worker/README.md
- packages/jest-worker/src/__tests__/index.test.js
- packages/jest-worker/src/base/BaseWorkerPool.ts
- packages/jest-worker/src/base/__tests__/BaseWorkerPool.test.js
- packages/jest-worker/src/index.ts
- packages/jest-worker/src/types.ts
- packages/jest-worker/src/workers/ChildProcessWorker.ts
- packages/jest-worker/src/workers/NodeThreadsWorker.ts
- packages/jest-worker/src/workers/__tests__/ChildProcessWorker.test.js
- packages/jest-worker/src/workers/__tests__/NodeThreadsWorker.test.js
- packages/jest-worker/src/workers/__tests__/processChild.test.js
- packages/jest-worker/src/workers/__tests__/threadChild.test.js
- packages/jest-worker/src/workers/processChild.ts
- packages/jest-worker/src/workers/threadChild.ts
- yarn.lock
This PR makes child process workers avoid `process.exit`, instead gracefully exiting them by clearing open handles. If they fail to exit gracefully (usually because the user code leaks) after a delay, they are force exited using `SIGTERM` and if that doesn't help after another delay using `SIGKILL`. For Node worker threads, the force exit method is `terminate()`.
The primary use for this (besides being cleaner) is that we can at least print a warning if tests leak open handles (which this PR also does) instead of effectively just cancelling the whole event loop by terminating the worker. Many users have complained about bugs like `console.log`s being lost and this is likely one of the reasons why stuff like that happens, hopefully exiting gracefully can reduce such hard-to-debug behavior …
> exit workers gracefully

- CHANGELOG.md
- e2e/run-programmatically/cjs.js
- e2e/run-programmatically/esm.js
- packages/babel-plugin-jest-hoist/src/index.ts
- packages/jest-cli/src/index.ts
- packages/jest-jasmine2/src/index.ts
- packages/jest-jasmine2/src/jasmine/jasmineLight.ts
- packages/jest-validate/src/index.ts
- packages/jest/package.json
- packages/jest/src/jest.ts
- packages/jest/tsconfig.json
We wanna migrate off of `export =` as it's not valid JS. These ones should be free as they already export objects. Marking them as breaking, but it should just be breaking for people using `TS` - either `import` or `require` should work the same
Green CI
> chore: convert jest-cli and jest-validate to esm

- packages/jest-console/package.json
- packages/jest-console/src/CustomConsole.ts
- packages/jest-console/src/__tests__/CustomConsole.test.ts
- packages/jest-console/tsconfig.json
- packages/jest-core/src/cli/index.ts
- packages/jest-core/src/runJest.ts
- packages/jest-util/src/clearLine.ts
- packages/jest-util/src/preRunMessage.ts
Part of #8863 (which broke the cycle this change would have introduced), so no separate changelog.
Green CI
> chore: import clearline rather than duplicating it

- .azure-pipelines-steps.yml
- .azure-pipelines.yml
Hopefully this'll speed up CI.
Green CI with some nice cache output?
> chore: add caching to azure pipelines

- packages/jest-cli/src/cli/args.ts
- packages/jest-config/src/ValidConfig.ts
- packages/jest-transform/src/ScriptTransformer.ts
We've upgraded to a version of Babel that supports this syntax
Green CI
> chore: use `as const` rather than casting individual strings

- CHANGELOG.md
- e2e/__tests__/__snapshots__/failures.test.ts.snap
- e2e/__tests__/detectOpenHandles.ts
- e2e/__tests__/iterator-to-null-test.ts
- e2e/__tests__/snapshot.test.ts
- e2e/__tests__/snapshotMockFs.test.ts
- e2e/__tests__/snapshotResolver.test.ts
- e2e/__tests__/snapshotSerializers.test.ts
- e2e/auto-clear-mocks/with-auto-clear/index.js
- e2e/bad-source-map/__tests__/badSourceMap.js
- e2e/clear-cache/__tests__/clearCache.test.js
- e2e/failures/macros.js
- e2e/mock-names/with-empty-mock-name-not-called/index.js
- e2e/mock-names/with-empty-mock-name/index.js
- e2e/mock-names/with-mock-name-call-times-fail/index.js
- e2e/mock-names/with-mock-name-call-times-pass/index.js
- e2e/mock-names/with-mock-name-not-called-fail/index.js
- e2e/mock-names/with-mock-name-not-called-pass/index.js
- e2e/mock-names/with-mock-name-not-called/index.js
- e2e/mock-names/with-mock-name/index.js
- e2e/mock-names/without-mock-name-not-called/index.js
- e2e/mock-names/without-mock-name/index.js
- e2e/override-globals/index.js
- e2e/run-programmatically/index.js
As far as I can find, this is the last of them:
* 1 in `./e2e/__tests__/detectOpenHandles.ts`
* 2 in `./e2e/__tests__/iterator-to-null-test.ts`
* 3 in `./e2e/__tests__/snapshot.test.ts`
* 1 in `./e2e/__tests__/snapshotMockFs.test.ts`
* 1 in `./e2e/__tests__/snapshotResolver.test.ts`
* 1 in `./e2e/__tests__/snapshotSerializers.test.ts`
EDIT here is the command that I used to find those file in the project:
```sh
fgrep -lr --exclude-dir 'node_modules' --include '*.[j|t]s' '$FlowFixMe' .
```
Local lint and tests, and then CI
> chore: Delete obsolete FlowFixMe comments

- packages/jest-transform/src/ScriptTransformer.ts
In the current implementation of `requireAndTranspileModule` the `extensions` used for pirates is determined by `path.extname`. `path.extname` returns empty string for directories, which resulted in `PnP` test failing in #8854. Restricting the extensions to the ones specified in `moduleFileExtensions`
/cc @SimenB @jeysal 
Existing tests should not break
All PRs related to #8810 should not be affected
> Refractor requireAndTranspileModule to use exts from moduleFileExtenstions

- CHANGELOG.md
- e2e/__tests__/toMatchSnapshotWithStringSerializer.test.ts
- e2e/to-match-snapshot-with-string-serializer/package.json
- e2e/to-match-snapshot-with-string-serializer/serializers/string.js
- packages/jest-snapshot/src/State.ts
- packages/jest-snapshot/src/index.ts
When I tested the report for edge case that snapshot is **empty string** from custom serializer and received value is non-empty string, Jest confused it with new snapshot not written:
Fixed three places where the code distinguished snapshot from no snapshot:
* baseline: truthy versus falsey
* improved: string versus undefined (or nil, see Question) following example of code snippet:
```js
const hasSnapshot = isInline
? inlineSnapshot !== ''
: this._snapshotData[key] !== undefined;
```
**Question**: What do you think about the conditional expression where `undefined` becomes `null` in the object that `match` returns? I am trying to keep the changes in complicated code to a minimum, but it fails the `grep` test to be able to find `undefined` :(
**Residue**:
* The test feedback above does …
> jest-snapshot: Distinguish empty string from external snapshot not written

- CHANGELOG.md
- e2e/__tests__/toMatchSnapshotWithStringSerializer.test.ts
- packages/jest-snapshot/src/State.ts
- packages/jest-snapshot/src/index.ts
**Breaking change**: Add boolean `isInline` property to `SnapshotMatchOptions` so
* `inlineSnapshot: undefined` means internal snapshot **not written** instead of external snapshot
* `inlineSnapshot: ''` means **empty string** instead of internal snapshot not written
While trouble-shooting #8880 empty string in external snapshot, I found that internal snapshots had similar problem with different effect:
1. `'--ci=false'` when inline snapshot is **empty string** and received value is non-empty string, then instead of **ordinary failure**, test passes and replaces expected with received
2. `'--ci=true'` when inline snapshot was **not written**, test has ordinary failure with empty string as expected value
Edge case 1 requires custom serializer which writes empty string not enclosed in quote …
> jest-snapshot: Distinguish empty string from internal snapshot not written

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/jest-diff/src/__tests__/__snapshots__/getAlignedDiffs.test.ts.snap
- packages/jest-diff/src/getAlignedDiffs.ts
It distracts attention of reviewer if entire change line has inverse format
Updated snapshots:
| | package | test |
| ---: | ---: | :--- |
| 11 | jest-diff | getAlignedDiffs |
| 1 | expect | matchers |
Realistic regression tests for the win: the code change was more subtle than I thought
Example pictures baseline at left and **improved at right**
The inverse lines fight for attention with the substrings within lines:
The inverse lines add insult to injury ~~when cleanup merges `from` and `to` into changes because common `o` is chaff~~:
To set the record straight, merging `o` chaff into `from` and `to` changes is good cleanup. The problem is the length criterion where common substring `'change '.length` does not have greater  length than adjacent change substring `'delete\n'.length` so is …
> jest-diff: Do not inverse format if line consists of one change

- docs/Configuration.md
> chore: remove mention of outdated jsdom from docs

- CHANGELOG.md
- packages/jest-diff/README.md
- packages/jest-diff/src/__tests__/__snapshots__/diff.test.ts.snap
- packages/jest-diff/src/__tests__/__snapshots__/getAlignedDiffs.test.ts.snap
- packages/jest-diff/src/__tests__/__snapshots__/joinAlignedDiffs.test.ts.snap
- packages/jest-diff/src/__tests__/diff.test.ts
- packages/jest-diff/src/__tests__/getAlignedDiffs.test.ts
- packages/jest-diff/src/__tests__/joinAlignedDiffs.test.ts
- packages/jest-diff/src/diffLines.ts
- packages/jest-diff/src/getAlignedDiffs.ts
- packages/jest-diff/src/joinAlignedDiffs.ts
- packages/jest-diff/src/normalizeDiffOptions.ts
- packages/jest-diff/src/printDiffs.ts
- packages/jest-diff/src/types.ts
Provide options for the remaining 2 hard-coded colors used by `diffStringsUnified`
**Residue**: the default export can output 2 additional hard-coded colors in edge cases:
1. `cyan` for lines for which indentation is the only difference: will be superseded by `ignoreIndentation` option and no color distinction for such common lines
2. `bgYellow` for leading or trailing spaces in common lines, because inverse of dim is invisible, but it is not clear that they need formatting
@thymikee after the residue has been solved, it seems like the default `colors: false` option in `snapshot-diff` package can replace `strip-ansi` with identity function for `jest-diff` color options
Added 1 and updated 3 snapshots in `diffs.test.ts.snap`
Add string serializer to omit double quote marks and use options …
> jest-diff: Add changeColor and patchColor options

- website/pages/en/index.js
- website/static/css/jest.css
We're starting to get quite a lot of people signing up for the SEO boost from sites that TBH Jest shouldn't be pushing (online casinos, textbook cheating etc) - that's a bit sucky, but it's also annoying that these company pretty regularly email or DM a few of the core devs about these links not appearing on the site instantly.
This should de-incentivize this behavior. Also makes the BG white instead of green.
> Add ref=nofollow to backers on the site

- CHANGELOG.md
- e2e/timer-reset-mocks/after-reset-all-mocks/timerAndMock.test.js
- e2e/timer-reset-mocks/with-reset-mocks/timerWithMock.test.js
- examples/timer/__tests__/infinite_timer_game.test.js
- examples/timer/__tests__/timer_game.test.js
- packages/jest-fake-timers/package.json
- packages/jest-fake-timers/src/FakeTimersLolex.ts
- packages/jest-fake-timers/src/__tests__/__snapshots__/fakeTimersLolex.test.ts.snap
- packages/jest-fake-timers/src/__tests__/fakeTimersLolex.test.ts
- packages/jest-fake-timers/src/index.ts
- packages/jest-jasmine2/src/__tests__/pTimeout.test.ts
- yarn.lock
Adds the implementation of fake timers using Lolex from all of my other PRs. Note that this does _not_ include a way to actually use this in Jest - It's just the implementation. This is not terribly useful on its own, but it makes it easier to keep up to date with the current implementation, and less rebasing work.
Test added, which is a copy of the current tests with initialization changed for Lolex
> feat: add fake timers implementation backed by Lolex

- CHANGELOG.md
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/normalize.ts
When using a jest preset that contains a general `Error` (not a `SyntaxError` or `TypeError`) `jest-config` throws a `"Preset ... not found"` validation error.
This is somewhat misleading for users of a broken preset that may just be missing a peer dependency. 
To get around this in `jest-expo` I wrap the requires of peer dependencies in try/catch, rethrow the meaningful error message, then exit the process to prevent users from thinking the preset is missing.
- Attempting to require any missing library in a Jest preset should result in a useful error message like: 
```sh
● Validation Error:
Error resolving jest-expo/web:
Cannot find module 'react-native-web'
Error: Cannot find module 'react-native-web'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at …
```
> [jest-config] Changed "Preset ... not found" validation error

- docs/TutorialAsync.md
`it` is used everywhere in TutorialAsync.md except for one test where `test` is used. This commit replaces that `test` with an `it` to keep things consistent and because there does not seem to be a good reason to use `test` over `it` here.
> Replace `test` with `it` in TutorialAsync.md

- CHANGELOG.md
- e2e/__tests__/transform.test.ts
- e2e/transform/cache/__tests__/aTests.js
- e2e/transform/cache/__tests__/bTests.js
- e2e/transform/cache/__tests__/cTests.js
- e2e/transform/cache/__tests__/dTests.js
- e2e/transform/cache/common-file.js
- e2e/transform/cache/package.json
- e2e/transform/cache/transformer.js
- packages/jest-transform/src/ScriptTransformer.ts
May or may not fix #7811, but it looks pretty good!
---
Due to the changes in #7186, we no longer cached transformed files between tests within a single worker. Not sure why, but we get a cache miss in the weakmap. Anyone has any good ideas?
@rafeca I realise you don't work at FB aymore, but FYI just in case you remember some context or have any comments 🙂 
Added test. Without the changes in `ScriptTransformer`, this is the result of the new test:
(I've since tweaked this test to work on Windows, but it's still essentially accurate)
> fix: cache transforms within a worker

- packages/jest-circus/README.md
A minor yet important syntax fix in the main README.md. 'Had me confused...
Also, aligns it with the Jest's [environment associated documentation](https://jestjs.io/docs/en/configuration#testenvironment-string).
N/A
> Fix NodeEnvironment import in README.md

- website/pages/en/index.js
Hi there! I noticed that you list financial backers on your homepage (which is _awesome_ by the way) and even allow them to link to their own websites — but as of now you have links to a few dozen random sites (and some pretty sketchy ones [[1]](https://buycheaprdp.com/) [[2]](https://tips4videotodvd.co.uk/) [[3]](https://playroulette.co.uk/) [[4]](https://www.windows-10.nl/) to be blunt) without using `rel=noopener` which is an understated security risk. @mathiasbynens does a better job of explaining/demonstrating this than I could ever do here: https://mathiasbynens.github.io/rel-noopener/ 
It might be a good practice to add this to all external links to be super safe, but I've only added it to the links to lower-tier backers that are pulled automatically from Open Collective.
(I'd …
> Use rel="noopener" on backer links (possible security risk with some sketchy websites)

- CHANGELOG.md
- packages/jest-reporters/package.json
- packages/jest-reporters/src/__tests__/notify_reporter.test.ts
- packages/jest-reporters/src/notify_reporter.ts
`notify` is an optional feature that is disabled by default. Its implementation requires [node-notifier](https://github.com/mikaelbr/node-notifier), which distributes snoreToast, a [LGPL-3.0 executable](https://github.com/mikaelbr/node-notifier/tree/master/vendor/snoreToast). node-notifier also includes terminal-notifier and notifu which are not MIT licensed.
My employer will not import node-notifier to our npm repository due to the LGPL executable which means we cannot use jest.
This pull request make node-notifier an optional dependency, so jest install will not fail if node-notifier cannot be found. jest will throw an error if notifications are enabled and node-notifier cannot be found.
Tested by running `jest --notify` after removing `node-notifier` from node_modules.
> jest errors …
> feat: make node-notifier an optional dependency

- docs/UsingMatchers.md
- website/versioned_docs/version-22.x/UsingMatchers.md
The code snippet using on ['Using Matchers' docs under Exceptions section is broken](https://jestjs.io/docs/en/using-matchers#exceptions).
The code snippet is using, `ConfigError` inside `compileAndroidCode` function. Running the test, throws following error `ReferenceError: ConfigError is not defined`.
I have changed, `ConfigError` to generic [`Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error).
So the original snippet of code now looks like this:
```js
function compileAndroidCode() {
throw new Error('you are using the wrong JDK');
}
test('compiling android goes as expected', () => {
expect(compileAndroidCode).toThrow();
expect(compileAndroidCode).toThrow(Error);
// You can also use the exact error message or a regexp …
```
> Fix example code on `using matchers` docs

- CHANGELOG.md
- e2e/__tests__/detectOpenHandles.ts
- e2e/detect-open-handles/__tests__/unref.js
- packages/jest-core/src/collectHandles.ts
- packages/test-utils/src/ConditionalTest.ts
- packages/test-utils/src/index.ts
Fix #8939 
Note that this shouldn't affect any behaviour in Node < 11, and because of that the test is skipped in older versions. It passes happily for me locally with Node 12.9.1 though.
It would be possible to extend this to cover old versions later on (by wrapping `ref()`/`unref()`) if that seems worthwhile for somebody.
> Don't include unref'd timers in --detectOpenHandles results

- packages/jest-diff/src/__tests__/__snapshots__/diff.test.ts.snap
- packages/jest-diff/src/__tests__/diff.test.ts
Display colors concisely and clearly so you can review future changes quickly and confidently
Also omits distracting escape of double quote marks
* Use `addSnapshotSerializer` for only the expected colors with one-letter tag names
* Use `stripAnsi` only for edge case error messages
* Replace `stripAnsi` with options and `toMatch` with `toBe` in assertions for comparison lines (which as a future chore could become snapshots with the serializer and `omitAnnotationLines` option)
**Question**: Before I go on to 5 snapshot test files in `expect` package, do I need to consider an alternative to repetition of the same or very similar inline serializer?
* `diff.test.ts.snap` updated 35
> chore: Align snapshots in jest-diff

- CHANGELOG.md
- examples/react/.babelrc.js
- examples/react/package.json
When I'm using React test example, it brokes the tests because the Babel component is missing to run the same.
To test my fix, uses:
```shell script
cd examples/react
npm install && npm run test
```
> [React Test Example] Fixed babel to example tests

- CHANGELOG.md
- docs/Configuration.md
- docs/JestObjectAPI.md
- website/versioned_docs/version-22.x/JestObjectAPI.md
- website/versioned_docs/version-23.x/JestObjectAPI.md
- website/versioned_docs/version-24.0/Configuration.md
- website/versioned_docs/version-24.0/JestObjectAPI.md
- website/versioned_docs/version-24.1/Configuration.md
- website/versioned_docs/version-24.6/Configuration.md
- website/versioned_docs/version-24.8/Configuration.md
- website/versioned_docs/version-24.9/Configuration.md
- website/versioned_docs/version-24.9/JestObjectAPI.md
The current docs did not efficiently explain setupTestFrameworkScriptFile was deprecated nor give a clear example of how to use.
n/a as doc changes only
> docs: Add `setupFilesAfterEnv` and `jest.setTimeout` example

- packages/expect/src/__tests__/__snapshots__/assertionCounts.test.js.snap
- packages/expect/src/__tests__/__snapshots__/extend.test.js.snap
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/__snapshots__/spyMatchers.test.js.snap
- packages/expect/src/__tests__/__snapshots__/toThrowMatchers.test.ts.snap
- packages/expect/src/__tests__/assertionCounts.test.js
- packages/expect/src/__tests__/extend.test.js
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/__tests__/spyMatchers.test.js
- packages/expect/src/__tests__/toThrowMatchers.test.ts
- packages/expect/tsconfig.json
Display colors concisely and clearly to review changes quickly and confidently
Too bad about the blame, but the next pull request to `expect` will illustrate the benefit
Updated 903 snapshots:
| | file |
| ---: | :--- |
| 1 | `assertionCounts.test.ts.snap` |
| 7 | `extend.test.ts.snap` |
| 521 | `matchers.test.ts.snap` |
| 308 | `spyMatchers.test.ts.snap` |
| 66 | `toThrowMatchers.test.ts.snap` |
Substring differences for the win to review changes locally before updating snapshots :)
But double tests for spy and toThrow matchers added insult to eye injury :(
> chore: Align snapshots in expect

- e2e/__tests__/detectOpenHandles.ts
- e2e/__tests__/unexpectedToken.test.ts
- packages/jest-transform/src/ScriptTransformer.ts
Should fix e.g. https://circleci.com/gh/facebook/jest/72260
Green CI
> chore: update test for new node 12 error message

- CHANGELOG.md
- e2e/__tests__/__snapshots__/failures.test.ts.snap
- packages/expect/src/__tests__/__snapshots__/extend.test.js.snap
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/__snapshots__/toThrowMatchers.test.ts.snap
- packages/jest-matcher-utils/src/__tests__/__snapshots__/index.test.ts.snap
- packages/jest-matcher-utils/src/__tests__/__snapshots__/printDiffOrStringify.test.ts.snap
- packages/jest-matcher-utils/src/index.ts
In the `printDiffOrStringify` function, add `includeChangeCounts` option to calls:
* `diffStringsUnified`
* `diffDefault`
For consistency with #8982 to interpret differences when other assertions fail
**Residue**
Did not add `includeChangeCounts` option:
* to spy matchers because not separate annotations for multiple diffs per call
* to `diff` named export from `jest-matcher-utils` but caller can add it
I noticed something brittle about a few snapshots of matcher errors which contain diffs: when I tested with `--expand` option to see all of the lines in the snapshot to count changes, it affected the matcher, which is not correct.
Updated 76 snapshots
The differences between empty and non-empty map or object are example where change counts would be even clearer in a data-driven-diff
| | …
> expect, jest-matcher-utils: Display change counts in annotation lines

- CHANGELOG.md
- packages/jest-reporters/package.json
- packages/jest-reporters/src/__tests__/get_result_header.test.js
- packages/jest-reporters/src/get_result_header.ts
- yarn.lock
Closes #8937
Straightforward change, file paths will now become hyperlinks in terminals that support it. In the ones that don't they will stay the same. I was thinking about displaying the paths somehow (flag??) as they are still clickable and quite useful in the Terminal.app even though they are not exactly hyperlinks.
I've used commonJS modules to import the lib as we don't have `esModuleInterop` flag in TS config, can you see any reasons for not using it?
Hyperlink in ITerm2:
Hyperlink in ITerm2 when hovered with CMD pressed:
Hyperlink in Terminal.app without a fallback:
^ It's ugly, but useful which makes me wonder if it would be worth it to add some kind of flag for it.
> feat: transform file paths into hyperlinks

- packages/diff-sequences/README.md
It seems that the Usage section of README for `diff-sequences` is incorrect.
CommonJS users have to do `var diff = require('diff-sequences').default` in order to use `diff-sequences`. Not `var diff = require('diff-sequences')` as stated in the documentation.
Existing documentation of `diff-sequences` states the following:
> To use `diff` as the name of the default export from this package, do either of the following:
> - `var diff = require('diff-sequences'); // CommonJS modules`
> - `import diff from 'diff-sequences'; // ECMAScript modules`
Unfortunately the `require`-based version is not working as expected. Steps to reproduce:
```bash
mkdir repro
cd repro
npm init -y
npm i diff-sequences
echo "var diff = require('diff-sequences'); diff()" > main.js
node main.js # fails with error: diff …
```
> docs: Fix invalid Usage section for diff-sequences in README

- CHANGELOG.md
- packages/expect/src/__tests__/utils.test.js
- packages/expect/src/utils.ts
Fixes #8947
When the `getObjectSubset` function copies the relevant subset of object properties recursively, it creates ordinary `Object` instances. If expected and received values are a subclass or typed array, then the type change of the received subset becomes an incorrect change in the difference when `toMatchObject` fails.
If corresponding values:
* are subset match, then return the expected value instead of a copy of the received value
* are not subset match, then incorrect type difference is still possible
Although the function returns an unnecessary copy for arrays, I left it as is, because the `map` method returns the same array class as the subset
Background information:
* `toMatchObject` does not require same type: like `toEqual` and unlike `toStrictEqual`
* `Array.isArray` …
> expect: Avoid incorrect difference for subset when toMatchObject fails

- CHANGELOG.md
- docs/CLI.md
Having been confused myself, as well as noting the same confusion in forums. Many people cannot figure out how to turn off coverage reports, if the option has been set via Configuration.
Note, a similar confusion/change apply to other boolean options as well, but that's not covered in this PR.
n/a
> docs: Add collectCoverage to Reference

- README.md
- docs/GettingStarted.md
- website/versioned_docs/version-24.6/GettingStarted.md
Trivial grammar fix: corrects "they are ran" to "they are run"
> Docs: trivial grammar fix to GettingStarted.md

- .eslintrc.js
- packages/jest-haste-map/src/lib/FSEventsWatcher.ts
Related issue #9015
On macOS, the 'import/no-unresolved' rule doesn't throw an error when importing 'fsevents' module. Therefore it does not need to disable this rule, because eslint throws an error when `--report-unused-disable-directives` is used. In my opinion, the best way is to ignore `fsevents` import.
Linting without caching:
`eslint . --report-unused-disable-directives --ext js,jsx,ts,tsx,md`
> chore: fix linting error on macOS

- packages/pretty-format/src/index.ts
- packages/pretty-format/src/plugins/AsymmetricMatcher.ts
- packages/pretty-format/src/plugins/ReactTestComponent.ts
`Symbol` is not defined in es5 environments but accessed regardless. The approach is similar to reacts:
https://github.com/facebook/react/blob/5faf377df5267c4248599e14311a75c2f46050c0/packages/shared/ReactSymbols.js#L14-L16
We use `1357` for `jest`:
```js
1357
jest
``` 
I haven't looked much into the test setup. At a surface level this should already throw in an es5 environment (which is implied by e.g. `lint-es5-build`).
> fix(pretty-format): Use symbol safely only when it's defined

- .circleci/config.yml
- CONTRIBUTING.md
- packages/jest-worker/src/workers/NodeThreadsWorker.ts
- packages/jest-worker/src/workers/threadChild.ts
Now in [CONTRIBUTING.md](https://github.com/facebook/jest/blob/master/CONTRIBUTING.md), it is recommended to use node `10.x` for development because of this bug #8490. Since that bug was fixed and node 12 [became LTS](https://medium.com/@nodejs/node-js-12-to-lts-and-node-js-13-is-here-e28d6a4a2bd), I suggest switching to node 12 as a recommendation for contributing and linting.
What this PR does:
1. Fix lint errors in node 12
2. Update CircleCI config to use node 12 for linting
3. Update contributing documentation
close #9015 
Green CI
> Suggesting to use node 12 as default

- CHANGELOG.md
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/normalize.ts
Resolves #9026 
Unit test "preset with globals" added to `packages/jest-config/src/__tests__/normalize.test.js`
> feat(jest-config): merge preset globals with project globals

- .azure-pipelines-steps.yml
- .circleci/config.yml
- .travis.yml
#9088 without node 13. will minimize that diff (and maybe speed up CI)
green CI
> chore: move full CI run from node 10 to 12

- CHANGELOG.md
- packages/jest-diff/README.md
- packages/jest-diff/src/__tests__/__snapshots__/diff.test.ts.snap
- packages/jest-diff/src/__tests__/diff.test.ts
- packages/jest-diff/src/__tests__/joinAlignedDiffs.test.ts
- packages/jest-diff/src/index.ts
- packages/jest-diff/src/normalizeDiffOptions.ts
- packages/jest-diff/src/printDiffs.ts
- packages/jest-diff/src/types.ts
- packages/jest-matcher-utils/src/index.ts
- packages/jest-snapshot/src/printSnapshot.ts
1. Split and rename `trailingSpaceFormatter` option as prerequisite to improve snapshot colors:
* `changeLineTrailingSpaceColor` because `aColor` and `bColor` might have background color
* `commonLineTrailingSpaceColor` because `dim` does not modify like other colors
2. Rename `firstOrLastEmptyLineReplacement` as `emptyFirstOrLastLinePlaceholder`
3. Change default values so dependents can turn them on instead of need to turn them off (not breaking, because the new options have not yet been published)
4. Edit `README.md` table and examples of new options
5. Provide explicit values for these options in `jest-matcher-utils` and `jest-snapshot`
6. Export `DiffOptionsColor` type so `jest-snapshot` can declare `getSnapshotColor` and `getReceivedColor` with conditional expression of …
> jest-diff: Rename some new options and change their default values

- .circleci/config.yml
Node 13 is out, so let's test on it. (I haven't ran this locally 🤞).
~Also move typecheck, website and circus from node 10 to 12, as 12 is now LTS~ moved to (and merged from) #9100
Green CI
> chore: test on node 13

- e2e/__tests__/jestChangedFiles.test.ts
- package.json
- yarn.lock
To unblock https://github.com/nodejs/citgm/pull/728 and https://github.com/facebook/jest/pull/9101
Green CI
> chore: skip hg tests if mercurial is not installed

- CHANGELOG.md
- packages/jest-config/src/__tests__/getMaxWorkers.test.ts
- packages/jest-config/src/getMaxWorkers.ts
Fixes #9116
Added a new condition in the `Returns based on the number of cpus` test of the `packages/jest-config/src/__tests__/getMaxWorkers.test.ts` file
> Use half of the available cores when in watchAll mode

- examples/react/CheckboxWithLabel.js
- examples/react/__tests__/CheckboxWithLabel-test.js
As mentioned in #9043 usage of `findDomeNode()` is deprecated and have rule against its usage in ESLint. This PR Closes #9043 by removing `findDomeNode()` usage in the example and replaces it with `createRef()`.  
Since the test required accessing two different DOM nodes (`label` and `input`), ref forwarding is used for both of them
`yarn test`
> refactor: Replaces findDomNode() with refs

- CHANGELOG.md
- e2e/__tests__/toMatchSnapshot.test.ts
- packages/jest-snapshot/src/State.ts
- packages/jest-snapshot/src/__tests__/__snapshots__/printSnapshot.test.ts.snap
- packages/jest-snapshot/src/__tests__/printSnapshot.test.ts
- packages/jest-snapshot/src/__tests__/utils.test.ts
- packages/jest-snapshot/src/index.ts
- packages/jest-snapshot/src/printSnapshot.ts
- packages/jest-snapshot/src/utils.ts
Borrow some features from `toMatchObject` for reports when snapshot matchers fail:
1. Throw `Matcher error: received value must be an object when the matcher has properties` instead of
* ordinary test failure
* **BREAKING**: test success if received is a **string** see #8059
2. In an ordinary test failure because received object does not match properties, display comparison lines if `isLineDiffable`
A similarity with `toMatchObject` that I did **not** include is `getObjectSubset` because:
* it has known limitations
* it is not a public interface
* the long-term goal is to replace it with data-driven diff
Refactor for clearer distinction between snapshot and generic serialization:
* call `addExtraLineBreaks` in `State.ts` for symmetry with `removeExtraLineBreaks`
* change `serialize` not …
> jest-snapshot: Improve report when the matcher has properties

- CHANGELOG.md
- CONTRIBUTING.md
It now seems that Flow Type is no longer the default option. #7554
N/A
> docs: replace FlowType with Typescript in CONTRIBUTING.MD code conventions

- CHANGELOG.md
- packages/jest-environment-node/src/index.ts
Fix https://github.com/facebook/jest/issues/9139
> jest-environment-node: Add queueMicrotask

- docs/ExpectAPI.md
- website/versioned_docs/version-24.0/ExpectAPI.md
- website/versioned_docs/version-24.8/ExpectAPI.md
When reading expect API docs, I was confused about the usage of `isNot` in custom matchers. The original docs says that it allows to "flip your assertions", but in fact it's only used to display correct hint.
In the example, I think it'd be also helpful to show how `isNot` can be used when prefixing the "Expected" value.
N/A
> Clarify usage of isNot in docs

- CHANGELOG.md
- packages/jest-transform/src/ScriptTransformer.ts
- packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap
- packages/jest-transform/src/__tests__/script_transformer.test.js
Fixes #8966.
This prevents rare, non-deterministic errors of the following type (further described in #8966):
```
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at new Converter (../../node_modules/convert-source-map/index.js:50:48)
at Object.exports.fromComment (../../node_modules/convert-source-map/index.js:106:10)
at Object.exports.fromSource (../../node_modules/convert-source-map/index.js:116:22)
at ScriptTransformer.transformSource (../../node_modules/@jest/transform/build/ScriptTransformer.js:468:61)
at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:524:40)
at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:568:25)
```
The change treats cases in which the …
> Don't fail the test suite when convert-source-map throws an error

- CHANGELOG.md
- packages/jest-diff/README.md
- packages/jest-diff/src/__tests__/diff.test.ts
- packages/jest-diff/src/diffLines.ts
- packages/jest-diff/src/index.ts
- packages/jest-diff/src/printDiffs.ts
- packages/jest-snapshot/src/printSnapshot.ts
Let callers of `diffLinesUnified` and `diffLinesUnified2` use `split` method, because it is a private implementation issue that `''.split('\n')` is `['']` instead of `[]`
But callers of `diffLinesRaw` must decide whether `['']` or `[]` has correct meaning for their applications
In `README.md` file, move information:
* from `Edge cases of diffLinesUnified or diffStringsUnified`
* to `Edge case of diffLinesRaw`
This is not a breaking change, because the export was never published
In `diff.tests.ts`
* Added 8 tests to `diff.test.ts` to cover new conditions
* Added 2 tests to close previous gap in code coverage
* Edited 1 describe to replace obsolete `firstOrLastEmptyLineReplacement` with `emptyFirstOrLastLinePlaceholder default empty string`
> jest-diff: Remove the need to export splitLines0 function

- CHANGELOG.md
- website/versioned_docs/version-24.9/Webpack.md
`transform` link on `Using with webpack` (https://jestjs.io/docs/en/webpack) is broken. So, it does not lead to configuration's transform section (https://jestjs.io/docs/en/configuration#transform-object-string-pathtotransformer-pathtotransformer-object).
> docs: Fix broken transform link on webpack page

- docs/TutorialReact.md
- examples/react-testing-library/__tests__/CheckboxWithLabel-test.js
```react-testing-library``` automatically runs ```cleanup``` unless otherwise specified (https://github.com/testing-library/react-testing-library/pull/430). The change takes place in ```@testing-library/react@9.0.0``` (https://github.com/testing-library/react-testing-library/releases/tag/v9.0.0) and later.
I found the documentation to be contradictory as to whether ```afterEach(cleanup)``` should be called, and so hopefully this comment clarifies it for future users.
This is just adding a comment, so I do not believe any test plan is necessary.
> docs: add comment about 'cleanup' in react-testing-library example

- e2e/__tests__/detectOpenHandles.ts
- e2e/runJest.ts
Extracted from #7347 as I think it's a great idea, and makes rebasing that branch way easier if it goes in separately.
/cc @rubennorte 
Green CI
> chore: replace `until` test helper with a `continuous`

- package.json
- packages/jest-circus/src/utils.ts
- yarn.lock
3.7 is out 🎉 I haven't actually tried to run this, just opening up a PR 😀 
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/
Green CI?
> chore: bump TS to 3.7

- CHANGELOG.md
- packages/jest-reporters/src/base_reporter.ts
If people extend the class they won't have to pass the arguments to please TS
Green CI
> chore: make arguments to methods in base reporter optional

- CHANGELOG.md
- packages/jest-reporters/src/index.ts
They can be useful in custom reporters
Green CI, just exporting more stuff that already exists
> feat(reporters): export utils for path formatting

- CHANGELOG.md
- docs/Configuration.md
- e2e/__tests__/__snapshots__/customReporters.test.ts.snap
- e2e/__tests__/customReporters.test.ts
- e2e/custom-reporters/reporters/DefaultExportReporter.js
- packages/jest-config/src/normalize.ts
- packages/jest-core/src/TestScheduler.ts
Way nicer if the reporter is transpiled
Green CI
> feat: allow reporters to be default exports

- packages/jest-circus/src/formatNodeAssertErrors.ts
Removed `switch` with only one `case`(replaced by `if`).
> jest-circus: remove switch with single case

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers-toContain.property.test.ts
- packages/expect/src/__tests__/matchers-toContainEqual.property.test.ts
- packages/expect/src/__tests__/matchers-toEqual.property.test.ts
- packages/expect/src/__tests__/matchers-toStrictEqual.property.test.ts
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/jasmineUtils.ts
Builds on the awesome work of @dubzzz by adding a test that our `expect.toStrictEqual` is equivalent to Node's `assert.deepStrictEqual`. Even though I disagree with the behavior of `deepStrictEqual` [in some situations](https://github.com/facebook/jest/pull/7730), I think these are not too important and aligning with other equality implementations `deepStrictEqual` is more important. @SimenB @pedrottimark do you agree?
Running this a couple of times uncovered one mismatch:
Node (this btw means `fast-deep-equal` afaik) considers a primitive different from a `new Primitive()` (while it is of course equal to a `Primitive()` without `new`). This makes sense to me (they do not even have the same `typeof`!), and fwiw I tried `concordance` (=> AVA) and it agrees with Node.
I fixed this, which is …
> property-based test for Node `deepStrictEqual` equivalence

- jest.config.ci.js
A breaking change in `jest-junit` 8.0.0 (https://github.com/jest-community/jest-junit/pull/101) caused test results to no longer appear for the facebook/jest CI pipeline in Azure Pipelines:
[Example run](https://dev.azure.com/jestjs/jest/_build/results?buildId=3792&view=ms.vss-test-web.build-test-results-tab)
The jest-junit reporter is used in facebook/jest CI runs to produce XML Junit files which feed the Tests UX in Azure Pipelines. 
The breaking change replaced the `output` configuration option (used in `jest.config.ci.js`) with separate `outputDirectory` and `outputName` options. Moving to jest-junit 9.0.0 (#9114) caused the problem to surface.
With this fix, test results are now appearing again in Azure Pipelines:
> Fix missing test results for facebook/jest CI runs in Azure Pipelines

- CHANGELOG.md
- packages/jest-fake-timers/package.json
- packages/pretty-format/package.json
- packages/pretty-format/src/plugins/ReactElement.ts
- yarn.lock
Handles the change in https://github.com/facebook/react/pull/17278
Green CI
> fix(pretty-format): correctly detect memo

- e2e/__tests__/__snapshots__/showConfig.test.ts.snap
- packages/jest-config/src/normalize.ts
- packages/jest-runtime/src/__tests__/instrumentation.test.ts
- packages/jest-runtime/src/index.ts
- packages/jest-transform/src/__tests__/script_transformer.test.js
- packages/jest-transform/src/__tests__/should_instrument.test.ts
- packages/jest-transform/src/shouldInstrument.ts
- packages/jest-transform/src/types.ts
> chore: make changedFiles option optional in `shouldInstrument`

- CHANGELOG.md
- packages/jest-snapshot/src/__tests__/__snapshots__/printSnapshot.test.ts.snap
- packages/jest-snapshot/src/__tests__/printSnapshot.test.ts
- packages/jest-snapshot/src/printSnapshot.ts
Call `getObjectSubset` to be consistent with `toMatchObject`
* a subset helps if a property is **missing or obsolete** however, there are bogus changes for the properties that match
* although a subset hides the problem if there is a **change to a key** of a property, a minified serialization or even complete line diff of `Expected properties` versus `Received value` can also hide the problem in a mess of irrelevant details
Because the long-term solution is data-driven diff, please forgive a temporary hack to import `getObjectSubset` which is a private helper function of the `expect` package
Simen, when I wrote `'expect/src/utils'` the package tests ran okay, but the example test outside Jest threw an error, so is this correct instead:
```js
import {getObjectSubset} from …
```
> jest-snapshot: Omit irrelevant received properties when property matchers fail

- CHANGELOG.md
- packages/jest-snapshot/src/__tests__/__snapshots__/printSnapshot.test.ts.snap
- packages/jest-snapshot/src/__tests__/dedentLines.test.ts
- packages/jest-snapshot/src/__tests__/printSnapshot.test.ts
- packages/jest-snapshot/src/dedentLines.ts
- packages/jest-snapshot/src/printSnapshot.ts
- packages/jest-snapshot/src/utils.ts
Fixes #8626
Call `diffLinesUnified2` to compare without indentation:
* add optional `indent` arg to serialize received without indentation
* call `dedentLines` heuristic to remove indentation from snapshot
Fall back to baseline `diffLinesUnified` in edge case of multi-line strings:
* text node child of markup element
* key or value of object property
* item of array
* added 17 tests to new `dedent.test.ts`
* added 5 snapshots to `printSnapshot.test.ts` (although my eyes have already adjusted to magenta and teal in console, `<m>` and `<t>` in snapshots will take a while longer)
See also pictures in following comment
Example pictures **baseline** at left and **improved** at right
> jest-snapshot: Ignore indentation for most serialized objects

- docs/JestPlatform.md
- website/versioned_docs/version-22.x/JestPlatform.md
- website/versioned_docs/version-24.0/JestPlatform.md
Fix incorrect "where" => "were". It is already in another [pull request](https://github.com/facebook/jest/pull/9122) where are requested updates in versioned docs. But it was more than 2 weeks ago, so here are also those changes done.
> Fix typo in JestPlatform.md

- docs/TutorialAsync.md
Hi. 
a few days ago, i registered issue #9143 
please, read that issue.
i suggest how about removing expect.assertions(1); code in rejects example of TutorialAsync.md
becauese i was not sure whether I should used assertions.
thank u.
> docs: remove expect.assertions(1) in rejects example of TutorialAsync.md

- CHANGELOG.md
- packages/jest-haste-map/package.json
- packages/jest-haste-map/src/lib/FSEventsWatcher.ts
- yarn.lock
Fixes #9191.
I tested this on my own mac (with `--no-watchman`) - seemed to work out great 🙂
> chore: upgrade to fsevents 2

- .circleci/config.yml
- .github/workflows/nodejs.yml
- packages/jest-transform/src/ScriptTransformer.ts
- scripts/buildTs.js
They have built in "problem matchers" that should report eslint and tsc errors - I wonder if that's cleaner than having it on circle?
Docs: https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md
EDIT: Hmm, I was hoping it'd comment inlined
EDIT2: Hmmmmm, it did at least find the file for eslint, which is awesome
Might be due to our output
EDIT3: Yup, that was it
I'll add a type error and lint error and see what it output
> chore: run tsc and linting as GH action

- docs/TutorialReactNative.md
- website/versioned_docs/version-22.x/TutorialReactNative.md
- website/versioned_docs/version-24.0/TutorialReactNative.md
The old domain `callstack.io` redirects to broken links. The new URLs seem to link to identical blog entries.
-
> docs: tutorial links updated

- CHANGELOG.md
- e2e/__tests__/multiProjectRunner.test.ts
- packages/jest-config/src/index.ts
This PR adds a failing test case for #8860 ~~but I haven't had any clue on how to fix it~~ and I found a way to solve it, but I actually wonder if this is the best way to fix this. I guess I need input from the maintainers.
There are failing tests when I do the following change
```diff
-  if (
-    projects.length > 1 ||
-    (projects.length && typeof projects[0] === 'object')
-  ) {
+  if (projects.length > 0) {
```
The main issue was that at `readConfigs`, when calling `readConfig`, `skipArgvConfigOption` should only be `true` if the project is not "global". By global, I mean, it is not added from `getProjectListFromCLIArgs` using `process.cwd`. That's why I changed `getProjectListFromCLIArgs` to also return `isGlobalProject`.
Update: the implementation have changed based on suggestion …
> fix: Jest multi project runner still cannot handle exactly one project

- CHANGELOG.md
- packages/jest-transform/src/ScriptTransformer.ts
- packages/jest-transform/src/index.ts
This is a breaking out of [`buildDefaultResolverRequire`](https://github.com/facebook/jest/pull/8829/files#diff-79e46c9e92027daadc4fc85b7b71ae2dR27-R32) from #8829 as [requested](https://github.com/facebook/jest/pull/8829#issuecomment-522338238)
@SimenB I've not written tests or add an entry in the changelog as it seemed like a bit of overkill for something that is going to be used in future PRs.
I did a sweep of the codebase, and the only place this could actually be used right now is in `jest-core`, but that'd require implementing support for the callback parameters 🤷‍♀
It'll be nice to trim down the transformer PRs a bit :)
> feat: add `buildDefaultResolverRequire`

- package.json
- scripts/buildUtils.js
- scripts/watch.js
- yarn.lock
The current script picks up dotfile, so I just migrated to chokidar, which had a nice `ignore dotfiles` regex in its readme 😀 Can probably simplify by providing a single glob instead of array if dirs, but meh. We theoretically avoid a bunch of separate `fs.watch` which is better anyways
I also fixed the delete script, which has been broken since we started using `.ts` files 😬 
Added, renamed, changed and deleted files locally, it behaved nicely
> chore: use chokidar for watch script

- .eslintrc.js
- yarn.lock
@SimenB remember this one isn't enabled by the `recommended`. I've done this via github, so will see what fails in the CI and then maybe fix 🤷‍♂ 
Run the CI, and see what fails.
> chore(lint): enable `eslint-comments/no-unused-disable`

- packages/babel-jest/src/__tests__/index.ts
- packages/jest-core/src/__tests__/TestScheduler.test.js
- packages/jest-snapshot/src/__tests__/snapshot_resolver.test.ts
Some tests don't use `makeProjectConfig`, using `as Config.ProjectConfig` instead 😱
This is brittle as it means the tests can fail if the configuration changes. 
This changes that, so that all `as Config.ProjectConfig` usage in tests are replaced w/ `makeProjectConfig` to ensure the configurations have the correct default values.
Run the tests, check the CI output, then have a 🍺 when it's green.
> chore: use `makeProjectConfig` in tests

- TestUtils.ts
- e2e/__tests__/__snapshots__/showConfig.test.ts.snap
- packages/jest-config/src/index.ts
- packages/jest-core/src/lib/__tests__/__snapshots__/log_debug_messages.test.ts.snap
- packages/jest-transform/src/types.ts
- packages/jest-types/src/Config.ts
It's currently on both `ProjectConfig` and `GlobalConfig` - the correct one is `ProjectConfig`
Green CI
> chore: remove extraGlobals from GlobalConfig

- packages/jest-transform/package.json
- packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap
- packages/jest-transform/src/__tests__/script_transformer.test.js
While working on #9253 I found it very difficult to read the snapshots. Which also means changes to them are hard to read, so I decided to land this separately. It does this by using `dedent` to avoid the extra indentation and `jest-serializer-raw` to avoid the wrapping double quotes and escaped inner double quotes
Green CI
> chore: make script transform snapshots more readable

- CHANGELOG.md
- packages/jest-runtime/src/index.ts
> chore: do not export `ScriptTransformer`

- CHANGELOG.md
- packages/jest-environment/package.json
- packages/jest-environment/src/index.ts
- packages/jest-environment/tsconfig.json
- packages/jest-runtime/src/__tests__/__snapshots__/runtime_wrap.js.snap
- packages/jest-runtime/src/__tests__/instrumentation.test.ts
- packages/jest-runtime/src/__tests__/runtime_require_module.test.js
- packages/jest-runtime/src/__tests__/runtime_wrap.js
- packages/jest-runtime/src/index.ts
- packages/jest-transform/src/ScriptTransformer.ts
- packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap
- packages/jest-transform/src/__tests__/script_transformer.test.js
- packages/jest-transform/src/enhanceUnexpectedTokenMessage.ts
- packages/jest-transform/src/index.ts
- packages/jest-transform/src/types.ts
Extracted from #9252. Since `jest-runtime` is the one injecting arguments into the module wrapper, it should also say _which_ arguments those are. This makes `@jest/transform` less coupled to the module wrapper, and thus to Jest's use case. It's marked as a breaking change since it changes `@jest/transform`'s interface, but it's not a breaking change for users of Jest.
Added some tests
> feat: return transformed code as a string, do not wrap in `vm.Script`

- .vscode/settings.json
- CHANGELOG.md
- packages/jest-core/src/cli/index.ts
- packages/jest-runtime/src/cli/index.ts
- packages/jest-worker/README.md
Partially addresses https://github.com/facebook/jest/issues/9236.
When creating haste contexts and maps, Jest currently spawns `maxWorkers` per "project". While it doesn't make a difference in a single-project workspace, it's a big deal for those using multiple projects. 
A quick-and-dirty-but-works solution is to limit the number of workers based on the projects number. It's sub-optimal, because we may have smaller and larger projects which we assign the same number of workers. However a proper solution would require more work. E.g. we could delegate `createHasteMap` of each project to a worker pool created in `jest-core`, instead of deferring parallelization to `createHasteMap` itself. Feel free to implement this solution. However, I'm not pursuing this, as @scotthovestadt has likely …
> fix: limit number of workers when creating haste maps in projects

- CHANGELOG.md
- e2e/__tests__/__snapshots__/failures.test.ts.snap
- e2e/failures/__tests__/assertionError.test.js
- packages/jest-circus/src/formatNodeAssertErrors.ts
- packages/jest-jasmine2/src/assertionErrorMessage.ts
This PR fixes incorrect error message format when using Node's `assert.fail`.
Currently when using `assert.fail` in a test, We get a message that includes two parts that should be omitted:
- Expected/Received with `undefined`s
- An empty "Difference".
This was fixed by updating the node assert message helpers in both of `jest-jasmine2` and `jest-circus` to account for the `fail` operator.
**Before**
```
✕ does not print expected/received message for assert.fail (1ms)
● does not print expected/received message for assert.fail
assert.fail(received, expected)
Expected value fail to:
undefined
Received:
undefined
Message:
nooooooo
Difference:
Compared values have no visual difference.
2 | 
3 | it('does not print expected/received message for assert.fail', () => {
> 4 | …
```
> Improve error message format for Node's assert.fail

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/jest-environment-node/src/__tests__/node_environment.test.ts
- packages/jest-environment-node/src/index.ts
Fixes #9204 
This is a follow up for my comment: https://github.com/facebook/jest/issues/9204#issuecomment-561438263
Currently the following tests are failing in Jest:
- **Using global TextEncoder (node v11 and above)**
```js
it('TextEncoder.encode references the same global Uint8Array constructor', () => {
const actual = new TextEncoder().encode('foo');
expect(actual).toEqual(new Uint8Array([102, 111, 111])); // fails
expect(actual).toBeInstanceOf(Uint8Array); // fails
});
```
- **Importing TextEncoder from the 'util' module (not using global TextEncoder)**
```js
const {TextEncoder} = require('util');
it('TextEncoder.encode references the same global Uint8Array constructor', () => {
const actual = new TextEncoder().encode('foo');
expect(actual).toEqual(new Uint8Array([102, 111, 111])); …
```
> Fix TextEncoder.encode not referencing same global Uint8Array constructor

- CHANGELOG.md
- docs/ExpectAPI.md
- e2e/__tests__/__snapshots__/toMatchInlineSnapshot.test.ts.snap
- e2e/__tests__/toMatchInlineSnapshot.test.ts
- packages/expect/src/externalMatcherMark.ts
- packages/expect/src/index.ts
- packages/jest-snapshot/src/State.ts
- packages/jest-snapshot/src/__tests__/utils.test.ts
- packages/jest-snapshot/src/inline_snapshots.ts
- packages/jest-snapshot/src/utils.ts
Fix #8181.
Supports custom inline snapshot matchers, currently using them isn't possible.
```js
const { toMatchInlineSnapshot } = require("jest-snapshot");
expect.extend({
toMatchCustomInlineSnapshot(received, ...args) {
return toMatchInlineSnapshot.call(this, received, ...args);
}
});
test("inline snapshots", () => {
expect({ apple: "original value" }).toMatchCustomInlineSnapshot();
// Will inject snapshot to
expect({ apple: "original value" }).toMatchCustomInlineSnapshot(`
Object {
"apple": "original value",
}
`);
});
```
The implementation is a bit of a hack, I'm not sure if it's suitable for production but it's the only better way I can think of for now.
<details>
<summary>To summarize the issue to those who is not familiar with how inline snapshots works, here is a simplified …
> Support custom inline snapshot matchers

- packages/jest-worker/README.md
https://github.com/facebook/jest/pull/8596#discussion_r355214239
> docs: give recommendation on jest-worker end() Promises

- CHANGELOG.md
- packages/expect/src/__tests__/utils.test.js
- packages/expect/src/utils.ts
This fixes https://github.com/facebook/jest/issues/9089
This bug is introduced by this PR https://github.com/facebook/jest/pull/8687
So basically, there is a flaw on the circular reference logic within a function called `subsetEquality`.
The logic is that, to avoid circular reference, it stores the references of nodes that it has been through within one singleton variable `seenReferences`. Whenever we have seen the same node (using the reference), we skip the subset equality checking (which is done recursively) and do deep equality checking instead.
The implication is that nodes within the same level of tree will use the same reference `seenReferences`. It's a problem because then it will cause an invalid handling on this case :
```
const referencedObj = {abc: 'def'};
const object = {
a: …
```
> Fix subsetEquality: same referenced object on same level node of tree is regarded as circular reference

- docs/Configuration.md
- website/versioned_docs/version-22.x/Configuration.md
- website/versioned_docs/version-23.x/Configuration.md
- website/versioned_docs/version-24.0/Configuration.md
- website/versioned_docs/version-24.1/Configuration.md
- website/versioned_docs/version-24.6/Configuration.md
- website/versioned_docs/version-24.8/Configuration.md
- website/versioned_docs/version-24.9/Configuration.md
Add helpful link to the custom transformer guide in the 'transform' configuration description. 
It makes it easier to get started if individuals are looking for that.
Documentation change only. No testing required.
> Add helpful link to custom transformer in the 'transform' config option

- examples/mongodb/package.json
- examples/react-native/package.json
- yarn.lock
Fixes dependencies of mongodb and react-native examples.
```
cd examples/mongodb
npm install
npm test
```
```
cd examples/react-native
npm install
npm test
```
> chore: fix examples dependencies

- docs/ManualMocks.md
- website/versioned_docs/version-23.x/ManualMocks.md
Direct assignments to `window` properties fails silently if they are not
writable, so `Object.defineProperty()` should be used when stubbing
global properties.
Closes #9287
#9287
This is a documentation-only change.
> docs: Use `Object.defineProperty()` for stubbing global properties

- packages/jest-config/package.json
- packages/jest-core/package.json
- packages/jest-haste-map/package.json
- packages/jest-message-util/package.json
- packages/jest-transform/package.json
- yarn.lock
`micromatchv4.+` has breaking changes. This update should help avoid runtime errors.
Green CI
> chore: bump @types/micromatch to ^4.0.0

- CHANGELOG.md
- packages/jest-reporters/src/__tests__/coverage_reporter.test.js
- packages/jest-reporters/src/__tests__/get_watermarks.test.js
- packages/jest-reporters/src/__tests__/get_watermarks.test.ts
- packages/jest-reporters/src/coverage_reporter.ts
- packages/jest-reporters/src/get_watermarks.ts
When Istanbul generates the some reports (like html & lcov) it uses watermarks to to provide visual feedback with colors. The default watermarks are 50% and 80%. Which in the html reports means that coverage under 50% is red and coverage over 80% is green. But we have a coverage threshold of 100%, so using the report to find any file with coverage between 80% and 100% can be quite difficult as @nemoDreamer describes here: [#6578](https://github.com/facebook/jest/issues/6578). 
My solution is to provide istanbul with watermarks where the high watermarks are set to the global coverage threshold of each coverage category (branches, functions, lines, and statements)
I added unit tests for my use case and for not having any global coverage threshold and tested my changes using `yarn link`
> jest-reporters: Use global coverage thresholds as high watermarks

- CHANGELOG.md
- packages/jest-snapshot/src/printSnapshot.ts
Found by @SimenB in a diff for `e2e/__tests__/__snapshots__/showConfig.test.ts.snap`
Ouch, I assumed that all snapshot serializers support the `indent` option.
But `jest-snapshot-serializer-raw` does not, because it deals with strings.
Because the snapshot is JSON serialization of an object, it can be dedented.
Therefore, the expected value has no indentation and the received value has default indentation. Only the opening and closing braces are in common.
As a future chore, add a minimal serializer to `test-utils` which does not use the object-with-symbol-key-idiom, for tests that do not need to distinguish top-level strings from lower-level strings (for example, array items, object keys or values). That will support substring diffs for Jest test files that serialize only strings (like …
> jest-snapshot: Fix regression in diff for jest-snapshot-serializer-raw

- CHANGELOG.md
- e2e/__tests__/findRelatedFiles.test.ts
- packages/jest-core/src/SearchSource.ts
Hey, there is a fix for #8900 however I'm not sure this is the right place to normalize non flag arguments. 
I've made a few runs with "wrong" cased path on my machine. For `packages\jest-core\src\FailedTestsCache.ts` file I've run `jest --findRelatedTests  packages/jest-core/SRC/FailedTestsCache.ts` and that works well.
In addition I'll cover it with some test, just before do that I'm interested in your opinion about a correct place for paths normalization.
> Normalize --findRelatedTests paths on win32 platforms

- CHANGELOG.md
- packages/pretty-format/src/__tests__/ReactElement.test.ts
- packages/pretty-format/src/plugins/ReactElement.ts
Unlike React DevTools, Jest ignores a custom displayName set on forwardRef components. We should align serialization with DevTools, so change the behavior.
Created a new unit test to cover the changes.
CC @scotthovestadt @bvaughn
> Fix pretty-format to respect displayName on forwardRef.

- CHANGELOG.md
- package.json
- packages/jest-snapshot/package.json
- yarn.lock
Downgrades the semver dependency in `jest-snapshot` to a version that supports node 8.
Fixes #9450 
N/A
> chore: downgrade jest-snapshot#semver to v6 to support node 8

- docs/Configuration.md
- website/versioned_docs/version-25.1/Configuration.md
The `testTimeout` configuration option was documented in the CLI docs but not the configuration docs so I wasn't completely sure if it was available to use in my package.json configuration, so I needed to try it and also dig into the jest source code to confirm. This simply documents the option in the config docs as well.
Fixes #9448
> Document testTimeout configuration option

- CHANGELOG.md
- packages/jest-reporters/package.json
- packages/jest-reporters/src/types.ts
- packages/jest-reporters/tsconfig.json
Noticed when I was messing with the reporters. Technically breaking for TS users if they import these types, but meh. They should import `TestFramework` from https://github.com/facebook/jest/blob/eee81208163d2b64171a6b7eec13a8a1aebfc901/packages/jest-runner/src/types.ts#L40-L46
Green CI
> chore: remove unused deps from @jest/reporters

- CHANGELOG.md
- packages/jest-transform/src/ScriptTransformer.ts
- packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap
- packages/jest-transform/src/__tests__/script_transformer.test.js
This change change generates inline and separate file source maps for the instrumented code produced when Jest runs with `--coverage` in the case that the code has been transformed. 
While coverage reporting appears to function correctly in this case prior to this PR, debugging code under test did not work as expected, nor did stack traces emitted by errors in code under test.
Fixes #5739
I primarily tested this by running Jest against a small test project (https://github.com/mbpreble/jest-test)
Running my local Jest branch against the project produces the expected coverage output and stack trace for the thrown error in the test code. I am also able to debug Jest using the Node debugger and hit break points in my test code:
```
FAIL  ../test-project/src/app.test.ts
hello world
✕ should …
```
> Produce source maps when instrumenting code

- CHANGELOG.md
- docs/Configuration.md
- website/versioned_docs/version-25.1/CLI.md
fixes #9452
Fixes the issue #9452 by informing the user of the unexpected behavior of node-notifier when using ```--notify``` CLI param or the ```notify``` config option.
Green CI. Just a documentation change.
> docs: Warn about node-notifier caveat on windows systems.

- docs/TestingAsyncCode.md
- website/versioned_docs/version-22.x/TestingAsyncCode.md
- website/versioned_docs/version-24.x/TestingAsyncCode.md
The callback code sample was too simple leaving beginners them with the test which provides only useless timeout error in the log instead of received value causing fail if the test.
Improved callback code sample with the done parameter so beginners do not end up with opaque timeout error.  Added try-catch block and error handling in case expect matcher fails. Added explanation if importance to wrap expect in try statement in this scenario, what happens if the test fails and done() is not called.
No test needed. Changes only to the text of documentation.
> docs: clarify error handling when using test callbacks

- .github/ISSUE_TEMPLATE/bug.md
The output of envinfo is not executable bash script, so the highlighting won't do what was probably expected by the author. This PR removes highlighting.
before:
```bash
$ npx envinfo --preset jest
npx: installed 1 in 1.775s
System:
OS: macOS 10.15.2
CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
Binaries:
Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
Yarn: 1.21.1 - /usr/local/bin/yarn
npm: 6.13.6 - ~/.nvm/versions/node/v10.18.0/bin/npm
npmPackages:
jest: ^25.1.0 => 25.1.0
```
after:
```
$ npx envinfo --preset jest
npx: installed 1 in 1.775s
System:
OS: macOS 10.15.2
CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
Binaries:
Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
Yarn: 1.21.1 - /usr/local/bin/yarn
npm: 6.13.6 - ~/.nvm/versions/node/v10.18.0/bin/npm …
```
> Remove bash syntax highlighting from GitHub issue template

- .github/ISSUE_TEMPLATE/regression.md
Same as #9474 but for the regression template.
Sorry, should've done both in one PR.
> Remove bash syntax highlighting from GitHub issue template (regression)

- CHANGELOG.md
- packages/pretty-format/src/index.ts
- packages/pretty-format/src/types.ts
Otherwise, people cannot specify that the `print` function is of the correct shape, as just `Plugin` can refer to both
Not much... :P It _works_
> fix: export `OldPlugin` from pretty-format

- CHANGELOG.md
- docs/Configuration.md
- docs/TutorialReactNative.md
- e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
- e2e/__tests__/moduleNameMapper.test.ts
- e2e/module-name-mapper-correct-config/package.json
- e2e/module-name-mapper-wrong-array-config/__tests__/index.js
- e2e/module-name-mapper-wrong-array-config/index.js
- e2e/module-name-mapper-wrong-array-config/package.json
- packages/jest-cli/src/cli/args.ts
- packages/jest-cli/src/init/__tests__/__snapshots__/init.test.js.snap
- packages/jest-config/src/Descriptions.ts
- packages/jest-config/src/__tests__/setFromArgv.test.ts
- packages/jest-resolve/src/index.ts
- packages/jest-resolve/src/types.ts
- packages/jest-types/src/Config.ts
- packages/jest-validate/src/__tests__/fixtures/jestConfig.ts
Fixes #8461 
I've added test cases let me know if I should add more.
I have not updated CHANGELOG.md eventhough PR template suggests it, not sure if I should do it or it's autodone
> Support array of paths for `moduleNameMapper` aliases

- CHANGELOG.md
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/normalize.ts
The value of `setupFiles` from a local Jest config is concatenated to the value of `setupFiles` from a preset when the local Jest config specifies `preset` and `setupFiles`. The same should be true for `setupFilesAfterEnv`. Without this change, if the local Jest config wants to take advantage of the `setupFilesAfterEnv` files from the preset, it has to redeclare them:
```js
// jest-preset-foo
setupFilesAfterEnv: ['a'],
};
// local jest.config.js
preset: 'jest-preset-foo',
setupFilesAfterEnv: ['b'],
};
```
Before:
Value of `setupFilesAfterEnv` = `['b']`
After:
Value of `setupFilesAfterEnv` = `['a', 'b']`
> Treat setupFilesAfterEnv like setupFiles when normalizing configs against presets

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/jest-matcher-utils/src/Replaceable.ts
- packages/jest-matcher-utils/src/__tests__/Replaceable.test.ts
- packages/jest-matcher-utils/src/__tests__/__snapshots__/printDiffOrStringify.test.ts.snap
- packages/jest-matcher-utils/src/__tests__/printDiffOrStringify.test.ts
Fixes #9432.
Use `Object.getOwnPropertySymbols` to traverse object's symbol key can fix this issue.
Thanks @pedrottimark to point out this edge case.
Add  symbol-keyed object tests.
> Fix diff highlight of symbol-keyed object.

- docs/Configuration.md
Sorry for this, it was left from my previous PR. Thank you!
> Fix typo in moduleNameMapper docs

- CHANGELOG.md
- packages/jest-haste-map/src/crawlers/__tests__/node.test.js
- packages/jest-haste-map/src/crawlers/node.ts
`fs.readdir` has a withFileTypes option that will tell us if the file is a symlink or directory. Therefore, there's no need to make and wait for an lstat call before taking the appropriate actions for those file types (skip and recurse, respectively). 
This drastically improves the initial crawl time when using the node watcher.
Applied changes and ran it against my project. The activeCalls counter is a little tricky, but I'm fairly certain I've handled it correctly here since I'd expect an infinite loop if I got it wrong.
> [jest-haste-map] reduce the number of lstat calls in node crawler

- CHANGELOG.md
- packages/jest-resolve/package.json
- packages/jest-resolve/src/__mocks__/userResolver.js
- packages/jest-resolve/src/__tests__/resolve.test.ts
- packages/jest-resolve/src/defaultResolver.ts
- yarn.lock
Ref https://github.com/facebook/jest/issues/2925#issuecomment-582344445 (and #9505).
This keeps the optimizations from #8388 by passing the cached `isFile` and `isDirectory` to `resolve`. We can also implement `readFile` backed by HasteFS (like #2925 talks about) in the future.
Green CI. I've kept all of our tests, so hopefully we're sufficiently covered
> feat: use `resolve` package in `jest-resolve`

- CHANGELOG.md
- e2e/__tests__/__snapshots__/toMatchInlineSnapshot.test.ts.snap
- e2e/__tests__/toMatchInlineSnapshot.test.ts
- package.json
- packages/jest-snapshot/src/inline_snapshots.ts
Fixes #9477 
I've added a new test 🌮
> Fix inline snapshot indenting

- CHANGELOG.md
- packages/jest-resolve/package.json
- packages/jest-resolve/src/__mocks__/foo/foo.js
- packages/jest-resolve/src/__tests__/resolve.test.ts
- packages/jest-resolve/src/defaultResolver.ts
- yarn.lock
Fixes #8910
This might be an inherited bug from `resolve`: https://github.com/browserify/resolve/blob/bd3f55188f0f3d1dac1e29c2f9a0eaa0878d4bd0/lib/sync.js#L69 which this code came from in #4315.
EDIT: No, seems like `resolve` works correctly
Test added
> fix(jest-resolve): don't confuse directories with files

- .github/workflows/nodejs.yml
No idea if this'll work 🤷‍♀ I created this through GH's UI, so hopefully that means actions are enabled
Green CI?
> chore: add GH Actions CI

- CHANGELOG.md
- packages/jest-runtime/src/__tests__/runtime_require_module_or_mock.test.js
- packages/jest-runtime/src/index.ts
> fix: Reset isolateModules after failing

- docs/Configuration.md
- website/versioned_docs/version-22.x/Configuration.md
- website/versioned_docs/version-23.x/Configuration.md
- website/versioned_docs/version-24.x/Configuration.md
- website/versioned_docs/version-25.1/Configuration.md
Commit 3749160188889142c2b904372f9b529e2180d3fb (v20.0.0~79, #3346) added the `globalConfig` parameter without updating this documentation.
> docs/Configuration: Correct signature for testRunner

- CHANGELOG.md
- packages/jest-config/src/importMjs.ts
Fixes #9544.
I've tested this on windows. We have an integration test for this, but we only run windows CI with node v12...
> fix: use file urls when calling `import()`

- CHANGELOG.md
- packages/jest-cli/src/cli/args.ts
Fixed #9561
We default in `normalize` and since argv overwrites config from file the default from argv always won. Now we'll default from `Defaults` instead - so still `babel` by default out of `normalize`, but now possible to set `coverageProvider` in config
Verified manually 😅
> fix: do not default coverageProvider in yargs

- CHANGELOG.md
- e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
- packages/jest-resolve/src/__tests__/resolve.test.ts
- packages/jest-resolve/src/index.ts
Resolved #8610 
Green Ci, write more test for new code.
> fix: `moduleNameMapper` should take precedence over Node core modules

- CHANGELOG.md
- e2e/__tests__/detectOpenHandles.ts
- e2e/detect-open-handles/__tests__/notify.js
- packages/jest-reporters/src/notify_reporter.ts
Fixes #8036
Verified locally. Due to #9454 I didn't wanna add a test. Writing that justification now though, makes me wanna just skip the test on windows, though...
> fix: notifications should be fire&forget rather than having a timeout

- CHANGELOG.md
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/normalize.ts
Fix https://github.com/facebook/jest/issues/9526#issue-560779688
- the pattern of  replacePosixSep should be string type
> Ensure pattern of `replacePosixSep` is a string

- CHANGELOG.md
- e2e/__tests__/existentRoots.test.ts
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/normalize.ts
- packages/jest-core/src/__tests__/SearchSource.test.ts
See #9549 for background.
This _could_ be considered a breaking change and I can print a warning instead?. Also, as mentioned in #9549, should we verify that `roots` exist in `jest-haste-map` as well? Not sure how that affects Metro, but `jest-haste-map` is super inconsistent in how it handles missing `roots` depending on whether Watchman is used and if the OS is Windows.
Closes #9549.
Integration tests added
> fix: verify `rootDir` and all `roots` are directories

- examples/typescript/CheckboxWithLabel.tsx
- examples/typescript/__tests__/CheckboxWithLabel-test.tsx
- examples/typescript/sub.ts
- examples/typescript/sum.ts
I imitated #9124 commit which is about deprcated findDomNode() using Typescript.
Plus, I refactored sum.ts and sub.ts with arrow functions.
yarn test
This is my first pull request. If you have any advice, please do it for me.
> chore: replace `findDOMNode()` in examples/typescript

- examples/snapshot/.babelrc.js
- examples/snapshot/package.json
The snapshot example tests do not pass as is. This pull request adds babel configuration and dependency to fix this issue.
```
cd examples/snapshots
npm install
npm test
```
Expected result:   
```
> jest
PASS  __tests__/clock.react.test.js
PASS  __tests__/link.react.test.js
Test Suites: 2 passed, 2 total
Tests:       5 passed, 5 total
Snapshots:   7 passed, 7 total
Time:        1.851s, estimated 2s
Ran all test suites
```
> chore: add babel classProperties plugin to snapshot example

- CHANGELOG.md
- docs/Configuration.md
- packages/jest-reporters/src/__tests__/coverage_reporter.test.js
- packages/jest-reporters/src/coverage_reporter.ts
- packages/jest-types/src/Config.ts
Istanbul-reporters recently [changed](https://github.com/istanbuljs/istanbuljs/issues/529) their coverage reporting behaviour by introducing the `projectRoot` options.
This PR attempts to right the wrong and let a jest user configure the `projectRoot` right from the jest config by introducing the configuration through the well known tuple pattern.
Fixes #4103
> adds ability to pass custom reporter options

- CHANGELOG.md
- packages/jest-cli/src/__tests__/cli/args.test.ts
- packages/jest-cli/src/cli/args.ts
Fixes `.cjs` file validation for CLI `--config` option. Jest supports such files already, but CLI args validation wasn't updated (#9086).
Try to run jest by specifying a `.cjs` config manually:
```sh
$ jest --config path/jest.config.cjs
```
It should successfully load the config.
> fix(cli): .cjs files support by "--config" option

- CHANGELOG.md
- packages/jest-haste-map/src/__tests__/index.test.js
- packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js
- packages/jest-haste-map/src/crawlers/watchman.ts
- packages/jest-haste-map/src/index.ts
- packages/jest-haste-map/src/types.ts
This option was added a while back to support some use-cases with Yarn PnP but it was neither documented nor is this how I would solve the problem of files not being materialized as this functionality has the potential to de-opt operations in Jest's haste map.
This PR removes the option.
yolo
> [jest-haste-map] Remove `mapper` option.

- .vscode/settings.json
`eslint.autoFixOnSave` was deprecated.
VSCode on save runs eslint
> fix: vscode eslint on save settings

- CHANGELOG.md
- packages/jest-haste-map/package.json
- packages/jest-haste-map/src/crawlers/__tests__/node.test.js
- packages/jest-haste-map/src/crawlers/node.ts
- yarn.lock
Closes #9329 
Unit tests added
> fix: crash on unix based systems without find

- CHANGELOG.md
- packages/jest-jasmine2/src/index.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-runtime/src/__mocks__/createRuntime.js
- packages/jest-runtime/src/cli/index.ts
- packages/jest-runtime/src/index.ts
- packages/jest-util/src/index.ts
Since ESM is asynchronous we cannot run this as part of `jest-runtime`'s constructor.
This is technically a breaking change, but I'd be hugely surprised if someone either uses a custom runtime or uses `jest-runtime` directly. Can hold off on merging until Jest 26 changes start landing, but that'll make it impossible to land any kind of support for ESM in `setupFiles`. Maybe not a biggie 🙂 
Green CI
> chore: move execution of `setupFiles` to `jest-runner`

- packages/pretty-format/.npmignore
No need to publish perf directory from `pretty-format`. 106KB less to download by consumers.
Before -> After:
```
npm notice package size:  170.2 kB -> 64.1 kB
npm notice unpacked size: 526.6 kB -> 263.9 kB
```
npm pack
> chore: don't publish pretty-format/perf to npm

- CHANGELOG.md
- e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
- packages/jest-runtime/src/__tests__/__snapshots__/runtime_require_module_no_ext.test.js.snap
- packages/jest-runtime/src/helpers.ts
Anchor link to doc is broken, due to removed hypen in actual doc :+1: 
```
You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].
See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
```
Working link : https://jestjs.io/docs/en/configuration#modulefileextensions-arraystring
Unable to test. Stumbled on this issue :
https://github.com/nodkz/mongodb-memory-server/issues/131
> fix: update anchor link to doc

- CHANGELOG.md
- packages/jest-config/package.json
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/normalize.ts
- packages/jest-types/src/Config.ts
- yarn.lock
As discussed [here](https://github.com/facebook/jest/issues/9529#issuecomment-583556696).
Makes `ConfigGlobal` an interface to allow for declaration merging:
```
// ts-jest/index.d.ts
declare module '@jest/types' {
namespace Config {
interface ConfigGlobals {
'ts-jest': TsJestGlobalOptions;
}
}
}
// jest.config.js
/** @type {import('@jest/types').Config.InitialOptions} */
const config= {
globals: {
'ts-jest': {
isolatedModules: true,
myProperty: 1 // error, "myProperty" is not defined!
}
}
}
module.exports = config;
```
None 😬
> fix(jest-types): make `ConfigGlobal` an interace

- docs/Configuration.md
Just fix a typo in Configuration.md `runner`
> docs: fix typo in configuration runner

- CHANGELOG.md
- packages/jest-transform/src/ScriptTransformer.ts
- packages/jest-transform/src/__tests__/script_transformer.test.js
`writeFileAtomic` defaults to running `fsync` on the file after use.
`fsync` is a nearly 3x slowdown for me, ts-jest'ing my whole codebase (~900 files in testcase).
`ubuntu` defaults to `/tmp` as regular filesystem (i.e. not tmpfs), and some filesystems/devices have a large overhead for these repeated `fsync`s. I happen to be on nvme (sm961), and `btrfs`.
We're using `writeFileAtomic` here in order to get atomic rename, not to get full system power failure resilience. Most(tm) filesystems will guarantee either/or during a system power failure here, which is plenty enough for us.
There should be no functional changes here (even during a system power failure), only a performance increase in all cases, and a drastic performance increase in some cases.
> fix: fsync: false when writing cache files

- docs/JestObjectAPI.md
It was not clear to me what scope the effect of calling `jest.setTimeout(timeout)` would have, i.e. whether the default timeout would change only for the test file or describe block where the call originated or for all tests executed after the call.
The behavior that I describe here was reverse-engineered by experiment, since I could not immediately find the implementation of it. So it would be great to have my findings confirmed by someone who understands the implementation.
> docs: Clarify scope of jest.setTimeout

- CHANGELOG.md
- docs/TestingAsyncCode.md
A few sections of the "Testing Asynchronous Code" section of the docs seem to have grammatical errors: missing articles, commas, and unclear phrasing. This PR corrects them.
Requests for additional changes to these parts are welcome; I'm happy to make them in this PR.
n/a
> docs: Grammatical Corrections to Async Docs Page

- CHANGELOG.md
- packages/jest-environment-node/package.json
- packages/jest-environment-node/src/index.ts
Should silently fix #9538 without people needing to upgrade their version of node
I tested with node 10.14.0 and 10.14.2 locally - seems to work correctly
> fix: remove `getVmContext` from node env on older versions of node

- CHANGELOG.md
- packages/jest-runtime/src/__tests__/runtime_require_module.test.js
- packages/jest-runtime/src/index.ts
`require('module')` apparently returns a class with static properties, and not an object. This is not documented, but probably old behavior. We broke this in #9469. This is a quick and dirty "fix". Ideas welcome!
Fixes #9710
/cc @doniyor2109 
Unit test added
> fix: return constructable class from `require('module')`

- .github/workflows/nodejs.yml
- CHANGELOG.md
- package.json
- packages/jest-console/src/CustomConsole.ts
- packages/jest-core/package.json
- packages/jest-docblock/package.json
- packages/jest-phabricator/package.json
- packages/jest-transform/package.json
- packages/jest-transform/src/types.ts
- packages/jest-types/src/Global.ts
- packages/jest-watcher/package.json
- packages/jest/package.json
- scripts/buildTs.js
- scripts/verifyOldTs.js
- yarn.lock
In #9705 I just tested with `pretty-format` - seems I forgot to update a few `package.json`s. This also uncovered a few missing `types` fields as well, so fixing those at the same time.
I also rolled back on syntax that downlevel [doesn't support](https://github.com/sandersn/downlevel-dts/issues/32) and worked around [another bug](https://github.com/sandersn/downlevel-dts/issues/33).
Fixes #9714.
I've now verified `typescript@3.4` can compile the entire `jest` package, not just `pretty-format` and what that pulls in
> fix: ensure all packages correctly downlevel TS files

- CHANGELOG.md
- packages/jest-circus/package.json
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
- packages/jest-jasmine2/src/index.ts
- packages/jest-runtime/src/index.ts
Fixes #9600.
After refreshing my project's lockfile, I noticed an issue when running Jest with `jest-circus` as the runner due to a missing `jest-runtime` dependency. Making it a non-dev dependency should fix this.
Installing the dependency at the top level fixes the issue in my project, `npm` seems to install it in a nested node_modules folder otherwise.
> Fix type ellision of jest-runtime imports

- e2e/__tests__/coverageReport.test.ts
- e2e/__tests__/env.test.ts
- e2e/__tests__/hasteMapMockChanged.test.ts
- e2e/__tests__/hasteMapSha1.test.ts
- e2e/__tests__/jsonReporter.test.ts
- e2e/__tests__/listTests.test.ts
- e2e/__tests__/nodePath.test.ts
- e2e/__tests__/overrideGlobals.test.ts
- e2e/__tests__/showConfig.test.ts
- e2e/__tests__/testEnvironment.test.ts
- e2e/__tests__/toMatchSnapshotWithStringSerializer.test.ts
- e2e/__tests__/toThrowErrorMatchingInlineSnapshot.test.ts
- e2e/__tests__/watchModeOnlyFailed.test.ts
- e2e/__tests__/watchModePatterns.test.ts
- e2e/__tests__/watchModeUpdateSnapshot.test.ts
- e2e/__tests__/workerForceExit.test.ts
- e2e/babel-plugin-jest-hoist/__tests__/typescript.test.ts
- e2e/runJest.ts
- e2e/tsconfig.json
This is far from perfect, but it's better than nothing 🙂 We don't actually typecheck these, so it's solely for local DX as the squigglies are annoying
Green CI
> chore: fix some type errors in e2e tests

- CHANGELOG.md
- packages/jest-transform/src/index.ts
- packages/jest-transform/src/types.ts
Reference https://github.com/kulshekhar/ts-jest/pull/1363#discussion_r401243338
Not sure how to test this, probably Green CI ?
> chore(jest-types): expose TransformedSource for transformers

- CHANGELOG.md
- packages/jest-test-result/package.json
- packages/jest-test-result/src/types.ts
- packages/jest-test-result/tsconfig.json
- packages/jest-transform/src/types.ts
- packages/jest-types/src/Transform.ts
- packages/jest-types/src/index.ts
`@jest/test-result` is used ina. bunch of places, and its dependency on `@jest/transform` led to everybody depending on babel, istanbul etc.
We might wanna do this in more places. It's essentially why `Config` is still in `@jest/types` - so modules can depend on the type without pulling in the huge `jest-config`. As longs as we still re-export the type from the specific package (like `@jest/transform` does in this case) so you don't need to care about it, I think this is a cleaner solution.
Should move `@jest/test-result` as well, so `jest-message-util` doesn't need it
Green CI
> chore: move `TransformResult` to types package

- CHANGELOG.md
- packages/jest-message-util/package.json
- packages/jest-message-util/src/index.ts
- packages/jest-message-util/tsconfig.json
- packages/jest-test-result/src/types.ts
- packages/jest-types/src/TestResult.ts
- packages/jest-types/src/index.ts
> chore: extract `AssertionResult` from `@jest/test-result`

- CHANGELOG.md
- packages/jest-watcher/src/types.ts
> chore(jest-types): correct return type of shouldRunTestSuite for JestHookEmitter

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/jest-matcher-utils/src/Replaceable.ts
- packages/jest-matcher-utils/src/__tests__/Replaceable.test.ts
- packages/jest-matcher-utils/src/__tests__/deepCyclicCopyReplaceable.test.ts
- packages/jest-matcher-utils/src/deepCyclicCopyReplaceable.ts
Fixes #9745. Not sure if it makes sense to drop the fix from #9575? I can check if it's `writeable` at the same time I now check for a setter, which makes the test added at that time pass.
/cc @WeiAnAn 
Unit test added.
> fix: drop getters and setters when diffing objects for error

- packages/jest-each/README.md
There is a small typo in packages/jest-each/README.md.
Should read `separated` rather than `seperated`.
> docs: Fix simple typo, seperated -> separated

- CHANGELOG.md
- packages/jest-transform/src/index.ts
Expose  type `CacheKeyOptions` for `getCacheKey`
Green CI
> chore(jest-types): expose type `CacheKeyOptions` for `getCacheKey` 

- e2e/__tests__/__snapshots__/coverageReport.test.ts.snap
- e2e/__tests__/__snapshots__/coverageThreshold.test.ts.snap
- e2e/__tests__/__snapshots__/coverageWithoutTransform.test.ts.snap
- packages/jest-reporters/package.json
- yarn.lock
For https://github.com/istanbuljs/istanbuljs/pull/525
Green CI
> chore: bump istanbul-reports for new uncovered lines design

- CHANGELOG.md
- e2e/__tests__/__snapshots__/transform.test.ts.snap
- packages/babel-jest/package.json
- packages/babel-jest/src/__tests__/index.ts
- packages/babel-jest/src/index.ts
- packages/babel-jest/src/loadBabelConfig.ts
- packages/jest-runtime/src/index.ts
- packages/jest-runtime/tsconfig.json
- packages/jest-transform/src/ScriptTransformer.ts
- packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap
- packages/jest-transform/src/index.ts
- packages/jest-transform/src/types.ts
- yarn.lock
Extracted from #9597. I don't like the changes to `ScriptTransformer` in that PR, but I think the changes to `babel-jest` makes sense.
Unit tests added. As with #9597, there's no real way of triggering this behavior with real code so not thoroughly tested
> feat: pass ESM options to Babel

- CHANGELOG.md
- packages/jest-runtime/src/index.ts
- packages/jest-transform/src/ScriptTransformer.ts
When `jest-runtime` supports ESM, then babel can leave those statements alone. While not usable yet, this helps reduce the eventual diff for ESM.
~Added some unit tests to some funky merging code, otherwise~ this is not really testable until we land more ESM stuff. While it's all added as optional to avoid a breaking change, `jest-runtime` explicitly opts out if it, so no real way of triggering this.
> feat: pass ESM options to transformers

- e2e/__tests__/config.test.ts
- e2e/__tests__/esmConfigFile.test.ts
- e2e/__tests__/multiProjectRunner.test.ts
- e2e/runJest.ts
- packages/jest-core/src/lib/log_debug_messages.ts
- packages/test-utils/src/ConditionalTest.ts
Mostly useful as it's typed
Green CI
> chore: add helper for getting Jest's config in e2e tests

- CHANGELOG.md
- packages/babel-jest/package.json
- packages/babel-preset-jest/index.js
- packages/babel-preset-jest/package.json
- yarn.lock
~Breaking due to the increased peer dep, so let's land this in Jets 26.~
~Also needs https://github.com/nicolo-ribaudo/babel-preset-current-node-syntax/commit/565b63ac1b9876cb48bdb1dcc88121a7607624bf to be published~
Adds any babel syntax syntax plugins needed for the current runtime that exists in _some_ version of noe. Makes it so user don't have to care about the Babel implementation detail.
Ref
- #4519
- #6829
- #6492
- #8929
- #9768
Not sure... It looks correct? 😀
> feat: enable all babel syntax plugins

- CHANGELOG.md
- packages/jest-core/src/SearchSource.ts
- packages/jest-types/src/Config.ts
Type of `testRegex` in `ProjectConfig` doesn't match with documentation and also not match with real capable value. It should be `string | string[] | RegExp[]`. This PR does 2 things:
- Add `Array<RegExp>` to the existing type of `testRegex` in `ProjectConfig`.
- Update documentation to add `Array<RegExp>` for `testRegex` in Configuration page.
I'm not entirely sure if `testRegex` in `ProjectConfig` can be string or not, but the documentation says it can be string as well. For now I just updated the type to add `Array<RegExp>` to the existing type. I observed that adding `string` will change quite something in internal codes so I won't touch.
Green CI probably ?
> chore(jest-types): correct type testRegex for ProjectConfig

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/matchers.ts
If it isn't broke, don't fix it.
I reverted back to the original guard since the type hasn't changed and it was an ugly nest of conditions.
Added a new test case.
-----
fixes #9792
> Fix to have length guard

- docs/GlobalAPI.md
Adds missing aliases to API documentation:
- `ftest`
- `ftest.each(table)`
- `` ftest.each`table` ``
- `it.todo`
These undocumented aliases exist in the TypeScript type declarations for Jest tests
> Document missing aliases

- CHANGELOG.md
- e2e/__tests__/jestChangedFiles.test.ts
- packages/jest-changed-files/src/git.ts
I don't think it makes sense to exclude them.
Assertion added to existing test.
> fix: `--only-changed` should include staged files

- CHANGELOG.md
- docs/GlobalAPI.md
- docs/JestObjectAPI.md
- e2e/__tests__/importedGlobals.test.ts
- e2e/imported-globals/__tests__/env.test.js
- e2e/imported-globals/babel.config.js
- e2e/imported-globals/package.json
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
- packages/jest-globals/.npmignore
- packages/jest-globals/package.json
- packages/jest-globals/src/__tests__/index.ts
- packages/jest-globals/src/index.ts
- packages/jest-globals/tsconfig.json
- packages/jest-runtime/package.json
- packages/jest-runtime/src/index.ts
- packages/jest-runtime/tsconfig.json
- packages/jest-types/src/Circus.ts
- packages/jest-types/src/Global.ts
- scripts/buildTs.js
People have asked for it, so why not. We still add to the global env - we can remove that later if we want to (via some config flag I guess). If we want to do that it should be pretty straight forward, just add a `runtime.registerGlobals` function or some such and get the globals from that rather than `environment.global`. I don't want it to be `import {test} from 'jest'` as that's difficult to type correctly - a separate package can both ensure types are correct and that it's only used in a Jest environment.
Fixes #4473
Fixes #5192
Closes #7571
Closes #9306
Integration test added
> feat: add `@jest/globals` package for importing globals explicitly

- packages/jest-core/src/TestScheduler.ts
- packages/jest-runner/src/index.ts
- packages/jest-runner/src/types.ts
There was an `any` object containing all of the TestRunners. I gave it a type.
Typescript build succeeded.
> chore: type TestScheduler's testRunners object

- CHANGELOG.md
- packages/jest-each/src/__tests__/__snapshots__/index.test.ts.snap
- packages/jest-each/src/__tests__/index.test.ts
- packages/jest-each/src/index.ts
> fix(jest-each) Throws an error when too much arguments are passed

- CHANGELOG.md
- tsconfig.json
They don't work anyways since we run `prettier` on Jest's built code, and they bloat the install size.
🤷
> chore: remove declaration maps

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/index.ts
- packages/expect/src/types.ts
resolves #9240
snapshot && unit test
> feat: support `async function`s in `toThrow`

- CHANGELOG.md
- babel.config.js
- e2e/__tests__/__snapshots__/transform.test.ts.snap
This drops the `objectSpread` babel helper, resulting in these sorts of diffs:
Should in theory be faster on newer nodes as well, as the engine can optimize it
Green CI
> chore: target node 8.3, not 8.0

- packages/expect/src/matchers.ts
Simplifies the check using optional chaining. Maybe the code can be simplified even further omitting the string check as well. WDYT?
Relates to #9796
cc @G-Rath @SimenB
> Use optional chaining in toHaveLength matcher

- CHANGELOG.md
- e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
- e2e/__tests__/nativeEsm.test.ts
- e2e/native-esm/__tests__/native-esm.test.js
- e2e/native-esm/index.js
- e2e/native-esm/package.json
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
- packages/jest-jasmine2/src/index.ts
- packages/jest-resolve/package.json
- packages/jest-resolve/src/index.ts
- packages/jest-resolve/src/shouldLoadAsEsm.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-runtime/src/__mocks__/createRuntime.js
- packages/jest-runtime/src/cli/index.ts
- packages/jest-runtime/src/index.ts
- yarn.lock
This adds _very_ basic support for running tests as native ES modules. 2 main limitations:
1. it does not support mixing ESM and CJS
1. the `jest` object on `import.meta` is an empty object. (meaning none of `jest.*` functions are available)
Another limitation is that the APIs we need only exist on node 13, and they're flagged as experimental
Like V8 test coverage, it only supports the node env, but using JSDOM 16 should also work, although I haven't bothered to verify.
Ref #9430.
Integration test added. More of a smoketest than anything else.
> feat: experimental ES Modules support

- CHANGELOG.md
- e2e/__tests__/workerForceExit.test.ts
- packages/jest-runner/src/index.ts
This warning should go to `stderr`, otherwise when you have a test that leaks while using `--json` it will produce invalid JSON when reading the `stdout` of a Jest process.
This regressed in Jest through #8206 and made Jest on CI at FB fail. Verified this change fixes it.
> `[jest-runner]` Don't print warning to stdout when using `--json`

- CHANGELOG.md
- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/native-esm/__tests__/native-esm.test.js
- e2e/native-esm/fromCjs.mjs
- packages/jest-resolve/src/shouldLoadAsEsm.ts
- packages/jest-runtime/src/index.ts
Reported in https://github.com/facebook/jest/issues/9430#issuecomment-616742403
Test added
> fix: support import cjs from mjs

- e2e/Utils.ts
- e2e/__tests__/jestChangedFiles.test.ts
- e2e/__tests__/onlyChanged.test.ts
DISCLAIMER: Feel free to close this PR if it does not make sense.
When running `yarn test-ci` on my machine not having `hg` installed, I saw that some tests requiring `hg` were explicitely skipped while others were still executed.
I just applied what was done in `jestChangedFiles.test.ts` on another test that needs `hg` to run.
> chore: skip mercurial tests when no hg installed

- e2e/Utils.ts
Switching to `type=junction` in `fs.symlinks` seems to fix the issue.
Before that change, running `yarn test-ci` was failing due to symlinks on the tests:
- no babel-jest › fails with syntax error on flow types
- no babel-jest › instrumentation with no babel-jest
Here is a related ticket on node: https://github.com/nodejs/node/issues/18518
See comments https://github.com/nodejs/node/issues/18518#issuecomment-513809856 and https://github.com/nodejs/node/issues/18518#issuecomment-513866491
The tests relying on those helpers are now passing on my Windows machine without the need to have admit rights.
_Let see if they pass the CI_
> chore: fix symlink creation failures on windows in tests

- packages/jest-haste-map/src/lib/__tests__/dependencyExtractor.test.js
- packages/jest-runtime/src/index.ts
Extracted from #9854 as it makes #9849 cleaner, and isn't breaking,
Also includes a fix for a faulty test (also from #9849)
Green CI
> chore(runtime): simplify `createJestObjectFor`

- .github/workflows/nodejs.yml
- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/__tests__/nativeEsm.test.ts
- packages/jest-cli/src/init/__tests__/init.test.js
Circle doesn't have node 14 yet: https://hub.docker.com/r/circleci/node/tags
Green CI 🤞 I haven't tested any of the nightlies for 14, completely slipped my mind. Hopefully we still pass 😀
> chore: run CI on Node 14

- CHANGELOG.md
- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/native-esm/__tests__/native-esm.test.js
- e2e/native-esm/anotherDynamicImport.js
- packages/jest-runtime/src/index.ts
Fixes issue reported in https://github.com/facebook/jest/issues/9430#issuecomment-617492893
Test added
> fix(esm): handle parallel imports

- .vscode/settings.json
By default VSCode is using its own copy of TS instead of the workspace one. This is never something users want (when actually having their own TS) - not sure why VScode default has not been changed 🤷 Having it use the one built into VScode can cause ultimate confusion sometimes (e.g. seeing errors not reported by `tsc`)
> Add an option to vscode settings to always use workspace TS

- .circleci/config.yml
Should be published now
Green CI
> chore: run CircleCI on node 14

- CHANGELOG.md
- packages/jest-resolve/package.json
- packages/jest-resolve/src/defaultResolver.ts
- yarn.lock
`resolve@1.16.1` uses `realpathSync.native` internally if available, but it's not available on node 8. `realpath-native` falls back to `process.bindings`, so let's plug that in
Green CI
> chore: update resolve

- packages/jest-runtime/src/index.ts
- testSetupFile.js
As mentioned here: https://github.com/facebook/jest/pull/9841#issuecomment-617413947
This makes me think that we might want to rethink the warning... Is it safe to include this change?
@antongolub @thymikee @jeysal would love your thoughts
EDIT: One thing we can do is only warn _once_ per `jest-runtime` (meaning per test file). Better than potentially flooding the output at least
Green CI without flooded output
> chore: mock stealthy-require in tests

- CHANGELOG.md
- packages/jest-resolve/src/defaultResolver.ts
`realpath` continues to be quite slow on Windows, let's try to cache the `realpath` call.
~(This includes #9872, which just updates `resolve`)~
Fixes #9776
Green CI
> fix: pass custom cached `realpath` function to `resolve`

- .vscode/launch.json
I've tried to use the existing setting but it was outdated and couldn't be used - it was referencing `flow-remove-types/register` which you no longer use. So I've updated it locally for the config recommended here: https://github.com/microsoft/vscode-recipes/tree/master/debugging-jest-tests#configure-launchjson-file-for-your-test-framework and used it with success. It differs slightly from what you had configured previously - I'm not too familiar with those options so I'm not in a position of adjusting the previous config (instead of just using a new one).
> Update .vscode/launch.json settings

- CHANGELOG.md
- packages/jest-message-util/src/__tests__/__snapshots__/messages.test.ts.snap
- packages/jest-message-util/src/__tests__/messages.test.ts
- packages/jest-message-util/src/index.ts
When `--noStackTrace` flag is set, code frames should not be printed as mentioned [here](https://github.com/facebook/jest/pull/9741#issuecomment-617385240)
New snapshot test cases added.
> noCodeFrame respects noStackTrace

- CHANGELOG.md
- package.json
- packages/jest-environment/tsconfig.json
- scripts/buildTs.js
- yarn.lock
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44033#issuecomment-618480183
`@jest/environment` references `types="jest"` without a dependency on `@types/jest`:
```Shell
$ npm install @jest/environment
$ > index.ts
$ tsc --types @jest/environment index.ts
node_modules/@jest/environment/build/index.d.ts:8:23 - error TS2688: Cannot find type definition file for 'jest'.
8 /// <reference types="jest" />
~~~~
```
I'm assuming that the `/// <reference types="jest" />` is unintended? but I haven't gotten to the bottom of why it gets added/whether it's a bug in the compiler?
[By default](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types), all visible `@types` packages are included in your compilation, but there are plenty of other visible `@types` …
> fix: don't /// <reference types="jest" />

- CHANGELOG.md
- e2e/__tests__/onlyChanged.test.ts
- packages/jest-core/src/SearchSource.ts
- packages/jest-core/src/TestScheduler.ts
- packages/jest-core/src/__tests__/SearchSource.test.ts
- packages/jest-core/src/runJest.ts
- packages/jest-reporters/src/__tests__/coverage_worker.test.js
- packages/jest-reporters/src/coverage_reporter.ts
- packages/jest-reporters/src/coverage_worker.ts
- packages/jest-reporters/src/generateEmptyCoverage.ts
- packages/jest-reporters/src/types.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-runner/src/types.ts
- packages/jest-runtime/src/index.ts
- packages/jest-transform/src/shouldInstrument.ts
- packages/jest-transform/src/types.ts
This PR fixes #8545 . It will show coverage of sources related to tests when jest is in watch mode (`--watch`) or `--onlyChange`.
As for implementation, this PR added `findRelatedSourceFromTestsInChangedFiles` in `SearchSource`, and apply it when there are `changedFiles`, then pass the results into options of `shouldInstrument`. When `changedFiles` exist and the file is not in changedFiles nor `sourcesRelatedToTestsInChangedFiles`, we will not instrument it.
Add an e2e test case for the use case and some unit test case for `SearchSource`.
> Show coverage of sources related to tests in changed files

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/extend.test.js.snap
- packages/expect/src/__tests__/extend.test.js
- packages/expect/src/jestMatchersObject.ts
> Prints the Symbol name into the error message with a custom asymmetric matcher

- docs/Configuration.md
- website/versioned_docs/version-22.x/Configuration.md
- website/versioned_docs/version-23.x/Configuration.md
- website/versioned_docs/version-24.x/Configuration.md
- website/versioned_docs/version-25.1/Configuration.md
- website/versioned_docs/version-25.3/Configuration.md
According to `pretty-format` docs the [new API has been introduced in Jest 21](https://github.com/facebook/jest/tree/27228e8fe7af50e1113763fe4c277fec8034fdd5/packages/pretty-format#writing-plugins) but the main docs still mention only the old API (I wasn't actually able to find any reference to the new API).
> Use the new serializer plugin API in example

- website/versioned_docs/version-25.1/Troubleshooting.md
We've dropped node 6, but unlike the time we dropped node 4 we don't support v6 _at all_. Engine warnings should crop up, so let's just delete the section.
(added a 25.1 version so all 25 versions of the docs gets the section removed)
Ran website locally
> chore: remove dated node 6 reference from docs

- website/pages/en/index.js
Fix dead link to coverage CLI option in website landing page (https://jestjs.io/)
> Fix dead link to coverage CLI option

- CHANGELOG.md
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
- packages/jest-jasmine2/src/index.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-runtime/src/cli/index.ts
Fixes #9851. I think it prints a peer dep warning that people are ignoring, but trivial to fix so why not
Green CI
> fix: handle mismatch between circus and runtime versions

- CHANGELOG.md
- packages/jest-runner/src/runTest.ts
- packages/jest-runtime/src/index.ts
I had to add this to #9902 otherwise Circus exploded with an OOM. Makes sense to me regardless to help GC along a bit, so we can land this separately
Green CI
> chore: add teardown of `jest-runtime`

- CHANGELOG.md
- packages/jest-runtime/src/index.ts
Any internal module should never be transformed at runtime, so let's just bail early rather than having `ScriptTransformer` skip them (or not, which is super wasteful).
Green CI
> fix: do not transform internally imported files

- CHANGELOG.md
- packages/jest-resolve/src/index.ts
- packages/jest-runtime/src/index.ts
- tsconfig.json
`Map`s are about twice as fast for larger data sets in Chrome 80, very much likely this applies to Node as well: https://stackoverflow.com/a/55711780/1850276
Similar to #8232, but applied to all caches.
~(Includes #9900 as I forgot to switch to master first and can't be bothered to fix the conflict twice 😀 Please review second commit until I rebase)~
Green CI.
> chore: use `Map`s rather than objects as cache holders

- CHANGELOG.md
- docs/Es6ClassMocks.md
All examples for mocking ES6 classes assume that the class is exported as the default export. If that's not the case then mocking is done a little bit differently.
Users are confused about why the mock is not working `[*Exported function name] is not a constructor` is the error when you try to instantiate the mocked instance.
This pull request adds an example of how to mock a class which is not the default export from the module.
> Add an example for mocking non-default module export class

- CHANGELOG.md
- packages/jest-haste-map/package.json
See https://github.com/microsoft/playwright-runner/pull/38
```sh-session
$ grep 'graceful-fs' `find packages -iname '*.d.ts'`
packages/jest-haste-map/build/types.d.ts:import type { Stats } from 'graceful-fs';
packages/jest-haste-map/build/ts3.4/types.d.ts:import { Stats } from 'graceful-fs';
```
🤷
> fix: include missing `@types/graceful-fs` dep

- CHANGELOG.md
- packages/jest-runner/src/index.ts
- packages/jest-runner/src/testWorker.ts
- packages/jest-runner/src/types.ts
Fixes #9910.
I've tested manually. Seeing as the error only came on a re-run in watch mode, I don't think we have any good ways to write a test for this?
> fix: correctly serialize `Set` passed to worker

- CHANGELOG.md
- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/native-esm/__tests__/native-esm.test.js
- packages/jest-runtime/src/index.ts
Fixes first part of https://github.com/facebook/jest/issues/9430#issuecomment-620944138
Test added
> fix: vary ESM cache by query

- CHANGELOG.md
- packages/jest-globals/src/index.ts
- packages/jest-runtime/src/index.ts
Fixes #9922
I've copied the new files into a VS Code project, and it worked
> fix: export globals as values, not types

- .circleci/config.yml
- CHANGELOG.md
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
I have a fix for this, but I'm hoping CI will tell us it currently leaks, then I can push the fix.
Fixes #8816
Activating the leaks checks on circus
> fix: plug memory leak in jest-circus when running in band

- CHANGELOG.md
- e2e/__tests__/skipBeforeAfterAll.test.ts
- e2e/before-all-skipped/__tests__/beforeAllFiltered.test.js
- e2e/before-all-skipped/package.json
- packages/jest-jasmine2/src/treeProcessor.ts
Fixes #6755
Fixes #8379
`e2e/__tests__/skipBeforeAfterAll.test.ts` corresponds to #8379 example. I checked it failed on previous revision.
> fix: don't run beforeAll/afterAll in skipped block

- CHANGELOG.md
- TestUtils.ts
- e2e/__tests__/__snapshots__/showConfig.test.ts.snap
- packages/jest-config/src/Defaults.ts
- packages/jest-config/src/ValidConfig.ts
- packages/jest-core/src/__tests__/SearchSource.test.ts
- packages/jest-core/src/lib/__tests__/__snapshots__/log_debug_messages.test.ts.snap
- packages/jest-haste-map/src/__tests__/index.test.js
- packages/jest-haste-map/src/index.ts
- packages/jest-runtime/src/__tests__/runtime_require_module.test.js
- packages/jest-runtime/src/index.ts
- packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap
- packages/jest-types/src/Config.ts
- packages/jest-validate/src/__tests__/__snapshots__/validate.test.ts.snap
- packages/jest-validate/src/__tests__/fixtures/jestConfig.ts
- packages/jest-validate/src/__tests__/validate.test.ts
- website/versioned_docs/version-22.x/TutorialReactNative.md
- yarn.lock
*Same as https://github.com/facebook/jest/pull/8535 that was accidentally closed.*
With the removal of haste from `react-native`, we *finally* do not need `providesModuleNodeModules` in either Jest or Metro any longer. This is the PR that removes this feature from Jest and a corresponding change will be merged to Metro soon.
This was one of my least favorite configuration options and the added complexity (see the whitelist in `jest-haste-map`) was annoying to deal with. No more!
Ran the tests via `yarn jest`
> Remove `providesModuleNodeModules` from Jest.

- packages/jest-core/src/__tests__/SearchSource.test.ts
Missed this one (probably was added recently).
No more validation warnings.
> Remove leftover `providesModuleNodeModules`

- docs/CLI.md
- docs/Configuration.md
- e2e/__tests__/__snapshots__/globals.test.ts.snap
- e2e/__tests__/globals.test.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-runtime/src/index.ts
Following up #9423 - since we've bumped the minimum version of Node (and jsdom@16 update is incoming), we can remove some guards and caveats from the docs.
Green CI
> chore: remove checks for compileFunction

- CHANGELOG.md
- CONTRIBUTING.md
- e2e/Utils.ts
- e2e/__tests__/overrideGlobals.test.ts
- packages/jest-circus/src/utils.ts
- packages/jest-console/src/BufferedConsole.ts
- packages/jest-console/src/CustomConsole.ts
- packages/jest-jasmine2/src/__tests__/queueRunner.test.ts
- packages/jest-jasmine2/src/queueRunner.ts
- packages/jest-reporters/src/__tests__/__snapshots__/summary_reporter.test.js.snap
- packages/jest-reporters/src/get_result_header.ts
- packages/jest-reporters/src/utils.ts
- packages/jest-reporters/src/verbose_reporter.ts
- packages/jest-util/src/__tests__/formatTime.test.ts
- packages/jest-util/src/formatTime.ts
- packages/jest-util/src/index.ts
- packages/pretty-format/package.json
- packages/pretty-format/perf/test.js
This commit fixes the formatting of time durations to have a spcae
between the quantity and the unit symbol which is compliant with
the SI. It also consolidates all of the time duration formatting
code into formatTime() in jest-util to keep the code DRY and so
that future updates are easy.
`yarn jest formatTime`
> Fix time duration formatting as per SI

- CHANGELOG.md
- e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
- e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
- e2e/__tests__/hasteMapSize.test.ts
- package.json
- packages/jest-cli/package.json
- packages/jest-cli/src/cli/index.ts
- packages/jest-cli/src/init/index.ts
- packages/jest-config/package.json
- packages/jest-config/src/getCacheDirectory.ts
- packages/jest-config/src/index.ts
- packages/jest-config/src/normalize.ts
- packages/jest-config/src/utils.ts
- packages/jest-core/package.json
- packages/jest-core/src/runJest.ts
- packages/jest-resolve/package.json
- packages/jest-resolve/src/__tests__/resolve.test.ts
- packages/jest-resolve/src/defaultResolver.ts
- packages/jest-resolve/src/index.ts
- packages/jest-resolve/src/nodeModulesPaths.ts
- packages/jest-runtime/package.json
- packages/jest-runtime/src/cli/index.ts
- packages/jest-transform/package.json
- packages/jest-transform/src/ScriptTransformer.ts
- packages/jest-transform/src/__tests__/script_transformer.test.js
- packages/jest-util/src/index.ts
- packages/jest-util/src/tryRealpath.ts
We don't need it anymore as node 10 has `realpathSync.native`
Green CI
> chore: remove dependency on `realpath-native`

- CHANGELOG.md
- docs/Configuration.md
- website/versioned_docs/version-22.x/Configuration.md
- website/versioned_docs/version-23.x/Configuration.md
- website/versioned_docs/version-24.x/Configuration.md
- website/versioned_docs/version-25.1/Configuration.md
- website/versioned_docs/version-25.3/Configuration.md
- website/versioned_docs/version-25.5/Configuration.md
I've added a default option to clear up any confusion, hopefully that will make it more obvious how it should be added back in  when additional transformers are added.
It wasn't clear to me when adding an SVG transformer that the default transformer is ignored. Especially as in the docs the default is `undefined`
As per https://github.com/facebook/jest/issues/8574 it was recommended I could update the docs to make this a little clearer
docs only.
> Updated config docs - transform

- CHANGELOG.md
- e2e/__tests__/__snapshots__/transform.test.ts.snap
- packages/babel-jest/src/__tests__/index.ts
- packages/babel-jest/src/index.ts
I took a regression bug in babel-jest. 
The regression bug occurs since https://github.com/facebook/jest/commit/bb720d2e180e15b0d0962d255bb8f76901da4a66#diff-ad0be0b5e1f4711c408a42bdbea512bcR43-R57 .
fixes https://github.com/facebook/jest/issues/9926
> fix: handle `null` being passed to `createTransformer`

- docs/Configuration.md
- website/versioned_docs/version-24.x/Configuration.md
- website/versioned_docs/version-25.5/Configuration.md
While trying to make run jest test cases in the required sequence, it was a little difficult to find and how to add **testSequencer** config. So Added example config for **testSequencer**. It will help and makes easier for users to run.
Not required as we updated only docs.
> updated docs regarding testSequencer

- CHANGELOG.md
- docs/TestingFrameworks.md
- website/versioned_docs/version-25.1/TestingFrameworks.md
> docs: Updated Testing Frameworks guide with React; make it generic

- CHANGELOG.md
- docs/Configuration.md
- docs/JestObjectAPI.md
- e2e/__tests__/modernFakeTimers.test.ts
- e2e/modern-fake-timers/from-config/__tests__/test.js
- e2e/modern-fake-timers/from-config/package.json
- e2e/modern-fake-timers/from-jest-object/__tests__/test.js
- e2e/modern-fake-timers/from-jest-object/package.json
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
- packages/jest-environment/src/index.ts
- packages/jest-jasmine2/src/index.ts
- packages/jest-runtime/package.json
- packages/jest-runtime/src/index.ts
- packages/jest-runtime/tsconfig.json
- packages/jest-types/src/Config.ts
This is an alternative to #5171 and #7300. Difference from them is that in this PR Lolex is added as an opt-in alternative to the current implementation of fake timers, instead of replacing it.
I've added `jest.useFakeTimers('modern');` which will allow people to migrate test file by test file if they want the new system. People can also use `useFakeTimers('legacy')` if they want to keep using the old implementation.
The default if nothing is passed to `jest.useFakeTimers` (or just `fake` is passed in config) will be the legacy implementation in Jest 26, and we will swap the default in Jest 27. We have no plans to ever remove the legacy implementation.
Hopefully this means FB can migrate over over timer and we can remove Jest's implementation.
Fixes #3465
Fixes #5165
Closes #5171
Closes …
> feat: add new 'modern' implementation of Fake Timers

- CHANGELOG.md
- e2e/__tests__/stackTrace.test.ts
- e2e/resolve/__tests__/resolve.test.js
- packages/jest-resolve/src/index.ts
I think it's a bit easier to grok
Tests updated
> chore: improve error on module not found

- e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
- e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
- packages/jest-resolve/src/index.ts
> chore: fix windows CI

- CHANGELOG.md
- e2e/__tests__/watchModeNoAccess.test.ts
- e2e/__tests__/watch_mode_no_access.test.js
- packages/jest-haste-map/src/index.ts
Fixes #7124. Watch mode shouldn't trigger a new test run when only the access time of the file has been modified.
Added e2e tests.
> Fix invalid re-run of tests in watch mode

- CHANGELOG.md
- e2e/__tests__/__snapshots__/globals.test.ts.snap
- e2e/__tests__/globals.test.ts
- packages/jest-circus/src/eventHandler.ts
- packages/jest-circus/src/run.ts
- packages/jest-circus/src/utils.ts
- packages/jest-types/src/Circus.ts
Fixes #8360 
Added a test to `globals.test` failing on circus master but passing on Jasmine and circus PR.
> align circus with jasmine's top-to-bottom execution order

- e2e/__tests__/watchModeNoAccess.test.ts
> chore: skip broken test on windows

- e2e/__tests__/watchModeNoAccess.test.ts
It should be seconds, not ms.
(we cannot pass a `Date` object due to #2549)
Green CI
> chore: fix watch mode test with utimes

- CHANGELOG.md
- e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
- e2e/__tests__/moduleNameMapper.test.ts
- e2e/module-name-mapper-correct-mock-absolute-path/__tests__/index.js
- e2e/module-name-mapper-correct-mock-absolute-path/index.js
- e2e/module-name-mapper-correct-mock-absolute-path/package.json
- e2e/module-name-mapper-correct-mock-absolute-path/src/components/Button.js
- packages/jest-runtime/src/index.ts
In this special case, the moduleNameMapper got applied to the import path twice, resulting in an invalid module path.
still validating the changes, WIP
Fixes #8633
Added the absolute path moduleNameMapper test case.
> fix: absolute path moduleNameMapper + jest.mock issue

- website/blog/2020-05-05-jest-26.md
> chore: fix date and heading in blog post

- CHANGELOG.md
- packages/jest-jasmine2/src/__tests__/expectationResultFactory.test.ts
- packages/jest-jasmine2/src/expectationResultFactory.ts
Fix https://github.com/facebook/jest/issues/9988
> fix(jest-jasmine2): fix Error message

- CHANGELOG.md
- packages/jest-diff/src/__tests__/__snapshots__/diff.test.ts.snap
- packages/jest-diff/src/__tests__/diff.test.ts
- packages/jest-diff/src/constants.ts
- packages/jest-diff/src/index.ts
`snapshot-diff` has been [updated to make use of `jest-diff` options for no colors](https://github.com/jest-community/snapshot-diff/pull/123), as [provided in the documentation](https://github.com/facebook/jest/tree/d81464622dc8857ba995ed04e121af2b3e8e33bc/packages/jest-diff#example-of-options-for-no-colors). Unfortunately, the "no visual differences" message is still output with `chalk.dim` and doesn't make use of the options for no colors - this means that some [snapshot diffs are now outputting ansi escape codes](https://github.com/jest-community/snapshot-diff/issues/129).
This PR updates the `NO_DIFF_MESSAGE` and `SIMILAR_MESSAGE` messages to use the `commonColor` value from the diff options, which defaults to `chalk.dim`, but can now be overridden by the user.
- The existing test …
> fix: Control no diff message color with diff options

- packages/jest-config/src/Deprecated.ts
When running `jest` v26 with the `browser` config field set, there's a deprecation warning in the console that contains a minor typo for the [`resolver`](https://jestjs.io/docs/en/configuration#resolver-string) field.
This change only applies to the warning generating when using the `browser` config field for `jest` v26.
> Fix dependency warning typo for `browser` config field

- CHANGELOG.md
- packages/jest-snapshot/package.json
Hi there,
I recently updated to `jest-snapshot` version `26.0.1`, and was getting this TypeScript compilation error:
```
node_modules/jest-snapshot/build/index.d.ts:17:31 - error TS2307: Cannot find module 'jest-haste-map/build/HasteFS'.
17     cleanup: (hasteFS: import("jest-haste-map/build/HasteFS").default, update: Config.SnapshotUpdateState, snapshotResolver: JestSnapshotResolver, testPathIgnorePatterns?: string[] | undefined) => {
```
It appears `jest-haste-map` should no longer be a dev dependency of `jest-snapshot`?
PS: I raised this PR before raising an issue, feel free to 🔥it if there's already a fix underway (or if it's the wrong fix).
> fix: add missing haste-map dep to jest-snapshot

- CHANGELOG.md
- docs/Configuration.md
- packages/jest-config/src/__tests__/readConfigs.test.ts
- packages/jest-config/src/index.ts
Original #8357 was too old, created this PR to start fresh.
At that time jest cli required the dynamic config module synchronously, that PR enabled loading jest config module async.
It appears that the code in master already have these or similar changes that allows async loading.
All that is missing is documentation
No tests needed as all of the changes are already in master, only changed docs
> feat: support config files exporting (`async`) `function`s

- CHANGELOG.md
- docs/JestObjectAPI.md
- website/versioned_docs/version-26.0/JestObjectAPI.md
Current example for `jest.enableAutomock()` functionality uses `disableAutomocking.js` as the filename for the example test file:
it results confusing for the reader.
Here you can see a screenshot of the built website after the changes:
> docs: correct confusing filename in `enableAutomock` example

- CHANGELOG.md
- packages/jest-core/src/getProjectDisplayName.ts
- packages/jest-reporters/src/__tests__/utils.test.ts
- packages/jest-reporters/src/utils.ts
- packages/jest-test-result/src/helpers.ts
- packages/jest-types/src/Config.ts
Fixes #10010 
If I understand correctly, the type of `displayName` in `ProjectConfig` type cannot be a string because it has been normalized, therefore I remove the `string` type in the `DisplayName` type. Since `InitialOptions` can still take in `string` I add it back there.
The rest is to change the places where `displayName` is treated as `string` (i.e. remove such codes because it will never happen)
TODOs:
Check CI results 😅
> Cleanup `displayName` type

- CHANGELOG.md
- packages/jest-cli/src/init/__tests__/__snapshots__/init.test.js.snap
- packages/jest-cli/src/init/__tests__/init.test.js
- packages/jest-cli/src/init/generate_config_file.ts
- packages/jest-cli/src/init/index.ts
- packages/jest-cli/src/init/questions.ts
- packages/jest-config/src/Descriptions.ts
Created This PR to resolve this issue #10015, to add 'coverageProvider' to 'jest --init' prompts
We need  to encourage folks try out the V8 based code coverage, so the prompt in "--init" and its entry into the generated config file would be help.
> Add `coverageProvider` to `jest --init` prompt

- CHANGELOG.md
- e2e/__tests__/__snapshots__/console.test.ts.snap
- e2e/__tests__/console.test.ts
- packages/jest-console/src/__tests__/getConsoleOutput.test.ts
- packages/jest-console/src/getConsoleOutput.ts
- packages/jest-message-util/src/__tests__/__snapshots__/messages.test.ts.snap
- packages/jest-message-util/src/__tests__/messages.test.ts
- packages/jest-reporters/src/default_reporter.ts
- packages/jest-runner/src/runTest.ts
Although `formatStackTrace` acts according to `StackTraceOptions`, `getConsoleOutput` needs to take `noStackTrace` value in global config and use it to override the options passed to `formatStackTrace`. This will resolve the bug mentioned [here](https://github.com/facebook/jest/issues/8819#issuecomment-632763136)
Pass existing test cases. Adding new test case to ensure `getConsoleOutput` does override corresponding configuration.
> getConsoleOutput receives global noStackTrace

- .vscode/extensions.json
Jest has migrated to TypeScript, so this extension is probably
not very useful in this repo anymore.
https://github.com/facebook/jest/issues/7807
> Remove Flow from vscode recommended extensions

- CHANGELOG.md
- docs/JestObjectAPI.md
- e2e/modern-fake-timers/from-config/__tests__/test.js
- e2e/modern-fake-timers/from-jest-object/__tests__/test.js
- packages/jest-environment/src/index.ts
- packages/jest-fake-timers/src/modernFakeTimers.ts
- packages/jest-runtime/src/index.ts
- website/versioned_docs/version-26.0/JestObjectAPI.md
This PR does two (related) things. 
The internal types for `setSystemTime` are currently `now?: number`, but in using jest I found passing a `Date` also worked and was a bit more ergonomic in some cases. For example:
```ts
// if Date is not in the union, this errors:
jest.setSystemTime(new Date('2020-06-15T00:00:00.933Z'));
// you'd have to do:
jest.setSystemTime(new Date('2020-06-15T00:00:00.933Z').getTime());
```
The types for the underlying `this._clock.setSystemTime` call in `jest-fake-timers/src/modernFakeTimers.ts` support `Date`, so echoing that in `setSystemTime` seemed reasonable. I was looking into this while working on a PR to add types for `setSystemTime` and `getRealSystemTime` to DefinitelyTyped, and wanted to make sure that those types matched jest's codebase's types and …
> setSystemTime and getRealSystemTime type and doc update

- .github/ISSUE_TEMPLATE/question.md
- .github/SUPPORT.md
- CONTRIBUTING.md
- docs/MoreResources.md
- website/blog/2017-05-06-jest-20-delightful-testing-multi-project-runner.md
- website/blog/2018-05-29-jest-23-blazing-fast-delightful-testing.md
- website/core/Footer.js
- website/pages/en/help.js
- website/versioned_docs/version-22.x/MoreResources.md
- website/versioned_docs/version-23.x/MoreResources.md
We're planning on some changes to channels on Reactiflux, such as merging the `#jest` channel into `#testing` (which is more active and mostly about Jest anyway) and showing a rules/CoC document when accessing the server for the first time. The website and docs are currently linking directly to the `#jest` channel that we're planning on removing, so we'd like to change Jest's links first to prevent any interruptions or confusion for users.
> Update links to Reactiflux

- CHANGELOG.md
- packages/jest-core/src/SearchSource.ts
- packages/jest-core/src/__tests__/SearchSource.test.ts
- packages/jest-haste-map/src/HasteFS.ts
- packages/jest-transform/src/shouldInstrument.ts
- packages/jest-util/package.json
- packages/jest-util/src/__tests__/globsToMatcher.test.ts
- packages/jest-util/src/globsToMatcher.ts
- packages/jest-util/src/index.ts
I was profiling some Jest runs at Airbnb and noticed that on my
MacBook Pro, we can spend over 2 seconds at Jest startup time in
SearchSource getTestPaths. I believe that this will grow as the size
of the codebase increases.
Looking at the call stacks, it appears to be calling micromatch
repeatedly, which calls picomatch, which builds a regex out of the
globs. It seems that the parsing and regex building also triggers the
garbage collector frequently.
Upon testing, I noticed that the globs don't actually change between
these calls, so we can save a bunch of work by making a micromatch
matcher and reusing that function for all of the paths.
micromatch has some logic internally to handle lists of globs that
may include negated globs. A naive approach of just checking if it
matched any of …
> Improve Jest startup time and test runtime, particularly when running with coverage, by caching micromatch and avoiding recreating RegExp instances

- CHANGELOG.md
- packages/jest-mock/src/index.ts
I'm maintaining a utility library that eases module mocking for TS projects: https://github.com/userlike/joke
While trying to fix `@userlike/joke` to be compatible with Jest 26, I've noticed that:
1) `@types/jest` is not needed anymore.
2) Although `fn` and `spyOn` are part of the public API, their return types are not directly exported. They can be indirectly acquired via `ReturnType`, but that causes loss of generic types. I see no reason why those types should not be exported as they are already part of the public contract.
So I modified `jest-mock` package to export `Mock`, `MockInstance` and `SpyInstance` types.
> feat(jest-mock): Export Mock, MockInstance, SpyInstance types

- CHANGELOG.md
- e2e/Utils.ts
- package.json
- packages/jest-snapshot/package.json
- packages/jest-snapshot/src/utils.ts
- packages/jest-util/package.json
- packages/jest-util/src/createDirectory.ts
- scripts/build.js
Builtin fs.mkdir supports recursive option since node v10.
See here https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_mkdirsync_path_option
> chore: replace `make-dir` with `fs.mkdir`

- package.json
Rather than relying on the shell to expand the globs, pass it through to `rimraf`. Also ditches `prebuild` in favor of explicit `&&`.
This is needed for Yarn v2
Green CI
> chore: quote globs in scripts

- CONTRIBUTING.md
* Python 2.7 is deprecated
https://www.python.org/doc/sunset-python-2/
* Python 2.7, 3.5...3.8 are supported
https://github.com/nodejs/node-gyp#installation
https://github.com/nodejs/node-gyp/issues/1687#issuecomment-541471076
> Fix the stale information about node-gyp & python

- CHANGELOG.md
- README.md
- docs/GettingStarted.md
Jest is supported and can be integrated with parcel-bundler for testing of the applications and that was not listed under documentation so added that.
Changes were made inside the documentation part so there were no changes done in the codebase.
However, the installation code for parcel-bundler follows:
```
npm install -g parcel-bundler
or
yarn add parcel-bundler
```
> Adding parcel bundler

- CHANGELOG.md
- packages/expect/src/__tests__/asymmetricMatchers.test.ts
- packages/expect/src/asymmetricMatchers.ts
Adds clauses to `expect`'s `Any.asymmetricMatch()` to handle `Symbol` and `BigInt` analogously to other primitives, i.e., using `typeof` instead of `instanceof`. This makes `expect.any()`'s behavior more consistent across primitive types.
Adds a clause to `Any.asymmetricMatch()` to exclude `null` from `expect.any(Object)`. This makes `expect.any()`'s behavior more consistent with its [documentation](https://jestjs.io/docs/en/expect#expectanyconstructor); `null` is not created with the `Object` constructor, and so should not be matched.
Closes #10179.
Added checks to the list in `asymmetricMatchers.test.ts` `test('Any.asymmetricMatch())'` to cover the changed behavior.
> fix: fix any() for symbols and bigints (#10179)

- CHANGELOG.md
- packages/jest-snapshot/src/__tests__/inline_snapshots.test.ts
- packages/jest-snapshot/src/index.ts
Currently, `jest-snapshot` does not strip added white space characters when comparing inline snapshots for errors. Test will pass on the first run (when the snapshot is written), but will fail in any subsequent runs. This mainly only affects errors with multi-line messages.
Run this code (I'm happy to move this into a test case if required):
```js
it('should pass', () => {
// This will fail when the snapshot is written
expect(() => {
throw new Error(['Line 1', 'Line 2'].join('\n'));
}).toThrowErrorMatchingInlineSnapshot();
});
```
Before the change, the test fails.
It passes afterwards.
> fix: strip added indent in error inline snapshots

- CHANGELOG.md
- packages/jest-console/src/BufferedConsole.ts
- packages/jest-console/src/CustomConsole.ts
- packages/jest-console/src/NullConsole.ts
- packages/jest-console/src/__tests__/CustomConsole.test.ts
- packages/jest-console/src/__tests__/bufferedConsole.test.ts
Provide timeLog to be compatible with node.
console.timeLog was added in node v10.7.0.  Jest gets errors when the function is used.  A [stackoverflow question](https://stackoverflow.com/questions/58961221/console-timelog-not-working-in-jest-tests) was never explained.
Tests were added to the files in the __test__ directory.  A [test run](https://github.com/webstech/jest/actions) was successful.  These are basic jest tests.
> Add console.timeLog function

- scripts/build.js
- scripts/checkCopyrightHeaders.js
- scripts/cleanE2e.js
Part **4 of 4** of continuous effort to get rid of non-inclusive terms like "whitelist" and "blacklist" implying that white = good and black = bad.
n/a
> Replace non-inclusive terms with alternatives in internal scripts

- packages/jest-haste-map/src/ModuleMap.ts
- packages/jest-haste-map/src/__tests__/__snapshots__/index.test.js.snap
Part **3 of 4** of continuous effort to get rid of non-inclusive terms like "whitelist" and "blacklist" implying that white = good and black = bad.
n/a
> Replace non-inclusive "blacklist" term with "exclude" in jest-haste-map

- CHANGELOG.md
- packages/pretty-format/src/__tests__/DOMElement.test.ts
- packages/pretty-format/src/plugins/DOMElement.ts
--added support for properly serializing/printing custom elements by pretty-print
Previously serializing the custom elements would not be handled properly by DOMElement plugin of pretty-print and instead of element's HTML markup all of the custom element properties along with it's constructor name would be printed instead. Now custom elements will be treated in DOMElement plugin as the built-in DOM elements.
Fixes #10226
Unit tests were written so `yarn jest DOMElement.test.ts` (`supports custom elements` test) will test if it's working.
> feat: pretty-print web components properly

- CHANGELOG.md
- e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
- e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
- packages/jest-resolve/src/ModuleNotFoundError.ts
- packages/jest-resolve/src/__mocks__/userResolver.d.ts
- packages/jest-resolve/src/__tests__/resolve.test.ts
- packages/jest-resolve/src/defaultResolver.ts
- packages/jest-resolve/src/index.ts
- packages/jest-resolve/src/isBuiltinModule.ts
Improves the types of `jest-resolve` mainly for #10177, and also cleaning up a few little nits around the place, including a nice little find in `ModuleNotFoundError`.
Run the tests and see if anything breaks 🚂
> chore(jest-resolve): improve types

- CHANGELOG.md
- packages/jest-jasmine2/src/jasmine/Env.ts
- packages/jest-jasmine2/src/jasmine/Spec.ts
- packages/jest-jasmine2/src/jasmine/jasmineLight.ts
- packages/jest-jasmine2/src/jasmineAsyncInstall.ts
- packages/jest-jasmine2/src/jestExpect.ts
- packages/jest-jasmine2/src/queueRunner.ts
- packages/jest-jasmine2/src/types.ts
Improves the types for `jest-jasmine2` to remove banned types (specifically `Function` & `object`) as part of #10177.
The only two files that have banned types (well, type: `Function`) are:
* `errorOnPrivate`: I suspect that `Function` might actually be the "right" type to use here, but more importantly it's usage is for a passthrough parameter to `ErrorWithStack` which comes from `jest-utils`, so the correct type will be whatever replaces the `Function` usage in that package.
* `jasmineAsyncInstall`: I've almost got this typed, but the remaining errors point towards a type being incorrect somewhere that I can't pin down. I think there's a bit of critical understanding that would make it all click that I'm missing.
I've included the work in this commit, so CI will fail, but am happy to …
> chore(jest-jasmine2): remove usage of `Function` type

- CHANGELOG.md
- package.json
- packages/jest-circus/package.json
- packages/jest-console/package.json
- packages/jest-core/package.json
- packages/jest-environment-jsdom/package.json
- packages/jest-environment-node/package.json
- packages/jest-environment/package.json
- packages/jest-fake-timers/package.json
- packages/jest-globals/tsconfig.json
- packages/jest-haste-map/package.json
- packages/jest-jasmine2/package.json
- packages/jest-mock/package.json
- packages/jest-runner/package.json
- packages/jest-serializer/package.json
- packages/jest-types/package.json
- packages/jest-util/package.json
- packages/jest-watcher/package.json
- packages/jest-worker/package.json
- scripts/buildTs.js
- yarn.lock
PnP complains in #9476.
Usages:
https://github.com/facebook/jest/blob/1010b1550c005c204fba279c36292aa361b8f8d8/packages/jest-environment/src/index.ts#L8
https://github.com/facebook/jest/blob/1010b1550c005c204fba279c36292aa361b8f8d8/packages/jest-types/src/Global.ts#L99
Green CI
> Add missing dependency on `@types/node` to all packages

- CHANGELOG.md
- docs/JestObjectAPI.md
This clarifies the [`jest.requireActual(moduleName)`](https://jestjs.io/docs/en/jest-object#jestrequireactualmodulename) example to point out what `moduleName` is being used.
Not applicable -- this is just a docs change; no code change introduced.
> Clarify the jest.requireActual example

- packages/jest-reporters/src/coverage_reporter.ts
Closes #10259 
This changes resolves issue #10259 by adding missing space in terminal output to provide a better user experience.
Execute in test project based on https://github.com/KonH/JestMissingSpaceIssue:
```
nmp t
```
Before that change:
```
Jest: Uncovered count for statements (2)exceeds global threshold (1)
```
After that change:
```
Jest: Uncovered count for statements (2) exceeds global threshold (1)
```
> chore (jest-reporters): add missing space in coverage report message

- CHANGELOG.md
- packages/jest-haste-map/package.json
- packages/jest-haste-map/src/crawlers/__tests__/node.test.js
- packages/jest-haste-map/src/crawlers/node.ts
- yarn.lock
The `-iname` parameter is a non-POSIX extension and may not be supported
by a POSIX compliant find binary. Add a check that the parameter is
supported when determining whether to use the native find binary.
Fixes: https://github.com/facebook/jest/issues/10263
Wrote included test first that failed. Test passes with changes.
> fix: check `find` binary supports the `-iname` parameter

- docs/CLI.md
- docs/WatchPlugins.md
- website/blog/2017-05-06-jest-20-delightful-testing-multi-project-runner.md
- website/versioned_docs/version-22.x/CLI.md
- website/versioned_docs/version-23.x/CLI.md
- website/versioned_docs/version-23.x/WatchPlugins.md
- website/versioned_docs/version-24.x/CLI.md
- website/versioned_docs/version-24.x/WatchPlugins.md
- website/versioned_docs/version-25.x/CLI.md
- website/versioned_docs/version-26.0/CLI.md
It needed replace because markdown interprated `<rootDir>`, `<q>`, `<n>` and `<x>`
as html tags and don't show it.
https://jestjs.io/docs/en/cli#--collectcoveragefromglob should view 
`A glob pattern relative to rootDir matching the files that coverage info needs to be collected from.`
instead of
`A glob pattern relative to matching the files that coverage info needs to be collected from.
`
https://jestjs.io/docs/en/watch-plugins#when-a-conflict-happens and https://jestjs.io/blog/2017/05/06/jest-20-delightful-testing-multi-project-runner#new--improved-testing-apis must have analog behavior
> docs: replace angle brackets to quotes

- CHANGELOG.md
- TestUtils.ts
- docs/Configuration.md
- e2e/__tests__/__snapshots__/showConfig.test.ts.snap
- packages/jest-cli/src/init/__tests__/__snapshots__/init.test.js.snap
- packages/jest-config/src/Defaults.ts
- packages/jest-config/src/Descriptions.ts
- packages/jest-config/src/ValidConfig.ts
- packages/jest-config/src/index.ts
- packages/jest-config/src/normalize.ts
- packages/jest-core/src/lib/__tests__/__snapshots__/log_debug_messages.test.ts.snap
- packages/jest-reporters/src/__tests__/get_result_header.test.js
- packages/jest-reporters/src/get_result_header.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-test-result/src/__tests__/formatTestResults.test.ts
- packages/jest-test-result/src/helpers.ts
- packages/jest-test-result/src/types.ts
- packages/jest-test-sequencer/src/__tests__/test_sequencer.test.js
- packages/jest-test-sequencer/src/index.ts
- packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap
- packages/jest-types/src/Config.ts
Adds `slowTestThreshold` option to configure what is considered to be a long running test. Defaults to 5 seconds since it was the original hardcoded value. Based on suggestions from #7220.
Fixes #7220
I have added two new tests to `get_result_header.test.js`.
> feat: add long test time threshold option

- CHANGELOG.md
- packages/jest-worker/src/base/BaseWorkerPool.ts
- packages/jest-worker/src/index.ts
- packages/jest-worker/src/types.ts
- packages/jest-worker/src/workers/NodeThreadsWorker.ts
In the same way we allow passing `forkOptions` to `child_process`.
https://nodejs.org/api/worker_threads.html#worker_threads_new_worker_filename_options
Green CI
> feat(jest-worker): support passing through ResourceLimits to worker

- CHANGELOG.md
- docs/Configuration.md
- packages/jest-types/src/Config.ts
```javascript
import { Config } from '@jest/types';
const config: Config.InitialOptions = {
coverageReporters: ['html', { subdir: 'dir' }] // typing error
}
```
Typing the config object as Config.InitialOptions resulted in error, because coverageReporters property in Config.InitialOptions was listed as an array of strings.
Since there is only a change in typing precision, there is none.
> chore: update type definitions for coverageReporters

- CHANGELOG.md
- package.json
- packages/jest-core/src/collectHandles.ts
- packages/jest-runtime/package.json
- packages/jest-worker/src/types.ts
- packages/jest-worker/src/workers/NodeThreadsWorker.ts
- yarn.lock
People using "older" `@types/node` will get type errors with the import
Installed a version of `@types/node` that matches our engine requirement. Without the changes here, there's a type error now
> fix(worker): support v12 node typings

- CHANGELOG.md
- packages/jest-cli/src/init/__tests__/init.test.js
- packages/jest-cli/src/init/index.ts
Init with existing config should override the config with correct filename.
Bug
When overriding jest config it creates a file only with extension.
Fix
> fix(jest-cli): use correct filename to override config

- CHANGELOG.md
- packages/jest-haste-map/src/crawlers/__tests__/node.test.js
- packages/jest-haste-map/src/crawlers/node.ts
Fixes #10339
Verified on Windows VM. Not sure how to write a test for this… I'm quite confused by why our windows tests pass without this - I doubt watchman is installed. Maybe they have some other `find`?
> fix: correct check for compatible `find` binary

- CHANGELOG.md
- e2e/__tests__/failureDetailsProperty.test.ts
- e2e/failureDetails-property/__tests__/tests.test.js
- e2e/failureDetails-property/myreporter.js
- e2e/failureDetails-property/package.json
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
- packages/jest-circus/src/utils.ts
- packages/jest-jasmine2/src/reporter.ts
- packages/jest-types/src/Circus.ts
- packages/jest-types/src/TestResult.ts
This is a first pass run at the second part of #8840
I used this to get the details:
```
class MyCustomReporter {
onRunComplete(contexts, results) {
console.log('Custom reporter output:');
console.log(
results.testResults[0].testResults.map(r =>
r.failureDetails.filter(d => !!d).map(d => d.matcherResult)
)
);
}
}
module.exports = MyCustomReporter;
```
This seems to be working nice, but the actual data type is interesting:
It's an array of what seems to be sometimes an array inside another array with just a stracktrace, sometimes it's got matcherResult - I'm sure some of it has good reason (i.e similar to why eslint takes an array of configurations for a rule rather than an object), but I imagine it'd make things easier for @segrey if we could ensure even a little bit of structure.
In …
> Add `failureDetails` property to circus test results

- e2e/__tests__/cliHandlesExactFilenames.test.ts
- e2e/__tests__/dependencyClash.test.ts
- e2e/__tests__/detectOpenHandles.ts
- e2e/__tests__/existentRoots.test.ts
- e2e/__tests__/jestChangedFiles.test.ts
- e2e/__tests__/pnp.test.ts
- e2e/__tests__/showConfig.test.ts
- packages/jest-circus/src/__mocks__/testUtils.ts
- packages/jest-haste-map/src/__tests__/index.test.js
- packages/jest-haste-map/src/__tests__/worker.test.js
- packages/jest-repl/src/__tests__/jest_repl.test.js
- packages/jest-runtime/src/__tests__/runtime_cli.test.js
- packages/test-utils/src/ConditionalTest.ts
- packages/test-utils/src/index.ts
Closes #3121 (mostly) - the only two outstanding are the [yarn pnp](https://github.com/facebook/jest/pull/8094#issuecomment-471220694) test & an open handles test.
See if Windows runs in CI passes after adjusting the relevant tests.
> test: allow more tests to run on windows

- CHANGELOG.md
- packages/jest-worker/package.json
- scripts/buildUtils.js
Fixes #10142
Closes #10145
Change requested to downgrade the minimum required version of node to 10.13 to solve an issue people were experiencing when using the jest-worker as a dependency
> fix(worker): downgrade minimum required node version to 10.13

- CHANGELOG.md
- packages/jest-leak-detector/src/index.ts
See https://github.com/nodejs/node/issues/34636
Green CI
> fix(leak-detector): wait more ticks for GC to run

- CHANGELOG.md
- docs/GlobalAPI.md
- e2e/__tests__/circusConcurrentEach.test.ts
- e2e/__tests__/jasmineAsync.test.ts
- e2e/circus-concurrent/__tests__/concurrent-each.test.js
- e2e/circus-concurrent/__tests__/concurrent-only-each.test.js
- e2e/circus-concurrent/package.json
- e2e/jasmine-async/__tests__/concurrent-each.test.js
- e2e/jasmine-async/__tests__/concurrent-only-each.test.js
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
- packages/jest-each/README.md
- packages/jest-each/src/__tests__/__snapshots__/array.test.ts.snap
- packages/jest-each/src/__tests__/__snapshots__/template.test.ts.snap
- packages/jest-each/src/__tests__/array.test.ts
- packages/jest-each/src/__tests__/index.test.ts
- packages/jest-each/src/__tests__/template.test.ts
- packages/jest-each/src/bind.ts
- packages/jest-each/src/index.ts
- packages/jest-jasmine2/src/__tests__/concurrent.test.ts
- packages/jest-jasmine2/src/each.ts
- packages/jest-jasmine2/src/jasmineAsyncInstall.ts
- packages/jest-types/src/Global.ts
Fixes #8985.
Supported .concurrent in test.each
1) Is this `test.each.concurrent.only` valid?
2) Is this `test.concurrent.each` valid?
3) There does not seem to be tests for concurrent both in `jest-jasmine` and `jest-circus`, tests in `jest-circus` are using `execa` for running the tests I can't seem to run a test which has `test.concurrent`
- Have updated types in Global.ts to accommodate `each.concurrent`
- Have created an additional method in `jest-each` `bindConcurrent`
- Currently there is code duplication in `jest-each`, will remove it raising as draft PR for now to get clarifications
- Have used `bindConcurrent` in `jest-jasmine` and `jest-circus`
```js
test.each.concurrent([1,2,3])('Name', (num)=> {
// This function is executed concurrently with different `num`!
});
```
Have …
> feat: support `concurrent` in Jest Each

- CHANGELOG.md
- docs/Configuration.md
- e2e/__tests__/__snapshots__/showConfig.test.ts.snap
- e2e/__tests__/showConfig.test.ts
- packages/jest-cli/src/init/__tests__/__snapshots__/init.test.js.snap
- packages/jest-config/src/Defaults.ts
> Add `.pnp.js` to `transformIgnorePatterns` defaults

- CHANGELOG.md
- packages/pretty-format/src/__tests__/DOMElement.test.ts
- packages/pretty-format/src/plugins/DOMElement.ts
See https://app.circleci.com/pipelines/github/storybookjs/storybook/12354/workflows/e8752f72-9082-42c5-87b3-d07ea7053a95/jobs/249451
Unit test added that failed without these changes. Applying the changes to storybook also fixes the test error there
> fix(pretty-format): handle `tagName` not being a string

- CHANGELOG.md
- docs/Configuration.md
- packages/jest-resolve/src/__tests__/resolve.test.ts
- packages/jest-resolve/src/defaultResolver.ts
Forwards option `packageFilter` to `resolve`. This is useful in case a custom resolver wants to use it. The best example is #2702 (in particular, https://github.com/facebook/jest/issues/2702#issuecomment-671947783)
Fixes #2702
Write a custom resolver like
```
module.exports = ( request, options ) => {
return options.defaultResolver( request, {
...options,
...{
packageFilter: ( pkg ) => {
return {
...pkg,
main: pkg.module || pkg.main,
};
},
},
} );
};
```
Then, in any jest test, when importing package `X`, it will try to load it from the field `module` first, with fallback to `main` if `module` doesn't exist.
> [jest-resolve] Add support for `packageFilter` for custom resolvers

- CHANGELOG.md
- packages/jest-reporters/package.json
- yarn.lock
There was an issue with Linux systems and node-notifier dependency (https://github.com/facebook/jest/issues/9701). This PR bumps node-notifier to v8.0.0 which should fix these issues. Should get the people experiencing issues to confirm.
cc @millette @mpareja
Fixes #9701
Shouldn't be any changes other than patch fix for Jest usage. Timeout for Linux systems will change, but no API changes. Types definitions on definitely typed aren't updated, but it is inconsequential for this PR as I see it.
> fix: Bumps node-notifier to v8.0.0

- CHANGELOG.md
- packages/jest-snapshot/src/__tests__/utils.test.ts
- packages/jest-snapshot/src/utils.ts
> fix: correctly handle arrays in snapshot deep merge

- .circleci/config.yml
Current one doesn't work due to looking for the wrong directory. Ideally we'd run `yarn config get cacheFolder` in order to get the directory rather than hard coding it, but I don't think that's possible.
Also make the cache be keyed only by checksum of the lockfile, not the branch name
I'll push another commit removing the debugging and verify it's a cache hit instead of a miss
> chore: fix yarn caching on circle ci

- docs/MongoDB.md
Removed unnecessary symbol on MongoDB guide
> docs: remove unnecessary symbol from mongodb guide

- CHANGELOG.md
- docs/CLI.md
- docs/Configuration.md
- e2e/__tests__/__snapshots__/injectGlobals.test.ts.snap
- e2e/__tests__/__snapshots__/showConfig.test.ts.snap
- e2e/__tests__/injectGlobals.test.ts
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
- packages/jest-circus/src/legacy-code-todo-rewrite/jestExpect.ts
- packages/jest-cli/src/cli/args.ts
- packages/jest-config/src/Defaults.ts
- packages/jest-config/src/ValidConfig.ts
- packages/jest-config/src/index.ts
- packages/jest-config/src/normalize.ts
- packages/jest-environment/src/index.ts
- packages/jest-runtime/src/index.ts
- packages/jest-types/src/Config.ts
> feat: add new `injectGlobals` config and CLI option to disable injecting global variables into the runtime 

- CHANGELOG.md
- packages/jest-types/src/Global.ts
- test-types/top-level-globals.test.ts
Fixes #10066 
Added a new type test suite for the @jest/globals to ensure lifecycle hooks are not typed as `HookFn` that could return `Promise`, but are at least functions that return `void`.
> Fix lifecycle hook function types

- packages/jest-circus/package.json
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
- packages/jest-config/src/Deprecated.ts
- packages/jest-snapshot/package.json
- packages/jest-snapshot/src/State.ts
- packages/jest-snapshot/src/inline_snapshots.ts
- packages/jest-snapshot/src/types.ts
- packages/jest-validate/src/exampleConfig.ts
- packages/jest-validate/src/index.ts
- packages/jest-validate/src/types.ts
- packages/jest-validate/src/validateCLIOptions.ts
- yarn.lock
Relates to #10177
See if CI passes
> choreØ eplace function types

- packages/jest-snapshot/src/State.ts
- packages/jest-snapshot/src/inline_snapshots.ts
Less custom types and `any` is a good thing
Green CI
> chore(jest-snapshot): type prettier usage properly

- .eslintrc.js
- e2e/coverage-remapping/covered.ts
- e2e/focused-tests/__tests__/tests.js
- e2e/jasmine-async/__tests__/promiseFit.test.js
- packages/jest-cli/src/init/__tests__/init.test.js
- packages/test-utils/src/ConditionalTest.ts
Copied from https://github.com/facebook/jest/pull/10438/files#diff-e4403a877d80de653400d88d85e4801aR205 but also removed now unneeded `enable`s
Green CI
> chore: add `allowWholeFile` to `disable-enable-pair` eslint rule

- CHANGELOG.md
- e2e/__tests__/__snapshots__/consoleAfterTeardown.test.ts.snap
- packages/jest-console/src/BufferedConsole.ts
- packages/jest-console/src/CustomConsole.ts
- packages/jest-console/src/__tests__/CustomConsole.test.ts
- packages/jest-console/src/__tests__/bufferedConsole.test.ts
Add Console to `CustomConsole` and `BufferedConsole`
Fixes #10282
Tests have been added
cc: @jeysal
> feat: Add Console to custom console object

- packages/jest-circus/src/types.ts
- packages/jest-cli/package.json
- packages/jest-jasmine2/src/types.ts
- packages/jest-repl/package.json
- packages/jest-resolve/src/defaultResolver.ts
- packages/jest-runtime/package.json
- packages/jest-snapshot/src/inline_snapshots.ts
- packages/pretty-format/src/__tests__/setPrettyPrint.ts
- yarn.lock
Mostly for the prettier types so we can delete a tiny bit of types on our side
Green CI
> chore: bump deps

- CHANGELOG.md
- packages/jest-runner/src/runTest.ts
- packages/jest-runtime/src/__mocks__/createRuntime.js
- packages/jest-runtime/src/__tests__/Runtime-statics.test.js
- packages/jest-runtime/src/cli/index.ts
Useful for people with custom runtimes (a la https://github.com/facebook/jest/issues/10540#issuecomment-696263594)
Green CI
> fix(runner): handle module loaders with default exports

- docs/GlobalAPI.md
- website/versioned_docs/version-26.4/GlobalAPI.md
One of the links in the documentation has a syntax error:
[Link to wonky docs](https://jestjs.io/docs/en/api#testconcurrentname-fn-timeout)
Screenshot from locally hosted docs after the fix:
> docs: fix markdown link syntax

- docs/Configuration.md
- website/versioned_docs/version-22.x/Configuration.md
- website/versioned_docs/version-23.x/Configuration.md
- website/versioned_docs/version-24.x/Configuration.md
- website/versioned_docs/version-25.x/Configuration.md
- website/versioned_docs/version-26.0/Configuration.md
- website/versioned_docs/version-26.2/Configuration.md
- website/versioned_docs/version-26.4/Configuration.md
Includes the `--testFailureExitCode` config parameter in the documentation. This parameter was added in the 21.0.0 release by #4067 but wasn't included in the release notes or added to the documentation.
From a motivation perspective, at my company we're incorporating a variety of small `create-react-app`'s into a much larger product that has a handrolled continuous integration system. It considers a non-zero exit code of a testing tool to be a build environment failure and will abort subsequent steps (it scoops up the test reports and process them to determine test failures). Given Jest's default behaviour of returning `1` for both test failures and tool failures I was going to need to find a way to distinguish between a test and a tool failure. I tried searching for this exact …
> docs: Document `--testFailureExitCode`

- CHANGELOG.md
- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/__tests__/nativeEsm.test.ts
- packages/jest-resolve/package.json
- packages/jest-resolve/src/shouldLoadAsEsm.ts
- yarn.lock
Ref https://packagephobia.com/result?p=read-pkg-up https://packagephobia.com/result?p=escalade
Read-pkg-up package is quite big and have a lot of dependencies.
It also handles cases not necessary for jest. Beautiful JSON parsing
errors are not relevant and can be replaced with builtin JSON.parse.
Not sure about this. Looks like es modules support was not covered by tests.
> refactor(resolve): replace read-pkg-up with escalade

- .eslintplugin/index.js
- .eslintrc.js
- packages/expect/src/index.ts
- packages/jest-fake-timers/src/legacyFakeTimers.ts
- packages/jest-jasmine2/src/jasmine/Env.ts
- packages/jest-jasmine2/src/jasmine/ReportDispatcher.ts
- packages/jest-jasmine2/src/jasmine/Spec.ts
- packages/jest-jasmine2/src/jasmine/SpyStrategy.ts
- packages/jest-jasmine2/src/jasmine/Suite.ts
- packages/jest-jasmine2/src/jasmine/createSpy.ts
- packages/jest-jasmine2/src/jasmine/jasmineLight.ts
- packages/jest-jasmine2/src/jestExpect.ts
- packages/jest-mock/src/__tests__/index.test.ts
- packages/jest-mock/src/index.ts
- packages/jest-resolve/src/index.ts
- packages/pretty-format/src/__tests__/Immutable.test.ts
- packages/pretty-format/src/__tests__/prettyFormat.test.ts
See [this comment](https://github.com/facebook/jest/pull/10438#issuecomment-691640145).
> chore: duplicate eslint rules locally to allow warning

- CHANGELOG.md
- packages/jest-environment-jsdom/package.json
- yarn.lock
Fixes https://github.com/facebook/jest/issues/10489
Jsdom 16.2.2 causes "Cannot read property 'some' of undefined" error.
Ran `yarn test` and everything passed.
> chore(deps): upgrade jsdom to 16.4.0

- CHANGELOG.md
- e2e/__tests__/__snapshots__/consoleLogOutputWhenRunInBand.test.ts.snap
- e2e/__tests__/__snapshots__/globals.test.ts.snap
- e2e/__tests__/consoleLogOutputWhenRunInBand.test.ts
- e2e/__tests__/errorOnDeprecated.test.ts
- e2e/__tests__/failures.test.ts
- packages/jest-reporters/src/coverage_reporter.ts
- packages/jest-runtime/src/index.ts
- packages/jest-test-result/src/index.ts
- packages/jest-test-result/src/types.ts
- packages/jest-types/src/Transform.ts
See https://github.com/nodejs/node/issues/35375 and https://github.com/facebook/jest/issues/9457#issuecomment-702970726
Green CI
> chore: drop usage of `compileFunction`

- CHANGELOG.md
- packages/jest-mock/src/index.ts
- test-types/top-level-jest-namespace.test.ts
When calling `mockResolvedValue` (-`Once`), the argument should be
the expected return value unwrapped from its Promise. Likewise,
when mocking a rejected value, the passed argument needs not
necessarily be of the same type as the expected successful return
value.
Without this change, the following code will cause TypeScript to complain:
```typescript
const mockFetch = jest.fn(window.fetch).mockResolvedValue(new Response());
```
```
Argument of type 'Response' is not assignable to parameter of type 'Promise<Response>'.
Type 'Response' is missing the following properties from type 'Promise<Response>': then, catch, [Symbol.toStringTag], finally
```
That error will disappear with this PR.
> Fix type definitions for promises

- CHANGELOG.md
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
- packages/jest-circus/src/legacy-code-todo-rewrite/jestExpect.ts
- packages/jest-types/src/Circus.ts
- packages/jest-util/src/globsToMatcher.ts
Fix for https://github.com/facebook/jest/pull/10484#issuecomment-703761828
In addition to restoring time when globals are added, I've also added a property to the `setup` event that comes with the globals. That way consumers don't have to care about `this.globals.*`, which would also be unset if the end user use `injectGlobals: false`.
/cc @noomorph
Verified locally that globals are set during `setup`
> fix(circus): make sure to install globals before emitting `setup` event

- CHANGELOG.md
- packages/jest-cli/package.json
- packages/jest-repl/package.json
- packages/jest-reporters/package.json
- packages/jest-resolve/package.json
- packages/jest-resolve/src/shouldLoadAsEsm.ts
- packages/jest-runtime/package.json
- yarn.lock
Fixes #10596
This reverts commit 0a9e77d5e75adc87f8d7497ec30472c661c6fc11.
Let's land it for Jest 27 instead
🤷
> fix: revert usage of Escalade and yargs@16 as they breaks Node 13

- CHANGELOG.md
- packages/jest-validate/src/__tests__/__snapshots__/validateCLIOptions.test.js.snap
- packages/jest-validate/src/__tests__/validateCLIOptions.test.js
- packages/jest-validate/src/validateCLIOptions.ts
Resolves #9007 
Currently running CLI command with an unrecognized parameter of length 1 results in a message containing `Did you mean "$0"?`
This fix adds a check to make a suggestion only when the unrecognized cli param length is greater than 1, so that `"$0"` is not suggested to the user as a possible param
Added relevant tests to `validateCLIOptions.test.ts`
> Show suggestion only when unrecognized cli param is longer than 1 character

- CHANGELOG.md
- packages/jest-validate/src/__tests__/validateCLIOptions.test.js
- packages/jest-validate/src/validateCLIOptions.ts
Resolves #8889 
Currently running `jest --testURL "https://localhost"` fails with `--testURL` being treated as `Unrecognized CLI Parameter`.
> fix: validate `testURL` as CLI option

- packages/jest-reporters/package.json
- yarn.lock
https://github.com/istanbuljs/v8-to-istanbul/releases/tag/v6.0.0
Green CI
> chore: bump v8-to-istanbul

- docs/ECMAScriptModules.md
- website/sidebars.json
- website/versioned_docs/version-26.0/ECMAScriptModules.md
- website/versioned_sidebars/version-26.0-sidebars.json
Ref https://github.com/facebook/jest/issues/9430#issuecomment-693352478
I haven't written too much, but it's _something_. Added it to all `jest@26` versioned docs.
🤷
> chore: add info about ES modules to docs

- CHANGELOG.md
- packages/jest-runtime/src/__tests__/runtime_require_module.test.js
- packages/jest-runtime/src/__tests__/test_root/RegularModule.js
- packages/jest-runtime/src/index.ts
https://nodejs.org/docs/latest/api/modules.html#modules_module_path
Unit test updated
> fix: add missing `module.path` field to modules

- CHANGELOG.md
- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/native-esm/__tests__/native-esm.test.js
- e2e/native-esm/fromEsm.cjs
- packages/jest-runtime/src/index.ts
Since we no longer use `compileFunction`, we can now implement this.
Test added
> feat: add support for dynamic imports in CJS

- CHANGELOG.md
- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/native-esm/__tests__/native-esm.test.js
- packages/jest-runtime/src/index.ts
> fix(esm): evaluate node core modules on dynamic import

- CHANGELOG.md
- e2e/__tests__/requireMainResetModules.test.ts
- e2e/require-main-reset-modules/__tests__/callJestResetModules.test.js
- e2e/require-main-reset-modules/__tests__/index.test.js
- e2e/require-main-reset-modules/index.js
- e2e/require-main-reset-modules/package.json
- packages/jest-runtime/src/__tests__/runtime_require_module.test.js
- packages/jest-runtime/src/index.ts
Closes #10625.
`require.main` is `undefined` on using the `--resetModules` flag. This PR aims to resolve this issue.
E2E tests added
> fix: `require.main` is undefined on using `jest.resetModules`

- CHANGELOG.md
- CONTRIBUTING.md
- website/README.md
Supercedes: #10191
Fixes: #9808
When attempting to run `yarn start` for the first time after following the install steps I got this error message:
```
Error: Cannot find module '/Users/stdavis/Documents/Projects/jest/website/backers.json'
```
This PR adds the required command to fix this error.
I've run `node fetchSupporters.js` and now the website behaves normally without errors.
> Add step for fetching backers.json to website install steps

- CHANGELOG.md
- packages/jest-types/src/Config.ts
`@jest/types` config in `Config.ts` has missing value(s) for `timers` in two variables `InitialOptions` and `DefaultOptions`.
----
Closes #10609
> refactor: add missing options for timers on config.ts file

- website/pages/en/index.js
- website/static/css/jest.css
Switches the open collective info from showing logos to not, there's a trade-off here where we could have continued to make a more complex filter for what we show. But TBH, it's not really something we want to be actively keeping an eye on. So, rather than play whack-a-mole on the sponsors, this PR drops is completely.
> chore(website): minor CSS improvements to logos

- CHANGELOG.md
- packages/jest-validate/README.md
- packages/jest-validate/src/__tests__/validate.test.ts
- packages/jest-validate/src/defaultConfig.ts
- packages/jest-validate/src/exampleConfig.ts
- packages/jest-validate/src/types.ts
- packages/jest-validate/src/validate.ts
Clone of #10236 which has to be closed because the original repo was deleted by me.
Part of #10235.
* Adds support for `recursiveDenylist` option as an alternative to `recursiveBlacklist` in `jest-validate`. Does NOT remove `recursiveBlacklist` option. It will continue to work, unless overwritten with `recursiveDenylist`, to which I've given the priority.
* Updates documentation not to mention `recursiveBlacklist` (in favor of the newly added option).
* ~~Changes internal calls to `validate()` to use new config **(Maintainers: I'm not sure if that's a good idea - can you please advise? Should we expect `jest-config`, say, v26.2 work with other dependencies @ v26.1 at all times? Shall I roll that back and add it as a TODO to #10235 instead? TIA)**~~
Part of continuous effort to get rid of …
> Add support for `recursiveDenylist` option as an alternative to `recursiveBlacklist`

- CHANGELOG.md
- packages/jest-mock/src/__tests__/index.test.ts
- packages/jest-mock/src/index.ts
In TypeScript `3.9.x`, module "re-export" is done using readonly accessor.
It breaks all tests written using `jest.spyOn` mocks.
A solution is to automatically mock methods that are wrapped in getters.
```typescript
/**********************
* module-a
**********************/
// file: lib/feature.ts
export function myFunction(): boolean {
return true;
}
// file: index.ts
export * from "./lib/feature.ts"
/**********************
* submodule
**********************/
// file: lib/subfeature.ts
import * as mod from "module-a";
export function mySubFunction(): boolean {
return mod.myFunction();
}
// file: lib/subfeature.spec.ts
import * as submod from "./subfeature";
import * as mod from "module-a";
describe("mySubFunction", () => {
let spy: jest.SpyInstance;
beforeEach(() => { spy = …
```
> fix(mock): allow to mock methods in getters

- CHANGELOG.md
- packages/expect/src/__tests__/asymmetricMatchers.test.ts
- packages/expect/src/asymmetricMatchers.ts
Addressing bug report facebook/jest#10462. According to the docs, ```objectContaining``` should apply in a recursive sense, however it doesn't seem to do this currently.
This change will make ```objectContaining``` work recursively into sub-objects.
Included a unit test for the new behavior, and confirmed that all older tests still pass.
> fix(expect): `objectContaining` should recurse into sub-objects

- CHANGELOG.md
- packages/jest-message-util/src/index.ts
- packages/jest-worker/src/workers/__tests__/ChildProcessWorker.test.js
- packages/jest-worker/src/workers/__tests__/NodeThreadsWorker.test.js
Tried out today's nightly and we had a few failures. These changes makes the test suite pass on Node 15
Green CI
> chore: update code to pass tests on Node 15

- docs/ExpectAPI.md
- website/versioned_docs/version-26.2/ExpectAPI.md
Fix typo in Custom Matchers API.
Build and view docs using development server by following the [instructions](https://github.com/facebook/jest/blob/f4d6a18bd4ae33ea59b16a1e6ce6ccca2da488dd/CONTRIBUTING.md#additional-workflow-for-any-changes-made-to-website-or-docs).
> docs: Fix typo in Custom Matchers API

- .circleci/config.yml
- .github/workflows/nodejs.yml
> build: run tests on node v15

- CHANGELOG.md
- e2e/__tests__/onlyFailuresNonWatch.test.ts
- packages/jest-cli/src/__tests__/cli/args.test.ts
- packages/jest-cli/src/cli/args.ts
- packages/jest-config/src/ValidConfig.ts
- packages/jest-config/src/normalize.ts
- packages/jest-core/src/__tests__/__snapshots__/getNoTestsFoundMessage.test.js.snap
- packages/jest-core/src/getNoTestFoundFailed.ts
- packages/jest-core/src/getNoTestsFoundMessage.ts
- packages/jest-core/src/runJest.ts
- packages/jest-test-sequencer/src/__tests__/test_sequencer.test.js
- packages/jest-test-sequencer/src/index.ts
- packages/jest-types/src/Config.ts
Fixes #6470 .
Previously, upon passing the `--onlyFailures` flag in non-watch mode, all the tests were run instead of just the failed tests.
This PR fixes the bug. Now, the `--onlyFailures` flag will work as expected in non-watch mode.
> Fix --onlyfailures flag to work in non-watch mode

- CHANGELOG.md
- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/native-esm/__tests__/native-esm.test.js
- e2e/native-esm/namedExport.cjs
- packages/jest-runtime/package.json
- packages/jest-runtime/src/index.ts
- yarn.lock
See https://github.com/facebook/jest/issues/9430#issuecomment-712944270
Test added
> feat: support named exports from CJS as named ESM imports

- docs/ExpectAPI.md
- website/versioned_docs/version-22.x/ExpectAPI.md
- website/versioned_docs/version-23.x/ExpectAPI.md
- website/versioned_docs/version-24.x/ExpectAPI.md
- website/versioned_docs/version-25.x/ExpectAPI.md
- website/versioned_docs/version-26.2/ExpectAPI.md
to make function sign consistent with other functions sign like
`expect.not.stringMatching(string | regexp)`
or
`expect.stringMatching(string | regexp)`
closes #10664
closes #10665
closes #10666
closes #10667
closes #10668
> more consistent function sign

- packages/jest-runner/src/index.ts
The documentation says when you use `--detectOpenHandles` `--runInBand` is implied, I'm assuming there is no need to add it to the text then, (I might be wrong).
> fix: do not mention implied `runInBand` on `detectOpenHandles` warning

- CHANGELOG.md
- packages/expect/src/__tests__/asymmetricMatchers.test.ts
- packages/expect/src/asymmetricMatchers.ts
Closes #10689. PR #10508 replaced the sample's properties with asymmetric matchers to facilitate recursion. This PR instead constructs asymmetric matchers each time the base matcher is invoked, avoiding the need to mutate the sample.
Added a test case asserting that the sample is not mutated.
> fix: don't mutate the sample in expect.objectContaining()

- .eslintrc.js
- docs/SnapshotTesting.md
- docs/TutorialReact.md
- docs/TutorialReactNative.md
- e2e/babel-plugin-jest-hoist/__tests__/integration.test.js
- fixtures/parser_tests.js
- packages/jest-validate/README.md
- website/versioned_docs/version-22.x/SnapshotTesting.md
- website/versioned_docs/version-22.x/TutorialReact.md
- website/versioned_docs/version-22.x/TutorialReactNative.md
- website/versioned_docs/version-23.x/SnapshotTesting.md
- website/versioned_docs/version-23.x/TutorialReact.md
- website/versioned_docs/version-24.x/TutorialReact.md
- website/versioned_docs/version-25.x/TutorialReactNative.md
> chore: use `typescript-eslint` to parse all files

- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/__tests__/nativeEsm.test.ts
- e2e/native-esm/__tests__/native-esm-tla.test.js
It's nice to have a test for it
Green CI
> chore: add test verifying top-level await works

- babel.config.js
- package.json
- packages/expect/src/index.ts
- packages/jest-haste-map/src/index.ts
- packages/jest-jasmine2/src/index.ts
- packages/jest-mock/src/index.ts
- packages/jest-resolve-dependencies/src/index.ts
- packages/jest-resolve/src/index.ts
- packages/jest-runner/src/index.ts
- packages/jest-runtime/src/index.ts
- packages/jest-snapshot/src/index.ts
- packages/pretty-format/src/index.ts
- yarn.lock
https://babeljs.io/docs/en/babel-plugin-transform-typescript#impartial-namespace-support
I tested locally by checking in `build/` and there is zero diff in the output, in neither `d.ts` files or `js` files. Beyond that, green CI should verify
> chore: remove custom babel plugin for stripping namespaces

- package.json
- yarn.lock
To unblock #10399.
We need to ensure that `@types/jest` does not depend on anything in our repo, as they are not yet built. Forcing it to load v25 deps negates this issue as it'll get the stuff it needs from its own `node_modules`.
Green CI
> chore: bump @types/jest

- CHANGELOG.md
- examples/typescript/__tests__/calc.test.ts
- examples/typescript/__tests__/sub-test.ts
- examples/typescript/__tests__/sum-test.ts
- examples/typescript/calc.ts
- examples/typescript/memory.ts
There have been some updates to Jest's separate `@types/jest` (started here I think - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37173) that are very useful and I thought I'd update the TypeScript example to show how they can be used.
~~- [x] Remove `@types/jest` from root `package.json` (not needed I think and child packages state `@types/jest: "*"` anyway~~
~~- [x] Update `@types/jest` in `yarn.lock` to 24.9.0 that includes `MockedFunction` and `MockedClass`~~
> Update TypeScript example to show use of newer Jest types

- docs/UsingMatchers.md
- website/versioned_docs/version-22.x/UsingMatchers.md
It looks like the documentation no longer mentions that the function needs to be wrapped otherwise the assertion will fail.
> Add a note to the Exceptions section

- CHANGELOG.md
- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/native-esm/__tests__/native-esm.test.js
- packages/jest-runtime/src/index.ts
Not sure if a `startsWith` is the best, but it works 🤷 
Test added
> chore: handle file URLs in dynamic imports

- CHANGELOG.md
- packages/jest-transform/src/enhanceUnexpectedTokenMessage.ts
It's getting to the point where it's usable enough that we can point people to it. The docs are pretty explicit about its experimental nature, so I think this is fine.
> chore: link to ESM docs on syntax error

- CHANGELOG.md
- e2e/__tests__/__snapshots__/transform.test.ts.snap
- packages/babel-jest/src/index.ts
- packages/jest-runtime/src/index.ts
- packages/jest-transform/src/index.ts
- packages/jest-transform/src/types.ts
Extracted from #10750
Green CI
> chore: support more caller options in babel-jest

- CHANGELOG.md
- e2e/__tests__/extraGlobals.test.ts
- packages/jest-runtime/src/index.ts
Fixes #10754
Added a regression e2e test
> fix: properly inject `extraGlobals` into the environment

- CHANGELOG.md
- packages/babel-plugin-jest-hoist/package.json
- packages/babel-plugin-jest-hoist/src/__tests__/__snapshots__/hoistPlugin.test.ts.snap
- packages/babel-plugin-jest-hoist/src/__tests__/hoistPlugin.test.ts
- packages/babel-plugin-jest-hoist/src/index.ts
- yarn.lock
Fixes #10690 (eventually, hopefully, possibly)
~Note that I don't want this test to actually land. It's a very brute force way of illustrating the bug, but a bad test to add to ensure we don't have regressions in the future~ pushed a better test now
> fix(hoist-plugin): hoist pure constants to support experimental JSX transform in mocks

- packages/jest-runtime/package.json
- packages/jest-runtime/src/index.ts
- yarn.lock
New version comes with TS definitions
Green CI
> chore: update cjs-module-lexer

- CHANGELOG.md
- packages/babel-jest/src/__tests__/index.ts
- packages/expect/src/__tests__/asymmetricMatchers.test.ts
- packages/expect/src/asymmetricMatchers.ts
Fixes #10716
Green CI. Kept some of the tests added later for the mutation regression
> Revert "fix(expect): `objectContaining` should recurse into sub-objects (#10508)"

- .azure-pipelines-steps.yml
- .circleci/config.yml
- .circleci/website.sh
- .github/workflows/nodejs.yml
- e2e/Utils.ts
- e2e/__tests__/asyncRegenerator.test.ts
- e2e/__tests__/babelPluginJestHoist.test.ts
- e2e/__tests__/chaiAssertionLibrary.ts
- e2e/__tests__/console.test.ts
- e2e/__tests__/coverageHandlebars.test.ts
- e2e/__tests__/coverageRemapping.test.ts
- e2e/__tests__/coverageReport.test.ts
- e2e/__tests__/coverageTransformInstrumented.test.ts
- e2e/__tests__/expectAsyncMatcher.test.ts
- e2e/__tests__/failures.test.ts
- e2e/__tests__/globalSetup.test.ts
- e2e/__tests__/globalTeardown.test.ts
- e2e/__tests__/nativeAsyncMock.test.ts
- e2e/__tests__/pnp.test.ts
- e2e/__tests__/stackTraceSourceMaps.test.ts
- e2e/__tests__/stackTraceSourceMapsWithCoverage.test.ts
- e2e/__tests__/transform.test.ts
- e2e/__tests__/typescriptCoverage.test.ts
Good practice on CI. Also snuck in using node 14 on azure and node 14 for the code coverage run on circle
Green CI
> chore: run yarn with `immutable` flag

- CHANGELOG.md
- packages/jest-resolve-dependencies/src/__tests__/dependency_resolver.test.ts
- packages/jest-resolve-dependencies/src/index.ts
This fixes https://github.com/facebook/jest/issues/10771, a regression caused by https://github.com/facebook/jest/pull/10713
I've basically wrapped the `getMockModule` call with a `try/catch`, similarly to how it's done in the bit above.
Added a unit test to make sure dependency resolution continues if a mock dependency can't be found.
> Don't throw an error if mock dependency can't be found

- CHANGELOG.md
- packages/jest-transform/src/enhanceUnexpectedTokenMessage.ts
#6275 added this helpful error message, but it doesn't trigger on e.g. TLA.
Master: 
While with this PR the enhancement triggers
See above
> chore: show enhanced syntax error for all syntax errors

- CHANGELOG.md
- docs/Configuration.md
- e2e/__tests__/__snapshots__/showConfig.test.ts.snap
- e2e/__tests__/config.test.ts
- e2e/dom-diffing/package.json
- examples/angular/jest.config.js
- examples/jquery/package.json
- examples/react-testing-library/package.json
- examples/react/package.json
- examples/typescript/package.json
- jest.config.js
- packages/jest-cli/src/init/__tests__/__snapshots__/init.test.js.snap
- packages/jest-cli/src/init/__tests__/init.test.js
- packages/jest-cli/src/init/generateConfigFile.ts
- packages/jest-config/src/Defaults.ts
- website/versioned_docs/version-22.x/Configuration.md
- website/versioned_docs/version-23.x/Configuration.md
- website/versioned_docs/version-24.x/Configuration.md
- website/versioned_docs/version-25.x/Configuration.md
- website/versioned_docs/version-26.0/Configuration.md
- website/versioned_docs/version-26.2/Configuration.md
- website/versioned_docs/version-26.4/Configuration.md
- website/versioned_docs/version-26.5/Configuration.md
- website/versioned_docs/version-26.6/Configuration.md
> chore: default to node test env rather than browser

- CHANGELOG.md
- packages/jest-reporters/src/generateEmptyCoverage.ts
- packages/jest-transform/src/ScriptTransformer.ts
- packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.ts.snap
- packages/jest-transform/src/__tests__/script_transformer.test.ts
What it says on the tin - to make it less spaghetti to pass options internally in the class. Especially after #10752 adds 2 more fields
Green CI
> chore(transform): refactor API to pass an options bag around rather than multiple boolean options

- CHANGELOG.md
- e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
- e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
- packages/jest-config/src/__tests__/normalize.test.js
- packages/jest-config/src/normalize.ts
- packages/jest-config/src/utils.ts
- packages/jest-core/src/watch.ts
- packages/jest-reporters/src/types.ts
- packages/jest-resolve-dependencies/src/__tests__/dependency_resolver.test.ts
- packages/jest-resolve-dependencies/src/index.ts
- packages/jest-resolve/src/__tests__/resolve.test.ts
- packages/jest-resolve/src/defaultResolver.ts
- packages/jest-resolve/src/index.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-runner/src/testWorker.ts
- packages/jest-runner/src/types.ts
- packages/jest-runtime/src/index.ts
- packages/jest-runtime/src/types.ts
> chore: migrate jest-resolve to ESM

- CHANGELOG.md
- e2e/__tests__/global-mutation.test.ts
- packages/jest-environment-jsdom/src/index.ts
- packages/jest-environment/src/index.ts
- packages/jest-runtime/src/__tests__/__snapshots__/runtime_wrap.js.snap
- packages/jest-runtime/src/index.ts
It's not part of the module wrapper, so we shouldn't inject it: https://nodejs.org/api/modules.html#modules_the_module_wrapper
Fixes #10565.
EDIT: Huh, seems like this blows up for tests I didn't bother to run locally. Specifically, it explodes for tests using `global` in JSDOM. I'm thinking we can just add it to the JSDOM env and remove in a future version. Might be considered a breaking change, though?
Test added
> fix: do not inject `global` variable into module wrapper

- CHANGELOG.md
- e2e/__tests__/consoleAfterTeardown.test.ts
- packages/jest-runner/src/runTest.ts
Resolve https://github.com/facebook/jest/issues/10715
Green CI
> feat(jest-runner): set exit code to 1 if test logs after teardown

- CHANGELOG.md
- packages/jest-cli/package.json
- packages/jest-repl/package.json
- packages/jest-resolve/package.json
- packages/jest-resolve/src/shouldLoadAsEsm.ts
- packages/jest-runtime/package.json
- yarn.lock
> fix(resolve): use escalade to find package.json

- CHANGELOG.md
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
- packages/jest-core/src/__tests__/SearchSource.test.ts
- packages/jest-core/src/__tests__/watchFileChanges.test.ts
- packages/jest-core/src/cli/index.ts
- packages/jest-core/src/lib/createContext.ts
- packages/jest-jasmine2/src/index.ts
- packages/jest-repl/src/cli/args.ts
- packages/jest-repl/src/cli/index.ts
- packages/jest-resolve-dependencies/src/__tests__/dependency_resolver.test.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-runner/src/testWorker.ts
- packages/jest-runner/src/types.ts
- packages/jest-runtime/src/cli/index.ts
- packages/jest-runtime/src/index.ts
A start - the `namespace` stuff is really annoying 😛 
Green CI
> chore: convert jest-runtime to ESM

- CHANGELOG.md
- docs/JestObjectAPI.md
- docs/TimerMocks.md
- packages/jest-environment/src/index.ts
- packages/jest-haste-map/src/__tests__/index.test.js
- packages/jest-runtime/src/__tests__/runtime_mock.test.js
- packages/jest-runtime/src/__tests__/runtime_require_module.test.js
- packages/jest-runtime/src/__tests__/runtime_require_module_or_mock_transitive_deps.test.js
- packages/jest-runtime/src/index.ts
- packages/jest-transform/src/__tests__/script_transformer.test.ts
- test-types/top-level-jest-namespace.test.ts
Been deprecated for a long time, let's remove them
Green CI
> fix: remove deprecated functions from the jest object

- docs/Configuration.md
- website/versioned_docs/version-22.x/Configuration.md
- website/versioned_docs/version-23.x/Configuration.md
- website/versioned_docs/version-24.x/Configuration.md
- website/versioned_docs/version-25.x/Configuration.md
- website/versioned_docs/version-26.0/Configuration.md
- website/versioned_docs/version-26.2/Configuration.md
- website/versioned_docs/version-26.4/Configuration.md
- website/versioned_docs/version-26.5/Configuration.md
- website/versioned_docs/version-26.6/Configuration.md
Upon reading the documentation about the `@jest-environment` annotation, I had to find out how to use a custom class on another website, so I thought I'd add what I learned to the docs for the next developer looking for the same answer.
The docs explain how to use `node` or `jsdom`, but not how to refer to your own class in the annotation. I added some text and a code example, and added the example to an existing code snippet.
(I completed the CLA.)
> Added explanation on how to use custom @jest-environment to docs

- package.json
- yarn.lock
- allows use of the `yarn workspace` command to target and run scripts defined in the root workspace
Having a well defined name allows project tools to target the root workspace specifically. For example, the `yarn workspace` command and run a project build script from another workspace.
> chore: add name to root project

- CHANGELOG.md
- packages/expect/src/__tests__/asymmetricMatchers.test.ts
- packages/expect/src/asymmetricMatchers.ts
Fixes #10186 by changing `expect.not.objectContaining()` to simply invert the result of `expect.objectContaining()`.
By semver this is a patch-level change, but I agree with [jeysal](https://github.com/facebook/jest/issues/10186#issuecomment-716196974) that it would be prudent to treat this as a breaking change anyway, just in case someone's relying on the previous behavior.
Revised existing tests which asserted undocumented behavior and added several new test cases.
> Change expect.not.objectContaining() to match documentation

- CHANGELOG.md
- packages/jest-config/src/index.ts
- packages/jest-core/src/FailedTestsCache.ts
- packages/jest-core/src/__tests__/FailedTestsCache.test.js
- packages/jest-core/src/__tests__/watch.test.js
- packages/jest-core/src/runJest.ts
- packages/jest-jasmine2/src/index.ts
- packages/jest-types/src/Config.ts
- packages/test-utils/src/config.ts
Have this on my todo list for too long now :D Part of https://github.com/facebook/jest/issues/7185
Existing tests.
> chore(breaking): remove undocumented `enabledTestsMap` config

- docs/CLI.md
- website/versioned_docs/version-22.x/CLI.md
- website/versioned_docs/version-23.x/CLI.md
- website/versioned_docs/version-24.x/CLI.md
- website/versioned_docs/version-25.x/CLI.md
- website/versioned_docs/version-26.0/CLI.md
- website/versioned_docs/version-26.2/CLI.md
- website/versioned_docs/version-26.5/CLI.md
> docs: add missing "--roots" options

- packages/jest-config/src/ValidConfig.ts
add `watchAll` to valid config to avoid validation warning (Unknown option):
```● Validation Warning:
Unknown option "watchAll" with value true was found.
This is probably a typing mistake. Fixing it will remove this message.
Configuration Documentation:
https://jestjs.io/docs/configuration.html
```
> fix: add `watchAll` to Valid config

- CHANGELOG.md
- e2e/__tests__/__snapshots__/v8Coverage.test.ts.snap
- e2e/__tests__/v8Coverage.test.ts
- e2e/v8-coverage/empty-sourcemap/babel.config.js
- e2e/v8-coverage/empty-sourcemap/package.json
- e2e/v8-coverage/empty-sourcemap/test.ts
- e2e/v8-coverage/empty-sourcemap/types.ts
- packages/jest-reporters/src/CoverageReporter.ts
> fix(reporters): make sure to handle empty files in v8 coverage

- CHANGELOG.md
- babel.config.js
- packages/jest-runtime/src/__tests__/runtime_require_resolve.test.ts
- packages/jest-runtime/src/__tests__/test_root/resolve_and_require_outside.js
- packages/jest-runtime/src/index.ts
- packages/jest-types/src/Global.ts
- scripts/babel-plugin-jest-require-outside-vm.js
See title.
And rename the Symbol to align with other Symbols that we have and use.
in Babel plugins
Works when I use it in #7792
> chore: make requiring from outside the Jest VM easier w/ a Babel plugin

- CHANGELOG.md
- packages/jest-console/src/__tests__/getConsoleOutput.test.ts
- packages/jest-console/src/getConsoleOutput.ts
- packages/jest-reporters/src/DefaultReporter.ts
- packages/jest-runner/src/runTest.ts
PR for #10112 
The breaking changes to `getConsoleOutput`: removing unused parameter, making new parameters mandatory.
Pass existing test cases.
> chore(jest-console): migrate function signature

- CHANGELOG.md
- e2e/__tests__/transform.test.ts
- e2e/babel-plugin-jest-hoist/package.json
- e2e/coverage-transform-instrumented/package.json
- e2e/transform-linked-modules/package.json
- e2e/transform/multiple-transformers/package.json
- e2e/transform/transform-environment/__tests__/add.test.js
- e2e/transform/transform-environment/babel.config.js
- e2e/transform/transform-environment/environment.ts
- e2e/transform/transform-environment/package.json
- e2e/transform/transform-environment/tsconfig.json
- e2e/v8-coverage/empty-sourcemap/babel.config.js
- e2e/v8-coverage/no-sourcemap/package.json
- packages/jest-repl/src/cli/runtime-cli.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-runner/tsconfig.json
Fixes #8479. The exact same approach as #7562. 
- Using the `Runtime` create an instance of `Transformer`
- Hijack the `require` and perform the transform
- Remove the hook on `require`
As of now the logic for the transformation is repeated across `jest-cli`, `jest-runner`, `jest-runtime` packages. Can you give me some inputs on whether it can be extracted to a single location?
Existing test cases should not be affected by the change, an additional test where the environment needs to be transformed to pass is added.
> feat: allow test environment to run with preset/transform

- e2e/__tests__/jestChangedFiles.test.ts
- e2e/__tests__/onlyChanged.test.ts
I've ran `git config --global init.defaultBranch main` locally, so these tests currently fail for me. I've modified the tests to pass `--initial-branch=main` during `init` so the user's config doesn't impact it.
Green CI
> chore: tweak git tests to handle default branch name

- e2e/__tests__/circusConcurrentEach.test.ts
- e2e/__tests__/toMatchInlineSnapshotWithRetries.test.ts
- e2e/__tests__/toMatchSnapshotWithRetries.test.ts
No reason to run tests with jasmine if they spawn using `testRunner` arg - just skip them to begin with
Green CI
> chore: skip circus-only tests when using jasmine

- CHANGELOG.md
- e2e/__tests__/transform.test.ts
- e2e/async-regenerator/package.json
- e2e/babel-plugin-jest-hoist/package.json
- e2e/coverage-transform-instrumented/package.json
- e2e/transform-linked-modules/package.json
- e2e/transform/babel-jest-ignored/babel.config.js
- e2e/transform/multiple-transformers/package.json
- e2e/transform/transform-testrunner/__tests__/add.test.js
- e2e/transform/transform-testrunner/babel.config.js
- e2e/transform/transform-testrunner/package.json
- e2e/transform/transform-testrunner/test-runner.ts
- e2e/transform/transform-testrunner/tsconfig.json
- packages/jest-runner/package.json
- packages/jest-runner/src/runTest.ts
- yarn.lock
Support transforming `testRunner` with `transform`
Part of #8810 
cc/ @SimenB 
Have added a test for transforming `testRunner`
> Support transforming testRunner with preset/transform

- CHANGELOG.md
- e2e/__tests__/pnp.test.ts
- e2e/pnp/__tests__/undeclared-dependency.test.js
- e2e/pnp/package.json
- e2e/pnp/yarn.lock
- packages/jest-resolve/src/defaultResolver.ts
In https://github.com/facebook/jest/pull/9520 `jest-resolve` was switched to use `resolve` which, because Yarn 2 patches it, supports PnP. It can't be removed as that would be a breaking change for Yarn 1 PnP users but it can be disabled for Yarn 2.
Main reason for doing this is that `jest-pnp-resolver` doesn't support projects where there are multiple `pnpapi` instances but the patch in `resolve` does.
Tests should still pass
> fix(jest-resolve): disable `jest-pnp-resolver` for Yarn 2

- CHANGELOG.md
- e2e/__tests__/__snapshots__/circusDeclarationErrors.test.ts.snap
- e2e/__tests__/skipBeforeAfterAll.test.ts
- e2e/before-all-skipped/__tests__/beforeAllFiltered.test.js
- packages/jest-circus/src/__tests__/__snapshots__/afterAll.test.ts.snap
- packages/jest-circus/src/__tests__/afterAll.test.ts
- packages/jest-circus/src/eventHandler.ts
- packages/jest-circus/src/run.ts
- packages/jest-jasmine2/src/jasmine/Env.ts
- packages/jest-jasmine2/src/treeProcessor.ts
Fixes #10451 
Fixes the below issues in packages `jest-circus` & `jest-jasmine2`.
1. `beforeAll` block runs even if it is inside a describe.skip block when the it block contains `tests` marked as `todo` or `only`
2. Tests run even if it is inside a `describe.skip` when the `tests` are marked as `todo` or `only`
`e2e/__tests__/skipBeforeAfterAll.test.ts`
`packages/jest-circus/src/__tests__/afterAll.test.ts`
> #10451 - beforeAll block & tests marked with only & todo runs even if it is inside a describe.skip block

- CHANGELOG.md
- docs/TimerMocks.md
Closes #10468 . Tweaks to language are welcome, I hope this keeps with the general tone/style of the docs!
> Clarify documentation of global nature of useFakeTimers.

- .github/workflows/nodejs.yml
- CHANGELOG.md
- e2e/runJest.ts
- package.json
- packages/jest-circus/src/utils.ts
Unblocks #10686.
I've tested on Windows via Virtualbox. I've also added a CI build that runs the test on all 3 OSes using node LTS
> fix: test location for test.each on windows

- CHANGELOG.md
- packages/jest-core/src/SearchSource.ts
- packages/jest-resolve-dependencies/src/__tests__/dependency_resolver.test.ts
- packages/jest-resolve-dependencies/src/index.ts
> chore: migrate jest-resolve-dependencies to ESM

- CHANGELOG.md
- e2e/env-test/__tests__/equivalent.test.js
- packages/jest-environment-jsdom/src/index.ts
- **Refs:** <https://github.com/facebook/jest/pull/9606#pullrequestreview-540409155>
- Fixes: <https://github.com/facebook/jest/issues/10786>
- Fixes: <https://github.com/facebook/jest/issues/10854>
See the changes to: [`e2e/env‑test/__tests__/equivalent.test.js`](https://github.com/ExE-Boss/jest/blob/fix/jest-environment-jsdom/use-inner-realm-arraybuffer-constructor/e2e/env-test/__tests__/equivalent.test.js).
> fix(jest‑environment‑jsdom): Use inner realm’s ArrayBuffer constructor

- CHANGELOG.md
- e2e/__tests__/hasteMapMockChanged.test.ts
- e2e/__tests__/hasteMapSha1.test.ts
- e2e/__tests__/hasteMapSize.test.ts
- packages/jest-core/src/__tests__/watchFileChanges.test.ts
- packages/jest-core/src/cli/index.ts
- packages/jest-core/src/watch.ts
- packages/jest-haste-map/src/__tests__/index.test.js
- packages/jest-haste-map/src/index.ts
- packages/jest-runner/src/testWorker.ts
- packages/jest-runtime/src/index.ts
- packages/jest-test-sequencer/src/index.ts
- packages/jest-transform/src/ScriptTransformer.ts
Getting rid of more `export =`s
Green CI
> chore: migrate jest-haste-map to ESM

- CHANGELOG.md
- packages/jest-environment/src/index.ts
- packages/jest-fake-timers/src/__tests__/legacyFakeTimers.test.ts
- packages/jest-mock/README.md
- packages/jest-mock/src/index.ts
- packages/jest-runtime/src/index.ts
Another one of these. Not sure what API we should expose? I ended up export `fn` and `spyOn` in addition to the class itself, but we maybe want more stuff?
Green CI
> chore: migrate jest-mock to ESM

- CHANGELOG.md
- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/native-esm/__tests__/native-esm.test.js
- e2e/native-esm/circularDependentA.mjs
- e2e/native-esm/circularDependentB.mjs
- packages/jest-runtime/src/index.ts
In current implementation, when importing a mutually dependent ES module, stack overflow and promise deadlock occur.
For a circular dependency like follow:
`moduleA.js`:
`import moduleB from './moduleB.js'; export default {}; `
`moduleB.js`:
`import moduleA from './moduleA.js'; export default {};`
Loading `moduleA.js` will trigger `loadEsmModule` of `moduleB.js` recursively from `module.link` before the promise for `moduleA.js` is set to  `_esmoduleRegistry`; which in turn will recursively trigger `loadEsmModule` of `moduleA.js`, having a cache miss. Thus this will continue until stack overflow.
Another issue is that since the current cache registry is containing a promise that is resolved **after** the module is evaluated.
If there are circular dependencies, the promise in registry will …
> fix: unable to cyclic ES modules

- CHANGELOG.md
- e2e/transform/transform-runner/runner.ts
- packages/jest-core/src/TestScheduler.ts
- packages/jest-core/src/__tests__/SearchSource.test.ts
- packages/jest-runner/src/index.ts
One more. Just a few left now
Green CI
> chore: convert jest-runner to ESM

- docs/ExpectAPI.md
- website/versioned_docs/version-25.x/ExpectAPI.md
`toMatchInlineSnapshot` needs to received the current inline snapshot. The documented implementation did not pass this argument along leading jest to always update the snapshot.
Tested in https://github.com/eps1lon/jest-custom-inline-snapshot-matcher/commit/8cd0b6216541d8898c8bd82812000eb963bd5736
> docs: Update incorrect implementation of custom inline snapshot matcher

- CHANGELOG.md
- packages/jest-jasmine2/src/index.ts
> chore: migrate jest-jasmine to ESM

- packages/jest-types/src/Config.ts
- test-types/top-level-config.test.ts
coverageThreshold now accepts custom properties
fixes #10884
> chore: update type definitions for coverageThreshold

- CHANGELOG.md
- packages/babel-plugin-jest-hoist/src/index.ts
This allows several things. My specific case is using the content of a file as the return value for a mocked function:
```ts
jest.mock('some-module', () => {
const fs = require('fs');
const path = require('path');
return {
someFunction() {
const pathToHtmlFile = path.resolve(__dirname, 'some-fixture.html');
const html = fs.readFileSync(pathToHtmlFile);
return html;
},
};
});
```
The test is located inside a Yarn workspace, and for complicated reasons I have to execute `jest` from the root of the repository. As far as I can tell, this is the only way I can avoid letting the test know about its own directory path in the repo.
To be honest, I'm just doing what @SimenB told me would solve my problem.
I applied this patch to my own repo, and it works. Does it make sense to document this …
> fix(babel-plugin-jest-hoist): allow using module wrapper arguments in hoisted mock factory function

- packages/jest-circus/src/utils.ts
- packages/jest-types/src/Global.ts
- test-types/top-level-globals.test.ts
Another go at #10066, generators weren't included in the last PR (#10480).
This is a redo of PR https://github.com/facebook/jest/pull/10526 cause I lost that fork :-P
Added more type tests.
Reviewers will notice some ugly stuff going on. For starters, that `isGeneratorFn` type guard is checking against the `GeneratorFunction` interface, which doesn't seem to be the correct approach here (it's badly misunderstood just like `Function`). If we try to use `GeneratorFunction` as the receiving type for hook functions, it will fail.
So I declared a makeshift interface that should hold any generator function. But then, for some reason the type inference of a few `fn.call` inside `jest-circus` broke. I have no idea why, but manually providing the type arguments was possible to please the compiler. …
> Add generator function to accepted hook types

- docs/UsingMatchers.md
- website/versioned_docs/version-22.x/UsingMatchers.md
I know this isn't anything major, but given that many people suffer from alcohol-related issues, I really would like to avoid that the only array example jest provides revolves around whether beer is present in an otherwise _family oriented_ `shoppingList`.
As someone who knows plenty of people with such issues I just found it of poor taste, again, nothing major, but I see no reason to not change it, nothing changes from a functional/documentation point of view, but avoids any pointless substance-related reference.
Milk seems more fitting.
> docs: changed UsingMatchers array example

- CHANGELOG.md
- packages/jest-core/package.json
- packages/jest-core/src/TestScheduler.ts
- packages/jest-core/src/TestWatcher.ts
- packages/jest-runner/src/index.ts
- packages/jest-runner/src/types.ts
- yarn.lock
This gives us typed events. I'm not sure if this should be considered a breaking change or not?
Green CI
> chore: make TestWatcher extend emittery

- CHANGELOG.md
- docs/JestObjectAPI.md
- e2e/fake-promises/immediate/__tests__/generator.test.js
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
- packages/jest-jasmine2/src/index.ts
- packages/jest-runtime/src/index.ts
As announced in the v26 [blog post](https://jestjs.io/blog/2020/05/05/jest-26#new-fake-timers)
Green CI
> feat: use modern fake timers by default

- jest
It uses `BASH_SOURCE`, which isn't available in `dash`, ubuntu's default `sh`. Instead, specify that we need actual `bash`.
```
% readlink -f =sh
/usr/bin/dash
% ./jest
./jest: 10: Bad substitution
% git checkout chore/fixup-helper-script
% ./jest
yarn node v1.22.10
...
```
> chore: ./jest requires bash

- packages/jest-runtime/src/index.ts
- packages/jest-transform/src/ScriptTransformer.ts
While working on the other PR, I noticed that some class fields in `jest-runtime/index.ts` and `ScriptTransformer` should be defined with `readonly`. This will be stricter for TypeScript.
- TypeScript build should not fail
- Green CI
> refactor(jest-runtime,jest-transform): add readonly for some class fields

- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
- packages/jest-core/src/ReporterDispatcher.ts
- packages/jest-test-result/src/helpers.ts
- packages/jest-test-result/src/types.ts
More minor cleanup - can break out into another PR if you want to land some before Jest 27
Let CI do its thing.
> chore(test-result): remove deprecated `sourcemap` property

- CHANGELOG.md
- packages/jest-repl/package.json
- packages/jest-runtime/package.json
- scripts/buildUtils.js
- yarn.lock
See https://github.com/facebook/jest/issues/9860#issuecomment-739859042. Forgotten in #10016
Added a check in the build script that all defined binary files exist
> fix: move binary file declaration from runtime to repl

- docs/ExpectAPI.md
- e2e/__tests__/__snapshots__/customInlineSnapshotMatchers.test.ts.snap
- e2e/__tests__/customInlineSnapshotMatchers.test.ts
- e2e/custom-inline-snapshot-matchers/__tests__/asynchronous.test.js
- e2e/custom-inline-snapshot-matchers/package.json
- website/versioned_docs/version-25.x/ExpectAPI.md
Documents and tests how to implement custom, async, inline snapshot matchers. Specifically, that `this.error = new Error()` must be set before any `await`.
Without overriding the stack jest fails when it encounters new snapshots with "Multiple inline snapshots for the same call are not supported"
> Document and test custom, async, inline snapshot matcher

- CHANGELOG.md
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/matchers.ts
The following expectations were still passing after #10119:
```js
expect("false").toContain(false);
expect("0").toContain(0n);
```
This PR ensures only strings will be accepted when received is a string itself in `toContain`.
They pass before that PR:
```js
expect("false").toContain(false);
expect("0").toContain(0n);
```
They do not pass now.
> Ensure `toContain` only accepts strings when `received` is a string

- docs/TutorialReactNative.md
- website/versioned_docs/version-22.x/TutorialReactNative.md
- website/versioned_docs/version-25.x/TutorialReactNative.md
Minor typo updates in documentation which could cause users to encounter test failures on case sensitive systems.
N/A
> docs: Rectify typo in tutorialReactNative

- CHANGELOG.md
- e2e/__tests__/__snapshots__/declarationErrors.test.ts.snap
- e2e/__tests__/declarationErrors.test.ts
- e2e/declaration-errors/__tests__/describeReturnPromise.test.js
- e2e/declaration-errors/__tests__/describeReturnSomething.test.js
- packages/jest-circus/src/index.ts
- packages/jest-jasmine2/src/jasmine/Env.ts
Closes #8074
BREAKING CHANGE:
Returning a value from `describe` will now fail the test instead of just
warn.
> feat(jest-circus,jest-jasmine2): throw when describe returns a value

- docs/MockFunctions.md
- website/versioned_docs/version-22.x/MockFunctions.md
- website/versioned_docs/version-23.x/MockFunctions.md
filter method runs callback function with three arguments so result of filterTestFn.mock.calls is not correct.
> docs: cleanup `mock.calls` structure

- CHANGELOG.md
- packages/jest-runtime/src/__tests__/runtime_require_module_or_mock.test.js
- packages/jest-runtime/src/index.ts
`require` statement inside `isolateModules` callbacks are unpredictable since they do not always return a fresh copy of imported modules. Currently if global registry has the require module in cache, the cached instance is returned even within `isolateModules. Fixes: #7863
This PR ensures that `require` statement inside `isolateModules` always return a fresh copy of imported modules.
```js
const myModule = require('myModule');
jest.isolateModules(() => {
const myIsolatedModule = require('myModule');
// myIsolatedModule === myModule;
});
```
```js
const myModule = require('myModule');
jest.isolateModules(() => {
const myIsolatedModule = require('myModule');
// myIsolatedModule !== myModule;
});
```
Added relevant test in: `packages/jest-runtime/src/__tests__/runtime_require_module_or_mock.t …
> fix(jest-runtime): prevent global module registry from leaking into isolateModules registry

- .github/workflows/nodejs.yml
When the lockfile changes, the changed dependencies will be fetched 4x3 + 3 + 1 = 16 times which wastes resources. To solve this I added a `prepare-yarn-cache` job that all the other jobs wait for to make sure they always get a cache hit.
CI passes
> ci: only fetch dependencies once

- CHANGELOG.md
- packages/jest-repl/src/cli/runtime-cli.ts
- packages/jest-resolve/src/index.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-runtime/src/__mocks__/createRuntime.js
- packages/jest-runtime/src/__tests__/__snapshots__/runtime_require_module_no_ext.test.js.snap
- packages/jest-runtime/src/index.ts
- packages/jest-source-map/src/__tests__/getCallsite.test.ts
- packages/jest-source-map/src/getCallsite.ts
- packages/jest-source-map/src/types.ts
Following up on #9902.
Green CI
> chore: use `Map`s throughout jest-runtime

- CHANGELOG.md
- packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js
- packages/jest-haste-map/src/crawlers/watchman.ts
- packages/jest-haste-map/src/types.ts
Jest's haste map supports incremental update. What this means is that when you first run Jest, a full rebuild of the map is done, but future invocations will only update changed files, which is pretty quick.
At Facebook, due to the size of our monorepo, we've taken this one step further. The first run of Jest downloads a version of the haste map that was created for a revision near yours. We then update it from there. This is done because doing a full rebuild takes several minutes.
To support this, we've been using a forked version of the Watchman crawler that supported doing an "SCM query". You can read about it here: https://facebook.github.io/watchman/docs/scm-query.html
The reason this is necessary is because Watchman clocks are not portable across systems; the haste map you create on …
> feat(jest-haste-map): handle injected scm clocks

- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
- packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
- packages/jest-repl/src/cli/runtime-cli.ts
- packages/jest-runtime/src/__mocks__/createRuntime.js
- packages/jest-runtime/src/index.ts
- packages/jest-test-result/src/types.ts
Clearing out some TODOs
Green CI
> chore(runtime): make arguments mandatory

- CHANGELOG.md
- package.json
- packages/jest-cli/package.json
- packages/jest-core/package.json
- packages/jest-reporters/package.json
- packages/jest-reporters/src/NotifyReporter.ts
- packages/jest-reporters/src/__tests__/NotifyReporter.test.ts
- packages/jest/package.json
- yarn.lock
`node-notifier` is 5MB due to the vendored binaries.
```sh-session
$ du -d1 -h node_modules/node-notifier
256K    node_modules/node-notifier/node_modules
20K    node_modules/node-notifier/lib
24K    node_modules/node-notifier/notifiers
5.4M    node_modules/node-notifier/vendor
5.7M    node_modules/node-notifier
```
This is the single biggest directory in `node_modules` of a fresh Jest install, beating out the combined `@babel` directory (albeit barely)
```sh-session
$ du -d1 -h node_modules/ | sort -hr | head
51M    node_modules/
5.7M    node_modules//node-notifier
5.7M    node_modules//@babel
4.8M    node_modules//lodash
3.8M    node_modules//jsdom
1.2M    node_modules//acorn
1.2M    node_modules//@types
1.1M    node_modules//ajv
984K    node_modules//@jest
960K …
```
> chore: make node-notifier a peer dep

- CHANGELOG.md
- e2e/__tests__/customTestSequencers.test.ts
- e2e/custom-test-sequencer/testSequencerAsync.js
- packages/jest-core/src/runJest.ts
Allow a `TestSequencer` implementation to perform `async` operations during its `allFailedTests` and `cacheResults` phases.
It's already allowed for `sort`, but not for the other methods, which I believe are part of the public/extensible API.
My Sequencer wants to go to a database.
There's already a test for `sort`, and I've added a similar test for `allFailedTests`.
It's hard to directly test `cacheResults` is awaited, as it's void. We could attempt to catch it with sleeps and testing the implementation ordering; e.g. checking if it has completed before the `globalHook` has run? It doesn't seem to have any value.
`await`ing it is necessary, as otherwise longer `cacheResults` implementations eventually trigger the `Jest did not exit one second after the test run has completed.` failure.
> feat: sequencer saving may be async

- CHANGELOG.md
- packages/jest-worker/src/workers/messageParent.ts
Extracted from #10981.
Error from the reproduction of #10577 changes from
```
"messageParent" can only be used inside a worker
at messageParent (packages/jest-worker/build/workers/messageParent.js:46:11)
```
to
```
TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Object'
--- property 'ref' closes the circle
at stringify (<anonymous>)
at messageParent (packages/jest-worker/build/workers/messageParent.js:42:19)
```
When using `jest-circus` which makes use of this function
> fix(worker): do not swallow errors when sending custom messages

- CHANGELOG.md
- e2e/__tests__/failureDetailsProperty.test.ts
- packages/expect/src/index.ts
When the error is thrown from `expect`, there's not reason to keep the `message` property a function. A function is removed by `JSON.stringify`, so it's lost when transferred between workers. And the structured clone used by `worker_threads` throws as the `message` function references out of scope variables.
Extracted from #10981.
Test tweaked
> fix(expect): resolve `message` on assertion errors

- CHANGELOG.md
- e2e/native-esm/__tests__/native-esm.test.js
- e2e/native-esm/commonjsNamed.cjs
- packages/jest-runtime/src/index.ts
Noticed when investigating #10814 that `import {jsx} from 'react/jsx-runtime'` didn't work as the exported function was not detected
Test for named CJS export expanded.
> feat: resolve reexported CJS modules as named ESM exports

- CHANGELOG.md
- packages/pretty-format/src/plugins/DOMElement.ts
See https://github.com/ionic-team/stencil/pull/2789.
Stencil.js uses Jest under the hood for testing, and I ran into an issue where `pretty-format` throws an error because Stencil passes a `MockCSSStyleDeclaration` object which is proxied and returns an empty string for all unknown properties.
`pretty-format` assumes that if the given object has a `hasAttribute` property, that it's a function and just tries calling it, which fails in this case because the value of `val.hasAttribute` is `''` in this case. I know this is an edge case which is why I've suggested a fix on Stencil's side as well. However I thought it doesn't hurt to make this code more robust here as well.
> fix(pretty-format): only call `hasAttribute` if function

- CHANGELOG.md
- packages/jest-core/src/TestScheduler.ts
- packages/jest-reporters/src/CoverageReporter.ts
- packages/jest-reporters/src/DefaultReporter.ts
- packages/jest-reporters/src/NotifyReporter.ts
- packages/jest-reporters/src/SummaryReporter.ts
- packages/jest-reporters/src/VerboseReporter.ts
https://github.com/jevakallio/jest-clean-console-reporter documents a pattern of doing
```
// Overriding config.reporters wipes out default reporters, so
// we need to restore the summary reporter
"@jest/reporters/build/SummaryReporter",
```
This won't work in Jest 27 due to #9921.
```sh-session
$ node -p 'require("@jest/reporters/build/SummaryReporter")'
internal/modules/cjs/loader.js:438
throw e;
^
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/SummaryReporter' is not defined by "exports" in /Users/simen/repos/jest/node_modules/@jest/reporters/package.json
at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
at resolveExports (internal/modules/cjs/loader.js:432:36)
at Function.Module._findPath …
```
> feat(reporters): add static filepath property to all reporters

- CHANGELOG.md
- packages/jest-console/src/index.ts
As discussed [here](https://github.com/jevakallio/jest-clean-console-reporter/pull/3#discussion_r559954156) @SimenB
> chore: export LogEntry from jest-console

- e2e/to-match-inline-snapshot/__tests__/basic-support.test.js
- packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
- packages/expect/src/__tests__/matchers.test.js
- packages/expect/src/jasmineUtils.ts
This Pull Request fixes #11056.
`arr1` and `arr2` are now said to be different in the code below:
```js
test('should not pass', () => {
const arr1 = [];
arr1[4294967295] = 1;
const arr2 = [];
arr2[4294967295] = 2;
expect(arr2).not.toEqual(arr1);
});
```
Test added
> fix: int keys ranging outside of [0, 4294967294] are ignored when comparing arrays together

- CHANGELOG.md
- e2e/__tests__/globalSetup.test.ts
- e2e/__tests__/globalTeardown.test.ts
- packages/jest-cli/src/cli/index.ts
- packages/jest-core/src/runGlobalHook.ts
Could probably make the error more pretty, but this is _something_
Fixes #11002
before:
after:
> fix: print underlying error when global hooks fail

- website/package.json
- yarn.lock
New Jest website should use the latest Docsaurus and React 17 cc @SimenB 
Netlify
> website: use React 17, upgrade Docusaurus

- website/package.json
@SimenB @merceyz the change made here:
https://github.com/jest-website-migration/jest/commit/fd34cd0cf64f0f1d0b0750400a65914c65b65df8
It broke Crowdin translation download (didn't notice)
Crowdin is quite sensitive to the path from which you call its cli, and it seems using the `:` and global yarn script does not run from the place where the cli is declared, unlike `yarn workspace`.
Netlify preview works
> Fix Yarn Crowdin scripts

- website/static/_redirects
- Docusaurus v1 RSS feed: https://jestjs.io/blog/feed.xml
- Docusaurus v2 RSS feed: https://jestjs.netlify.app/blog/rss.xml
Redirect /blog/feed.xml to /blog/rss.xml so that feed subscribers can keep using their feeds after the migration.
The following URL should work: https://jestjs.netlify.app/blog/feed.xml
CC @SimenB
> add redirect for Jest blog feed

- CHANGELOG.md
- e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
- packages/jest-resolve/package.json
- packages/jest-resolve/src/defaultResolver.ts
- packages/jest-resolve/src/index.ts
- packages/jest-runtime/src/index.ts
- yarn.lock
See #11034.
@lencioni would you be able to test this instead of your custom resolver?
Green CI
> fix(jest-resolve): cache package.json lookups

- e2e/runJest.ts
- packages/jest-circus/src/utils.ts
- packages/jest-jasmine2/src/PCancelable.ts
- packages/jest-snapshot/src/utils.ts
- packages/pretty-format/src/plugins/ReactElement.ts
- yarn.lock
~I'm unsure about the second commit - seems to be some array changes in TS 4.1 that are causing errors for us. @jeysal thoughts?~
Updating to 4.1.5 fixed those errors
Green CI
> chore: update to TypeScript@4.1

- CHANGELOG.md
- packages/jest-core/src/FailedTestsInteractiveMode.ts
- packages/jest-core/src/__tests__/FailedTestsInteractiveMode.test.js
- packages/jest-core/src/plugins/FailedTestsInteractive.ts
- packages/jest-core/src/plugins/__tests__/FailedTestsInteractive.test.js
- packages/jest-core/src/watch.ts
- packages/jest-watcher/src/BaseWatchPlugin.ts
Closes #7685.
When running multiple failed tests we may end up with a lot of noise in tests (console logs, deprecation warnings, etc.). Using an interactive mode would allow us to run and fix each test in isolation without having to manually run and re-run tests.
> feat: interactive failure runs

- docs/MockFunctionAPI.md
- website/versioned_docs/version-25.x/MockFunctionAPI.md
- website/versioned_docs/version-26.x/MockFunctionAPI.md
The inline TOC (in Methods section) is wrong on this page and does not look like it used to in v1.
https://jestjs.netlify.app/docs/mock-function-api
In v1 we had a flat structure mixing references + typescript methods:
https://jestjs.io/docs/en/mock-function-api
This PR fixes the issue, but also decided that it would be better to keep the non-flat structure:
Preview
> Fix site inline TOC for mock functions api page

- CHANGELOG.md
- packages/jest-core/src/__tests__/collectHandles.test.js
- packages/jest-core/src/collectHandles.ts
Fixes https://github.com/facebook/jest/issues/11051
> fix(): jest should not count PerformanceObserver as an open handle

- CHANGELOG.md
- packages/jest-runtime/src/index.ts
This refactor makes sure to only call `link` and `evaluate` at the top level module or any dynamic imports. This resolves an issue where we produced an invalid module graph, leading newer versions of Node to throw an error.
This also contains a revert of the implementation added in #10892, but keeps the test as the complexity there is not needed anymore with this more correct way of linking and evaluating.
Fixes #11093.
All existing tests pass in addition to the bug report in #11093.
> fix(runtime): refactor ESM code to avoid race condition

- packages/jest-runtime/src/index.ts
Noticed in #11163 we got a really bad error in `import` usage:
Now it's
Which is not beautiful, but way more useful
See screenshots 😀
> chore: add invariant on ESM support in dynamic import

- CHANGELOG.md
- packages/jest-worker/src/workers/ChildProcessWorker.ts
The detailed description is at https://github.com/facebook/jest/issues/11143.
Fixes #11143
> Fix unhandled ERR_IPC_CHANNEL_CLOSED and a deadlock

- CHANGELOG.md
- e2e/__tests__/jestChangedFiles.test.ts
- packages/jest-changed-files/src/git.ts
Hi. This PR fixes #10149.
Now `jest --watch`, `jest --lastCommit`, `--changedSince` work fine even if there are same name revision and filename.
e2e test modified
> fix: jest --watch fails with ambiguous argument

- CHANGELOG.md
- docs/Configuration.md
- docs/Puppeteer.md
- e2e/__tests__/__snapshots__/testEnvironmentRunScript.test.ts.snap
- e2e/__tests__/testEnvironmentRunScript.test.ts
- e2e/test-environment-async/TestEnvironment.js
- e2e/test-environment-run-script/EnvUsingRunScript.js
- e2e/test-environment-run-script/__tests__/envUsingRunScript.test.js
- e2e/test-environment-run-script/package.json
- examples/mongodb/mongo-environment.js
- packages/jest-environment-jsdom/src/index.ts
- packages/jest-environment-node/src/index.ts
- packages/jest-environment/src/index.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-runtime/src/index.ts
It cannot be used for ESM anyways, so let's clean up our code a bit
Green CI
> fix: remove support for `runScript`

- CHANGELOG.md
- packages/jest-transform/src/ScriptTransformer.ts
- packages/jest-transform/src/__tests__/ScriptTransformer.test.ts
- packages/jest-transform/src/types.ts
We never pass this flag from `runtime` as that's always the "real" modules. So we can simplify the transformer a bit by removing it
Green CI
> fix(transformer): remove unused `isCoreModule`

- CHANGELOG.md
- babel.config.js
- docs/Configuration.md
- e2e/__tests__/transform.test.ts
- e2e/transform/esm-transformer/__tests__/test.js
- e2e/transform/esm-transformer/module.js
- e2e/transform/esm-transformer/my-transform.mjs
- e2e/transform/esm-transformer/package.json
- package.json
- packages/jest-core/src/TestScheduler.ts
- packages/jest-core/src/__tests__/watchFileChanges.test.ts
- packages/jest-core/src/runGlobalHook.ts
- packages/jest-create-cache-key-function/package.json
- packages/jest-create-cache-key-function/src/__tests__/index.test.ts
- packages/jest-create-cache-key-function/tsconfig.json
- packages/jest-repl/src/cli/runtime-cli.ts
- packages/jest-reporters/src/CoverageWorker.ts
- packages/jest-reporters/src/__tests__/generateEmptyCoverage.test.js
- packages/jest-reporters/src/generateEmptyCoverage.ts
- packages/jest-runner/src/runTest.ts
- packages/jest-runtime/src/__mocks__/createRuntime.js
- packages/jest-runtime/src/__tests__/instrumentation.test.ts
- packages/jest-runtime/src/index.ts
- packages/jest-transform/src/ScriptTransformer.ts
- packages/jest-transform/src/__tests__/ScriptTransformer.test.ts
- packages/jest-transform/src/index.ts
- yarn.lock
This allows people to write their transformers in ESM. This is mostly a refactor since `import()` is async, I've changed `ScriptTransformer` to load all transformers when it's created rather than on demand.
To not force all consumers to call `load`, I now expose more of a factory method which does the extra function call for the user.
This solves the use case behind #11081, but I think that issue might be useful for other async work.
~I'll need to update docs here, but I'll do that after landing docusaurus 2~ Just added a line, I think since we don't mess with versioned docs it should be fine
E2E test added
> feat(jest-transform): support transformers written in ESM

- CHANGELOG.md
- packages/jest-environment-node/src/index.ts
This PR adds support for the AbortController global when using the `node` Jest environment with Node `v15`.
The motivation for this pull request is to fix the error `ReferenceError: AbortController is not defined` when trying to test code that uses the AbortController in Node v15. This has previously been a Browser API but has now been introduced as a native API in Node v15.
This change is non-breaking. Node versions earlier than `v15` will behave the same as before, throwing a ` ReferenceError` if you call `AbortController` without polyfilling it or using the `jsdom` environment.
> Add support for AbortController in Jest Node environment with Node v15

- CHANGELOG.md
- packages/babel-jest/src/index.ts
- packages/jest-repl/src/cli/repl.ts
- packages/jest-transform/src/ScriptTransformer.ts
- packages/jest-transform/src/__tests__/ScriptTransformer.test.ts
- packages/jest-transform/src/__tests__/__snapshots__/ScriptTransformer.test.ts.snap
- packages/jest-transform/src/index.ts
- packages/jest-transform/src/types.ts
Support async code transformation as mentioned in #9504 
Test cases added
> feat(transformer): async code transformation

- CHANGELOG.md
- docs/Configuration.md
- e2e/__tests__/transform.test.ts
- e2e/transform/async-transformer/__tests__/test.js
- e2e/transform/async-transformer/module-under-test.js
- e2e/transform/async-transformer/my-transform.cjs
- e2e/transform/async-transformer/package.json
- packages/jest-runtime/src/index.ts
- packages/jest-transform/src/types.ts
> feat(runtime): add support for async code transformation

- CHANGELOG.md
- e2e/__tests__/__snapshots__/transform.test.ts.snap
- e2e/transform/babel-jest-manual/transformer.js
- packages/babel-jest/src/__tests__/index.ts
- packages/babel-jest/src/index.ts
- packages/jest-repl/src/__tests__/jest_repl.test.js
- packages/jest-repl/src/cli/repl.ts
- packages/jest-transform/src/ScriptTransformer.ts
Vaguely related to #8810. We don't transpile at runtime, but pre-transpiled modules should load fine
Green CI
> feat: support transpiled transformers

- babel.config.js
- package.json
- yarn.lock
No difference in `packages/*/build`, so let's just remove it
Green CI
> chore: remove unused babel transform strict

- CHANGELOG.md
- packages/jest-fake-timers/package.json
- packages/jest-fake-timers/src/modernFakeTimers.ts
- packages/jest-fake-timers/tsconfig.json
- yarn.lock
This keeps using the types from DT rather than using the ones shipped with the module.
Fixes #11169.
Closes #11170.
Green CI
> feat: update to @sinonjs/fake-timers v7

- CHANGELOG.md
- docs/Configuration.md
- e2e/__tests__/fakeTime.test.ts
- e2e/fake-promises/immediate/package.json
- e2e/fake-time/legacy/from-config/__tests__/test.js
- e2e/fake-time/legacy/from-config/package.json
- e2e/fake-time/legacy/from-jest-object/__tests__/test.js
- e2e/fake-time/legacy/from-jest-object/package.json
- e2e/fake-time/modern/from-config/__tests__/test.js
- e2e/fake-time/modern/from-config/package.json
- e2e/fake-time/modern/from-jest-object/__tests__/test.js
- e2e/fake-time/modern/from-jest-object/package.json
This was supposed to be part of #10874, not sure why it wasn't... It's just docs and an integration test.
Green CI
> chore: update docs for fake timers

- CHANGELOG.md
- packages/pretty-format/src/__tests__/DOMElement.test.ts
- packages/pretty-format/src/plugins/DOMElement.ts
fixes #10770.
```js
expect(received).toMatchObject(expected)
```
When received object  mismatch with expected object, jest will copy received object with`deepCyclicCopyObject`. 
As for this issue, received object contains jsdom provided objects `AbortController`, and will encounter  `jsdom/lib/jsdom/living/attributes`.
This module also contains `hasAttribute`, `prettyFormat.plugins.DOMElement.test` will throw an exception by calling `hasAttribute`.
added `handles jsdom attributes properly` test.
> fix(pretty-format): handles jsdom attributes properly

- CHANGELOG.md
- packages/jest-worker/package.json
- packages/jest-worker/src/Farm.ts
- packages/jest-worker/src/__tests__/leak-integration.test.ts
- packages/jest-worker/src/workers/NodeThreadsWorker.ts
- packages/jest-worker/tsconfig.json
- yarn.lock
We noticed some closure related memory leaks in the current implementation of `jest-worker` with v8. The **arguments** and **result** of the task of each worker can't be garbage collected until a new task is assigned to that worker. If the arguments/result sizes are large, it's gonna introduce a huge memory increase.
This PR ensures that `args` and `task` are correctly scoped so they won't be claimed by other closures, and references can be cleaned once they become unneeded.
We have an app that passes image buffers as the argument of tasks which are pretty large, and we are seeing a huge memory leak after the tasks have finished (ref: vercel/next.js#22925). Here's a screenshot for the memory dump:
The memory usage increased from 112MB to 145MB (+29%) after processing the task, and most of …
> Fix memory leaks of jest-worker

- CHANGELOG.md
- docs/Configuration.md
- e2e/__tests__/presets.test.ts
- e2e/presets/cjs/__tests__/index.js
- e2e/presets/cjs/node_modules/jest-preset-cjs/jest-preset.cjs
- e2e/presets/cjs/node_modules/jest-preset-cjs/mapper.js
- e2e/presets/cjs/package.json
- e2e/presets/js-type-module/__tests__/index.js
- e2e/presets/js-type-module/node_modules/jest-preset-js-type-module/jest-preset.js
- e2e/presets/js-type-module/node_modules/jest-preset-js-type-module/mapper.js
- e2e/presets/js-type-module/node_modules/jest-preset-js-type-module/package.json
- e2e/presets/js-type-module/package.json
- e2e/presets/mjs/__tests__/index.js
- e2e/presets/mjs/node_modules/jest-preset-mjs/jest-preset.mjs
- e2e/presets/mjs/node_modules/jest-preset-mjs/mapper.js
- e2e/presets/mjs/package.json
- packages/jest-config/src/__tests__/normalize.test.ts
- packages/jest-config/src/normalize.ts
Related to #11167
- Add `.cjs`, `.mjs` to the supported extensions for `preset` as well as logic to load them, with `.mjs` for ESM preset and `.cjs` for CommonJS preset
- Clean up some unused mocks in `normalize.test.ts` as well as fix some ts type errors.
Added unit tests for happy path
Added e2e tests
> feat(jest-config): add support for `preset` written in ESM

- packages/jest-config/src/readConfigFileAndSetRootDir.ts
- packages/jest-transform/src/ScriptTransformer.ts
- packages/jest-util/src/importModule.ts
- packages/jest-util/src/index.ts
- packages/jest-util/src/requireOrImportModule.ts
According to #11167, we will support ESM of pluggable modules.
We may use the same logic to import them, so I extract it into an util function.
I think it should be useful in later work!
Cons:
Will lose information of which module type importing in error message
```diff
- `Jest: Failed to load ESM transformer at ${transformPath} - did you use a default export?` 
+ `Jest: Failed to load ESM at ${filePath} - did you use a default export?`
```
But I think it is ok, user can find out by file path.
> feat(jest-util): add requireOrImportModule util for importing CJS or ESM

- packages/jest-config/src/normalize.ts
Reuse the work from #11199 
Green CI
> refactor(jest-config): use `requireOrImportModule` util function for ESM/CJS import

- CHANGELOG.md
- packages/jest-config/src/readConfigFileAndSetRootDir.ts
`ts-node` has moved to deprecate the `Register` type in favour of `Service`. This change address that type update.
I've run the requested commands from `CONTRIBUTING.md` and verified that all tests pass.
> Switch ts-node `Register` type to `Service` due to deprecation

- CHANGELOG.md
- e2e/__tests__/transform.test.ts
- e2e/transform/async-transformer/__tests__/test.js
- e2e/transform/async-transformer/my-transform.cjs
- e2e/transform/async-transformer/package.json
- e2e/transform/async-transformer/some-symbol.js
- packages/jest-runtime/src/index.ts
The code currently ends up putting duplicate modules into the module cache, leading to different instances added to the cache (or rather, newer ones overriding old ones) which breaks referential identity.
We now have a sort of mutex on the cache key as well as asserting the cache does not have an entry for the cache key before we put the module into it.
Fixes #11214.
Test added
> fix(runtime): handle async transforms of same module

- CHANGELOG.md
- e2e/__tests__/customEsmTestSequencers.test.ts
- e2e/custom-esm-test-sequencer/a.test.js
- e2e/custom-esm-test-sequencer/b.test.js
- e2e/custom-esm-test-sequencer/c.test.js
- e2e/custom-esm-test-sequencer/d.test.js
- e2e/custom-esm-test-sequencer/e.test.js
- e2e/custom-esm-test-sequencer/package.json
- e2e/custom-esm-test-sequencer/testSequencer.mjs
- packages/jest-core/src/runJest.ts
Related to #11167
Add support for testSequencer written in ESM.
Use `requireOrImportModule` to load testSequencer
e2e test
> feat(jest-core): Add support for testSequencer written in ESM

- website/static/css/custom.scss
correct rendering of jest card - jagged edges in firefox
**before:**
**after:**
> docs: correct jest cards jagged edges in firefox

- docs/ExpectAPI.md
Update doc to add types for custom matchers
Fix : https://github.com/facebook/jest/issues/10642
Motivation : Copy pasting documentation doesn't work, as mentioned here, https://github.com/facebook/jest/issues/10642
> doc: Update ExpectAPI.md

- scripts/cleanE2e.js
Exclude several sub folders under `e2e/presets` from clean e2e script.
Clean e2e script should not delete `node_modules` folders in several sub folders under `e2e/presets`
> test(e2e): exclude several sub folders in `e2e/presets` from clean e2e

- CHANGELOG.md
- packages/jest-jasmine2/src/jasmine/Env.ts
- packages/jest-jasmine2/src/jasmine/jasmineLight.ts
- packages/jest-jasmine2/src/types.ts
Per https://github.com/facebook/jest/pull/10216#discussion_r446603676, I discovered that this parameter isn't actually used, and so ideally should be removed in Jest 27.
(this PR is based on the aforementioned PR, to skip having to deal with merge conflicts - I've also not made a changelog entry for the same reason).
Run the tests, see what breaks.
> fix(jasmine): remove unused options param

- CHANGELOG.md
- e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
- e2e/native-esm/__tests__/native-esm.test.js
- packages/jest-runtime/src/index.ts
> fix: throw correct error when loading ESM with `require`

- .github/ISSUE_TEMPLATE/question.md
- CHANGELOG.md
- e2e/__tests__/__snapshots__/customReporters.test.ts.snap
- e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
- packages/jest-changed-files/README.md
- packages/jest-cli/README.md
- packages/jest-config/src/__tests__/__snapshots__/normalize.test.ts.snap
- packages/jest-config/src/utils.ts
- packages/jest-core/src/getNoTestFoundVerbose.ts
- packages/jest-fake-timers/src/__tests__/__snapshots__/legacyFakeTimers.test.ts.snap
- packages/jest-fake-timers/src/legacyFakeTimers.ts
- packages/jest-runtime/src/index.ts
- packages/jest-snapshot/src/SnapshotResolver.ts
- packages/jest-snapshot/src/__tests__/__snapshots__/SnapshotResolver.test.ts.snap
- packages/jest/README.md
- website/versioned_docs/version-25.x/ExpectAPI.md
- website/versioned_docs/version-25.x/SnapshotTesting.md
- website/versioned_docs/version-26.x/SnapshotTesting.md
Following up #11256
/cc @slorber
Click around deploy preview
> chore(website): cleanup more links

- CHANGELOG.md
- website/docusaurus.config.js
The official representation of GitHub is 'GitHub' not 'Github'. This PR just replaces 'h' with 'H'.
> [website] chore: Replace 'Github' with 'GitHub'

- CHANGELOG.md
- website/src/pages/help.js
Remove a typo from the sentence inside this page: https://jestjs.io/help.
Ref. https://crowdin.com/translate/jest-v2/8188/en-ja?filter=basic&value=7
> docs: Remove a duplicated word in `website/src/pages/help.js`

- CHANGELOG.md
- packages/jest-core/src/cli/index.ts
- packages/jest-core/src/collectHandles.ts
- packages/jest-core/src/runJest.ts
Ref https://github.com/facebook/jest/issues/11275#issuecomment-815115650
/cc @jasnell, would love if you could confirm it was something like this you had in mind 🙂 
Not sure... I don't see issues using this or the current approach, but if this passes CI using a WeakRef seems better as we don't wanna keep the timer from being collected if possible.
> fix: use WeakRef for tracked handles

- .circleci/config.yml
We can simplify the current configuration of CircleCI by creating a `test-node` job that will take a `node-version` as a parameter. That way, we'll be able to easily add/remove node versions from the workflow with a matrix.
> chore: use a matrix to simplify test-node in CircleCI

- docs/GlobalAPI.md
- website/versioned_docs/version-26.x/GlobalAPI.md
Example codes for `test.concurrent.each` missed `async` keyword. This PR is to correct the example codes by adding the `async` keyword.
https://jestjs.io/docs/api#testconcurrenteachtablename-fn-timeout
https://jestjs.io/docs/next/api#testconcurrenteachtablename-fn-timeout
Start doc server and navigate to `Globals` chapter in `API` section. Check if example codes for `test.concurrent.each` have `async` keyword
> docs(globals-api): correct `test.concurrent.each` example to be async function

- website/docusaurus.config.js
Added a minor commit in order to fix the broken `Edit this page` link within docs.
Earlier, The <code><a href ='https://github.com/facebook/jest/blob/master/website/docusaurus.config.js'>docusaurus.config.js</a></code> was referring the Url to be of pattern: 
```
https://github.com/facebook/jest/edit/master/docs/${versionDocsDirPath}/${docPath}
```
which returned a 404 error while redirecting to Github. (Seems like was introduced within f73d5f6372a2570b7a38255bc0a69e0deacf67f5).
Rectified by editing the link to point the `versioned_docs` within the `website` directory rather than the `docs` directory. 
More clearly, 
Earlier: 
```
https://github.com/facebook/jest/edit/master/docs/${versionDocsDirPath}/${docPath}
```
Now:
```
https://github.com/facebook/jest/edit/master/website/${versionDoc …
```
> docs: Fix broken `Edit this page` link within documentation.

- CHANGELOG.md
- e2e/__tests__/watch-plugins.test.ts
- e2e/watch-plugins/cjs/__tests__/index.js
- e2e/watch-plugins/cjs/my-watch-plugin.cjs
- e2e/watch-plugins/cjs/package.json
- e2e/watch-plugins/js-type-module/__tests__/index.js
- e2e/watch-plugins/js-type-module/my-watch-plugin.js
- e2e/watch-plugins/js-type-module/package.json
- e2e/watch-plugins/js/__tests__/index.js
- e2e/watch-plugins/js/my-watch-plugin.js
- e2e/watch-plugins/js/package.json
- e2e/watch-plugins/mjs/__tests__/index.js
- e2e/watch-plugins/mjs/my-watch-plugin.mjs
- e2e/watch-plugins/mjs/package.json
- packages/jest-core/src/__tests__/watch.test.js
- packages/jest-core/src/watch.ts
- packages/jest-watcher/src/types.ts
Related to #11167 
Adjusted unit test and added e2e tests
Green CI
> feat(jest-core): add support for `watchPlugins` written in ESM

- CHANGELOG.md
- packages/pretty-format/src/__tests__/prettyFormat.test.ts
- packages/pretty-format/src/collections.ts
With current version of Jest, sparse arrays are handled as any other arrays when printing them. The resulting string replaces holes by `undefined`. This PR replaces the way sparse arrays are printed to show holes as holes while keeping undefined values as undefined values.
Tests have been added to check the new behaviour.
> feat: Better print for sparse arrays

- packages/pretty-format/src/index.ts
In short: Looks like the export of `Printer` was forgotten
When writing helper functions for custom plugin the printer type might be required for explicit signatures. For example, `printChildren` used by `DOMElement` already uses this type and I don't see a reason why userland implementations wouldn't be structured that way.
> feat(pretty-format): Export Printer type

- docs/Configuration.md
- website/versioned_docs/version-25.x/Configuration.md
- website/versioned_docs/version-26.x/Configuration.md
As discussed in #11293 this now describes (hopefully understandable) that the order of globs does matter. Added the note for `collectCoverageFrom` and `testMatch`.
Also fixed the link for micromatch.
Relates to #9464 and documents the new behaviour since jest 25 which is reported as a problem there in the initial description.
Maybe should be backported to the docs of jest 25 and 26
> docs: Add Note about order of glob patterns and fix link to micromatch

- CHANGELOG.md
- packages/jest-cli/src/init/__tests__/init.test.js
- packages/jest-cli/src/init/generateConfigFile.ts
https://github.com/facebook/jest/issues/11348
- `jest --init`
- reply positively to collect coverage question
- collectCoverage: true is present in jest config
> fix: missing collectCoverage after init (#11348)

- docs/CLI.md
- website/versioned_docs/version-25.x/CLI.md
- website/versioned_docs/version-26.x/CLI.md
It took me way too long to figure out the correct way to pass multiple regexps as an array. Update the docs with more information and examples.
Also clarify the testPathIgnorePatterns param accepts either a string or an array.
Ran examples I added to docs in my local environment.
> docs: Clarify CLI param testPathIgnorePatterns usage

- CHANGELOG.md
- docs/JestPlatform.md
- packages/expect/src/matchers.ts
- packages/expect/src/spyMatchers.ts
- packages/jest-config/src/ReporterValidationErrors.ts
- packages/jest-diff/src/index.ts
- packages/jest-get-type/src/__tests__/getType.test.ts
- packages/jest-get-type/src/index.ts
- packages/jest-matcher-utils/src/Replaceable.ts
- packages/jest-matcher-utils/src/index.ts
- packages/jest-snapshot/src/printSnapshot.ts
- packages/jest-validate/src/errors.ts
I tried using jest's `expect` together with snowpack (which converts everything to esm via rollup/plugin-commonjs), and it mostly worked okay except I was getting 
```TypeError: (0 , _jestGetType.default) is not a function```
I traced this down to a problem in how rollup/babel (or the combination of them) deal with mixed default and named exports.  The [rollup docs](https://rollupjs.org/guide/en/#outputexports) specifically talk about avoiding mixing the two, as well.  I see that all of the other jest packages (except for pretty-format, which also causes me errors) are using either default or named exports, so I chose to use named exports and convert `jest-get-type` to esm.
I built the code, copied all of the newly built files to my node_modules, and my error went away.  Also, existing …
> Move jest-get-type to ESM named exports

- CHANGELOG.md
- packages/jest-watcher/src/constants.ts
- packages/jest-watcher/src/lib/Prompt.ts
- packages/jest-watcher/src/lib/__tests__/prompt.test.ts
Added support for clearing the line when `<C-u>` is pressed in a watch mode pattern prompt. Resolves #11296 
Added a test case that tests this change. Wasn't able to test it manually because of the `jest-watch-typeahead` plugin that uses the published version of `jest-watcher` Refer: https://github.com/facebook/jest/issues/11296#issuecomment-829263394
> feat: add support for <C-u> to clear line in prompt

- CHANGELOG.md
- packages/jest-circus/src/formatNodeAssertErrors.ts
- packages/jest-circus/src/utils.ts
- packages/jest-config/src/Deprecated.ts
- packages/jest-core/src/runGlobalHook.ts
- packages/jest-diff/src/index.ts
- packages/jest-each/src/table/array.ts
- packages/jest-each/src/table/template.ts
- packages/jest-each/src/validation.ts
- packages/jest-jasmine2/src/expectationResultFactory.ts
- packages/jest-jasmine2/src/isError.ts
- packages/jest-leak-detector/src/index.ts
- packages/jest-matcher-utils/src/__tests__/index.test.ts
- packages/jest-matcher-utils/src/index.ts
- packages/jest-message-util/src/index.ts
- packages/jest-serializer/src/__tests__/index.test.ts
- packages/jest-snapshot/src/__tests__/mockSerializer.test.ts
- packages/jest-snapshot/src/printSnapshot.ts
- packages/jest-snapshot/src/utils.ts
- packages/jest-validate/src/utils.ts
Similarly to https://github.com/facebook/jest/pull/11359, I was trying to run `expect` in snowpack / webtestrunner, and got errors about 
```
TypeError: (0 , _prettyFormat.default) is not a function
```
This is because `pretty-format` exports both a default export and named exports.  This confuses babel+rollup, but it sounded like it was an intentional decision in https://github.com/facebook/jest/pull/10515 to keep both.  So, this PR does not remove the default export, but it changes all of the existing default imports throughout jest into named imports instead.  This seems to compile to cjs in such a way that rollup can successfully turn it back into esm.
Same as in #11359, I built jest and used it in my app, and the errors were resolved.
> Use named import from pretty-format, not default

- CHANGELOG.md
- crowdin.yaml
- website/i18n.js
- website/static/_redirects
Add French To website (Hello @slorber)
Nope
> docs: include French

- CHANGELOG.md
- packages/jest-each/src/__tests__/array.test.ts
- packages/jest-each/src/table/array.ts
fix #11356
fix #11363
Improved unit tests.
> fix(jest-each): fix placeholder interpolation

- CHANGELOG.md
- docs/ExpectAPI.md
- docs/JestPlatform.md
- packages/jest-diff/README.md
- packages/jest-diff/src/__tests__/__snapshots__/diff.test.ts.snap
- packages/jest-diff/src/__tests__/diff.test.ts
- packages/jest-diff/src/index.ts
- packages/jest-matcher-utils/src/__tests__/index.test.ts
- packages/jest-matcher-utils/src/index.ts
Similar to https://github.com/facebook/jest/pull/11359 and https://github.com/facebook/jest/pull/11360, I had problems when using jest-diff together with rollup's plugin-commonjs that turns cjs back into esm.  It appears that there was originally a [desire](https://github.com/facebook/jest/pull/8873#issuecomment-528568640) to use all named exports for jest-diff, but the move was delayed originally.  This PR removes the default export for `jest-diff` and exposes `diff()` as a named export.  I also did my best to find any usages of the default export in the documentation.
I tested this in my own snowpack app by building jest from my branch and replacing files in my `node_modules`.
> Use named exports for jest-diff

- docs/CLI.md
- website/versioned_docs/version-25.x/CLI.md
- website/versioned_docs/version-26.x/CLI.md
I noticed that `--filter` is missing from the website docs but it exists in `jest --help`. This PR fixes it.
> docs: Add --filter to the CLI doc

- CHANGELOG.md
- docs/Configuration.md
- website/versioned_docs/version-25.x/Configuration.md
- website/versioned_docs/version-26.x/Configuration.md
This PR clarifies the `timers` configuration property based on the conversation in #11370.
Fixes #11370
Documentation change only.
> docs: update timers config description

- docs/SnapshotTesting.md
Prettier is no longer required since https://github.com/facebook/jest/pull/7792 landed.
IMO the docs could now present `toMatchInlineSnapshot` more prominently and `toMatchSnapshot` only as a side note, but that's for another time.
> docs(snapshot): inline snapshots can be used without prettier

- e2e/__tests__/fatalWorkerError.test.ts
- packages/jest-worker/src/workers/ChildProcessWorker.ts
"Call retries were exceeded" is a bit obscure, with more information users could have an easier time tracking down bugs.
See also https://github.com/facebook/jest/issues/8769
Tests were updated
> Improve fatal worker error message

- CHANGELOG.md
- docs/GlobalAPI.md
- packages/jest-each/README.md
- packages/jest-each/src/__tests__/array.test.ts
- packages/jest-each/src/table/array.ts
- packages/jest-each/src/table/interpolation.ts
- packages/jest-each/src/table/template.ts
close #10394
`$variable`s are interpolated if the test name doesn't contain any of the `printf` placeholders (please refer to  https://github.com/facebook/jest/issues/10394#issuecomment-674341246 and https://github.com/facebook/jest/issues/10394#issuecomment-716202283).
Add unit tests.
> feat(jest-each): add support for interpolation with object properties

- .github/workflows/lock.yml
We have issues managing the issue tracker
Personally, a part of that is that notifications on really old issues pile up. I currently have over 500 unread notifications from this repo, and looking at the first 25, 6 of them are in closed issues/PRs, and the next 25 there are 8. I hope that by locking old threads there will be less noise and possibly easier to stay on top of issues as the (draining) distraction of comments on issues that have sometimes been closed for many years bubble up. Inbox zero is probably not realistic either way, but at least the hope is that new issues will also include full reproductions etc instead of a relatively common "this is still an issue"
I considered GH discussions but
1. I don't have access to enabling it
1. I'd probably still get notifications? I don't …
> chore: add GH Action to lock older closed issues and PRs

- packages/jest-snapshot/package.json
- yarn.lock
Fixes #10931.
Not sure why `@babel/core` would need to be a peer dep, we only parse and traverse some JS with all syntax enabled.
idk if we can test this without a beta release
> fix(jest-snapshot): @babel/core peer dependency warnings

- packages/expect/src/utils.ts
- packages/jest-core/src/getProjectDisplayName.ts
- packages/jest-fake-timers/src/legacyFakeTimers.ts
- Delete an unnecessary variable in the [utils.js](https://github.com/ftonato/jest/blob/4453901c0239939cc2c1c8b7c7d121447f6f5f52/packages/expect/src/utils.ts) file
- Use the nullish coalescing operator in the [getProjectDisplayName](https://github.com/ftonato/jest/blob/4453901c0239939cc2c1c8b7c7d121447f6f5f52/packages/jest-core/src/getProjectDisplayName.ts) method
- Refactor the method using [switch / case that all return the same value](https://github.com/ftonato/jest/blob/4453901c0239939cc2c1c8b7c7d121447f6f5f52/packages/expect/src/utils.ts#L352)
> refactor: use nullish coalescing operator on getProjectDisplayName

- CHANGELOG.md
- package.json
- packages/jest-validate/package.json
- packages/jest-validate/src/validateCLIOptions.ts
- yarn.lock
Fixes [#10004](https://github.com/facebook/jest/issues/10014).
As described in [this comment](https://github.com/facebook/jest/issues/10014#issuecomment-660536693), jest fails while running at machines with some non-English locales, like Turkish. 
This PR uses new `camelcase` version that offers a locale option to use while converting case, which makes default locale irrelevant; hence eliminates the problem.
Changes:
- Upgrade camelcase version for `jest-validate` workspace.
- Call `camelcase` function providing `en-US` as locale while validating CLI options.
Problem reproducible at machines using some certain locale. Following execution is on a Turkish locale machine:
```
D:\src\jest-test  (jest-test@1.0.0)
λ
node D:\src\jest\packages\jest-cli\bin\jest.js
● Unrecognized CLI Parameters: …
```
> Fix locale issue #10014

- CHANGELOG.md
- e2e/__tests__/customReporters.test.ts
- packages/jest-core/src/TestScheduler.ts
- packages/jest-core/src/__tests__/TestScheduler.test.js
- packages/jest-core/src/jest.ts
- packages/jest-core/src/runJest.ts
- packages/jest/src/jest.ts
Part of #11167
Integration test added
> feat: support reporters written in ESM

- packages/jest-haste-map/package.json
- yarn.lock
The current version of `fsevents` contains bug fixes for M1 Apple Silicon chips.
Specifically, a React Native app could not be started on M1 laptops in Xcode, because of the error message `Error: EMFILE: too many open files, watch`. Quite a few people are affected by it, see: https://github.com/facebook/metro/issues/668
I have isolated this change and verified that upgrading fsevents is the turnkey solution.
Fast refresh, the main feature relying on file watching operations, is still working just fine.
> Upgrade fsevents in jest-haste-map

- CHANGELOG.md
- packages/jest-snapshot/src/InlineSnapshots.ts
- packages/jest-snapshot/src/__tests__/InlineSnapshots.test.ts
ref #11386
This allows the require for prettier to fail, without bubbling up as an error.
An alternative to this approach would be to change `Defaults.ts` to attempt setting `prettier` to `require.resolve(prettier)` (or something), but I am not familiar enough with the codebase to know if that'd be OK. The current approach works, but may hide an accidental misconfiguration if a user manually sets `prettierPath`.
> feat: use fallback if prettier not found

- packages/jest-message-util/src/index.ts
> chore: minor simplify format results error

- CHANGELOG.md
- packages/pretty-format/README.md
- packages/pretty-format/src/__tests__/prettyFormat.test.ts
- packages/pretty-format/src/index.ts
- packages/pretty-format/src/types.ts
The new option `printBasicPrototype` determines whether or not the prototype should be printed for raw objects and arrays. By default this is `true`, which is backwards compatible.
I’m trying to create a snapshot matcher to test axios responses. In this case I’m interested pretty formatting JSON with custom matcher support, but I don’t want to print prototypes of raw objects or arrays, because I want to stay close to the original JSON data of the response.
```
yarn jest
```
> feat(pretty-print): add option `printBasicPrototype`

- CHANGELOG.md
- package.json
- packages/jest-environment-jsdom/package.json
- testSetupFile.js
- yarn.lock
`request` has been deprecated for a long time. While it's in semver range, I think we should bump it to "force" it for users
Green CI
> chore: bump jsdom
